import { performance } from 'node:perf_hooks';
import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { createDefaultManagerCharacter } from '../src/manager-character';
import { ensureAIManagerCharacters } from '../src/manager-ai-characters';
import { wireTrainingMedical } from '../src/training-medical';
import { wireManagerCareerDevelopment, annualManagerAging } from '../src/manager-career-development';
import { wireManagerSeasonEvolution } from '../src/manager-season-evolution';
import { institutionalState, tickPromises } from '../src/institutional-memory';
import { managerInteractionState, tickManagerInteractions } from '../src/manager-interactions';
import { wireManagerBackgroundInteractions } from '../src/manager-interaction-background';
import { tickManagerDevelopment } from '../src/manager-education-development';
import { tickManagerLongTermRuntime } from '../src/manager-longterm-runtime';
import { tickManagerEmployment } from '../src/manager-employment';
import { tickManagerPersonalFinance } from '../src/manager-personal-finance-v1';
import { tickFootballSchool } from '../src/football-school-v1';
import { tickFootballSchoolLegacy } from '../src/football-school-legacy-v1';
import { tickManagerJobInterviews } from '../src/manager-job-interview';
import { tickManagerJobMarket } from '../src/manager-job-market-v2';
import { tickTechnicalStaff } from '../src/technical-staff';
import { tickStaffCareer } from '../src/staff-career';
import { syncTechnicalStaffEffects } from '../src/technical-staff-effects';
import { tickRecruitmentAnalystEffects } from '../src/technical-staff-recruitment';
import { tickClubGovernance } from '../src/club-governance';
import { tickClubAssets } from '../src/club-assets-media';
import { tickCommercialEngine } from '../src/club-commercial-engine';
import { tickCommercialFinance } from '../src/club-commercial-finance';
import { tickTemporalProcesses } from '../src/temporal-processes';
import { tickHumanLife } from '../src/human-life';
import { tickSocialWorld } from '../src/social-world';
import { tickDressingRoom } from '../src/dressing-room';
import { tickManagerBiographyEffects } from '../src/manager-biography-daily';
import { executeTrainingDay } from '../src/training-engine';

const world=createBrazilRealWorld2026();
const club=world.clubs[0]!;
createDefaultManagerCharacter(world,club.id,'Profiler');
ensureAIManagerCharacters(world);
const date='2026-07-25';
const times:Array<[string,number]>=[];
function timed<T>(label:string,fn:()=>T):T{const t=performance.now();const r=fn();times.push([label,performance.now()-t]);return r;}

timed('wireTrainingMedical',()=>wireTrainingMedical(world));
timed('wireManagerCareerDevelopment',()=>wireManagerCareerDevelopment(world));
timed('wireManagerSeasonEvolution',()=>wireManagerSeasonEvolution(world));
timed('institutionalState',()=>institutionalState(world));
timed('managerInteractionState',()=>managerInteractionState(world));
timed('wireManagerBackgroundInteractions',()=>wireManagerBackgroundInteractions(world));
timed('annualManagerAging',()=>annualManagerAging(world,date));
timed('tickManagerDevelopment',()=>tickManagerDevelopment(world,date));
timed('tickManagerLongTermRuntime',()=>tickManagerLongTermRuntime(world,date));
timed('tickManagerEmployment',()=>tickManagerEmployment(world,date));
timed('tickManagerPersonalFinance',()=>tickManagerPersonalFinance(world,date));
timed('tickFootballSchool',()=>tickFootballSchool(world,date));
timed('tickFootballSchoolLegacy',()=>tickFootballSchoolLegacy(world,date));
timed('tickManagerJobInterviews',()=>tickManagerJobInterviews(world,date));
timed('tickManagerJobMarket',()=>tickManagerJobMarket(world,date));
timed('tickTechnicalStaff',()=>tickTechnicalStaff(world,date));
timed('tickStaffCareer',()=>tickStaffCareer(world,date));
timed('syncTechnicalStaffEffects',()=>syncTechnicalStaffEffects(world));
timed('tickRecruitmentAnalystEffects',()=>tickRecruitmentAnalystEffects(world,date));
timed('tickClubGovernance',()=>tickClubGovernance(world,date));
timed('tickClubAssets',()=>tickClubAssets(world,date));
timed('tickCommercialEngine',()=>tickCommercialEngine(world,date));
timed('tickCommercialFinance',()=>tickCommercialFinance(world,date));
timed('tickPromises',()=>tickPromises(world,date));
timed('tickTemporalProcesses',()=>tickTemporalProcesses(world,date));
timed('tickHumanLife',()=>tickHumanLife(world,date));
timed('tickSocialWorld',()=>tickSocialWorld(world,date));
timed('tickDressingRoom',()=>tickDressingRoom(world,date));
timed('tickManagerInteractions',()=>tickManagerInteractions(world,date));
timed('tickManagerBiographyEffects',()=>tickManagerBiographyEffects(world,date));
timed('executeTrainingDay',()=>executeTrainingDay(world,date,{daysToNextMatch:7,daysSinceLastMatch:undefined,matchesNext7:1}));

times.sort((a,b)=>b[1]-a[1]);
console.log('[profile] slowest daily subsystems');
for(const [label,ms] of times)console.log(`[profile] ${label.padEnd(34)} ${ms.toFixed(1)}ms`);
