import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { ensureActiveWorldFootballFoundation } from '../src/world-football-foundation-runtime-v1';
import { alias, footballClub, registerClubRecord } from '../src/world-football-data-v1';
import { loadPublicPeople2026 } from '../src/real-world-2026-loader-v1';
import { realPlayersV2 } from '../src/real-world-player-import-v2';
import { scoutingReport, toggleShortlist, isShortlisted } from '../src/scouting';
import { scoutingMarketStatus } from '../src/scouting-recruitment-bridge-v1';
import { snapshotWorldFoundation, restoreWorldFoundation } from '../src/world-save-schema-v2';

const world=createBrazilRealWorld2026();
ensureActiveWorldFootballFoundation(world);
const observer=world.clubs[0];if(!observer)throw new Error('Playable observer club missing');
const backgroundId='of-club-esp-background-united';
registerClubRecord(world,{id:backgroundId,name:'Background United CF',aliases:[alias('Background United'),alias('BU Madrid')],countryId:'ESP',cityName:'Madrid',active:true,stadiumIds:[],historicalNames:[],provenance:[{sourceId:'smoke-openfootball',sourceEntityId:'club-001',license:'CC0-1.0',historical:false,confidence:99}]});
const seed={externalIds:{wikidata:'Q999990001'},name:'Background Identity Player',dateOfBirth:'2001-04-05',position:'CM' as const,nationalityCountryIds:['ESP'],clubId:'BU Madrid',currentAbility:76,potentialAbility:84,provenance:[{source:'Wikidata',sourceId:'Q999990001',snapshotDate:'2026-08-26',confidence:99,license:'CC0'}]};
const loaded=loadPublicPeople2026(world,{players:[seed],staff:[]});
if(loaded.assignments.club.alias!==1)throw new Error(`Expected background club alias resolution, got ${JSON.stringify(loaded.assignments.club)}`);
const record=realPlayersV2(world).find(r=>r.externalIds.wikidata==='Q999990001');if(!record)throw new Error('Background real player missing after import');
const id=record.id;if(record.player.clubId!==backgroundId)throw new Error(`Canonical background club not assigned: ${record.player.clubId}`);
if(world.clubs.some(c=>c.id===backgroundId))throw new Error('Background club leaked into playable world.clubs and could create parallel fixtures');
if(world.clubs.some(c=>c.players.some(p=>p.id===id)))throw new Error('Background player leaked into playable club roster');
const report=scoutingReport(world,observer.id,id);if(!report||report.playerId!==id||report.clubId!==backgroundId)throw new Error('Scouting did not resolve canonical background player/club identity');
const market=scoutingMarketStatus(world,observer.id,id);if(market.kind!=='background-club'||market.transactionReady||market.sellerClubId!==backgroundId||market.sellerName!=='Background United CF')throw new Error(`Background market status invalid: ${JSON.stringify(market)}`);
if(!toggleShortlist(world,observer.id,id)||!isShortlisted(world,observer.id,id))throw new Error('Background player shortlist failed');
const save=snapshotWorldFoundation(world,{gameVersion:'background-club-smoke'}),restored=createBrazilRealWorld2026();ensureActiveWorldFootballFoundation(restored);restoreWorldFoundation(restored,save);
const restoredRecord=realPlayersV2(restored).find(r=>r.externalIds.wikidata==='Q999990001');if(restoredRecord?.id!==id||restoredRecord.player.clubId!==backgroundId)throw new Error('Save/load lost background player identity or club link');
if(footballClub(restored,backgroundId)?.name!=='Background United CF')throw new Error('Save/load lost canonical background club record');
if(!isShortlisted(restored,observer.id,id))throw new Error('Save/load lost shortlist link to background player');
const restoredMarket=scoutingMarketStatus(restored,observer.id,id);if(restoredMarket.kind!=='background-club'||restoredMarket.sellerClubId!==backgroundId)throw new Error('Save/load lost background market provenance');
console.log(`[smoke-background-club] player=${id} · club=${backgroundId} · alias=OK · playableLeak=0 · scouting=OK · market=background-club · shortlistSave=OK · identitySave=OK`);
