import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { createDefaultManagerCharacter } from '../src/manager-character';
import { emitWorldEvent } from '../src/event-bus';
import { generateSportNewsIssue } from '../src/sport-news-weekly-v1';
import { answerPressQuestion,createPressConferenceFromSportNews,restorePressRoom,snapshotPressRoom } from '../src/football-press-room-v1';
import { institutionalState } from '../src/institutional-memory';

const world=createBrazilRealWorld2026();
const club=world.clubs[0];
const manager=createDefaultManagerCharacter(world,club.id,'Treinador Diagnóstico');
institutionalState(world);
emitWorldEvent(world,{type:'MatchCompleted',date:`${world.season}-08-26`,clubIds:[club.id,world.clubs[1].id],actorIds:[manager.id],importance:5,summary:`${club.name} sofre derrota que aumenta a pressão sobre o trabalho.`,payload:{homeGoals:0,awayGoals:3}});
const issue=generateSportNewsIssue(world,`${world.season}-08-26`);
const conference=createPressConferenceFromSportNews(world,{clubId:club.id,issueId:issue.id,date:`${world.season}-08-26`});
if(!conference||!conference.questions.length)throw new Error('Press conference was not created from real Sport News issue');
const first=conference.questions[0];
if(!first.reporterId||!first.reporterName||!first.outlet)throw new Error('Question lacks persistent reporter identity');
if(!first.text.includes(first.reporterName)||!first.text.includes(first.outlet))throw new Error('Reporter identity is not visible in question text');
const initialCount=conference.questions.length;
if(!answerPressQuestion(world,conference.id,first.id,'dismiss'))throw new Error('Could not answer first press question');
const answer=conference.answers.find(x=>x.questionId===first.id);
if(!answer?.text||!answer.decisionLabel)throw new Error('Press answer lacks spoken text or semantic decision label');
const follow=conference.questions.find(x=>x.followUpOf===first.id);
if(!follow)throw new Error('High-pressure dismissive answer did not create reporter follow-up');
if(follow.reporterId!==first.reporterId||follow.reporterName!==first.reporterName||follow.outlet!==first.outlet)throw new Error('Follow-up changed reporter identity');
if((follow.depth??0)!==1||conference.questions.length!==initialCount+1)throw new Error('Follow-up depth/count contract broken');
if(!answerPressQuestion(world,conference.id,follow.id,'calm'))throw new Error('Could not answer reporter follow-up');
const followAnswer=conference.answers.find(x=>x.questionId===follow.id);
if(!followAnswer?.text)throw new Error('Follow-up answer lacks spoken text');
const snap=snapshotPressRoom(world);
restorePressRoom(world,snap);
const restored=snapshotPressRoom(world).conferences.find(x=>x.id===conference.id);
if(!restored)throw new Error('Conference disappeared after save/restore');
const rq=restored.questions.find(x=>x.id===follow.id),ra=restored.answers.find(x=>x.questionId===follow.id);
if(rq?.reporterId!==first.reporterId||!ra?.text)throw new Error('Reporter identity or answer text did not survive save/restore');
console.log(`[smoke-human-press] issue=${issue.id} · reporter=${first.reporterName}/${first.outlet} · initialQuestions=${initialCount} · followUp=OK · spokenAnswers=OK · save=OK · OK`);
