import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { humanDialogueDiagnostics,humanVoiceDiagnostics } from '../src/human-dialogue-diagnostics-v1';
import { boardConversation } from '../src/board-human-dialogue-v1';
import { emitWorldEvent,recentWorldEvents } from '../src/event-bus';
import { institutionalState,recentHumanConversations,snapshotInstitutionalState,restoreInstitutionalState } from '../src/institutional-memory';
import { managerInteractionState,pendingManagerInteractions,resolveManagerInteraction } from '../src/manager-interactions';
import { managerBehavior,recentManagerStatements,statementForInteraction } from '../src/manager-social-memory-v1';
import { captureResolvedManagerInteraction,wireManagerSocialMemoryRuntime } from '../src/manager-social-memory-runtime-v1';
import { serializeSave,restoreSave } from '../src/save-game';

const world=createBrazilRealWorld2026();
const club=world.clubs[0];
const player=club.players[0];
const coverage=humanDialogueDiagnostics();
if(!coverage.ok)throw new Error(`Dialogue coverage failed: ${JSON.stringify(coverage)}`);
const voice=humanVoiceDiagnostics(world);
if(!voice.ok)throw new Error(`Voice identity failed: ${JSON.stringify(voice)}`);
const board=boardConversation(world,club.id,'pressure',6);
if(board.length<6||new Set(board.map(x=>x.text)).size<4)throw new Error('Board conversation lacks usable variation');
institutionalState(world);
managerInteractionState(world);
wireManagerSocialMemoryRuntime(world);
const before=recentHumanConversations(world,100,club.id).length;
emitWorldEvent(world,{type:'DressingRoomConcern',date:`${world.season}-08-26`,clubIds:[club.id],playerIds:[player.id],importance:3,summary:`${player.name} pediu uma conversa sobre seu espaço no elenco.`,payload:{}});
const pending=pendingManagerInteractions(world,club.id)[0];
if(!pending)throw new Error('Real manager interaction engine did not open an interaction');
const behaviorBefore={...managerBehavior(world,pending.managerId)};
const opened=recentWorldEvents(world,20,{clubId:club.id,types:['ManagerInteractionOpened']})[0];
if(!opened?.payload.dialogueText||!opened?.payload.voiceSignature)throw new Error('Manager interaction opening was not enriched with human dialogue');
const chosen=pending.options.find(x=>x.id==='encourage')??pending.options[0];
if(!chosen||!resolveManagerInteraction(world,pending.id,chosen.id,`${world.season}-08-26`))throw new Error('Could not resolve real manager interaction');
const resolved=recentWorldEvents(world,20,{clubId:club.id,types:['ManagerInteractionResolved']})[0];
if(!resolved?.payload.reactionDialogue||!resolved?.payload.reactionVoiceSignature)throw new Error('Resolved interaction did not create a human reaction');
const resolvedInteraction=managerInteractionState(world).interactions.find(x=>x.id===pending.id);
if(!resolvedInteraction?.chosenText)throw new Error('Resolved interaction did not preserve exact manager spoken text');
const privateStatement=statementForInteraction(world,pending.managerId,pending.id);
if(!privateStatement)throw new Error('Resolved private interaction did not enter manager social memory');
if(privateStatement.text!==resolvedInteraction.chosenText||privateStatement.playerId!==player.id)throw new Error('Private social memory lost spoken text or player identity');
if(!privateStatement.behavior.includes('supportive'))throw new Error('Supportive private decision did not build supportive reputation');
if(managerBehavior(world,pending.managerId).supportive<=behaviorBefore.supportive)throw new Error('Private interaction did not alter manager behavioral reputation');
const countBeforeReplay=recentManagerStatements(world,pending.managerId,{interactionId:pending.id,limit:10}).length;
captureResolvedManagerInteraction(world,pending.id,`${world.season}-08-26`);
const countAfterReplay=recentManagerStatements(world,pending.managerId,{interactionId:pending.id,limit:10}).length;
if(countBeforeReplay!==1||countAfterReplay!==1)throw new Error('Private social-memory bridge is not idempotent');
const supportiveBeforeSave=managerBehavior(world,pending.managerId).supportive;
const restoredSaveWorld=restoreSave(serializeSave(world));
const restoredPrivateStatement=statementForInteraction(restoredSaveWorld,pending.managerId,pending.id);
if(!restoredPrivateStatement||restoredPrivateStatement.text!==privateStatement.text||restoredPrivateStatement.playerId!==privateStatement.playerId)throw new Error('Manager social memory did not survive canonical save/restore');
if(managerBehavior(restoredSaveWorld,pending.managerId).supportive!==supportiveBeforeSave)throw new Error('Manager behavioral reputation changed across save/restore');
emitWorldEvent(world,{type:'StaffConflict',date:`${world.season}-08-26`,actorIds:['staff-diag-1'],clubIds:[club.id],importance:3,summary:'O auxiliar discordou da distribuição de responsabilidades.',payload:{}});
emitWorldEvent(world,{type:'SupporterMoodChanged',date:`${world.season}-08-26`,clubIds:[club.id],importance:3,summary:'A torcida demonstrou impaciência após a última atuação.',payload:{}});
const after=recentHumanConversations(world,100,club.id);
const opening=after.find(x=>x.phase==='opening'&&x.playerId===player.id),reaction=after.find(x=>x.phase==='reaction'&&x.playerId===player.id),staff=after.find(x=>x.role==='staff'),supporter=after.find(x=>x.role==='supporter');
if(after.length<before+4||!opening||!reaction||!staff||!supporter)throw new Error('Human interaction network did not persist player, reaction, staff and supporter paths');
if(opening.speakerId!==reaction.speakerId||opening.voiceSignature!==reaction.voiceSignature)throw new Error('Speaker identity changed between opening and reaction');
const snap=snapshotInstitutionalState(world);
const expected=[opening,reaction,staff,supporter].map(x=>({text:x.text,signature:x.voiceSignature}));
restoreInstitutionalState(world,snap);
const restored=recentHumanConversations(world,100,club.id);
for(const x of expected)if(!restored.some(r=>r.text===x.text&&r.voiceSignature===x.signature))throw new Error('Human conversation network did not survive institutional save/restore');
const news=institutionalState(world).news;
console.log(`[smoke-human-dialogue] variants=${coverage.combinatorialVariants} · contexts=${coverage.contexts} · voices=${snap.humanVoices?.profiles.length??0} · boardLines=${board.length} · conversations=${after.length} · opening=OK · reaction=OK · privateMemory=OK · idempotency=OK · socialMemorySave=OK · staff=OK · supporters=OK · save=OK · identity=OK · news=${news.length} · OK`);
