import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { createDefaultManagerCharacter } from '../src/manager-character';
import { emitWorldEvent } from '../src/event-bus';
import { generateSportNewsIssue } from '../src/sport-news-weekly-v1';
import { answerPressQuestion,createPressConferenceFromSportNews,restorePressRoom,snapshotPressRoom } from '../src/football-press-room-v1';
import { managerBehavior,recentManagerStatements,statementRecall } from '../src/manager-social-memory-v1';
import { institutionalState } from '../src/institutional-memory';

const world=createBrazilRealWorld2026();
const club=world.clubs[0];
const manager=createDefaultManagerCharacter(world,club.id,'Treinador Diagnóstico');
institutionalState(world);
const behaviorBefore={...managerBehavior(world,manager.id)};
emitWorldEvent(world,{type:'MatchCompleted',date:`${world.season}-08-26`,clubIds:[club.id,world.clubs[1].id],actorIds:[manager.id],importance:5,summary:`${club.name} sofre derrota que aumenta a pressão sobre o trabalho.`,payload:{homeGoals:0,awayGoals:3}});
const issue=generateSportNewsIssue(world,`${world.season}-08-26`);
const conference=createPressConferenceFromSportNews(world,{clubId:club.id,issueId:issue.id,date:`${world.season}-08-26`});
if(!conference||!conference.questions.length)throw new Error('Press conference was not created from real Sport News issue');
const first=conference.questions[0];
if(!first.reporterId||!first.reporterName||!first.outlet)throw new Error('Question lacks persistent reporter identity');
if(!first.text.includes(first.reporterName)||!first.text.includes(first.outlet))throw new Error('Reporter identity is not visible in question text');
const initialCount=conference.questions.length;
if(!answerPressQuestion(world,conference.id,first.id,'dismiss'))throw new Error('Could not answer first press question');
const answer=conference.answers.find(x=>x.questionId===first.id);
if(!answer?.text||!answer.decisionLabel)throw new Error('Press answer lacks spoken text or semantic decision label');
const behaviorAfterDismiss=managerBehavior(world,manager.id);
if(behaviorAfterDismiss.evasive<=behaviorBefore.evasive)throw new Error('Dismissive answer did not increase evasive public reputation');
if(behaviorAfterDismiss.transparent>=behaviorBefore.transparent)throw new Error('Dismissive answer did not reduce transparency reputation');
const statements=recentManagerStatements(world,manager.id,{limit:10});
const statement=statements.find(x=>x.text===answer.text&&x.reporterId===first.reporterId);
if(!statement)throw new Error('Exact spoken answer was not stored in manager social memory');
const recalled=statementRecall(world,manager.id,statement.topic,first.reporterId);
if(recalled?.id!==statement.id)throw new Error('Reporter could not recall the manager statement it witnessed');
const follow=conference.questions.find(x=>x.followUpOf===first.id);
if(!follow)throw new Error('High-pressure dismissive answer did not create reporter follow-up');
if(follow.reporterId!==first.reporterId||follow.reporterName!==first.reporterName||follow.outlet!==first.outlet)throw new Error('Follow-up changed reporter identity');
if((follow.depth??0)!==1||conference.questions.length!==initialCount+1)throw new Error('Follow-up depth/count contract broken');
if(!follow.context.includes(answer.text))throw new Error('Reporter follow-up did not recover the exact previous manager statement');
if(!answerPressQuestion(world,conference.id,follow.id,'calm'))throw new Error('Could not answer reporter follow-up');
const followAnswer=conference.answers.find(x=>x.questionId===follow.id);
if(!followAnswer?.text)throw new Error('Follow-up answer lacks spoken text');
const snap=snapshotPressRoom(world);
if(!snap.socialMemory?.statements.some(x=>x.id===statement.id))throw new Error('PressRoom snapshot omitted manager social memory used by central beta save');
const savedEvasive=managerBehavior(world,manager.id).evasive;
restorePressRoom(world,snap);
const restored=snapshotPressRoom(world).conferences.find(x=>x.id===conference.id);
if(!restored)throw new Error('Conference disappeared after save/restore');
const rq=restored.questions.find(x=>x.id===follow.id),ra=restored.answers.find(x=>x.questionId===follow.id);
if(rq?.reporterId!==first.reporterId||!ra?.text)throw new Error('Reporter identity or answer text did not survive save/restore');
const restoredStatement=statementRecall(world,manager.id,statement.topic,first.reporterId);
if(restoredStatement?.text!==answer.text)throw new Error('Manager statement memory did not survive PressRoom restore');
if(managerBehavior(world,manager.id).evasive!==savedEvasive)throw new Error('Manager behavioral reputation did not survive PressRoom restore');
console.log(`[smoke-human-press] issue=${issue.id} · reporter=${first.reporterName}/${first.outlet} · initialQuestions=${initialCount} · followUp=OK · spokenAnswers=OK · socialMemory=OK · reputation=OK · centralSavePath=OK · OK`);
