import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { createDefaultManagerCharacter } from '../src/manager-character';
import { clubDressingRoom } from '../src/dressing-room';
import { recentWorldEvents } from '../src/event-bus';
import { createSaveSnapshot,restoreSave,serializeSave } from '../src/save-game';
import { deliverTeamTalk,openSquadMeeting,openTeamTalk,teamTalkHistory,wireTeamTalkRuntime } from '../src/team-talks-v1';

const world=createBrazilRealWorld2026(),club=world.clubs[0],opponent=world.clubs[1];
const manager=createDefaultManagerCharacter(world,club.id,'Treinador Team Talk');
wireTeamTalkRuntime(world);
const room=clubDressingRoom(world,club.id);
if(!room)throw new Error('Dressing room unavailable');
room.captaincy.captainId=club.players[0]?.id;
const first=openTeamTalk(world,{clubId:club.id,date:`${world.season}-08-26`,moment:'preMatch',opponentId:opponent.id,context:'Jogo importante diante de um adversário direto.'});
if(!first||first.managerId!==manager.id)throw new Error('Pre-match talk did not attach to canonical manager');
const moraleBefore=new Map(club.players.map(p=>[p.id,p.morale]));
if(!deliverTeamTalk(world,first.id,'encourage',`${world.season}-08-26`))throw new Error('Could not deliver pre-match talk');
if(first.status!=='resolved'||!first.managerText||first.reactions.length!==club.players.length)throw new Error('Resolved talk lacks spoken text or per-player reactions');
if(room.captaincy.captainId&&!first.captainResponse)throw new Error('Captain did not mediate team-talk response');
if(!first.reactions.some(r=>r.moraleDelta!==0)||!club.players.some(p=>p.morale!==moraleBefore.get(p.id)))throw new Error('Team talk produced no real player effect');
const second=openTeamTalk(world,{clubId:club.id,date:`${world.season}-08-27`,moment:'preMatch',opponentId:opponent.id,context:'Segundo jogo consecutivo com mensagem semelhante.'});
if(!second||!deliverTeamTalk(world,second.id,'encourage',`${world.season}-08-27`))throw new Error('Could not deliver repeated team talk');
if(!(second.repetitionFactor<first.repetitionFactor))throw new Error(`Repeated speech did not lose effect: first=${first.repetitionFactor} second=${second.repetitionFactor}`);
const meeting=openSquadMeeting(world,club.id,`${world.season}-08-28`,'O elenco foi reunido para tratar de concentração e comportamento coletivo.');
if(!meeting||!deliverTeamTalk(world,meeting.id,'demand',`${world.season}-08-28`))throw new Error('Squad meeting path failed');
const events=recentWorldEvents(world,30,{clubId:club.id,types:['TeamTalkDelivered','TeamMeetingHeld']});
if(events.filter(e=>e.type==='TeamTalkDelivered').length<2||!events.some(e=>e.type==='TeamMeetingHeld'))throw new Error('Team-talk lifecycle events were not emitted');
const base=createSaveSnapshot(world);
if(!base.teamTalks?.sessions.some(s=>s.id===meeting.id))throw new Error('Base V15 save omitted team talks');
const restored=restoreSave(serializeSave(world));
const restoredHistory=teamTalkHistory(restored,club.id,20);
if(!restoredHistory.some(s=>s.id===first.id&&s.managerText===first.managerText)||!restoredHistory.some(s=>s.id===meeting.id))throw new Error('Team talks did not survive save/restore');
const legacy=JSON.parse(JSON.stringify(base)) as any;delete legacy.teamTalks;
const legacyRestored=restoreSave(JSON.stringify(legacy));
if(teamTalkHistory(legacyRestored,club.id,10).length!==0)throw new Error('Old V15 save without teamTalks did not restore to empty compatible state');
console.log(`[smoke-team-talks] players=${club.players.length} · captain=${room.captaincy.captainId??'none'} · firstFactor=${first.repetitionFactor.toFixed(2)} · repeatedFactor=${second.repetitionFactor.toFixed(2)} · meetings=OK · events=OK · save=OK · legacy=OK · OK`);
