import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { humanDialogueDiagnostics,humanVoiceDiagnostics } from '../src/human-dialogue-diagnostics-v1';
import { boardConversation } from '../src/board-human-dialogue-v1';
import { emitWorldEvent,recentWorldEvents } from '../src/event-bus';
import { institutionalState,recentHumanConversations,snapshotInstitutionalState,restoreInstitutionalState } from '../src/institutional-memory';
import { managerInteractionState,pendingManagerInteractions,resolveManagerInteraction } from '../src/manager-interactions';

const world=createBrazilRealWorld2026();
const club=world.clubs[0];
const player=club.players[0];
const coverage=humanDialogueDiagnostics();
if(!coverage.ok)throw new Error(`Dialogue coverage failed: ${JSON.stringify(coverage)}`);
const voice=humanVoiceDiagnostics(world);
if(!voice.ok)throw new Error(`Voice identity failed: ${JSON.stringify(voice)}`);
const board=boardConversation(world,club.id,'pressure',6);
if(board.length<6||new Set(board.map(x=>x.text)).size<4)throw new Error('Board conversation lacks usable variation');
institutionalState(world);
managerInteractionState(world);
const before=recentHumanConversations(world,100,club.id).length;
emitWorldEvent(world,{type:'DressingRoomConcern',date:`${world.season}-08-26`,clubIds:[club.id],playerIds:[player.id],importance:3,summary:`${player.name} pediu uma conversa sobre seu espaço no elenco.`,payload:{}});
const pending=pendingManagerInteractions(world,club.id)[0];
if(!pending)throw new Error('Real manager interaction engine did not open an interaction');
const opened=recentWorldEvents(world,20,{clubId:club.id,types:['ManagerInteractionOpened']})[0];
if(!opened?.payload.dialogueText||!opened?.payload.voiceSignature)throw new Error('Manager interaction opening was not enriched with human dialogue');
const chosen=pending.options.find(x=>x.id==='encourage')??pending.options[0];
if(!chosen||!resolveManagerInteraction(world,pending.id,chosen.id,`${world.season}-08-26`))throw new Error('Could not resolve real manager interaction');
const resolved=recentWorldEvents(world,20,{clubId:club.id,types:['ManagerInteractionResolved']})[0];
if(!resolved?.payload.reactionDialogue||!resolved?.payload.reactionVoiceSignature)throw new Error('Resolved interaction did not create a human reaction');
emitWorldEvent(world,{type:'StaffConflict',date:`${world.season}-08-26`,actorIds:['staff-diag-1'],clubIds:[club.id],importance:3,summary:'O auxiliar discordou da distribuição de responsabilidades.',payload:{}});
emitWorldEvent(world,{type:'SupporterMoodChanged',date:`${world.season}-08-26`,clubIds:[club.id],importance:3,summary:'A torcida demonstrou impaciência após a última atuação.',payload:{}});
const after=recentHumanConversations(world,100,club.id);
const opening=after.find(x=>x.phase==='opening'&&x.playerId===player.id),reaction=after.find(x=>x.phase==='reaction'&&x.playerId===player.id),staff=after.find(x=>x.role==='staff'),supporter=after.find(x=>x.role==='supporter');
if(after.length<before+4||!opening||!reaction||!staff||!supporter)throw new Error('Human interaction network did not persist player, reaction, staff and supporter paths');
if(opening.speakerId!==reaction.speakerId||opening.voiceSignature!==reaction.voiceSignature)throw new Error('Speaker identity changed between opening and reaction');
const snap=snapshotInstitutionalState(world);
const expected=[opening,reaction,staff,supporter].map(x=>({text:x.text,signature:x.voiceSignature}));
restoreInstitutionalState(world,snap);
const restored=recentHumanConversations(world,100,club.id);
for(const x of expected)if(!restored.some(r=>r.text===x.text&&r.voiceSignature===x.signature))throw new Error('Human conversation network did not survive institutional save/restore');
const news=institutionalState(world).news;
console.log(`[smoke-human-dialogue] variants=${coverage.combinatorialVariants} · contexts=${coverage.contexts} · voices=${snap.humanVoices?.profiles.length??0} · boardLines=${board.length} · conversations=${after.length} · opening=OK · reaction=OK · staff=OK · supporters=OK · save=OK · identity=OK · news=${news.length} · OK`);
