import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { createDefaultManagerCharacter } from '../src/manager-character';
import { clubTraining, executeTrainingDay, setIndividualTraining, setMicrocyclePreset } from '../src/training-engine';
import { clearIndividualTraining } from '../src/training-individual-actions-v1';
import { clubDressingRoom } from '../src/dressing-room';
import { mentorshipTrainingModifier, wireTrainingMentorshipRuntime } from '../src/training-mentorship-runtime-v1';
import { createSaveSnapshot, restoreSave, serializeSave } from '../src/save-game';

const world=createBrazilRealWorld2026();
const club=world.clubs[0];
const player=club.players.find(p=>p.position!=='GK')??club.players[0];
const mentor=club.players.find(p=>p.id!==player?.id);
if(!player||!mentor)throw new Error('No player/mentor available for individual training smoke');
createDefaultManagerCharacter(world,club.id,'Treinador Training Smoke');
const room=clubDressingRoom(world,club.id);
if(!room)throw new Error('Dressing room unavailable for mentorship smoke');
room.mentorships.push({id:`smoke-mentor-${mentor.id}-${player.id}`,clubId:club.id,mentorId:mentor.id,menteeId:player.id,startedDate:`${world.season}-08-20`,strength:85,active:true,benefit:18,friction:0});
wireTrainingMentorshipRuntime(world);
const mentorModifier=mentorshipTrainingModifier(world,club.id,player.id);
if(!(mentorModifier>1))throw new Error(`Mentorship did not produce a positive development modifier: ${mentorModifier}`);
setMicrocyclePreset(world,club.id,'development');
setIndividualTraining(world,club.id,player.id,{focus:'weakFoot',intensity:'medium'},`${world.season}-08-26`);
const before=clubTraining(world,club.id)?.players.get(player.id);
if(!before?.individual||before.individual.focus!=='weakFoot')throw new Error('Individual plan was not created');
const progressBefore=before.individual.progress,weakFootBefore=before.weakFootProgress;
executeTrainingDay(world,`${world.season}-08-26`,{daysToNextMatch:4,daysSinceLastMatch:3,matchesNext7:1});
const after=clubTraining(world,club.id)?.players.get(player.id);
if(!after?.individual)throw new Error('Individual plan disappeared after training');
if(!(after.individual.progress>progressBefore))throw new Error(`Individual progress did not advance: ${progressBefore} -> ${after.individual.progress}`);
if(!(after.weakFootProgress>weakFootBefore))throw new Error(`Weak-foot progress did not advance: ${weakFootBefore} -> ${after.weakFootProgress}`);
if(!(after.individual.satisfaction>65.08))throw new Error(`Mentorship support did not improve training satisfaction: ${after.individual.satisfaction}`);
if(!(after.load.acuteLoad>0)&&!(after.load.chronicLoad>0))throw new Error('Individual training did not participate in load state');
const base=createSaveSnapshot(world);
const savedClub=base.training.clubs.find(([id])=>id===club.id)?.[1];
const savedPlayer=savedClub?.players.find(([id])=>id===player.id)?.[1];
if(!savedPlayer?.individual||savedPlayer.individual.focus!=='weakFoot')throw new Error('Save snapshot omitted individual plan');
const restored=restoreSave(serializeSave(world));
const restoredPlayer=clubTraining(restored,club.id)?.players.get(player.id);
if(!restoredPlayer?.individual)throw new Error('Individual plan did not survive save/restore');
if(restoredPlayer.individual.focus!==after.individual.focus)throw new Error('Individual focus changed after restore');
if(Math.abs(restoredPlayer.individual.progress-after.individual.progress)>1e-9)throw new Error('Individual progress changed after restore');
if(Math.abs(restoredPlayer.weakFootProgress-after.weakFootProgress)>1e-9)throw new Error('Weak-foot progress changed after restore');
if(Math.abs(restoredPlayer.load.acuteLoad-after.load.acuteLoad)>1e-9||Math.abs(restoredPlayer.load.chronicLoad-after.load.chronicLoad)>1e-9)throw new Error('Training load changed after restore');
setIndividualTraining(restored,club.id,player.id,{focus:'roleWork',intensity:'low'},`${world.season}-08-27`);
const replaced=clubTraining(restored,club.id)?.players.get(player.id)?.individual;
if(!replaced||replaced.focus!=='roleWork'||replaced.progress!==0)throw new Error('Replacing individual plan did not reset the new plan cleanly');
if(!clearIndividualTraining(restored,club.id,player.id))throw new Error('Could not cancel active individual plan');
if(clubTraining(restored,club.id)?.players.get(player.id)?.individual)throw new Error('Individual plan remained active after cancellation');
if(clearIndividualTraining(restored,club.id,player.id))throw new Error('Cancelling an already empty individual plan should return false');
console.log(`[smoke-training-individual] player=${player.name} · mentor=${mentor.name} · mentorModifier=${mentorModifier.toFixed(2)} · progress=${after.individual.progress.toFixed(2)} · weakFoot=${after.weakFootProgress.toFixed(2)} · load=${after.load.acuteLoad.toFixed(2)} · save=OK · replace=OK · cancel=OK · mentorship=OK · OK`);
