import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { ensureActiveWorldFootballFoundation } from '../src/world-football-foundation-runtime-v1';
import { alias, footballClub, registerClubRecord } from '../src/world-football-data-v1';
import { loadPublicPeople2026 } from '../src/real-world-2026-loader-v1';
import { realPlayersV2 } from '../src/real-world-player-import-v2';
import { scoutingReport, scoutingState, toggleShortlist, isShortlisted } from '../src/scouting';
import { completeBackgroundScoutedTransfer, scoutingMarketStatus } from '../src/scouting-recruitment-bridge-v1';
import { economyState, playerContract, recentTransfers } from '../src/economy';
import { snapshotWorldFoundation, restoreWorldFoundation } from '../src/world-save-schema-v2';

const world=createBrazilRealWorld2026();
ensureActiveWorldFootballFoundation(world);
const observer=world.clubs[0];if(!observer)throw new Error('Playable observer club missing');
const backgroundId='of-club-esp-background-united';
registerClubRecord(world,{id:backgroundId,name:'Background United CF',aliases:[alias('Background United'),alias('BU Madrid')],countryId:'ESP',cityName:'Madrid',active:true,stadiumIds:[],historicalNames:[],provenance:[{sourceId:'smoke-openfootball',sourceEntityId:'club-001',license:'CC0-1.0',historical:false,confidence:99}]});
const seed={externalIds:{wikidata:'Q999990001'},name:'Background Identity Player',dateOfBirth:'2001-04-05',position:'CM' as const,nationalityCountryIds:['ESP'],clubId:'BU Madrid',currentAbility:76,potentialAbility:84,provenance:[{source:'Wikidata',sourceId:'Q999990001',snapshotDate:'2026-08-26',confidence:99,license:'CC0'}]};
const loaded=loadPublicPeople2026(world,{players:[seed],staff:[]});
if(loaded.assignments.club.alias!==1)throw new Error(`Expected background club alias resolution, got ${JSON.stringify(loaded.assignments.club)}`);
const record=realPlayersV2(world).find(r=>r.externalIds.wikidata==='Q999990001');if(!record)throw new Error('Background real player missing after import');
const id=record.id;if(record.player.clubId!==backgroundId)throw new Error(`Canonical background club not assigned: ${record.player.clubId}`);
if(world.clubs.some(c=>c.id===backgroundId))throw new Error('Background club leaked into playable world.clubs and could create parallel fixtures');
if(world.clubs.some(c=>c.players.some(p=>p.id===id)))throw new Error('Background player leaked into playable club roster');
const report=scoutingReport(world,observer.id,id);if(!report||report.playerId!==id||report.clubId!==backgroundId)throw new Error('Scouting did not resolve canonical background player/club identity');
const market=scoutingMarketStatus(world,observer.id,id);if(market.kind!=='background-club'||!market.transactionReady||market.sellerClubId!==backgroundId||market.sellerName!=='Background United CF')throw new Error(`Background market status invalid: ${JSON.stringify(market)}`);
if(!toggleShortlist(world,observer.id,id)||!isShortlisted(world,observer.id,id))throw new Error('Background player shortlist failed');
const scout=scoutingState(world);scout.knowledge.set(`${observer.id}::${id}`,{observerClubId:observer.id,playerId:id,level:5,progress:100,lastSeenSeason:world.season,lastSeenRound:world.round});
const finance=economyState(world).finances.get(observer.id);if(!finance)throw new Error('Observer finance missing');finance.transferBudget=500_000_000;finance.balance=600_000_000;finance.wageBudget=Math.max(finance.wageBudget,5_000_000);
const completed=completeBackgroundScoutedTransfer(world,observer.id,id);if(!completed.ok||completed.proposal?.status!=='approved'||completed.negotiation?.status!=='accepted'||!completed.transfer)throw new Error(`Background transfer pipeline failed: ${JSON.stringify({ok:completed.ok,proposal:completed.proposal?.status,negotiation:completed.negotiation?.status,reason:completed.reason})}`);
if(completed.negotiation.sellerClubId!==backgroundId||completed.transfer.fromClubId!==backgroundId||completed.transfer.toClubId!==observer.id)throw new Error('Background seller identity was not preserved through negotiation and transfer history');
if(record.id!==id||record.player.clubId!==observer.id||!observer.players.some(p=>p.id===id))throw new Error('Transferred factual player did not retain identity in buyer roster');
if(world.clubs.some(c=>c.id===backgroundId))throw new Error('Background club became playable during transfer execution');
const contract=playerContract(world,id);if(contract?.clubId!==observer.id)throw new Error('Transferred player contract was not created for buyer');
const transfer=recentTransfers(world,10).find(t=>t.playerId===id&&t.kind==='transfer');if(!transfer||transfer.fromClubId!==backgroundId||transfer.toClubId!==observer.id)throw new Error('Economic transfer history missing canonical background seller');
const save=snapshotWorldFoundation(world,{gameVersion:'background-club-smoke'}),restored=createBrazilRealWorld2026();ensureActiveWorldFootballFoundation(restored);restoreWorldFoundation(restored,save);
const restoredObserver=restored.clubs.find(c=>c.id===observer.id);if(!restoredObserver)throw new Error('Restored observer club missing');
const restoredRecord=realPlayersV2(restored).find(r=>r.externalIds.wikidata==='Q999990001');if(restoredRecord?.id!==id||restoredRecord.player.clubId!==observer.id||!restoredObserver.players.some(p=>p.id===id))throw new Error('Save/load lost transferred factual player identity or buyer link');
if(footballClub(restored,backgroundId)?.name!=='Background United CF')throw new Error('Save/load lost canonical background club record');
if(restored.clubs.some(c=>c.id===backgroundId))throw new Error('Save/load promoted background club into playable world');
if(!isShortlisted(restored,observer.id,id))throw new Error('Save/load lost shortlist link to transferred factual player');
const restoredContract=playerContract(restored,id);if(restoredContract?.clubId!==observer.id||restoredContract.weeklyWage!==contract.weeklyWage)throw new Error('Save/load lost economic contract state');
const restoredTransfer=recentTransfers(restored,10).find(t=>t.playerId===id&&t.kind==='transfer');if(!restoredTransfer||restoredTransfer.fromClubId!==backgroundId||restoredTransfer.toClubId!==observer.id)throw new Error('Save/load lost economic transfer history');
const restoredMarket=scoutingMarketStatus(restored,observer.id,id);if(restoredMarket.kind!=='own-player')throw new Error(`Save/load did not expose transferred player as own-player: ${JSON.stringify(restoredMarket)}`);
console.log(`[smoke-background-club] player=${id} · club=${backgroundId} · alias=OK · playableLeak=0 · scouting=OK · committee=OK · negotiation=OK · transfer=OK · economySave=OK · identitySave=OK`);
