import { createBrazilRealWorld2026 } from '../src/real-world-v1';
import { humanDialogueDiagnostics,humanVoiceDiagnostics } from '../src/human-dialogue-diagnostics-v1';
import { boardConversation } from '../src/board-human-dialogue-v1';
import { emitWorldEvent,recentWorldEvents } from '../src/event-bus';
import { institutionalState,recentHumanConversations,snapshotInstitutionalState,restoreInstitutionalState } from '../src/institutional-memory';

const world=createBrazilRealWorld2026();
const club=world.clubs[0];
const player=club.players[0];
const coverage=humanDialogueDiagnostics();
if(!coverage.ok)throw new Error(`Dialogue coverage failed: ${JSON.stringify(coverage)}`);
const voice=humanVoiceDiagnostics(world);
if(!voice.ok)throw new Error(`Voice identity failed: ${JSON.stringify(voice)}`);
const board=boardConversation(world,club.id,'pressure',6);
if(board.length<6||new Set(board.map(x=>x.text)).size<4)throw new Error('Board conversation lacks usable variation');
const before=recentHumanConversations(world,50,club.id).length;
emitWorldEvent(world,{type:'DressingRoomConcern',date:`${world.season}-08-26`,clubIds:[club.id],playerIds:[player.id],importance:3,summary:`${player.name} pediu uma conversa sobre seu espaço no elenco.`,payload:{}});
emitWorldEvent(world,{type:'ManagerInteractionOpened',date:`${world.season}-08-26`,clubIds:[club.id],playerIds:[player.id],importance:3,summary:'Conversa individual necessária.',payload:{interactionId:'diag-human-1',kind:'performance'}});
const after=recentHumanConversations(world,50,club.id);
if(after.length<=before)throw new Error('Manager interaction did not create a human conversation');
const opened=recentWorldEvents(world,20,{clubId:club.id,types:['ManagerInteractionOpened']})[0];
if(!opened?.payload.dialogueText||!opened?.payload.voiceSignature)throw new Error('Manager interaction event was not enriched with human dialogue');
const snap=snapshotInstitutionalState(world);
const text=String(after[0].text),signature=String(after[0].voiceSignature);
restoreInstitutionalState(world,snap);
const restored=recentHumanConversations(world,50,club.id)[0];
if(!restored||restored.text!==text||restored.voiceSignature!==signature)throw new Error('Human conversation did not survive institutional save/restore');
const news=institutionalState(world).news;
console.log(`[smoke-human-dialogue] variants=${coverage.combinatorialVariants} · contexts=${coverage.contexts} · voices=${snap.humanVoices?.profiles.length??0} · boardLines=${board.length} · conversations=${after.length} · news=${news.length} · save=OK · identity=OK · OK`);
