import './beta-runtime-monitor-v1.css';

type BetaIssue={time:string;kind:'error'|'promise';message:string;source?:string};
const KEY='touchline-beta-runtime-issues-v1';
const VERSION='0.2.0-beta.1';
const read=():BetaIssue[]=>{try{return JSON.parse(sessionStorage.getItem(KEY)||'[]')}catch{return[]}};
const write=(rows:BetaIssue[])=>sessionStorage.setItem(KEY,JSON.stringify(rows.slice(-20)));
const record=(issue:BetaIssue)=>{const rows=read();rows.push(issue);write(rows);renderBadge()};
function renderBadge(){let badge=document.querySelector<HTMLButtonElement>('.beta-runtime-badge');if(!badge){badge=document.createElement('button');badge.className='beta-runtime-badge';badge.type='button';badge.addEventListener('click',openPanel);document.body.appendChild(badge)}const count=read().length;badge.innerHTML=`<b>BETA</b><span>${VERSION}${count?` · ${count} erro${count===1?'':'s'}`:' · runtime ok'}</span>`;badge.classList.toggle('has-errors',count>0)}
function esc(s:unknown){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
function diagnostics(){return{version:VERSION,userAgent:navigator.userAgent,viewport:`${innerWidth}x${innerHeight}`,url:location.href,issues:read(),time:new Date().toISOString()}}
function openPanel(){document.querySelector('.beta-runtime-panel')?.remove();const issues=read(),panel=document.createElement('section');panel.className='beta-runtime-panel';panel.innerHTML=`<header><div><span>THE TOUCHLINE</span><h3>Diagnóstico da Beta</h3></div><button data-beta-close>×</button></header><div class="beta-health ${issues.length?'warn':'ok'}"><b>${issues.length?'ATENÇÃO':'RUNTIME OK'}</b><span>${issues.length?`${issues.length} ocorrência(s) capturada(s) nesta sessão`:'Nenhum erro JavaScript capturado nesta sessão'}</span></div><div class="beta-runtime-list">${issues.length?issues.slice().reverse().map(i=>`<article><b>${esc(i.kind)}</b><span>${esc(new Date(i.time).toLocaleTimeString('pt-BR'))}</span><p>${esc(i.message)}</p>${i.source?`<small>${esc(i.source)}</small>`:''}</article>`).join(''):'<p class="beta-empty">Use a beta normalmente. Caso uma falha JavaScript ocorra, ela aparecerá aqui para facilitar a correção.</p>'}</div><footer><button data-beta-copy>COPIAR DIAGNÓSTICO</button><button data-beta-clear>LIMPAR LOG</button></footer>`;document.body.appendChild(panel);panel.querySelector('[data-beta-close]')?.addEventListener('click',()=>panel.remove());panel.querySelector('[data-beta-clear]')?.addEventListener('click',()=>{sessionStorage.removeItem(KEY);panel.remove();renderBadge()});panel.querySelector('[data-beta-copy]')?.addEventListener('click',async e=>{const btn=e.currentTarget as HTMLButtonElement;try{await navigator.clipboard.writeText(JSON.stringify(diagnostics(),null,2));btn.textContent='COPIADO ✓'}catch{btn.textContent='CÓPIA BLOQUEADA'}})}
window.addEventListener('error',e=>record({time:new Date().toISOString(),kind:'error',message:e.message||'Erro desconhecido',source:e.filename?`${e.filename}:${e.lineno}:${e.colno}`:undefined}));
window.addEventListener('unhandledrejection',e=>record({time:new Date().toISOString(),kind:'promise',message:e.reason instanceof Error?`${e.reason.name}: ${e.reason.message}`:String(e.reason)}));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',renderBadge,{once:true});else renderBadge();
