import type { World } from './engine';
import { clubGovernance } from './club-governance';
import { institutionalState } from './institutional-memory';
import { managerByClub } from './manager-character';
import { managerBehavior,recentManagerStatements } from './manager-social-memory-v1';
import { type DialogueTopic, type DialogueTone } from './human-dialogue-bank-v1';
import { speakAs } from './human-voice-state-v1';
export type BoardConversationReason='results'|'finance'|'transfer'|'contract'|'facilities'|'youth'|'pressure'|'promise'|'future';
const topic=(r:BoardConversationReason):DialogueTopic=>r==='results'?'result':r==='finance'?'finance':r==='transfer'?'transfer':r==='contract'?'contract':r==='facilities'?'facilities':r==='youth'?'youth':r==='promise'?'promise':r==='future'?'future':'pressure';
export function boardAccountabilityContext(world:World,clubId:string,reason:BoardConversationReason){const manager=managerByClub(world,clubId),managerId=manager?.id??`manager-${clubId}`,behavior=managerBehavior(world,managerId),recalled=recentManagerStatements(world,managerId,{topic:topic(reason),limit:8})[0];return{managerId,behavior,recalled,credibilityPressure:Math.max(0,(55-behavior.consistent)*.35)+Math.max(0,behavior.evasive-45)*.2+Math.max(0,behavior.confrontational-60)*.12}}
export function boardConversation(world:World,clubId:string,reason:BoardConversationReason,count=12){const club=world.clubs.find(c=>c.id===clubId),g=clubGovernance(world,clubId),p=institutionalState(world).pressure.get(clubId),president=g.board.find(x=>x.active&&x.role==='president'),speaker=president??g.board.find(x=>x.active&&x.role==='footballDirector'),accountability=boardAccountabilityContext(world,clubId,reason),load=Math.min(100,((p?.board??30)+(p?.financial??25)+g.crisis)/3+accountability.credibilityPressure);const tone:DialogueTone=load>=72||accountability.behavior.consistent<40?'firm':g.managerConfidence>=72&&accountability.behavior.confrontational<60?'supportive':load>=55?'cautious':'diplomatic',speakerId=speaker?.id??`board-${clubId}`,memory=accountability.recalled?`:${accountability.recalled.id}:${accountability.recalled.text}`:'';return Array.from({length:count},(_,i)=>speakAs(world,speakerId,speaker?.role==='president'?'president':'director',{audience:'board',topic:topic(reason),tone,club:club?.name,manager:speaker?.name,pressure:load,positive:g.managerConfidence>=65&&accountability.behavior.consistent>=45,seed:`board:${clubId}:${world.season}:${world.round}:${reason}${memory}`},i))}
export function boardHumanSummary(world:World,clubId:string){const g=clubGovernance(world,clubId),p=institutionalState(world).pressure.get(clubId),president=g.board.find(x=>x.active&&x.role==='president'),accountability=boardAccountabilityContext(world,clubId,'pressure');return{president:president?.name??'Presidência',managerConfidence:g.managerConfidence,boardStability:g.boardStability,crisis:g.crisis,mediaPressure:g.mediaPressure,externalPressure:p,managerBehavior:accountability.behavior,lastManagerStatement:accountability.recalled,credibilityPressure:Math.round(accountability.credibilityPressure),conversationTone:g.crisis>=70||accountability.behavior.consistent<35?'confrontational':g.managerConfidence>=70&&accountability.behavior.confrontational<60?'supportive':g.managerConfidence<40||accountability.behavior.evasive>70?'demanding':'professional'}}
