import './calendar-competition-v9.css';
import { sortedStandings, teamStrength, type Fixture, type World } from './engine';
import { dailyCalendar } from './daily-simulation';
import { userManager } from './manager-character';
import { crestMarkup } from './visual-identity-v1';
import { worldCore } from './world-core-v2';

let tab:'agenda'|'competition'|'results'='agenda';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const fmt=(iso:string)=>new Intl.DateTimeFormat('pt-BR',{weekday:'short',day:'2-digit',month:'short'}).format(new Date(`${iso}T12:00:00Z`)).replace('.','');
function world(){return window.__touchlineWorld as World|undefined}
function managedClub(w:World){const id=userManager(w)?.currentClubId??w.clubs[0]?.id;return w.clubs.find(c=>c.id===id)??w.clubs[0]}
function opponent(w:World,f:Fixture,id:string){return w.clubs.find(c=>c.id===(f.home===id?f.away:f.home))}
function resultLabel(f:Fixture,id:string){if(!f.played)return'';const gf=f.home===id?(f.homeGoals??0):(f.awayGoals??0),ga=f.home===id?(f.awayGoals??0):(f.homeGoals??0);return gf>ga?'V':gf===ga?'E':'D'}
function fixtureDate(w:World,f:Fixture){return dailyCalendar(w).matchDates.get(f.round)??dailyCalendar(w).date}
function nextFixture(w:World,id:string){return w.fixtures.find(f=>!f.played&&(f.home===id||f.away===id))}
function lastFixture(w:World,id:string){return [...w.fixtures].reverse().find(f=>f.played&&(f.home===id||f.away===id))}
function matchHero(w:World,id:string){const next=nextFixture(w,id),last=lastFixture(w,id),c=managedClub(w);if(next){const o=opponent(w,next,id)!;const home=next.home===id;return `<section class="cc-match-hero upcoming"><div class="cc-hero-meta"><span>PRÓXIMO COMPROMISSO</span><b>${fmt(fixtureDate(w,next))} · RODADA ${next.round}</b></div><div class="cc-versus"><div>${crestMarkup(c.name,'cc-crest-lg')}<b>${esc(c.name)}</b><small>${home?'MANDANTE':'VISITANTE'}</small></div><strong>VS</strong><div>${crestMarkup(o.name,'cc-crest-lg')}<b>${esc(o.name)}</b><small>${home?'VISITANTE':'MANDANTE'}</small></div></div><div class="cc-hero-foot"><span>Força ${Math.round(teamStrength(c).overall)} × ${Math.round(teamStrength(o).overall)}</span><button data-open-next>ABRIR PRÉ-JOGO</button></div></section>`}if(last){const o=opponent(w,last,id)!;return `<section class="cc-match-hero finished"><div class="cc-hero-meta"><span>ÚLTIMO JOGO</span><b>RODADA ${last.round} · ENCERRADO</b></div><div class="cc-versus"><div>${crestMarkup(c.name,'cc-crest-lg')}<b>${esc(c.name)}</b></div><strong>${last.home===id?last.homeGoals:last.awayGoals}<i>–</i>${last.home===id?last.awayGoals:last.homeGoals}</strong><div>${crestMarkup(o.name,'cc-crest-lg')}<b>${esc(o.name)}</b></div></div><div class="cc-hero-foot"><span>xG ${last.home===id?last.homeXg:last.awayXg??'—'} × ${last.home===id?last.awayXg:last.homeXg??'—'}</span><button data-open-last>ABRIR PÓS-JOGO</button></div></section>`}return '<section class="cc-match-hero"><div class="cc-empty">Nenhuma partida registrada.</div></section>'}
function agenda(w:World,id:string){const c=managedClub(w),fixtures=w.fixtures.filter(f=>f.home===id||f.away===id).slice(0,38),today=dailyCalendar(w).date;return `<div class="cc-agenda-grid">${matchHero(w,id)}<section class="cc-season"><header><div><span>TEMPORADA ${w.season}</span><h2>Agenda esportiva</h2></div><b>${fmt(today)}</b></header><div class="v2-calendar-list cc-fixture-list">${fixtures.map(f=>{const o=opponent(w,f,id)!;const date=fixtureDate(w,f),r=resultLabel(f,id),home=f.home===id;return `<article class="cc-fixture ${f.played?'played':'pending'} ${date===today?'today':''}"><time><b>${String(f.round).padStart(2,'0')}</b><span>${fmt(date)}</span></time>${crestMarkup(o.name,'cc-crest')}<div class="cc-fixture-main"><b>${esc(o.name)}</b><small>${home?'CASA':'FORA'} · Brasileirão</small></div><div class="cc-score">${f.played?`<b>${home?f.homeGoals:f.awayGoals}–${home?f.awayGoals:f.homeGoals}</b><span class="result ${r}">${r}</span>`:'<b>—</b><span>PENDENTE</span>'}</div></article>`}).join('')}</div></section><aside class="cc-side"><section><span>HOJE</span><b>${fmt(worldCore(w).date)}</b><small>dia ${dailyCalendar(w).daysAdvanced+1} da carreira</small></section><section><span>PRÓXIMA RODADA</span><b>${nextFixture(w,id)?.round??'—'}</b><small>${nextFixture(w,id)?fmt(fixtureDate(w,nextFixture(w,id)!)):'temporada concluída'}</small></section><section><span>FORÇA DO ELENCO</span><b>${Math.round(teamStrength(c).overall)}</b><small>índice do motor atual</small></section></aside></div>`}
function competition(w:World,id:string){const table=sortedStandings(w),pos=table.findIndex(r=>r.clubId===id)+1;return `<div class="cc-competition"><section class="cc-comp-hero"><div><span>BRASIL · PRIMEIRA DIVISÃO</span><h2>Campeonato Brasileiro</h2><p>Classificação calculada diretamente pelas partidas do universo ativo.</p></div><div><span>POSIÇÃO ATUAL</span><strong>${pos||'—'}º</strong><small>${w.standings[id]?.points??0} pontos</small></div></section><section class="cc-table"><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th><th>PTS</th></tr></thead><tbody>${table.map((r,i)=>{const c=w.clubs.find(x=>x.id===r.clubId)!;return `<tr class="${r.clubId===id?'managed':''}"><td>${i+1}</td><td><div>${crestMarkup(c.name,'cc-mini-crest')}<b>${esc(c.name)}</b></div></td><td>${r.played}</td><td>${r.wins}</td><td>${r.draws}</td><td>${r.losses}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gf-r.ga}</td><td><b>${r.points}</b></td></tr>`}).join('')}</tbody></table></section></div>`}
function results(w:World,id:string){const fixtures=w.fixtures.filter(f=>f.played&&(f.home===id||f.away===id)).reverse();return `<section class="cc-results"><header><span>ARQUIVO DA TEMPORADA</span><h2>Resultados e pós-jogo</h2></header>${fixtures.length?`<div class="v2-calendar-list cc-fixture-list">${fixtures.map(f=>{const o=opponent(w,f,id)!,home=f.home===id,r=resultLabel(f,id);return `<article class="cc-fixture played"><time><b>R${String(f.round).padStart(2,'0')}</b><span>${fmt(fixtureDate(w,f))}</span></time>${crestMarkup(o.name,'cc-crest')}<div class="cc-fixture-main"><b>${esc(o.name)}</b><small>${home?'CASA':'FORA'} · xG ${home?f.homeXg:f.awayXg??'—'} × ${home?f.awayXg:f.homeXg??'—'}</small></div><div class="cc-score"><b>${home?f.homeGoals:f.awayGoals}–${home?f.awayGoals:f.homeGoals}</b><span class="result ${r}">${r}</span></div></article>`}).join('')}</div>`:'<div class="cc-empty">Nenhuma partida disputada ainda.</div>'}</section>`}
function render(){const w=world(),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!host)return;const c=managedClub(w);if(!c)return;host.innerHTML=`<section class="calendar-competition-v9"><header class="cc-head"><div><span>TEMPORADA · ${esc(c.name.toUpperCase())}</span><h1>Calendário & Competições</h1><p>Agenda, classificação, pré-jogo e memória competitiva em um único centro esportivo.</p></div></header><nav class="cc-tabs"><button data-cc-tab="agenda" class="${tab==='agenda'?'active':''}">Agenda</button><button data-cc-tab="competition" class="${tab==='competition'?'active':''}">Competição</button><button data-cc-tab="results" class="${tab==='results'?'active':''}">Resultados</button></nav><div class="cc-pane">${tab==='agenda'?agenda(w,c.id):tab==='competition'?competition(w,c.id):results(w,c.id)}</div></section>`;bind(w,c.id);if(tab!=='competition')queueMicrotask(()=>document.dispatchEvent(new CustomEvent('touchline:view-rendered',{detail:{view:'calendar',calendarEnhanced:true}})))}
function clickMatchButton(which:'first'|'last'){const rows=[...document.querySelectorAll<HTMLButtonElement>('.v2-calendar-list .md-open')];const btn=which==='first'?rows.find(b=>b.textContent?.includes('PRÉ')):rows.slice().reverse().find(b=>b.textContent?.includes('MATCH'));btn?.click()}
function bind(w:World,id:string){document.querySelectorAll<HTMLButtonElement>('[data-cc-tab]').forEach(b=>b.onclick=()=>{tab=(b.dataset.ccTab as typeof tab)||'agenda';render()});document.querySelector('[data-open-next]')?.addEventListener('click',()=>clickMatchButton('first'));document.querySelector('[data-open-last]')?.addEventListener('click',()=>clickMatchButton('last'))}
document.addEventListener('touchline:view-rendered',e=>{const d=(e as CustomEvent).detail;if(d?.view==='calendar'&&!d?.calendarEnhanced)queueMicrotask(render)});
