import type { Club, Player, World } from './engine';
import { footballClub, footballCompetition, footballDataSnapshot } from './world-football-data-v1';
import { playerProfile } from './player-profile-v2';
import { queueWorldEvent } from './world-core-v2';

export type RegistrationWindow={opens:string;closes:string;phase:string};
export type SquadRegistrationRules={squadLimit:number;foreignLimit?:number;minHomegrown?:number;u21Exempt:boolean;maxChangesAfterPhase?:number;windows:RegistrationWindow[]};
export type SquadRegistration={competitionId:string;season:number;clubId:string;playerIds:string[];registeredAt:string;phase:string;changesUsed:number;locked:boolean};
type Runtime={entries:Map<string,SquadRegistration>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={entries:new Map()};states.set(w,s)}return s}
const key=(competitionId:string,season:number,clubId:string)=>`${competitionId}:${season}:${clubId}`;
function addMonths(iso:string,m:number){const d=new Date(`${iso}T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+m);return d.toISOString().slice(0,10)}
export function competitionRegistrationRules(w:World,competitionId:string,season=w.season):SquadRegistrationRules{const c=footballCompetition(w,competitionId);if(!c)throw new Error(`Unknown competition ${competitionId}`);const cross=c.rules.calendarPattern==='cross-year',start=`${season}-${String(c.rules.seasonStartMonth??(cross?8:2)).padStart(2,'0')}-01`,limit=c.rules.registrationSquadLimit??(c.scope==='continental'?25:30),foreign=c.rules.registrationForeignLimit;return{squadLimit:limit,foreignLimit:foreign,minHomegrown:c.scope==='continental'&&c.confederationId==='UEFA'?8:undefined,u21Exempt:true,maxChangesAfterPhase:c.scope==='continental'?3:undefined,windows:[{opens:addMonths(start,-1),closes:addMonths(start,1),phase:'initial'},{opens:addMonths(start,5),closes:addMonths(start,6),phase:'midseason'}]}}
function clubCountry(w:World,clubId:string){return footballClub(w,clubId)?.countryId}
function isHomegrown(w:World,p:Player,clubId:string){const country=clubCountry(w,clubId),profile=playerProfile(w,p.id);return !!country&&!!profile&&(profile.birthCountryId===country||profile.nationalities.includes(country))}
function isForeign(w:World,p:Player,clubId:string){return !isHomegrown(w,p,clubId)}
function score(p:Player){const roleBonus=p.position==='GK'?2:0;return p.currentAbility*1.1+p.potentialAbility*.08+p.condition*.05+p.morale*.03+roleBonus}
function pickSquad(w:World,club:Club,rules:SquadRegistrationRules){const sorted=[...club.players].sort((a,b)=>score(b)-score(a)),picked:Player[]=[];const add=(p:Player)=>{if(!picked.some(x=>x.id===p.id)&&picked.length<rules.squadLimit)picked.push(p)};for(const pos of ['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'] as const){const candidates=sorted.filter(p=>p.position===pos);for(const p of candidates.slice(0,pos==='GK'?2:1))add(p)}for(const p of sorted)add(p);if(rules.foreignLimit!==undefined){const foreign=picked.filter(p=>isForeign(w,p,club.id));if(foreign.length>rules.foreignLimit){const toRemove=new Set(foreign.slice(rules.foreignLimit).map(p=>p.id));for(let i=picked.length-1;i>=0;i--)if(toRemove.has(picked[i].id))picked.splice(i,1);for(const p of sorted.filter(p=>!isForeign(w,p,club.id)))add(p)}}if(rules.minHomegrown){const hg=picked.filter(p=>isHomegrown(w,p,club.id));if(hg.length<rules.minHomegrown){for(const p of sorted.filter(p=>isHomegrown(w,p,club.id)&&!picked.some(x=>x.id===p.id))){const replace=picked.map((x,i)=>({x,i})).filter(v=>!isHomegrown(w,v.x,club.id)).sort((a,b)=>score(a.x)-score(b.x))[0];if(!replace)break;picked[replace.i]=p;if(picked.filter(x=>isHomegrown(w,x,club.id)).length>=rules.minHomegrown)break}}}return picked.map(p=>p.id)}
export function ensureSquadRegistration(w:World,competitionId:string,clubId:string,season=w.season,date=`${season}-08-01`){const s=state(w),k=key(competitionId,season,clubId),existing=s.entries.get(k);if(existing)return existing;const club=w.clubs.find(c=>c.id===clubId);if(!club)throw new Error(`Runtime club missing ${clubId}`);const rules=competitionRegistrationRules(w,competitionId,season),entry:SquadRegistration={competitionId,season,clubId,playerIds:pickSquad(w,club,rules),registeredAt:date,phase:'initial',changesUsed:0,locked:false};s.entries.set(k,entry);queueWorldEvent(w,{date,type:'CompetitionSquadRegistered',scope:'club',entityIds:[clubId,competitionId],importance:2,payload:{season,count:entry.playerIds.length,phase:entry.phase}});return entry}
export function registeredPlayers(w:World,competitionId:string,clubId:string,season=w.season){const e=ensureSquadRegistration(w,competitionId,clubId,season);return new Set(e.playerIds)}
export function eligibleClubForCompetition(w:World,club:Club,competitionId:string,season=w.season){const rules=competitionRegistrationRules(w,competitionId,season),registered=registeredPlayers(w,competitionId,club.id,season);const players=club.players.filter(p=>registered.has(p.id)||(rules.u21Exempt&&p.age<=21));return players.length>=11?{...club,players}:club}
export function replaceRegisteredPlayer(w:World,input:{competitionId:string;clubId:string;season?:number;outPlayerId:string;inPlayerId:string;date:string;reason:string}){const season=input.season??w.season,e=ensureSquadRegistration(w,input.competitionId,input.clubId,season,input.date),rules=competitionRegistrationRules(w,input.competitionId,season);if(e.locked)throw new Error('Squad registration is locked');if(rules.maxChangesAfterPhase!==undefined&&e.changesUsed>=rules.maxChangesAfterPhase)throw new Error('Registration change limit reached');const idx=e.playerIds.indexOf(input.outPlayerId);if(idx<0)throw new Error('Outgoing player not registered');if(e.playerIds.includes(input.inPlayerId))return e;e.playerIds[idx]=input.inPlayerId;e.changesUsed++;queueWorldEvent(w,{date:input.date,type:'CompetitionSquadRegistrationChanged',scope:'club',entityIds:[input.clubId,input.competitionId,input.outPlayerId,input.inPlayerId],importance:2,payload:{reason:input.reason,changesUsed:e.changesUsed}});return e}
export function seedCompetitionRegistrations(w:World,season=w.season){const snap=footballDataSnapshot(w);let created=0;for(const m of snap.memberships.filter(m=>Number(m.season)===season&&m.teamKind==='club'&&['participant','qualified'].includes(m.status))){if(!w.clubs.some(c=>c.id===m.teamId)||!footballCompetition(w,m.competitionId))continue;const k=key(m.competitionId,season,m.teamId);if(state(w).entries.has(k))continue;ensureSquadRegistration(w,m.competitionId,m.teamId,season);created++}return{created,total:state(w).entries.size}}
export type SquadRegistrationSnapshot={entries:[string,SquadRegistration][]};export function snapshotSquadRegistrations(w:World):SquadRegistrationSnapshot{return{entries:[...state(w).entries].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}export function restoreSquadRegistrations(w:World,x:SquadRegistrationSnapshot){states.set(w,{entries:new Map((x?.entries??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
