import type { World } from './engine';
import { queueWorldEvent } from './world-core-v2';

export type ClubMomentType='title'|'promotion'|'relegation'|'record'|'derby'|'upset'|'comeback'|'transfer'|'manager'|'stadium'|'financial'|'supporter'|'era';
export type MemoryAudience={supporters:number;board:number;media:number};
export type ClubHistoricalMoment={id:string;clubId:string;date:string;season:number;type:ClubMomentType;importance:number;sentiment:'positive'|'negative'|'mixed';summary:string;competitionId?:string;matchId?:string;entityIds:string[];payload:Record<string,unknown>;audience:MemoryAudience;permanent:boolean;memoryStrength:number};
export type TransferHistoryRecord={id:string;date:string;season:number;playerId:string;fromClubId?:string;toClubId?:string;fee:number;kind:'permanent'|'loan'|'free'|'release';source?:string};
export type ManagerAchievementRecord={id:string;date:string;season:number;managerId:string;clubId:string;competitionId?:string;kind:'title'|'promotion'|'record'|'award';weight:number;summary:string};
export type ClubInstitutionalMemorySnapshot={moments:ClubHistoricalMoment[];transfers:TransferHistoryRecord[];managerAchievements:ManagerAchievementRecord[]};
type State=ClubInstitutionalMemorySnapshot;
const states=new WeakMap<World,State>();
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function state(w:World){let s=states.get(w);if(!s){s={moments:[],transfers:[],managerAchievements:[]};states.set(w,s)}return s}
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
function seasonFrom(date:string,fallback:number){const y=Number(date.slice(0,4));return Number.isFinite(y)&&y>0?y:fallback}
export function rememberClubMoment(w:World,input:Omit<ClubHistoricalMoment,'id'|'season'|'memoryStrength'> & {id?:string;season?:number;memoryStrength?:number}){const s=state(w),id=input.id??`club-memory-${hash(`${input.clubId}:${input.date}:${input.type}:${input.summary}:${input.competitionId??''}`)}`;const existing=s.moments.find(x=>x.id===id);if(existing)return existing;const importance=clamp(input.importance),row:ClubHistoricalMoment={...input,id,season:input.season??seasonFrom(input.date,w.season),importance,memoryStrength:clamp(input.memoryStrength??(input.permanent?100:Math.max(20,importance))),entityIds:[...new Set(input.entityIds??[])]};s.moments.push(row);queueWorldEvent(w,{date:row.date,type:'ClubHistoricalMomentCreated',scope:'club',entityIds:[row.clubId,...row.entityIds],importance:Math.max(1,Math.round(row.importance/15)),payload:{momentId:row.id,type:row.type,sentiment:row.sentiment,memoryStrength:row.memoryStrength,permanent:row.permanent}});return row}
export function clubHistoricalMoments(w:World,clubId:string){return state(w).moments.filter(x=>x.clubId===clubId).sort((a,b)=>b.date.localeCompare(a.date)||b.importance-a.importance)}
export function strongestClubMemories(w:World,clubId:string,limit=20){return clubHistoricalMoments(w,clubId).sort((a,b)=>(b.memoryStrength*b.importance)-(a.memoryStrength*a.importance)).slice(0,limit)}
export function decayClubMemories(w:World,years=1){for(const m of state(w).moments){if(m.permanent)continue;const audience=(m.audience.supporters+m.audience.board+m.audience.media)/300,rate=(1.8+Math.max(0,65-m.importance)/22)*(1-audience*.42);m.memoryStrength=clamp(m.memoryStrength-rate*Math.max(1,years))}return state(w).moments.filter(m=>m.memoryStrength>=8).length}
export function recordTransferHistory(w:World,input:Omit<TransferHistoryRecord,'id'|'season'> & {id?:string;season?:number}){const s=state(w),id=input.id??`transfer-${hash(`${input.date}:${input.playerId}:${input.fromClubId??''}:${input.toClubId??''}:${input.fee}`)}`;let row=s.transfers.find(x=>x.id===id);if(row)return row;row={...input,id,season:input.season??seasonFrom(input.date,w.season),fee:Math.max(0,input.fee)};s.transfers.push(row);for(const clubId of [row.fromClubId,row.toClubId].filter(Boolean) as string[])rememberClubMoment(w,{clubId,date:row.date,type:'transfer',importance:row.fee>=50_000_000?72:row.fee>=20_000_000?55:35,sentiment:clubId===row.toClubId?'positive':'mixed',summary:clubId===row.toClubId?'Contratação de grande impacto registrada.':'Venda relevante registrada.',entityIds:[row.playerId],payload:{transferId:row.id,fee:row.fee,fromClubId:row.fromClubId,toClubId:row.toClubId},audience:{supporters:65,board:90,media:75},permanent:row.fee>=50_000_000});return row}
export function clubTransferHistory(w:World,clubId:string){return state(w).transfers.filter(x=>x.fromClubId===clubId||x.toClubId===clubId).sort((a,b)=>a.date.localeCompare(b.date))}
export function recordManagerAchievement(w:World,input:Omit<ManagerAchievementRecord,'id'|'season'> & {id?:string;season?:number}){const s=state(w),id=input.id??`manager-achievement-${hash(`${input.managerId}:${input.clubId}:${input.date}:${input.kind}:${input.competitionId??''}`)}`;const existing=s.managerAchievements.find(x=>x.id===id);if(existing)return existing;const row:ManagerAchievementRecord={...input,id,season:input.season??seasonFrom(input.date,w.season)};s.managerAchievements.push(row);rememberClubMoment(w,{clubId:row.clubId,date:row.date,type:'manager',importance:clamp(row.weight),sentiment:'positive',summary:row.summary,competitionId:row.competitionId,entityIds:[row.managerId],payload:{achievementId:row.id,kind:row.kind},audience:{supporters:78,board:92,media:82},permanent:row.kind==='title'&&row.weight>=75});return row}
export function managerAchievements(w:World,clubId?:string){return state(w).managerAchievements.filter(x=>!clubId||x.clubId===clubId)}
export function snapshotClubInstitutionalMemory(w:World):ClubInstitutionalMemorySnapshot{const s=state(w);return JSON.parse(JSON.stringify(s))}
export function restoreClubInstitutionalMemory(w:World,x?:ClubInstitutionalMemorySnapshot){states.set(w,{moments:(x?.moments??[]).map(v=>({...v,entityIds:[...v.entityIds],payload:{...v.payload},audience:{...v.audience}})),transfers:(x?.transfers??[]).map(v=>({...v})),managerAchievements:(x?.managerAchievements??[]).map(v=>({...v}))})}
