import type { World } from './engine';
import { footballDataSnapshot } from './world-football-data-v1';
import { deepClubRecordBook } from './club-record-book-v2';
import { clubHistoricalMoments, snapshotClubInstitutionalMemory } from './club-institutional-memory-v1';
import { matchdayCommercialHistory } from './club-commercial-finance';
import { WORLD_SAVE_SCHEMA_VERSION, snapshotWorldFoundation, validateWorldFoundationSave } from './world-save-schema-v2';

export type InstitutionalMemoryDiagnostic={id:string;ok:boolean;detail:string};
export function diagnoseClubInstitutionalMemory(w:World,clubId?:string){const checks:InstitutionalMemoryDiagnostic[]=[],id=clubId??footballDataSnapshot(w).clubs[0]?.id;if(!id)return{ok:true,checks:[{id:'club-available',ok:true,detail:'no canonical clubs loaded'}]};const records=deepClubRecordBook(w,id),moments=clubHistoricalMoments(w,id),snapshot=snapshotClubInstitutionalMemory(w),matchdays=matchdayCommercialHistory(w,id);checks.push({id:'record-club',ok:records.clubId===id,detail:`club=${records.clubId}`});checks.push({id:'streak-nonnegative',ok:[records.longestWinning,records.longestUnbeaten,records.longestLosing,records.longestWinless].every(x=>x.length>=0),detail:`W=${records.longestWinning.length},U=${records.longestUnbeaten.length},L=${records.longestLosing.length},WL=${records.longestWinless.length}`});checks.push({id:'drought-nonnegative',ok:records.currentTitleDrought>=0&&records.longestTitleDrought>=0,detail:`current=${records.currentTitleDrought},longest=${records.longestTitleDrought}`});checks.push({id:'moment-range',ok:moments.every(x=>x.importance>=0&&x.importance<=100&&x.memoryStrength>=0&&x.memoryStrength<=100),detail:`moments=${moments.length}`});checks.push({id:'moment-unique',ok:new Set(snapshot.moments.map(x=>x.id)).size===snapshot.moments.length,detail:`moments=${snapshot.moments.length}`});checks.push({id:'transfer-unique',ok:new Set(snapshot.transfers.map(x=>x.id)).size===snapshot.transfers.length,detail:`transfers=${snapshot.transfers.length}`});checks.push({id:'commercial-nonnegative',ok:matchdays.every(x=>x.attendance>=0&&x.totalRevenue>=0),detail:`matchdays=${matchdays.length}`});const save=snapshotWorldFoundation(w),validation=validateWorldFoundationSave(save);checks.push({id:'save-current-schema',ok:save.schemaVersion===WORLD_SAVE_SCHEMA_VERSION,detail:`schema=${save.schemaVersion}`});checks.push({id:'save-valid',ok:validation.ok,detail:validation.issues.join('; ')||'ok'});return{ok:checks.every(x=>x.ok),checks,records,moments:Math.min(moments.length,9999)}}
