import type { World } from './engine';
import { footballCompetition, footballDataSnapshot } from './world-football-data-v1';
import { matchArchive } from './match-season-history-v2';

export type ClubReputationProfile={clubId:string;historical:number;current:number;continental:number;domestic:number;squad:number;overall:number;tier:'local'|'national'|'continental'|'elite'|'global'};
export type ClubRivalryProfile={clubAId:string;clubBId:string;score:number;geographic:number;history:number;competitive:number;balance:number;matches:number;label:'none'|'competitive'|'derby'|'major'|'historic'};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function titleWeight(w:World,competitionId:string){const c=footballCompetition(w,competitionId);if(!c)return 3;if(c.scope==='continental')return c.id.includes('uefa-cl')||c.id.includes('libertadores')?10:6;if(c.scope==='international')return 12;if(c.kind==='league'&&c.level===1)return 6;if(c.kind==='cup')return 3;return 2}
function clubRecord(w:World,id:string){return footballDataSnapshot(w).clubs.find(c=>c.id===id)}
function titleRows(w:World,id:string){return footballDataSnapshot(w).titles.filter(t=>t.teamKind==='club'&&t.teamId===id)}
function recentMatches(w:World,id:string,years=3){const from=w.season-years+1;return matchArchive(w).filter(m=>m.season>=from&&(m.homeClubId===id||m.awayClubId===id))}
function squadScore(w:World,id:string){const c=w.clubs.find(c=>c.id===id);if(!c?.players.length)return 45;const top=[...c.players].sort((a,b)=>b.currentAbility-a.currentAbility).slice(0,18);return clamp(top.reduce((a,p)=>a+p.currentAbility,0)/Math.max(1,top.length))}
function divisionScore(w:World,id:string){const snap=footballDataSnapshot(w),m=snap.memberships.filter(x=>x.teamId===id&&x.teamKind==='club'&&Number(x.season)===w.season).map(x=>footballCompetition(w,x.competitionId)).filter(Boolean);const top=m.filter(c=>c?.scope==='domestic'&&c.kind==='league').sort((a,b)=>(a!.level??99)-(b!.level??99))[0];if(!top)return 45;return clamp(82-(top.level??4)*10)}
export function clubReputation(w:World,clubId:string):ClubReputationProfile{const titles=titleRows(w,clubId),historical=clamp(28+titles.reduce((a,t)=>a+titleWeight(w,t.competitionId)*Math.max(.35,1-Math.max(0,w.season-Number(t.season))*.012),0)),continental=clamp(25+titles.filter(t=>footballCompetition(w,t.competitionId)?.scope==='continental').reduce((a,t)=>a+titleWeight(w,t.competitionId)*2,0)),domestic=divisionScore(w,clubId),squad=squadScore(w,clubId),recent=recentMatches(w,clubId),points=recent.reduce((a,m)=>{const home=m.homeClubId===clubId,gf=home?m.homeGoals:m.awayGoals,ga=home?m.awayGoals:m.homeGoals;return a+(gf>ga?3:gf===ga?1:0)},0),form=recent.length?clamp(points/(recent.length*3)*100):50,current=clamp(domestic*.32+squad*.36+form*.32),overall=clamp(historical*.34+current*.36+continental*.2+domestic*.1),tier=overall>=88?'global':overall>=78?'elite':overall>=66?'continental':overall>=52?'national':'local';return{clubId,historical:Number(historical.toFixed(1)),current:Number(current.toFixed(1)),continental:Number(continental.toFixed(1)),domestic:Number(domestic.toFixed(1)),squad:Number(squad.toFixed(1)),overall:Number(overall.toFixed(1)),tier}}
function allPairMatches(w:World,a:string,b:string){const imported=footballDataSnapshot(w).matches.filter(m=>(m.homeTeamId===a&&m.awayTeamId===b)||(m.homeTeamId===b&&m.awayTeamId===a)).map(m=>({home:m.homeTeamId,away:m.awayTeamId,hg:m.homeGoals,ag:m.awayGoals,stage:m.stage})),sim=matchArchive(w).filter(m=>(m.homeClubId===a&&m.awayClubId===b)||(m.homeClubId===b&&m.awayClubId===a)).map(m=>({home:m.homeClubId,away:m.awayClubId,hg:m.homeGoals,ag:m.awayGoals,stage:undefined as string|undefined}));return[...imported,...sim]}
export function clubRivalry(w:World,clubAId:string,clubBId:string):ClubRivalryProfile{if(clubAId===clubBId)return{clubAId,clubBId,score:0,geographic:0,history:0,competitive:0,balance:0,matches:0,label:'none'};const a=clubRecord(w,clubAId),b=clubRecord(w,clubBId),sameCountry=!!a&&!!b&&a.countryId===b.countryId,sameCity=sameCountry&&!!a?.cityName&&!!b?.cityName&&a.cityName.toLowerCase()===b.cityName.toLowerCase(),geographic=clamp((sameCountry?18:0)+(sameCity?42:0)),matches=allPairMatches(w,clubAId,clubBId),winsA=matches.filter(m=>(m.home===clubAId&&m.hg>m.ag)||(m.away===clubAId&&m.ag>m.hg)).length,winsB=matches.filter(m=>(m.home===clubBId&&m.hg>m.ag)||(m.away===clubBId&&m.ag>m.hg)).length,decided=winsA+winsB,balance=decided?clamp(100-Math.abs(winsA-winsB)/decided*100):50,finals=matches.filter(m=>(m.stage??'').toLowerCase().includes('final')).length,history=clamp(Math.log2(matches.length+1)*16+finals*9),ra=clubReputation(w,clubAId).overall,rb=clubReputation(w,clubBId).overall,competitive=clamp((100-Math.abs(ra-rb))*0.45+Math.min(ra,rb)*.35+(sameCountry?12:0)),score=clamp(geographic*.34+history*.26+competitive*.28+balance*.12),label=score>=85?'historic':score>=72?'major':score>=58?'derby':score>=38?'competitive':'none';return{clubAId,clubBId,score:Number(score.toFixed(1)),geographic:Number(geographic.toFixed(1)),history:Number(history.toFixed(1)),competitive:Number(competitive.toFixed(1)),balance:Number(balance.toFixed(1)),matches:matches.length,label}}
export function matchRivalryImportance(w:World,a:string,b:string){const r=clubRivalry(w,a,b);return{rivalry:r,multiplier:Number((1+r.score/180).toFixed(3)),pressure:clamp(30+r.score*.7),mediaInterest:clamp(25+r.score*.78)}}
export function clubReputationTable(w:World,countryId?:string){const clubs=footballDataSnapshot(w).clubs.filter(c=>c.active&&(!countryId||c.countryId===countryId));return clubs.map(c=>clubReputation(w,c.id)).sort((a,b)=>b.overall-a.overall||a.clubId.localeCompare(b.clubId))}
