import type { World } from './engine';
import { allDomesticSeasons } from './domestic-competition-runtime-v1';
import { allClubKnockouts } from './club-knockout-runtime-v1';
import { allContinentalSeasons } from './continental-club-runtime-v1';
import { snapshotClubDiscipline } from './club-discipline-v1';
import { snapshotClubTravel, recentTravelLoad } from './club-travel-recovery-v1';
import { clubSchedule, clubWorkloadWindow } from './club-calendar-congestion-v1';
export type ClubSeasonCheck={id:string;ok:boolean;detail:string};
export function diagnoseClubSeasonManagement(w:World,date:string){const checks:ClubSeasonCheck[]=[];for(const c of w.clubs){const schedule=clubSchedule(w,c.id),dupes=new Set<string>(),seen=new Set<string>();for(const f of schedule){const k=`${f.date}:${f.competitionId}:${f.fixtureId}`;if(seen.has(k))dupes.add(k);seen.add(k)}checks.push({id:`schedule-${c.id}`,ok:dupes.size===0,detail:`fixtures=${schedule.length}, duplicates=${dupes.size}`});const workload=clubWorkloadWindow(w,c.id,date,14);checks.push({id:`workload-${c.id}`,ok:workload.matches>=0&&workload.competitions>=0,detail:`matches=${workload.matches}, competitions=${workload.competitions}`});const travel=recentTravelLoad(w,c.id,date,14);checks.push({id:`travel-${c.id}`,ok:travel.distanceKm>=0&&travel.timezoneHours>=0,detail:`trips=${travel.trips}, km=${travel.distanceKm}`})}const discipline=snapshotClubDiscipline(w);for(const [k,r] of discipline.records)checks.push({id:`discipline-${k}`,ok:r.yellowCards>=0&&r.redCards>=0&&r.suspensionMatches>=0,detail:`Y=${r.yellowCards}, R=${r.redCards}, ban=${r.suspensionMatches}`});const travel=snapshotClubTravel(w);checks.push({id:'travel-records',ok:travel.records.every(x=>x.distanceKm>=0&&x.timezoneShiftHours>=0),detail:`records=${travel.records.length}`});checks.push({id:'competition-runtime',ok:allDomesticSeasons(w).length+allClubKnockouts(w).length+allContinentalSeasons(w).length>0,detail:`league=${allDomesticSeasons(w).length}, cup=${allClubKnockouts(w).length}, continental=${allContinentalSeasons(w).length}`});return{ok:checks.every(x=>x.ok),checks}}
