import type { Club, World } from './engine';
import type { MatchCoreState } from './match-core-v2';
import { footballCompetition } from './world-football-data-v1';
import { queueWorldEvent } from './world-core-v2';

export type DisciplineRule={yellowThresholds:number[];redBanMatches:number;secondYellowBanMatches:number;resetStages?:string[];carryYellowAfterThreshold?:boolean};
export type PlayerDiscipline={playerId:string;competitionId:string;season:number;yellowCards:number;redCards:number;suspensionMatches:number;servedSuspensions:number;thresholdsTriggered:number[]};
export type DisciplineSnapshot={records:[string,PlayerDiscipline][]};
type Runtime={records:Map<string,PlayerDiscipline>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={records:new Map()};states.set(w,s)}return s}
const key=(playerId:string,competitionId:string,season:number)=>`${competitionId}:${season}:${playerId}`;
export function disciplineRules(w:World,competitionId:string):DisciplineRule{const c=footballCompetition(w,competitionId),id=competitionId.toLowerCase();if(id.includes('uefa')||id.includes('libertadores')||id.includes('sudamericana'))return{yellowThresholds:[3,5,7],redBanMatches:1,secondYellowBanMatches:1,resetStages:['r16'],carryYellowAfterThreshold:true};if(c?.kind==='cup')return{yellowThresholds:[2,4,6],redBanMatches:1,secondYellowBanMatches:1,carryYellowAfterThreshold:true};return{yellowThresholds:[3,6,9,12],redBanMatches:1,secondYellowBanMatches:1,carryYellowAfterThreshold:true}}
export function disciplineRecord(w:World,playerId:string,competitionId:string,season=w.season){const s=state(w),k=key(playerId,competitionId,season);let r=s.records.get(k);if(!r){r={playerId,competitionId,season,yellowCards:0,redCards:0,suspensionMatches:0,servedSuspensions:0,thresholdsTriggered:[]};s.records.set(k,r)}return r}
export function playerSuspended(w:World,playerId:string,competitionId:string,season=w.season){return disciplineRecord(w,playerId,competitionId,season).suspensionMatches>0}
export function eligibleByDiscipline(w:World,club:Club,competitionId:string,season=w.season){return club.players.filter(p=>!playerSuspended(w,p.id,competitionId,season))}
function applyThreshold(w:World,r:PlayerDiscipline,date:string){const rules=disciplineRules(w,r.competitionId);for(const t of rules.yellowThresholds){if(r.yellowCards>=t&&!r.thresholdsTriggered.includes(t)){r.thresholdsTriggered.push(t);r.suspensionMatches++;queueWorldEvent(w,{date,type:'PlayerSuspendedForYellowAccumulation',scope:'competition',entityIds:[r.competitionId,r.playerId],importance:3,payload:{threshold:t,totalYellow:r.yellowCards,suspensionMatches:r.suspensionMatches}})}}}
export function recordMatchDiscipline(w:World,state:MatchCoreState,input:{competitionId:string;season?:number;date:string}){const season=input.season??w.season,rules=disciplineRules(w,input.competitionId),changed:PlayerDiscipline[]=[];for(const live of [...state.home.players,...state.away.players]){if(live.yellowCards<=0&&!live.sentOff)continue;const r=disciplineRecord(w,live.playerId,input.competitionId,season),before={y:r.yellowCards,red:r.redCards,s:r.suspensionMatches};r.yellowCards+=live.yellowCards;if(live.sentOff){r.redCards++;r.suspensionMatches+=live.yellowCards>=2?rules.secondYellowBanMatches:rules.redBanMatches;queueWorldEvent(w,{date:input.date,type:'PlayerSentOffSuspension',scope:'competition',entityIds:[input.competitionId,live.playerId],importance:4,payload:{competitionId:input.competitionId,redCards:r.redCards,suspensionMatches:r.suspensionMatches}})}applyThreshold(w,r,input.date);if(before.y!==r.yellowCards||before.red!==r.redCards||before.s!==r.suspensionMatches)changed.push({...r})}return changed}
export function serveSuspensionForFixture(w:World,club:Club,competitionId:string,season=w.season,date=''){const served:string[]=[];for(const p of club.players){const r=disciplineRecord(w,p.id,competitionId,season);if(r.suspensionMatches>0){r.suspensionMatches--;r.servedSuspensions++;served.push(p.id);if(date)queueWorldEvent(w,{date,type:'PlayerSuspensionServed',scope:'competition',entityIds:[competitionId,p.id],importance:2,payload:{remaining:r.suspensionMatches}})}}return served}
export function resetDisciplineStage(w:World,competitionId:string,season:number,stage:string){const rules=disciplineRules(w,competitionId);if(!rules.resetStages?.includes(stage))return 0;let n=0;for(const r of state(w).records.values())if(r.competitionId===competitionId&&r.season===season){r.yellowCards=0;r.thresholdsTriggered=[];n++}return n}
export function snapshotClubDiscipline(w:World):DisciplineSnapshot{return{records:[...state(w).records.entries()].map(([k,v])=>[k,{...v,thresholdsTriggered:[...v.thresholdsTriggered]}])}}
export function restoreClubDiscipline(w:World,x:DisciplineSnapshot){states.set(w,{records:new Map((x?.records??[]).map(([k,v])=>[k,{...v,thresholdsTriggered:[...(v.thresholdsTriggered??[])]}]))})}
