import './club-stadium-experience-v2.css';
import type { World } from './engine';
import { userManager } from './manager-character';
import { clubFinance } from './economy';
import { clubVisual } from './visual-identity-v1';

const world=()=>window.__touchlineWorld as World|undefined;
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function render(){const w=world(),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!host)return;const m=userManager(w),c=w.clubs.find(x=>x.id===(m?.currentClubId??''));if(!c)return;const existing=host.querySelector('.club-stadium-x');if(existing)return;const v=clubVisual(c.name),f=clubFinance(w,c.id),avgAge=Math.round(c.players.reduce((s,p)=>s+p.age,0)/Math.max(1,c.players.length)),morale=Math.round(c.players.reduce((s,p)=>s+p.morale,0)/Math.max(1,c.players.length)),condition=Math.round(c.players.reduce((s,p)=>s+p.condition,0)/Math.max(1,c.players.length));const hero=host.querySelector('header.view-hero, .view-hero');const panel=document.createElement('section');panel.className='club-stadium-x';panel.style.setProperty('--cs-primary',v.primaryColor);panel.style.setProperty('--cs-secondary',v.secondaryColor);panel.innerHTML=`<div class="cs-stadium"><div class="cs-flood cs-f1"></div><div class="cs-flood cs-f2"></div><div class="cs-bowl"><div class="cs-stand cs-back"></div><div class="cs-pitch"><i></i></div><div class="cs-stand cs-front"></div></div><div class="cs-copy"><span>CASA DO CLUBE</span><h2>${esc(v.stadiumName??'Estádio do clube')}</h2><p>Centro simbólico da identidade do ${esc(c.name)}. Matchday, torcida, pressão e legado convergem aqui.</p><div><b>REP ${c.reputation}</b><b>ELENCO ${c.players.length}</b><b>MORAL ${morale}</b></div></div></div><aside><header><span>ESTRUTURA OPERACIONAL</span><b>Visão rápida</b></header><div class="cs-grid"><article><span>Condição média</span><strong>${condition}%</strong></article><article><span>Idade média</span><strong>${avgAge}</strong></article><article><span>Orçamento</span><strong>${f?money(f.transferBudget):'—'}</strong></article><article><span>Folha</span><strong>${f?money(f.wageSpend):'—'}</strong></article></div><div class="cs-indicator"><span>Saúde financeira</span><i><em style="width:${f?Math.max(8,Math.min(100,(f.balance/Math.max(1,f.wageBudget*52))*100)):30}%"></em></i></div><p class="cs-note">A estrutura física detalhada continuará evoluindo conforme estádio, CT, base, medicina e infraestrutura ganharem níveis próprios no mundo persistente.</p></aside>`;if(hero?.parentElement)hero.insertAdjacentElement('afterend',panel);else host.prepend(panel)}
document.addEventListener('touchline:view-rendered',e=>{const d=(e as CustomEvent).detail;if(d?.view==='club')queueMicrotask(render)});
