import type { World } from './engine';
import { footballClub, footballClubRecords, footballCompetition, footballHistoricalMatchRecords, footballTitleRecords } from './world-football-data-v1';
import { matchArchive, snapshotMatchHistory } from './match-season-history-v2';
import { clubReputation, clubRivalry } from './club-reputation-rivalry-v1';

export type ClubEra={fromSeason:number;toSeason:number;score:number;titles:number;continentalTitles:number;winRate:number;label:'golden'|'dominant'|'competitive'|'decline'};
export type ClubRecordBook={clubId:string;foundedYear?:number;totalTitles:number;continentalTitles:number;topFlightTitles:number;largestWin?:{season:number;opponentId:string;score:string;margin:number};largestDefeat?:{season:number;opponentId:string;score:string;margin:number};longestUnbeaten:number;mostGoalsSeason?:{season:number;goals:number};bestPointsSeason?:{season:number;points:number};};
export type HallMember={playerId:string;name:string;score:number;appearances:number;goals:number;assists:number;motm:number;seasons:number;status:'legend'|'icon'|'notable'};
export type ClubIdentityProfile={clubId:string;ageYears:number;reputation:ReturnType<typeof clubReputation>;recordBook:ClubRecordBook;eras:ClubEra[];hall:HallMember[];majorRivals:Array<{clubId:string;score:number;label:string}>};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function competitionWeight(w:World,id:string){const c=footballCompetition(w,id);if(!c)return 1;if(c.scope==='continental')return id.includes('uefa-cl')||id.includes('libertadores')?5:3;if(c.kind==='league'&&c.level===1)return 3;if(c.kind==='cup')return 1.5;return 1}
function clubMatches(w:World,clubId:string){return matchArchive(w).filter(m=>m.homeClubId===clubId||m.awayClubId===clubId).sort((a,b)=>(a.season-b.season)||String(a.date??'').localeCompare(String(b.date??'')))}
function resultFor(clubId:string,m:ReturnType<typeof matchArchive>[number]){const home=m.homeClubId===clubId,gf=home?m.homeGoals:m.awayGoals,ga=home?m.awayGoals:m.homeGoals,opp=home?m.awayClubId:m.homeClubId;return{gf,ga,opp,points:gf>ga?3:gf===ga?1:0}}
export function clubRecordBook(w:World,clubId:string):ClubRecordBook{const club=footballClub(w,clubId),titles=footballTitleRecords(w).filter(t=>t.teamKind==='club'&&t.teamId===clubId),matches=clubMatches(w,clubId);let largestWin:ClubRecordBook['largestWin'],largestDefeat:ClubRecordBook['largestDefeat'],run=0,longestUnbeaten=0;const seasonGoals=new Map<number,number>(),seasonPoints=new Map<number,number>();for(const m of matches){const r=resultFor(clubId,m),margin=r.gf-r.ga;if(margin>0&&(!largestWin||margin>largestWin.margin))largestWin={season:m.season,opponentId:r.opp,score:`${r.gf}-${r.ga}`,margin};if(margin<0&&(!largestDefeat||-margin>largestDefeat.margin))largestDefeat={season:m.season,opponentId:r.opp,score:`${r.gf}-${r.ga}`,margin:-margin};run=r.points>0?run+1:0;longestUnbeaten=Math.max(longestUnbeaten,run);seasonGoals.set(m.season,(seasonGoals.get(m.season)??0)+r.gf);seasonPoints.set(m.season,(seasonPoints.get(m.season)??0)+r.points)}const maxEntry=(m:Map<number,number>)=>[...m].sort((a,b)=>b[1]-a[1]||a[0]-b[0])[0];const g=maxEntry(seasonGoals),p=maxEntry(seasonPoints);return{clubId,foundedYear:club?.foundedYear,totalTitles:titles.length,continentalTitles:titles.filter(t=>footballCompetition(w,t.competitionId)?.scope==='continental').length,topFlightTitles:titles.filter(t=>{const c=footballCompetition(w,t.competitionId);return c?.kind==='league'&&c.level===1}).length,largestWin,largestDefeat,longestUnbeaten,mostGoalsSeason:g?{season:g[0],goals:g[1]}:undefined,bestPointsSeason:p?{season:p[0],points:p[1]}:undefined}}
export function clubEraTimeline(w:World,clubId:string):ClubEra[]{const matches=clubMatches(w,clubId),titles=footballTitleRecords(w).filter(t=>t.teamId===clubId&&t.teamKind==='club'),years=[...new Set([...matches.map(m=>m.season),...titles.map(t=>Number(t.season))])].sort((a,b)=>a-b);if(!years.length)return[];const rows=years.map(y=>{const ms=matches.filter(m=>m.season===y),pts=ms.reduce((a,m)=>a+resultFor(clubId,m).points,0),winRate=ms.length?pts/(ms.length*3):0.5,ts=titles.filter(t=>Number(t.season)===y),continental=ts.filter(t=>footballCompetition(w,t.competitionId)?.scope==='continental').length,titleScore=ts.reduce((a,t)=>a+competitionWeight(w,t.competitionId),0),score=clamp(winRate*55+Math.min(45,titleScore*8));return{season:y,score,winRate,titles:ts.length,continental}});const eras:ClubEra[]=[];for(let i=0;i<rows.length;){let j=i;while(j+1<rows.length&&rows[j+1].season===rows[j].season+1&&Math.abs(rows[j+1].score-rows[j].score)<28)j++;const slice=rows.slice(i,j+1),avg=slice.reduce((a,b)=>a+b.score,0)/slice.length,win=slice.reduce((a,b)=>a+b.winRate,0)/slice.length,ts=slice.reduce((a,b)=>a+b.titles,0),ct=slice.reduce((a,b)=>a+b.continental,0),label:ClubEra['label']=avg>=78||ct>=2?'golden':avg>=65||ts>=3?'dominant':avg>=46?'competitive':'decline';eras.push({fromSeason:slice[0].season,toSeason:slice.at(-1)!.season,score:Number(avg.toFixed(1)),titles:ts,continentalTitles:ct,winRate:Number((win*100).toFixed(1)),label});i=j+1}return eras}
export function clubHallOfFame(w:World,clubId:string,limit=20):HallMember[]{const snap=snapshotMatchHistory(w),names=new Map<string,string>();for(const club of w.clubs)for(const player of club.players)if(!names.has(player.id))names.set(player.id,player.name);const rows:HallMember[]=[];for(const c of snap.players.map(([,v])=>v)){const seasons=Object.values(c.seasons).filter(s=>s.clubId===clubId);if(!seasons.length)continue;const appearances=seasons.reduce((a,s)=>a+s.appearances,0),goals=seasons.reduce((a,s)=>a+s.goals,0),assists=seasons.reduce((a,s)=>a+s.assists,0),motm=seasons.reduce((a,s)=>a+s.motm,0),minutes=seasons.reduce((a,s)=>a+s.minutes,0),score=appearances*.15+goals*.55+assists*.35+motm*1.4+minutes/900;const status:HallMember['status']=score>=95?'legend':score>=45?'icon':'notable';rows.push({playerId:c.playerId,name:names.get(c.playerId)??c.playerId,score:Number(score.toFixed(1)),appearances,goals,assists,motm,seasons:seasons.length,status})}return rows.sort((a,b)=>b.score-a.score||b.appearances-a.appearances).slice(0,limit)}
export function majorClubRivals(w:World,clubId:string,limit=8){const club=footballClub(w,clubId);if(!club)return[];const candidates=new Set<string>();for(const c of footballClubRecords(w))if(c.id!==clubId&&c.countryId===club.countryId)candidates.add(c.id);for(const m of footballHistoricalMatchRecords(w)){if(m.homeTeamId===clubId)candidates.add(m.awayTeamId);else if(m.awayTeamId===clubId)candidates.add(m.homeTeamId)}for(const m of matchArchive(w)){if(m.homeClubId===clubId)candidates.add(m.awayClubId);else if(m.awayClubId===clubId)candidates.add(m.homeClubId)}candidates.delete(clubId);return[...candidates].map(id=>{const r=clubRivalry(w,clubId,id);return{clubId:id,score:r.score,label:r.label}}).filter(x=>x.score>=38).sort((a,b)=>b.score-a.score).slice(0,limit)}
export function clubIdentityProfile(w:World,clubId:string):ClubIdentityProfile{const club=footballClub(w,clubId),founded=club?.foundedYear??w.season;return{clubId,ageYears:Math.max(0,w.season-founded),reputation:clubReputation(w,clubId),recordBook:clubRecordBook(w,clubId),eras:clubEraTimeline(w,clubId),hall:clubHallOfFame(w,clubId),majorRivals:majorClubRivals(w,clubId)}}
