import type { World } from './engine';
import { footballDataSnapshot } from './world-football-data-v1';
import { allDomesticSeasons } from './domestic-competition-runtime-v1';
import { allClubKnockouts } from './club-knockout-runtime-v1';
import { allContinentalSeasons } from './continental-club-runtime-v1';
import { buildNextSeasonPyramid, auditPyramidTransition } from './domestic-pyramid-transition-v1';
import { qualifyClubsForContinentalSeason } from './continental-club-qualification-v1';
import { seedDomesticCompetitions } from './domestic-competition-calendar-v1';
import { materializeDomesticRuntimeClubs } from './domestic-club-runtime-bridge-v1';
import { seedClubCompetitionSeason } from './club-competition-season-bootstrap-v1';
import { clubReputation } from './club-reputation-rivalry-v1';
import { queueWorldEvent } from './world-core-v2';

export type ClubSeasonTransitionReport={fromSeason:number;toSeason:number;ok:boolean;blockers:string[];pyramidIssues:string[];domesticCompetitions:number;domesticFixtures:number;clubCompetitionSeasons:number;runtimeClubs:number;qualification:Array<{confederationId:string;primary:number;secondary:number;warnings:string[]}>;reputationsUpdated:number};
function activeCountries(w:World){return[...new Set(footballDataSnapshot(w).competitions.filter(c=>c.scope==='domestic'&&c.kind==='league'&&c.countryId).map(c=>c.countryId!))]}
export function clubSeasonTransitionReadiness(w:World,season=w.season){const blockers:string[]=[];for(const s of allDomesticSeasons(w).filter(x=>x.season===season))if(!s.completed)blockers.push(`liga incompleta: ${s.competitionId}`);for(const c of allClubKnockouts(w).filter(x=>x.season===season))if(!c.completed)blockers.push(`copa incompleta: ${c.competitionId}`);for(const c of allContinentalSeasons(w).filter(x=>x.season===season))if(!c.completed)blockers.push(`continental incompleta: ${c.competitionId}`);return{ready:blockers.length===0,blockers}}
export function transitionClubWorldSeason(w:World,options:{force?:boolean}={}):ClubSeasonTransitionReport{const fromSeason=w.season,toSeason=fromSeason+1,ready=clubSeasonTransitionReadiness(w,fromSeason);if(!ready.ready&&!options.force)return{fromSeason,toSeason,ok:false,blockers:ready.blockers,pyramidIssues:[],domesticCompetitions:0,domesticFixtures:0,clubCompetitionSeasons:0,runtimeClubs:0,qualification:[],reputationsUpdated:0};const countries=activeCountries(w),pyramid=countries.flatMap(c=>buildNextSeasonPyramid(w,c,fromSeason)),audit=auditPyramidTransition(w,pyramid),qualification:ClubSeasonTransitionReport['qualification']=[];for(const confederationId of ['CONMEBOL','UEFA']){try{const q=qualifyClubsForContinentalSeason(w,{confederationId,domesticSeason:fromSeason,continentalSeason:toSeason});qualification.push({confederationId,primary:q.qualifiedPrimary.length,secondary:q.qualifiedSecondary.length,warnings:q.warnings})}catch(e:any){qualification.push({confederationId,primary:0,secondary:0,warnings:[e?.message??String(e)]})}}w.season=toSeason;const domestic=seedDomesticCompetitions(w,countries,toSeason),runtime=materializeDomesticRuntimeClubs(w),clubSeason=seedClubCompetitionSeason(w,countries,toSeason);let reputationsUpdated=0;for(const c of w.clubs){c.reputation=Math.round(clubReputation(w,c.id).overall);reputationsUpdated++}queueWorldEvent(w,{date:`${toSeason}-01-01`,type:'ClubFootballSeasonTransitionCompleted',scope:'world',entityIds:[],importance:7,payload:{fromSeason,toSeason,countries,pyramidIssues:audit.issues,qualification,domestic,clubCompetitionSeasons:clubSeason.total,runtimeClubs:runtime.total}});return{fromSeason,toSeason,ok:audit.ok,blockers:ready.blockers,pyramidIssues:audit.issues,domesticCompetitions:domestic.competitions,domesticFixtures:domestic.fixtures,clubCompetitionSeasons:clubSeason.total,runtimeClubs:runtime.total,qualification,reputationsUpdated}}
