import type { World } from './engine';
import { snapshotMatchHistory } from './match-season-history-v2';
import { deepClubRecordBook } from './club-record-book-v2';

export type ClubRecordChase={clubId:string;playerId:string;playerName:string;record:'goals'|'appearances'|'assists'|'cleanSheets';current:number;target:number;remaining:number;progress:number;status:'approaching'|'close'|'equalled'|'broken'};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));

function totalsForClub(w:World,clubId:string){const snap=snapshotMatchHistory(w),rows=new Map<string,{playerId:string;goals:number;appearances:number;assists:number;cleanSheets:number}>();for(const [,career] of snap.players)for(const s of Object.values(career.seasons)){if(s.clubId!==clubId)continue;const r=rows.get(career.playerId)??{playerId:career.playerId,goals:0,appearances:0,assists:0,cleanSheets:0};r.goals+=s.goals;r.appearances+=s.appearances;r.assists+=s.assists;r.cleanSheets+=s.cleanSheets;rows.set(career.playerId,r)}return rows}

export function activeClubRecordChases(w:World,clubId:string,threshold=.72):ClubRecordChase[]{const club=w.clubs.find(c=>c.id===clubId);if(!club)return[];const totals=totalsForClub(w,clubId),records=deepClubRecordBook(w,clubId),targets={goals:records.topScorer?.value??0,appearances:records.mostAppearances?.value??0,assists:records.mostAssists?.value??0,cleanSheets:records.mostCleanSheets?.value??0};const out:ClubRecordChase[]=[];for(const p of club.players){const t=totals.get(p.id);if(!t)continue;for(const record of Object.keys(targets) as Array<keyof typeof targets>){const target=targets[record],current=t[record];if(target<=0)continue;const ratio=current/target;if(ratio<threshold&&current<target)continue;const remaining=Math.max(0,target-current),status:ClubRecordChase['status']=current>target?'broken':current===target?'equalled':ratio>=.9?'close':'approaching';out.push({clubId,playerId:p.id,playerName:p.name,record,current,target,remaining,progress:Number(clamp(ratio*100).toFixed(1)),status})}}return out.sort((a,b)=>{const rank=(s:ClubRecordChase['status'])=>s==='broken'?4:s==='equalled'?3:s==='close'?2:1;return rank(b.status)-rank(a.status)||b.progress-a.progress||a.remaining-b.remaining})}

export function clubRecordChaseNarratives(w:World,clubId:string,limit=8){return activeClubRecordChases(w,clubId).slice(0,limit).map(x=>x.status==='broken'?`${x.playerName} superou o recorde histórico de ${x.record} do clube.`:x.status==='equalled'?`${x.playerName} igualou o recorde histórico de ${x.record}.`:x.status==='close'?`${x.playerName} está a ${x.remaining} de igualar o recorde histórico de ${x.record}.`:`${x.playerName} entrou na zona de perseguição do recorde de ${x.record}.`)}
