import type { World } from './engine';
import { footballCompetition, footballDataSnapshot } from './world-football-data-v1';
import { matchArchive } from './match-season-history-v2';
import { clubReputation, clubRivalry } from './club-reputation-rivalry-v1';
import { managerByClub } from './manager-character';
import { negotiationState } from './negotiation';
import { matchdayCommercialHistory } from './club-commercial-finance';
import { rememberClubMoment, recordManagerAchievement, clubHistoricalMoments, recordTransferHistory, managerAchievements, snapshotClubInstitutionalMemory } from './club-institutional-memory-v1';

export function syncMatchMemories(w:World,fromSeason=w.season){let created=0;for(const m of matchArchive(w).filter(x=>x.season>=fromSeason)){const beforeH=clubHistoricalMoments(w,m.homeClubId).length,beforeA=clubHistoricalMoments(w,m.awayClubId).length,hg=m.homeGoals,ag=m.awayGoals,margin=Math.abs(hg-ag),winner=hg>ag?m.homeClubId:ag>hg?m.awayClubId:undefined,loser=winner===m.homeClubId?m.awayClubId:winner===m.awayClubId?m.homeClubId:undefined,date=m.date??`${m.season}-12-31`,rivalry=clubRivalry(w,m.homeClubId,m.awayClubId),homeRep=clubReputation(w,m.homeClubId).overall,awayRep=clubReputation(w,m.awayClubId).overall;if(rivalry.score>=72){for(const clubId of [m.homeClubId,m.awayClubId])rememberClubMoment(w,{id:`memory-derby-${m.id}-${clubId}`,clubId,date,season:m.season,type:'derby',importance:Math.min(92,62+rivalry.score*.28),sentiment:winner?clubId===winner?'positive':'negative':'mixed',summary:`Clássico marcante: ${m.homeClubId} ${hg}–${ag} ${m.awayClubId}.`,competitionId:m.competitionId,matchId:m.id,entityIds:[clubId===m.homeClubId?m.awayClubId:m.homeClubId],payload:{score:`${hg}-${ag}`,rivalryScore:rivalry.score},audience:{supporters:100,board:75,media:95},permanent:rivalry.score>=85&&margin>=3})}if(winner&&loser){const underdog=winner===m.homeClubId?homeRep<awayRep-18:awayRep<homeRep-18;if(underdog)rememberClubMoment(w,{id:`memory-upset-${m.id}-${winner}`,clubId:winner,date,season:m.season,type:'upset',importance:Math.min(88,58+Math.abs(homeRep-awayRep)),sentiment:'positive',summary:`Vitória histórica como azarão sobre ${loser}.`,competitionId:m.competitionId,matchId:m.id,entityIds:[loser],payload:{score:`${hg}-${ag}`,reputationGap:Math.abs(homeRep-awayRep)},audience:{supporters:92,board:80,media:90},permanent:Math.abs(homeRep-awayRep)>=30});if(margin>=5){rememberClubMoment(w,{id:`memory-record-win-${m.id}-${winner}`,clubId:winner,date,season:m.season,type:'record',importance:70+Math.min(20,margin*2),sentiment:'positive',summary:`Goleada histórica por ${margin} gols de diferença.`,competitionId:m.competitionId,matchId:m.id,entityIds:[loser],payload:{score:`${hg}-${ag}`,margin},audience:{supporters:95,board:70,media:88},permanent:margin>=7});rememberClubMoment(w,{id:`memory-record-loss-${m.id}-${loser}`,clubId:loser,date,season:m.season,type:'record',importance:68+Math.min(20,margin*2),sentiment:'negative',summary:`Derrota histórica por ${margin} gols de diferença.`,competitionId:m.competitionId,matchId:m.id,entityIds:[winner],payload:{score:`${hg}-${ag}`,margin},audience:{supporters:92,board:84,media:88},permanent:margin>=7})}}created+=Math.max(0,clubHistoricalMoments(w,m.homeClubId).length-beforeH)+Math.max(0,clubHistoricalMoments(w,m.awayClubId).length-beforeA)}return created}
export function syncTitleMemories(w:World,fromSeason=w.season){let created=0;for(const t of footballDataSnapshot(w).titles.filter(x=>x.teamKind==='club'&&x.source==='simulated'&&Number(x.season)>=fromSeason)){const before=clubHistoricalMoments(w,t.teamId).length,c=footballCompetition(w,t.competitionId),weight=c?.scope==='continental'?92:c?.kind==='league'&&c.level===1?86:c?.kind==='cup'?78:68,date=t.date??`${t.season}-12-31`;rememberClubMoment(w,{id:`memory-title-${t.id}`,clubId:t.teamId,date,season:Number(t.season),type:'title',importance:weight,sentiment:'positive',summary:`Título de ${c?.name??t.competitionId} conquistado.`,competitionId:t.competitionId,entityIds:[],payload:{titleId:t.id},audience:{supporters:100,board:100,media:96},permanent:true});const mgr=managerByClub(w,t.teamId);if(mgr&&!managerAchievements(w,t.teamId).some(a=>a.managerId===mgr.id&&a.competitionId===t.competitionId&&a.season===Number(t.season)&&a.kind==='title'))recordManagerAchievement(w,{id:`manager-title-${t.id}-${mgr.id}`,date,season:Number(t.season),managerId:mgr.id,clubId:t.teamId,competitionId:t.competitionId,kind:'title',weight,summary:`Conduziu o clube ao título de ${c?.name??t.competitionId}.`});if(clubHistoricalMoments(w,t.teamId).length>before)created++}return created}
export function syncTransferMemories(w:World,fromSeason=w.season){let created=0;for(const n of negotiationState(w).cases.filter(x=>x.status==='accepted'&&x.season>=fromSeason)){const fee=Math.max(0,n.currentPackage.upfrontFee+n.currentPackage.installments*n.currentPackage.installmentValue),kind=n.currentPackage.type==='permanent'?'permanent':'loan',id=`transfer-negotiation-${n.id}`,exists=snapshotClubInstitutionalMemory(w).transfers.some(x=>x.id===id);recordTransferHistory(w,{id,date:`${n.season}-12-31`,season:n.season,playerId:n.playerId,fromClubId:n.sellerClubId,toClubId:n.buyerClubId,fee,kind,source:'negotiation-agreement'});if(!exists)created++}return created}
export function syncCommercialRecordMemories(w:World,fromSeason=w.season){let created=0;const clubs=[...new Set(matchdayCommercialHistory(w).map(x=>x.clubId))];for(const clubId of clubs){const rows=matchdayCommercialHistory(w,clubId).sort((a,b)=>a.date.localeCompare(b.date));let maxAttendance=0,maxRevenue=0;for(const r of rows){const year=Number(r.date.slice(0,4));if(year<fromSeason){maxAttendance=Math.max(maxAttendance,r.attendance);maxRevenue=Math.max(maxRevenue,r.totalRevenue);continue}if(r.attendance>maxAttendance&&maxAttendance>0&&r.attendance>=maxAttendance*1.03){const before=clubHistoricalMoments(w,clubId).length;rememberClubMoment(w,{id:`memory-attendance-record-${clubId}-${r.date}`,clubId,date:r.date,season:year,type:'record',importance:r.attendance>=50000?72:58,sentiment:'positive',summary:`Novo recorde de público do clube: ${r.attendance.toLocaleString('pt-BR')} torcedores.`,entityIds:[],payload:{attendance:r.attendance,previous:maxAttendance},audience:{supporters:90,board:70,media:78},permanent:r.attendance>=50000});if(clubHistoricalMoments(w,clubId).length>before)created++}if(r.totalRevenue>maxRevenue&&maxRevenue>0&&r.totalRevenue>=maxRevenue*1.05){const before=clubHistoricalMoments(w,clubId).length;rememberClubMoment(w,{id:`memory-revenue-record-${clubId}-${r.date}`,clubId,date:r.date,season:year,type:'financial',importance:r.totalRevenue>=5_000_000?70:55,sentiment:'positive',summary:`Novo recorde de receita em dia de jogo.`,entityIds:[],payload:{totalRevenue:r.totalRevenue,previous:maxRevenue,attendance:r.attendance},audience:{supporters:45,board:95,media:68},permanent:r.totalRevenue>=5_000_000});if(clubHistoricalMoments(w,clubId).length>before)created++}maxAttendance=Math.max(maxAttendance,r.attendance);maxRevenue=Math.max(maxRevenue,r.totalRevenue)}}return created}
export function syncClubInstitutionalHistory(w:World,fromSeason=w.season){return{matchMoments:syncMatchMemories(w,fromSeason),titleMoments:syncTitleMemories(w,fromSeason),transferRecords:syncTransferMemories(w,fromSeason),commercialRecords:syncCommercialRecordMemories(w,fromSeason)}}
