import type { World } from './engine';
import { allDomesticSeasons } from './domestic-competition-runtime-v1';
import { allClubKnockouts } from './club-knockout-runtime-v1';
import { allContinentalSeasons } from './continental-club-runtime-v1';
import { queueWorldEvent } from './world-core-v2';

export type ClubCalendarFixtureRef={kind:'league'|'cup'|'continental';competitionId:string;season:number;fixtureId:string;date:string;homeTeamId:string;awayTeamId:string;priority:number};
export type CongestionConflict={clubId:string;first:ClubCalendarFixtureRef;second:ClubCalendarFixtureRef;gapDays:number};
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const diff=(a:string,b:string)=>Math.round((new Date(`${b}T12:00:00Z`).getTime()-new Date(`${a}T12:00:00Z`).getTime())/86400000);
function refs(w:World){const out:ClubCalendarFixtureRef[]=[];for(const s of allDomesticSeasons(w))for(const f of s.fixtures.filter(x=>!x.played))out.push({kind:'league',competitionId:s.competitionId,season:s.season,fixtureId:f.id,date:f.date,homeTeamId:f.homeTeamId,awayTeamId:f.awayTeamId,priority:2});for(const s of allClubKnockouts(w))for(const f of s.fixtures.filter(x=>!x.played))out.push({kind:'cup',competitionId:s.competitionId,season:s.season,fixtureId:f.id,date:f.date,homeTeamId:f.homeTeamId,awayTeamId:f.awayTeamId,priority:f.stage==='final'?5:3});for(const s of allContinentalSeasons(w))for(const f of s.fixtures.filter(x=>!x.played))out.push({kind:'continental',competitionId:s.competitionId,season:s.season,fixtureId:f.id,date:f.date,homeTeamId:f.homeTeamId,awayTeamId:f.awayTeamId,priority:f.stage==='final'?6:4});return out}
export function clubCalendar(w:World,clubId:string){return refs(w).filter(f=>f.homeTeamId===clubId||f.awayTeamId===clubId).sort((a,b)=>a.date.localeCompare(b.date)||b.priority-a.priority)}
export function detectCalendarCongestion(w:World,minRestDays=2){const conflicts:CongestionConflict[]=[];const clubs=new Set(refs(w).flatMap(f=>[f.homeTeamId,f.awayTeamId]));for(const clubId of clubs){const cal=clubCalendar(w,clubId);for(let i=1;i<cal.length;i++){const gap=diff(cal[i-1].date,cal[i].date);if(gap<minRestDays)conflicts.push({clubId,first:cal[i-1],second:cal[i],gapDays:gap})}}return conflicts}
function fixtureObject(w:World,r:ClubCalendarFixtureRef):any{if(r.kind==='league')return allDomesticSeasons(w).find(s=>s.competitionId===r.competitionId&&s.season===r.season)?.fixtures.find(f=>f.id===r.fixtureId);if(r.kind==='cup')return allClubKnockouts(w).find(s=>s.competitionId===r.competitionId&&s.season===r.season)?.fixtures.find(f=>f.id===r.fixtureId);return allContinentalSeasons(w).find(s=>s.competitionId===r.competitionId&&s.season===r.season)?.fixtures.find(f=>f.id===r.fixtureId)}
function occupied(w:World,clubId:string,date:string,ignoreId:string){return clubCalendar(w,clubId).some(f=>f.fixtureId!==ignoreId&&f.date===date)}
export function resolveCalendarCongestion(w:World,input:{minRestDays?:number;maxShiftDays?:number;date?:string}={}){const minRest=input.minRestDays??2,maxShift=input.maxShiftDays??10,changes:Array<{fixtureId:string;oldDate:string;newDate:string;reason:string}>=[];for(let pass=0;pass<4;pass++){const conflicts=detectCalendarCongestion(w,minRest);if(!conflicts.length)break;let changed=false;for(const c of conflicts){const movable=c.first.priority<=c.second.priority?c.first:c.second,other=movable===c.first?c.second:c.first,obj=fixtureObject(w,movable);if(!obj||obj.played)continue;const old=obj.date;let target:string|undefined;for(let d=1;d<=maxShiftDays;d++){const candidate=add(old,d),gap=diff(other.date,candidate);if(Math.abs(gap)<minRest)continue;if(occupied(w,c.clubId,candidate,movable.fixtureId))continue;const opponent=movable.homeTeamId===c.clubId?movable.awayTeamId:movable.homeTeamId;if(occupied(w,opponent,candidate,movable.fixtureId))continue;target=candidate;break}if(!target)continue;obj.date=target;changed=true;const reason=`calendar-congestion:${c.clubId}:${c.gapDays}d`;changes.push({fixtureId:movable.fixtureId,oldDate:old,newDate:target,reason});queueWorldEvent(w,{date:input.date??old,type:'ClubFixtureRescheduledForCongestion',scope:'competition',entityIds:[movable.competitionId,movable.homeTeamId,movable.awayTeamId],importance:3,payload:{fixtureId:movable.fixtureId,oldDate:old,newDate:target,reason}})}if(!changed)break}return{changes,remaining:detectCalendarCongestion(w,minRest)}}
export function clubWorkloadWindow(w:World,clubId:string,start:string,days=14){const end=add(start,days),matches=clubCalendar(w,clubId).filter(f=>f.date>=start&&f.date<=end);return{clubId,start,end,matches:matches.length,dates:matches.map(x=>x.date),competitions:[...new Set(matches.map(x=>x.competitionId))],highCongestion:matches.length>=4}}
