import type { World } from './engine';
import { footballClub, footballClubRecords } from './world-football-data-v1';
import { clubReputation, clubRivalry } from './club-reputation-rivalry-v1';
import { historicalMatchContext, clubHistoricalPressure } from './club-memory-consequences-v1';
import { queueWorldEvent } from './world-core-v2';

export type SupporterCulture={clubId:string;supporters:number;localShare:number;nationalShare:number;internationalShare:number;loyalty:number;expectation:number;patience:number;identityStrength:number;organizedInfluence:number;commercialEngagement:number;volatility:number;lastUpdatedSeason:number};
export type SupporterCultureSnapshot={clubs:[string,SupporterCulture][]};
const states=new WeakMap<World,Map<string,SupporterCulture>>();
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function state(w:World){let s=states.get(w);if(!s){s=new Map();states.set(w,s)}return s}
function seedBase(w:World,clubId:string):SupporterCulture{const c=footballClub(w,clubId),rep=clubReputation(w,clubId),age=c?.foundedYear?Math.max(0,w.season-c.foundedYear):40,cityFactor=c?.cityName?1.15:1,base=Math.round((80_000+rep.overall**2*850+age*9_000)*cityFactor),international=clamp((rep.continental-35)*.9),national=clamp(rep.overall*.65+age*.08-international*.25),local=clamp(100-national*.55-international*.35),loyalty=clamp(42+age*.18+rep.historical*.32),expectation=clamp(rep.overall*.82+rep.historical*.18),patience=clamp(78-expectation*.45+loyalty*.28),identityStrength=clamp(35+age*.25+rep.historical*.38),organizedInfluence=clamp(20+identityStrength*.48+(hash(clubId)%21)),commercialEngagement=clamp(rep.current*.55+rep.overall*.35),volatility=clamp(65-patience*.45+expectation*.35);return{clubId,supporters:base,localShare:Number(local.toFixed(1)),nationalShare:Number(national.toFixed(1)),internationalShare:Number(international.toFixed(1)),loyalty:Number(loyalty.toFixed(1)),expectation:Number(expectation.toFixed(1)),patience:Number(patience.toFixed(1)),identityStrength:Number(identityStrength.toFixed(1)),organizedInfluence:Number(organizedInfluence.toFixed(1)),commercialEngagement:Number(commercialEngagement.toFixed(1)),volatility:Number(volatility.toFixed(1)),lastUpdatedSeason:w.season}}
export function supporterCulture(w:World,clubId:string){const s=state(w);let x=s.get(clubId);if(!x){x=seedBase(w,clubId);s.set(clubId,x)}return x}
export function supporterPressureForMatch(w:World,clubId:string,opponentId:string){const c=supporterCulture(w,clubId),r=clubRivalry(w,clubId,opponentId),history=historicalMatchContext(w,clubId,opponentId),pressure=clamp(c.expectation*.34+c.organizedInfluence*.15+r.score*.23+c.volatility*.07+history.historicalPressure*.13+history.anxiety*.08),attendanceBoost=clamp(r.score*.27+c.identityStrength*.18+c.commercialEngagement*.14+history.motivation*.13+history.confidenceFactor*.08);return{pressure:Number(pressure.toFixed(1)),attendanceBoost:Number(attendanceBoost.toFixed(1)),rivalry:r.label,historicalPressure:history.historicalPressure,motivation:history.motivation,anxiety:history.anxiety,revengeFactor:history.revengeFactor,confidenceFactor:history.confidenceFactor,reasons:history.reasons,memoryIds:history.sourceMemoryIds}}
export function evolveSupporterCulture(w:World,clubId:string,fromSeason:number,toSeason=fromSeason+1){const x=supporterCulture(w,clubId),rep=clubReputation(w,clubId),history=clubHistoricalPressure(w,clubId),previous=x.supporters,deltaRep=rep.overall-x.expectation,growthRate=clamp(1.5+deltaRep*.08+rep.continental*.012+history.gloryMomentum*.006-history.traumaPressure*.004,-8,14)/100;x.supporters=Math.max(1000,Math.round(x.supporters*(1+growthRate)));x.expectation=Number(clamp(x.expectation*.66+rep.overall*.24+history.legacyExpectation*.1).toFixed(1));x.loyalty=Number(clamp(x.loyalty+(growthRate<-.03?-.8:.35)+history.identityWeight*.004).toFixed(1));x.patience=Number(clamp(78-x.expectation*.45+x.loyalty*.28-history.titleDroughtPressure*.06).toFixed(1));x.commercialEngagement=Number(clamp(x.commercialEngagement*.75+rep.current*.25).toFixed(1));x.internationalShare=Number(clamp(x.internationalShare+(rep.continental-50)*.015).toFixed(1));x.nationalShare=Number(clamp(x.nationalShare+(rep.domestic-50)*.01).toFixed(1));x.localShare=Number(clamp(100-x.nationalShare*.55-x.internationalShare*.35).toFixed(1));x.volatility=Number(clamp(65-x.patience*.45+x.expectation*.35+history.traumaPressure*.035).toFixed(1));x.lastUpdatedSeason=toSeason;if(Math.abs(x.supporters-previous)>Math.max(50_000,previous*.05))queueWorldEvent(w,{date:`${toSeason}-01-02`,type:'ClubSupporterBaseShift',scope:'club',entityIds:[clubId],importance:3,payload:{fromSeason,toSeason,previous,current:x.supporters,growthRate:Number((growthRate*100).toFixed(2)),reputation:rep.overall,historyPressure:history.totalPressure}});return x}
export function evolveAllSupporterCultures(w:World,fromSeason:number,toSeason=fromSeason+1){const ids=footballClubRecords(w).filter(c=>c.active).map(c=>c.id);for(const id of ids)evolveSupporterCulture(w,id,fromSeason,toSeason);return ids.length}
export function snapshotSupporterCultures(w:World):SupporterCultureSnapshot{return{clubs:[...state(w)].map(([k,v])=>[k,{...v}])}}
export function restoreSupporterCultures(w:World,x:SupporterCultureSnapshot){states.set(w,new Map((x?.clubs??[]).map(([k,v])=>[k,{...v}]))) }
