import type { World } from './engine';
import { footballCompetition, footballDataSnapshot, registerMembership, registerTitle } from './world-football-data-v1';
import { queueWorldEvent } from './world-core-v2';
import { createMatchCore } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { shootoutState } from './match-time-competition-v2';
import { defaultCompetitionRules } from './match-rules-v2';
import { persistCompletedMatchV2 } from './match-season-history-v2';
import { playerMatchPerformances } from './match-player-performance-v2';
import { recordMatchExposure } from './player-match-state-v2';
import { recordPartnershipMinutes } from './player-partnerships-v2';
import { recordPositionMinutes } from './player-technical-profile-v2';
import { ensurePlayerBehavior } from './player-behavior-v2';

export type ClubKnockoutFixture={id:string;competitionId:string;season:number;round:number;stage:string;date:string;homeTeamId:string;awayTeamId:string;homeGoals?:number;awayGoals?:number;penalties?:{home:number;away:number;winnerTeamId:string};played:boolean};
export type ClubKnockoutState={id:string;competitionId:string;season:number;teamIds:string[];fixtures:ClubKnockoutFixture[];currentRound:number;completed:boolean;championTeamId?:string;runnerUpTeamId?:string};
type Runtime={competitions:Map<string,ClubKnockoutState>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={competitions:new Map()};states.set(w,s)}return s}
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function club(world:World,id:string){return world.clubs.find(c=>c.id===id)}
function roundName(count:number){if(count<=2)return'final';if(count<=4)return'semifinal';if(count<=8)return'quarterfinal';if(count<=16)return'roundOf16';if(count<=32)return'roundOf32';return`roundOf${count}`}
function buildRound(competitionId:string,season:number,teamIds:string[],round:number,startDate:string){const seeded=[...teamIds].sort((a,b)=>hash(`${competitionId}:${season}:${round}:${a}`)-hash(`${competitionId}:${season}:${round}:${b}`)),fixtures:ClubKnockoutFixture[]=[];for(let i=0;i<seeded.length;i+=2){if(!seeded[i+1])continue;fixtures.push({id:`${competitionId}-${season}-ko-r${round}-${i/2+1}`,competitionId,season,round,stage:roundName(seeded.length),date:add(startDate,Math.floor(i/2)%4),homeTeamId:seeded[i],awayTeamId:seeded[i+1],played:false})}return fixtures}
export function createClubKnockoutCompetition(w:World,input:{competitionId:string;season?:number;teamIds:string[];startDate:string}){const season=input.season??w.season,comp=footballCompetition(w,input.competitionId);if(!comp||!['cup','supercup','tournament'].includes(comp.kind))throw new Error(`Not a club knockout competition: ${input.competitionId}`);const teams=[...new Set(input.teamIds)].filter(id=>footballDataSnapshot(w).clubs.some(c=>c.id===id));if(teams.length<2)throw new Error('Knockout competition requires at least two clubs');let size=1;while(size*2<=teams.length)size*=2;const selected=teams.slice(0,size),id=`${input.competitionId}-${season}`,x:ClubKnockoutState={id,competitionId:input.competitionId,season,teamIds:selected,fixtures:buildRound(input.competitionId,season,selected,1,input.startDate),currentRound:1,completed:false};state(w).competitions.set(id,x);for(const teamId of selected)registerMembership(w,{season:String(season),competitionId:input.competitionId,teamId,teamKind:'club',status:'participant',source:'simulated',provenance:[{sourceId:'club-knockout-runtime-v1',historical:false,confidence:100}]});return x}
export function clubKnockoutState(w:World,competitionId:string,season=w.season){return state(w).competitions.get(`${competitionId}-${season}`)}
export function allClubKnockouts(w:World){return[...state(w).competitions.values()]}
function feedPlayers(w:World,s:any,home:any,away:any,date:string){const perf=playerMatchPerformances(s,home,away),by=new Map(perf.map(x=>[x.playerId,x]));for(const c of [home,away]){const used=c.players.filter((p:any)=>(by.get(p.id)?.minutes??0)>0);for(const p of used){const row=by.get(p.id)!;ensurePlayerBehavior(w,p);recordMatchExposure(w,p,row.minutes,row.rating,date);recordPositionMinutes(w,p,p.position,row.minutes)}for(let i=0;i<used.length;i++)for(let j=i+1;j<used.length;j++){const mins=Math.min(by.get(used[i].id)?.minutes??0,by.get(used[j].id)?.minutes??0);if(mins>=15)recordPartnershipMinutes(w,used[i],used[j],mins)}}}
export function playClubKnockoutFixture(w:World,input:{competitionId:string;season?:number;fixtureId:string}){const season=input.season??w.season,x=clubKnockoutState(w,input.competitionId,season);if(!x)throw new Error('Knockout state missing');const f=x.fixtures.find(q=>q.id===input.fixtureId);if(!f)throw new Error('Knockout fixture missing');if(f.played)return f;const home=club(w,f.homeTeamId),away=club(w,f.awayTeamId);if(!home||!away)throw new Error(`Runtime club missing for knockout ${f.homeTeamId} vs ${f.awayTeamId}`);for(const p of [...home.players,...away.players])ensurePlayerBehavior(w,p);const match=createMatchCore(home,away,{seed:hash(`${x.id}:${f.id}`)});simulateMatchCore(match,home,away,36000,{requiresWinner:true,rules:defaultCompetitionRules});f.homeGoals=match.home.score;f.awayGoals=match.away.score;const so=shootoutState(match);if(so)f.penalties={home:so.home,away:so.away,winnerTeamId:so.winnerClubId!};f.played=true;persistCompletedMatchV2(w,match,home,away,{fixtureId:f.id,competitionId:x.competitionId,date:f.date,round:f.round});feedPlayers(w,match,home,away,f.date);queueWorldEvent(w,{date:f.date,type:'ClubKnockoutMatchCompleted',scope:'competition',entityIds:[x.competitionId,f.homeTeamId,f.awayTeamId],importance:f.stage==='final'?7:4,payload:{stage:f.stage,homeGoals:f.homeGoals,awayGoals:f.awayGoals,penalties:f.penalties}});advanceClubKnockoutIfReady(w,x,f.date);return f}
function fixtureWinner(f:ClubKnockoutFixture){if((f.homeGoals??0)>(f.awayGoals??0))return f.homeTeamId;if((f.awayGoals??0)>(f.homeGoals??0))return f.awayTeamId;return f.penalties?.winnerTeamId}
export function advanceClubKnockoutIfReady(w:World,x:ClubKnockoutState,date:string){const round=x.fixtures.filter(f=>f.round===x.currentRound);if(!round.length||round.some(f=>!f.played))return x;const winners=round.map(fixtureWinner).filter(Boolean) as string[];if(winners.length===1){x.championTeamId=winners[0];const final=round[0];x.runnerUpTeamId=final.homeTeamId===winners[0]?final.awayTeamId:final.homeTeamId;x.completed=true;registerTitle(w,{id:`title-${x.competitionId}-${x.season}-${winners[0]}`,teamId:winners[0],teamKind:'club',competitionId:x.competitionId,season:String(x.season),date,source:'simulated',provenance:[{sourceId:'club-knockout-runtime-v1',historical:false,confidence:100}]});queueWorldEvent(w,{date,type:'ClubCupChampionCrowned',scope:'competition',entityIds:[x.competitionId,winners[0]],importance:8,payload:{season:x.season,champion:winners[0],runnerUp:x.runnerUpTeamId}});return x}x.currentRound++;x.fixtures.push(...buildRound(x.competitionId,x.season,winners,x.currentRound,add(date,7)));return x}
export function playClubKnockoutsOnDate(w:World,date:string){const out:ClubKnockoutFixture[]=[];for(const x of allClubKnockouts(w))for(const f of x.fixtures.filter(q=>q.date===date&&!q.played))out.push(playClubKnockoutFixture(w,{competitionId:x.competitionId,season:x.season,fixtureId:f.id}));return out}
export type ClubKnockoutSnapshot={competitions:[string,ClubKnockoutState][]};export function snapshotClubKnockouts(w:World):ClubKnockoutSnapshot{return{competitions:[...state(w).competitions].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}export function restoreClubKnockouts(w:World,x:ClubKnockoutSnapshot){states.set(w,{competitions:new Map((x?.competitions??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
