import type { World } from './engine';
import { footballCompetition, footballDataSnapshot } from './world-football-data-v1';
import { matchArchive } from './match-season-history-v2';
import { clubReputation, clubRivalry } from './club-reputation-rivalry-v1';
import { managerByClub } from './manager-character';
import { rememberClubMoment, recordManagerAchievement, clubHistoricalMoments } from './club-institutional-memory-v1';

function goalComeback(w:World,matchId:string,clubId:string){const archive=matchArchive(w).find(m=>m.id===matchId);if(!archive)return false;return false}
export function syncMatchMemories(w:World,fromSeason=w.season){let created=0;for(const m of matchArchive(w).filter(x=>x.season>=fromSeason)){const homeBefore=clubHistoricalMoments(w,m.homeClubId).length,awayBefore=clubHistoricalMoments(w,m.awayClubId).length,hg=m.homeGoals,ag=m.awayGoals,margin=Math.abs(hg-ag),winner=hg>ag?m.homeClubId:ag>hg?m.awayClubId:undefined,loser=winner==m.homeClubId?m.awayClubId:winner==m.awayClubId?m.homeClubId:undefined,date=m.date??`${m.season}-12-31`,rivalry=clubRivalry(w,m.homeClubId,m.awayClubId),homeRep=clubReputation(w,m.homeClubId).overall,awayRep=clubReputation(w,m.awayClubId).overall;if(rivalry.score>=72){for(const clubId of [m.homeClubId,m.awayClubId])rememberClubMoment(w,{id:`memory-derby-${m.id}-${clubId}`,clubId,date,season:m.season,type:'derby',importance:Math.min(92,62+rivalry.score*.28),sentiment:winner?clubId===winner?'positive':'negative':'mixed',summary:`Clássico marcante: ${m.homeClubId} ${hg}–${ag} ${m.awayClubId}.`,competitionId:m.competitionId,matchId:m.id,entityIds:[clubId===m.homeClubId?m.awayClubId:m.homeClubId],payload:{score:`${hg}-${ag}`,rivalryScore:rivalry.score},audience:{supporters:100,board:75,media:95},permanent:rivalry.score>=85&&margin>=3})}if(winner&&loser){const underdog=winner===m.homeClubId?homeRep<awayRep-18:awayRep<homeRep-18;if(underdog)rememberClubMoment(w,{id:`memory-upset-${m.id}-${winner}`,clubId:winner,date,season:m.season,type:'upset',importance:Math.min(88,58+Math.abs(homeRep-awayRep)),sentiment:'positive',summary:`Vitória histórica como azarão sobre ${loser}.`,competitionId:m.competitionId,matchId:m.id,entityIds:[loser],payload:{score:`${hg}-${ag}`,reputationGap:Math.abs(homeRep-awayRep)},audience:{supporters:92,board:80,media:90},permanent:Math.abs(homeRep-awayRep)>=30});if(margin>=5){rememberClubMoment(w,{id:`memory-record-win-${m.id}-${winner}`,clubId:winner,date,season:m.season,type:'record',importance:70+Math.min(20,margin*2),sentiment:'positive',summary:`Goleada histórica por ${margin} gols de diferença.`,competitionId:m.competitionId,matchId:m.id,entityIds:[loser],payload:{score:`${hg}-${ag}`,margin},audience:{supporters:95,board:70,media:88},permanent:margin>=7});rememberClubMoment(w,{id:`memory-record-loss-${m.id}-${loser}`,clubId:loser,date,season:m.season,type:'record',importance:68+Math.min(20,margin*2),sentiment:'negative',summary:`Derrota histórica por ${margin} gols de diferença.`,competitionId:m.competitionId,matchId:m.id,entityIds:[winner],payload:{score:`${hg}-${ag}`,margin},audience:{supporters:92,board:84,media:88},permanent:margin>=7})}}if(clubHistoricalMoments(w,m.homeClubId).length>homeBefore)created+=clubHistoricalMoments(w,m.homeClubId).length-homeBefore;if(clubHistoricalMoments(w,m.awayClubId).length>awayBefore)created+=clubHistoricalMoments(w,m.awayClubId).length-awayBefore}return created}
export function syncTitleMemories(w:World,fromSeason=w.season){let created=0;for(const t of footballDataSnapshot(w).titles.filter(x=>x.teamKind==='club'&&x.source==='simulated'&&Number(x.season)>=fromSeason)){const before=clubHistoricalMoments(w,t.teamId).length,c=footballCompetition(w,t.competitionId),weight=c?.scope==='continental'?92:c?.kind==='league'&&c.level===1?86:c?.kind==='cup'?78:68,date=t.date??`${t.season}-12-31`;rememberClubMoment(w,{id:`memory-title-${t.id}`,clubId:t.teamId,date,season:Number(t.season),type:'title',importance:weight,sentiment:'positive',summary:`Título de ${c?.name??t.competitionId} conquistado.`,competitionId:t.competitionId,entityIds:[],payload:{titleId:t.id},audience:{supporters:100,board:100,media:96},permanent:true});const mgr=managerByClub(w,t.teamId);if(mgr)recordManagerAchievement(w,{id:`manager-title-${t.id}-${mgr.id}`,date,season:Number(t.season),managerId:mgr.id,clubId:t.teamId,competitionId:t.competitionId,kind:'title',weight,summary:`Conduziu o clube ao título de ${c?.name??t.competitionId}.`});if(clubHistoricalMoments(w,t.teamId).length>before)created++}return created}
export function syncClubInstitutionalHistory(w:World,fromSeason=w.season){return{matchMoments:syncMatchMemories(w,fromSeason),titleMoments:syncTitleMemories(w,fromSeason)}}
