import type { World } from './engine';
import { footballDataSnapshot, footballCompetition } from './world-football-data-v1';
import { createClubKnockoutCompetition, clubKnockoutState } from './club-knockout-runtime-v1';
import { createContinentalClubSeason, continentalSeason } from './continental-club-runtime-v1';
import { qualifiedClubs } from './continental-club-qualification-v1';

function powerOfTwoAtMost(n:number,max=64){let p=1;while(p*2<=Math.min(n,max))p*=2;return p}
function domesticCupParticipants(w:World,countryId:string,season:number){const snap=footballDataSnapshot(w),ids=snap.memberships.filter(m=>Number(m.season)===season&&m.teamKind==='club').filter(m=>{const c=footballCompetition(w,m.competitionId);return c?.countryId===countryId&&c.scope==='domestic'&&c.kind==='league'}).map(m=>m.teamId);const unique=[...new Set(ids)];if(unique.length>=2)return unique;return snap.clubs.filter(c=>c.active&&c.countryId===countryId).map(c=>c.id)}
export function seedDomesticCupSeasons(w:World,countryIds:string[],season=w.season){const snap=footballDataSnapshot(w),created:string[]=[];for(const countryId of countryIds){const cups=snap.competitions.filter(c=>c.active&&c.countryId===countryId&&c.scope==='domestic'&&c.kind==='cup');for(const cup of cups){if(clubKnockoutState(w,cup.id,season))continue;const candidates=domesticCupParticipants(w,countryId,season),size=powerOfTwoAtMost(candidates.length,64);if(size<2)continue;const startMonth=cup.rules.seasonStartMonth??(cup.rules.calendarPattern==='calendar-year'?2:8),start=`${season}-${String(startMonth).padStart(2,'0')}-15`;createClubKnockoutCompetition(w,{competitionId:cup.id,season,teamIds:candidates.slice(0,size),startDate:start});created.push(`${cup.id}-${season}`)}}return{created,count:created.length}}
export function seedContinentalClubSeasons(w:World,season=w.season){const ids=['comp-conmebol-libertadores','comp-conmebol-sudamericana','comp-uefa-cl','comp-uefa-el','comp-uefa-conf'],created:string[]=[];for(const competitionId of ids){const comp=footballCompetition(w,competitionId);if(!comp)continue;const teams=qualifiedClubs(w,competitionId,season);if(competitionId==='comp-conmebol-libertadores'){if(continentalSeason(w,competitionId,season)||teams.length<16)continue;createContinentalClubSeason(w,{competitionId,season,teamIds:teams,startDate:`${season}-04-01`,format:'libertadores-groups'});created.push(`${competitionId}-${season}`);continue}if(competitionId==='comp-uefa-cl'){if(continentalSeason(w,competitionId,season)||teams.length<16)continue;createContinentalClubSeason(w,{competitionId,season,teamIds:teams,startDate:`${season}-09-10`,format:'uefa-league-phase'});created.push(`${competitionId}-${season}`);continue}if(clubKnockoutState(w,competitionId,season))continue;const size=powerOfTwoAtMost(teams.length,32);if(size<2)continue;const month=comp.rules.seasonStartMonth??(comp.rules.calendarPattern==='calendar-year'?2:9),start=`${season}-${String(month).padStart(2,'0')}-10`;createClubKnockoutCompetition(w,{competitionId,season,teamIds:teams.slice(0,size),startDate:start});created.push(`${competitionId}-${season}`)}return{created,count:created.length}}
export function seedClubCompetitionSeason(w:World,countryIds:string[],season=w.season){const domestic=seedDomesticCupSeasons(w,countryIds,season),continental=seedContinentalClubSeasons(w,season);return{domestic,continental,total:domestic.count+continental.count}}
