import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { clubHistoricalPressure } from './club-memory-consequences-v1';
export type Ownership='association'|'saf'|'privateCompany'|'memberOwned';
export type BoardRole='president'|'vicePresident'|'footballDirector'|'academyDirector'|'financeDirector'|'commercialDirector'|'facilitiesDirector'|'councillor'|'supportersRepresentative';
export type BoardPerson={id:string;clubId:string;name:string;age:number;role:BoardRole;reputation:number;finance:number;football:number;youth:number;negotiation:number;communication:number;integrity:number;ambition:number;patience:number;tradition:number;innovation:number;fanSensitivity:number;mediaSkill:number;managerSupport:number;boardInfluence:number;active:boolean;electedYear?:number;retirementAge:number};
export type ClubPhilosophy={financialPrudence:number;youthPriority:number;competitiveAmbition:number;tradition:number;commercialGrowth:number;infrastructure:number;managerAutonomy:number;fanVoice:number};
export type Governance={clubId:string;ownership:Ownership;board:BoardPerson[];philosophy:ClubPhilosophy;nextElectionYear:number;electionCycle:4|0;boardStability:number;fanApproval:number;mediaPressure:number;financialConfidence:number;managerConfidence:number;crisis:number;takeoverRisk:number;supportersSafApproval:number};
type State={clubs:Map<string,Governance>;lastTick?:string};const states=new WeakMap<World,State>(),clamp=(v:number)=>Math.max(0,Math.min(100,v));
const first=['Augusto','Carlos','Roberto','Marcelo','Paulo','Ricardo','Fernando','Eduardo','Sérgio','Rafael','Luiz','André'],last=['Almeida','Barros','Cardoso','Duarte','Ferreira','Gomes','Moraes','Nogueira','Oliveira','Pereira','Ramos','Silva'];let seq=1;const rnd=(a:number,b:number)=>Math.round(a+Math.random()*(b-a)),name=()=>`${first[rnd(0,first.length-1)]} ${last[rnd(0,last.length-1)]}`;
function person(clubId:string,role:BoardRole,year:number):BoardPerson{return{id:`board-${seq++}`,clubId,name:name(),age:rnd(38,71),role,reputation:rnd(35,82),finance:rnd(35,88),football:rnd(30,85),youth:rnd(30,85),negotiation:rnd(35,88),communication:rnd(30,88),integrity:rnd(35,95),ambition:rnd(30,90),patience:rnd(25,90),tradition:rnd(25,95),innovation:rnd(25,92),fanSensitivity:rnd(25,95),mediaSkill:rnd(25,90),managerSupport:rnd(35,75),boardInfluence:role==='president'?95:role==='vicePresident'?78:role==='councillor'?rnd(35,75):rnd(45,80),active:true,electedYear:role==='councillor'?undefined:year,retirementAge:rnd(70,86)}}
function create(clubId:string,year:number):Governance{const roles:BoardRole[]=['president','vicePresident','footballDirector','academyDirector','financeDirector','commercialDirector','facilitiesDirector','supportersRepresentative'];const board=roles.map(r=>person(clubId,r,year));for(let i=0;i<9;i++)board.push(person(clubId,'councillor',year));return{clubId,ownership:'association',board,philosophy:{financialPrudence:rnd(45,80),youthPriority:rnd(35,85),competitiveAmbition:rnd(45,90),tradition:rnd(35,90),commercialGrowth:rnd(35,85),infrastructure:rnd(35,80),managerAutonomy:rnd(35,80),fanVoice:rnd(35,85)},nextElectionYear:year+4,electionCycle:4,boardStability:70,fanApproval:60,mediaPressure:25,financialConfidence:65,managerConfidence:60,crisis:10,takeoverRisk:5,supportersSafApproval:35}}
export function governanceState(world:World){let s=states.get(world);if(!s){s={clubs:new Map()};states.set(world,s)}for(const c of world.clubs)if(!s.clubs.has(c.id))s.clubs.set(c.id,create(c.id,world.season));return s}export const clubGovernance=(w:World,id:string)=>governanceState(w).clubs.get(id)!;
export function boardVote(world:World,clubId:string,topic:'managerDismissal'|'majorTransfer'|'facilityInvestment'|'debt'|'safConversion',urgency=50){const g=clubGovernance(world,clubId),history=clubHistoricalPressure(world,clubId);let yes=0,total=0;for(const p of g.board.filter(x=>x.active)){let inclination=50;if(topic==='managerDismissal')inclination=100-p.managerSupport+g.crisis*.35+history.totalPressure*.12+history.managerShadow*.12;if(topic==='facilityInvestment')inclination=g.philosophy.infrastructure*.6+p.innovation*.25-g.crisis*.2+history.identityWeight*.04;if(topic==='debt')inclination=g.philosophy.competitiveAmbition*.35-p.finance*.25+urgency*.35+history.legacyExpectation*.05;if(topic==='safConversion')inclination=g.takeoverRisk*.45+g.supportersSafApproval*.3+p.innovation*.2-p.tradition*.15;if(topic==='majorTransfer')inclination=p.football*.3+g.philosophy.competitiveAmbition*.35-g.crisis*.2+history.titleDroughtPressure*.08+history.legacyExpectation*.05;const weight=p.boardInfluence*(p.role==='supportersRepresentative'?g.philosophy.fanVoice/60:1);total+=weight;if(inclination+Math.random()*25-12>50)yes+=weight}return{approved:yes>total*.5,support:total?yes/total*100:0,historicalPressure:history.totalPressure}}
function election(world:World,g:Governance,date:string){const year=Number(date.slice(0,4));if(g.electionCycle===0||year<g.nextElectionYear)return;const old=g.board.find(p=>p.role==='president'&&p.active),approval=g.fanApproval*.4+g.financialConfidence*.3+g.boardStability*.3;if(old&&approval>=58){old.electedYear=year;old.managerSupport=clamp(old.managerSupport+(Math.random()*8-4))}else{if(old)old.active=false;g.board.push(person(g.clubId,'president',year));g.boardStability=clamp(g.boardStability-12);emitWorldEvent(world,{type:'ClubElection',date,clubIds:[g.clubId],importance:4,summary:`Eleição presidencial alterou o comando institucional do clube.`,payload:{previous:old?.id}})}g.nextElectionYear=year+4}
function councillors(world:World,g:Governance,date:string){for(const p of g.board.filter(x=>x.active&&x.role==='councillor'))if(p.age>=p.retirementAge){p.active=false;const n=person(g.clubId,'councillor',Number(date.slice(0,4)));g.board.push(n);emitWorldEvent(world,{type:'CouncillorSuccession',date,clubIds:[g.clubId],importance:2,summary:`Um novo conselheiro foi eleito após saída do conselho.`,payload:{retired:p.id,new:n.id}})}}
export function tickClubGovernance(world:World,date:string){const s=governanceState(world);if(s.lastTick===date)return;for(const g of s.clubs.values()){election(world,g,date);councillors(world,g,date);const yearDay=date.endsWith('-01-01');if(yearDay)for(const p of g.board.filter(x=>x.active))p.age++;if(date.endsWith('-01')){const h=clubHistoricalPressure(world,g.clubId);g.mediaPressure=clamp(g.mediaPressure+(h.totalPressure-45)*.012+(h.titleDroughtPressure-35)*.01);g.managerConfidence=clamp(g.managerConfidence-(h.managerShadow*.006+h.titleDroughtPressure*.004)+h.gloryMomentum*.003);g.fanApproval=clamp(g.fanApproval-(h.titleDroughtPressure*.003+h.traumaPressure*.002)+h.gloryMomentum*.002)}g.crisis=clamp(g.crisis+(50-g.financialConfidence)*.004+(50-g.fanApproval)*.003);g.mediaPressure=clamp(g.mediaPressure+(g.crisis-40)*.002);g.boardStability=clamp(g.boardStability+(g.financialConfidence-50)*.002-(g.mediaPressure-50)*.002);g.takeoverRisk=clamp(g.takeoverRisk+(g.crisis-65)*.008+(35-g.financialConfidence)*.006);g.supportersSafApproval=clamp(g.supportersSafApproval+(g.crisis-65)*.004);if(g.ownership==='association'&&g.takeoverRisk>82&&g.supportersSafApproval>55){const vote=boardVote(world,g.clubId,'safConversion',90);if(vote.approved){g.ownership='saf';g.electionCycle=0;g.financialConfidence=clamp(g.financialConfidence+20);emitWorldEvent(world,{type:'ClubOwnershipChanged',date,clubIds:[g.clubId],importance:5,summary:`O clube aprovou conversão para SAF em meio à crise financeira.`,payload:{support:vote.support}})}}}s.lastTick=date}
export function snapshotClubGovernance(world:World){const s=governanceState(world);return{clubs:[...s.clubs],lastTick:s.lastTick}}export function restoreClubGovernance(world:World,x:ReturnType<typeof snapshotClubGovernance>){states.set(world,{clubs:new Map(x.clubs),lastTick:x.lastTick})}
