import type { World } from './engine';
import { economyState } from './economy';
import { clubAssets } from './club-assets-media';
import { clubCommercial, signPartnership } from './club-commercial-engine';
import { clubGovernance } from './club-governance';
import { emitWorldEvent } from './event-bus';
export type SponsorProfile={name:string;category:'sportswear'|'bank'|'airline'|'beverage'|'technology'|'automotive'|'betting'|'retail'|'telecom';prestige:number;globalReach:number;controversyTolerance:number;annualMin:number;annualMax:number};
export const sponsorCatalog:SponsorProfile[]=[
{name:'Adidas',category:'sportswear',prestige:94,globalReach:95,controversyTolerance:48,annualMin:4_000_000,annualMax:45_000_000},{name:'Nike',category:'sportswear',prestige:96,globalReach:98,controversyTolerance:45,annualMin:5_000_000,annualMax:55_000_000},{name:'Puma',category:'sportswear',prestige:88,globalReach:90,controversyTolerance:52,annualMin:3_000_000,annualMax:30_000_000},{name:'Itaú',category:'bank',prestige:84,globalReach:62,controversyTolerance:38,annualMin:2_000_000,annualMax:20_000_000},{name:'Banco do Brasil',category:'bank',prestige:82,globalReach:55,controversyTolerance:32,annualMin:2_000_000,annualMax:18_000_000},{name:'Emirates',category:'airline',prestige:95,globalReach:97,controversyTolerance:55,annualMin:6_000_000,annualMax:70_000_000},{name:'Coca-Cola',category:'beverage',prestige:95,globalReach:100,controversyTolerance:42,annualMin:4_000_000,annualMax:40_000_000},{name:'Samsung',category:'technology',prestige:92,globalReach:96,controversyTolerance:46,annualMin:4_000_000,annualMax:45_000_000},{name:'Volkswagen',category:'automotive',prestige:86,globalReach:92,controversyTolerance:43,annualMin:3_000_000,annualMax:28_000_000},{name:'Mercado Livre',category:'retail',prestige:88,globalReach:80,controversyTolerance:50,annualMin:3_000_000,annualMax:30_000_000},{name:'Vivo',category:'telecom',prestige:82,globalReach:66,controversyTolerance:45,annualMin:2_000_000,annualMax:18_000_000}];
export type MatchdayCommercial={ticketPrice:number;hospitalitySeats:number;hospitalityPrice:number;averageAttendance:number;seasonTicketHolders:number;museumVisitorsMonthly:number;toursMonthly:number;namingRights?:{brand:string;annualValue:number;yearsLeft:number};preseasonTour?:{country:string;fee:number;commercialBoost:number;completed:boolean}};
export type MatchdayCommercialRecord={clubId:string;date:string;attendance:number;tickets:number;hospitality:number;concessions:number;totalRevenue:number};
type State={clubs:Map<string,MatchdayCommercial>;matchdays:MatchdayCommercialRecord[];lastMonth?:string};const states=new WeakMap<World,State>();const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function container(world:World){let s=states.get(world);if(!s){s={clubs:new Map(),matchdays:[]};states.set(world,s)}return s}
function create(world:World,clubId:string):MatchdayCommercial{const cap=clubAssets(world,clubId).facilities.stadium.capacity??25000,rep=world.clubs.find(c=>c.id===clubId)?.reputation??60;return{ticketPrice:45+rep*.65,hospitalitySeats:Math.round(cap*.025),hospitalityPrice:250+rep*5,averageAttendance:Math.round(cap*(.48+rep/220)),seasonTicketHolders:Math.round(cap*.22),museumVisitorsMonthly:Math.round(800+rep*35),toursMonthly:Math.round(300+rep*18)}}
export function commercialFinanceState(world:World){const s=container(world);for(const c of world.clubs)if(!s.clubs.has(c.id))s.clubs.set(c.id,create(world,c.id));return s}
export function signRealSponsor(world:World,clubId:string,sponsorName:string,date:string){const p=sponsorCatalog.find(x=>x.name===sponsorName),club=world.clubs.find(c=>c.id===clubId);if(!p||!club)return false;const g=clubGovernance(world,clubId),fit=clamp(club.reputation*.55+p.prestige*.25+g.financialConfidence*.2),value=Math.round((p.annualMin+(p.annualMax-p.annualMin)*(fit/100)) /100000)*100000;signPartnership(world,clubId,{partner:p.name,kind:p.category==='sportswear'?'technicalSupplier':p.globalReach>85?'internationalBrand':'regionalBrand',annualValue:value,yearsLeft:3,reputationImpact:Math.round((p.prestige-70)/10)},date);return true}
export function signNamingRights(world:World,clubId:string,brand:string,annualValue:number,years:number,date:string){const s=commercialFinanceState(world).clubs.get(clubId)!;s.namingRights={brand,annualValue,yearsLeft:years};emitWorldEvent(world,{type:'NamingRightsSigned',date,clubIds:[clubId],importance:3,summary:`O estádio passou a ter acordo de naming rights com ${brand}.`,payload:{annualValue,years}})}
export function schedulePreseasonTour(world:World,clubId:string,country:string,fee:number,commercialBoost:number){commercialFinanceState(world).clubs.get(clubId)!.preseasonTour={country,fee,commercialBoost,completed:false}}
export function recordHomeMatchCommercial(world:World,clubId:string,date:string){const st=commercialFinanceState(world),existing=st.matchdays.find(x=>x.clubId===clubId&&x.date===date);if(existing)return existing;const s=st.clubs.get(clubId)!,a=clubAssets(world,clubId),g=clubGovernance(world,clubId),finance=economyState(world).finances.get(clubId)!;const cap=a.facilities.stadium.capacity??25000,attendance=Math.min(cap,Math.round(s.averageAttendance*(.82+g.fanApproval/220))),tickets=Math.max(0,attendance-s.seasonTicketHolders)*s.ticketPrice,hospitality=Math.min(s.hospitalitySeats,Math.round(s.hospitalitySeats*(.55+g.fanApproval/220)))*s.hospitalityPrice,concessions=attendance*(12+clubCommercial(world,clubId).brandStrength*.08),totalRevenue=tickets+hospitality+concessions;finance.balance+=totalRevenue;const record={clubId,date,attendance,tickets,hospitality,concessions,totalRevenue} satisfies MatchdayCommercialRecord;st.matchdays.push(record);if(st.matchdays.length>20000)st.matchdays.shift();emitWorldEvent(world,{type:'MatchdayCommercialRevenue',date,clubIds:[clubId],importance:1,summary:`Dia de jogo gerou receita comercial e de bilheteria.`,payload:{attendance,tickets,hospitality,concessions,totalRevenue}});return record}
export function matchdayCommercialHistory(world:World,clubId?:string){return container(world).matchdays.filter(x=>!clubId||x.clubId===clubId).map(x=>({...x}))}
function settleMonth(world:World,date:string){for(const club of world.clubs){const c=clubCommercial(world,club.id),m=commercialFinanceState(world).clubs.get(club.id)!,f=economyState(world).finances.get(club.id)!,assets=clubAssets(world,club.id);const recurring=Object.values(c.seasonRevenue).reduce((a,b)=>a+b,0)/12,museum=m.museumVisitorsMonthly*28,tours=m.toursMonthly*35,naming=(m.namingRights?.annualValue??0)/12,maintenance=Object.values(assets.facilities).reduce((a,x)=>a+x.annualMaintenance,0)/12+assets.annualAdminCost/12;f.balance+=recurring+museum+tours+naming-maintenance;if(f.balance<0){const g=clubGovernance(world,club.id);g.financialConfidence=clamp(g.financialConfidence-4);g.crisis=clamp(g.crisis+3)}if(m.preseasonTour&&!m.preseasonTour.completed&&date.endsWith('-07-01')){m.preseasonTour.completed=true;f.balance+=m.preseasonTour.fee;c.brandStrength=clamp(c.brandStrength+m.preseasonTour.commercialBoost);emitWorldEvent(world,{type:'PreseasonCommercialTour',date,clubIds:[club.id],importance:2,summary:`O clube realizou pré-temporada comercial em ${m.preseasonTour.country}.`,payload:{fee:m.preseasonTour.fee,boost:m.preseasonTour.commercialBoost}})}if(date.endsWith('-07-01')&&m.namingRights){m.namingRights.yearsLeft--;if(m.namingRights.yearsLeft<=0)m.namingRights=undefined}}}
export function tickCommercialFinance(world:World,date:string){const s=commercialFinanceState(world),month=date.slice(0,7);if(s.lastMonth!==month){settleMonth(world,date);s.lastMonth=month}}
export function snapshotCommercialFinance(world:World){const s=commercialFinanceState(world);return{clubs:[...s.clubs],matchdays:s.matchdays.map(x=>({...x})),lastMonth:s.lastMonth}}export function restoreCommercialFinance(world:World,x:ReturnType<typeof snapshotCommercialFinance>|any){states.set(world,{clubs:new Map(x?.clubs??[]),matchdays:(x?.matchdays??[]).map((v:MatchdayCommercialRecord)=>({...v})),lastMonth:x?.lastMonth})}
