import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { clubAssets } from './club-assets-media';
import { clubGovernance } from './club-governance';
export type MembershipTier={id:string;name:string;monthlyFee:number;members:number;benefitsCost:number;retention:number};
export type StadiumLease={id:string;tenant:string;kind:'clubStore'|'restaurant'|'museum'|'retail'|'office'|'eventSpace';monthlyRent:number;revenueShare:number;occupancy:number};
export type Partnership={id:string;partner:string;kind:'sponsor'|'technicalSupplier'|'regionalBrand'|'internationalBrand'|'academyPartner';annualValue:number;yearsLeft:number;reputationImpact:number};
export type PartnerClub={clubId:string;country:string;tier:number;relationship:number;youthPriority:boolean;loanPriority:boolean;firstOption:boolean;annualCost:number};
export type CommercialAppearance={id:string;personId:string;personType:'player'|'manager';kind:'tvShow'|'sportsProgram'|'advertising'|'clubEvent';fee:number;clubShare:number;date:string;completed:boolean;controversyRisk:number;audience:number};
export type CommercialState={clubId:string;brandStrength:number;shirtDemand:number;shirtPrice:number;shirtMargin:number;shirtsSoldSeason:number;membership:MembershipTier[];leases:StadiumLease[];partnerships:Partnership[];partnerClubs:PartnerClub[];appearances:CommercialAppearance[];seasonRevenue:{membership:number;merchandise:number;leases:number;partnerships:number;appearances:number};fanCommercialTrust:number;commercialSaturation:number;lastSettlementMonth?:string};
type State={clubs:Map<string,CommercialState>;lastTick?:string};const states=new WeakMap<World,State>();let seq=1;const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function create(clubId:string,rep:number):CommercialState{const base=Math.round(1800+rep*75);return{clubId,brandStrength:clamp(rep),shirtDemand:clamp(rep*.8),shirtPrice:299,shirtMargin:.34,shirtsSoldSeason:0,membership:[{id:'basic',name:'Sócio Torcedor',monthlyFee:39.9,members:base,benefitsCost:5.5,retention:.94},{id:'plus',name:'Sócio Torcedor Plus',monthlyFee:79.9,members:Math.round(base*.28),benefitsCost:14,retention:.91},{id:'premium',name:'Sócio Torcedor Premium',monthlyFee:159.9,members:Math.round(base*.07),benefitsCost:31,retention:.89}],leases:[],partnerships:[],partnerClubs:[],appearances:[],seasonRevenue:{membership:0,merchandise:0,leases:0,partnerships:0,appearances:0},fanCommercialTrust:65,commercialSaturation:20}}
export function commercialState(world:World){let s=states.get(world);if(!s){s={clubs:new Map()};states.set(world,s)}for(const c of world.clubs)if(!s.clubs.has(c.id))s.clubs.set(c.id,create(c.id,c.reputation));return s}export const clubCommercial=(w:World,id:string)=>commercialState(w).clubs.get(id)!;
export function addStadiumLease(world:World,clubId:string,tenant:string,kind:StadiumLease['kind'],monthlyRent:number,revenueShare:number,date:string){const c=clubCommercial(world,clubId);c.leases.push({id:`lease-${seq++}`,tenant,kind,monthlyRent,revenueShare,occupancy:100});emitWorldEvent(world,{type:'StadiumCommercialLease',date,clubIds:[clubId],importance:2,summary:`${tenant} alugou espaço comercial no estádio.`,payload:{kind,monthlyRent,revenueShare}})}
export function signPartnership(world:World,clubId:string,p:Omit<Partnership,'id'>,date:string){const c=clubCommercial(world,clubId);c.partnerships.push({...p,id:`partner-${seq++}`});c.brandStrength=clamp(c.brandStrength+p.reputationImpact*.25);emitWorldEvent(world,{type:'CommercialPartnershipSigned',date,clubIds:[clubId],importance:3,summary:`O clube fechou parceria comercial com ${p.partner}.`,payload:{kind:p.kind,value:p.annualValue}})}
export function establishPartnerClub(world:World,clubId:string,partner:PartnerClub,date:string){const c=clubCommercial(world,clubId);if(c.partnerClubs.some(x=>x.clubId===partner.clubId))return false;c.partnerClubs.push({...partner});emitWorldEvent(world,{type:'PartnerClubAgreement',date,clubIds:[clubId,partner.clubId],importance:3,summary:`Foi estabelecida parceria internacional entre clubes.`,payload:{partner}});return true}
export function partnerClubNegotiationModifier(world:World,clubId:string,targetClubId:string,isYouth:boolean){const p=clubCommercial(world,clubId).partnerClubs.find(x=>x.clubId===targetClubId);if(!p)return{priority:0,feeDiscount:0,loanChance:0};return{priority:p.firstOption?clamp(p.relationship*.6):0,feeDiscount:(p.firstOption&&isYouth?p.relationship*.0015:0),loanChance:p.loanPriority?clamp(15+p.relationship*.65):0}}
export function scheduleCommercialAppearance(world:World,clubId:string,personId:string,personType:CommercialAppearance['personType'],kind:CommercialAppearance['kind'],fee:number,clubShare:number,date:string){const c=clubCommercial(world,clubId),a:CommercialAppearance={id:`appearance-${seq++}`,personId,personType,kind,fee,clubShare:clamp(clubShare,0,100),date,completed:false,controversyRisk:personType==='manager'&&kind==='sportsProgram'?35:kind==='tvShow'?22:8,audience:Math.round(100_000+c.brandStrength*18_000)};c.appearances.push(a);return a}
export function completeCommercialAppearance(world:World,clubId:string,id:string,date:string,tone:'safe'|'assertive'|'provocative'='safe'){const c=clubCommercial(world,clubId),a=c.appearances.find(x=>x.id===id);if(!a||a.completed)return false;a.completed=true;const revenue=a.fee*a.clubShare/100;c.seasonRevenue.appearances+=revenue;const g=clubGovernance(world,clubId),risk=a.controversyRisk*(tone==='provocative'?1.8:tone==='assertive'?1.15:.55),incident=Math.random()*100<risk;if(incident){g.mediaPressure=clamp(g.mediaPressure+(tone==='provocative'?9:5));g.fanApproval=clamp(g.fanApproval+(Math.random()>.5?4:-5));g.managerConfidence=clamp(g.managerConfidence+(a.personType==='manager'?-4:0));emitWorldEvent(world,{type:'CommercialAppearanceControversy',date,actorIds:[a.personId],clubIds:[clubId],importance:3,summary:`Uma participação em ${a.kind} gerou repercussão e tensão entre grupos ligados ao clube.`,payload:{tone,audience:a.audience,revenue}})}else{c.brandStrength=clamp(c.brandStrength+Math.min(2,a.audience/5_000_000));emitWorldEvent(world,{type:'CommercialAppearanceSuccess',date,actorIds:[a.personId],clubIds:[clubId],importance:2,summary:`Participação pública ampliou a exposição comercial do clube.`,payload:{audience:a.audience,revenue}})}return true}
function month(world:World,c:CommercialState,date:string){const g=clubGovernance(world,c.clubId),assets=clubAssets(world,c.clubId),fanFactor=clamp(g.fanApproval*.55+c.brandStrength*.45)/100;let memberRev=0;for(const t of c.membership){const growth=(fanFactor-.5)*.025+(c.fanCommercialTrust-50)*.0002-c.commercialSaturation*.00015;t.members=Math.max(0,Math.round(t.members*(t.retention+growth)+(c.brandStrength*fanFactor*.8)));memberRev+=t.members*Math.max(0,t.monthlyFee-t.benefitsCost)}c.seasonRevenue.membership+=memberRev;const capacity=assets.facilities.stadium.capacity??25000,shirts=Math.max(40,Math.round((c.shirtDemand*.7+c.brandStrength*.3)*fanFactor*capacity/650));c.shirtsSoldSeason+=shirts;c.seasonRevenue.merchandise+=shirts*c.shirtPrice*c.shirtMargin;c.seasonRevenue.leases+=c.leases.reduce((a,l)=>a+l.monthlyRent*l.occupancy/100,0);c.seasonRevenue.partnerships+=c.partnerships.reduce((a,p)=>a+p.annualValue/12,0);const partnerCost=c.partnerClubs.reduce((a,p)=>a+p.annualCost/12,0);c.seasonRevenue.partnerships-=partnerCost;c.commercialSaturation=clamp(c.commercialSaturation+c.partnerships.length*.05+c.appearances.filter(a=>a.completed&&a.date.slice(0,7)===date.slice(0,7)).length*.15-.25);g.financialConfidence=clamp(g.financialConfidence+(memberRev>250_000?.08:-.02));}
export function tickCommercialEngine(world:World,date:string){const s=commercialState(world);if(s.lastTick===date)return;for(const c of s.clubs.values()){const m=date.slice(0,7);if(c.lastSettlementMonth!==m){month(world,c,date);c.lastSettlementMonth=m}for(const p of c.partnerships)if(date.endsWith('-07-01'))p.yearsLeft--;c.partnerships=c.partnerships.filter(p=>p.yearsLeft>0);if(date.endsWith('-07-01')){c.shirtsSoldSeason=0;c.seasonRevenue={membership:0,merchandise:0,leases:0,partnerships:0,appearances:0}}}s.lastTick=date}
export function commercialRevenue(world:World,clubId:string){const r=clubCommercial(world,clubId).seasonRevenue;return Object.values(r).reduce((a,b)=>a+b,0)}export function snapshotCommercial(world:World){const s=commercialState(world);return{clubs:[...s.clubs],lastTick:s.lastTick}}export function restoreCommercial(world:World,x:ReturnType<typeof snapshotCommercial>){states.set(world,{clubs:new Map(x.clubs),lastTick:x.lastTick})}
