import type { World } from './engine';
import { clubIdentityProfile } from './club-history-identity-v1';
import { deepClubRecordBook, competitionHonoursBreakdown } from './club-record-book-v2';
import { strongestClubMemories, managerAchievements, clubTransferHistory } from './club-institutional-memory-v1';
import { supporterCulture } from './club-supporter-culture-v1';
import { clubReputation } from './club-reputation-rivalry-v1';

export type ClubLegacyProfile={clubId:string;reputation:ReturnType<typeof clubReputation>;supporters:ReturnType<typeof supporterCulture>;honours:ReturnType<typeof competitionHonoursBreakdown>;records:ReturnType<typeof deepClubRecordBook>;eras:ReturnType<typeof clubIdentityProfile>['eras'];hallOfFame:ReturnType<typeof clubIdentityProfile>['hall'];rivals:ReturnType<typeof clubIdentityProfile>['majorRivals'];memories:ReturnType<typeof strongestClubMemories>;managerLegacy:Array<{managerId:string;score:number;titles:number;promotions:number;records:number;achievements:number}>;transfers:{count:number;largestPurchases:ReturnType<typeof clubTransferHistory>;largestSales:ReturnType<typeof clubTransferHistory>}};
export function clubLegacyProfile(w:World,clubId:string,memoryLimit=30):ClubLegacyProfile{const identity=clubIdentityProfile(w,clubId),achievements=managerAchievements(w,clubId),managers=new Map<string,{managerId:string;score:number;titles:number;promotions:number;records:number;achievements:number}>();for(const a of achievements){const r=managers.get(a.managerId)??{managerId:a.managerId,score:0,titles:0,promotions:0,records:0,achievements:0};r.score+=a.weight;r.achievements++;if(a.kind==='title')r.titles++;if(a.kind==='promotion')r.promotions++;if(a.kind==='record')r.records++;managers.set(a.managerId,r)}const transfers=clubTransferHistory(w,clubId),purchases=transfers.filter(x=>x.toClubId===clubId).sort((a,b)=>b.fee-a.fee).slice(0,10),sales=transfers.filter(x=>x.fromClubId===clubId).sort((a,b)=>b.fee-a.fee).slice(0,10);return{clubId,reputation:clubReputation(w,clubId),supporters:supporterCulture(w,clubId),honours:competitionHonoursBreakdown(w,clubId),records:deepClubRecordBook(w,clubId),eras:identity.eras,hallOfFame:identity.hall,rivals:identity.majorRivals,memories:strongestClubMemories(w,clubId,memoryLimit),managerLegacy:[...managers.values()].sort((a,b)=>b.score-a.score||b.titles-a.titles),transfers:{count:transfers.length,largestPurchases:purchases,largestSales:sales}}}
