import type { World } from './engine';
import { footballCompetition, type CompetitionRecord, type CompetitionRules } from './world-football-data-v1';

export type CompetitionRuleOverride={competitionId:string;validFromSeason?:number;validToSeason?:number;source:string;confidence:number;patch:Partial<CompetitionRules>};
const rules:CompetitionRuleOverride[]=[
 {competitionId:'comp-bra-1',validFromSeason:2006,source:'Brazilian league current format baseline',confidence:95,patch:{teams:20,pointsWin:3,pointsDraw:1,legs:2,rounds:38,tiebreakers:['points','wins','goalDifference','goalsFor'],relegation:[{toCompetitionId:'comp-bra-2',automaticSlots:4,fromRank:17,toRank:20}],promotion:[],calendarPattern:'calendar-year',usesPlayoffs:false}},
 {competitionId:'comp-bra-2',validFromSeason:2006,source:'Brazilian league current format baseline',confidence:95,patch:{teams:20,pointsWin:3,pointsDraw:1,legs:2,rounds:38,tiebreakers:['points','wins','goalDifference','goalsFor'],promotion:[{toCompetitionId:'comp-bra-1',automaticSlots:4,fromRank:1,toRank:4}],relegation:[{toCompetitionId:'comp-bra-3',automaticSlots:4,fromRank:17,toRank:20}],calendarPattern:'calendar-year',usesPlayoffs:false}},
 {competitionId:'comp-bra-3',validFromSeason:2024,source:'Brazilian Serie C structural baseline',confidence:70,patch:{pointsWin:3,pointsDraw:1,tiebreakers:['points','wins','goalDifference','goalsFor'],promotion:[{toCompetitionId:'comp-bra-2',automaticSlots:4}],relegation:[{toCompetitionId:'comp-bra-4',automaticSlots:4}],calendarPattern:'calendar-year',usesPlayoffs:true}},
 {competitionId:'comp-eng-1',validFromSeason:1995,source:'English Premier League structural baseline',confidence:95,patch:{teams:20,pointsWin:3,pointsDraw:1,legs:2,rounds:38,tiebreakers:['points','goalDifference','goalsFor'],relegation:[{toCompetitionId:'comp-eng-2',automaticSlots:3,fromRank:18,toRank:20}],calendarPattern:'cross-year',seasonStartMonth:8,seasonEndMonth:5,usesPlayoffs:false}},
 {competitionId:'comp-eng-2',validFromSeason:2004,source:'English Championship structural baseline',confidence:90,patch:{teams:24,pointsWin:3,pointsDraw:1,legs:2,rounds:46,tiebreakers:['points','goalDifference','goalsFor'],promotion:[{toCompetitionId:'comp-eng-1',automaticSlots:2,playoffSlots:1}],relegation:[{toCompetitionId:'comp-eng-3',automaticSlots:3}],calendarPattern:'cross-year',seasonStartMonth:8,seasonEndMonth:5,usesPlayoffs:true}}
];
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
function mergeRules(base:CompetitionRules,patch:Partial<CompetitionRules>):CompetitionRules{return{...base,...clone(patch),promotion:patch.promotion?clone(patch.promotion):base.promotion,relegation:patch.relegation?clone(patch.relegation):base.relegation,qualification:patch.qualification?clone(patch.qualification):base.qualification,tiebreakers:patch.tiebreakers?[...patch.tiebreakers]:base.tiebreakers}}
export function registerCompetitionRuleOverride(rule:CompetitionRuleOverride){rules.push(clone(rule));return rule}
export function ruleOverrides(){return rules.map(clone)}
export function rulesForCompetition(world:World,competitionId:string,season:number):CompetitionRules|undefined{const comp=footballCompetition(world,competitionId);if(!comp)return;const candidates=rules.filter(r=>r.competitionId===competitionId&&(r.validFromSeason===undefined||season>=r.validFromSeason)&&(r.validToSeason===undefined||season<=r.validToSeason)).sort((a,b)=>(b.validFromSeason??0)-(a.validFromSeason??0)||b.confidence-a.confidence);return candidates.reduce((acc,r)=>mergeRules(acc,r.patch),clone(comp.rules))}
export function applyCompetitionRuleOverrides(world:World,season=world.season){let applied=0;for(const rule of rules){if((rule.validFromSeason!==undefined&&season<rule.validFromSeason)||(rule.validToSeason!==undefined&&season>rule.validToSeason))continue;const comp=footballCompetition(world,rule.competitionId);if(!comp)continue;comp.rules=mergeRules(comp.rules,rule.patch);applied++}return applied}
export function competitionRuleAudit(world:World,season=world.season){const issues:string[]=[];for(const rule of rules){if((rule.validFromSeason!==undefined&&season<rule.validFromSeason)||(rule.validToSeason!==undefined&&season>rule.validToSeason))continue;const comp=footballCompetition(world,rule.competitionId);if(!comp)continue;const r=rulesForCompetition(world,comp.id,season)!;if(r.teams&&r.rounds&&r.legs===2&&r.rounds!==2*(r.teams-1))issues.push(`${comp.id}: rounds incompatíveis com double round-robin`);for(const x of [...r.promotion,...r.relegation])if(!footballCompetition(world,x.toCompetitionId))issues.push(`${comp.id}: regra aponta para ${x.toCompetitionId} ausente`)}return{ok:issues.length===0,issues,season}}
