import type { World } from './engine';
import { footballCompetition, footballDataSnapshot, registerMembership, registerTitle } from './world-football-data-v1';
import { createMatchCore } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { shootoutState } from './match-time-competition-v2';
import { defaultCompetitionRules } from './match-rules-v2';
import { persistCompletedMatchV2 } from './match-season-history-v2';
import { queueWorldEvent } from './world-core-v2';
import { ensureSquadRegistration } from './club-squad-registration-v1';
import { prepareClubCompetitionMatch, completeClubCompetitionDiscipline } from './club-competition-match-context-v1';
import { stageRegulation } from './club-competition-regulations-v2';
import { resetDisciplineStage } from './club-discipline-v1';

export type ContinentalFormat='libertadores-groups'|'uefa-league-phase';
export type ContinentalFixture={id:string;competitionId:string;season:number;stage:'group'|'league'|'playoff'|'r16'|'qf'|'sf'|'final';date:string;round:number;groupId?:string;tieId?:string;leg?:1|2;neutralVenue?:boolean;venueId?:string;homeTeamId:string;awayTeamId:string;homeGoals?:number;awayGoals?:number;penalties?:{home:number;away:number;winnerTeamId:string};played:boolean};
export type ContinentalStanding={teamId:string;p:number;w:number;d:number;l:number;gf:number;ga:number;gd:number;pts:number};
export type ContinentalClubSeason={id:string;competitionId:string;season:number;format:ContinentalFormat;teamIds:string[];groups?:Array<{id:string;teamIds:string[]}>;fixtures:ContinentalFixture[];phase:'primary'|'playoff'|'knockout'|'completed';completed:boolean;championTeamId?:string;runnerUpTeamId?:string};
type Runtime={seasons:Map<string,ContinentalClubSeason>};const states=new WeakMap<World,Runtime>();function state(w:World){let s=states.get(w);if(!s){s={seasons:new Map()};states.set(w,s)}return s}
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)},hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function club(w:World,id:string){return w.clubs.find(c=>c.id===id)}
function seeded(ids:string[],key:string){return[...ids].sort((a,b)=>hash(`${key}:${a}`)-hash(`${key}:${b}`))}
function roundRobin(comp:string,season:number,ids:string[],start:string,stage:'group'|'league',groupId?:string,legs=1){const out:ContinentalFixture[]=[];let round=1,day=0;for(let leg=0;leg<legs;leg++)for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const swap=leg%2===1,home=swap?ids[j]:ids[i],away=swap?ids[i]:ids[j];out.push({id:`${comp}-${season}-${stage}-${groupId??'all'}-${round}-${i}-${j}-${leg}`,competitionId:comp,season,stage,date:add(start,day++*7),round:round++,groupId,homeTeamId:home,awayTeamId:away,played:false})}return out}
function uefaLeagueFixtures(comp:string,season:number,ids:string[],start:string){const n=ids.length,out:ContinentalFixture[]=[];for(let r=0;r<8;r++){const rotated=ids.map((_,i)=>ids[(i+r+1)%n]);for(let i=0;i<n/2;i++){const a=ids[i],b=rotated[n-1-i];if(a===b)continue;const home=(r+i)%2?a:b,away=home===a?b:a,key=[home,away].sort().join(':');if(out.some(x=>[x.homeTeamId,x.awayTeamId].sort().join(':')===key))continue;out.push({id:`${comp}-${season}-league-r${r+1}-${i}`,competitionId:comp,season,stage:'league',date:add(start,r*21),round:r+1,homeTeamId:home,awayTeamId:away,played:false})}}return out}
export function createContinentalClubSeason(w:World,input:{competitionId:string;season?:number;teamIds:string[];startDate:string;format:ContinentalFormat}){const season=input.season??w.season,id=`${input.competitionId}-${season}`,s=state(w);if(s.seasons.has(id))return s.seasons.get(id)!;const comp=footballCompetition(w,input.competitionId);if(!comp||comp.scope!=='continental')throw new Error(`Not continental: ${input.competitionId}`);const needed=input.format==='libertadores-groups'?32:36,teams=seeded([...new Set(input.teamIds)],id).slice(0,needed);if(teams.length<Math.min(16,needed))throw new Error(`Insufficient continental clubs: ${teams.length}`);let groups:ContinentalClubSeason['groups'],fixtures:ContinentalFixture[]=[];if(input.format==='libertadores-groups'){groups=Array.from({length:8},(_,i)=>({id:String.fromCharCode(65+i),teamIds:[]}));teams.forEach((t,i)=>groups![i%8].teamIds.push(t));for(const g of groups)fixtures.push(...roundRobin(input.competitionId,season,g.teamIds,input.startDate,'group',g.id,2))}else fixtures=uefaLeagueFixtures(input.competitionId,season,teams,input.startDate);const x:ContinentalClubSeason={id,competitionId:input.competitionId,season,format:input.format,teamIds:teams,groups,fixtures,phase:'primary',completed:false};s.seasons.set(id,x);for(const teamId of teams){registerMembership(w,{season:String(season),competitionId:input.competitionId,teamId,teamKind:'club',status:'participant',source:'simulated',provenance:[{sourceId:'continental-club-runtime-v1',historical:false,confidence:100}]});if(w.clubs.some(c=>c.id===teamId))ensureSquadRegistration(w,input.competitionId,teamId,season,input.startDate)}return x}
export function continentalSeason(w:World,competitionId:string,season=w.season){return state(w).seasons.get(`${competitionId}-${season}`)}export function allContinentalSeasons(w:World){return[...state(w).seasons.values()]}
export function continentalTable(x:ContinentalClubSeason,groupId?:string){const ids=groupId?x.groups?.find(g=>g.id===groupId)?.teamIds??[]:x.teamIds,tab=new Map(ids.map(teamId=>[teamId,{teamId,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0} as ContinentalStanding]));for(const f of x.fixtures.filter(f=>f.played&&['group','league'].includes(f.stage)&&(groupId?f.groupId===groupId:true))){const h=tab.get(f.homeTeamId),a=tab.get(f.awayTeamId);if(!h||!a)continue;const hg=f.homeGoals??0,ag=f.awayGoals??0;h.p++;a.p++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.w++;a.l++;h.pts+=3}else if(ag>hg){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}}for(const t of tab.values())t.gd=t.gf-t.ga;return[...tab.values()].sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.teamId.localeCompare(b.teamId))}
function koStage(n:number):ContinentalFixture['stage']{return n>16?'playoff':n>8?'r16':n>4?'qf':n>2?'sf':'final'}
function neutralVenue(w:World,teams:string[],competitionId:string){const snap=footballDataSnapshot(w),clubMap=new Map(snap.clubs.map(c=>[c.id,c])),conf=footballCompetition(w,competitionId)?.confederationId,excluded=new Set(teams.flatMap(id=>clubMap.get(id)?.stadiumIds??[]));return snap.stadiums.filter(s=>!excluded.has(s.id)).filter(s=>{if(conf==='CONMEBOL')return['BRA','ARG','COL','URU','CHI','PAR','PER','ECU','BOL','VEN'].includes(s.countryId);if(conf==='UEFA')return!['BRA','ARG','COL','URU','CHI','PAR','PER','ECU','BOL','VEN'].includes(s.countryId);return true}).sort((a,b)=>(b.capacity??0)-(a.capacity??0))[0]?.id}
function buildKo(w:World,x:ContinentalClubSeason,ids:string[],date:string){const teams=seeded(ids,`${x.id}:${x.fixtures.length}`),stage=koStage(teams.length),reg=stageRegulation(w,x.competitionId,stage,x.season);if(reg.yellowResetBeforeStage)resetDisciplineStage(w,x.competitionId,x.season,stage);for(let i=0;i<teams.length;i+=2){if(!teams[i+1])continue;const a=teams[i],b=teams[i+1],tieId=`${x.id}-${stage}-tie-${i/2+1}`,baseRound=x.fixtures.length+1;if(reg.legs===2)x.fixtures.push({id:`${tieId}-l1`,competitionId:x.competitionId,season:x.season,stage,date:add(date,Math.floor(i/2)%3),round:baseRound,tieId,leg:1,homeTeamId:a,awayTeamId:b,played:false},{id:`${tieId}-l2`,competitionId:x.competitionId,season:x.season,stage,date:add(date,7+Math.floor(i/2)%3),round:baseRound+1,tieId,leg:2,homeTeamId:b,awayTeamId:a,played:false});else x.fixtures.push({id:`${tieId}-single`,competitionId:x.competitionId,season:x.season,stage,date:add(date,Math.floor(i/2)%3),round:baseRound,tieId,leg:1,neutralVenue:reg.neutralVenue,venueId:reg.neutralVenue?neutralVenue(w,[a,b],x.competitionId):undefined,homeTeamId:a,awayTeamId:b,played:false})}x.phase=stage==='playoff'?'playoff':'knockout'}
function tieWinner(fixtures:ContinentalFixture[]){const fs=[...fixtures].sort((a,b)=>(a.leg??1)-(b.leg??1));if(fs.length===1){const f=fs[0];if((f.homeGoals??0)>(f.awayGoals??0))return f.homeTeamId;if((f.awayGoals??0)>(f.homeGoals??0))return f.awayTeamId;return f.penalties?.winnerTeamId}const teams=[fs[0].homeTeamId,fs[0].awayTeamId],score=new Map(teams.map(t=>[t,0]));for(const f of fs){score.set(f.homeTeamId,(score.get(f.homeTeamId)??0)+(f.homeGoals??0));score.set(f.awayTeamId,(score.get(f.awayTeamId)??0)+(f.awayGoals??0))}const [a,b]=teams,sa=score.get(a)??0,sb=score.get(b)??0;if(sa>sb)return a;if(sb>sa)return b;return fs[fs.length-1].penalties?.winnerTeamId}
function stageWinners(x:ContinentalClubSeason,stage:ContinentalFixture['stage']){const fs=x.fixtures.filter(f=>f.stage===stage),groups=new Map<string,ContinentalFixture[]>();for(const f of fs){const k=f.tieId??f.id,list=groups.get(k)??[];list.push(f);groups.set(k,list)}return[...groups.values()].map(tieWinner).filter(Boolean) as string[]}
function advance(w:World,x:ContinentalClubSeason,date:string){if(x.phase==='primary'&&x.fixtures.filter(f=>['group','league'].includes(f.stage)).every(f=>f.played)){if(x.format==='libertadores-groups')buildKo(w,x,x.groups!.flatMap(g=>continentalTable(x,g.id).slice(0,2).map(r=>r.teamId)),add(date,14));else{const table=continentalTable(x),direct=table.slice(0,8).map(r=>r.teamId),play=table.slice(8,24).map(r=>r.teamId);(x as any).__directR16=direct;buildKo(w,x,play,add(date,14))}return}const stages=['playoff','r16','qf','sf','final'] as const,latest=[...stages].reverse().find(st=>x.fixtures.some(f=>f.stage===st));if(!latest)return;const fs=x.fixtures.filter(f=>f.stage===latest);if(fs.some(f=>!f.played))return;let winners=stageWinners(x,latest);if(latest==='playoff')winners=[...(((x as any).__directR16??[]) as string[]),...winners];if(winners.length===1){x.championTeamId=winners[0];const finalTeams=[...new Set(fs.flatMap(f=>[f.homeTeamId,f.awayTeamId]))];x.runnerUpTeamId=finalTeams.find(t=>t!==winners[0]);x.completed=true;x.phase='completed';registerTitle(w,{id:`title-${x.competitionId}-${x.season}-${winners[0]}`,teamId:winners[0],teamKind:'club',competitionId:x.competitionId,season:String(x.season),date,source:'simulated',provenance:[{sourceId:'continental-club-runtime-v1',historical:false,confidence:100}]});queueWorldEvent(w,{date,type:'ContinentalClubChampionCrowned',scope:'competition',entityIds:[x.competitionId,winners[0]],importance:9,payload:{champion:winners[0],runnerUp:x.runnerUpTeamId}});return}buildKo(w,x,winners,add(date,14))}
function aggregateBeforeSecondLeg(x:ContinentalClubSeason,f:ContinentalFixture){if(f.leg!==2||!f.tieId)return{home:0,away:0};const first=x.fixtures.find(q=>q.tieId===f.tieId&&q.leg===1&&q.played);if(!first)return{home:0,away:0};return{home:first.awayTeamId===f.homeTeamId?(first.awayGoals??0):(first.homeGoals??0),away:first.homeTeamId===f.awayTeamId?(first.homeGoals??0):(first.awayGoals??0)}}
export function playContinentalFixture(w:World,x:ContinentalClubSeason,f:ContinentalFixture){if(f.played)return f;const homeBase=club(w,f.homeTeamId),awayBase=club(w,f.awayTeamId);if(!homeBase||!awayBase)throw new Error(`Runtime club missing: ${f.homeTeamId}/${f.awayTeamId}`);const prepared=prepareClubCompetitionMatch(w,{home:homeBase,away:awayBase,competitionId:x.competitionId,date:f.date,season:x.season}),home=prepared.home,away=prepared.away,ko=!['group','league'].includes(f.stage),reg=stageRegulation(w,x.competitionId,f.stage,x.season),agg=aggregateBeforeSecondLeg(x,f),requiresWinner=ko&&(reg.legs===1||f.leg===2),m=createMatchCore(home,away,{seed:hash(`${x.id}:${f.id}`)});simulateMatchCore(m,home,away,36000,{requiresWinner,aggregateHome:requiresWinner&&reg.legs===2?agg.home:0,aggregateAway:requiresWinner&&reg.legs===2?agg.away:0,rules:{...defaultCompetitionRules,extraTime:reg.extraTime,awayGoals:reg.awayGoals}});f.homeGoals=m.home.score;f.awayGoals=m.away.score;const so=shootoutState(m);if(so)f.penalties={home:so.home,away:so.away,winnerTeamId:so.winnerClubId!};f.played=true;persistCompletedMatchV2(w,m,homeBase,awayBase,{fixtureId:f.id,competitionId:x.competitionId,date:f.date,round:f.round});completeClubCompetitionDiscipline(w,m,{home:homeBase,away:awayBase,competitionId:x.competitionId,date:f.date,season:x.season});queueWorldEvent(w,{date:f.date,type:'ContinentalClubMatchCompleted',scope:'competition',entityIds:[x.competitionId,f.homeTeamId,f.awayTeamId],importance:f.stage==='final'?8:5,payload:{stage:f.stage,leg:f.leg,neutral:f.neutralVenue,venueId:f.venueId,homeGoals:f.homeGoals,awayGoals:f.awayGoals,aggregateBefore:agg,penalties:f.penalties,eligibleHome:home.players.length,eligibleAway:away.players.length}});advance(w,x,f.date);return f}
export function playContinentalFixturesOnDate(w:World,date:string){const out:ContinentalFixture[]=[];for(const x of allContinentalSeasons(w))for(const f of x.fixtures.filter(f=>f.date===date&&!f.played))out.push(playContinentalFixture(w,x,f));return out}
export type ContinentalClubSnapshot={seasons:[string,ContinentalClubSeason][]};export function snapshotContinentalClubRuntime(w:World):ContinentalClubSnapshot{return{seasons:[...state(w).seasons].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}export function restoreContinentalClubRuntime(w:World,x:ContinentalClubSnapshot){states.set(w,{seasons:new Map((x?.seasons??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
