import type { World } from './engine';
import { footballCompetition, registerMembership, registerTitle } from './world-football-data-v1';
import { createMatchCore } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { shootoutState } from './match-time-competition-v2';
import { defaultCompetitionRules } from './match-rules-v2';
import { persistCompletedMatchV2 } from './match-season-history-v2';
import { queueWorldEvent } from './world-core-v2';

export type ContinentalFormat='libertadores-groups'|'uefa-league-phase';
export type ContinentalFixture={id:string;competitionId:string;season:number;stage:'group'|'league'|'playoff'|'r16'|'qf'|'sf'|'final';date:string;round:number;groupId?:string;homeTeamId:string;awayTeamId:string;homeGoals?:number;awayGoals?:number;penalties?:{home:number;away:number;winnerTeamId:string};played:boolean};
export type ContinentalStanding={teamId:string;p:number;w:number;d:number;l:number;gf:number;ga:number;gd:number;pts:number};
export type ContinentalClubSeason={id:string;competitionId:string;season:number;format:ContinentalFormat;teamIds:string[];groups?:Array<{id:string;teamIds:string[]}>;fixtures:ContinentalFixture[];phase:'primary'|'playoff'|'knockout'|'completed';completed:boolean;championTeamId?:string;runnerUpTeamId?:string};
type Runtime={seasons:Map<string,ContinentalClubSeason>};const states=new WeakMap<World,Runtime>();function state(w:World){let s=states.get(w);if(!s){s={seasons:new Map()};states.set(w,s)}return s}
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)},hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function club(w:World,id:string){return w.clubs.find(c=>c.id===id)}
function seeded(ids:string[],key:string){return[...ids].sort((a,b)=>hash(`${key}:${a}`)-hash(`${key}:${b}`))}
function roundRobin(comp:string,season:number,ids:string[],start:string,stage:'group'|'league',groupId?:string,legs=1){const out:ContinentalFixture[]=[];let round=1,day=0;for(let leg=0;leg<legs;leg++)for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const swap=leg%2===1,home=swap?ids[j]:ids[i],away=swap?ids[i]:ids[j];out.push({id:`${comp}-${season}-${stage}-${groupId??'all'}-${round}-${i}-${j}-${leg}`,competitionId:comp,season,stage,date:add(start,day++*7),round:round++,groupId,homeTeamId:home,awayTeamId:away,played:false})}return out}
function uefaLeagueFixtures(comp:string,season:number,ids:string[],start:string){const n=ids.length,out:ContinentalFixture[]=[];for(let r=0;r<8;r++){const rotated=ids.map((_,i)=>ids[(i+r+1)%n]);for(let i=0;i<n/2;i++){const a=ids[i],b=rotated[n-1-i];if(a===b)continue;const home=(r+i)%2?a:b,away=home===a?b:a;const key=[home,away].sort().join(':');if(out.some(x=>[x.homeTeamId,x.awayTeamId].sort().join(':')===key))continue;out.push({id:`${comp}-${season}-league-r${r+1}-${i}`,competitionId:comp,season,stage:'league',date:add(start,r*21),round:r+1,homeTeamId:home,awayTeamId:away,played:false})}}return out}
export function createContinentalClubSeason(w:World,input:{competitionId:string;season?:number;teamIds:string[];startDate:string;format:ContinentalFormat}){const season=input.season??w.season,id=`${input.competitionId}-${season}`,s=state(w);if(s.seasons.has(id))return s.seasons.get(id)!;const comp=footballCompetition(w,input.competitionId);if(!comp||comp.scope!=='continental')throw new Error(`Not continental: ${input.competitionId}`);const needed=input.format==='libertadores-groups'?32:36,teams=seeded([...new Set(input.teamIds)],id).slice(0,needed);if(teams.length<Math.min(16,needed))throw new Error(`Insufficient continental clubs: ${teams.length}`);let groups:ContinentalClubSeason['groups'],fixtures:ContinentalFixture[]=[];if(input.format==='libertadores-groups'){groups=Array.from({length:8},(_,i)=>({id:String.fromCharCode(65+i),teamIds:[]}));teams.forEach((t,i)=>groups![i%8].teamIds.push(t));for(const g of groups)fixtures.push(...roundRobin(input.competitionId,season,g.teamIds,input.startDate,'group',g.id,2))}else fixtures=uefaLeagueFixtures(input.competitionId,season,teams,input.startDate);const x:ContinentalClubSeason={id,competitionId:input.competitionId,season,format:input.format,teamIds:teams,groups,fixtures,phase:'primary',completed:false};s.seasons.set(id,x);for(const teamId of teams)registerMembership(w,{season:String(season),competitionId:input.competitionId,teamId,teamKind:'club',status:'participant',source:'simulated',provenance:[{sourceId:'continental-club-runtime-v1',historical:false,confidence:100}]});return x}
export function continentalSeason(w:World,competitionId:string,season=w.season){return state(w).seasons.get(`${competitionId}-${season}`)}export function allContinentalSeasons(w:World){return[...state(w).seasons.values()]}
export function continentalTable(x:ContinentalClubSeason,groupId?:string){const ids=groupId?x.groups?.find(g=>g.id===groupId)?.teamIds??[]:x.teamIds,tab=new Map(ids.map(teamId=>[teamId,{teamId,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0} as ContinentalStanding]));for(const f of x.fixtures.filter(f=>f.played&&['group','league'].includes(f.stage)&&(groupId?f.groupId===groupId:true))){const h=tab.get(f.homeTeamId),a=tab.get(f.awayTeamId);if(!h||!a)continue;const hg=f.homeGoals??0,ag=f.awayGoals??0;h.p++;a.p++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.w++;a.l++;h.pts+=3}else if(ag>hg){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}}for(const t of tab.values())t.gd=t.gf-t.ga;return[...tab.values()].sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.teamId.localeCompare(b.teamId))}
function koStage(n:number):ContinentalFixture['stage']{return n>16?'playoff':n>8?'r16':n>4?'qf':n>2?'sf':'final'}
function buildKo(x:ContinentalClubSeason,ids:string[],date:string){const teams=seeded(ids,`${x.id}:${x.fixtures.length}`),stage=koStage(teams.length);for(let i=0;i<teams.length;i+=2)if(teams[i+1])x.fixtures.push({id:`${x.id}-${stage}-${i/2+1}`,competitionId:x.competitionId,season:x.season,stage,date:add(date,Math.floor(i/2)%3),round:x.fixtures.length+1,homeTeamId:teams[i],awayTeamId:teams[i+1],played:false});x.phase=stage==='playoff'?'playoff':'knockout'}
function winner(f:ContinentalFixture){if((f.homeGoals??0)>(f.awayGoals??0))return f.homeTeamId;if((f.awayGoals??0)>(f.homeGoals??0))return f.awayTeamId;return f.penalties?.winnerTeamId}
function advance(w:World,x:ContinentalClubSeason,date:string){if(x.phase==='primary'&&x.fixtures.filter(f=>['group','league'].includes(f.stage)).every(f=>f.played)){if(x.format==='libertadores-groups'){const ids=x.groups!.flatMap(g=>continentalTable(x,g.id).slice(0,2).map(r=>r.teamId));buildKo(x,ids,add(date,14))}else{const table=continentalTable(x),direct=table.slice(0,8).map(r=>r.teamId),play=table.slice(8,24).map(r=>r.teamId);(x as any).__directR16=direct;buildKo(x,play,add(date,14))}return}const stages=['playoff','r16','qf','sf','final'] as const;const latest=[...stages].reverse().find(st=>x.fixtures.some(f=>f.stage===st));if(!latest)return;const fs=x.fixtures.filter(f=>f.stage===latest);if(fs.some(f=>!f.played))return;let winners=fs.map(winner).filter(Boolean) as string[];if(latest==='playoff')winners=[...(((x as any).__directR16??[]) as string[]),...winners];if(winners.length===1){x.championTeamId=winners[0];const f=fs[0];x.runnerUpTeamId=f.homeTeamId===winners[0]?f.awayTeamId:f.homeTeamId;x.completed=true;x.phase='completed';registerTitle(w,{id:`title-${x.competitionId}-${x.season}-${winners[0]}`,teamId:winners[0],teamKind:'club',competitionId:x.competitionId,season:String(x.season),date,source:'simulated',provenance:[{sourceId:'continental-club-runtime-v1',historical:false,confidence:100}]});queueWorldEvent(w,{date,type:'ContinentalClubChampionCrowned',scope:'competition',entityIds:[x.competitionId,winners[0]],importance:9,payload:{champion:winners[0],runnerUp:x.runnerUpTeamId}});return}buildKo(x,winners,add(date,14))}
export function playContinentalFixture(w:World,x:ContinentalClubSeason,f:ContinentalFixture){if(f.played)return f;const home=club(w,f.homeTeamId),away=club(w,f.awayTeamId);if(!home||!away)throw new Error(`Runtime club missing: ${f.homeTeamId}/${f.awayTeamId}`);const ko=!['group','league'].includes(f.stage),m=createMatchCore(home,away,{seed:hash(`${x.id}:${f.id}`)});simulateMatchCore(m,home,away,36000,{requiresWinner:ko,rules:defaultCompetitionRules});f.homeGoals=m.home.score;f.awayGoals=m.away.score;const so=shootoutState(m);if(so)f.penalties={home:so.home,away:so.away,winnerTeamId:so.winnerClubId!};f.played=true;persistCompletedMatchV2(w,m,home,away,{fixtureId:f.id,competitionId:x.competitionId,date:f.date,round:f.round});queueWorldEvent(w,{date:f.date,type:'ContinentalClubMatchCompleted',scope:'competition',entityIds:[x.competitionId,f.homeTeamId,f.awayTeamId],importance:f.stage==='final'?8:5,payload:{stage:f.stage,homeGoals:f.homeGoals,awayGoals:f.awayGoals,penalties:f.penalties}});advance(w,x,f.date);return f}
export function playContinentalFixturesOnDate(w:World,date:string){const out:ContinentalFixture[]=[];for(const x of allContinentalSeasons(w))for(const f of x.fixtures.filter(f=>f.date===date&&!f.played))out.push(playContinentalFixture(w,x,f));return out}
export type ContinentalClubSnapshot={seasons:[string,ContinentalClubSeason][]};export function snapshotContinentalClubRuntime(w:World):ContinentalClubSnapshot{return{seasons:[...state(w).seasons].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}export function restoreContinentalClubRuntime(w:World,x:ContinentalClubSnapshot){states.set(w,{seasons:new Map((x?.seasons??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
