import type { World } from './engine';
import { domesticStandings, domesticSeason } from './domestic-competition-runtime-v1';
import { footballDataSnapshot, registerMembership } from './world-football-data-v1';
import { queueWorldEvent } from './world-core-v2';
import { coefficientSlotAdjustment } from './continental-coefficient-v1';
import { applyQualificationEntitlements, entitlementTeamsFor } from './club-qualification-entitlements-v1';

export type ContinentalQualificationProfile={confederationId:string;primaryCompetitionId:string;secondaryCompetitionId?:string;countrySlots:Record<string,{primary:number;secondary?:number}>};
const profiles:ContinentalQualificationProfile[]=[
 {confederationId:'CONMEBOL',primaryCompetitionId:'comp-conmebol-libertadores',secondaryCompetitionId:'comp-conmebol-sudamericana',countrySlots:{BRA:{primary:6,secondary:6},ARG:{primary:6,secondary:6},COL:{primary:4,secondary:4},URU:{primary:4,secondary:4},CHI:{primary:4,secondary:4},PAR:{primary:4,secondary:4},PER:{primary:4,secondary:4},ECU:{primary:4,secondary:4},BOL:{primary:4,secondary:4},VEN:{primary:4,secondary:4}}},
 {confederationId:'UEFA',primaryCompetitionId:'comp-uefa-cl',secondaryCompetitionId:'comp-uefa-el',countrySlots:{ENG:{primary:4,secondary:2},ESP:{primary:4,secondary:2},ITA:{primary:4,secondary:2},GER:{primary:4,secondary:2},FRA:{primary:3,secondary:2},POR:{primary:2,secondary:2},NED:{primary:2,secondary:2},BEL:{primary:1,secondary:2}}}
];
export function continentalQualificationProfiles(){return profiles.map(x=>JSON.parse(JSON.stringify(x)))}
function topLeague(world:World,countryId:string){return footballDataSnapshot(world).competitions.filter(c=>c.countryId===countryId&&c.scope==='domestic'&&c.kind==='league'&&c.level===1).sort((a,b)=>a.id.localeCompare(b.id))[0]}
function countryOf(world:World,teamId:string){return footballDataSnapshot(world).clubs.find(c=>c.id===teamId)?.countryId}
function alreadyQualified(world:World,competitionId:string,season:number){return new Set(footballDataSnapshot(world).memberships.filter(m=>m.competitionId===competitionId&&Number(m.season)===season&&m.status==='qualified').map(m=>m.teamId))}
function register(world:World,competitionId:string,season:number,teamId:string,confidence:number){if(alreadyQualified(world,competitionId,season).has(teamId))return false;registerMembership(world,{season:String(season),competitionId,teamId,teamKind:'club',status:'qualified',source:'simulated',provenance:[{sourceId:'continental-club-qualification-v1',historical:false,confidence}]});return true}
export function qualifyClubsForContinentalSeason(world:World,input:{confederationId:string;domesticSeason:number;continentalSeason?:number}){const profile=profiles.find(p=>p.confederationId===input.confederationId);if(!profile)throw new Error(`No continental qualification profile for ${input.confederationId}`);const continentalSeason=input.continentalSeason??input.domesticSeason+1,entitlements=applyQualificationEntitlements(world,input.domesticSeason,continentalSeason).created,qualifiedPrimary:string[]=entitlements.filter(x=>x.toCompetitionId===profile.primaryCompetitionId).map(x=>x.teamId),qualifiedSecondary:string[]=entitlements.filter(x=>x.toCompetitionId===profile.secondaryCompetitionId).map(x=>x.teamId),warnings:string[]=[],slotAdjustments:Record<string,number>={};
 for(const [countryId,baseSlots] of Object.entries(profile.countrySlots)){const league=topLeague(world,countryId);if(!league){warnings.push(`${countryId}: top division missing`);continue}const s=domesticSeason(world,league.id,input.domesticSeason);if(!s?.completed){warnings.push(`${countryId}: domestic season ${input.domesticSeason} incomplete`);continue}const adjustment=coefficientSlotAdjustment(world,input.confederationId,countryId,continentalSeason),primarySlots=Math.max(1,baseSlots.primary+adjustment),secondarySlots=Math.max(0,(baseSlots.secondary??0)-Math.max(0,adjustment));slotAdjustments[countryId]=adjustment;const primaryEnt=entitlementTeamsFor(world,profile.primaryCompetitionId,input.domesticSeason,continentalSeason).filter(x=>countryOf(world,x.teamId)===countryId&&!x.extraSlot),secondaryEnt=profile.secondaryCompetitionId?entitlementTeamsFor(world,profile.secondaryCompetitionId,input.domesticSeason,continentalSeason).filter(x=>countryOf(world,x.teamId)===countryId&&!x.extraSlot):[],table=domesticStandings(world,league.id,input.domesticSeason),blocked=new Set(entitlements.map(x=>x.teamId)),ordered=table.map(x=>x.teamId).filter(id=>!blocked.has(id)),primaryNeed=Math.max(0,primarySlots-primaryEnt.length),primary=ordered.slice(0,primaryNeed),secondaryStart=primary.length,secondaryNeed=Math.max(0,secondarySlots-secondaryEnt.length),secondary=ordered.slice(secondaryStart,secondaryStart+secondaryNeed);
  for(const teamId of primary)if(register(world,profile.primaryCompetitionId,continentalSeason,teamId,95)){qualifiedPrimary.push(teamId);blocked.add(teamId)}if(profile.secondaryCompetitionId)for(const teamId of secondary)if(register(world,profile.secondaryCompetitionId,continentalSeason,teamId,90)){qualifiedSecondary.push(teamId);blocked.add(teamId)}}
 queueWorldEvent(world,{date:`${continentalSeason}-01-05`,type:'ContinentalClubQualificationCompleted',scope:'competition',entityIds:[profile.primaryCompetitionId,...qualifiedPrimary],importance:5,payload:{confederationId:input.confederationId,domesticSeason:input.domesticSeason,continentalSeason,primary:[...new Set(qualifiedPrimary)],secondary:[...new Set(qualifiedSecondary)],entitlements,slotAdjustments,warnings}});return{profile,continentalSeason,qualifiedPrimary:[...new Set(qualifiedPrimary)],qualifiedSecondary:[...new Set(qualifiedSecondary)],entitlements,slotAdjustments,warnings}}
export function qualifiedClubs(world:World,competitionId:string,season:number){return [...new Set(footballDataSnapshot(world).memberships.filter(m=>m.competitionId===competitionId&&Number(m.season)===season&&m.teamKind==='club'&&m.status==='qualified').map(m=>m.teamId))]}
