import type { World } from './engine';
import { domesticStandings, domesticSeason } from './domestic-competition-runtime-v1';
import { footballCompetition, footballDataSnapshot, registerMembership } from './world-football-data-v1';
import { queueWorldEvent } from './world-core-v2';

export type ContinentalQualificationProfile={confederationId:string;primaryCompetitionId:string;secondaryCompetitionId?:string;countrySlots:Record<string,{primary:number;secondary?:number}>};
const profiles:ContinentalQualificationProfile[]=[
 {confederationId:'CONMEBOL',primaryCompetitionId:'comp-conmebol-libertadores',secondaryCompetitionId:'comp-conmebol-sudamericana',countrySlots:{BRA:{primary:6,secondary:6},ARG:{primary:6,secondary:6},COL:{primary:4,secondary:4},URU:{primary:4,secondary:4},CHI:{primary:4,secondary:4},PAR:{primary:4,secondary:4},PER:{primary:4,secondary:4},ECU:{primary:4,secondary:4},BOL:{primary:4,secondary:4},VEN:{primary:4,secondary:4}}},
 {confederationId:'UEFA',primaryCompetitionId:'comp-uefa-cl',secondaryCompetitionId:'comp-uefa-el',countrySlots:{ENG:{primary:4,secondary:2},ESP:{primary:4,secondary:2},ITA:{primary:4,secondary:2},GER:{primary:4,secondary:2},FRA:{primary:3,secondary:2},POR:{primary:2,secondary:2},NED:{primary:2,secondary:2},BEL:{primary:1,secondary:2}}}
];
export function continentalQualificationProfiles(){return profiles.map(x=>JSON.parse(JSON.stringify(x)))}
function topLeague(world:World,countryId:string){return footballDataSnapshot(world).competitions.filter(c=>c.countryId===countryId&&c.scope==='domestic'&&c.kind==='league'&&c.level===1).sort((a,b)=>a.id.localeCompare(b.id))[0]}
export function qualifyClubsForContinentalSeason(world:World,input:{confederationId:string;domesticSeason:number;continentalSeason?:number}){const profile=profiles.find(p=>p.confederationId===input.confederationId);if(!profile)throw new Error(`No continental qualification profile for ${input.confederationId}`);const continentalSeason=input.continentalSeason??input.domesticSeason+1,qualifiedPrimary:string[]=[],qualifiedSecondary:string[]=[],warnings:string[]=[];for(const [countryId,slots] of Object.entries(profile.countrySlots)){const league=topLeague(world,countryId);if(!league){warnings.push(`${countryId}: top division missing`);continue}const s=domesticSeason(world,league.id,input.domesticSeason);if(!s?.completed){warnings.push(`${countryId}: domestic season ${input.domesticSeason} incomplete`);continue}const table=domesticStandings(world,league.id,input.domesticSeason),primary=table.slice(0,slots.primary).map(x=>x.teamId),secondary=table.slice(slots.primary,slots.primary+(slots.secondary??0)).map(x=>x.teamId);for(const teamId of primary){registerMembership(world,{season:String(continentalSeason),competitionId:profile.primaryCompetitionId,teamId,teamKind:'club',status:'qualified',source:'simulated',provenance:[{sourceId:'continental-club-qualification-v1',historical:false,confidence:95}]});qualifiedPrimary.push(teamId)}if(profile.secondaryCompetitionId)for(const teamId of secondary){registerMembership(world,{season:String(continentalSeason),competitionId:profile.secondaryCompetitionId,teamId,teamKind:'club',status:'qualified',source:'simulated',provenance:[{sourceId:'continental-club-qualification-v1',historical:false,confidence:90}]});qualifiedSecondary.push(teamId)}}queueWorldEvent(world,{date:`${continentalSeason}-01-05`,type:'ContinentalClubQualificationCompleted',scope:'competition',entityIds:[profile.primaryCompetitionId,...qualifiedPrimary],importance:5,payload:{confederationId:input.confederationId,domesticSeason:input.domesticSeason,continentalSeason,primary:qualifiedPrimary,secondary:qualifiedSecondary,warnings}});return{profile,continentalSeason,qualifiedPrimary,qualifiedSecondary,warnings}}
export function qualifiedClubs(world:World,competitionId:string,season:number){return [...new Set(footballDataSnapshot(world).memberships.filter(m=>m.competitionId===competitionId&&Number(m.season)===season&&m.teamKind==='club'&&m.status==='qualified').map(m=>m.teamId))]}
