import type { World } from './engine';
import { allContinentalSeasons } from './continental-club-runtime-v1';
import { footballDataSnapshot } from './world-football-data-v1';

export type CountryCoefficient={countryId:string;confederationId:string;season:number;points:number;clubs:number;normalized:number};
export type RollingCoefficient={countryId:string;confederationId:string;seasons:CountryCoefficient[];total:number;rank:number};
function countryOf(w:World,clubId:string){return footballDataSnapshot(w).clubs.find(c=>c.id===clubId)?.countryId}
function confedForCompetition(id:string){return id.includes('conmebol')?'CONMEBOL':id.includes('uefa')?'UEFA':'OTHER'}
export function countryCoefficientForSeason(w:World,countryId:string,season:number,confederationId:string){let points=0;const clubs=new Set<string>();for(const s of allContinentalSeasons(w).filter(x=>x.season===season&&confedForCompetition(x.competitionId)===confederationId)){for(const teamId of s.teamIds)if(countryOf(w,teamId)===countryId)clubs.add(teamId);for(const f of s.fixtures.filter(x=>x.played)){const hc=countryOf(w,f.homeTeamId),ac=countryOf(w,f.awayTeamId),hg=f.homeGoals??0,ag=f.awayGoals??0;if(hc===countryId)points+=hg>ag?2:hg===ag?1:0;if(ac===countryId)points+=ag>hg?2:hg===ag?1:0}if(s.championTeamId&&countryOf(w,s.championTeamId)===countryId)points+=8;if(s.runnerUpTeamId&&countryOf(w,s.runnerUpTeamId)===countryId)points+=4}const n=clubs.size,normalized=n?Number((points/n).toFixed(3)):0;return{countryId,confederationId,season,points,clubs:n,normalized} as CountryCoefficient}
export function rollingContinentalCoefficients(w:World,confederationId:string,season:number,window=5){const snap=footballDataSnapshot(w),countries=[...new Set(snap.clubs.map(c=>c.countryId))],rows=countries.map(countryId=>{const seasons:Array<CountryCoefficient>=[];for(let y=season-window+1;y<=season;y++)seasons.push(countryCoefficientForSeason(w,countryId,y,confederationId));return{countryId,confederationId,seasons,total:Number(seasons.reduce((a,b)=>a+b.normalized,0).toFixed(3)),rank:0} as RollingCoefficient}).filter(x=>x.total>0).sort((a,b)=>b.total-a.total||a.countryId.localeCompare(b.countryId));rows.forEach((x,i)=>x.rank=i+1);return rows}
export function coefficientSlotAdjustment(w:World,confederationId:string,countryId:string,season:number){const table=rollingContinentalCoefficients(w,confederationId,season-1,5),row=table.find(x=>x.countryId===countryId);if(!row)return 0;if(confederationId==='UEFA'){if(row.rank<=2)return 1;if(row.rank>=8)return-1}if(confederationId==='CONMEBOL'){if(row.rank<=2)return 1;if(row.rank>=7)return-1}return 0}
