import type { World } from './engine';
import { footballCompetition, footballDataSnapshot, registerMembership, registerTitle } from './world-football-data-v1';
import { rulesForCompetition } from './competition-rule-normalizer-v1';
import { queueWorldEvent } from './world-core-v2';
import { rememberClubMoment, recordManagerAchievement } from './club-institutional-memory-v1';
import { managerByClub } from './manager-character';

export type LeagueFixture={id:string;competitionId:string;season:number;round:number;date:string;homeTeamId:string;awayTeamId:string;homeGoals?:number;awayGoals?:number;played:boolean};
export type LeagueStanding={teamId:string;p:number;w:number;d:number;l:number;gf:number;ga:number;gd:number;pts:number};
export type DomesticSeasonState={id:string;competitionId:string;season:number;teamIds:string[];fixtures:LeagueFixture[];completed:boolean;championTeamId?:string;promotedTeamIds:string[];relegatedTeamIds:string[];playoffTeamIds:string[]};
type Runtime={seasons:Map<string,DomesticSeasonState>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={seasons:new Map()};states.set(w,s)}return s}
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
function seasonStartDate(w:World,competitionId:string,season:number){const r=rulesForCompetition(w,competitionId,season),month=r?.seasonStartMonth??(r?.calendarPattern==='calendar-year'?4:8),year=r?.calendarPattern==='calendar-year'?season:season;return`${year}-${String(month).padStart(2,'0')}-01`}
function participants(w:World,competitionId:string,season:number){const snap=footballDataSnapshot(w),m=snap.memberships.filter(x=>x.competitionId===competitionId&&Number(x.season)===season&&['participant','qualified','promoted','relegated'].includes(x.status)).map(x=>x.teamId);if(m.length)return[...new Set(m)];const c=footballCompetition(w,competitionId);return snap.clubs.filter(x=>x.active&&x.countryId===c?.countryId).slice(0,c?.rules.teams??20).map(x=>x.id)}
function circleFixtures(teams:string[],competitionId:string,season:number,start:string){const list=[...teams];if(list.length%2)list.push('__BYE__');const n=list.length,rounds=n-1,out:LeagueFixture[]=[];for(let r=0;r<rounds;r++){for(let i=0;i<n/2;i++){const a=list[i],b=list[n-1-i];if(a!=='__BYE__'&&b!=='__BYE__'){const flip=(r+i)%2===1,home=flip?b:a,away=flip?a:b;out.push({id:`${competitionId}-${season}-r${r+1}-${home}-${away}`,competitionId,season,round:r+1,date:add(start,r*7),homeTeamId:home,awayTeamId:away,played:false})}}list.splice(1,0,list.pop()!)}const first=[...out];for(const f of first)out.push({id:`${competitionId}-${season}-r${f.round+rounds}-${f.awayTeamId}-${f.homeTeamId}`,competitionId,season,round:f.round+rounds,date:add(start,(f.round-1+rounds)*7),homeTeamId:f.awayTeamId,awayTeamId:f.homeTeamId,played:false});return out}
export function ensureDomesticSeason(w:World,competitionId:string,season=w.season){const id=`${competitionId}-${season}`,s=state(w);if(s.seasons.has(id))return s.seasons.get(id)!;const comp=footballCompetition(w,competitionId);if(!comp||comp.kind!=='league'||comp.scope!=='domestic')throw new Error(`Not a domestic league: ${competitionId}`);const teamIds=participants(w,competitionId,season),r=rulesForCompetition(w,competitionId,season);if(r?.teams&&teamIds.length!==r.teams)queueWorldEvent(w,{date:seasonStartDate(w,competitionId,season),type:'DomesticCompetitionParticipantMismatch',scope:'competition',entityIds:[competitionId],importance:3,payload:{expected:r.teams,actual:teamIds.length}});const x:DomesticSeasonState={id,competitionId,season,teamIds,fixtures:circleFixtures(teamIds,competitionId,season,seasonStartDate(w,competitionId,season)),completed:false,promotedTeamIds:[],relegatedTeamIds:[],playoffTeamIds:[]};s.seasons.set(id,x);for(const teamId of teamIds)registerMembership(w,{season:String(season),competitionId,teamId,teamKind:'club',status:'participant',source:'simulated',provenance:[{sourceId:'domestic-competition-runtime-v1',historical:false,confidence:100}]});return x}
export function domesticStandings(w:World,competitionId:string,season=w.season){const s=ensureDomesticSeason(w,competitionId,season),r=rulesForCompetition(w,competitionId,season),table=new Map(s.teamIds.map(teamId=>[teamId,{teamId,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0} as LeagueStanding]));for(const f of s.fixtures.filter(x=>x.played)){const h=table.get(f.homeTeamId)!,a=table.get(f.awayTeamId)!,hg=f.homeGoals??0,ag=f.awayGoals??0;h.p++;a.p++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.w++;a.l++;h.pts+=r?.pointsWin??3}else if(ag>hg){a.w++;h.l++;a.pts+=r?.pointsWin??3}else{h.d++;a.d++;h.pts+=r?.pointsDraw??1;a.pts+=r?.pointsDraw??1}}for(const x of table.values())x.gd=x.gf-x.ga;return [...table.values()].sort((a,b)=>b.pts-a.pts||b.w-a.w||b.gd-a.gd||b.gf-a.gf||a.teamId.localeCompare(b.teamId))}
export function recordDomesticLeagueResult(w:World,input:{competitionId:string;season?:number;fixtureId:string;homeGoals:number;awayGoals:number}){const season=input.season??w.season,s=ensureDomesticSeason(w,input.competitionId,season),f=s.fixtures.find(x=>x.id===input.fixtureId);if(!f)throw new Error(`Unknown fixture ${input.fixtureId}`);if(f.played)return f;f.homeGoals=input.homeGoals;f.awayGoals=input.awayGoals;f.played=true;if(s.fixtures.every(x=>x.played))finalizeDomesticSeason(w,input.competitionId,season,f.date);return f}
export function finalizeDomesticSeason(w:World,competitionId:string,season=w.season,date=`${season}-12-31`){const s=ensureDomesticSeason(w,competitionId,season);if(s.completed)return s;if(s.fixtures.some(x=>!x.played))throw new Error(`Domestic season incomplete: ${s.id}`);const table=domesticStandings(w,competitionId,season),r=rulesForCompetition(w,competitionId,season),comp=footballCompetition(w,competitionId);s.championTeamId=table[0]?.teamId;s.completed=true;if(s.championTeamId){registerTitle(w,{id:`title-${competitionId}-${season}-${s.championTeamId}`,teamId:s.championTeamId,teamKind:'club',competitionId,season:String(season),date,source:'simulated',provenance:[{sourceId:'domestic-competition-runtime-v1',historical:false,confidence:100}]});rememberClubMoment(w,{clubId:s.championTeamId,date,season,type:'title',importance:comp?.level===1?86:68,sentiment:'positive',summary:`Título de ${comp?.name??competitionId} conquistado.`,competitionId,entityIds:[],payload:{season,position:1,points:table[0]?.pts},audience:{supporters:100,board:100,media:94},permanent:true});const mgr=managerByClub(w,s.championTeamId);if(mgr)recordManagerAchievement(w,{date,season,managerId:mgr.id,clubId:s.championTeamId,competitionId,kind:'title',weight:comp?.level===1?86:68,summary:`Conduziu o clube ao título de ${comp?.name??competitionId}.`})}
 for(const pr of r?.promotion??[]){const from=pr.fromRank??1,to=pr.toRank??pr.automaticSlots;s.promotedTeamIds.push(...table.slice(from-1,to).map(x=>x.teamId));if(pr.playoffSlots)s.playoffTeamIds.push(...table.slice(to,to+pr.playoffSlots+3).map(x=>x.teamId))}for(const rr of r?.relegation??[]){const from=rr.fromRank??Math.max(1,table.length-rr.automaticSlots+1),to=rr.toRank??table.length;s.relegatedTeamIds.push(...table.slice(from-1,to).map(x=>x.teamId));if(rr.playoffSlots)s.playoffTeamIds.push(...table.slice(Math.max(0,from-1-rr.playoffSlots),from-1).map(x=>x.teamId))}
 for(const clubId of [...new Set(s.promotedTeamIds)]){rememberClubMoment(w,{clubId,date,season,type:'promotion',importance:72,sentiment:'positive',summary:`Acesso conquistado em ${comp?.name??competitionId}.`,competitionId,entityIds:[],payload:{season},audience:{supporters:96,board:94,media:75},permanent:true});const mgr=managerByClub(w,clubId);if(mgr)recordManagerAchievement(w,{date,season,managerId:mgr.id,clubId,competitionId,kind:'promotion',weight:72,summary:`Conduziu o clube ao acesso em ${comp?.name??competitionId}.`})}for(const clubId of [...new Set(s.relegatedTeamIds)])rememberClubMoment(w,{clubId,date,season,type:'relegation',importance:78,sentiment:'negative',summary:`Rebaixamento sofrido em ${comp?.name??competitionId}.`,competitionId,entityIds:[],payload:{season},audience:{supporters:100,board:100,media:90},permanent:true});queueWorldEvent(w,{date,type:'DomesticSeasonCompleted',scope:'competition',entityIds:[competitionId,...(s.championTeamId?[s.championTeamId]:[])],importance:6,payload:{season,champion:s.championTeamId,promoted:s.promotedTeamIds,relegated:s.relegatedTeamIds,playoff:s.playoffTeamIds}});return s}
export function domesticSeason(w:World,competitionId:string,season=w.season){return state(w).seasons.get(`${competitionId}-${season}`)}
export function allDomesticSeasons(w:World){return [...state(w).seasons.values()]}
export type DomesticCompetitionSnapshot={seasons:[string,DomesticSeasonState][]};export function snapshotDomesticCompetitions(w:World):DomesticCompetitionSnapshot{return{seasons:[...state(w).seasons].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}export function restoreDomesticCompetitions(w:World,x:DomesticCompetitionSnapshot){states.set(w,{seasons:new Map((x?.seasons??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
