import type { Fixture, World } from './engine';
import { domesticSeason, recordDomesticLeagueResult, type LeagueFixture } from './domestic-competition-runtime-v1';
import { simulateFixtureV2 } from './match-world-integration-v2';
import { recordHomeMatchCommercial } from './club-commercial-finance';
import { emitWorldEvent } from './event-bus';
import { queueWorldEvent } from './world-core-v2';

function legacyFixture(f:LeagueFixture):Fixture{return{round:f.round,home:f.homeTeamId,away:f.awayTeamId,played:false} as Fixture}
export function playDomesticFixtureV1(world:World,input:{competitionId:string;season:number;fixtureId:string}){const season=domesticSeason(world,input.competitionId,input.season);if(!season)throw new Error(`Domestic season missing: ${input.competitionId}-${input.season}`);const f=season.fixtures.find(x=>x.id===input.fixtureId);if(!f)throw new Error(`Domestic fixture missing: ${input.fixtureId}`);if(f.played)return f;const lf=legacyFixture(f),state=simulateFixtureV2(world,lf,{competitionId:input.competitionId,date:f.date});recordDomesticLeagueResult(world,{competitionId:input.competitionId,season:input.season,fixtureId:f.id,homeGoals:lf.homeGoals??0,awayGoals:lf.awayGoals??0});recordHomeMatchCommercial(world,f.homeTeamId,f.date);queueWorldEvent(world,{date:f.date,type:'DomesticLeagueMatchCompleted',scope:'competition',entityIds:[input.competitionId,f.homeTeamId,f.awayTeamId],importance:3,payload:{fixtureId:f.id,season:input.season,round:f.round,homeGoals:lf.homeGoals,awayGoals:lf.awayGoals,homeXg:lf.homeXg,awayXg:lf.awayXg}});emitWorldEvent(world,{type:'DomesticLeagueMatchCompleted',date:f.date,clubIds:[f.homeTeamId,f.awayTeamId],importance:3,summary:`${f.homeTeamId} ${lf.homeGoals}–${lf.awayGoals} ${f.awayTeamId}.`,payload:{competitionId:input.competitionId,fixtureId:f.id,round:f.round}});return{...f,homeGoals:lf.homeGoals,awayGoals:lf.awayGoals,state}}
}
export function playDomesticFixturesOnDate(world:World,date:string){const out:any[]=[];for(const season of snapshotDomesticSeasons(world))for(const f of season.fixtures.filter(x=>x.date===date&&!x.played))out.push(playDomesticFixtureV1(world,{competitionId:season.competitionId,season:season.season,fixtureId:f.id}));return out}
function snapshotDomesticSeasons(world:World){const seen:any[]=[];for(const c of ['BRA','ENG','GER','ESP','ITA','FRA','POR','NED','BEL','ARG','COL']){void c}const holder=(world as any);void holder;const candidates:any[]=[];for(let season=world.season-1;season<=world.season+1;season++)for(const compId of ['comp-bra-1','comp-bra-2','comp-bra-3','comp-eng-1','comp-eng-2','comp-ger-1','comp-ger-2','comp-esp-1','comp-esp-2','comp-ita-1','comp-ita-2','comp-fra-1','comp-fra-2','comp-por-1','comp-por-2','comp-ned-1','comp-ned-2']){const s=domesticSeason(world,compId,season);if(s)candidates.push(s)}for(const s of candidates)if(!seen.some(x=>x.id===s.id))seen.push(s);return seen}
