import type { Club, Player, Position, Tactics, World } from './engine';
import { allDomesticSeasons } from './domestic-competition-runtime-v1';
import { footballDataSnapshot } from './world-football-data-v1';
import { deterministicRandom } from './world-core-v2';

const positions:Position[]=['GK','GK','RB','RB','CB','CB','CB','CB','LB','LB','DM','DM','CM','CM','CM','AM','AM','RW','RW','LW','LW','ST','ST','ST'];
const tactics:Tactics={mentality:'balanced',tempo:50,pressing:50,defensiveLine:50,width:50,passingStyle:'mixed',transition:'balanced'};
const first=['Alex','Bruno','Caio','Daniel','Elias','Felipe','Gabriel','Hugo','Igor','João','Lucas','Marco','Nicolas','Oscar','Pedro','Rafael','Samuel','Thiago','Victor','Wesley'];
const last=['Almeida','Barbosa','Costa','Dias','Ferreira','Gomes','Lima','Martins','Nunes','Oliveira','Pereira','Rocha','Santos','Silva','Sousa','Teixeira','Vieira'];
const clamp=(v:number,a=1,b=99)=>Math.max(a,Math.min(b,v));
function r(w:World,key:string){return deterministicRandom(w,'players',`domestic-runtime:${key}`)}
function baseFor(w:World,clubId:string){const data=footballDataSnapshot(w),club=data.clubs.find(x=>x.id===clubId),titles=data.titles.filter(x=>x.teamId===clubId).length,continental=data.titles.filter(x=>x.teamId===clubId&&['comp-uefa-cl','comp-conmebol-libertadores','comp-fifa-club-world-cup'].includes(x.competitionId)).length,history=Math.min(12,titles*.45+continental*1.6),age=club?.foundedYear?Math.min(6,Math.max(0,(w.season-club.foundedYear-20)/25)):2;return clamp(54+history+age+(r(w,`${clubId}:base`)-.5)*8,46,86)}
function attrs(base:number,pos:Position,w:World,key:string){const a=(bias:number,k:string)=>Math.round(clamp(base+bias+(r(w,`${key}:${k}`)-.5)*18,20,95));return{pace:a(['RB','LB','RW','LW'].includes(pos)?8:pos==='GK'?-12:0,'pace'),passing:a(['DM','CM','AM'].includes(pos)?9:pos==='GK'?-8:0,'passing'),technique:a(['AM','RW','LW','ST'].includes(pos)?6:0,'technique'),finishing:a(pos==='ST'?12:['AM','RW','LW'].includes(pos)?5:-8,'finishing'),tackling:a(['CB','RB','LB','DM'].includes(pos)?11:-7,'tackling'),positioning:a(['GK','CB','DM'].includes(pos)?9:2,'positioning'),stamina:a(['RB','LB','DM','CM'].includes(pos)?7:0,'stamina'),decisions:a(0,'decisions'),goalkeeping:a(pos==='GK'?18:-38,'goalkeeping')};}
function player(w:World,clubId:string,base:number,pos:Position,i:number):Player{const key=`${clubId}:${i}:${pos}`,age=18+Math.floor(r(w,`${key}:age`)*17),ca=Math.round(clamp(base+(r(w,`${key}:ca`)-.5)*16+(pos==='GK'?1:0),42,91)),pa=Math.round(clamp(ca+(age<=22?6+r(w,`${key}:growth`)*13:age<=26?2+r(w,`${key}:growth`)*7:r(w,`${key}:growth`)*3),ca,96)),name=`${first[Math.floor(r(w,`${key}:first`)*first.length)]} ${last[Math.floor(r(w,`${key}:last`)*last.length)]}`;return{id:`rt-${clubId}-p${i+1}`,clubId,name,position:pos,age,currentAbility:ca,potentialAbility:pa,condition:92+Math.round(r(w,`${key}:condition`)*8),morale:62+Math.round(r(w,`${key}:morale`)*32),attributes:attrs(ca,pos,w,key)}}
export function ensureRuntimeClubForCanonical(world:World,clubId:string){const existing=world.clubs.find(c=>c.id===clubId);if(existing)return existing;const rec=footballDataSnapshot(world).clubs.find(c=>c.id===clubId);if(!rec)throw new Error(`Canonical club missing: ${clubId}`);const base=baseFor(world,clubId),club:Club={id:clubId,name:rec.name,reputation:Math.round(clamp(base+8,40,95)),players:positions.map((p,i)=>player(world,clubId,base,p,i)),tactics:{...tactics}};world.clubs.push(club);world.standings[clubId]??={clubId,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,points:0};return club}
export function materializeDomesticRuntimeClubs(world:World){const ids=new Set(allDomesticSeasons(world).flatMap(s=>s.teamIds));let created=0;for(const id of ids){if(!world.clubs.some(c=>c.id===id)){ensureRuntimeClubForCanonical(world,id);created++}}return{created,total:ids.size}}
