import type { Fixture, Player, World } from './engine';
import { allDomesticSeasons, domesticSeason, recordDomesticLeagueResult, type LeagueFixture } from './domestic-competition-runtime-v1';
import { simulateFixtureV2 } from './match-world-integration-v2';
import { recordHomeMatchCommercial } from './club-commercial-finance';
import { emitWorldEvent } from './event-bus';
import { queueWorldEvent } from './world-core-v2';
import { matchInjuries, type MatchInjury } from './match-contact-injury-v2';
import { inflictInjury, injuryDefinitions, tickRecovery } from './injuries';
import { matchRivalryImportance } from './club-reputation-rivalry-v1';

function legacyFixture(f:LeagueFixture):Fixture{return{round:f.round,home:f.homeTeamId,away:f.awayTeamId,played:false} as Fixture}
function playerById(w:World,id:string):Player|undefined{for(const c of w.clubs){const p=c.players.find(x=>x.id===id);if(p)return p}}
function injuryDefinition(i:MatchInjury){const by=(id:string)=>injuryDefinitions.find(x=>x.id===id)!;if(i.concussion||i.mechanism==='head')return by('concussion');if(i.mechanism==='shoulder')return i.severity==='knock'?by('bruise'):by('shoulder-dislocation');if(i.mechanism==='ankle')return by('ankle-sprain');if(i.mechanism==='knee')return i.severity==='severe'?by('knee-acl'):by('knee-mcl');if(i.mechanism==='lowerLeg')return i.severity==='severe'?by('tibia-fracture'):i.severity==='moderate'?by('fibula-fracture'):by('calf-strain');if(i.mechanism==='hip')return by('hip-flexor');if(i.mechanism==='muscle'||i.mechanism==='thigh')return i.severity==='knock'?by('bruise'):by('hamstring-strain');return by('bruise')}
function persistDomesticInjuries(w:World,state:any,fixture:LeagueFixture){for(const i of matchInjuries(state)){if(i.severity==='knock')continue;const p=playerById(w,i.playerId);if(!p)continue;const event=inflictInjury(w,p,injuryDefinition(i),i.source==='foul'||i.source==='duel'?'contact':'match');event.notes.push(`Lesão em ${fixture.competitionId}, rodada ${fixture.round}, minuto ${Math.floor(i.second/60)}.`);if(i.forcedOff)event.notes.push('Jogador deixou a partida.')}}
export function playDomesticFixtureV1(world:World,input:{competitionId:string;season:number;fixtureId:string}){const season=domesticSeason(world,input.competitionId,input.season);if(!season)throw new Error(`Domestic season missing: ${input.competitionId}-${input.season}`);const f=season.fixtures.find(x=>x.id===input.fixtureId);if(!f)throw new Error(`Domestic fixture missing: ${input.fixtureId}`);if(f.played)return f;const lf=legacyFixture(f),rivalry=matchRivalryImportance(world,f.homeTeamId,f.awayTeamId),state=simulateFixtureV2(world,lf,{competitionId:input.competitionId,date:f.date});persistDomesticInjuries(world,state,f);recordDomesticLeagueResult(world,{competitionId:input.competitionId,season:input.season,fixtureId:f.id,homeGoals:lf.homeGoals??0,awayGoals:lf.awayGoals??0});recordHomeMatchCommercial(world,f.homeTeamId,f.date);const importance=Math.max(3,Math.min(7,Math.round(3+rivalry.rivalry.score/25)));queueWorldEvent(world,{date:f.date,type:'DomesticLeagueMatchCompleted',scope:'competition',entityIds:[input.competitionId,f.homeTeamId,f.awayTeamId],importance,payload:{fixtureId:f.id,season:input.season,round:f.round,homeGoals:lf.homeGoals,awayGoals:lf.awayGoals,homeXg:lf.homeXg,awayXg:lf.awayXg,rivalry:rivalry.rivalry,pressure:rivalry.pressure,mediaInterest:rivalry.mediaInterest}});emitWorldEvent(world,{type:'DomesticLeagueMatchCompleted',date:f.date,clubIds:[f.homeTeamId,f.awayTeamId],importance,summary:`${f.homeTeamId} ${lf.homeGoals}–${lf.awayGoals} ${f.awayTeamId}.`,payload:{competitionId:input.competitionId,fixtureId:f.id,round:f.round,rivalry:rivalry.rivalry}});return{...f,homeGoals:lf.homeGoals,awayGoals:lf.awayGoals,state,rivalry:rivalry.rivalry}}
export function playDomesticFixturesOnDate(world:World,date:string){const out:any[]=[];for(const season of allDomesticSeasons(world))for(const f of season.fixtures.filter(x=>x.date===date&&!x.played))out.push(playDomesticFixtureV1(world,{competitionId:season.competitionId,season:season.season,fixtureId:f.id}));if(out.length)tickRecovery(world);return out}
