import type { Club, Player, Position, World } from './engine';
import { selectStartingEleven } from './engine';
import { economyState, type Contract } from './economy';
import { activeLifeEvents, humanLifeState, relationshipsOf } from './human-life';
import { emitWorldEvent } from './event-bus';
import { worldRandom } from './world-core-v2';

export type CultureAxis='discipline'|'youthTrust'|'starTolerance'|'collectivism'|'competitiveness'|'resultPressure'|'tradition'|'openness';
export type ClubCulture={clubId:string;discipline:number;youthTrust:number;starTolerance:number;collectivism:number;competitiveness:number;resultPressure:number;tradition:number;openness:number;identityStrength:number;lastShiftDate:string};
export type SocialStanding='captain'|'viceCaptain'|'teamLeader'|'influential'|'core'|'peripheral'|'isolated'|'prospect';
export type PlayerDressingStatus={playerId:string;clubId:string;standing:SocialStanding;influence:number;leadership:number;integration:number;managerTrust:number;playingTimeSatisfaction:number;salarySatisfaction:number;statusSatisfaction:number;cultureFit:number;overallHappiness:number;conflictRisk:number;grievanceDays:number;lastUpdated:string};
export type SquadFaction={id:string;clubId:string;memberIds:string[];leaderId?:string;cohesion:number;hostility:number;identity:'core'|'veterans'|'youth'|'international'|'performance'|'mixed';formedDate:string};
export type Mentorship={id:string;clubId:string;mentorId:string;menteeId:string;startedDate:string;strength:number;active:boolean;benefit:number;friction:number};
export type Captaincy={clubId:string;captainId?:string;viceCaptainId?:string;appointedDate:string;lastReviewDate:string};
export type ClubDressingRoom={clubId:string;culture:ClubCulture;captaincy:Captaincy;players:Map<string,PlayerDressingStatus>;factions:SquadFaction[];mentorships:Mentorship[];chemistry:number;conflictDensity:number;leadershipQuality:number;integration:number;managerAuthority:number;turnoverShock:number;lastRosterIds:string[];lastWeeklyTick?:string;crisisLevel:0|1|2|3|4};
export type DressingRoomState={clubs:Map<string,ClubDressingRoom>};
export type ClubDressingRoomSnapshot=Omit<ClubDressingRoom,'players'> & {players:[string,PlayerDressingStatus][]};
export type DressingRoomSnapshot={clubs:[string,ClubDressingRoomSnapshot][]};

const states=new WeakMap<World,DressingRoomState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(seed:number,offset:number)=>{const x=Math.sin(seed*12.9898+offset*78.233)*43758.5453;return x-Math.floor(x)};
const daysBetween=(a:string,b:string)=>Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/86400000);
const adjPositions:Record<Position,Position[]>={GK:['GK'],RB:['RB','LB','CB'],CB:['CB','RB','LB','DM'],LB:['LB','RB','CB'],DM:['DM','CM','CB'],CM:['CM','DM','AM'],AM:['AM','CM','RW','LW'],RW:['RW','LW','AM','ST'],LW:['LW','RW','AM','ST'],ST:['ST','RW','LW','AM']};

function initialCulture(club:Club,date:string):ClubCulture{const s=hash(`culture-${club.id}`);const press=(club.tactics.pressing+club.tactics.tempo)/2;return{clubId:club.id,discipline:Math.round(42+pseudo(s,1)*42+press*.08),youthTrust:Math.round(35+pseudo(s,2)*55),starTolerance:Math.round(30+pseudo(s,3)*62),collectivism:Math.round(38+pseudo(s,4)*52),competitiveness:Math.round(45+pseudo(s,5)*45),resultPressure:Math.round(30+club.reputation*.45+pseudo(s,6)*22),tradition:Math.round(28+pseudo(s,7)*65),openness:Math.round(30+pseudo(s,8)*60),identityStrength:Math.round(35+pseudo(s,9)*55),lastShiftDate:date};}
function emptyRoom(club:Club,date:string):ClubDressingRoom{return{clubId:club.id,culture:initialCulture(club,date),captaincy:{clubId:club.id,appointedDate:date,lastReviewDate:date},players:new Map(),factions:[],mentorships:[],chemistry:55,conflictDensity:10,leadershipQuality:50,integration:55,managerAuthority:60,turnoverShock:0,lastRosterIds:club.players.map(p=>p.id),crisisLevel:0};}
export function dressingRoomState(world:World,date=`${world.season}-07-25`):DressingRoomState{let s=states.get(world);if(!s){s={clubs:new Map()};states.set(world,s);}for(const club of world.clubs)if(!s.clubs.has(club.id))s.clubs.set(club.id,emptyRoom(club,date));return s;}
export function clubDressingRoom(world:World,clubId:string):ClubDressingRoom|undefined{return dressingRoomState(world).clubs.get(clubId);}
function contractFor(world:World,p:Player):Contract|undefined{return economyState(world).contracts.get(p.id);}
function professionalism(world:World,p:Player):number{return humanLifeState(world).people.get(p.id)?.professionalism??60;}
function sociability(world:World,p:Player):number{return humanLifeState(world).people.get(p.id)?.sociability??55;}
function relationScore(world:World,p:Player):number{const rel=relationshipsOf(world,p.id).filter(r=>r.type==='friend'||r.type==='closeFriend'||r.type==='mentor');if(!rel.length)return 42;return clamp(rel.reduce((s,r)=>s+r.closeness,0)/rel.length);}
function relationConflict(world:World,p:Player):number{const rel=relationshipsOf(world,p.id).filter(r=>r.type==='conflict'||r.type==='rival');return rel.length?clamp(rel.reduce((s,r)=>s+(100-r.stability)*.55+r.closeness*.1,0)/Math.max(1,rel.length)):0;}
function startsNow(club:Club):Set<string>{return new Set(selectStartingEleven(club).map(p=>p.id));}
function rankInSquad(club:Club,p:Player):number{return [...club.players].sort((a,b)=>b.currentAbility-a.currentAbility).findIndex(x=>x.id===p.id)+1;}
function expectedRoleScore(status:Contract['squadStatus']|undefined):number{return status==='star'?95:status==='starter'?78:status==='rotation'?55:status==='prospect'?45:35;}
function actualRoleScore(club:Club,p:Player,starter:boolean):number{const rank=rankInSquad(club,p);return clamp((starter?78:42)+(rank<=4?18:rank<=11?8:rank>=20?-10:0)+(p.age<=21?3:0));}
function salarySatisfaction(world:World,club:Club,p:Player):number{const state=economyState(world);const c=state.contracts.get(p.id);if(!c)return 45;const peers=club.players.map(x=>state.contracts.get(x.id)?.weeklyWage??0).filter(Boolean).sort((a,b)=>a-b);if(!peers.length)return 55;const median=peers[Math.floor(peers.length/2)]||1;const abilityRank=rankInSquad(club,p);const expected=median*(abilityRank<=4?1.7:abilityRank<=11?1.2:abilityRank>=20?.65:1);return clamp(50+(c.weeklyWage/Math.max(1,expected)-1)*45,-0,100);}
function cultureFit(world:World,room:ClubDressingRoom,p:Player):number{const profile=humanLifeState(world).profiles.get(p.id);const person=humanLifeState(world).people.get(p.id);if(!profile||!person)return 55;let score=55;score+=(person.professionalism-50)*(room.culture.discipline-50)/2600;score+=(person.sociability-50)*(room.culture.collectivism-50)/2500;score+=(profile.fameComfort-50)*(room.culture.starTolerance-50)/3100;if(p.age<=21)score+=(room.culture.youthTrust-50)*.16;score+=(profile.stressResilience-50)*(room.culture.resultPressure-50)/3300;return clamp(score);}
function leadershipScore(world:World,club:Club,p:Player):number{const age=Math.min(100,Math.max(0,(p.age-18)*5));const pro=professionalism(world,p);const social=relationScore(world,p);const ability=clamp((p.currentAbility-45)*2);const seniority=p.age>=29?76:p.age>=26?62:p.age>=23?48:28;return clamp(pro*.28+social*.24+ability*.18+seniority*.2+age*.1);}
function influenceScore(world:World,club:Club,p:Player):number{const rels=relationshipsOf(world,p.id);const socialReach=Math.min(100,rels.length*12+rels.filter(r=>r.type==='closeFriend').length*12);return clamp(leadershipScore(world,club,p)*.42+socialReach*.28+p.currentAbility*.22+(p.age>=28?8:0));}
function reviewCaptaincy(world:World,club:Club,room:ClubDressingRoom,date:string):void{if(daysBetween(date,room.captaincy.lastReviewDate)<28&&room.captaincy.captainId&&club.players.some(p=>p.id===room.captaincy.captainId))return;room.captaincy.lastReviewDate=date;const ranked=club.players.filter(p=>p.age>=21).map(p=>({p,score:leadershipScore(world,club,p)-((contractFor(world,p)?.squadStatus==='backup')?8:0)-((activeLifeEvents(world,p.id).some(e=>e.severity>=7))?7:0)})).sort((a,b)=>b.score-a.score);const incumbent=ranked.find(x=>x.p.id===room.captaincy.captainId);let cap=ranked[0];if(incumbent&&cap&&cap.p.id!==incumbent.p.id&&cap.score<incumbent.score+8)cap=incumbent;const vice=ranked.find(x=>x.p.id!==cap?.p.id);const oldCap=room.captaincy.captainId,oldVice=room.captaincy.viceCaptainId;room.captaincy.captainId=cap?.p.id;room.captaincy.viceCaptainId=vice?.p.id;if(!room.captaincy.appointedDate)room.captaincy.appointedDate=date;if(oldCap!==room.captaincy.captainId){room.captaincy.appointedDate=date;emitWorldEvent(world,{type:'CaptaincyChanged',date,clubIds:[club.id],playerIds:[...(oldCap?[oldCap]:[]),...(room.captaincy.captainId?[room.captaincy.captainId]:[])],importance:3,summary:`${club.name} redefiniu sua liderança de vestiário.`,payload:{oldCaptainId:oldCap,newCaptainId:room.captaincy.captainId,oldViceId:oldVice,newViceId:room.captaincy.viceCaptainId}});}}
function connectedFactions(world:World,club:Club,date:string):SquadFaction[]{const ids=new Set(club.players.map(p=>p.id));const edges=new Map<string,Set<string>>();for(const id of ids)edges.set(id,new Set());const life=humanLifeState(world);for(const r of life.relationships){if(!ids.has(r.aId)||!ids.has(r.bId))continue;if((r.type==='friend'||r.type==='closeFriend'||r.type==='mentor')&&r.closeness>=62){edges.get(r.aId)!.add(r.bId);edges.get(r.bId)!.add(r.aId);}}const visited=new Set<string>();const groups:string[][]=[];for(const id of ids){if(visited.has(id))continue;const stack=[id],g:string[]=[];visited.add(id);while(stack.length){const x=stack.pop()!;g.push(x);for(const n of edges.get(x)??[])if(!visited.has(n)){visited.add(n);stack.push(n);}}groups.push(g);}return groups.map((memberIds,i)=>{const members=memberIds.map(id=>club.players.find(p=>p.id===id)!).filter(Boolean);const ages=members.map(p=>p.age);const avgAge=ages.reduce((a,b)=>a+b,0)/Math.max(1,ages.length);const best=[...members].sort((a,b)=>influenceScore(world,club,b)-influenceScore(world,club,a))[0];let identity:SquadFaction['identity']='mixed';if(avgAge>=28)identity='veterans';else if(avgAge<=22)identity='youth';else if(members.every(p=>p.currentAbility>=club.players.reduce((s,x)=>s+x.currentAbility,0)/club.players.length+4))identity='performance';else if(memberIds.includes(roomCaptain(world,club.id)??''))identity='core';const cohesion=memberIds.length===1?25:clamp(45+memberIds.length*5+members.reduce((s,p)=>s+relationScore(world,p),0)/Math.max(1,members.length)*.25);const hostility=clamp(members.reduce((s,p)=>s+relationConflict(world,p),0)/Math.max(1,members.length));return{id:`faction-${club.id}-${i}-${memberIds.slice().sort().join('-')}`,clubId:club.id,memberIds,leaderId:best?.id,cohesion,hostility,identity,formedDate:date};});}
function roomCaptain(world:World,clubId:string):string|undefined{return dressingRoomState(world).clubs.get(clubId)?.captaincy.captainId;}
function maintainMentorships(world:World,club:Club,room:ClubDressingRoom,date:string):void{for(const m of room.mentorships)if(m.active&&(!club.players.some(p=>p.id===m.mentorId)||!club.players.some(p=>p.id===m.menteeId)))m.active=false;const activeMentees=new Set(room.mentorships.filter(m=>m.active).map(m=>m.menteeId));const mentors=club.players.filter(p=>p.age>=27&&leadershipScore(world,club,p)>=58).sort((a,b)=>leadershipScore(world,club,b)-leadershipScore(world,club,a));for(const young of club.players.filter(p=>p.age<=21&&!activeMentees.has(p.id))){const mentor=mentors.find(m=>m.id!==young.id&&adjPositions[young.position].includes(m.position));if(!mentor||worldRandom(world,'humanLife',`mentorship:${date}:${club.id}:${young.id}`)>.025)continue;const fit=clamp((professionalism(world,mentor)+relationScore(world,mentor)+sociability(world,young))/3);room.mentorships.push({id:`mentor-${club.id}-${mentor.id}-${young.id}`,clubId:club.id,mentorId:mentor.id,menteeId:young.id,startedDate:date,strength:fit,active:true,benefit:clamp((fit-45)*.12),friction:clamp((55-fit)*.16)});emitWorldEvent(world,{type:'MentorshipStarted',date,clubIds:[club.id],playerIds:[mentor.id,young.id],importance:2,summary:`${mentor.name} passa a orientar ${young.name} no elenco.`,payload:{mentorId:mentor.id,menteeId:young.id,strength:fit}});}}
function detectTurnover(world:World,club:Club,room:ClubDressingRoom,date:string):void{const previous=new Set(room.lastRosterIds),current=new Set(club.players.map(p=>p.id));const arrivals=[...current].filter(id=>!previous.has(id)),departures=[...previous].filter(id=>!current.has(id));if(!arrivals.length&&!departures.length)return;let shock=arrivals.length*3+departures.length*5;const life=humanLifeState(world);for(const departed of departures){const links=life.relationships.filter(r=>(r.aId===departed&&current.has(r.bId))||(r.bId===departed&&current.has(r.aId)));shock+=links.reduce((s,r)=>s+(r.type==='closeFriend'?8:r.type==='friend'?4:1),0);if(departed===room.captaincy.captainId)shock+=18;}room.turnoverShock=clamp(room.turnoverShock+shock);room.lastRosterIds=[...current];emitWorldEvent(world,{type:'SquadTurnover',date,clubIds:[club.id],playerIds:[...arrivals,...departures],importance:shock>=25?4:shock>=12?3:2,summary:`Mudanças no elenco de ${club.name} alteram o equilíbrio do vestiário.`,payload:{arrivals,departures,shock}});}
function statusStanding(p:Player,room:ClubDressingRoom,influence:number):SocialStanding{if(p.id===room.captaincy.captainId)return'captain';if(p.id===room.captaincy.viceCaptainId)return'viceCaptain';if(p.age<=21)return'prospect';if(influence>=82)return'teamLeader';if(influence>=68)return'influential';if(influence>=48)return'core';return influence<30?'isolated':'peripheral';}
function refreshPlayers(world:World,club:Club,room:ClubDressingRoom,date:string):void{const starters=startsNow(club);for(const p of club.players){const contract=contractFor(world,p);const expected=expectedRoleScore(contract?.squadStatus),actual=actualRoleScore(club,p,starters.has(p.id));const playSat=clamp(58+(actual-expected)*.72);const salSat=salarySatisfaction(world,club,p);const influence=influenceScore(world,club,p);const integration=clamp(relationScore(world,p)*.62+sociability(world,p)*.18+(room.turnoverShock?Math.max(0,20-room.turnoverShock*.25):20));const cfit=cultureFit(world,room,p);const captainBond=room.captaincy.captainId?relationshipsOf(world,p.id).find(r=>(r.aId===room.captaincy.captainId||r.bId===room.captaincy.captainId)&&r.type!=='conflict'):undefined;const managerTrust=clamp(55+(p.morale-60)*.35+(captainBond?.closeness??0)*.08-room.culture.resultPressure*.05);const statusSat=clamp((playSat+salSat+cfit)/3+(contract?.squadStatus==='star'?4:0));const conflict=clamp(relationConflict(world,p)*.45+(100-playSat)*.25+(100-salSat)*.13+(100-managerTrust)*.17);const happiness=clamp(p.morale*.32+playSat*.2+salSat*.12+integration*.14+cfit*.1+managerTrust*.12);const prev=room.players.get(p.id);const grievance=(playSat<35||salSat<30||managerTrust<32)?(prev?.grievanceDays??0)+1:Math.max(0,(prev?.grievanceDays??0)-2);room.players.set(p.id,{playerId:p.id,clubId:club.id,standing:statusStanding(p,room,influence),influence,leadership:leadershipScore(world,club,p),integration,managerTrust,playingTimeSatisfaction:playSat,salarySatisfaction:salSat,statusSatisfaction:statusSat,cultureFit:cfit,overallHappiness:happiness,conflictRisk:conflict,grievanceDays:grievance,lastUpdated:date});if(grievance===14||grievance===30){emitWorldEvent(world,{type:'DressingRoomConcern',date,clubIds:[club.id],playerIds:[p.id],importance:grievance>=30?4:3,summary:`${p.name} demonstra insatisfação persistente no elenco.`,payload:{playingTime:playSat,salary:salSat,managerTrust,days:grievance}});}}for(const id of [...room.players.keys()])if(!club.players.some(p=>p.id===id))room.players.delete(id);}
function refreshRoomMetrics(world:World,club:Club,room:ClubDressingRoom,date:string):void{room.factions=connectedFactions(world,club,date);const statuses=[...room.players.values()];if(!statuses.length)return;const avg=(key:keyof Pick<PlayerDressingStatus,'integration'|'managerTrust'|'overallHappiness'|'conflictRisk'>)=>statuses.reduce((s,x)=>s+Number(x[key]),0)/statuses.length;room.integration=avg('integration');room.conflictDensity=clamp(avg('conflictRisk')*.65+room.factions.reduce((s,f)=>s+f.hostility,0)/Math.max(1,room.factions.length)*.35);const leaders=statuses.filter(s=>['captain','viceCaptain','teamLeader','influential'].includes(s.standing));room.leadershipQuality=leaders.length?leaders.reduce((s,x)=>s+x.leadership,0)/leaders.length:42;const isolated=statuses.filter(s=>s.standing==='isolated').length;const fragmentation=Math.max(0,room.factions.length-3)*4+isolated*2;room.chemistry=clamp(avg('overallHappiness')*.32+room.integration*.2+room.leadershipQuality*.18+avg('managerTrust')*.14+room.culture.collectivism*.1-room.conflictDensity*.25-room.turnoverShock*.18-fragmentation);room.managerAuthority=clamp(avg('managerTrust')*.55+room.leadershipQuality*.18+room.culture.discipline*.12+(100-room.conflictDensity)*.15);room.turnoverShock=Math.max(0,room.turnoverShock-.8);const old=room.crisisLevel;room.crisisLevel=room.chemistry<30||room.conflictDensity>78?4:room.chemistry<40||room.conflictDensity>62?3:room.chemistry<50||room.conflictDensity>48?2:room.chemistry<60?1:0;if(room.crisisLevel!==old&&room.crisisLevel>=2)emitWorldEvent(world,{type:'DressingRoomCrisis',date,clubIds:[club.id],importance:room.crisisLevel>=4?5:room.crisisLevel===3?4:3,summary:`O ambiente interno de ${club.name} entrou em nível ${room.crisisLevel} de tensão.`,payload:{chemistry:room.chemistry,conflictDensity:room.conflictDensity,leadership:room.leadershipQuality,crisisLevel:room.crisisLevel}});}
function weeklyCultureDrift(world:World,club:Club,room:ClubDressingRoom,date:string):void{if(room.lastWeeklyTick&&daysBetween(date,room.lastWeeklyTick)<7)return;room.lastWeeklyTick=date;const starters=selectStartingEleven(club);const avgAge=starters.reduce((s,p)=>s+p.age,0)/Math.max(1,starters.length);const youngShare=club.players.filter(p=>p.age<=21).length/Math.max(1,club.players.length);room.culture.youthTrust=clamp(room.culture.youthTrust+(youngShare>.25?.25:-.04));room.culture.discipline=clamp(room.culture.discipline+(room.conflictDensity>55?.08:.02));room.culture.collectivism=clamp(room.culture.collectivism+(room.chemistry>68?.09:room.chemistry<42?-.12:0));room.culture.tradition=clamp(room.culture.tradition+(avgAge>=28?.04:0));room.culture.identityStrength=clamp(room.culture.identityStrength+(room.chemistry>65?.08:room.turnoverShock>25?-.16:0));}
export function tickDressingRoom(world:World,date:string):void{const s=dressingRoomState(world,date);for(const club of world.clubs){const room=s.clubs.get(club.id)!;detectTurnover(world,club,room,date);reviewCaptaincy(world,club,room,date);maintainMentorships(world,club,room,date);refreshPlayers(world,club,room,date);refreshRoomMetrics(world,club,room,date);weeklyCultureDrift(world,club,room,date);}}
export function dressingRoomPerformanceFactor(world:World,playerId:string):number{for(const room of dressingRoomState(world).clubs.values()){const p=room.players.get(playerId);if(!p)continue;let factor=1+(room.chemistry-55)/1200+(room.leadershipQuality-50)/2500-(p.conflictRisk/100)*.018+(p.integration-50)/3500;if(p.standing==='captain'||p.standing==='teamLeader')factor+=.004;if(p.standing==='isolated')factor-=.012;return clamp(factor,.94,1.035);}return 1;}
export function mentorshipDevelopmentBonus(world:World,playerId:string):number{for(const room of dressingRoomState(world).clubs.values()){const m=room.mentorships.find(x=>x.active&&x.menteeId===playerId);if(m)return clamp((m.benefit-m.friction)/100,0,.08);}return 0;}
export function dressingRoomSummary(world:World,clubId:string){const r=clubDressingRoom(world,clubId);if(!r)return undefined;return{chemistry:r.chemistry,conflictDensity:r.conflictDensity,leadershipQuality:r.leadershipQuality,integration:r.integration,managerAuthority:r.managerAuthority,turnoverShock:r.turnoverShock,crisisLevel:r.crisisLevel,captainId:r.captaincy.captainId,viceCaptainId:r.captaincy.viceCaptainId,factions:r.factions.length,isolated:[...r.players.values()].filter(p=>p.standing==='isolated').length};}
export function snapshotDressingRoom(world:World):DressingRoomSnapshot{return{clubs:[...dressingRoomState(world).clubs.entries()].map(([k,r])=>[k,{...r,culture:{...r.culture},captaincy:{...r.captaincy},players:[...r.players.entries()].map(([id,p])=>[id,{...p}]),factions:r.factions.map(f=>({...f,memberIds:[...f.memberIds]})),mentorships:r.mentorships.map(m=>({...m})),lastRosterIds:[...r.lastRosterIds]}])};}
export function restoreDressingRoom(world:World,snapshot?:DressingRoomSnapshot):void{if(!snapshot)return;states.set(world,{clubs:new Map(snapshot.clubs.map(([k,r])=>[k,{...r,culture:{...r.culture},captaincy:{...r.captaincy},players:new Map(r.players.map(([id,p])=>[id,{...p}])),factions:r.factions.map(f=>({...f,memberIds:[...f.memberIds]})),mentorships:r.mentorships.map(m=>({...m})),lastRosterIds:[...r.lastRosterIds]}]))});}
