import './engine-ui-bridge-v1.css';
import { userManager } from './manager-character';
import { createScoutingUiState, renderScouting, bindScouting } from './scouting-ui';
import { renderMedicalCenter, bindMedicalCenter } from './medical-ui';
import { renderStaff } from './staff-ui';
import { topPlayers, playerName } from './analytics';
import { sortedStandings, type Club, type World } from './engine';

const scoutingState=createScoutingUiState();
let medicalSelected:string|undefined;
let activeSystem:string|undefined;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function world(){return window.__touchlineWorld as World|undefined}
function observer(w:World):Club|undefined{const manager=userManager(w);return w.clubs.find(c=>c.id===(manager?.currentClubId??''))}
function main(){return document.querySelector<HTMLElement>('.game-stage main.view')}
function systemHero(title:string,sub:string,tag:string){return `<header class="view-hero"><div><span class="kicker">${tag}</span><h1>${title}</h1><p>${sub}</p></div><div class="hero-glow"></div></header>`}
function wrapLegacy(html:string){return `<section class="engine-native">${html}</section>`}
function renderScoutingSystem(){const w=world(),c=w&&observer(w),host=main();if(!w||!c||!host)return;activeSystem='transfers';host.innerHTML=wrapLegacy(renderScouting(w,c,scoutingState));bindScouting(w,c,scoutingState,renderScoutingSystem)}
function renderMedicalSystem(){const w=world(),c=w&&observer(w),host=main();if(!w||!c||!host)return;activeSystem='medical';host.innerHTML=wrapLegacy(renderMedicalCenter(w,c,medicalSelected));bindMedicalCenter(id=>{medicalSelected=id;renderMedicalSystem()})}
function renderStaffSystem(){const w=world(),c=w&&observer(w),host=main();if(!w||!c||!host)return;activeSystem='staff';host.innerHTML=wrapLegacy(renderStaff(w,c))}
function renderAnalyticsSystem(){const w=world(),c=w&&observer(w),host=main();if(!w||!c||!host)return;activeSystem='analytics';const rows=topPlayers(w,20),clubRows=rows.filter(r=>r.clubId===c.id),played=w.fixtures.filter(f=>f.played).length;host.innerHTML=`${systemHero('Centro de Análise','Produção individual calculada diretamente dos eventos do match engine.','FUTEBOL · ANALYTICS')}<section class="engine-metrics"><article class="glass"><span>PARTIDAS PROCESSADAS</span><b>${played}</b></article><article class="glass"><span>ATLETAS COM EVENTOS</span><b>${rows.length}</b></article><article class="glass"><span>DESTAQUES DO CLUBE</span><b>${clubRows.length}</b></article></section><section class="glass engine-table"><table><thead><tr><th>Jogador</th><th>Clube</th><th>Gols</th><th>Chutes</th><th>xG</th><th>Defesas</th><th>Amarelos</th><th>Impacto</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(playerName(w,r.playerId))}</b></td><td>${esc(w.clubs.find(x=>x.id===r.clubId)?.name??r.clubId)}</td><td>${r.goals}</td><td>${r.shots}</td><td>${r.xg}</td><td>${r.saves}</td><td>${r.yellows}</td><td><b>${r.impact}</b></td></tr>`).join('')||'<tr><td colspan="8">Avance a temporada para produzir estatísticas.</td></tr>'}</tbody></table></section>`}
function renderClubSystem(){const w=world(),c=w&&observer(w),host=main();if(!w||!c||!host)return;activeSystem='club';const raw=c as Club&{finances?:Record<string,unknown>;balance?:number;transferBudget?:number;wageBudget?:number};const finance=raw.finances??{};const money=(n:unknown)=>typeof n==='number'?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n):'—';host.innerHTML=`${systemHero('Estrutura do Clube','Leitura da estrutura econômica e esportiva já presente no mundo da carreira.','GESTÃO · CLUBE')}<section class="engine-metrics"><article class="glass"><span>REPUTAÇÃO</span><b>${c.reputation}</b></article><article class="glass"><span>ELENCO</span><b>${c.players.length}</b></article><article class="glass"><span>SALDO</span><b>${money(raw.balance??finance.balance)}</b></article><article class="glass"><span>ORÇAMENTO TRANSF.</span><b>${money(raw.transferBudget??finance.transferBudget)}</b></article></section><section class="glass engine-json"><h3>Estado econômico do engine</h3><pre>${esc(JSON.stringify(finance,null,2))}</pre></section>`}
function renderWorldSystem(){const w=world(),host=main();if(!w||!host)return;activeSystem='world';const table=sortedStandings(w);host.innerHTML=`${systemHero('Mundo do Futebol','Classificação e atividade calculadas no mesmo universo persistente da carreira.','UNIVERSO · MUNDO')}<section class="engine-metrics"><article class="glass"><span>CLUBES</span><b>${w.clubs.length}</b></article><article class="glass"><span>JOGOS DISPUTADOS</span><b>${w.fixtures.filter(f=>f.played).length}</b></article><article class="glass"><span>TEMPORADA</span><b>${w.season}</b></article></section><section class="glass engine-table"><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>GP</th><th>GC</th><th>SG</th><th>PTS</th></tr></thead><tbody>${table.map((r,i)=>`<tr><td>${i+1}</td><td><b>${esc(w.clubs.find(c=>c.id===r.clubId)?.name??r.clubId)}</b></td><td>${r.played}</td><td>${r.won}</td><td>${r.drawn}</td><td>${r.lost}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gf-r.ga}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></section>`}
function renderSystemsHome(){const w=world(),host=main();if(!w||!host)return;activeSystem='systems';host.innerHTML=`${systemHero('Motores da Carreira','Painel de integração da beta: todos os itens abaixo operam sobre a mesma instância do mundo ativo.','BETA · SISTEMAS')}<section class="system-launch-grid"><button data-engine-launch="medical"><b>Departamento Médico</b><span>Lesões, risco, recuperação e histórico físico.</span></button><button data-engine-launch="transfers"><b>Scouting</b><span>Conhecimento imperfeito, observações e shortlist reais do engine.</span></button><button data-engine-launch="staff"><b>Comissão Técnica</b><span>Scouts, capacidade e conhecimento regional.</span></button><button data-engine-launch="analytics"><b>Analytics</b><span>Estatísticas derivadas dos eventos das partidas.</span></button><button data-engine-launch="club"><b>Clube</b><span>Estado institucional e econômico disponível.</span></button><button data-engine-launch="world"><b>Mundo</b><span>Classificação e atividade global da carreira.</span></button></section><section class="glass system-note"><b>Integração canônica ativa</b><p>Estes painéis não criam uma simulação paralela: todos leem e alteram o mesmo objeto <code>World</code> usado por Continuar, calendário, elenco e partidas.</p></section>`;bindLaunchers()}
function launch(id:string){if(id==='medical')renderMedicalSystem();else if(id==='transfers')renderScoutingSystem();else if(id==='staff')renderStaffSystem();else if(id==='analytics')renderAnalyticsSystem();else if(id==='club')renderClubSystem();else if(id==='world')renderWorldSystem();else renderSystemsHome();markActive(id)}
function bindLaunchers(){document.querySelectorAll<HTMLButtonElement>('[data-engine-launch]').forEach(b=>b.onclick=()=>launch(b.dataset.engineLaunch||'systems'))}
function markActive(id:string){document.querySelectorAll('.game-sidebar nav button').forEach(b=>b.classList.remove('engine-active'));document.querySelector<HTMLElement>(`[data-system-view="${id}"]`)?.classList.add('engine-active')}
function injectNavigation(){const nav=document.querySelector('.game-sidebar nav');if(!nav||nav.querySelector('[data-system-view="medical"]'))return;const transfers=nav.querySelector('[data-view="transfers"]');const staff=nav.querySelector('[data-view="staff"]');const medical=document.createElement('button');medical.dataset.systemView='medical';medical.innerHTML='<span class="engine-nav-icon">✚</span><span>Médico</span>';medical.onclick=()=>launch('medical');transfers?.before(medical);const systems=document.createElement('button');systems.dataset.systemView='systems';systems.innerHTML='<span class="engine-nav-icon">◫</span><span>Sistemas</span>';systems.onclick=()=>launch('systems');staff?.after(systems)}
function bindCoreOverrides(){document.querySelectorAll<HTMLButtonElement>('[data-view="transfers"]').forEach(b=>{if(b.dataset.engineBound)return;b.dataset.engineBound='1';b.addEventListener('click',()=>queueMicrotask(renderScoutingSystem))});document.querySelectorAll<HTMLButtonElement>('[data-view="staff"]').forEach(b=>{if(b.dataset.engineBound)return;b.dataset.engineBound='1';b.addEventListener('click',()=>queueMicrotask(renderStaffSystem))});document.querySelectorAll<HTMLButtonElement>('[data-view="analytics"]').forEach(b=>{if(b.dataset.engineBound)return;b.dataset.engineBound='1';b.addEventListener('click',()=>queueMicrotask(renderAnalyticsSystem))});document.querySelectorAll<HTMLButtonElement>('[data-view="club"]').forEach(b=>{if(b.dataset.engineBound)return;b.dataset.engineBound='1';b.addEventListener('click',()=>queueMicrotask(renderClubSystem))});document.querySelectorAll<HTMLButtonElement>('[data-view="world"]').forEach(b=>{if(b.dataset.engineBound)return;b.dataset.engineBound='1';b.addEventListener('click',()=>queueMicrotask(renderWorldSystem))})}
function decorate(){injectNavigation();bindCoreOverrides();if(activeSystem&&document.querySelector('.game-shell'))markActive(activeSystem)}
const app=document.querySelector('#app');if(app)new MutationObserver(()=>queueMicrotask(decorate)).observe(app,{subtree:true,childList:true});window.addEventListener('touchline:world-ready',decorate);window.addEventListener('touchline:world-hydrated',decorate);decorate();