import type { World } from './engine';
import { footballDataSnapshot } from './world-football-data-v1';
import { clubHistoricalNarrativeHooks, clubHistoricalPressure, historicalMatchContext } from './club-memory-consequences-v1';
import { activeClubRecordChases } from './club-record-chase-v1';
import { deepClubRecordBook } from './club-record-book-v2';
import { managerByClub } from './manager-character';
import { clubGovernance } from './club-governance';

export type MediaNarrativeTone='celebratory'|'neutral'|'critical'|'provocative'|'historical'|'speculative';
export type MediaNarrativeHook={id:string;clubId:string;opponentId?:string;playerId?:string;managerId?:string;type:'history'|'record'|'manager'|'tactics'|'pressure'|'rivalry';tone:MediaNarrativeTone;weight:number;headline:string;context:string;question?:string;sourceIds:string[]};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const clubName=(w:World,id:string)=>footballDataSnapshot(w).clubs.find(c=>c.id===id)?.name??w.clubs.find(c=>c.id===id)?.name??id;

export function clubMediaNarrativeHooks(w:World,clubId:string,opponentId?:string):MediaNarrativeHook[]{const out:MediaNarrativeHook[]=[],pressure=clubHistoricalPressure(w,clubId),manager=managerByClub(w,clubId),records=deepClubRecordBook(w,clubId),name=clubName(w,clubId);for(const [i,ctx] of clubHistoricalNarrativeHooks(w,clubId,opponentId).entries())out.push({id:`history-${clubId}-${i}`,clubId,opponentId,type:'history',tone:'historical',weight:clamp(48+pressure.totalPressure*.35),headline:`A história volta ao centro no ${name}`,context:ctx,question:`Quanto o peso da história deve influenciar as decisões desta semana?`,sourceIds:pressure.sourceMemoryIds});if(pressure.titleDroughtPressure>=45)out.push({id:`drought-${clubId}`,clubId,type:'pressure',tone:'critical',weight:pressure.titleDroughtPressure,headline:`Jejum aumenta cobrança sobre ${name}`,context:`O clube está há ${records.currentTitleDrought} temporadas sem conquistar um título.`,question:'A pressão pelo fim do jejum está afetando suas decisões?',sourceIds:pressure.sourceMemoryIds});if(pressure.managerShadow>=50&&manager)out.push({id:`manager-shadow-${clubId}`,clubId,managerId:manager.id,type:'manager',tone:'provocative',weight:pressure.managerShadow,headline:`Comparações com eras vencedoras cercam ${manager.name}`,context:'A memória de treinadores históricos elevou a régua de comparação do trabalho atual.',question:'É justo comparar seu trabalho com os treinadores mais vitoriosos da história do clube?',sourceIds:pressure.sourceMemoryIds});for(const r of activeClubRecordChases(w,clubId,.85).slice(0,3))out.push({id:`record-${clubId}-${r.playerId}-${r.record}`,clubId,playerId:r.playerId,type:'record',tone:r.status==='broken'?'celebratory':'historical',weight:r.status==='broken'?92:r.status==='equalled'?86:r.status==='close'?74:58,headline:r.status==='broken'?`${r.playerName} escreve novo recorde no ${name}`:`${r.playerName} se aproxima de marca histórica`,context:r.status==='broken'?`${r.playerName} superou o recorde do clube em ${r.record}.`:`Faltam ${r.remaining} para igualar a marca histórica de ${r.record}.`,question:r.status==='broken'?'O que representa entrar definitivamente para a história do clube?':'O recorde muda a maneira de administrar os próximos jogos?',sourceIds:[]});if(opponentId){const m=historicalMatchContext(w,clubId,opponentId),opp=clubName(w,opponentId);if(m.rivalry>=65||m.historicalPressure>=58)out.push({id:`rivalry-${clubId}-${opponentId}`,clubId,opponentId,type:'rivalry',tone:'provocative',weight:Math.max(m.rivalry,m.historicalPressure),headline:`${name} e ${opp}: um confronto que carrega memória`,context:m.reasons.join(' ')||'O histórico entre os clubes aumenta o peso esportivo e emocional do confronto.',question:m.revengeFactor>=45?'Existe sentimento de revanche para este jogo?':'O histórico deste confronto muda sua preparação?',sourceIds:m.sourceMemoryIds})}return out.sort((a,b)=>b.weight-a.weight).slice(0,12)}

export function tacticalMediaQuestion(w:World,clubId:string,input:{opponentId?:string;lost?:boolean;margin?:number;xgFor?:number;xgAgainst?:number}){const manager=managerByClub(w,clubId),g=clubGovernance(w,clubId),name=clubName(w,clubId),margin=input.margin??0,xgGap=(input.xgAgainst??0)-(input.xgFor??0),severity=clamp((input.lost?28:0)+margin*13+Math.max(0,xgGap)*11+g.mediaPressure*.28);if(severity<42)return;const tactical=manager?.tactical,detail=tactical?`${tactical.favoriteFormation}, pressão ${tactical.pressingPreference} e linha ${tactical.defensiveLinePreference}`:'a estratégia escolhida';return{id:`tactical-${clubId}-${w.season}-${w.round}`,clubId,opponentId:input.opponentId,managerId:manager?.id,type:'tactics' as const,tone:'critical' as const,weight:severity,headline:`Escolhas táticas entram em debate no ${name}`,context:`Após o resultado, analistas questionam ${detail}.`,question:'Você considera que a abordagem tática contribuiu para o resultado negativo?',sourceIds:[]}}
