import type { PlayerAttributes, Position, World } from './engine';
import { deterministicRandom, queueWorldEvent, worldCore } from './world-core-v2';
import { userManager } from './manager-character';
import { debitManagerWallet, managerWallet } from './manager-personal-finance-v1';
import { generateNewgenPlayerV3, registerNewgenPlayerV3, type NewgenPersonality, type NewgenPlayerV3 } from './person-generation-v3';
import { potentialTierFor, type PlayerPotentialLabel } from './player-potential-tier-v1';
import { supporterCulture } from './club-supporter-culture-v1';
import { clubGovernance } from './club-governance';

export type SchoolCountry='BR'|'AR'|'UY'|'PY'|'CL'|'PE'|'CO'|'VE'|'BO'|'EC';
export type SchoolTrainingFocus='fundamentals'|'technique'|'passing'|'finishing'|'defending'|'goalkeeping'|'physical-literacy'|'decision-making'|'weak-foot'|'position-discovery'|'confidence';
export type SchoolFacilityLevel=1|2|3|4|5;
export type SchoolProspectStatus='active'|'academy-eligible'|'graduated'|'released'|'left-program';
export type SchoolYouthInjury={id:string;name:string;started:string;monthsRemaining:number;severity:'minor'|'moderate'|'serious'};
export type SchoolProspect={id:string;name:string;countryId:SchoolCountry;age:number;position:Position;secondaryPositions:Position[];heightCm:number;preferredFoot:'left'|'right';weakFoot:number;attributes:PlayerAttributes;currentAbility:number;truePotential:number;realisationCeiling:number;personality:NewgenPersonality;potentialView:PlayerPotentialLabel;potentialCertainty:number;familySupport:number;schoolAttendance:number;motivation:number;confidence:number;coachBond:number;managerBond:number;injuryRisk:number;injury?:SchoolYouthInjury;monthsInProgram:number;status:SchoolProspectStatus;transitionPendingSince?:string;trainingFocus:SchoolTrainingFocus;personalInvestment:number;notes:string[]};
export type SchoolTeacher={id:string;name:string;countryId:SchoolCountry;coaching:number;youthDevelopment:number;empathy:number;discipline:number;talentIdentification:number;volunteer:boolean};
export type VolunteerSession={id:string;date:string;volunteerType:'manager'|'player'|'staff';personId:string;personName:string;focus:SchoolTrainingFocus;impact:number;mediaInterest:number};
export type FootballSchoolState={id:string;name:string;city:string;countryId:'BR';municipalProgram:true;optional:true;createdSeason:number;managerId:string;facilityLevel:SchoolFacilityLevel;monthlyMunicipalGrant:number;monthlyOperatingCost:number;autoManagerSubsidy:boolean;recurringManagerSubsidy:number;managerTotalInvestment:number;teacher:SchoolTeacher;prospects:SchoolProspect[];volunteerSessions:VolunteerSession[];reputation:number;communityTrust:number;mediaInterest:number;lastMonthlyTick?:string;graduatedPlayerIds:string[]};
const states=new WeakMap<World,FootballSchoolState>();
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));const monthKey=(iso:string)=>iso.slice(0,7);const day=(iso:string)=>Math.floor(Date.parse(`${iso}T12:00:00Z`)/86400000);
const firstBR=['Adriel','André','Arthur','Breno','Caio','Davi','Enzo','Gabriel','Guilherme','Heitor','João','Kauã','Lucas','Mateus','Miguel','Murilo','Pedro','Rafael','Samuel','Vinícius'];const lastBR=['Almeida','Barbosa','Cardoso','Costa','Duarte','Ferreira','Gomes','Lima','Martins','Oliveira','Pereira','Rocha','Rodrigues','Santos','Silva','Souza','Teixeira'];
function r(w:World,k:string){return deterministicRandom(w,'football-school',k)}function pick<T>(w:World,k:string,a:T[]){return a[Math.floor(r(w,k)*a.length)]}
function country(w:World,key:string):SchoolCountry{const x=r(w,`${key}:country`);if(x<.84)return'BR';const pool:SchoolCountry[]=['AR','UY','PY','CL','PE','CO','VE','BO','EC'];return pool[Math.floor(r(w,`${key}:country2`)*pool.length)]}
function culture(c:SchoolCountry){return c==='BR'?'pt-BR':'es'}
function teacher(w:World,managerId:string):SchoolTeacher{const key=`teacher:${managerId}:${w.season}`;return{id:`school-teacher-${Math.floor(r(w,key)*1e8).toString(36)}`,name:`${pick(w,`${key}:f`,firstBR)} ${pick(w,`${key}:l`,lastBR)}`,countryId:'BR',coaching:45+Math.round(r(w,`${key}:coach`)*35),youthDevelopment:55+Math.round(r(w,`${key}:youth`)*35),empathy:50+Math.round(r(w,`${key}:emp`)*45),discipline:40+Math.round(r(w,`${key}:disc`)*50),talentIdentification:40+Math.round(r(w,`${key}:talent`)*45),volunteer:false}}
function prospectFromNewgen(w:World,ng:NewgenPlayerV3,key:string,c:SchoolCountry):SchoolProspect{const p=ng.result.player,age=r(w,`${key}:age`)<.54?14:15,truePotential=Math.round(clamp(p.potentialAbility+(r(w,`${key}:school-tail`)<.012?6:0),55,99)),certainty=18+Math.round(r(w,`${key}:certainty`)*22),realisation=Math.round(clamp(truePotential-(7+r(w,`${key}:realise`)*18),45,truePotential));p.age=age;p.currentAbility=Math.max(24,Math.min(p.currentAbility,age===14?46:50));p.attributes=Object.fromEntries(Object.entries(p.attributes).map(([k,v])=>[k,Math.max(15,Math.round(v-(age===14?8:5))) ])) as PlayerAttributes;return{id:`fsp-${p.id}`,name:p.name,countryId:c,age,position:p.position,secondaryPositions:[...ng.secondaryPositions],heightCm:ng.heightCm,preferredFoot:ng.preferredFoot,weakFoot:ng.weakFoot,attributes:{...p.attributes},currentAbility:p.currentAbility,truePotential,realisationCeiling:realisation,personality:{...ng.personality},potentialView:potentialTierFor({potential:truePotential,position:p.position,certainty,age}),potentialCertainty:certainty,familySupport:35+Math.round(r(w,`${key}:family`)*60),schoolAttendance:65+Math.round(r(w,`${key}:school`)*35),motivation:55+Math.round(r(w,`${key}:motivation`)*42),confidence:45+Math.round(r(w,`${key}:conf`)*45),coachBond:45+Math.round(r(w,`${key}:coachbond`)*40),managerBond:20,injuryRisk:15+Math.round(r(w,`${key}:injury`)*30),monthsInProgram:0,status:'active',trainingFocus:'fundamentals',personalInvestment:0,notes:[]}}
export function createFootballSchool(w:World,input:{name?:string;city?:string;initialProspects?:number}={}){const existing=states.get(w);if(existing)return existing;const m=userManager(w);if(!m)throw new Error('Escolinha exige o treinador controlável.');const s:FootballSchoolState={id:`municipal-school-${m.id}`,name:input.name??'Projeto Bola do Futuro',city:input.city??'São Paulo',countryId:'BR',municipalProgram:true,optional:true,createdSeason:w.season,managerId:m.id,facilityLevel:1,monthlyMunicipalGrant:7500,monthlyOperatingCost:9000,autoManagerSubsidy:false,recurringManagerSubsidy:0,managerTotalInvestment:0,teacher:teacher(w,m.id),prospects:[],volunteerSessions:[],reputation:20,communityTrust:58,mediaInterest:12,graduatedPlayerIds:[]};states.set(w,s);for(let i=0;i<(input.initialProspects??18);i++)discoverSchoolProspect(w,i+1);queueWorldEvent(w,{date:worldCore(w).date,type:'FootballSchoolCreated',scope:'person',entityIds:[m.id,s.id],importance:2,payload:{name:s.name,city:s.city,prospects:s.prospects.length}});return s}
export function footballSchool(w:World){return states.get(w)}
export function discoverSchoolProspect(w:World,serial?:number){const s=states.get(w);if(!s)throw new Error('Escolinha ainda não foi criada.');const n=serial??s.prospects.length+1,key=`${s.id}:${w.season}:${n}:${s.prospects.length}`,c=country(w,key),ng=generateNewgenPlayerV3(w,{clubId:s.id,countryId:c,cultureId:culture(c),season:w.season,serial:n,academyQuality:35+s.facilityLevel*7,recruitmentReach:40+s.reputation*.25,countryStrength:c==='BR'||c==='AR'?75:58}),p=prospectFromNewgen(w,ng,key,c);s.prospects.push(p);return p}
export function configureSchoolSubsidy(w:World,input:{enabled:boolean;monthlyAmount?:number}){const s=states.get(w),m=userManager(w);if(!s||!m||m.id!==s.managerId)return false;s.autoManagerSubsidy=input.enabled;s.recurringManagerSubsidy=input.enabled?Math.max(0,Math.round(input.monthlyAmount??0)):0;return true}
export function investInSchool(w:World,date:string,amount:number,purpose:'operations'|'facilities'|'equipment'|'scholarships'|'scouting'){const s=states.get(w),m=userManager(w);if(!s||!m||m.id!==s.managerId)return false;if(!debitManagerWallet(w,m.id,date,amount,'school-investment',`Investimento voluntário na escolinha: ${purpose}`,s.id))return false;s.managerTotalInvestment+=Math.round(amount);if(purpose==='facilities'&&amount>=25000&&s.facilityLevel<5)s.facilityLevel=(s.facilityLevel+1) as SchoolFacilityLevel;if(purpose==='scholarships')s.communityTrust=clamp(s.communityTrust+amount/8000);if(purpose==='scouting')s.reputation=clamp(s.reputation+amount/12000);queueWorldEvent(w,{date,type:'FootballSchoolInvestment',scope:'person',entityIds:[m.id,s.id],importance:amount>=50000?3:1,payload:{amount,purpose,balance:managerWallet(w,m.id).balance,facilityLevel:s.facilityLevel}});return true}
export function investInSchoolProspect(w:World,date:string,prospectId:string,amount:number,focus:SchoolTrainingFocus){const s=states.get(w),m=userManager(w),p=s?.prospects.find(x=>x.id===prospectId&&(x.status==='active'||x.status==='academy-eligible'));if(!s||!m||!p||amount<=0)return false;if(!debitManagerWallet(w,m.id,date,amount,'school-investment',`Treinamento individual de ${p.name}: ${focus}`,p.id))return false;p.personalInvestment+=Math.round(amount);p.trainingFocus=focus;p.managerBond=clamp(p.managerBond+Math.min(10,amount/2500));p.motivation=clamp(p.motivation+Math.min(7,amount/4000));const upside=Math.min(5,Math.log10(1+amount/1000)*1.5);p.realisationCeiling=Math.round(clamp(p.realisationCeiling+upside,p.currentAbility,p.truePotential));p.potentialCertainty=clamp(p.potentialCertainty+Math.min(8,amount/4000));p.potentialView=potentialTierFor({potential:p.truePotential,position:p.position,certainty:p.potentialCertainty,age:p.age});return true}
export function setSchoolProspectTraining(w:World,prospectId:string,focus:SchoolTrainingFocus){const p=states.get(w)?.prospects.find(x=>x.id===prospectId&&(x.status==='active'||x.status==='academy-eligible'));if(!p)return false;p.trainingFocus=focus;return true}
function attributeForFocus(f:SchoolTrainingFocus):keyof PlayerAttributes|undefined{return f==='technique'||f==='fundamentals'?'technique':f==='passing'?'passing':f==='finishing'?'finishing':f==='defending'?'tackling':f==='goalkeeping'?'goalkeeping':f==='physical-literacy'?'stamina':f==='decision-making'?'decisions':undefined}
function maybeYouthInjury(w:World,p:SchoolProspect,date:string){if(p.injury){p.injury.monthsRemaining--;if(p.injury.monthsRemaining<=0){p.notes.push(`Recuperado de ${p.injury.name} em ${date}.`);p.injury=undefined}return}const chance=.0025+p.injuryRisk/10000;if(r(w,`${p.id}:${date}:injury`)>chance)return;const roll=r(w,`${p.id}:${date}:injury-sev`),severity:SchoolYouthInjury['severity']=roll>.92?'serious':roll>.62?'moderate':'minor',months=severity==='serious'?2+Math.floor(r(w,`${p.id}:${date}:months`)*4):severity==='moderate'?1+Math.floor(r(w,`${p.id}:${date}:months`)*2):1;p.injury={id:`fsi-${p.id}-${date}`,name:severity==='serious'?'Lesão musculoesquelética juvenil':severity==='moderate'?'Entorse/lesão muscular':'Contusão leve',started:date,monthsRemaining:months,severity};p.notes.push(`${p.injury.name} em ${date}.`)}
function monthlyDevelopment(w:World,s:FootballSchoolState,p:SchoolProspect,date:string,environment=1){maybeYouthInjury(w,p,date);if(p.injury)return;const attr=attributeForFocus(p.trainingFocus),quality=(s.teacher.youthDevelopment*.35+s.teacher.coaching*.2+s.facilityLevel*10+p.motivation*.15+p.schoolAttendance*.1+p.personality.professionalism*.1)/100,investment=Math.min(.22,p.personalInvestment/100000),ageFactor=p.age===14?1.12:1,roll=.55+r(w,`${p.id}:${date}:dev`)*.9,gain=Math.max(0,(quality+investment)*ageFactor*roll*environment);p.currentAbility=Number(Math.min(p.realisationCeiling,p.currentAbility+gain*.38).toFixed(2));if(attr)p.attributes[attr]=Math.round(clamp(p.attributes[attr]+gain*.62,15,99));else if(p.trainingFocus==='weak-foot')p.weakFoot=Math.round(clamp(p.weakFoot+gain*.7));else if(p.trainingFocus==='confidence')p.confidence=clamp(p.confidence+gain*.8);if(p.trainingFocus==='position-discovery'&&p.secondaryPositions.length<2&&r(w,`${p.id}:${date}:position`)<.18){const options:Position[]=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];const next=options.find(x=>x!==p.position&&!p.secondaryPositions.includes(x));if(next)p.secondaryPositions.push(next)}p.monthsInProgram++;p.coachBond=clamp(p.coachBond+.4);p.confidence=clamp(p.confidence+(gain-.45)*.35);p.motivation=clamp(p.motivation+(p.schoolAttendance-70)*.006)}
export function volunteerAtSchool(w:World,date:string,input:{personId:string;personName:string;volunteerType:'manager'|'player'|'staff';focus:SchoolTrainingFocus}){const s=states.get(w);if(!s)return;const m=userManager(w);if(input.volunteerType==='manager'&&input.personId!==m?.id)return;const impact=input.volunteerType==='player'?6:input.volunteerType==='manager'?5:4,media=input.volunteerType==='player'?35:input.volunteerType==='manager'?18:10,session:VolunteerSession={id:`school-vol-${date}-${s.volunteerSessions.length+1}`,date,...input,impact,mediaInterest:media};s.volunteerSessions.push(session);for(const p of s.prospects.filter(x=>x.status==='active'||x.status==='academy-eligible')){p.motivation=clamp(p.motivation+impact*(.35+r(w,`${session.id}:${p.id}`)*.45));if(p.trainingFocus===input.focus)p.confidence=clamp(p.confidence+impact*.45)}s.mediaInterest=clamp(s.mediaInterest+media*.18);s.communityTrust=clamp(s.communityTrust+impact*.35);queueWorldEvent(w,{date,type:'FootballSchoolVolunteerSession',scope:'person',entityIds:[s.id,input.personId],importance:input.volunteerType==='player'?2:1,payload:{focus:input.focus,personName:input.personName,mediaInterest:media}});return session}
function graduate(w:World,s:FootballSchoolState,p:SchoolProspect,date:string,targetClubId='unattached'){const ng=generateNewgenPlayerV3(w,{clubId:targetClubId,countryId:p.countryId,cultureId:culture(p.countryId),season:w.season,serial:9000+s.graduatedPlayerIds.length,academyQuality:45+s.facilityLevel*8,recruitmentReach:50,countryStrength:p.countryId==='BR'||p.countryId==='AR'?75:58});ng.result.player.name=p.name;ng.result.player.age=16;ng.result.player.clubId=targetClubId;ng.result.player.position=p.position;ng.result.player.currentAbility=Math.round(p.currentAbility);ng.result.player.potentialAbility=p.truePotential;ng.result.player.attributes={...p.attributes};ng.secondaryPositions=[...p.secondaryPositions];ng.heightCm=p.heightCm+Math.round(r(w,`${p.id}:growth`)*3);ng.preferredFoot=p.preferredFoot;ng.weakFoot=p.weakFoot;ng.personality={...p.personality};registerNewgenPlayerV3(w,ng,p.countryId);const player=ng.result.player;p.status='graduated';s.graduatedPlayerIds.push(player.id);if(targetClubId!=='unattached'){const club=w.clubs.find(c=>c.id===targetClubId);if(club&&!club.players.some(x=>x.id===player.id))club.players.push(player)}queueWorldEvent(w,{date,type:'FootballSchoolProspectGraduated',scope:'person',entityIds:[p.id,player.id,s.id,targetClubId],importance:p.truePotential>=90?4:p.truePotential>=80?3:2,payload:{name:p.name,potentialTier:p.potentialView.tier,targetClubId,managerBond:p.managerBond}});return player}
export function offerYouthContractFromManagerClub(w:World,date:string,prospectId:string){const s=states.get(w),m=userManager(w),p=s?.prospects.find(x=>x.id===prospectId&&x.status==='academy-eligible');if(!s||!m||!m.currentClubId||!p||p.age<16)return false;const g=clubGovernance(w,m.currentClubId);if(g.managerConfidence<25)return false;graduate(w,s,p,date,m.currentClubId);queueWorldEvent(w,{date,type:'YouthContractFromFootballSchool',scope:'club',entityIds:[p.id,m.currentClubId,s.id],importance:p.truePotential>=88?4:2,payload:{name:p.name,potentialTier:p.potentialView.tier}});return true}
function transitionEligible(w:World,s:FootballSchoolState,p:SchoolProspect,date:string){if(p.status!=='active'||p.age<16)return;p.status='academy-eligible';p.transitionPendingSince=date;p.notes.push(`Elegível para categoria de base desde ${date}.`);queueWorldEvent(w,{date,type:'FootballSchoolAcademyTransitionAvailable',scope:'person',entityIds:[p.id,s.id,s.managerId],importance:p.truePotential>=88?4:2,payload:{name:p.name,potentialTier:p.potentialView.tier,decisionWindowDays:45,managerBond:p.managerBond}})}
function expireTransitions(w:World,s:FootballSchoolState,date:string){for(const p of s.prospects.filter(x=>x.status==='academy-eligible'&&x.transitionPendingSince)){if(day(date)-day(p.transitionPendingSince!)<45)continue;graduate(w,s,p,date,'unattached')}}
export function tickFootballSchool(w:World,date:string){const s=states.get(w);if(!s)return;const month=monthKey(date);if(s.lastMonthlyTick===month){expireTransitions(w,s,date);return}s.lastMonthlyTick=month;const shortfall=Math.max(0,s.monthlyOperatingCost-s.monthlyMunicipalGrant),requested=s.autoManagerSubsidy?Math.min(shortfall,s.recurringManagerSubsidy):0;let personalPaid=0;if(requested>0&&debitManagerWallet(w,s.managerId,date,requested,'school-investment','Subsídio mensal voluntário da escolinha',s.id)){personalPaid=requested;s.managerTotalInvestment+=requested}const uncovered=Math.max(0,shortfall-personalPaid),environment=clamp(1-uncovered/Math.max(1,s.monthlyOperatingCost)*.32,.62,1);if(uncovered>0){s.communityTrust=clamp(s.communityTrust-uncovered/12000);s.teacher.coaching=clamp(s.teacher.coaching-uncovered/60000,25,100)}for(const p of s.prospects.filter(x=>x.status==='active'))monthlyDevelopment(w,s,p,date,environment);if(month.endsWith('-01'))for(const p of s.prospects.filter(x=>x.status==='active')){p.age++;transitionEligible(w,s,p,date)}expireTransitions(w,s,date);if(month.endsWith('-01')||month.endsWith('-07'))for(let i=0;i<Math.max(2,Math.round(3+s.reputation/30));i++)discoverSchoolProspect(w);const elite=s.prospects.filter(x=>(x.status==='active'||x.status==='academy-eligible')&&x.truePotential>=88).length;s.mediaInterest=clamp(s.mediaInterest*.92+elite*1.4+s.reputation*.05);s.reputation=clamp(s.reputation+(s.communityTrust-50)*.01+elite*.06);if(elite&&r(w,`${s.id}:${date}:media`)<.18){const club=userManager(w)?.currentClubId;if(club){supporterCulture(w,club).commercialEngagement=clamp(supporterCulture(w,club).commercialEngagement+.2);clubGovernance(w,club).fanApproval=clamp(clubGovernance(w,club).fanApproval+.15)}queueWorldEvent(w,{date,type:'FootballSchoolMediaFeature',scope:'person',entityIds:[s.id,s.managerId],importance:2,payload:{eliteProspects:elite,reputation:s.reputation,communityTrust:s.communityTrust}})}return{active:s.prospects.filter(x=>x.status==='active').length,academyEligible:s.prospects.filter(x=>x.status==='academy-eligible').length,graduated:s.graduatedPlayerIds.length,eliteProspects:elite,environment:Number(environment.toFixed(2)),managerContribution:personalPaid}}
export function schoolProspectReport(w:World,id:string){const p=states.get(w)?.prospects.find(x=>x.id===id);if(!p)return;const {truePotential:_,realisationCeiling:__,...visible}=p;return{...visible,estimatedPotential:p.potentialView,developmentRisk:Math.round(clamp((100-p.personality.professionalism)*.25+(100-p.familySupport)*.15+(100-p.schoolAttendance)*.25+p.injuryRisk*.15+(100-p.motivation)*.2)),investmentToDate:p.personalInvestment}}
export function snapshotFootballSchool(w:World){const s=states.get(w);return s?JSON.parse(JSON.stringify(s)) as FootballSchoolState:undefined}
export function restoreFootballSchool(w:World,x?:FootballSchoolState){if(x)states.set(w,JSON.parse(JSON.stringify(x)))}
