import type { Player, PlayerAttributes, Position, World } from './engine';
import { deterministicRandom, queueWorldEvent, worldCore } from './world-core-v2';
import { userManager } from './manager-character';
import { debitManagerWallet, managerWallet } from './manager-personal-finance-v1';
import { generateNewgenPlayerV3, registerNewgenPlayerV3, type NewgenPersonality, type NewgenPlayerV3 } from './person-generation-v3';
import { potentialTierFor, type PlayerPotentialLabel } from './player-potential-tier-v1';
import { supporterCulture } from './club-supporter-culture-v1';
import { clubGovernance } from './club-governance';
import { movePlayerCanonical } from './player-roster-integrity-v1';

export type SchoolCountry='BR'|'AR'|'UY'|'PY'|'CL'|'PE'|'CO'|'VE'|'BO'|'EC';
export type SchoolTrainingFocus='fundamentals'|'technique'|'passing'|'finishing'|'defending'|'goalkeeping'|'physical-literacy'|'decision-making'|'weak-foot'|'position-discovery'|'confidence';
export type SchoolFacilityLevel=1|2|3|4|5;
export type SchoolProspectStatus='active'|'academy-eligible'|'graduated'|'released'|'left-program';
export type SchoolYouthInjury={id:string;name:string;started:string;monthsRemaining:number;severity:'minor'|'moderate'|'serious'};
export type SchoolVenueOption={id:'municipal-community'|'municipal-premium'|'private-synthetic'|'professional-rental';name:string;municipal:boolean;quality:number;monthlyDonation:number;description:string};
export type SchoolVenueRental={optionId:SchoolVenueOption['id'];started:string;throughMonth:string;months:number;donatedAmount:number};
export type SchoolMaterialState={uniformSets:number;balls:number;cones:number;bibs:number;firstAidKits:number;equipmentQuality:number;lastGiftDate?:string};
export type SchoolSponsor={id:string;name:string;kind:'neighborhood-business'|'local-company'|'community-partner';monthlyAmount:number;startMonth:string;monthsRemaining:number;active:boolean;managerIntroduced:boolean};
export type SchoolCommunityEvent={id:string;date:string;type:'festival'|'friendly'|'school-drive'|'family-day'|'donation-drive'|'nutrition-day'|'community-clinic';attendance:number;communityImpact:number;mediaImpact:number;notes:string};
export type SchoolClubInterest={id:string;date:string;prospectId:string;clubId:string;strength:number;status:'watching'|'offered'|'accepted'|'rejected'|'expired';managerClub:boolean};
export type SchoolProspect={id:string;playerId:string;name:string;countryId:SchoolCountry;age:number;position:Position;secondaryPositions:Position[];heightCm:number;preferredFoot:'left'|'right';weakFoot:number;attributes:PlayerAttributes;currentAbility:number;truePotential:number;realisationCeiling:number;personality:NewgenPersonality;potentialView:PlayerPotentialLabel;potentialCertainty:number;familySupport:number;schoolAttendance:number;schoolPerformance:number;discipline:number;nutritionSecurity:number;transportAccess:number;dropoutRisk:number;motivation:number;confidence:number;coachBond:number;managerBond:number;injuryRisk:number;injury?:SchoolYouthInjury;monthsInProgram:number;status:SchoolProspectStatus;transitionPendingSince?:string;trainingFocus:SchoolTrainingFocus;personalInvestment:number;scholarshipSupport:number;relationshipOutcome?:'mentor'|'positive'|'neutral'|'rejected-manager-club'|'future-rival';graduatedClubId?:string;notes:string[]};
export type SchoolTeacher={id:string;name:string;countryId:SchoolCountry;coaching:number;youthDevelopment:number;empathy:number;discipline:number;talentIdentification:number;volunteer:boolean};
export type VolunteerSession={id:string;date:string;volunteerType:'manager'|'player'|'staff'|'former-player';personId:string;personName:string;focus:SchoolTrainingFocus;impact:number;mediaInterest:number};
export type FootballSchoolState={id:string;name:string;teamName:string;city:string;countryId:'BR';municipalProgram:true;optional:true;createdSeason:number;managerId:string;facilityLevel:SchoolFacilityLevel;homeBaseType:'municipal-sports-centers';venueRental?:SchoolVenueRental;monthlyMunicipalGrant:number;monthlyOperatingCost:number;autoManagerSubsidy:boolean;recurringManagerSubsidy:number;managerTotalInvestment:number;namingRightsEligible:boolean;teacher:SchoolTeacher;materials:SchoolMaterialState;sponsors:SchoolSponsor[];communityEvents:SchoolCommunityEvent[];clubInterests:SchoolClubInterest[];prospects:SchoolProspect[];volunteerSessions:VolunteerSession[];reputation:number;communityTrust:number;mediaInterest:number;municipalRelationship:number;lastMonthlyTick?:string;graduatedPlayerIds:string[]};

const states=new WeakMap<World,FootballSchoolState>();
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const monthKey=(iso:string)=>iso.slice(0,7);
const day=(iso:string)=>Math.floor(Date.parse(`${iso}T12:00:00Z`)/86400000);
const firstBR=['Adriel','André','Arthur','Breno','Caio','Davi','Enzo','Gabriel','Guilherme','Heitor','João','Kauã','Lucas','Mateus','Miguel','Murilo','Pedro','Rafael','Samuel','Vinícius'];
const lastBR=['Almeida','Barbosa','Cardoso','Costa','Duarte','Ferreira','Gomes','Lima','Martins','Oliveira','Pereira','Rocha','Rodrigues','Santos','Silva','Souza','Teixeira'];
const venueOptions:SchoolVenueOption[]=[
 {id:'municipal-community',name:'Campo comunitário do centro esportivo',municipal:true,quality:1,monthlyDonation:0,description:'Campo municipal compartilhado; é a condição padrão e não exige verba do treinador.'},
 {id:'municipal-premium',name:'Campo municipal reservado em melhor horário',municipal:true,quality:2,monthlyDonation:1800,description:'Doação cobre reserva, iluminação e manutenção de um campo municipal melhor.'},
 {id:'private-synthetic',name:'Campo society/sintético alugado',municipal:false,quality:3,monthlyDonation:4200,description:'Aluguel temporário de campo privado com piso e estrutura superiores.'},
 {id:'professional-rental',name:'Centro de treinamento profissional alugado',municipal:false,quality:4,monthlyDonation:8500,description:'Uso pontual/temporário de estrutura profissional; não transfere propriedade à escolinha.'}
];
function r(w:World,k:string){return deterministicRandom(w,'football-school',k)}
function pick<T>(w:World,k:string,a:T[]){return a[Math.floor(r(w,k)*a.length)]}
function country(w:World,key:string):SchoolCountry{const x=r(w,`${key}:country`);if(x<.84)return'BR';const pool:SchoolCountry[]=['AR','UY','PY','CL','PE','CO','VE','BO','EC'];return pool[Math.floor(r(w,`${key}:country2`)*pool.length)]}
function culture(c:SchoolCountry){return c==='BR'?'pt-BR':'es'}
function teacher(w:World,managerId:string):SchoolTeacher{const key=`teacher:${managerId}:${w.season}`;return{id:`school-teacher-${Math.floor(r(w,key)*1e8).toString(36)}`,name:`${pick(w,`${key}:f`,firstBR)} ${pick(w,`${key}:l`,lastBR)}`,countryId:'BR',coaching:45+Math.round(r(w,`${key}:coach`)*35),youthDevelopment:55+Math.round(r(w,`${key}:youth`)*35),empathy:50+Math.round(r(w,`${key}:emp`)*45),discipline:40+Math.round(r(w,`${key}:disc`)*50),talentIdentification:40+Math.round(r(w,`${key}:talent`)*45),volunteer:false}}
function prospectFromNewgen(w:World,ng:NewgenPlayerV3,key:string,c:SchoolCountry):SchoolProspect{const p=ng.result.player,age=r(w,`${key}:age`)<.54?14:15,truePotential=Math.round(clamp(p.potentialAbility,55,99)),certainty=18+Math.round(r(w,`${key}:certainty`)*22),realisation=Math.round(clamp(truePotential-(7+r(w,`${key}:realise`)*18),45,truePotential));p.age=age;p.currentAbility=Math.max(24,Math.min(p.currentAbility,age===14?46:50));p.attributes=Object.fromEntries(Object.entries(p.attributes).map(([k,v])=>[k,Math.max(15,Math.round(v-(age===14?8:5))) ])) as PlayerAttributes;const schoolAttendance=65+Math.round(r(w,`${key}:school`)*35),familySupport=35+Math.round(r(w,`${key}:family`)*60),discipline=40+Math.round(r(w,`${key}:discipline`)*55),nutrition=38+Math.round(r(w,`${key}:nutrition`)*60),transport=35+Math.round(r(w,`${key}:transport`)*62);return{id:`fsp-${p.id}`,playerId:p.id,name:p.name,countryId:c,age,position:p.position,secondaryPositions:[...ng.secondaryPositions],heightCm:ng.heightCm,preferredFoot:ng.preferredFoot,weakFoot:ng.weakFoot,attributes:{...p.attributes},currentAbility:p.currentAbility,truePotential,realisationCeiling:realisation,personality:{...ng.personality},potentialView:potentialTierFor({potential:truePotential,position:p.position,certainty,age}),potentialCertainty:certainty,familySupport,schoolAttendance,schoolPerformance:48+Math.round(r(w,`${key}:performance`)*48),discipline,nutritionSecurity:nutrition,transportAccess:transport,dropoutRisk:0,motivation:55+Math.round(r(w,`${key}:motivation`)*42),confidence:45+Math.round(r(w,`${key}:conf`)*45),coachBond:45+Math.round(r(w,`${key}:coachbond`)*40),managerBond:20,injuryRisk:15+Math.round(r(w,`${key}:injury`)*30),monthsInProgram:0,status:'active',trainingFocus:'fundamentals',personalInvestment:0,scholarshipSupport:0,notes:[]}}
function activeVenue(s:FootballSchoolState,date:string){if(!s.venueRental||monthKey(date)>s.venueRental.throughMonth)return venueOptions[0];return venueOptions.find(v=>v.id===s.venueRental!.optionId)??venueOptions[0]}
function activeSponsorIncome(s:FootballSchoolState){return s.sponsors.filter(x=>x.active).reduce((a,x)=>a+x.monthlyAmount,0)}
function materialFactor(s:FootballSchoolState){return clamp(.82+s.materials.equipmentQuality/280,.82,1.17)}
function recomputeDropoutRisk(p:SchoolProspect){p.dropoutRisk=Math.round(clamp((100-p.familySupport)*.2+(100-p.schoolAttendance)*.25+(100-p.schoolPerformance)*.12+(100-p.discipline)*.12+(100-p.nutritionSecurity)*.12+(100-p.transportAccess)*.12+(100-p.motivation)*.07-p.scholarshipSupport*.12));return p.dropoutRisk}

export function schoolVenueOptions(){return venueOptions.map(v=>({...v}))}
export function createFootballSchool(w:World,input:{name?:string;teamName?:string;city?:string;initialProspects?:number}={}){const existing=states.get(w);if(existing)return existing;const m=userManager(w);if(!m)throw new Error('Escolinha exige o treinador controlável.');const name=input.name??'Projeto Bola do Futuro',s:FootballSchoolState={id:`municipal-school-${m.id}`,name,teamName:input.teamName??name,city:input.city??'São Paulo',countryId:'BR',municipalProgram:true,optional:true,createdSeason:w.season,managerId:m.id,facilityLevel:1,homeBaseType:'municipal-sports-centers',monthlyMunicipalGrant:7500,monthlyOperatingCost:9000,autoManagerSubsidy:false,recurringManagerSubsidy:0,managerTotalInvestment:0,namingRightsEligible:false,teacher:teacher(w,m.id),materials:{uniformSets:1,balls:8,cones:20,bibs:20,firstAidKits:1,equipmentQuality:38},sponsors:[],communityEvents:[],clubInterests:[],prospects:[],volunteerSessions:[],reputation:20,communityTrust:58,mediaInterest:12,municipalRelationship:62,graduatedPlayerIds:[]};states.set(w,s);for(let i=0;i<(input.initialProspects??18);i++)discoverSchoolProspect(w,i+1);queueWorldEvent(w,{date:worldCore(w).date,type:'FootballSchoolCreated',scope:'person',entityIds:[m.id,s.id],importance:2,payload:{name:s.name,teamName:s.teamName,city:s.city,prospects:s.prospects.length,homeBaseType:s.homeBaseType}});return s}
export function footballSchool(w:World){return states.get(w)}
export function discoverSchoolProspect(w:World,serial?:number){const s=states.get(w);if(!s)throw new Error('Escolinha ainda não foi criada.');const n=serial??s.prospects.length+1,key=`${s.id}:${w.season}:${n}:${s.prospects.length}`,c=country(w,key),ng=generateNewgenPlayerV3(w,{clubId:s.id,countryId:c,cultureId:culture(c),season:w.season,serial:n,academyQuality:35+s.facilityLevel*7,recruitmentReach:40+s.reputation*.25,countryStrength:c==='BR'||c==='AR'?75:58}),p=prospectFromNewgen(w,ng,key,c);if(s.prospects.some(x=>x.playerId===p.playerId))return s.prospects.find(x=>x.playerId===p.playerId)!;s.prospects.push(p);return p}
export function configureSchoolSubsidy(w:World,input:{enabled:boolean;monthlyAmount?:number}){const s=states.get(w),m=userManager(w);if(!s||!m||m.id!==s.managerId)return false;s.autoManagerSubsidy=input.enabled;s.recurringManagerSubsidy=input.enabled?Math.max(0,Math.round(input.monthlyAmount??0)):0;return true}

export function rentBetterSchoolField(w:World,date:string,optionId:Exclude<SchoolVenueOption['id'],'municipal-community'>,months=1){const s=states.get(w),m=userManager(w),option=venueOptions.find(v=>v.id===optionId);if(!s||!m||m.id!==s.managerId||!option)return false;const duration=Math.max(1,Math.min(12,Math.round(months))),amount=option.monthlyDonation*duration;if(!debitManagerWallet(w,m.id,date,amount,'donation',`Doação para uso temporário: ${option.name}`,s.id))return false;const start=monthKey(date),d=new Date(`${start}-01T12:00:00Z`);d.setUTCMonth(d.getUTCMonth()+duration-1);const through=d.toISOString().slice(0,7);s.venueRental={optionId,started:date,throughMonth:through,months:duration,donatedAmount:amount};s.managerTotalInvestment+=amount;s.namingRightsEligible=s.namingRightsEligible||s.managerTotalInvestment>=30000;s.communityTrust=clamp(s.communityTrust+Math.min(4,amount/6000));queueWorldEvent(w,{date,type:'FootballSchoolFieldRentalDonated',scope:'person',entityIds:[m.id,s.id],importance:option.quality>=4?3:2,payload:{optionId,name:option.name,months:duration,amount,throughMonth:through,balance:managerWallet(w,m.id).balance}});return s.venueRental}

export function giftSchoolMaterials(w:World,date:string,kind:'uniforms'|'balls'|'training-kit'|'first-aid'|'complete-kit',quantity=1){const s=states.get(w),m=userManager(w);if(!s||!m||m.id!==s.managerId)return false;const q=Math.max(1,Math.min(20,Math.round(quantity))),unit={uniforms:1400,balls:650,'training-kit':900,'first-aid':500,'complete-kit':3200}[kind],amount=unit*q;if(!debitManagerWallet(w,m.id,date,amount,'donation',`Presente à escolinha: ${kind}`,s.id))return false;if(kind==='uniforms'||kind==='complete-kit')s.materials.uniformSets+=q;if(kind==='balls'||kind==='complete-kit')s.materials.balls+=6*q;if(kind==='training-kit'||kind==='complete-kit'){s.materials.cones+=12*q;s.materials.bibs+=12*q}if(kind==='first-aid'||kind==='complete-kit')s.materials.firstAidKits+=q;s.materials.equipmentQuality=Math.round(clamp(s.materials.equipmentQuality+Math.min(12,q*(kind==='complete-kit'?4:2))));s.materials.lastGiftDate=date;s.managerTotalInvestment+=amount;s.namingRightsEligible=s.namingRightsEligible||s.managerTotalInvestment>=30000;s.communityTrust=clamp(s.communityTrust+Math.min(5,amount/4000));s.mediaInterest=clamp(s.mediaInterest+Math.min(4,amount/6000));queueWorldEvent(w,{date,type:'FootballSchoolMaterialGift',scope:'person',entityIds:[m.id,s.id],importance:amount>=10000?2:1,payload:{kind,quantity:q,amount,equipmentQuality:s.materials.equipmentQuality}});return true}

export function renameFootballSchoolTeam(w:World,date:string,teamName:string){const s=states.get(w),m=userManager(w),name=teamName.trim().slice(0,60);if(!s||!m||m.id!==s.managerId||!s.namingRightsEligible||name.length<3)return false;const previous=s.teamName;s.teamName=name;queueWorldEvent(w,{date,type:'FootballSchoolTeamNamedByDonor',scope:'person',entityIds:[m.id,s.id],importance:2,payload:{previous,teamName:name,programName:s.name,managerTotalInvestment:s.managerTotalInvestment}});return true}

export function seekLocalSchoolSponsor(w:World,date:string,input:{name:string;kind?:SchoolSponsor['kind'];requestedMonthly?:number}){const s=states.get(w),m=userManager(w);if(!s||!m||m.id!==s.managerId)return;const name=input.name.trim().slice(0,80);if(name.length<2||s.sponsors.some(x=>x.active&&x.name.toLowerCase()===name.toLowerCase()))return;const requested=Math.max(500,Math.min(12000,Math.round(input.requestedMonthly??1800))),chance=clamp(.22+s.communityTrust*.004+s.reputation*.003+s.mediaInterest*.0015-requested/30000,.08,.82),accepted=r(w,`${s.id}:${date}:sponsor:${name}`)<chance;queueWorldEvent(w,{date,type:accepted?'FootballSchoolLocalSponsorSecured':'FootballSchoolLocalSponsorDeclined',scope:'person',entityIds:[m.id,s.id],importance:accepted?2:1,payload:{name,requestedMonthly:requested,chance:Number(chance.toFixed(2))}});if(!accepted)return{accepted:false};const months=6+Math.floor(r(w,`${s.id}:${date}:sponsor-months:${name}`)*13),sponsor:SchoolSponsor={id:`school-sponsor-${Math.abs(hash(`${name}:${date}`)).toString(36)}`,name,kind:input.kind??'neighborhood-business',monthlyAmount:requested,startMonth:monthKey(date),monthsRemaining:months,active:true,managerIntroduced:true};s.sponsors.push(sponsor);s.communityTrust=clamp(s.communityTrust+2);s.reputation=clamp(s.reputation+1);return{accepted:true,sponsor}
}

export function investInSchool(w:World,date:string,amount:number,purpose:'operations'|'facilities'|'equipment'|'scholarships'|'scouting'|'nutrition'|'transport'){const s=states.get(w),m=userManager(w);if(!s||!m||m.id!==s.managerId||amount<=0)return false;if(!debitManagerWallet(w,m.id,date,amount,'school-investment',`Investimento voluntário na escolinha: ${purpose}`,s.id))return false;s.managerTotalInvestment+=Math.round(amount);s.namingRightsEligible=s.namingRightsEligible||s.managerTotalInvestment>=30000;if(purpose==='facilities'&&amount>=25000&&s.facilityLevel<5)s.facilityLevel=(s.facilityLevel+1) as SchoolFacilityLevel;if(purpose==='equipment')s.materials.equipmentQuality=Math.round(clamp(s.materials.equipmentQuality+amount/5000));if(purpose==='scholarships'){s.communityTrust=clamp(s.communityTrust+amount/8000);for(const p of s.prospects.filter(x=>x.status==='active').sort((a,b)=>b.dropoutRisk-a.dropoutRisk).slice(0,Math.max(1,Math.floor(amount/3000))))p.scholarshipSupport=clamp(p.scholarshipSupport+12)}if(purpose==='nutrition')for(const p of s.prospects.filter(x=>x.status==='active'))p.nutritionSecurity=clamp(p.nutritionSecurity+Math.min(10,amount/2500));if(purpose==='transport')for(const p of s.prospects.filter(x=>x.status==='active'))p.transportAccess=clamp(p.transportAccess+Math.min(10,amount/2500));if(purpose==='scouting')s.reputation=clamp(s.reputation+amount/12000);queueWorldEvent(w,{date,type:'FootballSchoolInvestment',scope:'person',entityIds:[m.id,s.id],importance:amount>=50000?3:1,payload:{amount,purpose,balance:managerWallet(w,m.id).balance,facilityLevel:s.facilityLevel,namingRightsEligible:s.namingRightsEligible}});return true}

export function investInSchoolProspect(w:World,date:string,prospectId:string,amount:number,focus:SchoolTrainingFocus){const s=states.get(w),m=userManager(w),p=s?.prospects.find(x=>x.id===prospectId&&(x.status==='active'||x.status==='academy-eligible'));if(!s||!m||!p||amount<=0)return false;if(!debitManagerWallet(w,m.id,date,amount,'school-investment',`Treinamento individual de ${p.name}: ${focus}`,p.id))return false;p.personalInvestment+=Math.round(amount);s.managerTotalInvestment+=Math.round(amount);s.namingRightsEligible=s.namingRightsEligible||s.managerTotalInvestment>=30000;p.trainingFocus=focus;p.managerBond=clamp(p.managerBond+Math.min(10,amount/2500));p.motivation=clamp(p.motivation+Math.min(7,amount/4000));const upside=Math.min(5,Math.log10(1+amount/1000)*1.5);p.realisationCeiling=Math.round(clamp(p.realisationCeiling+upside,p.currentAbility,p.truePotential));p.potentialCertainty=clamp(p.potentialCertainty+Math.min(8,amount/4000));p.potentialView=potentialTierFor({potential:p.truePotential,position:p.position,certainty:p.potentialCertainty,age:p.age});return true}
export function setSchoolProspectTraining(w:World,prospectId:string,focus:SchoolTrainingFocus){const p=states.get(w)?.prospects.find(x=>x.id===prospectId&&(x.status==='active'||x.status==='academy-eligible'));if(!p)return false;p.trainingFocus=focus;return true}
function attributeForFocus(f:SchoolTrainingFocus):keyof PlayerAttributes|undefined{return f==='technique'||f==='fundamentals'?'technique':f==='passing'?'passing':f==='finishing'?'finishing':f==='defending'?'tackling':f==='goalkeeping'?'goalkeeping':f==='physical-literacy'?'stamina':f==='decision-making'?'decisions':undefined}
function maybeYouthInjury(w:World,p:SchoolProspect,date:string){if(p.injury){p.injury.monthsRemaining--;if(p.injury.monthsRemaining<=0){p.notes.push(`Recuperado de ${p.injury.name} em ${date}.`);p.injury=undefined}return}const chance=.0025+p.injuryRisk/10000;if(r(w,`${p.id}:${date}:injury`)>chance)return;const roll=r(w,`${p.id}:${date}:injury-sev`),severity:SchoolYouthInjury['severity']=roll>.92?'serious':roll>.62?'moderate':'minor',months=severity==='serious'?2+Math.floor(r(w,`${p.id}:${date}:months`)*4):severity==='moderate'?1+Math.floor(r(w,`${p.id}:${date}:months`)*2):1;p.injury={id:`fsi-${p.id}-${date}`,name:severity==='serious'?'Lesão musculoesquelética juvenil':severity==='moderate'?'Entorse/lesão muscular':'Contusão leve',started:date,monthsRemaining:months,severity};p.notes.push(`${p.injury.name} em ${date}.`)}
function monthlyDevelopment(w:World,s:FootballSchoolState,p:SchoolProspect,date:string,environment=1){maybeYouthInjury(w,p,date);if(p.injury)return;const attr=attributeForFocus(p.trainingFocus),venue=activeVenue(s,date),quality=(s.teacher.youthDevelopment*.32+s.teacher.coaching*.18+s.facilityLevel*7+venue.quality*4+p.motivation*.13+p.schoolAttendance*.08+p.personality.professionalism*.1+p.nutritionSecurity*.05+p.transportAccess*.03)/100,investment=Math.min(.22,p.personalInvestment/100000),ageFactor=p.age===14?1.12:1,roll=.55+r(w,`${p.id}:${date}:dev`)*.9,gain=Math.max(0,(quality+investment)*ageFactor*roll*environment*materialFactor(s));p.currentAbility=Number(Math.min(p.realisationCeiling,p.currentAbility+gain*.38).toFixed(2));if(attr)p.attributes[attr]=Math.round(clamp(p.attributes[attr]+gain*.62,15,99));else if(p.trainingFocus==='weak-foot')p.weakFoot=Math.round(clamp(p.weakFoot+gain*.7));else if(p.trainingFocus==='confidence')p.confidence=clamp(p.confidence+gain*.8);if(p.trainingFocus==='position-discovery'&&p.secondaryPositions.length<2&&r(w,`${p.id}:${date}:position`)<.18){const options:Position[]=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];const next=options.find(x=>x!==p.position&&!p.secondaryPositions.includes(x));if(next)p.secondaryPositions.push(next)}p.monthsInProgram++;p.coachBond=clamp(p.coachBond+.4);p.confidence=clamp(p.confidence+(gain-.45)*.35);p.motivation=clamp(p.motivation+(p.schoolAttendance-70)*.006);p.schoolPerformance=clamp(p.schoolPerformance+(p.discipline-50)*.012+(p.schoolAttendance-75)*.018);p.schoolAttendance=clamp(p.schoolAttendance+(p.transportAccess-55)*.006+(p.familySupport-55)*.004);recomputeDropoutRisk(p)}

export function volunteerAtSchool(w:World,date:string,input:{personId:string;personName:string;volunteerType:'manager'|'player'|'staff'|'former-player';focus:SchoolTrainingFocus}){const s=states.get(w);if(!s)return;const m=userManager(w);if(input.volunteerType==='manager'&&input.personId!==m?.id)return;const impact=input.volunteerType==='player'?6:input.volunteerType==='former-player'?5.5:input.volunteerType==='manager'?5:4,media=input.volunteerType==='player'?35:input.volunteerType==='former-player'?28:input.volunteerType==='manager'?18:10,session:VolunteerSession={id:`school-vol-${date}-${s.volunteerSessions.length+1}`,date,...input,impact,mediaInterest:media};s.volunteerSessions.push(session);for(const p of s.prospects.filter(x=>x.status==='active'||x.status==='academy-eligible')){p.motivation=clamp(p.motivation+impact*(.35+r(w,`${session.id}:${p.id}`)*.45));if(p.trainingFocus===input.focus)p.confidence=clamp(p.confidence+impact*.45);if(input.volunteerType==='manager')p.managerBond=clamp(p.managerBond+1.2)}s.mediaInterest=clamp(s.mediaInterest+media*.18);s.communityTrust=clamp(s.communityTrust+impact*.35);queueWorldEvent(w,{date,type:'FootballSchoolVolunteerSession',scope:'person',entityIds:[s.id,input.personId],importance:input.volunteerType==='player'||input.volunteerType==='former-player'?2:1,payload:{focus:input.focus,personName:input.personName,volunteerType:input.volunteerType,mediaInterest:media}});return session}

export function holdSchoolCommunityEvent(w:World,date:string,type:SchoolCommunityEvent['type']){const s=states.get(w);if(!s)return;const attendance=Math.round(35+s.communityTrust*2+r(w,`${s.id}:${date}:${type}:attendance`)*180),communityImpact=2+r(w,`${s.id}:${date}:${type}:community`)*6,mediaImpact=type==='festival'||type==='friendly'?4+r(w,`${s.id}:${date}:${type}:media`)*10:1+r(w,`${s.id}:${date}:${type}:media`)*6,e:SchoolCommunityEvent={id:`school-event-${date}-${s.communityEvents.length+1}`,date,type,attendance,communityImpact:Number(communityImpact.toFixed(1)),mediaImpact:Number(mediaImpact.toFixed(1)),notes:''};s.communityEvents.push(e);s.communityTrust=clamp(s.communityTrust+communityImpact);s.mediaInterest=clamp(s.mediaInterest+mediaImpact);s.municipalRelationship=clamp(s.municipalRelationship+(type==='school-drive'||type==='family-day'?3:1));if(type==='nutrition-day')for(const p of s.prospects.filter(x=>x.status==='active'))p.nutritionSecurity=clamp(p.nutritionSecurity+2);if(type==='school-drive')for(const p of s.prospects.filter(x=>x.status==='active')){p.schoolAttendance=clamp(p.schoolAttendance+2);p.schoolPerformance=clamp(p.schoolPerformance+1)}queueWorldEvent(w,{date,type:'FootballSchoolCommunityEvent',scope:'person',entityIds:[s.id,s.managerId],importance:attendance>250?2:1,payload:e});return e}

function rarityFor(potential:number):NewgenPlayerV3['result']['rarity']{return potential>=94?'generational':potential>=88?'elite':potential>=76?'promising':'ordinary'}
function materializeProspect(w:World,p:SchoolProspect,targetClubId:string):Player{const player:Player={id:p.playerId,clubId:targetClubId,name:p.name,position:p.position,age:16,currentAbility:Math.round(p.currentAbility),potentialAbility:p.truePotential,condition:96,morale:72,attributes:{...p.attributes}},ng:NewgenPlayerV3={result:{player,profileSeed:`football-school:${p.playerId}`,rarity:rarityFor(p.truePotential)},preferredFoot:p.preferredFoot,weakFoot:p.weakFoot,secondaryPositions:[...p.secondaryPositions],heightCm:p.heightCm,personality:{...p.personality},cultureId:culture(p.countryId),potentialLabel:potentialTierFor({potential:p.truePotential,position:p.position,certainty:p.potentialCertainty,age:16})};registerNewgenPlayerV3(w,ng,p.countryId);if(targetClubId!=='unattached')movePlayerCanonical(w,player,targetClubId);return player}
function graduate(w:World,s:FootballSchoolState,p:SchoolProspect,date:string,targetClubId='unattached'){if(p.status==='graduated')return;const player=materializeProspect(w,p,targetClubId);p.status='graduated';p.graduatedClubId=targetClubId;if(!s.graduatedPlayerIds.includes(player.id))s.graduatedPlayerIds.push(player.id);if(!p.relationshipOutcome)p.relationshipOutcome=p.managerBond>=78?'mentor':p.managerBond>=55?'positive':'neutral';queueWorldEvent(w,{date,type:'FootballSchoolProspectGraduated',scope:'person',entityIds:[p.id,player.id,s.id,targetClubId],importance:p.truePotential>=94?5:p.truePotential>=88?4:p.truePotential>=80?3:2,payload:{name:p.name,potentialTier:p.potentialView.tier,targetClubId,managerBond:p.managerBond,relationshipOutcome:p.relationshipOutcome,persistentPlayerId:p.playerId}});return player}

export function offerYouthContractFromManagerClub(w:World,date:string,prospectId:string){const s=states.get(w),m=userManager(w),p=s?.prospects.find(x=>x.id===prospectId&&x.status==='academy-eligible');if(!s||!m||!m.currentClubId||!p||p.age<16)return false;const g=clubGovernance(w,m.currentClubId);if(g.managerConfidence<25)return false;const club=w.clubs.find(c=>c.id===m.currentClubId),appeal=clamp((club?.reputation??55)*.5+p.managerBond*.34+p.familySupport*.1+p.motivation*.06),acceptChance=clamp(.18+appeal/135-(p.managerBond<30?.12:0),.12,.92);if(r(w,`${p.id}:${date}:manager-club-offer`)>acceptChance){p.relationshipOutcome=r(w,`${p.id}:${date}:rival-seed`)<.18?'future-rival':'rejected-manager-club';p.notes.push(`Recusou proposta da base do clube do treinador em ${date}.`);s.clubInterests.push({id:`school-interest-${s.clubInterests.length+1}`,date,prospectId:p.id,clubId:m.currentClubId,strength:Math.round(appeal),status:'rejected',managerClub:true});queueWorldEvent(w,{date,type:'FootballSchoolManagerClubRejected',scope:'person',entityIds:[p.id,p.playerId,m.currentClubId,s.managerId],importance:p.truePotential>=88?4:2,payload:{name:p.name,managerBond:p.managerBond,relationshipOutcome:p.relationshipOutcome,acceptChance:Number(acceptChance.toFixed(2))}});return false}graduate(w,s,p,date,m.currentClubId);s.clubInterests.push({id:`school-interest-${s.clubInterests.length+1}`,date,prospectId:p.id,clubId:m.currentClubId,strength:Math.round(appeal),status:'accepted',managerClub:true});queueWorldEvent(w,{date,type:'YouthContractFromFootballSchool',scope:'club',entityIds:[p.id,p.playerId,m.currentClubId,s.id],importance:p.truePotential>=88?4:2,payload:{name:p.name,potentialTier:p.potentialView.tier,persistentPlayerId:p.playerId}});return true}

export function externalClubApproachSchoolProspect(w:World,date:string,prospectId:string,clubId:string){const s=states.get(w),p=s?.prospects.find(x=>x.id===prospectId&&x.status==='academy-eligible'),club=w.clubs.find(c=>c.id===clubId);if(!s||!p||!club)return false;const managerClub=userManager(w)?.currentClubId===clubId,appeal=clamp(club.reputation*.65+p.familySupport*.12+p.motivation*.13+(100-p.managerBond)*(managerClub?-.08:.1)),acceptChance=clamp(.16+appeal/130,.12,.9),accepted=r(w,`${p.id}:${date}:external:${clubId}`)<acceptChance;const interest:SchoolClubInterest={id:`school-interest-${s.clubInterests.length+1}`,date,prospectId:p.id,clubId,strength:Math.round(appeal),status:accepted?'accepted':'rejected',managerClub};s.clubInterests.push(interest);if(accepted){graduate(w,s,p,date,clubId);if(!managerClub&&p.managerBond>=72)p.relationshipOutcome='mentor';queueWorldEvent(w,{date,type:'FootballSchoolExternalClubSignedProspect',scope:'club',entityIds:[p.id,p.playerId,clubId,s.id],importance:p.truePotential>=90?4:2,payload:{name:p.name,managerBond:p.managerBond,persistentPlayerId:p.playerId}})}else queueWorldEvent(w,{date,type:'FootballSchoolExternalClubRejected',scope:'person',entityIds:[p.id,p.playerId,clubId,s.id],importance:1,payload:{name:p.name}});return accepted}

function transitionEligible(w:World,s:FootballSchoolState,p:SchoolProspect,date:string){if(p.status!=='active'||p.age<16)return;p.status='academy-eligible';p.transitionPendingSince=date;p.notes.push(`Elegível para categoria de base desde ${date}.`);queueWorldEvent(w,{date,type:'FootballSchoolAcademyTransitionAvailable',scope:'person',entityIds:[p.id,p.playerId,s.id,s.managerId],importance:p.truePotential>=88?4:2,payload:{name:p.name,potentialTier:p.potentialView.tier,decisionWindowDays:45,managerBond:p.managerBond,persistentPlayerId:p.playerId}})}
function expireTransitions(w:World,s:FootballSchoolState,date:string){for(const p of s.prospects.filter(x=>x.status==='academy-eligible'&&x.transitionPendingSince)){if(day(date)-day(p.transitionPendingSince!)<45)continue;const candidates=w.clubs.filter(c=>c.id!==userManager(w)?.currentClubId).sort((a,b)=>b.reputation-a.reputation),club=candidates[Math.floor(r(w,`${p.id}:${date}:fallback-club`)*Math.min(8,Math.max(1,candidates.length)))];if(club&&r(w,`${p.id}:${date}:fallback-offer`)<clamp(.15+s.reputation*.004+p.potentialCertainty*.003,.12,.65))externalClubApproachSchoolProspect(w,date,p.id,club.id);if(p.status==='academy-eligible')graduate(w,s,p,date,'unattached')}}
function maybeDropout(w:World,s:FootballSchoolState,p:SchoolProspect,date:string){if(p.status!=='active')return;const risk=recomputeDropoutRisk(p);if(risk<45||r(w,`${p.id}:${date}:dropout`)>clamp((risk-35)/650,.005,.12))return;p.status='left-program';p.notes.push(`Deixou o projeto em ${date}; risco social/escolar acumulado ${risk}.`);queueWorldEvent(w,{date,type:'FootballSchoolProspectLeftProgram',scope:'person',entityIds:[p.id,p.playerId,s.id],importance:p.truePotential>=88?3:1,payload:{name:p.name,dropoutRisk:risk,schoolAttendance:p.schoolAttendance,familySupport:p.familySupport}})}
function monthlySocialDynamics(w:World,s:FootballSchoolState,p:SchoolProspect,date:string){p.familySupport=clamp(p.familySupport+(r(w,`${p.id}:${date}:family`)-.5)*1.6);p.discipline=clamp(p.discipline+(r(w,`${p.id}:${date}:discipline`)-.5)*1.4+(s.teacher.discipline-55)*.006);p.nutritionSecurity=clamp(p.nutritionSecurity+(r(w,`${p.id}:${date}:nutrition`)-.5)*1.2);p.transportAccess=clamp(p.transportAccess+(r(w,`${p.id}:${date}:transport`)-.5)*1.1);if(p.scholarshipSupport>0){p.schoolAttendance=clamp(p.schoolAttendance+.5);p.schoolPerformance=clamp(p.schoolPerformance+.35);p.scholarshipSupport=clamp(p.scholarshipSupport-.4)}recomputeDropoutRisk(p);maybeDropout(w,s,p,date)}
function maybeExternalScout(w:World,s:FootballSchoolState,date:string){const eligible=s.prospects.filter(p=>(p.status==='active'||p.status==='academy-eligible')&&p.age>=15);if(!eligible.length||r(w,`${s.id}:${date}:external-scout`)>clamp(.04+s.reputation*.002+s.mediaInterest*.001,.04,.32))return;const p=eligible.sort((a,b)=>b.currentAbility-a.currentAbility)[Math.floor(r(w,`${s.id}:${date}:scout-pick`)*Math.min(4,eligible.length))],clubs=w.clubs.filter(c=>c.id!==userManager(w)?.currentClubId);if(!p||!clubs.length)return;const club=clubs[Math.floor(r(w,`${p.id}:${date}:scout-club`)*clubs.length)];s.clubInterests.push({id:`school-interest-${s.clubInterests.length+1}`,date,prospectId:p.id,clubId:club.id,strength:Math.round(clamp(25+club.reputation*.45+s.reputation*.2)),status:'watching',managerClub:false});p.potentialCertainty=clamp(p.potentialCertainty+2);p.potentialView=potentialTierFor({potential:p.truePotential,position:p.position,certainty:p.potentialCertainty,age:p.age});queueWorldEvent(w,{date,type:'FootballSchoolExternalScoutVisit',scope:'club',entityIds:[p.id,p.playerId,club.id,s.id],importance:p.truePotential>=88?3:1,payload:{name:p.name,clubId:club.id,potentialView:p.potentialView}})}

export function tickFootballSchool(w:World,date:string){const s=states.get(w);if(!s)return;const month=monthKey(date);if(s.lastMonthlyTick===month){expireTransitions(w,s,date);return}s.lastMonthlyTick=month;for(const sp of s.sponsors.filter(x=>x.active)){sp.monthsRemaining--;if(sp.monthsRemaining<=0)sp.active=false}const sponsorIncome=activeSponsorIncome(s),shortfall=Math.max(0,s.monthlyOperatingCost-s.monthlyMunicipalGrant-sponsorIncome),requested=s.autoManagerSubsidy?Math.min(shortfall,s.recurringManagerSubsidy):0;let personalPaid=0;if(requested>0&&debitManagerWallet(w,s.managerId,date,requested,'school-investment','Subsídio mensal voluntário da escolinha',s.id)){personalPaid=requested;s.managerTotalInvestment+=requested;s.namingRightsEligible=s.namingRightsEligible||s.managerTotalInvestment>=30000}const uncovered=Math.max(0,shortfall-personalPaid),environment=clamp(1-uncovered/Math.max(1,s.monthlyOperatingCost)*.32,.62,1);if(uncovered>0){s.communityTrust=clamp(s.communityTrust-uncovered/12000);s.teacher.coaching=clamp(s.teacher.coaching-uncovered/60000,25,100);s.municipalRelationship=clamp(s.municipalRelationship-uncovered/18000)}for(const p of s.prospects.filter(x=>x.status==='active')){monthlySocialDynamics(w,s,p,date);if(p.status==='active')monthlyDevelopment(w,s,p,date,environment)}if(month.endsWith('-01'))for(const p of s.prospects.filter(x=>x.status==='active')){p.age++;transitionEligible(w,s,p,date)}expireTransitions(w,s,date);if(month.endsWith('-01')||month.endsWith('-07'))for(let i=0;i<Math.max(2,Math.round(3+s.reputation/30));i++)discoverSchoolProspect(w);maybeExternalScout(w,s,date);const elite=s.prospects.filter(x=>(x.status==='active'||x.status==='academy-eligible')&&x.truePotential>=88).length;s.mediaInterest=clamp(s.mediaInterest*.92+elite*1.4+s.reputation*.05+s.communityEvents.filter(e=>monthKey(e.date)===month).reduce((a,e)=>a+e.mediaImpact*.12,0));s.reputation=clamp(s.reputation+(s.communityTrust-50)*.01+elite*.06+sponsorIncome/50000);if(elite&&r(w,`${s.id}:${date}:media`)<.18){const club=userManager(w)?.currentClubId;if(club){supporterCulture(w,club).commercialEngagement=clamp(supporterCulture(w,club).commercialEngagement+.2);clubGovernance(w,club).fanApproval=clamp(clubGovernance(w,club).fanApproval+.15)}queueWorldEvent(w,{date,type:'FootballSchoolMediaFeature',scope:'person',entityIds:[s.id,s.managerId],importance:2,payload:{eliteProspects:elite,reputation:s.reputation,communityTrust:s.communityTrust,teamName:s.teamName,venue:activeVenue(s,date).name}})}return{active:s.prospects.filter(x=>x.status==='active').length,academyEligible:s.prospects.filter(x=>x.status==='academy-eligible').length,graduated:s.graduatedPlayerIds.length,leftProgram:s.prospects.filter(x=>x.status==='left-program').length,eliteProspects:elite,environment:Number(environment.toFixed(2)),managerContribution:personalPaid,sponsorIncome,venue:activeVenue(s,date).id}}

export function schoolProspectReport(w:World,id:string){const p=states.get(w)?.prospects.find(x=>x.id===id);if(!p)return;const {truePotential:_,realisationCeiling:__,...visible}=p;return{...visible,estimatedPotential:p.potentialView,developmentRisk:Math.round(clamp((100-p.personality.professionalism)*.2+(100-p.familySupport)*.12+(100-p.schoolAttendance)*.18+p.injuryRisk*.12+(100-p.motivation)*.14+p.dropoutRisk*.24)),investmentToDate:p.personalInvestment}}
export function snapshotFootballSchool(w:World){const s=states.get(w);return s?JSON.parse(JSON.stringify(s)) as FootballSchoolState:undefined}
export function restoreFootballSchool(w:World,x?:FootballSchoolState){if(!x){states.delete(w);return}const s=JSON.parse(JSON.stringify(x)) as FootballSchoolState;s.teamName??=s.name;s.homeBaseType='municipal-sports-centers';s.namingRightsEligible??=s.managerTotalInvestment>=30000;s.materials??={uniformSets:1,balls:8,cones:20,bibs:20,firstAidKits:1,equipmentQuality:38};s.sponsors??=[];s.communityEvents??=[];s.clubInterests??=[];s.municipalRelationship??=60;for(const p of s.prospects){p.playerId??=p.id.startsWith('fsp-')?p.id.slice(4):p.id;p.schoolPerformance??=60;p.discipline??=60;p.nutritionSecurity??=55;p.transportAccess??=55;p.dropoutRisk??=0;p.scholarshipSupport??=0;recomputeDropoutRisk(p)}states.set(w,s)}
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
