import type { World } from './engine';
import { footballDataSnapshot, registerHistoricalMatch, registerTitle, resolveFootballEntity, type HistoricalMatchRecord, type TitleRecord } from './world-football-data-v1';

export type HistoricalChampionInput={competitionId:string;season:string;team:string;teamKind?:'club'|'national';date?:string;sourceId:string;sourcePath?:string;confidence?:number};
export type HistoricalFinalInput={id:string;competitionId:string;season:string;date:string;homeTeam:string;awayTeam:string;homeGoals:number;awayGoals:number;venueId?:string;stage?:string;sourceId:string;sourcePath?:string;confidence?:number};
export type HistoryImportReport={titles:number;matches:number;unresolved:string[];duplicates:number};
const provenance=(sourceId:string,sourcePath:string|undefined,confidence=90)=>[{sourceId,sourcePath,historical:true,confidence}];
const unique=(xs:string[])=>[...new Set(xs)];
function one(world:World,name:string){const ids=resolveFootballEntity(world,name);return ids.length===1?ids[0]:undefined}
export function importHistoricalChampions(world:World,rows:HistoricalChampionInput[]):HistoryImportReport{let titles=0,duplicates=0;const unresolved:string[]=[];for(const r of rows){const teamId=one(world,r.team);if(!teamId){unresolved.push(r.team);continue}const id=`title-${r.competitionId}-${r.season}-${teamId}`;const before=footballDataSnapshot(world).titles.length;registerTitle(world,{id,teamId,teamKind:r.teamKind??'club',competitionId:r.competitionId,season:r.season,date:r.date,source:'historical',provenance:provenance(r.sourceId,r.sourcePath,r.confidence)});const after=footballDataSnapshot(world).titles.length;if(after>before)titles++;else duplicates++}return{titles,matches:0,unresolved:unique(unresolved),duplicates}}
export function importHistoricalFinals(world:World,rows:HistoricalFinalInput[]):HistoryImportReport{let matches=0,duplicates=0;const unresolved:string[]=[];for(const r of rows){const homeTeamId=one(world,r.homeTeam),awayTeamId=one(world,r.awayTeam);if(!homeTeamId||!awayTeamId){if(!homeTeamId)unresolved.push(r.homeTeam);if(!awayTeamId)unresolved.push(r.awayTeam);continue}const rec:HistoricalMatchRecord={id:r.id,date:r.date,competitionId:r.competitionId,season:r.season,homeTeamId,awayTeamId,homeGoals:r.homeGoals,awayGoals:r.awayGoals,venueId:r.venueId,stage:r.stage??'final',source:'historical',provenance:provenance(r.sourceId,r.sourcePath,r.confidence)};const before=footballDataSnapshot(world).matches.length;registerHistoricalMatch(world,rec);const after=footballDataSnapshot(world).matches.length;if(after>before)matches++;else duplicates++}return{titles:0,matches,unresolved:unique(unresolved),duplicates}}
export function historicalHonours(world:World,teamId:string){const x=footballDataSnapshot(world);const titles=x.titles.filter(t=>t.teamId===teamId).sort((a,b)=>a.season.localeCompare(b.season));const byCompetition=new Map<string,TitleRecord[]>();for(const t of titles){const list=byCompetition.get(t.competitionId)??[];list.push(t);byCompetition.set(t.competitionId,list)}return{teamId,total:titles.length,titles,byCompetition:[...byCompetition].map(([competitionId,items])=>({competitionId,count:items.length,seasons:items.map(x=>x.season)})).sort((a,b)=>b.count-a.count)}}
export function competitionChampions(world:World,competitionId:string){return footballDataSnapshot(world).titles.filter(t=>t.competitionId===competitionId).sort((a,b)=>a.season.localeCompare(b.season))}
