import type { World } from './engine';
import { footballDataSnapshot } from './world-football-data-v1';

export type HonourSummary={teamId:string;totalTitles:number;continentalTitles:number;internationalTitles:number;domesticTitles:number;byCompetition:{competitionId:string;count:number;seasons:string[]}[];finals:number;runnerUpFinishes:number;historicalPrestige:number};
const weights:Record<string,number>={'comp-fifa-world-cup':100,'comp-fifa-club-world-cup':90,'comp-uefa-cl':88,'comp-conmebol-libertadores':88,'comp-uefa-el':60,'comp-conmebol-sudamericana':60,'comp-uefa-euro':82,'comp-conmebol-copa-america':82,'comp-uefa-conf':45};
export function teamHonours(world:World,teamId:string):HonourSummary{const s=footballDataSnapshot(world),titles=s.titles.filter(t=>t.teamId===teamId),by=new Map<string,string[]>();for(const t of titles){const x=by.get(t.competitionId)??[];x.push(t.season);by.set(t.competitionId,x)}const finals=s.matches.filter(m=>/^final$/i.test(m.stage??'')&&(m.homeTeamId===teamId||m.awayTeamId===teamId)),wonFinals=new Set(titles.map(t=>`${t.competitionId}:${t.season}`));const runnerUpFinishes=finals.filter(f=>!wonFinals.has(`${f.competitionId}:${f.season}`)).length;let continentalTitles=0,internationalTitles=0,domesticTitles=0,prestige=0;for(const t of titles){const c=s.competitions.find(x=>x.id===t.competitionId);if(c?.scope==='continental')continentalTitles++;else if(c?.scope==='international')internationalTitles++;else domesticTitles++;prestige+=weights[t.competitionId]??(c?.scope==='domestic'?20:35)}prestige+=Math.min(40,runnerUpFinishes*2);return{teamId,totalTitles:titles.length,continentalTitles,internationalTitles,domesticTitles,byCompetition:[...by].map(([competitionId,seasons])=>({competitionId,count:seasons.length,seasons:[...seasons].sort()})).sort((a,b)=>b.count-a.count),finals:finals.length,runnerUpFinishes,historicalPrestige:Math.round(prestige)}}
export function competitionHonoursTable(world:World,competitionId:string){const s=footballDataSnapshot(world),titles=s.titles.filter(t=>t.competitionId===competitionId),by=new Map<string,string[]>();for(const t of titles){const x=by.get(t.teamId)??[];x.push(t.season);by.set(t.teamId,x)}return[...by].map(([teamId,seasons])=>({teamId,titles:seasons.length,seasons:[...seasons].sort(),lastTitle:[...seasons].sort().at(-1)})).sort((a,b)=>b.titles-a.titles||(b.lastTitle??'').localeCompare(a.lastTitle??''))}
export function historicalFinals(world:World,competitionId?:string){return footballDataSnapshot(world).matches.filter(m=>/^final$/i.test(m.stage??'')&&(!competitionId||m.competitionId===competitionId)).sort((a,b)=>a.date.localeCompare(b.date))}
export function allTimePrestigeTable(world:World,scope?:'club'|'national'){const s=footballDataSnapshot(world),ids=new Set<string>();for(const t of s.titles)if(!scope||t.teamKind===scope)ids.add(t.teamId);return[...ids].map(id=>teamHonours(world,id)).sort((a,b)=>b.historicalPrestige-a.historicalPrestige||b.totalTitles-a.totalTitles)}
