import type { World } from './engine';
import { userManager } from './manager-character';
import { dailyCalendar } from './daily-simulation';
import { footballSchool, createFootballSchool, giftSchoolMaterials, rentBetterSchoolField, seekLocalSchoolSponsor, setSchoolProspectTraining, schoolVenueOptions, type SchoolProspect, type SchoolTrainingFocus } from './football-school-v1';
import { managerWallet } from './manager-personal-finance-v1';
import { deterministicRandom, queueWorldEvent } from './world-core-v2';
import { potentialTierFor } from './player-potential-tier-v1';
import { clubTechnicalStaff } from './technical-staff';

const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
const assignedScout=new WeakMap<World,string>();
let selectedProspect='';
const focusLabels:Record<SchoolTrainingFocus,string>={fundamentals:'Fundamentos',technique:'Técnica',passing:'Passe',finishing:'Finalização',defending:'Defesa',goalkeeping:'Goleiro','physical-literacy':'Coordenação física','decision-making':'Decisão','weak-foot':'Pé fraco','position-discovery':'Descobrir posição',confidence:'Confiança'};
const spots=[[8,50],[23,82],[20,62],[20,38],[23,18],[43,65],[43,35],[68,82],[65,50],[68,18],[88,50]];
function world(){return window.__touchlineWorld as World|undefined}
function managedClubId(w:World){return userManager(w)?.currentClubId??w.clubs[0]?.id??''}
function normalizeLegendRarity(w:World){const s=footballSchool(w);if(!s)return;for(const p of s.prospects){if(p.truePotential<96)continue;const allowed=deterministicRandom(w,'football-school',`legend-gate:${p.playerId}`)<.02;if(allowed)continue;p.truePotential=Math.min(95,p.truePotential);p.realisationCeiling=Math.min(p.realisationCeiling,p.truePotential);p.potentialView=potentialTierFor({potential:p.truePotential,position:p.position,certainty:p.potentialCertainty,age:p.age});if(!p.notes.includes('Potencial geracional reavaliado com alta incerteza.'))p.notes.push('Potencial geracional reavaliado com alta incerteza.')}}
function prospectScore(p:SchoolProspect){return Math.round(p.currentAbility*.36+p.motivation*.17+p.discipline*.13+p.schoolAttendance*.12+p.confidence*.12+p.coachBond*.1)}
function activeProspects(w:World){normalizeLegendRarity(w);return (footballSchool(w)?.prospects??[]).filter(p=>p.status==='active'||p.status==='academy-eligible').sort((a,b)=>prospectScore(b)-prospectScore(a))}
function potentialTone(p:SchoolProspect){const t=p.potentialView.tier;return t==='possible-legend'?'legend':t==='possible-elite'?'elite':t==='possible-star'?'star':t==='high-level'?'high':'normal'}
function shortName(n:string){const x=n.trim().split(/\s+/);return x.length>1?x[x.length-1]:n}
function metric(label:string,value:string,sub=''){return `<article><span>${label}</span><b>${value}</b>${sub?`<small>${sub}</small>`:''}</article>`}
function scoutOptions(w:World){const cid=managedClubId(w);return clubTechnicalStaff(w,cid).filter(s=>['chiefScout','recruitmentAnalyst','youthDevelopmentCoach','youthCoach'].includes(s.role)).sort((a,b)=>b.skills.recruitment-a.skills.recruitment)}
function fieldPlayer(p:SchoolProspect,i:number){const [x,y]=spots[i]??[50,50];return `<button class="fs2-field-player tone-${potentialTone(p)}" data-fs-prospect="${esc(p.id)}" style="left:${x}%;top:${y}%"><span>${i+1}</span><b>${esc(shortName(p.name))}</b><small>${p.position} · ${prospectScore(p)}</small></button>`}
function prospectModal(w:World,p:SchoolProspect){const scoutId=assignedScout.get(w),scout=scoutOptions(w).find(x=>x.id===scoutId),attrs=Object.entries(p.attributes).sort((a,b)=>b[1]-a[1]).slice(0,6);return `<div class="fs2-modal" data-fs-close><section onclick="event.stopPropagation()"><button class="fs2-close" data-fs-close>×</button><header><div class="fs2-avatar">${esc(p.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div><span>PROSPECTO · ${p.countryId}</span><h2>${esc(p.name)}</h2><p>${p.age} anos · ${p.position}${p.secondaryPositions.length?` · também ${p.secondaryPositions.join('/')}`:''} · ${p.heightCm} cm · pé ${p.preferredFoot==='left'?'esquerdo':'direito'}</p></div><em class="tone-${potentialTone(p)}">${esc(p.potentialView.shortLabel)}</em></header><div class="fs2-profile-grid"><article><span>VISÃO DO PROFESSOR</span><b>${esc(p.potentialView.label)}</b><small>Confiança da avaliação: ${Math.round(p.potentialCertainty)}%. Nesta idade a margem de erro é alta e potencial não garante carreira.</small></article><article><span>OLHEIRO DESIGNADO</span><b>${esc(scout?.name??'Nenhum')}</b><small>${scout?`Recrutamento ${scout.skills.recruitment} · análise ${scout.skills.analysis}`:'Escolha um profissional do clube para acompanhar a evolução.'}</small></article></div><div class="fs2-bars">${[['Motivação',p.motivation],['Confiança',p.confidence],['Disciplina',p.discipline],['Escola',p.schoolAttendance],['Família',p.familySupport],['Vínculo',p.managerBond]].map(([l,v])=>`<label><span>${l}</span><i><b style="width:${v}%"></b></i><strong>${v}</strong></label>`).join('')}</div><div class="fs2-attrs">${attrs.map(([k,v])=>`<div><span>${esc(k)}</span><b>${v}</b></div>`).join('')}</div><footer><label>FOCO INDIVIDUAL<select data-fs-focus="${esc(p.id)}">${Object.entries(focusLabels).map(([k,l])=>`<option value="${k}" ${p.trainingFocus===k?'selected':''}>${l}</option>`).join('')}</select></label><div><span>Risco de abandono <b>${Math.round(p.dropoutRisk)}%</b></span><span>Realização atual do teto <b>${Math.round(p.realisationCeiling)}</b></span></div></footer></section></div>`}
function render(){const w=world(),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!host)return;const m=userManager(w);if(!m)return;let s=footballSchool(w);if(!s){host.innerHTML=`<section class="fs2"><header class="fs2-hero"><div class="fs2-badge">⚽</div><div><span>CARREIRA · COMUNIDADE</span><h1>Escolinha de Futebol</h1><p>Projeto municipal opcional, separado do clube profissional e focado em desenvolvimento humano.</p></div></header><div class="fs2-empty"><h2>Nenhum projeto ativo</h2><p>Você pode apoiar uma escolinha municipal sem transformar os jovens em propriedade do seu clube.</p><button data-fs-create>CRIAR PROJETO MUNICIPAL</button></div></section>`;host.querySelector<HTMLButtonElement>('[data-fs-create]')!.onclick=()=>{createFootballSchool(w);render()};return}
 normalizeLegendRarity(w);s=footballSchool(w)!;const date=dailyCalendar(w).date,wallet=managerWallet(w,m.id),active=activeProspects(w),venue=s.venueRental?schoolVenueOptions().find(v=>v.id===s.venueRental?.optionId):schoolVenueOptions()[0],scouts=scoutOptions(w),currentScout=assignedScout.get(w),sponsorIncome=s.sponsors.filter(x=>x.active).reduce((a,x)=>a+x.monthlyAmount,0),lineup=active.slice(0,11),selected=active.find(p=>p.id===selectedProspect);
 host.innerHTML=`<section class="fs2"><header class="fs2-hero"><div class="fs2-badge">⚽</div><div><span>CARREIRA · ESCOLINHA</span><h1>${esc(s.teamName)}</h1><p>${esc(s.name)} · ${esc(s.city)} · projeto municipal independente</p></div><div class="fs2-hero-actions">${s.managerTotalInvestment>0?'<button data-fs-rename>RENOMEAR PROJETO</button>':''}<strong>NÍVEL ${s.facilityLevel}</strong></div></header><div class="fs2-metrics">${metric('CARTEIRA PESSOAL',money(wallet.balance))}${metric('JOVENS ATIVOS',String(active.length))}${metric('REPUTAÇÃO',String(Math.round(s.reputation)))}${metric('CONFIANÇA',String(Math.round(s.communityTrust)))}${metric('PATROCÍNIO/MÊS',money(sponsorIncome))}${metric('MATERIAL',String(Math.round(s.materials.equipmentQuality)))}</div><div class="fs2-layout"><section class="fs2-field-card"><header><div><span>CAMPO DE TREINO</span><b>${esc(venue?.name??'Campo comunitário')}</b></div><small>${esc(venue?.description??'')}</small></header><div class="fs2-dirt-pitch"><i class="half"></i><i class="circle"></i><i class="box left"></i><i class="box right"></i><i class="goal left"></i><i class="goal right"></i>${lineup.map(fieldPlayer).join('')}</div><footer><span>Grupo visual sugerido pelo professor · clique em um jovem para abrir o dossiê</span><button data-fs-field>MELHORAR CAMPO · ${money(1800)}</button></footer></section><aside class="fs2-side"><section><span>PROFESSOR RESPONSÁVEL</span><h3>${esc(s.teacher.name)}</h3><p>Formação ${s.teacher.coaching} · jovens ${s.teacher.youthDevelopment} · identificação ${s.teacher.talentIdentification}</p></section><section><span>OLHEIRO DO CLUBE</span><select data-fs-scout><option value="">Sem olheiro designado</option>${scouts.map(x=>`<option value="${esc(x.id)}" ${currentScout===x.id?'selected':''}>${esc(x.name)} · rec ${x.skills.recruitment}</option>`).join('')}</select><p>O olheiro não revela potencial verdadeiro. Ele aumenta contexto e qualidade da avaliação.</p></section><section class="fs2-actions"><button data-fs-kit>PRESENTEAR KIT · ${money(3200)}</button><button data-fs-sponsor>BUSCAR PATROCÍNIO LOCAL</button></section></aside></div><section class="fs2-prospects"><header><div><span>PAINEL DE PROSPECÇÃO</span><h2>Jovens do projeto</h2></div><small>“Lendário” é uma hipótese raríssima: no máximo ~2% passam pelo filtro geracional e ainda podem não realizar o teto.</small></header><div class="fs2-prospect-grid">${active.map(p=>`<button data-fs-prospect="${esc(p.id)}"><i class="tone-${potentialTone(p)}"></i><div><b>${esc(p.name)}</b><small>${p.age} anos · ${p.position} · ${p.countryId}</small></div><strong>${esc(p.potentialView.shortLabel)}</strong><em>${Math.round(p.potentialCertainty)}%</em></button>`).join('')}</div></section>${selected?prospectModal(w,selected):''}</section>`;
 bind(w);
}
function bind(w:World){const host=document.querySelector<HTMLElement>('.game-stage main.view');if(!host)return;host.querySelectorAll<HTMLButtonElement>('[data-fs-prospect]').forEach(b=>b.onclick=()=>{selectedProspect=b.dataset.fsProspect??'';render()});host.querySelectorAll<HTMLElement>('[data-fs-close]').forEach(b=>b.addEventListener('click',()=>{selectedProspect='';render()}));host.querySelector<HTMLSelectElement>('[data-fs-focus]')?.addEventListener('change',e=>{const el=e.target as HTMLSelectElement;setSchoolProspectTraining(w,el.dataset.fsFocus!,el.value as SchoolTrainingFocus);render()});host.querySelector<HTMLSelectElement>('[data-fs-scout]')?.addEventListener('change',e=>{assignedScout.set(w,(e.target as HTMLSelectElement).value);render()});host.querySelector<HTMLButtonElement>('[data-fs-field]')?.addEventListener('click',()=>{rentBetterSchoolField(w,dailyCalendar(w).date,'municipal-premium',1);render()});host.querySelector<HTMLButtonElement>('[data-fs-kit]')?.addEventListener('click',()=>{giftSchoolMaterials(w,dailyCalendar(w).date,'complete-kit',1);render()});host.querySelector<HTMLButtonElement>('[data-fs-sponsor]')?.addEventListener('click',()=>{seekLocalSchoolSponsor(w,dailyCalendar(w).date);render()});host.querySelector<HTMLButtonElement>('[data-fs-rename]')?.addEventListener('click',()=>{const s=footballSchool(w);if(!s||s.managerTotalInvestment<=0)return;const name=window.prompt('Novo nome da escolinha',s.teamName)?.trim();if(!name)return;s.teamName=name;s.name=name;queueWorldEvent(w,{date:dailyCalendar(w).date,type:'FootballSchoolRenamed',scope:'person',entityIds:[s.managerId,s.id],importance:1,payload:{name}});render()})}
document.addEventListener('touchline:view-rendered',e=>{if((e as CustomEvent).detail?.view==='school')queueMicrotask(render)});
window.addEventListener('touchline:save-loaded',()=>{const b=document.querySelector<HTMLElement>('.game-sidebar [data-view="school"].active');if(b)queueMicrotask(render)});
