import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { clubMediaNarrativeHooks } from './football-media-narrative-v1';
import { sportNewsIssue, type SportNewsArticle } from './sport-news-weekly-v1';
import { managerByClub } from './manager-character';
import { managerProfile } from './manager-interactions';
import { clubGovernance } from './club-governance';
import { supporterCulture } from './club-supporter-culture-v1';

export type PressAnswerTone='protective'|'calm'|'accountable'|'defiant'|'ambitious'|'dismissive';
export type PressQuestion={id:string;topic:'history'|'tactics'|'result'|'record'|'transfer'|'injury'|'manager'|'supporters'|'competition';text:string;context:string;pressure:number;articleId?:string;playerId?:string;opponentId?:string;options:PressAnswerOption[]};
export type PressAnswerOption={id:string;tone:PressAnswerTone;label:string;managerStress:number;managerReputation:number;boardConfidence:number;fanApproval:number;mediaPressure:number};
export type PressConference={id:string;date:string;clubId:string;managerId:string;issueId?:string;questions:PressQuestion[];status:'pending'|'resolved';answers:{questionId:string;optionId:string}[];publicReaction:number};
export type PressRoomSnapshot={conferences:PressConference[]};
const states=new WeakMap<World,PressConference[]>(),clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function state(w:World){let s=states.get(w);if(!s){s=[];states.set(w,s)}return s}
function options(pressure:number):PressAnswerOption[]{return[
{id:'protect',tone:'protective',label:'Proteger elenco e assumir a pressão',managerStress:2,managerReputation:1,boardConfidence:1,fanApproval:2,mediaPressure:-2},
{id:'account',tone:'accountable',label:'Assumir responsabilidade e prometer ajustes',managerStress:3,managerReputation:2,boardConfidence:2,fanApproval:2,mediaPressure:-1},
{id:'calm',tone:'calm',label:'Responder com equilíbrio e foco no próximo jogo',managerStress:-1,managerReputation:1,boardConfidence:1,fanApproval:0,mediaPressure:-2},
{id:'ambition',tone:'ambitious',label:'Elevar a meta e cobrar reação imediata',managerStress:2,managerReputation:pressure>65?2:0,boardConfidence:1,fanApproval:pressure>55?2:0,mediaPressure:2},
{id:'defy',tone:'defiant',label:'Contestar a leitura da imprensa',managerStress:1,managerReputation:-1,boardConfidence:0,fanApproval:0,mediaPressure:4},
{id:'dismiss',tone:'dismissive',label:'Encerrar o assunto sem alimentar a pauta',managerStress:-1,managerReputation:0,boardConfidence:0,fanApproval:-1,mediaPressure:pressure>70?3:-1}
]}
function topicFor(a:SportNewsArticle):PressQuestion['topic']{if(a.category==='tactics')return'tactics';if(a.category==='record')return'record';if(a.category==='transfer')return'transfer';if(a.category==='injury')return'injury';if(a.category==='manager')return'manager';if(a.category==='supporters')return'supporters';if(a.category==='competition')return'competition';if(a.category==='history')return'history';return'result'}
function articleQuestion(a:SportNewsArticle,clubId:string):PressQuestion{const text=a.category==='tactics'?a.body.match(/“([^”]+)”/)?.[1]??'Você considera que a abordagem tática precisa mudar?':a.category==='transfer'?'A exposição pública desta negociação muda a postura do clube?':a.category==='record'?'A proximidade de um recorde histórico muda suas decisões de escalação?':a.category==='injury'?'Como a ausência do jogador altera o planejamento da equipe?':a.category==='manager'?'Como você reage ao aumento de atenção sobre o seu trabalho?':a.category==='competition'?'A mudança na classificação altera a meta imediata da equipe?':a.category==='history'?'O peso da história está aumentando a cobrança sobre o trabalho atual?':'Qual é a principal leitura do clube sobre esta repercussão?';return{id:`pq-${a.id}-${clubId}`,topic:topicFor(a),text,context:`${a.headline}. ${a.deck}`,pressure:clamp(a.importance),articleId:a.id,playerId:a.playerIds[0],options:options(a.importance)}}
export function createPressConferenceFromSportNews(w:World,input:{clubId:string;issueId:string;date?:string}){const issue=sportNewsIssue(w,input.issueId),manager=managerByClub(w,input.clubId);if(!issue||!manager)return;const id=`press-${issue.id}-${input.clubId}`,existing=state(w).find(x=>x.id===id);if(existing)return existing;const related=issue.pages.flatMap(p=>p.articles).filter(a=>a.clubIds.includes(input.clubId)).sort((a,b)=>b.importance-a.importance),questions=related.slice(0,4).map(a=>articleQuestion(a,input.clubId));for(const h of clubMediaNarrativeHooks(w,input.clubId).filter(h=>h.question).slice(0,Math.max(0,4-questions.length)))questions.push({id:`pq-hook-${h.id}`,topic:h.type==='rivalry'?'history':h.type==='tactics'?'tactics':h.type==='record'?'record':h.type==='manager'?'manager':'history',text:h.question!,context:h.context,pressure:h.weight,playerId:h.playerId,opponentId:h.opponentId,options:options(h.weight)});if(!questions.length)return;const conference:PressConference={id,date:input.date??issue.date,clubId:input.clubId,managerId:manager.id,issueId:issue.id,questions,status:'pending',answers:[],publicReaction:50};state(w).push(conference);emitWorldEvent(w,{type:'MediaStoryPublished',date:conference.date,clubIds:[conference.clubId],actorIds:[conference.managerId],importance:2,summary:'A imprensa prepara perguntas sobre os principais assuntos da semana.',payload:{pressConferenceId:id,issueId:issue.id,questions:questions.length}});return conference}
export function answerPressQuestion(w:World,conferenceId:string,questionId:string,optionId:string){const c=state(w).find(x=>x.id===conferenceId);if(!c||c.status==='resolved')return false;const q=c.questions.find(x=>x.id===questionId),o=q?.options.find(x=>x.id===optionId);if(!q||!o||c.answers.some(x=>x.questionId===questionId))return false;c.answers.push({questionId,optionId});const m=managerProfile(w,c.clubId),g=clubGovernance(w,c.clubId),fans=supporterCulture(w,c.clubId);if(m){m.stress=clamp(m.stress+o.managerStress);m.reputation=clamp(m.reputation+o.managerReputation)}if(g){g.managerConfidence=clamp(g.managerConfidence+o.boardConfidence);g.fanApproval=clamp(g.fanApproval+o.fanApproval);g.mediaPressure=clamp(g.mediaPressure+o.mediaPressure)}fans.patience=clamp(fans.patience+o.fanApproval*.25);c.publicReaction=clamp(c.publicReaction+o.managerReputation*2+o.fanApproval-o.mediaPressure*.5);if(c.answers.length>=c.questions.length)c.status='resolved';emitWorldEvent(w,{type:'MediaStoryPublished',date:c.date,clubIds:[c.clubId],actorIds:[c.managerId],playerIds:q.playerId?[q.playerId]:[],importance:q.pressure>=75?3:2,summary:`Coletiva: ${o.label}.`,payload:{pressConferenceId:c.id,questionId:q.id,answerTone:o.tone,publicReaction:c.publicReaction}});return true}
export function resolvePressConferenceAI(w:World,conferenceId:string){const c=state(w).find(x=>x.id===conferenceId);if(!c)return;const m=managerProfile(w,c.clubId);for(const q of c.questions.filter(q=>!c.answers.some(a=>a.questionId===q.id))){const ranked=[...q.options].sort((a,b)=>{const sa=(m?.mediaSkill??50)*a.managerReputation+(m?.diplomacy??50)*(-a.mediaPressure)+(m?.assertiveness??50)*(a.tone==='ambitious'||a.tone==='defiant'?1:0)+(m?.publicProtection??50)*(a.tone==='protective'?1:0);const sb=(m?.mediaSkill??50)*b.managerReputation+(m?.diplomacy??50)*(-b.mediaPressure)+(m?.assertiveness??50)*(b.tone==='ambitious'||b.tone==='defiant'?1:0)+(m?.publicProtection??50)*(b.tone==='protective'?1:0);return sb-sa});answerPressQuestion(w,c.id,q.id,ranked[0]?.id??'calm')}return c}
export function pressConferences(w:World,clubId?:string){return state(w).filter(x=>!clubId||x.clubId===clubId)}
export function snapshotPressRoom(w:World):PressRoomSnapshot{return{conferences:JSON.parse(JSON.stringify(state(w)))}}
export function restorePressRoom(w:World,x?:PressRoomSnapshot){states.set(w,JSON.parse(JSON.stringify(x?.conferences??[])))}
