import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { clubMediaNarrativeHooks } from './football-media-narrative-v1';
import { sportNewsIssue, type SportNewsArticle } from './sport-news-weekly-v1';
import { managerByClub } from './manager-character';
import { managerProfile } from './manager-interactions';
import { clubGovernance } from './club-governance';
import { supporterCulture } from './club-supporter-culture-v1';
import { generateDialogue, type DialogueTone, type DialogueTopic } from './human-dialogue-bank-v1';
import { humanVoice, speakAs } from './human-voice-state-v1';
import { managerBehavior,recordManagerStatement,statementRecall,snapshotManagerSocialMemory,restoreManagerSocialMemory,type ManagerBehaviorTag,type SocialMemorySnapshot } from './manager-social-memory-v1';

export type PressAnswerTone='protective'|'calm'|'accountable'|'defiant'|'ambitious'|'dismissive';
export type PressQuestion={id:string;topic:'history'|'tactics'|'result'|'record'|'transfer'|'injury'|'manager'|'supporters'|'competition';text:string;context:string;pressure:number;articleId?:string;playerId?:string;opponentId?:string;reporterId?:string;reporterName?:string;outlet?:string;followUpOf?:string;depth?:number;options:PressAnswerOption[]};
export type PressAnswerOption={id:string;tone:PressAnswerTone;label:string;managerStress:number;managerReputation:number;boardConfidence:number;fanApproval:number;mediaPressure:number};
export type PressAnswer={questionId:string;optionId:string;text?:string;decisionLabel?:string;reporterReaction?:string};
export type PressConference={id:string;date:string;clubId:string;managerId:string;issueId?:string;questions:PressQuestion[];status:'pending'|'resolved';answers:PressAnswer[];publicReaction:number};
export type PressRoomSnapshot={conferences:PressConference[];socialMemory?:SocialMemorySnapshot};
const states=new WeakMap<World,PressConference[]>(),clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const reporters=[['Marina Costa','Diário Esportivo'],['Rafael Prado','Jornal do Futebol'],['Beatriz Nunes','Rádio Arquibancada'],['Caio Mendes','Mercado Agora'],['Luana Ribeiro','Bastidores da Bola'],['Felipe Azevedo','Futebol em Foco'],['Renata Lima','TV Esporte Nacional'],['Eduardo Salles','Central da Bola'],['Patrícia Moura','Rede Futebol'],['Bruno Tavares','Portal da Torcida']] as const;
function state(w:World){let s=states.get(w);if(!s){s=[];states.set(w,s)}return s}
function h(s:string){let x=2166136261;for(const c of s){x^=c.charCodeAt(0);x=Math.imul(x,16777619)}return x>>>0}
function reporter(seed:string){const r=reporters[h(seed)%reporters.length];return{id:`reporter-${h(r[0]).toString(36)}`,name:r[0],outlet:r[1]}}
function options(pressure:number):PressAnswerOption[]{return[
{id:'protect',tone:'protective',label:'Proteger elenco e assumir a pressão',managerStress:2,managerReputation:1,boardConfidence:1,fanApproval:2,mediaPressure:-2},
{id:'account',tone:'accountable',label:'Assumir responsabilidade e prometer ajustes',managerStress:3,managerReputation:2,boardConfidence:2,fanApproval:2,mediaPressure:-1},
{id:'calm',tone:'calm',label:'Responder com equilíbrio e foco no próximo jogo',managerStress:-1,managerReputation:1,boardConfidence:1,fanApproval:0,mediaPressure:-2},
{id:'ambition',tone:'ambitious',label:'Elevar a meta e cobrar reação imediata',managerStress:2,managerReputation:pressure>65?2:0,boardConfidence:1,fanApproval:pressure>55?2:0,mediaPressure:2},
{id:'defy',tone:'defiant',label:'Contestar a leitura da imprensa',managerStress:1,managerReputation:-1,boardConfidence:0,fanApproval:0,mediaPressure:4},
{id:'dismiss',tone:'dismissive',label:'Encerrar o assunto sem alimentar a pauta',managerStress:-1,managerReputation:0,boardConfidence:0,fanApproval:-1,mediaPressure:pressure>70?3:-1}
]}
function topicFor(a:SportNewsArticle):PressQuestion['topic']{if(a.category==='tactics')return'tactics';if(a.category==='record')return'record';if(a.category==='transfer')return'transfer';if(a.category==='injury')return'injury';if(a.category==='manager')return'manager';if(a.category==='supporters')return'supporters';if(a.category==='competition')return'competition';if(a.category==='history')return'history';return'result'}
function dialogueTopic(t:PressQuestion['topic']):DialogueTopic{if(t==='record'||t==='history'||t==='competition')return'pressure';if(t==='manager')return'future';if(t==='supporters')return'pressure';return t}
function quotedQuestion(a:SportNewsArticle){return a.body.match(/Pergunta de coletiva:\s*[“"]([^”"]+)[”"]/i)?.[1]??a.body.match(/“([^”]+\?)”/)?.[1]}
function questionPart(line:string){const i=line.indexOf(' — ');return(i>=0?line.slice(0,i):line).replace(/^.*?:\s*[“"]?/,'').replace(/[”"]$/,'').trim()}
function answerPart(line:string){const i=line.indexOf(' — ');return(i>=0?line.slice(i+3):line).replace(/^[“"]|[”"]$/g,'').trim()}
function decorateQuestion(w:World,q:PressQuestion,seed:string,preferred?:string,managerId?:string){const r=reporter(preferred??seed);const spoken=speakAs(w,r.id,'journalist',{audience:'press',topic:dialogueTopic(q.topic),pressure:q.pressure,player:q.playerId?w.clubs.flatMap(c=>c.players).find(p=>p.id===q.playerId)?.name:undefined,opponent:q.opponentId?w.clubs.find(c=>c.id===q.opponentId)?.name:undefined,seed:`press-question:${seed}`});q.reporterId=r.id;q.reporterName=r.name;q.outlet=r.outlet;if(!q.text||q.text.startsWith('Qual é a principal leitura'))q.text=questionPart(spoken.text);if(managerId){const recalled=statementRecall(w,managerId,dialogueTopic(q.topic),r.id);if(recalled){q.context=`${q.context} ${r.name} recupera uma fala anterior de ${recalled.date}: “${recalled.text}”`;q.pressure=clamp(q.pressure+Math.min(12,recalled.importance*2))}}q.text=`${r.name} · ${r.outlet}: ${q.text}`;return q}
function articleQuestion(w:World,a:SportNewsArticle,clubId:string,managerId:string):PressQuestion{const memoryQuestion=quotedQuestion(a),text=memoryQuestion??(a.category==='tactics'?a.body.match(/“([^”]+)”/)?.[1]??'Você considera que a abordagem tática precisa mudar?':a.category==='transfer'?'A exposição pública desta negociação muda a postura do clube?':a.category==='record'?'A proximidade de um recorde histórico muda suas decisões de escalação?':a.category==='injury'?'Como a ausência do jogador altera o planejamento da equipe?':a.category==='manager'?'Como você reage ao aumento de atenção sobre o seu trabalho?':a.category==='competition'?'A mudança na classificação altera a meta imediata da equipe?':a.category==='history'?'O peso da história está aumentando a cobrança sobre o trabalho atual?':'Qual é a principal leitura do clube sobre esta repercussão?');return decorateQuestion(w,{id:`pq-${a.id}-${clubId}`,topic:topicFor(a),text,context:`${a.headline}. ${a.deck}${memoryQuestion?' A pergunta recupera diretamente um episódio arquivado pelo Sport News.':''}`,pressure:clamp(a.importance),articleId:a.id,playerId:a.playerIds[0],depth:0,options:options(a.importance)},`${a.id}:${clubId}`,undefined,managerId)}
function answerTone(t:PressAnswerTone):DialogueTone{return t==='protective'?'supportive':t==='accountable'?'firm':t==='defiant'?'defensive':t==='ambitious'?'ambitious':t==='dismissive'?'cautious':'calm'}
function behaviorTags(t:PressAnswerTone):ManagerBehaviorTag[]{if(t==='protective')return['protective','supportive'];if(t==='accountable')return['accountable','transparent'];if(t==='defiant')return['confrontational'];if(t==='ambitious')return['ambitious'];if(t==='dismissive')return['evasive'];return['diplomatic','consistent']}
function managerAnswer(w:World,c:PressConference,q:PressQuestion,o:PressAnswerOption){const club=w.clubs.find(x=>x.id===c.clubId),player=q.playerId?w.clubs.flatMap(x=>x.players).find(p=>p.id===q.playerId):undefined,opponent=q.opponentId?w.clubs.find(x=>x.id===q.opponentId):undefined;return answerPart(generateDialogue({audience:'press',topic:dialogueTopic(q.topic),tone:answerTone(o.tone),club:club?.name,player:player?.name,opponent:opponent?.name,pressure:q.pressure,positive:['protective','calm','accountable','ambitious'].includes(o.tone),seed:`manager-answer:${c.managerId}:${q.id}:${o.id}`}).text)}
function maybeFollowUp(w:World,c:PressConference,q:PressQuestion,o:PressAnswerOption){if((q.depth??0)>=1||c.questions.length>=8||!q.reporterId)return;const voice=humanVoice(w,q.reporterId,'journalist'),profile=managerBehavior(w,c.managerId),evasive=o.tone==='dismissive'||o.tone==='defiant',behaviorPressure=profile.evasive*.12+profile.confrontational*.08,should=(evasive&&q.pressure>=45)||(voice.insistence>=78&&q.pressure>=65)||(behaviorPressure>=13&&q.pressure>=55);if(!should)return;const previous=statementRecall(w,c.managerId,dialogueTopic(q.topic),q.reporterId),raw=speakAs(w,q.reporterId,'journalist',{audience:'press',topic:dialogueTopic(q.topic),tone:evasive?'firm':'calm',pressure:clamp(q.pressure+10),player:q.playerId?w.clubs.flatMap(x=>x.players).find(p=>p.id===q.playerId)?.name:undefined,opponent:q.opponentId?w.clubs.find(x=>x.id===q.opponentId)?.name:undefined,seed:`followup:${c.id}:${q.id}:${o.id}`});const memory=previous?` Você já havia dito em ${previous.date}: “${previous.text}”`:'',fq:PressQuestion={id:`${q.id}-fu`,topic:q.topic,text:`${q.reporterName} · ${q.outlet}: ${questionPart(raw.text)}`,context:`O repórter insiste após a resposta anterior.${memory} ${q.context}`,pressure:clamp(q.pressure+10),articleId:q.articleId,playerId:q.playerId,opponentId:q.opponentId,reporterId:q.reporterId,reporterName:q.reporterName,outlet:q.outlet,followUpOf:q.id,depth:(q.depth??0)+1,options:options(clamp(q.pressure+10))};c.questions.push(fq)}
export function createPressConferenceFromSportNews(w:World,input:{clubId:string;issueId:string;date?:string}){const issue=sportNewsIssue(w,input.issueId),manager=managerByClub(w,input.clubId);if(!issue||!manager)return;const id=`press-${issue.id}-${input.clubId}`,existing=state(w).find(x=>x.id===id);if(existing)return existing;const related=issue.pages.flatMap(p=>p.articles).filter(a=>a.clubIds.includes(input.clubId)).sort((a,b)=>b.importance-a.importance),questions=related.slice(0,4).map(a=>articleQuestion(w,a,input.clubId,manager.id));for(const x of clubMediaNarrativeHooks(w,input.clubId).filter(x=>x.question).slice(0,Math.max(0,4-questions.length))){const q:PressQuestion={id:`pq-hook-${x.id}`,topic:x.type==='rivalry'?'history':x.type==='tactics'?'tactics':x.type==='record'?'record':x.type==='manager'?'manager':'history',text:x.question!,context:x.context,pressure:x.weight,playerId:x.playerId,opponentId:x.opponentId,depth:0,options:options(x.weight)};questions.push(decorateQuestion(w,q,`${x.id}:${input.clubId}`,undefined,manager.id))}if(!questions.length)return;const conference:PressConference={id,date:input.date??issue.date,clubId:input.clubId,managerId:manager.id,issueId:issue.id,questions,status:'pending',answers:[],publicReaction:50};state(w).push(conference);emitWorldEvent(w,{type:'MediaStoryPublished',date:conference.date,clubIds:[conference.clubId],actorIds:[conference.managerId],importance:2,summary:'A imprensa prepara perguntas sobre os principais assuntos da semana.',payload:{pressConferenceId:id,issueId:issue.id,questions:questions.length,reporters:[...new Set(questions.map(q=>q.reporterName).filter(Boolean))]}});return conference}
export function answerPressQuestion(w:World,conferenceId:string,questionId:string,optionId:string){const c=state(w).find(x=>x.id===conferenceId);if(!c||c.status==='resolved')return false;const q=c.questions.find(x=>x.id===questionId),o=q?.options.find(x=>x.id===optionId);if(!q||!o||c.answers.some(x=>x.questionId===questionId))return false;const decisionLabel=o.label,spoken=managerAnswer(w,c,q,o),answer:PressAnswer={questionId,optionId,text:spoken,decisionLabel};c.answers.push(answer);o.label=spoken;recordManagerStatement(w,{managerId:c.managerId,clubId:c.clubId,date:c.date,topic:dialogueTopic(q.topic),text:spoken,behavior:behaviorTags(o.tone),source:'pressConference',playerId:q.playerId,reporterId:q.reporterId,importance:q.pressure>=75?4:q.pressure>=55?3:2});const m=managerProfile(w,c.clubId),g=clubGovernance(w,c.clubId),fans=supporterCulture(w,c.clubId);if(m){m.stress=clamp(m.stress+o.managerStress);m.reputation=clamp(m.reputation+o.managerReputation)}if(g){g.managerConfidence=clamp(g.managerConfidence+o.boardConfidence);g.fanApproval=clamp(g.fanApproval+o.fanApproval);g.mediaPressure=clamp(g.mediaPressure+o.mediaPressure)}fans.patience=clamp(fans.patience+o.fanApproval*.25);c.publicReaction=clamp(c.publicReaction+o.managerReputation*2+o.fanApproval-o.mediaPressure*.5);maybeFollowUp(w,c,q,o);c.status=c.answers.length>=c.questions.length?'resolved':'pending';const behavior=managerBehavior(w,c.managerId);emitWorldEvent(w,{type:'MediaStoryPublished',date:c.date,clubIds:[c.clubId],actorIds:[c.managerId,q.reporterId??''].filter(Boolean),playerIds:q.playerId?[q.playerId]:[],importance:q.pressure>=75?3:2,summary:`Coletiva: ${decisionLabel}.`,payload:{pressConferenceId:c.id,questionId:q.id,answerTone:o.tone,answerText:spoken,decisionLabel,reporterId:q.reporterId,reporterName:q.reporterName,outlet:q.outlet,followUpAdded:c.questions.some(x=>x.followUpOf===q.id),publicReaction:c.publicReaction,managerBehavior:{protective:behavior.protective,transparent:behavior.transparent,accountable:behavior.accountable,confrontational:behavior.confrontational,evasive:behavior.evasive}}});return true}
export function resolvePressConferenceAI(w:World,conferenceId:string){const c=state(w).find(x=>x.id===conferenceId);if(!c)return;const m=managerProfile(w,c.clubId);let safety=0;while(c.status==='pending'&&safety++<12){const q=c.questions.find(q=>!c.answers.some(a=>a.questionId===q.id));if(!q)break;const ranked=[...q.options].sort((a,b)=>{const sa=(m?.mediaSkill??50)*a.managerReputation+(m?.diplomacy??50)*(-a.mediaPressure)+(m?.assertiveness??50)*(a.tone==='ambitious'||a.tone==='defiant'?1:0)+(m?.publicProtection??50)*(a.tone==='protective'?1:0),sb=(m?.mediaSkill??50)*b.managerReputation+(m?.diplomacy??50)*(-b.mediaPressure)+(m?.assertiveness??50)*(b.tone==='ambitious'||b.tone==='defiant'?1:0)+(m?.publicProtection??50)*(b.tone==='protective'?1:0);return sb-sa});answerPressQuestion(w,c.id,q.id,ranked[0]?.id??'calm')}return c}
export function pressConferences(w:World,clubId?:string){return state(w).filter(x=>!clubId||x.clubId===clubId)}
export function snapshotPressRoom(w:World):PressRoomSnapshot{return{conferences:JSON.parse(JSON.stringify(state(w))),socialMemory:snapshotManagerSocialMemory(w)}}
export function restorePressRoom(w:World,x?:PressRoomSnapshot){states.set(w,JSON.parse(JSON.stringify(x?.conferences??[])));restoreManagerSocialMemory(w,x?.socialMemory)}
