import './game-ui-v1.css';
import { createWorld, sortedStandings, selectStartingEleven, teamStrength, type World } from './engine';
import { createManagerCharacter, userManager, type ManagerCreationInput, type ManagerGender, type PlayingLevel, type CoachingLicence } from './manager-character';
import { advanceOneDay, dailyCalendar } from './daily-simulation';
import { buildManagerCareerProfile } from './manager-career-profile';

const app=document.querySelector<HTMLDivElement>('#app')!;
let world:World=createWorld();
let stage:'login'|'creator'|'game'='login';
let view='home';
let creatorStep=0;
let selectedClubId=world.clubs[0]?.id??'';

const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const club=(id:string)=>world.clubs.find(c=>c.id===id);
const clubName=(id:string)=>club(id)?.name??id;
const icon=(name:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const pct=(n:number)=>Math.max(0,Math.min(100,n));

function sprite(){return `<svg class="svg-sprite" xmlns="http://www.w3.org/2000/svg"><defs>
<symbol id="i-home"><path d="M3 10.8 12 3l9 7.8V21h-6v-6H9v6H3Z"/></symbol><symbol id="i-inbox"><path d="M3 5h18v14H3z"/><path d="m3 8 9 6 9-6"/></symbol><symbol id="i-team"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 20c.6-4 2.6-6 6-6s5.4 2 6 6M15 14c3 0 5 2 5.5 5"/></symbol><symbol id="i-tactics"><rect x="3" y="4" width="18" height="16" rx="1"/><circle cx="12" cy="12" r="3"/><path d="M12 4v16M3 12h18"/></symbol><symbol id="i-calendar"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 10h18"/></symbol><symbol id="i-transfer"><path d="M4 7h14l-3-3m3 3-3 3M20 17H6l3 3m-3-3 3-3"/></symbol><symbol id="i-staff"><circle cx="12" cy="7" r="3"/><path d="M6 21v-2c0-4 2-6 6-6s6 2 6 6v2M4 10l2 1m14-1-2 1"/></symbol><symbol id="i-chart"><path d="M4 20V10m5 10V4m5 16v-7m5 7V7"/></symbol><symbol id="i-club"><path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6Z"/><path d="M8 11h8m-4-4v9"/></symbol><symbol id="i-world"><circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3 3 4 6 4 9s-1 6-4 9c-3-3-4-6-4-9s1-6 4-9"/></symbol><symbol id="i-user"><circle cx="12" cy="8" r="4"/><path d="M4 21c.7-5 3.3-7 8-7s7.3 2 8 7"/></symbol><symbol id="i-play"><path d="m9 7 8 5-8 5Z"/></symbol><symbol id="i-search"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></symbol><symbol id="i-settings"><circle cx="12" cy="12" r="3"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M19 5l-2 2M7 17l-2 2"/></symbol>
</defs></svg>`}

function renderLogin(){app.innerHTML=sprite()+`<div class="login-scene"><div class="stadium-aura"></div><section class="login-brand"><div class="game-mark"><span>FM</span></div><div><span class="kicker">FOOTBALL MANAGEMENT SIMULATION</span><h1>THE<br><strong>TOUCHLINE</strong></h1><p>Construa uma carreira. Comande pessoas. Mude a história.</p></div><div class="season-stamp">DATABASE <b>2026</b> · WORLD ENGINE V1</div></section><section class="login-panel"><div class="panel-noise"></div><header><span class="status-dot"></span><span>PERFIL DO MANAGER</span></header><div class="login-copy"><h2>Bem-vindo ao banco.</h2><p>Entre no universo profissional do futebol e assuma cada consequência das suas decisões.</p></div><label>Nome do perfil<input id="login-name" value="Manager" autocomplete="off"></label><label>Código local<input id="login-pass" type="password" value="local" autocomplete="off"></label><button id="login-enter" class="cta">ENTRAR NO JOGO ${icon('play')}</button><button id="new-career" class="ghost">NOVA CARREIRA</button><footer><span>LOCAL BUILD</span><b>v0.1.0</b><span>PT-BR</span></footer></section></div>`;bindLogin()}
function bindLogin(){document.querySelector('#login-enter')?.addEventListener('click',()=>{stage='creator';render()});document.querySelector('#new-career')?.addEventListener('click',()=>{stage='creator';render()});}

const steps=['IDENTIDADE','HISTÓRICO','FORMAÇÃO','PERSONALIDADE','FUTEBOL','CLUBE'];
function field(label:string,id:string,value:string,type='text'){return `<label>${label}<input id="${id}" type="${type}" value="${esc(value)}"></label>`}
function select(label:string,id:string,opts:Array<[string,string]>,value:string){return `<label>${label}<select id="${id}">${opts.map(([v,n])=>`<option value="${v}" ${v===value?'selected':''}>${n}</option>`).join('')}</select></label>`}
function slider(label:string,id:string,value:number,left:string,right:string){return `<label class="axis"><span><b>${label}</b><small>${left}</small><small>${right}</small></span><input id="${id}" type="range" min="0" max="100" value="${value}"><output>${value}</output></label>`}
function portrait(){return `<div class="manager-portrait"><div class="portrait-light"></div><div class="silhouette"><i></i><b></b></div><div class="portrait-meta"><span>MANAGER PROFILE</span><strong id="portrait-name">Seu Treinador</strong><small>Identidade dinâmica · 2026</small></div></div>`}
function creatorContent(){if(creatorStep===0)return `<div class="form-grid">${field('Nome completo','m-name','Seu Treinador')}${field('Apelido','m-nick','')}${field('Data de nascimento','m-birth','1988-06-15','date')}${select('Gênero','m-gender',[['male','Masculino'],['female','Feminino'],['nonbinary','Não-binário'],['unspecified','Prefiro não informar']],'male')}${field('Nacionalidade','m-nationality','Brasil')}${field('Cidade natal','m-city','São Paulo')}</div><div class="subsection"><h3>Aparência</h3><div class="form-grid compact">${field('Altura (cm)','m-height','178','number')}${select('Porte físico','m-build',[['slim','Magro'],['average','Médio'],['athletic','Atlético'],['stocky','Robusto'],['large','Grande']],'athletic')}${select('Cabelo','m-hair',[['bald','Careca'],['short','Curto'],['medium','Médio'],['long','Longo']],'short')}${select('Estilo','m-style',[['tracksuit','Agasalho'],['suit','Terno'],['smartCasual','Esporte fino'],['casual','Casual']],'smartCasual')}</div></div>`;
if(creatorStep===1)return `<div class="creator-intro"><span>PASSADO PROFISSIONAL</span><h2>De onde você vem muda como o futebol enxerga você.</h2><p>Experiência anterior altera conhecimento, prestígio, networking e autoridade inicial.</p></div><div class="choice-cards" id="career-cards"><button data-level="none"><b>SEM CARREIRA</b><span>Início do zero</span><small>Mais difícil · reputação mínima</small></button><button data-level="amateur"><b>AMADOR</b><span>Futebol regional</span><small>Conhecimento prático básico</small></button><button data-level="semiPro" class="selected"><b>SEMIPROFISSIONAL</b><span>Experiência competitiva</span><small>Base equilibrada</small></button><button data-level="professional"><b>PROFISSIONAL</b><span>Carreira consolidada</span><small>Rede e reputação relevantes</small></button><button data-level="elite"><b>ELITE</b><span>Ex-jogador de destaque</span><small>Prestígio e pressão imediatos</small></button></div>`;
if(creatorStep===2)return `<div class="creator-intro"><span>FORMAÇÃO TÉCNICA</span><h2>Diplomas não vencem partidas. Mas mudam o que você consegue enxergar.</h2></div><div class="form-grid">${select('Licença de treinador','m-license',[['none','Sem licença'],['regionalC','Regional C'],['regionalB','Regional B'],['regionalA','Regional A'],['continentalC','Continental C'],['continentalB','Continental B'],['continentalA','Continental A'],['continentalPro','Continental Pro']],'continentalA')}${select('Formação acadêmica','m-education',[['none','Sem formação superior'],['technical','Técnico'],['bachelor','Graduação'],['postgraduate','Pós-graduação'],['masters','Mestrado'],['doctorate','Doutorado']],'bachelor')}</div><div class="course-grid"><label><input type="checkbox" checked value="performanceAnalysis"> Análise de desempenho</label><label><input type="checkbox" checked value="leadership"> Liderança</label><label><input type="checkbox" checked value="youthDevelopment"> Desenvolvimento de jovens</label><label><input type="checkbox" value="dataAnalysis"> Análise de dados</label><label><input type="checkbox" value="sportsPsychology"> Psicologia esportiva</label><label><input type="checkbox" value="footballManagement"> Gestão de futebol</label></div>`;
if(creatorStep===3)return `<div class="creator-intro"><span>PERSONALIDADE</span><h2>Você não escolhe respostas. Você constrói quem vai respondê-las.</h2></div><div class="axes">${slider('Disciplina','p-discipline',62,'Flexível','Rígido')}${slider('Empatia','p-empathy',58,'Distante','Próximo')}${slider('Paciência','p-patience',60,'Impulsivo','Paciente')}${slider('Assertividade','p-assertiveness',62,'Conciliador','Impositivo')}${slider('Diplomacia','p-diplomacy',58,'Direto','Diplomático')}${slider('Confronto','p-confrontation',42,'Evita conflito','Confrontador')}${slider('Adaptabilidade','p-adaptability',68,'Convicto','Adaptável')}${slider('Proteção pública','p-protection',60,'Expõe','Protege elenco')}</div>`;
if(creatorStep===4)return `<div class="creator-intro"><span>IDENTIDADE DE JOGO</span><h2>Defina princípios. Não uma prisão tática.</h2></div><div class="form-grid compact">${select('Formação favorita','t-formation',[['4-3-3','4-3-3'],['4-2-3-1','4-2-3-1'],['4-4-2','4-4-2'],['3-4-3','3-4-3'],['3-5-2','3-5-2']],'4-3-3')}${select('Mentalidade','t-mentality',[['defensive','Defensiva'],['balanced','Equilibrada'],['positive','Positiva'],['attacking','Ofensiva']],'positive')}</div><div class="axes">${slider('Posse','t-possession',64,'Vertical','Paciente')}${slider('Pressão','t-pressing',70,'Bloco baixo','Pressão alta')}${slider('Ritmo','t-tempo',64,'Cadenciado','Acelerado')}${slider('Jogo direto','t-direct',38,'Curto','Direto')}${slider('Linha defensiva','t-line',62,'Baixa','Alta')}${slider('Uso da base','t-youth',72,'Experiência','Juventude')}</div>`;
return `<div class="creator-intro"><span>PRIMEIRO CONTRATO</span><h2>Escolha onde sua história começa.</h2><p>O clube inicial será gravado na carreira e definirá diretoria, elenco, torcida, calendário e ambiente de pressão.</p></div><div class="club-picker">${world.clubs.slice(0,24).map((c,i)=>`<button data-club="${esc(c.id)}" class="${c.id===selectedClubId?'selected':''}"><i>${String(i+1).padStart(2,'0')}</i><div><b>${esc(c.name)}</b><span>Reputação ${c.reputation} · ${c.players.length} jogadores</span></div><strong>${Math.round(teamStrength(c).overall)}</strong></button>`).join('')}</div>`}
function renderCreator(){app.innerHTML=sprite()+`<div class="creator-shell"><aside class="creator-rail"><div class="mini-brand"><span>FM</span><b>THE TOUCHLINE</b></div><ol>${steps.map((s,i)=>`<li class="${i===creatorStep?'active':i<creatorStep?'done':''}"><i>${i<creatorStep?'✓':i+1}</i><span>${s}</span></li>`).join('')}</ol><div class="creator-tip"><span>CARREIRA DINÂMICA</span><p>As escolhas aqui não são cosméticas. Elas alimentam os motores de relações, imprensa, emprego, treino e evolução.</p></div></aside><main class="creator-main"><header><div><span class="kicker">CRIAR TREINADOR · ETAPA ${creatorStep+1}/${steps.length}</span><h1>${steps[creatorStep]}</h1></div><button id="creator-exit" class="icon-btn">×</button></header><div class="creator-workspace">${portrait()}<section class="creator-form">${creatorContent()}</section></div><footer><button id="creator-back" class="ghost" ${creatorStep===0?'disabled':''}>VOLTAR</button><div class="progress"><i style="width:${((creatorStep+1)/steps.length)*100}%"></i></div><button id="creator-next" class="cta">${creatorStep===steps.length-1?'ASSINAR CONTRATO':'CONTINUAR'} ${icon('play')}</button></footer></main></div>`;bindCreator()}
function bindCreator(){document.querySelector('#creator-exit')?.addEventListener('click',()=>{stage='login';render()});document.querySelector('#creator-back')?.addEventListener('click',()=>{if(creatorStep>0){creatorStep--;render()}});document.querySelector('#creator-next')?.addEventListener('click',()=>{if(creatorStep<steps.length-1){creatorStep++;render()}else startCareer()});document.querySelectorAll<HTMLButtonElement>('[data-level]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-level]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');sessionStorage.setItem('manager-playing-level',b.dataset.level??'semiPro')});document.querySelectorAll<HTMLButtonElement>('[data-club]').forEach(b=>b.onclick=()=>{selectedClubId=b.dataset.club??selectedClubId;render()});document.querySelectorAll<HTMLInputElement>('input[type=range]').forEach(x=>x.oninput=()=>{const out=x.parentElement?.querySelector('output');if(out)out.textContent=x.value});const name=document.querySelector<HTMLInputElement>('#m-name');if(name)name.oninput=()=>{const p=document.querySelector('#portrait-name');if(p)p.textContent=name.value||'Seu Treinador'}}

function v(id:string,fallback:number){return Number((document.querySelector<HTMLInputElement>(`#${id}`)?.value??sessionStorage.getItem(id))||fallback)}
function val(id:string,fallback:string){return (document.querySelector<HTMLInputElement|HTMLSelectElement>(`#${id}`)?.value??sessionStorage.getItem(id)??fallback)}
function startCareer(){const season=world.season;const level=(sessionStorage.getItem('manager-playing-level')??'semiPro') as PlayingLevel;const input:ManagerCreationInput={name:'Seu Treinador',dateOfBirth:`${season-38}-06-15`,age:38,gender:'male' as ManagerGender,appearance:{heightCm:178,build:'athletic',hair:'short',hairColor:'brown',facialHair:'stubble',style:'smartCasual',glasses:false},social:{maritalStatus:'single',children:0,languages:['Português'],nationality:'Brasil',birthCity:'São Paulo',rivalClubs:[]},playingLevel:level,primaryPlayingPosition:level==='none'?undefined:'CM',playingCareer:level==='none'?[]:[{clubName:'Carreira anterior',country:'Brasil',startYear:season-12,endYear:season-4,position:'CM',titles:[],awards:[]}],staffCareer:[],education:{level:'bachelor',field:'physicalEducation',licence:'continentalA' as CoachingLicence,courses:['performanceAnalysis','leadership','youthDevelopment']},personality:{discipline:62,empathy:58,patience:60,assertiveness:62,publicProtection:60,diplomacy:58,confrontation:42,pragmatism:58,consistency:64,mediaSkill:54,adaptability:68,forgiveness:58},tactical:{favoriteFormation:'4-3-3',secondaryFormations:['4-2-3-1'],mentality:'positive',possessionPreference:64,pressingPreference:70,tempoPreference:64,directness:38,defensiveLinePreference:62,widthPreference:60,counterAttack:56,buildFromBack:68,creativeFreedom:60,setPieceImportance:52,youthUsage:72,rotation:56},training:{intensity:62,physical:55,technical:66,tactical:70,individualDevelopment:70,videoAnalysis:62,opponentPreparation:60,recovery:64,repetition:56,playerFreedom:58},ambition:{startingClubId:selectedClubId,dreamClubs:[],preferredCountries:['Brasil'],avoidCountries:[],nationalTeamAmbition:55,salaryImportance:40,stabilityImportance:55,trophyAmbition:72,reputationAmbition:65,youthProjectPreference:70,financialProjectPreference:48},currentClubId:selectedClubId,createdSeason:season};createManagerCharacter(world,input,true);stage='game';view='home';render()}

const nav=[['home','home','Início'],['inbox','inbox','Caixa de Entrada'],['squad','team','Elenco'],['tactics','tactics','Táticas'],['calendar','calendar','Calendário'],['transfers','transfer','Transferências'],['staff','staff','Comissão Técnica'],['analytics','chart','Análise'],['club','club','Clube'],['world','world','Mundo'],['manager','user','Meu Treinador']];
function shell(content:string){const m=userManager(world),date=dailyCalendar(world).date,c=club(m?.currentClubId??selectedClubId);return `<div class="game-shell"><aside class="game-sidebar"><div class="mini-brand game"><span>FM</span><b>THE TOUCHLINE</b></div><div class="club-identity"><div class="crest">${(c?.name??'FC').slice(0,2).toUpperCase()}</div><div><b>${esc(c?.name??'Sem clube')}</b><span>${world.season} · Brasil</span></div></div><nav>${nav.map(([id,ic,label])=>`<button data-view="${id}" class="${view===id?'active':''}">${icon(ic)}<span>${label}</span>${id==='inbox'?'<i>4</i>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><button>${icon('settings')}<span>Preferências</span></button></div></aside><section class="game-stage"><header class="topbar"><div class="quick-search">${icon('search')}<span>Buscar jogador, clube, competição...</span><kbd>Ctrl K</kbd></div><div class="top-status"><span><small>DATA</small><b>${date.split('-').reverse().join('/')}</b></span><span><small>HORA</small><b>09:30</b></span><button id="continue-day" class="continue">CONTINUAR ${icon('play')}</button></div></header><main class="view">${content}</main></section></div>`}
function hero(title:string,subtitle:string,tag='CENTRO DO MANAGER'){return `<header class="view-hero"><div><span class="kicker">${tag}</span><h1>${title}</h1><p>${subtitle}</p></div><div class="hero-glow"></div></header>`}
function renderHome(){const m=userManager(world)!,c=club(m.currentClubId)!,table=sortedStandings(world),pos=Math.max(1,table.findIndex(r=>r.clubId===c.id)+1),strength=teamStrength(c),next=world.fixtures.find(f=>!f.played&&(f.home===c.id||f.away===c.id));return shell(`${hero(`Bom dia, ${esc(m.name.split(' ')[0])}.`,'A comissão terminou a análise da manhã. Três decisões aguardam sua atenção.')}<section class="dashboard-grid"><article class="glass priority"><div class="card-title"><span>PRÓXIMA PARTIDA</span><b>${next?`Rodada ${next.round}`:'Pré-temporada'}</b></div><div class="matchup"><div><div class="mini-crest">${(next?clubName(next.home):c.name).slice(0,2).toUpperCase()}</div><b>${esc(next?clubName(next.home):c.name)}</b></div><strong><small>${next?'CAMPEONATO':'AMISTOSO'}</small>VS</strong><div><div class="mini-crest away">${(next?clubName(next.away):'Adversário').slice(0,2).toUpperCase()}</div><b>${esc(next?clubName(next.away):'A definir')}</b></div></div><div class="match-foot"><span>Força do time <b>${strength.overall.toFixed(0)}</b></span><button data-view="tactics">PREPARAR PARTIDA</button></div></article><article class="glass inbox-card"><div class="card-title"><span>CAIXA DE ENTRADA</span><b>4 NOVAS</b></div>${[['Assistente técnico','Relatório de preparação concluído','08:42'],['Diretoria','Reunião mensal de desempenho','08:15'],['Departamento médico','Atualização de condição do elenco','07:50'],['Scout-chefe','Jogadores recomendados','Ontem']].map(x=>`<button><i></i><div><b>${x[0]}</b><span>${x[1]}</span></div><time>${x[2]}</time></button>`).join('')}</article><article class="glass metric-card"><span>CLASSIFICAÇÃO</span><strong>${pos}<sup>º</sup></strong><small>${table.find(r=>r.clubId===c.id)?.points??0} pontos</small><div class="metric-line"><i style="width:${pct(70-pos*2)}%"></i></div></article><article class="glass metric-card"><span>CONFIANÇA DA DIRETORIA</span><strong>68</strong><small>Estável · expectativa atendida</small><div class="metric-line"><i style="width:68%"></i></div></article><article class="glass news"><div class="card-title"><span>MUNDO DO FUTEBOL</span><b>AO VIVO</b></div><div class="news-lead"><span>BRASIL · AGORA</span><h3>Mercado começa a ganhar força enquanto clubes ajustam seus elencos para a temporada.</h3><p>Olheiros, empresários e diretorias intensificam movimentos nas primeiras semanas do calendário.</p></div></article><article class="glass squad-pulse"><div class="card-title"><span>PULSO DO ELENCO</span><b>${c.players.length} ATLETAS</b></div><div class="pulse-row"><span>Moral</span><b>${Math.round(c.players.reduce((s,p)=>s+p.morale,0)/c.players.length)}</b><i><em style="width:74%"></em></i></div><div class="pulse-row"><span>Condição</span><b>${Math.round(c.players.reduce((s,p)=>s+p.condition,0)/c.players.length)}%</b><i><em style="width:86%"></em></i></div><div class="pulse-row"><span>Coesão</span><b>71</b><i><em style="width:71%"></em></i></div></article></section>`)}
function renderSquad(){const c=club(userManager(world)!.currentClubId)!,xi=new Set(selectStartingEleven(c).map(p=>p.id));return shell(`${hero('Elenco Principal',`${c.name} · ${c.players.length} jogadores registrados`,'FUTEBOL · ELENCO')}<section class="glass data-panel"><div class="table-toolbar"><div><button class="active">PRINCIPAL</button><button>SUB-20</button><button>EMPRESTADOS</button></div><span>${icon('search')} Filtrar jogadores</span></div><table class="pro-table"><thead><tr><th></th><th>JOGADOR</th><th>POS</th><th>IDADE</th><th>CA</th><th>PA</th><th>CONDIÇÃO</th><th>MORAL</th></tr></thead><tbody>${[...c.players].sort((a,b)=>b.currentAbility-a.currentAbility).map(p=>`<tr class="${xi.has(p.id)?'starter':''}"><td><i class="status ${xi.has(p.id)?'on':''}"></i></td><td><div class="player-name"><span>${p.name.slice(0,1)}</span><b>${esc(p.name)}</b></div></td><td><mark>${p.position}</mark></td><td>${p.age}</td><td><b>${p.currentAbility}</b></td><td>${p.potentialAbility}</td><td><div class="condition"><i style="width:${pct(p.condition)}%"></i></div><small>${p.condition}%</small></td><td><span class="morale">●</span> ${p.morale}</td></tr>`).join('')}</tbody></table></section>`)}
function renderTactics(){const c=club(userManager(world)!.currentClubId)!,xi=selectStartingEleven(c);const positions=[[50,88],[18,68],[39,73],[61,73],[82,68],[35,52],[65,52],[18,34],[50,36],[82,34],[50,14]];return shell(`${hero('Plano de Jogo','Estrutura, funções e princípios para a próxima partida.','FUTEBOL · TÁTICAS')}<div class="tactics-pro"><section class="pitch-wrap"><div class="pitch-3d">${xi.map((p,i)=>`<button class="player-chip" style="left:${positions[i]?.[0]??50}%;top:${positions[i]?.[1]??50}%"><i>${i+1}</i><span><b>${esc(p.name.split(' ').pop())}</b><small>${p.position} · ${p.currentAbility}</small></span></button>`).join('')}</div></section><section class="glass tactic-panel"><div class="tactic-head"><span>IDENTIDADE</span><strong>${c.tactics.mentality.toUpperCase()}</strong></div>${[['Formação',userManager(world)!.tactical.favoriteFormation],['Mentalidade',c.tactics.mentality],['Ritmo',String(c.tactics.tempo)],['Pressão',String(c.tactics.pressing)],['Linha defensiva',String(c.tactics.defensiveLine)],['Largura',String(c.tactics.width)]].map(x=>`<div class="setting-row"><span>${x[0]}</span><b>${esc(x[1])}</b></div>`).join('')}<div class="tactic-actions"><button>INSTRUÇÕES</button><button class="accent">SALVAR PLANO</button></div></section></div>`)}
function renderInbox(){return shell(`${hero('Caixa de Entrada','Tudo o que exige sua atenção chega aqui.','CENTRAL · COMUNICAÇÃO')}<section class="inbox-layout"><aside class="glass inbox-list">${[['Assistente técnico','Relatório de preparação concluído','08:42'],['Diretoria','Reunião mensal de desempenho','08:15'],['Departamento médico','Atualização física','07:50'],['Scout-chefe','Jogadores recomendados','Ontem'],['Imprensa','Coletiva pré-jogo','Ontem']].map((x,i)=>`<button class="${i===0?'active':''}"><span>${x[0].slice(0,1)}</span><div><b>${x[0]}</b><p>${x[1]}</p></div><time>${x[2]}</time></button>`).join('')}</aside><article class="glass message"><header><div><span>ASSISTENTE TÉCNICO · 08:42</span><h2>Preparação para a próxima partida concluída</h2></div></header><p>A equipe técnica finalizou os relatórios de carga, condição, tendências do adversário e encaixes táticos. O elenco principal está disponível para sua decisão.</p><div class="advice-box"><b>RECOMENDAÇÃO</b><p>Manter a estrutura-base, reduzir ligeiramente a intensidade de pressão no primeiro tempo e atacar o espaço entre lateral e zagueiro adversários.</p></div><footer><button>IGNORAR</button><button data-view="tactics" class="accent">ABRIR TÁTICAS</button></footer></article></section>`)}
function renderCalendar(){const c=club(userManager(world)!.currentClubId)!,fixtures=world.fixtures.filter(f=>f.home===c.id||f.away===c.id).slice(0,12);return shell(`${hero('Calendário','Partidas, treinos, viagens e compromissos institucionais.','TEMPORADA · PLANEJAMENTO')}<section class="glass calendar-list">${fixtures.map((f,i)=>`<div><time><b>${String(i+1).padStart(2,'0')}</b><span>AGO</span></time><i class="event-line"></i><div class="calendar-event"><span>${f.played?'CONCLUÍDA':'CAMPEONATO'}</span><b>${esc(clubName(f.home))} <strong>${f.played?`${f.homeGoals}–${f.awayGoals}`:'×'}</strong> ${esc(clubName(f.away))}</b><small>Rodada ${f.round} · ${f.home===c.id?'Casa':'Fora'}</small></div></div>`).join('')}</section>`)}
function renderGeneric(title:string,sub:string,tag:string){return shell(`${hero(title,sub,tag)}<section class="generic-grid"><article class="glass feature"><span>VISÃO GERAL</span><h2>O módulo está conectado ao universo da carreira.</h2><p>Esta camada visual foi preparada para receber os controles específicos do motor sem romper a identidade do jogo.</p><div class="feature-stats"><b><strong>LIVE</strong> Mundo persistente</b><b><strong>2026</strong> Base inicial</b><b><strong>∞</strong> Continuidade</b></div></article><article class="glass ambient"><div class="light-orb"></div><span>${tag}</span><h3>${title}</h3></article></section>`)}
function renderManager(){const p=buildManagerCareerProfile(world),m=userManager(world)!;return shell(`${hero(m.name,`${p?.clubName??clubName(m.currentClubId)} · ${m.age} anos · ${m.social.nationality}`,'CARREIRA · MEU TREINADOR')}<section class="manager-dashboard"><div class="manager-card">${portrait()}</div><article class="glass profile-stats"><div><span>REPUTAÇÃO</span><b>${m.reputation.domestic}</b></div><div><span>PRESTÍGIO TÉCNICO</span><b>${m.reputation.coachingPrestige}</b></div><div><span>EXPERIÊNCIA</span><b>${m.experienceYears}<small> anos</small></b></div><div><span>CARREIRA</span><b>${m.careerPoints}</b></div></article><article class="glass philosophy"><span>IDENTIDADE ATUAL</span><h3>${m.tactical.favoriteFormation} · ${m.tactical.mentality}</h3><p>Pressão ${m.tactical.pressingPreference} · posse ${m.tactical.possessionPreference} · formação de jovens ${m.tactical.youthUsage}</p><div class="trait-tags"><i>Disciplina ${m.personality.discipline}</i><i>Empatia ${m.personality.empathy}</i><i>Adaptabilidade ${m.personality.adaptability}</i></div></article></section>`)}
function renderGame(){const content=view==='home'?renderHome():view==='inbox'?renderInbox():view==='squad'?renderSquad():view==='tactics'?renderTactics():view==='calendar'?renderCalendar():view==='manager'?renderManager():view==='transfers'?renderGeneric('Mercado de Transferências','Scouting, negociações, agentes e oportunidades em um só espaço.','RECRUTAMENTO · MERCADO'):view==='staff'?renderGeneric('Comissão Técnica','Pessoas, funções, relações e impacto diário no trabalho.','CLUBE · STAFF'):view==='analytics'?renderGeneric('Centro de Análise','Dados de desempenho produzidos pelo próprio match engine.','FUTEBOL · DADOS'):view==='club'?renderGeneric('Estrutura do Clube','Diretoria, finanças, patrimônio, torcida e ambiente institucional.','GESTÃO · CLUBE'):renderGeneric('Mundo do Futebol','Competições, países, clubes, seleções e acontecimentos globais.','UNIVERSO · MUNDO');app.innerHTML=sprite()+content;bindGame()}
function bindGame(){document.querySelectorAll<HTMLElement>('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view??'home';render()});document.querySelector('#continue-day')?.addEventListener('click',()=>{advanceOneDay(world);render()})}
function render(){if(stage==='login')renderLogin();else if(stage==='creator')renderCreator();else renderGame()}
render();
