import type { World } from './engine';
import type { DialogueAudience,DialogueContext,DialogueLine,DialogueTone,DialogueTopic } from './human-dialogue-bank-v1';
import { generateDialogue } from './human-dialogue-bank-v1';
export type HumanVoiceRole='journalist'|'president'|'director'|'agent'|'player'|'captain'|'staff'|'supporter';
export type HumanVoiceProfile={speakerId:string;role:HumanVoiceRole;formality:number;directness:number;aggression:number;warmth:number;patience:number;humour:number;insistence:number;discretion:number;optimism:number;ego:number;preferredTone:DialogueTone;signature:string;topicMemory:Partial<Record<DialogueTopic,number>>;lastTopics:DialogueTopic[];timesSpoken:number};
export type HumanDialogueFeedItem={id:string;speakerId:string;role:HumanVoiceRole;audience:DialogueAudience;topic:DialogueTopic;text:string;voiceSignature:string;seed?:string};
export type HumanVoiceSnapshot={profiles:[string,HumanVoiceProfile][];feed?:HumanDialogueFeedItem[]};
const states=new WeakMap<World,Map<string,HumanVoiceProfile>>();
const clamp=(n:number)=>Math.max(0,Math.min(100,n));
const h=(s:string)=>{let x=2166136261;for(const c of s){x^=c.charCodeAt(0);x=Math.imul(x,16777619)}return x>>>0};
const n=(seed:number,k:number,min:number,max:number)=>Math.round(min+(((Math.sin(seed*0.000013+k*31.73)+1)/2)*(max-min)));
const feed=()=>{const g=globalThis as any;if(!Array.isArray(g.__touchlineHumanDialogueFeed))g.__touchlineHumanDialogueFeed=[] as HumanDialogueFeedItem[];return g.__touchlineHumanDialogueFeed as HumanDialogueFeedItem[]};
export function humanDialogueFeed(limit=100){return feed().slice(-limit)}
export function replaceHumanDialogueFeed(items:HumanDialogueFeedItem[]){const f=feed();f.splice(0,f.length,...items.slice(-200))}
function publishFeed(item:HumanDialogueFeedItem){const f=feed();f.push(item);if(f.length>200)f.splice(0,f.length-200);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('touchline:human-dialogue',{detail:item}))}
function defaultTone(role:HumanVoiceRole,p:{aggression:number;warmth:number;directness:number;optimism:number}):DialogueTone{if(p.aggression>72)return'firm';if(p.warmth>72)return'supportive';if(p.optimism>70)return'confident';if(p.directness<35)return'diplomatic';return'calm'}
function signature(role:HumanVoiceRole,seed:number){const rows:Record<HumanVoiceRole,string[]>={journalist:['insiste em respostas concretas','prefere perguntas curtas','costuma retomar contradições antigas','faz perguntas técnicas antes de provocar','busca bastidores e reações'],president:['fala em responsabilidade institucional','cobra compromisso com o projeto','evita promessas públicas','mistura futebol e política interna','cobra resultados com linguagem empresarial'],director:['fala em planejamento e processo','é objetivo sobre mercado','protege informações de negociação','cobra coerência esportiva','pensa em médio prazo'],agent:['fala em valorização e carreira','retoma promessas feitas ao atleta','pressiona por prazos','evita fechar portas','usa interesse externo como alavanca'],player:['fala de confiança e espaço','mede as palavras quando está inseguro','é direto quando se sente injustiçado','valoriza respeito no trato pessoal','fala mais quando confia no treinador'],captain:['fala pelo grupo sem expor nomes','tenta preservar o vestiário','é franco sobre clima interno','cobra coerência do treinador','media interesses individuais e coletivos'],staff:['fala de evidência e rotina','evita dramatizar','aponta riscos antes de problemas','prefere conversas reservadas','traduz análise em recomendação'],supporter:['fala com memória afetiva','cobra identidade competitiva','compara o presente com temporadas marcantes','valoriza jogadores identificados com o clube','reage fortemente a clássicos']};const a=rows[role];return a[seed%a.length]}
export function humanVoiceState(world:World){let s=states.get(world);if(!s){s=new Map();states.set(world,s)}return s}
export function humanVoice(world:World,speakerId:string,role:HumanVoiceRole){const s=humanVoiceState(world),key=`${role}:${speakerId}`;let p=s.get(key);if(!p){const seed=h(key),base={aggression:n(seed,1,10,88),warmth:n(seed,2,15,90),directness:n(seed,3,20,95),optimism:n(seed,4,20,85)};p={speakerId,role,formality:n(seed,5,20,95),directness:base.directness,aggression:base.aggression,warmth:base.warmth,patience:n(seed,6,15,92),humour:n(seed,7,0,70),insistence:n(seed,8,20,95),discretion:n(seed,9,15,95),optimism:base.optimism,ego:n(seed,10,10,88),preferredTone:defaultTone(role,base),signature:signature(role,seed),topicMemory:{},lastTopics:[],timesSpoken:0};s.set(key,p)}return p}
function adaptiveTone(v:HumanVoiceProfile,ctx:DialogueContext):DialogueTone{if((ctx.pressure??0)>78&&v.aggression>58)return'firm';if(ctx.positive===false&&v.optimism<45)return'frustrated';if(v.discretion>76&&['personal','contract','transfer'].includes(ctx.topic))return'diplomatic';if(v.warmth>78&&['personal','injury'].includes(ctx.topic))return'supportive';return ctx.tone??v.preferredTone}
export function speakAs(world:World,speakerId:string,role:HumanVoiceRole,ctx:DialogueContext,index=0):DialogueLine&{speakerId:string;voiceSignature:string}{const v=humanVoice(world,speakerId,role);const repetition=v.topicMemory[ctx.topic]??0,tone=adaptiveTone(v,ctx),row=generateDialogue({...ctx,tone,seed:`${ctx.seed??''}:${speakerId}:${v.signature}:${repetition}`},index+repetition);v.topicMemory[ctx.topic]=repetition+1;v.lastTopics.push(ctx.topic);if(v.lastTopics.length>8)v.lastTopics.shift();v.timesSpoken++;if(repetition>=3&&v.insistence>65)v.aggression=clamp(v.aggression+.15);const out={...row,speakerId,voiceSignature:v.signature};publishFeed({id:`speech-${h(`${speakerId}:${ctx.seed??''}:${v.timesSpoken}`).toString(36)}`,speakerId,role,audience:ctx.audience,topic:ctx.topic,text:row.text,voiceSignature:v.signature,seed:ctx.seed});return out}
export function voiceAudience(role:HumanVoiceRole):DialogueAudience{return role==='journalist'?'press':role==='president'||role==='director'?'board':role==='agent'?'agent':role==='captain'?'dressingRoom':role==='staff'?'staff':role==='supporter'?'supporters':'player'}
export function snapshotHumanVoices(world:World):HumanVoiceSnapshot{return{profiles:[...humanVoiceState(world)].map(([k,v])=>[k,{...v,topicMemory:{...v.topicMemory},lastTopics:[...v.lastTopics]}]),feed:humanDialogueFeed(200).map(x=>({...x}))}}
export function restoreHumanVoices(world:World,snapshot?:HumanVoiceSnapshot){if(!snapshot)return;states.set(world,new Map(snapshot.profiles.map(([k,v])=>[k,{...v,topicMemory:{...v.topicMemory},lastTopics:[...v.lastTopics]}])));replaceHumanDialogueFeed((snapshot.feed??[]).map(x=>({...x})))}
