export type DialogueAudience='press'|'board'|'player'|'dressingRoom'|'staff'|'agent'|'supporters';
export type DialogueTopic='result'|'performance'|'selection'|'tactics'|'pressure'|'future'|'transfer'|'contract'|'discipline'|'personal'|'injury'|'dressingRoom'|'leadership'|'youth'|'finance'|'facilities'|'promise'|'rivalry'|'referee'|'training';
export type DialogueTone='supportive'|'calm'|'firm'|'harsh'|'diplomatic'|'defensive'|'ambitious'|'cautious'|'frustrated'|'confident';
export type DialogueContext={audience:DialogueAudience;topic:DialogueTopic;tone?:DialogueTone;club?:string;player?:string;opponent?:string;competition?:string;manager?:string;severity?:number;pressure?:number;positive?:boolean;seed?:string};
export type DialogueLine={id:string;audience:DialogueAudience;topic:DialogueTopic;tone:DialogueTone;text:string};
const subjects:Record<DialogueAudience,string[]>={
 press:['O repórter da TV pergunta','A jornalista do setorista pergunta','O comentarista insiste','O repórter de campo questiona','A rádio local pergunta','O portal esportivo quer saber','A imprensa volta ao tema','O jornalista mais experiente pergunta','A repórter da coletiva questiona','O correspondente pergunta'],
 board:['O presidente pondera','O diretor de futebol pergunta','O vice-presidente questiona','O conselho quer entender','O diretor financeiro alerta','O representante da torcida pergunta','O executivo de futebol observa','A presidência cobra uma posição','Um conselheiro influente questiona','O diretor da base pergunta'],
 player:['O jogador diz','O atleta pergunta','O jogador procura você e diz','O atleta fala em particular','O jogador hesita antes de perguntar','O atleta é direto','O jogador demonstra incômodo e diz','O atleta tenta entender a decisão','O jogador pede uma conversa e diz','O atleta fala em tom reservado'],
 dressingRoom:['Um dos líderes pergunta','O capitão fala pelo grupo','Um jogador experiente diz','O vestiário quer uma resposta','Um dos atletas mais influentes pergunta','O vice-capitão comenta','Um grupo de jogadores questiona','O capitão chama você de lado e diz','Um veterano resume o sentimento do elenco','Um dos líderes tenta aliviar a tensão e pergunta'],
 staff:['O auxiliar pergunta','O preparador comenta','O analista sugere','O diretor técnico questiona','O treinador de goleiros observa','O fisiologista alerta','O assistente chama você de lado e diz','O analista de desempenho pergunta','Um membro da comissão comenta','O coordenador técnico quer saber'],
 agent:['O agente pergunta','O representante do atleta diz','O empresário insiste','O agente tenta esclarecer','O representante faz uma contraproposta e diz','O empresário cobra uma definição','O agente fala em nome do jogador','O representante tenta reduzir a tensão e pergunta','O empresário é direto','O agente retoma a conversa'],
 supporters:['Um torcedor pergunta','A associação de torcedores questiona','Um sócio quer saber','A torcida organizada cobra','Um representante dos sócios pergunta','Um torcedor antigo comenta','A arquibancada quer uma resposta','Um grupo de torcedores questiona','Um conselheiro ligado à torcida pergunta','Um torcedor em evento do clube pergunta']};
const questions:Record<DialogueTopic,string[]>={
 result:['como você explica o resultado de hoje?','o placar refletiu o que aconteceu em campo?','onde a partida escapou das mãos da equipe?','o que mais incomodou você no jogo?','o que a equipe fez melhor do que o placar sugere?','esse resultado muda alguma coisa no planejamento?','houve falta de concentração nos momentos decisivos?','a equipe merecia sair com mais?','qual é a principal lição desta partida?','você considera este um resultado aceitável?'],
 performance:['você está satisfeito com o nível de atuação da equipe?','por que o time caiu tanto de rendimento?','o desempenho recente preocupa?','faltou intensidade hoje?','a equipe está conseguindo executar o que você treina?','você enxerga evolução apesar das oscilações?','há jogadores abaixo do nível esperado?','o problema é técnico, físico ou emocional?','o time está sentindo a sequência de jogos?','quanto desse desempenho passa pela confiança do elenco?'],
 selection:['por que você deixou {player} fora da equipe?','{player} perdeu espaço definitivamente?','o que pesou na escolha dos titulares?','há meritocracia na disputa por posição?','você pretende rodar mais o elenco?','essa escalação foi uma mensagem para alguém?','o banco de reservas de {player} foi uma decisão técnica?','há jogadores intocáveis no seu time?','como você administra quem joga menos?','a hierarquia do elenco mudou?'],
 tactics:['por que você mudou a estrutura tática?','o plano de jogo funcionou como esperava?','você pretende manter esse sistema?','a equipe ficou exposta demais?','faltou agressividade sem a bola?','por que o time baixou as linhas?','a saída de bola está funcionando?','a equipe está confortável com as novas funções?','quanto o adversário obrigou você a mudar o plano?','você considera rever sua ideia de jogo?'],
 pressure:['você se sente pressionado neste momento?','a cobrança externa está afetando o trabalho?','você teme pelo cargo?','como convive com as críticas?','a pressão da torcida é justa?','a diretoria ainda demonstra confiança?','o ambiente ficou mais pesado nos últimos dias?','você consegue blindar o elenco dessa cobrança?','há sensação de ultimato internamente?','você sente que precisa provar algo agora?'],
 future:['você se vê aqui na próxima temporada?','há conversas sobre renovação?','seu projeto ainda está no começo?','o que falta para o clube dar o próximo passo?','você pretende cumprir o contrato até o fim?','há interesse de outros clubes?','qual é sua ambição para os próximos anos?','o planejamento depende de classificação para {competition}?','você sente que o clube compartilha sua visão?','quando será possível avaliar de verdade este trabalho?'],
 transfer:['{player} está no mercado?','você autorizaria a saída de {player}?','o clube precisa vender antes de contratar?','há uma posição tratada como prioridade?','você pediu reforços à diretoria?','existe alguma negociação avançada?','como reage ao interesse de outros clubes em seus jogadores?','você prefere um elenco curto ou mais opções?','há atletas insatisfeitos buscando saída?','o mercado atual mudou seu planejamento?'],
 contract:['por que a renovação ainda não foi fechada?','o salário pedido está dentro da realidade do clube?','há risco de perder {player} sem compensação?','o papel esportivo prometido está em discussão?','você considera essa negociação prioritária?','o clube está disposto a melhorar a proposta?','há divergência sobre duração do contrato?','a relação com o agente está dificultando o acordo?','você deu garantias ao jogador?','quando espera uma definição?'],
 discipline:['como você vai lidar com o episódio envolvendo {player}?','há regras diferentes para jogadores importantes?','o clube pretende punir o atleta?','isso foi uma quebra de confiança?','você conversou com {player} em particular?','a situação exige uma resposta pública?','até onde vai a vida privada de um jogador?','o episódio pode afetar a escalação?','o elenco espera uma postura mais dura?','você teme perder autoridade se não houver punição?'],
 personal:['como o clube está apoiando {player}?','você pretende dar tempo ao atleta para resolver a situação?','o futebol fica em segundo plano neste momento?','há preocupação com a privacidade do jogador?','você conversou pessoalmente com {player}?','a situação emocional pode afastá-lo dos jogos?','o grupo está dando suporte ao companheiro?','como equilibrar humanidade e responsabilidade profissional?','o clube vai oferecer apoio especializado?','você prefere não expor detalhes deste assunto?'],
 injury:['qual é a gravidade da lesão de {player}?','há previsão de retorno?','o departamento médico poderia ter evitado isso?','o jogador vinha atuando no limite físico?','você vai buscar reposição no mercado?','a sequência de jogos contribuiu para a lesão?','há risco de retorno antecipado?','como a ausência muda o plano da equipe?','o clube está satisfeito com o processo de recuperação?','{player} será preservado quando voltar?'],
 dressingRoom:['há problemas no vestiário?','o elenco ainda está fechado com você?','existem grupos insatisfeitos?','como está sua relação com os líderes?','houve discussão após o último jogo?','a disputa por espaço está saudável?','há jogadores questionando suas decisões?','o ambiente interno é melhor do que parece de fora?','você precisou reunir o elenco para conter a tensão?','há alguma situação interna que possa afetar o campo?'],
 leadership:['quem são as vozes mais importantes do elenco?','a capitania está definida?','você espera mais dos jogadores experientes?','os líderes estão ajudando nos momentos difíceis?','há espaço para jovens assumirem responsabilidade?','o capitão representa bem o grupo?','você conversa com os líderes antes de decisões importantes?','a hierarquia interna mudou nesta temporada?','há liderança suficiente quando o time sofre?','como você reage quando um líder discorda de você?'],
 youth:['por que os jovens têm recebido poucas oportunidades?','há alguém da base pronto para subir?','o clube precisa contratar ou pode olhar para dentro?','você aceita perder resultados para desenvolver jovens?','como protege um jovem da pressão precoce?','a academia está alinhada ao seu modelo de jogo?','há promessa de minutos para algum jogador da base?','qual é o peso da formação no seu projeto?','você pretende integrar mais jovens aos treinos?','o clube está produzindo jogadores no nível necessário?'],
 finance:['as limitações financeiras comprometem o projeto?','o orçamento é suficiente para competir?','você entende a necessidade de vender jogadores?','há espaço para uma contratação de maior impacto?','o clube está gastando acima do que deveria?','como equilibrar ambição esportiva e responsabilidade financeira?','a folha salarial limita suas escolhas?','você aceitaria reduzir custos do elenco?','os objetivos da diretoria combinam com o orçamento disponível?','a situação financeira pode mudar suas metas?'],
 facilities:['as instalações atuais atendem ao nível que você espera?','qual investimento estrutural é mais urgente?','o centro de treinamento limita a evolução da equipe?','você pediu melhorias à diretoria?','a estrutura médica precisa de investimento?','a base tem condições adequadas de trabalho?','o estádio influencia o crescimento do clube?','você prefere investir em estrutura ou no elenco agora?','as obras previstas são suficientes?','a falta de infraestrutura pesa na atração de jogadores?'],
 promise:['você ainda pretende cumprir o que prometeu?','o prazo combinado continua realista?','o jogador sente que recebeu garantias que não foram cumpridas?','a diretoria está cobrando essa promessa?','você se arrepende de ter assumido esse compromisso?','houve mudança de cenário desde a conversa original?','como recuperar confiança se a promessa não puder ser cumprida?','você vai conversar novamente com o envolvido?','essa situação pode gerar desgaste no elenco?','sua credibilidade está em jogo?'],
 rivalry:['o peso da rivalidade muda sua preparação?','vencer {opponent} vale mais do que três pontos?','como controlar a emoção num clássico?','o histórico recente contra {opponent} incomoda?','você espera um jogo mais físico?','a torcida aceita uma postura cautelosa neste confronto?','há jogadores que sentem demais este tipo de partida?','o clássico pode mudar o ambiente da temporada?','você usa a rivalidade como motivação?','o que não pode faltar contra {opponent}?'],
 referee:['você se sentiu prejudicado pela arbitragem?','o lance decisivo merece reclamação?','você teme punição se falar sobre o árbitro?','a arbitragem influenciou o resultado?','o clube deveria se manifestar oficialmente?','você prefere não usar a arbitragem como desculpa?','houve critério diferente para as duas equipes?','seus jogadores perderam o foco discutindo com o árbitro?','você vai pedir esclarecimentos à comissão de arbitragem?','o tema precisa morrer aqui?'],
 training:['a carga de treinamento está adequada?','por que a equipe pareceu fisicamente abaixo?','você mudou a rotina de treinos?','há reclamações sobre intensidade?','como trabalha recuperação entre partidas?','o elenco está assimilando as sessões táticas?','você pretende reduzir carga nesta semana?','há treinos individuais para jogadores em baixa?','o calendário está prejudicando o trabalho de campo?','como mede se o treino está produzindo efeito?']};
const answers:Record<DialogueTone,string[]>={
 supportive:['Eu preciso olhar primeiro para a pessoa. Depois nós tratamos do futebol.','Minha responsabilidade é ajudar, sem deixar de ser claro sobre o que esperamos.','Ele sabe que tem meu apoio. Isso não significa ausência de cobrança.','O grupo precisa sentir que ninguém é descartado por atravessar um momento difícil.','Vamos conversar com calma, entender o contexto e tomar a decisão mais justa.','Confiança se constrói também quando as coisas não estão bem.','Eu prefiro resolver isso olhando no olho, não por manchete.','Há momentos em que o treinador precisa ouvir mais do que falar.','Vamos proteger o jogador e trabalhar para que ele volte a se sentir inteiro.','Eu não vou reduzir uma pessoa a noventa minutos ruins.'],
 calm:['Nós avaliamos o contexto inteiro antes de decidir.','Não existe uma única causa e eu não vou simplificar uma situação complexa.','A decisão foi técnica e pode mudar conforme o trabalho da semana.','Temos informação interna que naturalmente não está toda disponível fora do clube.','Vamos analisar, conversar e agir sem precipitação.','O resultado importa, mas o processo também precisa ser entendido.','Não vou transformar uma questão normal de futebol em crise.','Há coisas para corrigir e outras que funcionaram bem.','Nossa posição é clara internamente e isso é o mais importante agora.','Prefiro trabalhar com fatos e não com especulação.'],
 firm:['Aqui ninguém recebe lugar por nome; recebe por desempenho e comportamento.','Eu sou responsável pelas escolhas e não vou fugir delas.','Quando uma regra é estabelecida, ela precisa valer para todos.','Quem quiser jogar precisa mostrar diariamente que merece.','Podemos discutir a decisão, mas não a responsabilidade de representar este clube.','Há um padrão mínimo e eu vou cobrá-lo.','O elenco sabe exatamente o que espero e onde precisa melhorar.','Eu não prometo minutos; prometo oportunidade para quem entrega.','Se houver um problema, nós vamos enfrentá-lo internamente e com clareza.','Não vou negociar princípios para aliviar pressão de curto prazo.'],
 harsh:['Se alguém não quer competir pelo lugar, teremos de encontrar outra solução.','Eu não vou aceitar que interesses individuais fiquem acima do clube.','Há comportamentos que simplesmente não cabem num ambiente profissional.','Quem não estiver comprometido vai ficar para trás.','A camisa não garante nada a ninguém.','Eu posso aceitar erro; falta de compromisso é outra coisa.','Não preciso que todos concordem comigo, mas preciso que respeitem o trabalho.','Se a resposta em campo não vier, as decisões serão tomadas.','O clube não pode ser refém de ninguém.','Quando o limite é ultrapassado, consequência deixa de ser opção.'],
 diplomatic:['Entendo a pergunta, mas algumas conversas precisam permanecer dentro do clube.','Há interesses diferentes e nosso trabalho é encontrar um ponto responsável de equilíbrio.','Eu respeito a posição de todas as partes e espero o mesmo respeito pelo nosso processo.','Não seria correto falar por quem ainda está negociando.','A diretoria e a comissão conversam com frequência; divergência não significa ruptura.','Eu não vou alimentar uma interpretação antes de os fatos estarem completos.','Cada parte tem suas responsabilidades e estamos trabalhando para aproximá-las.','O futebol exige diálogo, especialmente quando há pressão.','Podemos discordar sobre o caminho sem transformar isso em conflito pessoal.','Quando houver algo definitivo, o clube vai comunicar da maneira adequada.'],
 defensive:['Eu não concordo com essa leitura.','Essa pergunta parte de uma premissa que não corresponde ao que acontece internamente.','É fácil construir uma narrativa olhando apenas para o resultado.','Eu protejo meu grupo porque conheço o trabalho que eles fazem todos os dias.','Não vou expor um jogador para satisfazer uma discussão pública.','Há críticas justas e há conclusões que simplesmente não têm base.','Nós assumimos nossos erros, mas não vamos aceitar qualquer versão dos fatos.','O vestiário não é o ambiente que está sendo descrito lá fora.','Se houver algo a corrigir, será corrigido; espetáculo público não ajuda.','Minha obrigação é com o clube e com o grupo, não com o ruído de fora.'],
 ambitious:['Nós queremos mais e não escondemos isso.','Este clube precisa pensar grande sem perder responsabilidade.','O objetivo não é participar; é chegar em condição de vencer.','Se houver oportunidade de melhorar o elenco, vamos pressionar para aproveitá-la.','Eu não vim aqui para administrar acomodação.','Queremos construir uma equipe capaz de competir com os melhores.','A exigência aumenta porque acreditamos que podemos chegar mais longe.','O próximo passo precisa ser maior do que simplesmente repetir a temporada passada.','Ambição não é promessa vazia; é elevar o padrão de trabalho todos os dias.','Respeitamos o adversário, mas não entramos em campo aceitando inferioridade.'],
 cautious:['Precisamos respeitar o momento e não criar expectativas artificiais.','Uma boa sequência não muda tudo, assim como uma derrota não destrói o projeto.','Ainda é cedo para conclusões definitivas.','Vamos avançar etapa por etapa.','Não quero colocar um peso desnecessário sobre o grupo.','O planejamento precisa sobreviver à emoção de um resultado.','Há margem para crescer, mas também há limitações que precisamos reconhecer.','Não vamos comprometer o futuro por ansiedade de curto prazo.','Prefiro prometer trabalho e deixar o campo construir as expectativas.','É importante manter os pés no chão.'],
 frustrated:['Nós sabemos que entregamos menos do que podemos.','Eu não saio satisfeito quando repetimos erros que já foram trabalhados.','Há uma frustração grande porque tivemos oportunidades para fazer diferente.','O que me incomoda é a maneira como deixamos o jogo escapar.','Precisamos parar de procurar explicações e começar a corrigir.','Eu esperava uma resposta melhor do grupo hoje.','Não adianta esconder: foi abaixo do nosso padrão.','Há coisas que não podem continuar acontecendo.','A cobrança começa por mim e chega a todos.','Vamos sentir este resultado hoje e trabalhar para que ele tenha consequência positiva amanhã.'],
 confident:['Eu confio no trabalho e no grupo.','Sabemos exatamente onde queremos chegar.','Uma oscilação não muda minha convicção sobre a equipe.','O time já mostrou que consegue responder em momentos difíceis.','Estamos mais próximos do nível que queremos do que parece de fora.','A pressão faz parte quando se trabalha num clube que quer vencer.','Tenho segurança nas decisões porque vejo o treino todos os dias.','O grupo está preparado para dar uma resposta.','Não precisamos de discurso extraordinário; precisamos repetir o que fazemos bem.','Eu acredito que a evolução vai aparecer de forma consistente.']};
const fill=(s:string,c:DialogueContext)=>s.replaceAll('{player}',c.player??'o jogador').replaceAll('{club}',c.club??'o clube').replaceAll('{opponent}',c.opponent??'o adversário').replaceAll('{competition}',c.competition??'a competição').replaceAll('{manager}',c.manager??'o treinador');
const hash=(s:string)=>{let h=2166136261;for(const ch of s){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
export function dialogueVariantCount(audience?:DialogueAudience,topic?:DialogueTopic){const audiences=audience?[audience]:Object.keys(subjects) as DialogueAudience[],topics=topic?[topic]:Object.keys(questions) as DialogueTopic[];let n=0;for(const a of audiences)for(const t of topics)n+=subjects[a].length*questions[t].length*Object.values(answers).reduce((x,v)=>x+v.length,0);return n}
export function generateDialogue(ctx:DialogueContext,index=0):DialogueLine{const tone=ctx.tone??(ctx.positive===false?'frustrated':ctx.pressure&&ctx.pressure>70?'defensive':'calm'),seed=hash(`${ctx.seed??''}:${ctx.audience}:${ctx.topic}:${tone}:${index}`),ss=subjects[ctx.audience],qs=questions[ctx.topic],as=answers[tone];const intro=ss[seed%ss.length],q=fill(qs[Math.floor(seed/ss.length)%qs.length],ctx),a=fill(as[Math.floor(seed/(ss.length*qs.length))%as.length],ctx);return{id:`dlg-${seed.toString(36)}`,audience:ctx.audience,topic:ctx.topic,tone,text:`${intro}: “${q}” — “${a}”`}}
export function generateDialogueSet(ctx:DialogueContext,count=12){const seen=new Set<string>(),out:DialogueLine[]=[];for(let i=0;out.length<count&&i<count*8;i++){const row=generateDialogue(ctx,i);if(!seen.has(row.text)){seen.add(row.text);out.push(row)}}return out}
export function pressQuestion(ctx:Omit<DialogueContext,'audience'>,index=0){return generateDialogue({...ctx,audience:'press'},index)}
export function boardDialogue(ctx:Omit<DialogueContext,'audience'>,index=0){return generateDialogue({...ctx,audience:'board'},index)}
export function playerDialogue(ctx:Omit<DialogueContext,'audience'>,index=0){return generateDialogue({...ctx,audience:'player'},index)}
