import type { World } from './engine';
import type { NationalSquad, NationalSquadMember } from './national-team-selection-v1';
import { playerProfile } from './player-profile-v2';
import { effectiveReadiness } from './player-match-state-v2';
import { withdrawFromInternationalDuty } from './international-duty-v1';
export type CallUpEventType='withdrawal'|'replacement'|'clubConflict'|'lateArrival'|'injuryReturn'|'debut';
export type CallUpEvent={id:string;date:string;type:CallUpEventType;teamId:string;playerId?:string;replacementId?:string;clubId?:string;severity:number;text:string};
type State={events:CallUpEvent[]};const states=new WeakMap<World,State>();function state(w:World){let s=states.get(w);if(!s){s={events:[]};states.set(w,s)}return s}const push=(w:World,e:Omit<CallUpEvent,'id'>)=>{const x={...e,id:`callup-${state(w).events.length+1}-${e.date}`};state(w).events.push(x);return x};
export function replaceWithdrawnPlayer(w:World,squad:NationalSquad,playerId:string,windowId:string,date:string,reason:string){const idx=squad.members.findIndex(x=>x.playerId===playerId);if(idx<0)return;const old=squad.members[idx],replacement=squad.reserves.shift();withdrawFromInternationalDuty(w,playerId,windowId,reason,/injur|les/i.test(reason));push(w,{date,type:'withdrawal',teamId:squad.teamId,playerId,clubId:old.clubId,severity:55,text:`${playerId} retirado da convocação: ${reason}`});if(replacement){squad.members[idx]={...replacement,status:'selected'};push(w,{date,type:'replacement',teamId:squad.teamId,playerId,replacementId:replacement.playerId,clubId:replacement.clubId,severity:35,text:`${replacement.playerId} chamado como substituto`})}return replacement}
export function flagClubSelectionConflict(w:World,squad:NationalSquad,clubId:string,date:string,fixtureImportance:number){const affected=squad.members.filter(x=>x.clubId===clubId);if(!affected.length)return[];return affected.map(x=>push(w,{date,type:'clubConflict',teamId:squad.teamId,playerId:x.playerId,clubId,severity:Math.min(100,35+fixtureImportance*.6),text:`Conflito clube-seleção envolvendo ${x.playerId}`}))}
export function assessCallUpAvailability(w:World,squad:NationalSquad){return squad.members.map(m=>{const p=w.clubs.flatMap(c=>c.players).find(x=>x.id===m.playerId),profile=playerProfile(w,m.playerId);if(!p)return{playerId:m.playerId,available:false,reason:'player_missing'};const r=effectiveReadiness(w,p);if(profile?.retired)return{playerId:m.playerId,available:false,reason:'international_retirement'};if(r.condition<45)return{playerId:m.playerId,available:false,reason:'fitness'};return{playerId:m.playerId,available:true,readiness:r.overall}})}
export function callUpEvents(w:World,teamId?:string){return state(w).events.filter(x=>!teamId||x.teamId===teamId)}
export type CallUpEventSnapshot={events:CallUpEvent[]};export function snapshotCallUpEvents(w:World):CallUpEventSnapshot{return{events:state(w).events.map(x=>({...x}))}}export function restoreCallUpEvents(w:World,x:CallUpEventSnapshot){states.set(w,{events:(x?.events??[]).map(e=>({...e}))})}
