import type { World } from './engine';
import { activeInternationalWindow } from './international-calendar-v1';
import { playQualifierMatchday, qualifierCalendar, qualifierState } from './international-qualifier-runtime-v1';
import { worldCupQualifierConfigs } from './international-qualifiers-v1';
import { footballDataSnapshot } from './world-football-data-v1';
import { nationalRankingTable } from './national-team-ranking-v1';
import { selectNationalSquad } from './national-team-selection-v1';
import { simulateInternationalMatch } from './international-match-engine-v1';
import { isUnavailable } from './injuries';
import { playerProfile } from './player-profile-v2';
import { queueWorldEvent, worldCore } from './world-core-v2';

export type InternationalDailyResult={date:string;qualifierMatchdays:number;qualifierMatches:number;friendlies:number;skippedFriendlies:number};
type State={playedFriendlyWindows:Set<string>;processedQualifierDates:Set<string>};const states=new WeakMap<World,State>();
function state(w:World){let s=states.get(w);if(!s){s={playedFriendlyWindows:new Set(),processedQualifierDates:new Set()};states.set(w,s)}return s}
function nextWorldCupYear(season:number){let y=Math.max(2030,season);while((y-2026)%4!==0)y++;return y}
function existingQualifierCycles(w:World,cycleYear:number){return worldCupQualifierConfigs(cycleYear).map(config=>qualifierState(w,config.id)).filter((q):q is NonNullable<typeof q>=>!!q)}
function countryOf(w:World,teamId:string){return footballDataSnapshot(w).nationalTeams.find(t=>t.id===teamId)?.countryId}
function hasEleven(w:World,countryId:string){let n=0;for(const c of w.clubs)for(const p of c.players){const pr=playerProfile(w,p.id);if(!pr||pr.retired||isUnavailable(w,p.id))continue;if(pr.eligibility.some(e=>e.countryId===countryId&&e.eligible)||pr.nationalities.includes(countryId)||pr.citizenships.includes(countryId))n++;if(n>=11)return true}return false}
function qualifierDue(w:World,date:string){const cycle=existingQualifierCycles(w,nextWorldCupYear(Number(date.slice(0,4))));const due:Array<{competitionId:string;matchday:number}>=[];for(const q of cycle)for(const row of qualifierCalendar(w,q.config.id))if(row.date===date&&row.played<row.fixtures)due.push({competitionId:q.config.id,matchday:row.matchday});return due}
function teamsReservedForWindow(w:World,start:string,end:string){const reserved=new Set<string>(),cycle=existingQualifierCycles(w,nextWorldCupYear(Number(start.slice(0,4))));for(const q of cycle){for(const row of qualifierCalendar(w,q.config.id)){if(row.date<start||row.date>end)continue;const current=qualifierState(w,q.config.id);for(const f of current?.fixtures.filter(x=>x.matchday===row.matchday)??[]){reserved.add(f.homeTeamId);reserved.add(f.awayTeamId)}}}return reserved}
function friendlyPairs(w:World,excluded:Set<string>){const snap=footballDataSnapshot(w),teams=snap.nationalTeams.filter(t=>t.active&&t.teamKind==='senior'&&t.gender==='men'&&!excluded.has(t.id)),ranking=nationalRankingTable(w),rank=new Map(ranking.map(x=>[x.teamId,x.rank])),used=new Set<string>(),pairs:Array<[string,string]>=[];const ordered=[...teams].filter(t=>hasEleven(w,t.countryId)).sort((a,b)=>(rank.get(a.id)??999)-(rank.get(b.id)??999));for(const home of ordered){if(used.has(home.id))continue;const ha=snap.associations.find(a=>a.id===home.associationId),candidates=ordered.filter(x=>x.id!==home.id&&!used.has(x.id));candidates.sort((a,b)=>{const aa=snap.associations.find(x=>x.id===a.associationId),sameA=aa?.confederationId===ha?.confederationId?0:1,ab=snap.associations.find(x=>x.id===b.associationId),sameB=ab?.confederationId===ha?.confederationId?0:1;return sameA-sameB+Math.abs((rank.get(a.id)??999)-(rank.get(home.id)??999))*.001-Math.abs((rank.get(b.id)??999)-(rank.get(home.id)??999))*.001});const away=candidates[0];if(!away)continue;used.add(home.id);used.add(away.id);pairs.push([home.id,away.id]);if(pairs.length>=12)break}return pairs}
function playWindowFriendlies(w:World,date:string){const win=activeInternationalWindow(w,date),s=state(w);if(!win||s.playedFriendlyWindows.has(win.id)||date!==win.start)return{played:0,skipped:0};const excluded=teamsReservedForWindow(w,win.start,win.end);let played=0,skipped=0;for(const [homeId,awayId] of friendlyPairs(w,excluded)){const hc=countryOf(w,homeId),ac=countryOf(w,awayId);if(!hc||!ac){skipped++;continue}const home=selectNationalSquad(w,{teamId:homeId,countryId:hc,date,size:26,competitionId:'international-friendly'}),away=selectNationalSquad(w,{teamId:awayId,countryId:ac,date,size:26,competitionId:'international-friendly'});if(home.members.length<11||away.members.length<11){skipped++;continue}simulateInternationalMatch(w,{home,away,date,competitionId:'international-friendly',importance:'friendly'});played++}s.playedFriendlyWindows.add(win.id);if(played)queueWorldEvent(w,{date,type:'InternationalFriendlyRound',scope:'world',entityIds:[],importance:2,payload:{windowId:win.id,matches:played,excludedCompetitiveTeams:excluded.size}});return{played,skipped}}
export function tickInternationalMatches(w:World,date=worldCore(w).date):InternationalDailyResult{const s=state(w),due=qualifierDue(w,date);let qualifierMatchdays=0,qualifierMatches=0;if(!s.processedQualifierDates.has(date)){for(const row of due){const r=playQualifierMatchday(w,row.competitionId,row.matchday,date);qualifierMatchdays++;qualifierMatches+=r.fixtures}s.processedQualifierDates.add(date)}const fr=playWindowFriendlies(w,date);return{date,qualifierMatchdays,qualifierMatches,friendlies:fr.played,skippedFriendlies:fr.skipped}}
export type InternationalDailyRuntimeSnapshot={playedFriendlyWindows:string[];processedQualifierDates:string[]};export function snapshotInternationalDailyRuntime(w:World):InternationalDailyRuntimeSnapshot{const s=state(w);return{playedFriendlyWindows:[...s.playedFriendlyWindows],processedQualifierDates:[...s.processedQualifierDates]}}export function restoreInternationalDailyRuntime(w:World,x:InternationalDailyRuntimeSnapshot){states.set(w,{playedFriendlyWindows:new Set(x?.playedFriendlyWindows??[]),processedQualifierDates:new Set(x?.processedQualifierDates??[])})}
