import type { World } from './engine';
import { activeInternationalWindow } from './international-calendar-v1';
import { assignInternationalDuty, dutiesForWindow, reportForInternationalDuty } from './international-duty-v1';
import { selectNationalSquad, type NationalSquad } from './national-team-selection-v1';
import { playerProfile } from './player-profile-v2';
import { isUnavailable } from './injuries';
import { queueWorldEvent, worldCore } from './world-core-v2';

type State={replaced:Set<string>};const states=new WeakMap<World,State>();function state(w:World){let s=states.get(w);if(!s){s={replaced:new Set()};states.set(w,s)}return s}
function emptySquad(teamId:string,countryId:string,date:string,member:any):NationalSquad{return{teamId,countryId,date,members:[member],reserves:[],averageAbility:0,averageAge:0}}
export function processInternationalReplacements(w:World,date=worldCore(w).date){const win=activeInternationalWindow(w,date);if(!win)return{replacements:0};const duties=dutiesForWindow(w,win.id),s=state(w);let replacements=0;for(const withdrawn of duties.filter(d=>d.status==='withdrawn'&&d.injured)){const key=`${win.id}:${withdrawn.playerId}`;if(s.replaced.has(key))continue;const currentIds=new Set(duties.filter(d=>d.teamId===withdrawn.teamId&&d.status!=='withdrawn').map(d=>d.playerId)),squad=selectNationalSquad(w,{teamId:withdrawn.teamId,countryId:withdrawn.countryId,date,size:26,reserveSize:12}),candidate=[...squad.members,...squad.reserves].find(m=>!currentIds.has(m.playerId)&&m.playerId!==withdrawn.playerId&&!isUnavailable(w,m.playerId)&&playerProfile(w,m.playerId)?.eligibility.some(e=>e.countryId===withdrawn.countryId&&e.eligible));if(candidate){const assigned=assignInternationalDuty(w,emptySquad(withdrawn.teamId,withdrawn.countryId,date,{...candidate,status:'selected'}),win,()=>({km:withdrawn.travelKm,timezoneShift:withdrawn.timezoneShift}));const d=assigned.find(x=>x.playerId===candidate.playerId);if(d)reportForInternationalDuty(w,d.playerId,win.id);queueWorldEvent(w,{date,type:'InternationalReplacementCalled',scope:'person',entityIds:[candidate.playerId,candidate.clubId,withdrawn.teamId],importance:3,payload:{replacedPlayerId:withdrawn.playerId,windowId:win.id}});replacements++}s.replaced.add(key)}return{replacements}}
export type InternationalReplacementSnapshot={replaced:string[]};export function snapshotInternationalReplacements(w:World):InternationalReplacementSnapshot{return{replaced:[...state(w).replaced]}}export function restoreInternationalReplacements(w:World,x:InternationalReplacementSnapshot){states.set(w,{replaced:new Set(x?.replaced??[])})}
