import type { Player, World } from './engine';
import type { NationalSquad } from './national-team-selection-v1';
import type { InternationalWindow } from './international-calendar-v1';
import { effectiveReadiness, recordMatchExposure } from './player-match-state-v2';
import { playerProfile } from './player-profile-v2';
export type DutyStatus='called'|'reported'|'withTeam'|'released'|'withdrawn';
export type InternationalDuty={playerId:string;clubId:string;teamId:string;countryId:string;windowId:string;reportDate:string;releaseDate:string;status:DutyStatus;travelKm:number;timezoneShift:number;minutes:number;matches:number;injured:boolean;withdrawalReason?:string};
type State={duties:Map<string,InternationalDuty>};const states=new WeakMap<World,State>();function state(w:World){let s=states.get(w);if(!s){s={duties:new Map()};states.set(w,s)}return s}const key=(p:string,w:string)=>`${p}:${w}`;
export function assignInternationalDuty(w:World,squad:NationalSquad,window:InternationalWindow,travel:(p:Player)=>{km:number;timezoneShift:number}={km:0,timezoneShift:0} as any){const s=state(w);for(const m of squad.members){const p=w.clubs.flatMap(c=>c.players).find(x=>x.id===m.playerId);if(!p)continue;const t=travel(p);s.duties.set(key(p.id,window.id),{playerId:p.id,clubId:p.clubId,teamId:squad.teamId,countryId:squad.countryId,windowId:window.id,reportDate:window.start,releaseDate:window.end,status:'called',travelKm:t.km,timezoneShift:t.timezoneShift,minutes:0,matches:0,injured:false})}return dutiesForWindow(w,window.id)}
export function dutiesForWindow(w:World,windowId:string){return[...state(w).duties.values()].filter(x=>x.windowId===windowId)}
export function dutyForPlayer(w:World,playerId:string,windowId?:string){return[...state(w).duties.values()].filter(x=>x.playerId===playerId&&(!windowId||x.windowId===windowId)).sort((a,b)=>b.reportDate.localeCompare(a.reportDate))[0]}
export function reportForInternationalDuty(w:World,playerId:string,windowId:string){const d=state(w).duties.get(key(playerId,windowId));if(d)d.status='withTeam';return d}
export function recordInternationalMinutes(w:World,playerId:string,windowId:string,minutes:number,rating=6.5,date?:string){const d=state(w).duties.get(key(playerId,windowId));if(!d)return;const p=w.clubs.flatMap(c=>c.players).find(x=>x.id===playerId);if(!p)return;d.minutes+=minutes;d.matches++;recordMatchExposure(w,p,minutes,rating,date);return d}
export function withdrawFromInternationalDuty(w:World,playerId:string,windowId:string,reason:string,injured=false){const d=state(w).duties.get(key(playerId,windowId));if(!d)return;d.status='withdrawn';d.withdrawalReason=reason;d.injured=injured;return d}
export function releaseFromInternationalDuty(w:World,playerId:string,windowId:string){const d=state(w).duties.get(key(playerId,windowId));if(d)d.status='released';return d}
export function postInternationalReadiness(w:World,playerId:string,windowId:string){const d=dutyForPlayer(w,playerId,windowId),p=w.clubs.flatMap(c=>c.players).find(x=>x.id===playerId);if(!d||!p)return;const r=effectiveReadiness(w,p),travelPenalty=Math.min(12,d.travelKm/1800)+Math.min(8,Math.abs(d.timezoneShift)*1.2),loadPenalty=Math.min(18,d.minutes/18),hidden=playerProfile(w,playerId)?.hidden.adaptability??50;return{...r,internationalLoad:Number((travelPenalty+loadPenalty).toFixed(1)),returnReadiness:Number(Math.max(0,r.overall-travelPenalty-loadPenalty+(hidden-50)*.04).toFixed(1))}}
export function playerUnavailableForClub(w:World,playerId:string,date:string){return[...state(w).duties.values()].some(d=>d.playerId===playerId&&d.status!=='withdrawn'&&d.status!=='released'&&date>=d.reportDate&&date<=d.releaseDate)}
export type InternationalDutySnapshot={duties:[string,InternationalDuty][]};export function snapshotInternationalDuty(w:World):InternationalDutySnapshot{return{duties:[...state(w).duties.entries()].map(([k,v])=>[k,{...v}])}}export function restoreInternationalDuty(w:World,x:InternationalDutySnapshot){states.set(w,{duties:new Map((x?.duties??[]).map(([k,v])=>[k,{...v}]))})}
