import type { World } from './engine';
import { buildNextKnockoutRound, createFinalsTournament, finalizeFinals, finalsFormats, playFinalsFixture, snapshotInternationalFinals, restoreInternationalFinals, type FinalsState } from './international-finals-v1';
import { assignTournamentVenues, chooseHostBid, type VenueAssignment } from './international-hosting-v1';
import { footballDataSnapshot, registerMembership, registerTitle } from './world-football-data-v1';
import { queueWorldEvent } from './world-core-v2';

type Runtime={venues:Map<string,VenueAssignment>;processedDates:Set<string>;seeded:Set<string>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={venues:new Map(),processedDates:new Set(),seeded:new Set()};states.set(w,s)}return s}
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
function participantIds(w:World,competitionId:string,year:number){return [...new Set(footballDataSnapshot(w).memberships.filter(m=>m.competitionId===competitionId&&m.season===String(year)&&['qualified','participant'].includes(m.status)&&m.teamKind==='national').map(m=>m.teamId))]}
function defaultHostCandidates(w:World){const snap=footballDataSnapshot(w),by=new Map<string,number>();for(const s of snap.stadiums)if((s.capacity??0)>=30000)by.set(s.countryId,(by.get(s.countryId)??0)+1);return [...by.entries()].sort((a,b)=>b[1]-a[1]).slice(0,12).map(([id])=>[id])}
function startDate(kind:string,year:number){return kind==='worldCup'?`${year}-06-08`:kind==='euro'?`${year}-06-12`:`${year}-06-15`}
export function seedFinalsForYear(w:World,year:number,hostOverrides:Partial<Record<'worldCup'|'copaAmerica'|'euro',string[]>>={}){const s=state(w),created:FinalsState[]=[];for(const format of finalsFormats(year)){const key=`${format.competitionId}-${year}`;if(s.seeded.has(key))continue;const teams=participantIds(w,format.competitionId,year);if(teams.length<format.teams)continue;const override=hostOverrides[format.kind],host=override?.length?override:chooseHostBid(w,defaultHostCandidates(w))?.countryIds??[];if(!host.length)continue;const t=createFinalsTournament(w,{year,format,teamIds:teams,hostCountryIds:host,startDate:startDate(format.kind,year)}),assignments=assignTournamentVenues(w,t.fixtures.map(f=>f.id),host,format.kind==='worldCup'?40000:30000);for(const a of assignments)s.venues.set(`${t.id}:${a.fixtureId}`,a);s.seeded.add(key);created.push(t)}return created}
function currentStage(t:FinalsState){const pending=t.fixtures.filter(f=>!f.played).sort((a,b)=>a.date.localeCompare(b.date));return pending[0]?.stage}
function assignNewVenues(w:World,t:FinalsState,fixtureIds:string[]){const s=state(w),rows=assignTournamentVenues(w,fixtureIds,t.hostCountryIds,t.format.kind==='worldCup'?40000:30000);for(const a of rows)s.venues.set(`${t.id}:${a.fixtureId}`,a)}
function maybeAdvanceBracket(w:World,t:FinalsState,date:string){if(t.completed)return;const pending=t.fixtures.filter(f=>!f.played);if(pending.length)return;const finals=t.fixtures.filter(f=>f.stage==='final');if(finals.length&&finals.every(f=>f.played)){finalizeFinals(w,t,date);if(t.championTeamId){registerTitle(w,{id:`title-${t.format.competitionId}-${t.year}-${t.championTeamId}`,teamId:t.championTeamId,teamKind:'national',competitionId:t.format.competitionId,season:String(t.year),date,source:'simulated',provenance:[{sourceId:'international-finals-runtime-v1',historical:false,confidence:100}]});registerMembership(w,{season:String(t.year),competitionId:t.format.competitionId,teamId:t.championTeamId,teamKind:'national',status:'champion',source:'simulated',provenance:[{sourceId:'international-finals-runtime-v1',historical:false,confidence:100}]})}return}
 const last=t.fixtures.map(f=>f.date).sort().at(-1)??date,newFixtures=buildNextKnockoutRound(t,add(last,3));assignNewVenues(w,t,newFixtures.map(f=>f.id));if(newFixtures.length)queueWorldEvent(w,{date,type:'InternationalKnockoutRoundDrawn',scope:'competition',entityIds:newFixtures.flatMap(f=>[f.homeTeamId,f.awayTeamId]),importance:6,payload:{tournamentId:t.id,stage:newFixtures[0].stage,fixtures:newFixtures.length}})}
export function tickInternationalFinals(w:World,date:string){const s=state(w);if(s.processedDates.has(date))return{date,matches:0,tournaments:0};s.processedDates.add(date);seedFinalsForYear(w,Number(date.slice(0,4)));let matches=0,tournaments=0;for(const t of snapshotInternationalFinals(w).tournaments.map(x=>x[1]).filter(t=>!t.completed)){const live=(snapshotInternationalFinals(w).tournaments.find(x=>x[0]===t.id)?.[1])!;const due=live.fixtures.filter(f=>!f.played&&f.date===date);if(!due.length)continue;tournaments++;for(const f of due){playFinalsFixture(w,live,f);matches++}maybeAdvanceBracket(w,live,date);const snap=snapshotInternationalFinals(w);const all=new Map(snap.tournaments);all.set(live.id,live);restoreInternationalFinals(w,{tournaments:[...all]})}return{date,matches,tournaments}}
export function finalsVenue(w:World,tournamentId:string,fixtureId:string){return state(w).venues.get(`${tournamentId}:${fixtureId}`)}
export type InternationalFinalsRuntimeSnapshot={finals:ReturnType<typeof snapshotInternationalFinals>;venues:[string,VenueAssignment][];processedDates:string[];seeded:string[]};
export function snapshotInternationalFinalsRuntime(w:World):InternationalFinalsRuntimeSnapshot{const s=state(w);return{finals:snapshotInternationalFinals(w),venues:[...s.venues.entries()].map(([k,v])=>[k,{...v}]),processedDates:[...s.processedDates],seeded:[...s.seeded]}}
export function restoreInternationalFinalsRuntime(w:World,x:InternationalFinalsRuntimeSnapshot){restoreInternationalFinals(w,x?.finals??{tournaments:[]});states.set(w,{venues:new Map((x?.venues??[]).map(([k,v])=>[k,{...v}])),processedDates:new Set(x?.processedDates??[]),seeded:new Set(x?.seeded??[])})}
