import type { Club, Player, Tactics, World } from './engine';
import { createMatchCore } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { matchEventLedger } from './match-event-ledger-v2';
import { matchInjuries, type MatchInjury } from './match-contact-injury-v2';
import { playerMatchPerformances } from './match-player-performance-v2';
import { footballDataSnapshot, registerHistoricalMatch } from './world-football-data-v1';
import { recordInternationalResult, type InternationalMatchImportance } from './national-team-ranking-v1';
import { recordSeniorInternationalAppearance, type NationalSquad } from './national-team-selection-v1';
import { dutyForPlayer, recordInternationalMinutes } from './international-duty-v1';
import { inflictInjury, injuryDefinitions } from './injuries';
import { queueWorldEvent, worldCore } from './world-core-v2';

export type InternationalMatchResult={id:string;date:string;competitionId:string;homeTeamId:string;awayTeamId:string;homeGoals:number;awayGoals:number;homeXg:number;awayXg:number;neutral:boolean;importance:InternationalMatchImportance;state:any;goals:Array<{playerId?:string;clubId?:string;minute:number}>;injuries:number};
const tactics:Tactics={mentality:'balanced',tempo:50,pressing:50,defensiveLine:50,width:50,passingStyle:'mixed',transition:'balanced'};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function hash(text:string){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function sourcePlayer(w:World,id:string){for(const c of w.clubs){const p=c.players.find(x=>x.id===id);if(p)return p}}
function teamName(w:World,teamId:string){return footballDataSnapshot(w).nationalTeams.find(x=>x.id===teamId)?.name??teamId}
function asNationalClub(w:World,squad:NationalSquad):Club{const players=squad.members.map(m=>sourcePlayer(w,m.playerId)).filter(Boolean).map(p=>({...p!,clubId:squad.teamId,attributes:{...p!.attributes}}));return{id:squad.teamId,name:teamName(w,squad.teamId),reputation:70,players,tactics:{...tactics}}}
function injuryDefinition(i:MatchInjury){const by=(id:string)=>injuryDefinitions.find(x=>x.id===id)!;if(i.concussion||i.mechanism==='head')return by('concussion');if(i.mechanism==='shoulder')return i.severity==='knock'?by('bruise'):by('shoulder-dislocation');if(i.mechanism==='ankle')return by('ankle-sprain');if(i.mechanism==='knee')return i.severity==='severe'?by('knee-acl'):by('knee-mcl');if(i.mechanism==='lowerLeg')return i.severity==='severe'?by('tibia-fracture'):i.severity==='moderate'?by('fibula-fracture'):by('calf-strain');if(i.mechanism==='hip')return by('hip-flexor');if(i.mechanism==='muscle'||i.mechanism==='thigh')return i.severity==='knock'?by('bruise'):by('hamstring-strain');return by('bruise')}
function persistInternationalInjuries(w:World,state:any){let count=0;for(const i of matchInjuries(state)){if(i.severity==='knock')continue;const p=sourcePlayer(w,i.playerId);if(!p)continue;const ev=inflictInjury(w,p,injuryDefinition(i),i.source==='foul'||i.source==='duel'?'contact':'match');ev.notes.push(`Lesão em partida internacional: ${state.home.clubId} x ${state.away.clubId}, minuto ${Math.floor(i.second/60)}.`);count++}return count}
function importanceFor(competitionId:string,explicit?:InternationalMatchImportance):InternationalMatchImportance{if(explicit)return explicit;if(competitionId==='comp-fifa-world-cup')return'worldCup';if(competitionId.startsWith('qual-'))return'qualifier';if(['comp-conmebol-copa-america','comp-uefa-euro'].includes(competitionId))return'continentalFinals';return'friendly'}
function recordCapsAndLoad(w:World,state:any,home:NationalSquad,away:NationalSquad,date:string,competitive:boolean){const perf=playerMatchPerformances(state,asNationalClub(w,home),asNationalClub(w,away));for(const row of perf){if(row.minutes<=0)continue;const countryId=row.clubId===home.teamId?home.countryId:away.countryId;recordSeniorInternationalAppearance(w,row.playerId,countryId,date,competitive);const duty=dutyForPlayer(w,row.playerId);if(duty)recordInternationalMinutes(w,row.playerId,duty.windowId,row.minutes,row.rating,date)}}
export function simulateInternationalMatch(w:World,input:{home:NationalSquad;away:NationalSquad;date?:string;competitionId?:string;neutral?:boolean;importance?:InternationalMatchImportance;stage?:string;round?:string}) : InternationalMatchResult {const date=input.date??worldCore(w).date,competitionId=input.competitionId??'international-friendly',importance=importanceFor(competitionId,input.importance),homeClub=asNationalClub(w,input.home),awayClub=asNationalClub(w,input.away);if(homeClub.players.length<11||awayClub.players.length<11)throw new Error('International match requires at least 11 selected players per team.');const id=`intl-${date}-${input.home.teamId}-${input.away.teamId}-${competitionId}`,seed=hash(`${worldCore(w).seed}:${id}`),state=createMatchCore(homeClub,awayClub,{seed});simulateMatchCore(state,homeClub,awayClub);const competitive=importance!=='friendly';recordCapsAndLoad(w,state,input.home,input.away,date,competitive);const injuries=persistInternationalInjuries(w,state);recordInternationalResult(w,{homeTeamId:input.home.teamId,awayTeamId:input.away.teamId,homeGoals:state.home.score,awayGoals:state.away.score,date,importance,neutral:input.neutral});registerHistoricalMatch(w,{id,date,competitionId,season:String(Number(date.slice(0,4))),homeTeamId:input.home.teamId,awayTeamId:input.away.teamId,homeGoals:state.home.score,awayGoals:state.away.score,stage:input.stage,round:input.round,source:'simulated',provenance:[{sourceId:'match-engine-v2',historical:false,confidence:100}]});const goals=matchEventLedger(state).filter(x=>x.type==='goal'||x.type==='physicalGoal').map(x=>({playerId:x.playerId,clubId:x.clubId,minute:Math.floor(x.second/60)}));queueWorldEvent(w,{date,type:'InternationalMatchCompleted',scope:'competition',entityIds:[competitionId,input.home.teamId,input.away.teamId],importance:importance==='worldCup'?8:importance==='continentalFinals'?7:importance==='qualifier'?5:2,payload:{homeGoals:state.home.score,awayGoals:state.away.score,neutral:!!input.neutral,goals:goals.length,injuries}});return{id,date,competitionId,homeTeamId:input.home.teamId,awayTeamId:input.away.teamId,homeGoals:state.home.score,awayGoals:state.away.score,homeXg:Number(state.home.xg.toFixed(2)),awayXg:Number(state.away.xg.toFixed(2)),neutral:!!input.neutral,importance,state,goals,injuries}}
