import type { World } from './engine';
import { footballDataSnapshot, registerCompetitionRecord, alias, type ConfederationId } from './world-football-data-v1';
import { rankingByConfederation } from './national-team-ranking-v1';
export type QualifierFormat='league'|'groups'|'groups-playoff'|'knockout';
export type QualifierConfig={id:string;name:string;confederationId:ConfederationId;targetCompetitionId:string;cycleYear:number;format:QualifierFormat;directSlots:number;playoffSlots:number;groupCount?:number;groupSize?:number;legs:1|2};
export type QualifierGroup={id:string;teams:string[]};
export type QualifierFixture={id:string;competitionId:string;groupId?:string;homeTeamId:string;awayTeamId:string;matchday:number;leg:1|2;played:boolean;homeGoals?:number;awayGoals?:number};
export type QualificationState={config:QualifierConfig;groups:QualifierGroup[];fixtures:QualifierFixture[];qualifiedTeamIds:string[];playoffTeamIds:string[]};
const defaultConfigs=(year:number):QualifierConfig[]=>[
{id:`qual-conmebol-wc-${year}`,name:`CONMEBOL World Cup Qualifiers ${year}`,confederationId:'CONMEBOL',targetCompetitionId:'comp-fifa-world-cup',cycleYear:year,format:'league',directSlots:6,playoffSlots:1,legs:2},
{id:`qual-uefa-wc-${year}`,name:`UEFA World Cup Qualifiers ${year}`,confederationId:'UEFA',targetCompetitionId:'comp-fifa-world-cup',cycleYear:year,format:'groups-playoff',directSlots:12,playoffSlots:4,groupCount:12,legs:2},
{id:`qual-afc-wc-${year}`,name:`AFC World Cup Qualifiers ${year}`,confederationId:'AFC',targetCompetitionId:'comp-fifa-world-cup',cycleYear:year,format:'groups-playoff',directSlots:8,playoffSlots:1,groupCount:3,legs:2},
{id:`qual-caf-wc-${year}`,name:`CAF World Cup Qualifiers ${year}`,confederationId:'CAF',targetCompetitionId:'comp-fifa-world-cup',cycleYear:year,format:'groups-playoff',directSlots:9,playoffSlots:1,groupCount:9,legs:2},
{id:`qual-concacaf-wc-${year}`,name:`CONCACAF World Cup Qualifiers ${year}`,confederationId:'CONCACAF',targetCompetitionId:'comp-fifa-world-cup',cycleYear:year,format:'groups-playoff',directSlots:3,playoffSlots:2,groupCount:3,legs:2},
{id:`qual-ofc-wc-${year}`,name:`OFC World Cup Qualifiers ${year}`,confederationId:'OFC',targetCompetitionId:'comp-fifa-world-cup',cycleYear:year,format:'groups-playoff',directSlots:1,playoffSlots:1,groupCount:2,legs:1}
];
function seededTeams(w:World,confed:string){const snap=footballDataSnapshot(w),active=new Set(snap.nationalTeams.filter(x=>x.active).map(x=>x.id)),ranked=rankingByConfederation(w,confed).filter(x=>active.has(x.teamId)).map(x=>x.teamId);const rest=snap.nationalTeams.filter(t=>t.active&&snap.associations.find(a=>a.id===t.associationId)?.confederationId===confed&&!ranked.includes(t.id)).map(t=>t.id);return[...ranked,...rest]}
function snakeGroups(teams:string[],count:number){const groups:Array<string[]> = Array.from({length:Math.max(1,count)},()=>[]);let dir=1,index=0;for(const t of teams){groups[index].push(t);if(dir===1&&index===groups.length-1)dir=-1;else if(dir===-1&&index===0)dir=1;else index+=dir}return groups}
function roundRobin(competitionId:string,groupId:string|undefined,teams:string[],legs:1|2){const list=[...teams];if(list.length%2)list.push('__BYE__');const n=list.length,rounds=n-1,fixtures:QualifierFixture[]=[];let arr=[...list];for(let r=0;r<rounds;r++){for(let i=0;i<n/2;i++){const a=arr[i],b=arr[n-1-i];if(a==='__BYE__'||b==='__BYE__')continue;const firstHome=r%2===0?a:b,firstAway=r%2===0?b:a;fixtures.push({id:`${competitionId}-${groupId??'league'}-md${r+1}-${i+1}-1`,competitionId,groupId,homeTeamId:firstHome,awayTeamId:firstAway,matchday:r+1,leg:1,played:false});if(legs===2)fixtures.push({id:`${competitionId}-${groupId??'league'}-md${r+1+rounds}-${i+1}-2`,competitionId,groupId,homeTeamId:firstAway,awayTeamId:firstHome,matchday:r+1+rounds,leg:2,played:false})}arr=[arr[0],arr[n-1],...arr.slice(1,n-1)]}return fixtures}
export function createQualificationState(w:World,config:QualifierConfig):QualificationState{const teams=seededTeams(w,config.confederationId);const groupCount=config.format==='league'?1:Math.max(1,config.groupCount??1),groups=snakeGroups(teams,groupCount).map((x,i)=>({id:`${config.id}-g${i+1}`,teams:x})),fixtures=groups.flatMap(g=>roundRobin(config.id,groupCount===1?undefined:g.id,g.teams,config.legs));return{config,groups,fixtures,qualifiedTeamIds:[],playoffTeamIds:[]}}
export function seedWorldCupQualifierCompetitions(w:World,cycleYear:number){const configs=defaultConfigs(cycleYear);for(const c of configs)registerCompetitionRecord(w,{id:c.id,name:c.name,aliases:[alias(`${c.confederationId} qualifiers ${cycleYear}`)],scope:'continental',kind:'qualifier',confederationId:c.confederationId,active:true,validFrom:String(cycleYear-3),validTo:String(cycleYear),rules:{pointsWin:3,pointsDraw:1,legs:c.legs,tiebreakers:['points','goalDifference','goalsFor','headToHead'],promotion:[],relegation:[],qualification:[{toCompetitionId:c.targetCompetitionId,slots:c.directSlots,fromRank:1,toRank:c.directSlots}],calendarPattern:c.confederationId==='UEFA'?'cross-year':'calendar-year',usesPlayoffs:c.playoffSlots>0},provenance:[{sourceId:'football-project-qualifier-model',historical:false,confidence:80}]});return configs}
export function worldCupQualifierConfigs(year:number){return defaultConfigs(year).map(x=>({...x}))}
