import type { World } from './engine';
import { activeInternationalWindow, internationalWindowsForYear } from './international-calendar-v1';
import { assignInternationalDuty, playerUnavailableForClub, postInternationalReadiness, recordInternationalMinutes, reportForInternationalDuty, releaseFromInternationalDuty } from './international-duty-v1';
import { selectNationalSquad } from './national-team-selection-v1';
import { worldCore } from './world-core-v2';

export function runInternationalCalendarDiagnostics(world:World){const issues:string[]=[];const year=Number(worldCore(world).date.slice(0,4)),windows=internationalWindowsForYear(year);if(windows.length<5)issues.push('menos de cinco janelas internacionais anuais');for(const w of windows)if(w.end<w.start)issues.push(`janela inválida: ${w.id}`);for(let i=1;i<windows.length;i++)if(windows[i].start<windows[i-1].start)issues.push('janelas fora de ordem');
const brazil=world.clubs.flatMap(c=>c.players).filter(p=>{const pr=(require('./player-profile-v2') as typeof import('./player-profile-v2')).playerProfile(world,p.id);return pr?.eligibility.some(e=>e.countryId==='BRA'&&e.eligible)});if(brazil.length){const date=windows[0]?.start,squad=selectNationalSquad(world,{teamId:'nt-bra-men-senior',countryId:'BRA',date,size:Math.min(26,brazil.length)});if(!squad.members.length)issues.push('convocação brasileira vazia com jogadores elegíveis');if(date&&squad.members.length){const win=windows[0],duties=assignInternationalDuty(world,squad,win,()=>({km:7000,timezoneShift:4})),first=duties[0];if(first){reportForInternationalDuty(world,first.playerId,win.id);if(!playerUnavailableForClub(world,first.playerId,win.start))issues.push('jogador convocado permaneceu disponível ao clube');recordInternationalMinutes(world,first.playerId,win.id,90,7.2,win.start);releaseFromInternationalDuty(world,first.playerId,win.id);if(playerUnavailableForClub(world,first.playerId,win.end))issues.push('jogador liberado continuou indisponível ao clube');const readiness=postInternationalReadiness(world,first.playerId,win.id);if(!readiness||readiness.internationalLoad<=0)issues.push('carga internacional não afetou readiness')}}}
return{ok:issues.length===0,issues,year,windows:windows.length,active:activeInternationalWindow(world)?.id}}
