import type { World } from './engine';
import { footballDataSnapshot, registerHistoricalMatch, registerMembership } from './world-football-data-v1';
import { nationalRankingTable } from './national-team-ranking-v1';
import { selectNationalSquad } from './national-team-selection-v1';
import { simulateInternationalMatch } from './international-match-engine-v1';
import { queueWorldEvent } from './world-core-v2';

export type FinalsKind='worldCup'|'copaAmerica'|'euro';
export type FinalsFormat={competitionId:string;kind:FinalsKind;teams:number;groups:number;groupSize:number;advancePerGroup:number;bestThird:number;squadSize:number};
export type FinalsFixture={id:string;stage:'group'|'r32'|'r16'|'qf'|'sf'|'third'|'final';groupId?:string;date:string;homeTeamId:string;awayTeamId:string;homeGoals?:number;awayGoals?:number;extraTime?:boolean;penalties?:{home:number;away:number};played:boolean};
export type FinalsGroup={id:string;teams:string[]};
export type FinalsState={id:string;year:number;hostCountryIds:string[];format:FinalsFormat;teams:string[];groups:FinalsGroup[];fixtures:FinalsFixture[];championTeamId?:string;runnerUpTeamId?:string;thirdTeamId?:string;completed:boolean};
type Runtime={tournaments:Map<string,FinalsState>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={tournaments:new Map()};states.set(w,s)}return s}
const add=(iso:string,n:number)=>{const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
export function finalsFormats(year:number):FinalsFormat[]{return[{competitionId:'comp-fifa-world-cup',kind:'worldCup',teams:48,groups:12,groupSize:4,advancePerGroup:2,bestThird:8,squadSize:26},{competitionId:'comp-conmebol-copa-america',kind:'copaAmerica',teams:16,groups:4,groupSize:4,advancePerGroup:2,bestThird:0,squadSize:26},{competitionId:'comp-uefa-euro',kind:'euro',teams:24,groups:6,groupSize:4,advancePerGroup:2,bestThird:4,squadSize:26}]}
function seeded(w:World,ids:string[]){const rank=new Map(nationalRankingTable(w).map(x=>[x.teamId,x.rank]));return [...ids].sort((a,b)=>(rank.get(a)??999)-(rank.get(b)??999))}
function drawGroups(w:World,teams:string[],format:FinalsFormat){const order=seeded(w,teams),groups:Array<FinalsGroup>=Array.from({length:format.groups},(_,i)=>({id:String.fromCharCode(65+i),teams:[]}));for(let i=0;i<order.length;i++){const pot=Math.floor(i/format.groups),slot=i%format.groups,gi=pot%2===0?slot:format.groups-1-slot;groups[gi].teams.push(order[i])}return groups}
function groupFixtures(groups:FinalsGroup[],start:string){const out:FinalsFixture[]=[];let day=0;for(const g of groups){for(let i=0;i<g.teams.length;i++)for(let j=i+1;j<g.teams.length;j++){out.push({id:`g-${g.id}-${i}-${j}`,stage:'group',groupId:g.id,date:add(start,day++%12),homeTeamId:g.teams[i],awayTeamId:g.teams[j],played:false})}}return out}
export function createFinalsTournament(w:World,input:{year:number;format:FinalsFormat;teamIds:string[];hostCountryIds:string[];startDate:string}){const teams=seeded(w,input.teamIds).slice(0,input.format.teams);if(teams.length<input.format.teams)throw new Error(`Insufficient qualified teams for ${input.format.competitionId}: ${teams.length}/${input.format.teams}`);const id=`${input.format.competitionId}-${input.year}`,groups=drawGroups(w,teams,input.format),t:FinalsState={id,year:input.year,hostCountryIds:[...input.hostCountryIds],format:{...input.format},teams,groups,fixtures:groupFixtures(groups,input.startDate),completed:false};state(w).tournaments.set(id,t);for(const teamId of teams)registerMembership(w,{season:String(input.year),competitionId:input.format.competitionId,teamId,teamKind:'national',status:'qualified',source:'simulated',provenance:[{sourceId:'international-finals-v1',historical:false,confidence:100}]});queueWorldEvent(w,{date:input.startDate,type:'InternationalFinalsDraw',scope:'competition',entityIds:teams,importance:7,payload:{tournamentId:id,hosts:input.hostCountryIds,groups}});return t}
export function finalsTournament(w:World,id:string){return state(w).tournaments.get(id)}
export function finalsStandings(t:FinalsState,groupId:string){const teams=t.groups.find(g=>g.id===groupId)?.teams??[],tab=new Map(teams.map(id=>[id,{teamId:id,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0}]));for(const f of t.fixtures.filter(x=>x.stage==='group'&&x.groupId===groupId&&x.played)){const h=tab.get(f.homeTeamId)!,a=tab.get(f.awayTeamId)!,hg=f.homeGoals??0,ag=f.awayGoals??0;h.p++;a.p++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.w++;a.l++;h.pts+=3}else if(ag>hg){a.w++;h.l++;a.pts+=3}else{h.d++;a.d++;h.pts++;a.pts++}}for(const x of tab.values())x.gd=x.gf-x.ga;return [...tab.values()].sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.teamId.localeCompare(b.teamId))}
function country(w:World,teamId:string){return footballDataSnapshot(w).nationalTeams.find(t=>t.id===teamId)?.countryId}
function shootoutSeed(id:string){let h=0;for(const c of id)h=(h*31+c.charCodeAt(0))>>>0;return h}
function resolveKnockout(f:FinalsFixture){if((f.homeGoals??0)!==(f.awayGoals??0))return;f.extraTime=true;const s=shootoutSeed(f.id),home=3+(s%3),away=3+((s>>>3)%3);f.penalties=home===away?{home:home+1,away}:{home,away};if(f.penalties.home===f.penalties.away)f.penalties.home++}
function winner(f:FinalsFixture){if((f.homeGoals??0)>(f.awayGoals??0))return f.homeTeamId;if((f.awayGoals??0)>(f.homeGoals??0))return f.awayTeamId;return (f.penalties?.home??0)>(f.penalties?.away??0)?f.homeTeamId:f.awayTeamId}
export function playFinalsFixture(w:World,t:FinalsState,f:FinalsFixture){if(f.played)return f;const hc=country(w,f.homeTeamId),ac=country(w,f.awayTeamId);if(!hc||!ac)throw new Error('Unknown national team in finals');const home=selectNationalSquad(w,{teamId:f.homeTeamId,countryId:hc,size:t.format.squadSize,competitionId:t.format.competitionId,date:f.date}),away=selectNationalSquad(w,{teamId:f.awayTeamId,countryId:ac,size:t.format.squadSize,competitionId:t.format.competitionId,date:f.date});if(home.members.length<11||away.members.length<11)throw new Error('Finals match requires 11 eligible players');const r=simulateInternationalMatch(w,{home,away,date:f.date,competitionId:t.format.competitionId,neutral:true,importance:t.format.kind==='worldCup'?'worldCup':'continentalFinals',stage:f.stage,round:f.groupId});f.homeGoals=r.homeGoals;f.awayGoals=r.awayGoals;f.played=true;if(f.stage!=='group')resolveKnockout(f);return f}
function qualifiedFromGroups(t:FinalsState){const direct:string[]=[],third:Array<{teamId:string;pts:number;gd:number;gf:number}>=[];for(const g of t.groups){const table=finalsStandings(t,g.id);direct.push(...table.slice(0,t.format.advancePerGroup).map(x=>x.teamId));if(table[t.format.advancePerGroup])third.push(table[t.format.advancePerGroup])}third.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf);return [...direct,...third.slice(0,t.format.bestThird).map(x=>x.teamId)]}
function stageForCount(n:number):FinalsFixture['stage']{return n>16?'r32':n>8?'r16':n>4?'qf':n>2?'sf':'final'}
export function buildNextKnockoutRound(t:FinalsState,startDate:string){let entrants:string[];const knockout=t.fixtures.filter(f=>f.stage!=='group');if(!knockout.length){if(t.fixtures.some(f=>f.stage==='group'&&!f.played))throw new Error('Group stage incomplete');entrants=qualifiedFromGroups(t)}else{const lastStage=knockout[knockout.length-1].stage,last=t.fixtures.filter(f=>f.stage===lastStage);if(last.some(f=>!f.played))throw new Error('Knockout stage incomplete');entrants=last.map(winner)}if(entrants.length===1){t.championTeamId=entrants[0];t.completed=true;return []}const stage=stageForCount(entrants.length),fixtures:FinalsFixture[]=[];for(let i=0;i<entrants.length;i+=2)fixtures.push({id:`${stage}-${t.fixtures.length+i/2}`,stage,date:add(startDate,Math.floor(i/2)),homeTeamId:entrants[i],awayTeamId:entrants[i+1],played:false});t.fixtures.push(...fixtures);return fixtures}
export function finalizeFinals(w:World,t:FinalsState,date:string){const final=t.fixtures.find(f=>f.stage==='final'&&f.played);if(!final)return t;t.championTeamId=winner(final);t.runnerUpTeamId=t.championTeamId===final.homeTeamId?final.awayTeamId:final.homeTeamId;t.completed=true;queueWorldEvent(w,{date,type:'InternationalChampionCrowned',scope:'competition',entityIds:[t.championTeamId],importance:10,payload:{tournamentId:t.id,competitionId:t.format.competitionId,champion:t.championTeamId,runnerUp:t.runnerUpTeamId}});return t}
export type InternationalFinalsSnapshot={tournaments:[string,FinalsState][]};export function snapshotInternationalFinals(w:World):InternationalFinalsSnapshot{return{tournaments:[...state(w).tournaments].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}export function restoreInternationalFinals(w:World,x:InternationalFinalsSnapshot){states.set(w,{tournaments:new Map((x?.tournaments??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
