import type { World } from './engine';
import { createQualificationState, worldCupQualifierConfigs, type QualificationState, type QualifierFixture } from './international-qualifiers-v1';
import { selectNationalSquad } from './national-team-selection-v1';
import { simulateInternationalMatch } from './international-match-engine-v1';
import { footballDataSnapshot, registerMembership } from './world-football-data-v1';
import { worldCore } from './world-core-v2';

export type QualifierStanding={teamId:string;played:number;wins:number;draws:number;losses:number;gf:number;ga:number;gd:number;points:number};
export type QualifierRuntimeSnapshot={cycles:[string,QualificationState][]};
type Runtime={cycles:Map<string,QualificationState>};const states=new WeakMap<World,Runtime>();
function state(w:World){let s=states.get(w);if(!s){s={cycles:new Map()};states.set(w,s)}return s}
export function ensureQualifierCycle(w:World,cycleYear:number){const s=state(w);for(const config of worldCupQualifierConfigs(cycleYear))if(!s.cycles.has(config.id))s.cycles.set(config.id,createQualificationState(w,config));return[...s.cycles.values()].filter(x=>x.config.cycleYear===cycleYear)}
export function qualifierState(w:World,competitionId:string){return state(w).cycles.get(competitionId)}
export function qualifierStandings(q:QualificationState,groupId?:string){const teams=groupId?q.groups.find(g=>g.id===groupId)?.teams??[]:q.groups.flatMap(g=>g.teams),table=new Map<string,QualifierStanding>();for(const t of teams)table.set(t,{teamId:t,played:0,wins:0,draws:0,losses:0,gf:0,ga:0,gd:0,points:0});for(const f of q.fixtures.filter(x=>x.played&&(!groupId||x.groupId===groupId))){const h=table.get(f.homeTeamId),a=table.get(f.awayTeamId);if(!h||!a)continue;const hg=f.homeGoals??0,ag=f.awayGoals??0;h.played++;a.played++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.wins++;a.losses++;h.points+=3}else if(ag>hg){a.wins++;h.losses++;a.points+=3}else{h.draws++;a.draws++;h.points++;a.points++}}for(const x of table.values())x.gd=x.gf-x.ga;return[...table.values()].sort((a,b)=>b.points-a.points||b.gd-a.gd||b.gf-a.gf||a.teamId.localeCompare(b.teamId))}
function countryIdFor(w:World,teamId:string){return footballDataSnapshot(w).nationalTeams.find(t=>t.id===teamId)?.countryId}
function dateForMatchday(cycleYear:number,matchday:number){const dates=[`${cycleYear-2}-09-05`,`${cycleYear-2}-10-10`,`${cycleYear-2}-11-14`,`${cycleYear-1}-03-20`,`${cycleYear-1}-06-05`,`${cycleYear-1}-09-04`,`${cycleYear-1}-10-09`,`${cycleYear-1}-11-13`,`${cycleYear}-03-19`,`${cycleYear}-06-04`,`${cycleYear}-09-03`,`${cycleYear}-10-08`,`${cycleYear}-11-12`];return dates[Math.min(dates.length-1,Math.max(0,matchday-1))]}
export function playQualifierFixture(w:World,q:QualificationState,f:QualifierFixture,date?:string){if(f.played)return;const hc=countryIdFor(w,f.homeTeamId),ac=countryIdFor(w,f.awayTeamId);if(!hc||!ac)throw new Error(`Qualifier fixture references unknown national team: ${f.homeTeamId} vs ${f.awayTeamId}`);const d=date??dateForMatchday(q.config.cycleYear,f.matchday),home=selectNationalSquad(w,{teamId:f.homeTeamId,countryId:hc,size:26,competitionId:q.config.id,date:d}),away=selectNationalSquad(w,{teamId:f.awayTeamId,countryId:ac,size:26,competitionId:q.config.id,date:d});if(home.members.length<11||away.members.length<11)return{skipped:true,reason:'insufficient eligible players'};const result=simulateInternationalMatch(w,{home,away,date:d,competitionId:q.config.id,importance:'qualifier',round:String(f.matchday)});f.homeGoals=result.homeGoals;f.awayGoals=result.awayGoals;f.played=true;return{skipped:false,result}}
export function playQualifierMatchday(w:World,competitionId:string,matchday:number,date?:string){const q=qualifierState(w,competitionId);if(!q)throw new Error(`Unknown qualifier competition ${competitionId}`);const fixtures=q.fixtures.filter(f=>f.matchday===matchday&&!f.played),results=fixtures.map(f=>playQualifierFixture(w,q,f,date));if(q.fixtures.every(f=>f.played))finalizeQualification(w,q);return{competitionId,matchday,fixtures:fixtures.length,results,completed:q.fixtures.every(f=>f.played)}}
export function finalizeQualification(w:World,q:QualificationState){if(!q.fixtures.every(f=>f.played))return q;const direct:string[]=[],playoff:string[]=[];if(q.config.format==='league'){const table=qualifierStandings(q);direct.push(...table.slice(0,q.config.directSlots).map(x=>x.teamId));playoff.push(...table.slice(q.config.directSlots,q.config.directSlots+q.config.playoffSlots).map(x=>x.teamId))}else{const groupWinners:string[]=[],nextBest:string[]=[];for(const g of q.groups){const t=qualifierStandings(q,g.id);if(t[0])groupWinners.push(t[0].teamId);if(t[1])nextBest.push(t[1].teamId)}direct.push(...groupWinners.slice(0,q.config.directSlots));const remaining=q.config.directSlots-direct.length;if(remaining>0)direct.push(...nextBest.slice(0,remaining));playoff.push(...nextBest.slice(remaining,remaining+q.config.playoffSlots))}q.qualifiedTeamIds=[...new Set(direct)];q.playoffTeamIds=[...new Set(playoff.filter(x=>!q.qualifiedTeamIds.includes(x)))];for(const id of q.qualifiedTeamIds)registerMembership(w,{season:String(q.config.cycleYear),competitionId:q.config.targetCompetitionId,teamId:id,teamKind:'national',status:'qualified',source:'simulated',provenance:[{sourceId:'international-qualifier-runtime-v1',historical:false,confidence:100}]});return q}
export function qualifierCalendar(w:World,competitionId:string){const q=qualifierState(w,competitionId);if(!q)return[];return[...new Set(q.fixtures.map(f=>f.matchday))].sort((a,b)=>a-b).map(md=>({matchday:md,date:dateForMatchday(q.config.cycleYear,md),fixtures:q.fixtures.filter(f=>f.matchday===md).length,played:q.fixtures.filter(f=>f.matchday===md&&f.played).length}))}
export function snapshotQualifierRuntime(w:World):QualifierRuntimeSnapshot{return{cycles:[...state(w).cycles.entries()].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}
export function restoreQualifierRuntime(w:World,x:QualifierRuntimeSnapshot){states.set(w,{cycles:new Map((x?.cycles??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
