import type { World } from './engine';
import { footballDataSnapshot } from './world-football-data-v1';
import { selectNationalSquad } from './national-team-selection-v1';
import { simulateInternationalMatch } from './international-match-engine-v1';
import { nationalTeamRanking } from './national-team-ranking-v1';
import { ensureQualifierCycle, qualifierStandings, qualifierCalendar } from './international-qualifier-runtime-v1';
import { playerProfile } from './player-profile-v2';

export function runInternationalMatchDiagnostics(world:World){const issues:string[]=[],active=footballDataSnapshot(world).nationalTeams.filter(t=>t.active&&t.teamKind==='senior');const viable=active.map(t=>({team:t,players:world.clubs.flatMap(c=>c.players).filter(p=>{const pr=playerProfile(world,p.id);return pr?.eligibility.some(e=>e.countryId===t.countryId&&e.eligible)}).length})).filter(x=>x.players>=11);let matchTested=false;if(viable.length>=2){const a=viable[0].team,b=viable[1].team,home=selectNationalSquad(world,{teamId:a.id,countryId:a.countryId,size:26,date:'2027-03-20'}),away=selectNationalSquad(world,{teamId:b.id,countryId:b.countryId,size:26,date:'2027-03-20'}),beforeH=nationalTeamRanking(world,a.id)?.matches??0,beforeA=nationalTeamRanking(world,b.id)?.matches??0,capsBefore=new Map(home.members.map(m=>[m.playerId,playerProfile(world,m.playerId)?.eligibility.find(e=>e.countryId===a.countryId)?.seniorCaps??0]));const r=simulateInternationalMatch(world,{home,away,date:'2027-03-20',competitionId:'international-friendly',importance:'friendly'});matchTested=true;if(r.homeGoals<0||r.awayGoals<0)issues.push('placar internacional inválido');if((nationalTeamRanking(world,a.id)?.matches??0)!==beforeH+1||(nationalTeamRanking(world,b.id)?.matches??0)!==beforeA+1)issues.push('ranking não registrou partida internacional');const played=[...r.state.home.players,...r.state.away.players].filter((p:any)=>p.minutesPlayed>0);if(!played.length)issues.push('nenhum jogador recebeu minutos internacionais');for(const p of played.filter((x:any)=>x.clubId===a.id)){const before=capsBefore.get(p.playerId)??0,after=playerProfile(world,p.playerId)?.eligibility.find(e=>e.countryId===a.countryId)?.seniorCaps??0;if(after<before+1)issues.push(`cap não registrada: ${p.playerId}`)}}
const cycle=ensureQualifierCycle(world,2030);if(cycle.length<6)issues.push('ciclo de eliminatórias incompleto');for(const q of cycle){if(q.fixtures.some(f=>f.homeTeamId===f.awayTeamId))issues.push(`fixture contra si próprio: ${q.config.id}`);const cal=qualifierCalendar(world,q.config.id);if(!cal.length&&q.groups.some(g=>g.teams.length>1))issues.push(`calendário vazio: ${q.config.id}`);const table=qualifierStandings(q,q.groups[0]?.id);if(new Set(table.map(x=>x.teamId)).size!==table.length)issues.push(`tabela duplicada: ${q.config.id}`)}return{ok:issues.length===0,issues,activeNationalTeams:active.length,viableNationalTeams:viable.length,matchTested,qualifierCompetitions:cycle.length}}
