import './styles.css';
import { createWorld, playerById, selectStartingEleven, sortedStandings, teamStrength, type Fixture, type World } from './engine';
import { bindTactics, renderTactics } from './tactics';
import { availableRoles, getPlayerRole, playCurrentRoundWithRoles, roleDefinition, roleSuitability, setPlayerRole, tacticalRoleSummary, type PlayerRole } from './roles';
import { fixturePlayerStats, playerFromWorld, topPlayers } from './analytics';
import { advanceToNextSeason, careerState, isAcademyPlayer, seasonFinished, simulateSeasons } from './lifecycle';

let world: World = createWorld();
let selectedClubId = world.clubs[0].id;
let selectedFixture: Fixture | null = null;
let activeView: 'overview' | 'squad' | 'tactics' | 'roles' | 'analytics' | 'world' | 'match' = 'overview';

const app = document.querySelector<HTMLDivElement>('#app')!;
const clubName = (id: string) => world.clubs.find(c => c.id === id)?.name ?? id;
const selectedClub = () => world.clubs.find(c => c.id === selectedClubId) ?? world.clubs[0];
const clubOptions = () => world.clubs.map(c => `<option value="${c.id}" ${c.id === selectedClubId ? 'selected' : ''}>${c.name}</option>`).join('');
const navButton = (label: string, view: Exclude<typeof activeView, 'match'>) => `<button class="nav ${activeView === view ? 'active' : ''}" data-view="${view}">${label}</button>`;

function renderOverview() {
  const currentRound = world.fixtures.filter(f => f.round === world.round && !f.played);
  const lastRound = world.fixtures.filter(f => f.round === world.round - 1 && f.played);
  const table = sortedStandings(world);
  const totalPlayers = world.clubs.reduce((sum, c) => sum + c.players.length, 0);
  const finished = seasonFinished(world);
  return `<header><div><span class="eyebrow">TEMPORADA ${world.season}</span><h1>Centro do Manager</h1><p>O mundo agora envelhece, desenvolve jogadores, aposenta veteranos e recebe novas gerações da base todos os anos.</p></div><div class="actions"><button id="reset" class="secondary">Reiniciar</button><button id="advance" class="primary">${finished ? `Iniciar temporada ${world.season + 1}` : `Simular rodada ${world.round}`}</button></div></header>
  <section class="cards"><article class="card metric"><span>Clubes ativos</span><strong>${world.clubs.length}</strong></article><article class="card metric"><span>Jogadores ativos</span><strong>${totalPlayers}</strong></article><article class="card metric"><span>Temporada</span><strong>${world.season}</strong></article><article class="card metric"><span>Líder</span><strong>${table[0] ? clubName(table[0].clubId) : '—'}</strong></article></section>
  <div class="grid"><section class="card standings"><div class="section-title"><h2>Classificação</h2><span>Pontos corridos · ida e volta</span></div><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>Pts</th></tr></thead><tbody>${table.map((r, i) => `<tr><td>${i + 1}</td><td><button class="club-link" data-club="${r.clubId}">${clubName(r.clubId)}</button></td><td>${r.played}</td><td>${r.wins}</td><td>${r.draws}</td><td>${r.losses}</td><td>${r.gf - r.ga}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></section>
  <section class="stack"><article class="card fixtures"><div class="section-title"><h2>${finished ? 'Fim da temporada' : 'Próxima rodada'}</h2><span>${finished ? world.season : `Rodada ${world.round}`}</span></div>${finished ? `<p>Temporada concluída. Avance o calendário para envelhecimento, aposentadorias e nova fornada da base.</p>` : currentRound.map(f => `<div class="fixture"><span>${clubName(f.home)}</span><b>×</b><span>${clubName(f.away)}</span></div>`).join('')}</article>
  <article class="card fixtures"><div class="section-title"><h2>Últimos resultados</h2><span>${lastRound.length ? `Rodada ${world.round - 1}` : 'Nenhum jogo ainda'}</span></div>${lastRound.length ? lastRound.map((f, i) => `<button class="fixture result match-link" data-match="${i}"><span>${clubName(f.home)}</span><b>${f.homeGoals}–${f.awayGoals}</b><span>${clubName(f.away)}</span><small>xG ${f.homeXg} · ${f.awayXg}</small></button>`).join('') : '<p>Simule a primeira rodada.</p>'}</article></section></div>`;
}

function renderSquad() {
  const club = selectedClub();
  const xi = selectStartingEleven(club);
  const ids = new Set(xi.map(p => p.id));
  const strength = teamStrength(club);
  const avgAge = club.players.reduce((s, p) => s + p.age, 0) / club.players.length;
  const academyCount = club.players.filter(isAcademyPlayer).length;
  return `<header><div><span class="eyebrow">ELENCO · ${club.name.toUpperCase()}</span><h1>${club.name}</h1><p>O elenco muda com o tempo: jovens crescem, veteranos declinam e novas gerações chegam da base.</p></div><select id="club-select">${clubOptions()}</select></header>
  <section class="cards"><article class="card metric"><span>Força geral</span><strong>${strength.overall.toFixed(1)}</strong></article><article class="card metric"><span>Média de idade</span><strong>${avgAge.toFixed(1)}</strong></article><article class="card metric"><span>Jogadores da base gerados</span><strong>${academyCount}</strong></article><article class="card metric"><span>Reputação</span><strong>${club.reputation}</strong></article></section>
  <div class="squad-grid"><section class="card"><div class="section-title"><h2>Onze inicial automático</h2><span>4-2-3-1 base</span></div><div class="strength-strip"><span>Ataque <b>${strength.attack.toFixed(0)}</b></span><span>Meio <b>${strength.midfield.toFixed(0)}</b></span><span>Defesa <b>${strength.defense.toFixed(0)}</b></span><span>Goleiro <b>${strength.goalkeeper.toFixed(0)}</b></span></div><div class="xi-list">${xi.map((p, i) => `<div><span class="shirt">${i + 1}</span><b>${p.position}</b><span>${p.name}${isAcademyPlayer(p) ? ' ★' : ''}</span><small>${roleDefinition(getPlayerRole(club, p)).name} · CA ${p.currentAbility} · ${p.age}a</small></div>`).join('')}</div></section>
  <section class="card squad-table"><div class="section-title"><h2>Plantel completo</h2><span>★ gerado pela categoria de base</span></div><table><thead><tr><th></th><th>Jogador</th><th>Pos</th><th>Idade</th><th>CA</th><th>PA</th><th>Cond.</th><th>Moral</th></tr></thead><tbody>${[...club.players].sort((a, b) => b.currentAbility - a.currentAbility).map(p => `<tr class="${ids.has(p.id) ? 'starter' : ''}"><td>${ids.has(p.id) ? '●' : ''}</td><td>${p.name}${isAcademyPlayer(p) ? ' ★' : ''}</td><td>${p.position}</td><td>${p.age}</td><td><b>${p.currentAbility}</b></td><td>${p.potentialAbility}</td><td>${p.condition}%</td><td>${p.morale}</td></tr>`).join('')}</tbody></table></section></div>`;
}

function renderRoles() {
  const club = selectedClub(); const xi = selectStartingEleven(club); const summary = tacticalRoleSummary(club); const delta = (n: number) => `${n > 0 ? '+' : ''}${n}`;
  return `<header><div><span class="eyebrow">PAPÉIS · ${club.name.toUpperCase()}</span><h1>Papéis dos Jogadores</h1><p>Funções individuais alteram a expressão tática e o perfil usado nos eventos da partida.</p></div><select id="club-select">${clubOptions()}</select></header>
  <section class="cards"><article class="card metric"><span>Ritmo efetivo</span><strong>${summary.effective.tempo}</strong><small>${delta(summary.tempoDelta)} pelos papéis</small></article><article class="card metric"><span>Pressão efetiva</span><strong>${summary.effective.pressing}</strong><small>${delta(summary.pressingDelta)} pelos papéis</small></article><article class="card metric"><span>Linha efetiva</span><strong>${summary.effective.defensiveLine}</strong><small>${delta(summary.lineDelta)} pelos papéis</small></article><article class="card metric"><span>Largura efetiva</span><strong>${summary.effective.width}</strong><small>${delta(summary.widthDelta)} pelos papéis</small></article></section>
  <div class="roles-layout"><section class="card"><div class="section-title"><h2>Onze inicial</h2><span>Escolha um papel por jogador</span></div><div class="roles-list">${xi.map((p, i) => { const current = getPlayerRole(club, p); const def = roleDefinition(current); const suit = roleSuitability(p, current); return `<div class="role-row"><span class="shirt">${i + 1}</span><div class="role-player"><b>${p.name}</b><small>${p.position} · CA ${p.currentAbility} · ${p.age}a</small></div><select class="role-select" data-player="${p.id}">${availableRoles(p).map(r => `<option value="${r.id}" ${r.id === current ? 'selected' : ''}>${r.name} · ${r.duty}</option>`).join('')}</select><span class="suitability ${suit >= 78 ? 'good' : suit >= 68 ? 'mid' : 'low'}">${suit}</span><div class="role-desc"><b>${def.name}</b><small>${def.description}</small></div></div>`; }).join('')}</div></section><aside class="card role-help"><div class="section-title"><h2>Leitura do motor</h2><span>Impacto real</span></div><div class="role-help-body"><p>O papel não altera permanentemente os atributos. Ele muda como o jogador usa suas qualidades durante a simulação.</p><div class="role-rule"><b>Falso 9</b><span>conecta e cria mais</span></div><div class="role-rule"><b>Atacante interior</b><span>ataca mais a área</span></div><div class="role-rule"><b>Recuperador</b><span>eleva pressão e desarme</span></div><div class="role-rule"><b>Zagueiro construtor</b><span>melhora saída de bola</span></div></div></aside></div>`;
}

function renderAnalytics() {
  const rows = topPlayers(world, 15); const leader = rows[0]; const topScorer = [...rows].sort((a, b) => b.goals - a.goals)[0];
  return `<header><div><span class="eyebrow">ANÁLISE DE DESEMPENHO</span><h1>Estatísticas Individuais</h1><p>Os números vêm dos eventos realmente gerados pelo match engine na temporada ${world.season}.</p></div></header>
  <section class="cards"><article class="card metric"><span>Maior impacto</span><strong>${leader ? playerFromWorld(world, leader.playerId)?.name : '—'}</strong></article><article class="card metric"><span>Artilheiro</span><strong>${topScorer?.goals ? `${playerFromWorld(world, topScorer.playerId)?.name} · ${topScorer.goals}` : '—'}</strong></article><article class="card metric"><span>Partidas</span><strong>${world.fixtures.filter(f => f.played).length}</strong></article><article class="card metric"><span>Eventos</span><strong>${world.fixtures.reduce((s, f) => s + (f.events?.length ?? 0), 0)}</strong></article></section>
  <section class="card analytics-table"><div class="section-title"><h2>Ranking da temporada</h2><span>Produção individual do motor</span></div>${rows.length ? `<table><thead><tr><th>#</th><th>Jogador</th><th>Clube</th><th>Pos</th><th>Gols</th><th>Chutes</th><th>xG</th><th>Defesas</th><th>Amar.</th><th>Impacto</th></tr></thead><tbody>${rows.map((r, i) => { const p = playerFromWorld(world, r.playerId); return `<tr><td>${i + 1}</td><td>${p?.name ?? r.playerId}</td><td>${clubName(r.clubId)}</td><td>${p?.position ?? '—'}</td><td><b>${r.goals}</b></td><td>${r.shots}</td><td>${r.xg}</td><td>${r.saves}</td><td>${r.yellows}</td><td><b>${r.impact}</b></td></tr>`; }).join('')}</tbody></table>` : '<div class="empty-state">Simule partidas para gerar estatísticas.</div>'}</section>`;
}

function renderWorld() {
  const state = careerState(world);
  const latestIntake = state.youthIntakes.filter(x => x.season === world.season).slice(-24);
  const latestRetirements = state.retiredPlayers.filter(x => x.retiredSeason === world.season).slice(-20);
  const latestDev = [...state.development].filter(x => x.season === world.season).sort((a, b) => (b.after - b.before) - (a.after - a.before)).slice(0, 15);
  const activePlayers = world.clubs.reduce((sum, c) => sum + c.players.length, 0);
  const academyPlayers = world.clubs.reduce((sum, c) => sum + c.players.filter(isAcademyPlayer).length, 0);
  return `<header><div><span class="eyebrow">MOTOR DE MUNDO VIVO</span><h1>Continuidade do Universo</h1><p>Cada virada de temporada envelhece e desenvolve o elenco, aposenta jogadores e gera uma nova fornada de jovens para manter o futebol vivo indefinidamente.</p></div><div class="actions"><button id="simulate-five" class="secondary">Simular 5 temporadas</button>${seasonFinished(world) ? `<button id="next-season" class="primary">Virar para ${world.season + 1}</button>` : ''}</div></header>
  <section class="cards"><article class="card metric"><span>Temporada atual</span><strong>${world.season}</strong></article><article class="card metric"><span>Jogadores ativos</span><strong>${activePlayers}</strong></article><article class="card metric"><span>Gerados pela base</span><strong>${academyPlayers}</strong></article><article class="card metric"><span>Aposentados históricos</span><strong>${state.retiredPlayers.length}</strong></article></section>
  <div class="world-grid"><section class="card"><div class="section-title"><h2>Histórico de temporadas</h2><span>${state.completedSeasons.length} concluídas</span></div>${state.completedSeasons.length ? `<table><thead><tr><th>Ano</th><th>Campeão</th><th>Pts</th><th>Artilheiro</th><th>Gols</th></tr></thead><tbody>${[...state.completedSeasons].reverse().map(s => `<tr><td>${s.season}</td><td>${clubName(s.championClubId)}</td><td>${s.championPoints}</td><td>${s.topScorerId ? (playerById(world, s.topScorerId)?.name ?? state.retiredPlayers.find(p => p.id === s.topScorerId)?.name ?? s.topScorerId) : '—'}</td><td>${s.topScorerGoals}</td></tr>`).join('')}</tbody></table>` : '<div class="empty-state">Conclua a primeira temporada para iniciar a história do mundo.</div>'}</section>
  <section class="card"><div class="section-title"><h2>Nova geração · ${world.season}</h2><span>${latestIntake.length} jovens</span></div>${latestIntake.length ? `<table><thead><tr><th>Jogador</th><th>Clube</th><th>Pos</th><th>Idade</th><th>CA</th><th>PA</th></tr></thead><tbody>${latestIntake.map(p => `<tr><td>${p.name}</td><td>${clubName(p.clubId)}</td><td>${p.position}</td><td>${p.age}</td><td>${p.currentAbility}</td><td><b>${p.potentialAbility}</b></td></tr>`).join('')}</tbody></table>` : '<div class="empty-state">A próxima virada anual produzirá uma nova fornada de 4 a 9 jovens por clube.</div>'}</section>
  <section class="card"><div class="section-title"><h2>Desenvolvimento anual</h2><span>maiores evoluções de ${world.season}</span></div>${latestDev.length ? `<div class="career-list">${latestDev.map(p => `<div><b>${p.name}</b><span>${clubName(p.clubId)} · ${p.age} anos</span><strong>${p.before} → ${p.after} (${p.after - p.before > 0 ? '+' : ''}${p.after - p.before})</strong></div>`).join('')}</div>` : '<div class="empty-state">Nenhuma virada de temporada registrada ainda.</div>'}</section>
  <section class="card"><div class="section-title"><h2>Aposentadorias</h2><span>${world.season}</span></div>${latestRetirements.length ? `<div class="career-list">${latestRetirements.map(p => `<div><b>${p.name}</b><span>${clubName(p.clubId)} · ${p.position}</span><strong>${p.age} anos · CA ${p.currentAbility}</strong></div>`).join('')}</div>` : '<div class="empty-state">Nenhuma aposentadoria nesta temporada.</div>'}</section></div>`;
}

function renderMatch() {
  const f = selectedFixture;
  if (!f?.played || !f.stats || !f.events) return `<header><div><h1>Central da Partida</h1><p>Nenhuma partida selecionada.</p></div></header>`;
  const s = f.stats; const important = f.events.filter(e => ['goal', 'yellow', 'substitution', 'fulltime'].includes(e.type)); const rows = fixturePlayerStats(f).sort((a, b) => b.goals - a.goals || b.xg - a.xg || b.saves - a.saves);
  return `<header><div><span class="eyebrow">RODADA ${f.round} · CENTRAL DA PARTIDA</span><h1>${clubName(f.home)} ${f.homeGoals}–${f.awayGoals} ${clubName(f.away)}</h1><p>xG ${f.homeXg} – ${f.awayXg}</p></div><button id="back-overview" class="secondary">Voltar</button></header><section class="score-hero card"><div><strong>${clubName(f.home)}</strong><span>${f.homeGoals}</span></div><div class="score-meta"><b>ENCERRADO</b><small>xG ${f.homeXg} · ${f.awayXg}</small></div><div><span>${f.awayGoals}</span><strong>${clubName(f.away)}</strong></div></section>
  <div class="match-grid"><section class="card"><div class="section-title"><h2>Estatísticas</h2><span>90 minutos</span></div><div class="stats-list"><div><span>${s.possessionHome}%</span><b>Posse</b><span>${s.possessionAway}%</span></div><div><span>${s.shotsHome}</span><b>Finalizações</b><span>${s.shotsAway}</span></div><div><span>${s.shotsOnTargetHome}</span><b>No alvo</b><span>${s.shotsOnTargetAway}</span></div><div><span>${s.passesHome}</span><b>Passes</b><span>${s.passesAway}</span></div><div><span>${s.yellowHome}</span><b>Amarelos</b><span>${s.yellowAway}</span></div></div></section><section class="card"><div class="section-title"><h2>Linha do tempo</h2><span>${f.events.length} eventos</span></div><div class="timeline">${important.map(e => `<div class="timeline-event ${e.type}"><span class="minute">${e.minute}'</span><span class="event-icon">${e.type === 'goal' ? '⚽' : e.type === 'yellow' ? '🟨' : e.type === 'substitution' ? '↔' : '■'}</span><div><b>${e.text}</b>${e.playerId ? `<small>${playerById(world, e.playerId)?.name ?? ''}</small>` : ''}</div></div>`).join('')}</div></section></div>
  <section class="card analytics-table"><div class="section-title"><h2>Produção individual</h2><span>eventos da partida</span></div><table><thead><tr><th>Jogador</th><th>Clube</th><th>Gols</th><th>Chutes</th><th>xG</th><th>Defesas</th><th>Amar.</th></tr></thead><tbody>${rows.map(r => `<tr><td>${playerById(world, r.playerId)?.name ?? r.playerId}</td><td>${clubName(r.clubId)}</td><td>${r.goals}</td><td>${r.shots}</td><td>${r.xg}</td><td>${r.saves}</td><td>${r.yellows}</td></tr>`).join('')}</tbody></table></section>`;
}

function render() {
  const content = activeView === 'overview' ? renderOverview() : activeView === 'squad' ? renderSquad() : activeView === 'tactics' ? renderTactics(selectedClub(), clubOptions()) : activeView === 'roles' ? renderRoles() : activeView === 'analytics' ? renderAnalytics() : activeView === 'world' ? renderWorld() : renderMatch();
  app.innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand">FP</div><div class="game-name">Football Project</div><nav>${navButton('Visão Geral', 'overview')}${navButton('Elenco', 'squad')}${navButton('Táticas', 'tactics')}${navButton('Papéis', 'roles')}${navButton('Estatísticas', 'analytics')}${navButton('Mundo Vivo', 'world')}<button class="nav disabled">Mercado</button><button class="nav disabled">Finanças</button></nav></aside><main>${content}</main></div>`;

  document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b => b.addEventListener('click', () => { activeView = b.dataset.view as Exclude<typeof activeView, 'match'>; render(); }));
  document.querySelectorAll<HTMLButtonElement>('.club-link').forEach(b => b.addEventListener('click', () => { selectedClubId = b.dataset.club ?? selectedClubId; activeView = 'squad'; render(); }));
  document.querySelector<HTMLSelectElement>('#club-select')?.addEventListener('change', e => { selectedClubId = (e.target as HTMLSelectElement).value; render(); });
  document.querySelector<HTMLButtonElement>('#advance')?.addEventListener('click', () => { if (seasonFinished(world)) advanceToNextSeason(world); else playCurrentRoundWithRoles(world); selectedFixture = null; render(); });
  document.querySelector<HTMLButtonElement>('#next-season')?.addEventListener('click', () => { advanceToNextSeason(world); selectedFixture = null; render(); });
  document.querySelector<HTMLButtonElement>('#simulate-five')?.addEventListener('click', () => { simulateSeasons(world, 5, playCurrentRoundWithRoles); selectedFixture = null; render(); });
  document.querySelector<HTMLButtonElement>('#reset')?.addEventListener('click', () => { world = createWorld(); selectedClubId = world.clubs[0].id; selectedFixture = null; activeView = 'overview'; render(); });

  const lastRound = world.fixtures.filter(f => f.round === world.round - 1 && f.played);
  document.querySelectorAll<HTMLButtonElement>('.match-link').forEach(b => b.addEventListener('click', () => { selectedFixture = lastRound[Number(b.dataset.match)]; activeView = 'match'; render(); }));
  document.querySelector<HTMLButtonElement>('#back-overview')?.addEventListener('click', () => { activeView = 'overview'; render(); });
  if (activeView === 'tactics') bindTactics(selectedClub(), render);
  if (activeView === 'roles') document.querySelectorAll<HTMLSelectElement>('.role-select').forEach(select => select.addEventListener('change', () => { setPlayerRole(selectedClub(), select.dataset.player!, select.value as PlayerRole); render(); }));
}

render();
