import './styles.css';
import { createWorld, playerById, selectStartingEleven, sortedStandings, teamStrength, type Fixture, type World } from './engine';
import { bindTactics, renderTactics } from './tactics';
import { availableRoles, getPlayerRole, playCurrentRoundWithRoles, roleDefinition, roleSuitability, setPlayerRole, tacticalRoleSummary, type PlayerRole } from './roles';
import { fixturePlayerStats, playerFromWorld, topPlayers } from './analytics';

let world: World = createWorld();
let selectedClubId = world.clubs[0].id;
let selectedFixture: Fixture | null = null;
let activeView: 'overview' | 'squad' | 'tactics' | 'roles' | 'analytics' | 'match' = 'overview';

const app = document.querySelector<HTMLDivElement>('#app')!;
const clubName = (id: string) => world.clubs.find(c => c.id === id)?.name ?? id;
const selectedClub = () => world.clubs.find(c => c.id === selectedClubId) ?? world.clubs[0];
const clubOptions = () => world.clubs.map(c=>`<option value="${c.id}" ${c.id===selectedClubId?'selected':''}>${c.name}</option>`).join('');

function navButton(label: string, view: 'overview'|'squad'|'tactics'|'roles'|'analytics') {
  return `<button class="nav ${activeView===view?'active':''}" data-view="${view}">${label}</button>`;
}

function renderOverview() {
  const currentRound = world.fixtures.filter(f=>f.round===world.round);
  const lastRound = world.fixtures.filter(f=>f.round===world.round-1&&f.played);
  const table = sortedStandings(world);
  const totalPlayers = world.clubs.reduce((sum,c)=>sum+c.players.length,0);
  return `<header><div><span class="eyebrow">TEMPORADA ${world.season}</span><h1>Centro do Manager</h1><p>Jogadores, condição, tática e papéis individuais já alteram o comportamento do motor.</p></div><div class="actions"><button id="reset" class="secondary">Reiniciar</button><button id="advance" class="primary" ${currentRound.length?'':'disabled'}>${currentRound.length?`Simular rodada ${world.round}`:'Temporada concluída'}</button></div></header>
  <section class="cards"><article class="card metric"><span>Clubes ativos</span><strong>${world.clubs.length}</strong></article><article class="card metric"><span>Jogadores</span><strong>${totalPlayers}</strong></article><article class="card metric"><span>Jogos realizados</span><strong>${world.fixtures.filter(f=>f.played).length}</strong></article><article class="card metric"><span>Líder</span><strong>${table[0]?clubName(table[0].clubId):'—'}</strong></article></section>
  <div class="grid"><section class="card standings"><div class="section-title"><h2>Classificação</h2><span>Pontos corridos · ida e volta</span></div><table><thead><tr><th>#</th><th>Clube</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th><th>Pts</th></tr></thead><tbody>${table.map((r,i)=>`<tr><td>${i+1}</td><td><button class="club-link" data-club="${r.clubId}">${clubName(r.clubId)}</button></td><td>${r.played}</td><td>${r.wins}</td><td>${r.draws}</td><td>${r.losses}</td><td>${r.gf-r.ga}</td><td><b>${r.points}</b></td></tr>`).join('')}</tbody></table></section><section class="stack"><article class="card fixtures"><div class="section-title"><h2>Próxima rodada</h2><span>Rodada ${world.round}</span></div>${currentRound.length?currentRound.map(f=>`<div class="fixture"><span>${clubName(f.home)}</span><b>×</b><span>${clubName(f.away)}</span></div>`).join(''):'<p>Temporada concluída.</p>'}</article><article class="card fixtures"><div class="section-title"><h2>Últimos resultados</h2><span>${lastRound.length?`Rodada ${world.round-1}`:'Nenhum jogo ainda'}</span></div>${lastRound.length?lastRound.map((f,i)=>`<button class="fixture result match-link" data-match="${i}"><span>${clubName(f.home)}</span><b>${f.homeGoals}–${f.awayGoals}</b><span>${clubName(f.away)}</span><small>xG ${f.homeXg} · ${f.awayXg}</small></button>`).join(''):'<p>Simule a primeira rodada.</p>'}</article></section></div>`;
}

function renderSquad() {
  const club=selectedClub(); const xi=selectStartingEleven(club); const ids=new Set(xi.map(p=>p.id)); const strength=teamStrength(club);
  const avgAge=club.players.reduce((s,p)=>s+p.age,0)/club.players.length; const avgCondition=club.players.reduce((s,p)=>s+p.condition,0)/club.players.length;
  return `<header><div><span class="eyebrow">ELENCO · ${club.name.toUpperCase()}</span><h1>${club.name}</h1><p>O onze inicial é escolhido automaticamente por função, atributos, condição e moral.</p></div><select id="club-select">${clubOptions()}</select></header><section class="cards"><article class="card metric"><span>Força geral</span><strong>${strength.overall.toFixed(1)}</strong></article><article class="card metric"><span>Média de idade</span><strong>${avgAge.toFixed(1)}</strong></article><article class="card metric"><span>Condição média</span><strong>${avgCondition.toFixed(0)}%</strong></article><article class="card metric"><span>Reputação</span><strong>${club.reputation}</strong></article></section><div class="squad-grid"><section class="card"><div class="section-title"><h2>Onze inicial automático</h2><span>4-2-3-1 base</span></div><div class="strength-strip"><span>Ataque <b>${strength.attack.toFixed(0)}</b></span><span>Meio <b>${strength.midfield.toFixed(0)}</b></span><span>Defesa <b>${strength.defense.toFixed(0)}</b></span><span>Goleiro <b>${strength.goalkeeper.toFixed(0)}</b></span></div><div class="xi-list">${xi.map((p,i)=>`<div><span class="shirt">${i+1}</span><b>${p.position}</b><span>${p.name}</span><small>${roleDefinition(getPlayerRole(club,p)).name} · CA ${p.currentAbility} · Cond. ${p.condition}%</small></div>`).join('')}</div></section><section class="card squad-table"><div class="section-title"><h2>Plantel completo</h2><span>CA = habilidade atual · PA = potencial</span></div><table><thead><tr><th></th><th>Jogador</th><th>Pos</th><th>Idade</th><th>CA</th><th>PA</th><th>Cond.</th><th>Moral</th></tr></thead><tbody>${[...club.players].sort((a,b)=>b.currentAbility-a.currentAbility).map(p=>`<tr class="${ids.has(p.id)?'starter':''}"><td>${ids.has(p.id)?'●':''}</td><td>${p.name}</td><td>${p.position}</td><td>${p.age}</td><td><b>${p.currentAbility}</b></td><td>${p.potentialAbility}</td><td>${p.condition}%</td><td>${p.morale}</td></tr>`).join('')}</tbody></table></section></div>`;
}

function renderRoles() {
  const club=selectedClub(); const xi=selectStartingEleven(club); const summary=tacticalRoleSummary(club); const delta=(n:number)=>`${n>0?'+':''}${n}`;
  return `<header><div><span class="eyebrow">PAPÉIS · ${club.name.toUpperCase()}</span><h1>Papéis dos Jogadores</h1><p>Os papéis agora alteram também os atributos efetivos usados durante a partida, mudando quem cria, finaliza, pressiona e constrói.</p></div><select id="club-select">${clubOptions()}</select></header>
  <section class="cards"><article class="card metric"><span>Ritmo efetivo</span><strong>${summary.effective.tempo}</strong><small>${delta(summary.tempoDelta)} pelos papéis</small></article><article class="card metric"><span>Pressão efetiva</span><strong>${summary.effective.pressing}</strong><small>${delta(summary.pressingDelta)} pelos papéis</small></article><article class="card metric"><span>Linha efetiva</span><strong>${summary.effective.defensiveLine}</strong><small>${delta(summary.lineDelta)} pelos papéis</small></article><article class="card metric"><span>Largura efetiva</span><strong>${summary.effective.width}</strong><small>${delta(summary.widthDelta)} pelos papéis</small></article></section>
  <div class="roles-layout"><section class="card"><div class="section-title"><h2>Onze inicial</h2><span>Escolha um papel por jogador</span></div><div class="roles-list">${xi.map((p,i)=>{const current=getPlayerRole(club,p);const def=roleDefinition(current);const suit=roleSuitability(p,current);return `<div class="role-row"><span class="shirt">${i+1}</span><div class="role-player"><b>${p.name}</b><small>${p.position} · CA ${p.currentAbility} · Cond. ${p.condition}%</small></div><select class="role-select" data-player="${p.id}">${availableRoles(p).map(r=>`<option value="${r.id}" ${r.id===current?'selected':''}>${r.name} · ${r.duty}</option>`).join('')}</select><span class="suitability ${suit>=78?'good':suit>=68?'mid':'low'}">${suit}</span><div class="role-desc"><b>${def.name}</b><small>${def.description}</small></div></div>`;}).join('')}</div></section><aside class="card role-help"><div class="section-title"><h2>Leitura do motor</h2><span>Impacto real</span></div><div class="role-help-body"><p>O papel afeta a expressão coletiva e também o perfil usado pelo jogador nos eventos da partida.</p><div class="role-rule"><b>Falso 9</b><span>ganha passe, técnica e decisão; finaliza menos</span></div><div class="role-rule"><b>Atacante interior</b><span>ganha finalização, técnica e presença ofensiva</span></div><div class="role-rule"><b>Organizador</b><span>participa mais da criação</span></div><div class="role-rule"><b>Recuperador</b><span>ganha desarme e intensidade</span></div><div class="role-rule"><b>Zagueiro construtor</b><span>melhora saída e qualidade de passe</span></div><p class="role-note">Os bônus são temporários durante a simulação e não alteram os atributos-base salvos do jogador.</p></div></aside></div>`;
}

function renderAnalytics() {
  const rows=topPlayers(world,15);
  const leader=rows[0];
  const topScorer=[...rows].sort((a,b)=>b.goals-a.goals)[0];
  const topXg=[...rows].sort((a,b)=>b.xg-a.xg)[0];
  return `<header><div><span class="eyebrow">ANÁLISE DE DESEMPENHO</span><h1>Estatísticas Individuais</h1><p>Os números abaixo vêm dos eventos realmente gerados pelo match engine.</p></div></header>
  <section class="cards"><article class="card metric"><span>Maior impacto</span><strong>${leader?playerFromWorld(world,leader.playerId)?.name:'—'}</strong></article><article class="card metric"><span>Artilheiro</span><strong>${topScorer&&topScorer.goals?`${playerFromWorld(world,topScorer.playerId)?.name} · ${topScorer.goals}`:'—'}</strong></article><article class="card metric"><span>Maior xG</span><strong>${topXg&&topXg.xg?`${playerFromWorld(world,topXg.playerId)?.name} · ${topXg.xg}`:'—'}</strong></article><article class="card metric"><span>Eventos contabilizados</span><strong>${world.fixtures.filter(f=>f.played).reduce((s,f)=>s+(f.events?.length??0),0)}</strong></article></section>
  <section class="card analytics-table"><div class="section-title"><h2>Ranking da temporada</h2><span>Impacto = gols, defesas, chutes, xG e disciplina</span></div>${rows.length?`<table><thead><tr><th>#</th><th>Jogador</th><th>Clube</th><th>Pos</th><th>Gols</th><th>Chutes</th><th>xG</th><th>Defesas</th><th>Amar.</th><th>Impacto</th></tr></thead><tbody>${rows.map((r,i)=>{const p=playerFromWorld(world,r.playerId);return `<tr><td>${i+1}</td><td>${p?.name??r.playerId}</td><td>${clubName(r.clubId)}</td><td>${p?.position??'—'}</td><td><b>${r.goals}</b></td><td>${r.shots}</td><td>${r.xg}</td><td>${r.saves}</td><td>${r.yellows}</td><td><b>${r.impact}</b></td></tr>`;}).join('')}</tbody></table>`:'<div class="empty-state">Simule partidas para gerar estatísticas individuais.</div>'}</section>`;
}

function renderMatch() {
  const f=selectedFixture;
  if(!f||!f.played||!f.stats||!f.events) return `<header><div><h1>Central da Partida</h1><p>Nenhuma partida selecionada.</p></div></header>`;
  const s=f.stats; const important=f.events.filter(e=>['goal','yellow','substitution','fulltime'].includes(e.type));
  const playerRows=fixturePlayerStats(f).sort((a,b)=>b.goals-a.goals||b.xg-a.xg||b.saves-a.saves);
  const icon=(t:string)=>t==='goal'?'⚽':t==='yellow'?'🟨':t==='substitution'?'↔':'■';
  return `<header><div><span class="eyebrow">RODADA ${f.round} · CENTRAL DA PARTIDA</span><h1>${clubName(f.home)} ${f.homeGoals}–${f.awayGoals} ${clubName(f.away)}</h1><p>xG ${f.homeXg} – ${f.awayXg}</p></div><button id="back-overview" class="secondary">Voltar</button></header>
  <section class="score-hero card"><div><strong>${clubName(f.home)}</strong><span>${f.homeGoals}</span></div><div class="score-meta"><b>ENCERRADO</b><small>xG ${f.homeXg} · ${f.awayXg}</small></div><div><span>${f.awayGoals}</span><strong>${clubName(f.away)}</strong></div></section>
  <div class="match-grid"><section class="card"><div class="section-title"><h2>Estatísticas</h2><span>90 minutos</span></div><div class="stats-list"><div><span>${s.possessionHome}%</span><b>Posse</b><span>${s.possessionAway}%</span></div><div><span>${s.shotsHome}</span><b>Finalizações</b><span>${s.shotsAway}</span></div><div><span>${s.shotsOnTargetHome}</span><b>No alvo</b><span>${s.shotsOnTargetAway}</span></div><div><span>${s.passesHome}</span><b>Passes</b><span>${s.passesAway}</span></div><div><span>${s.yellowHome}</span><b>Amarelos</b><span>${s.yellowAway}</span></div><div><span>${f.homeXg}</span><b>xG</b><span>${f.awayXg}</span></div></div></section><section class="card"><div class="section-title"><h2>Linha do tempo</h2><span>${f.events.length} eventos simulados</span></div><div class="timeline">${important.map(e=>{const p=playerById(world,e.playerId);const c=p?world.clubs.find(x=>x.id===p.clubId):undefined;return `<div class="timeline-event ${e.type}"><span class="minute">${e.minute}'</span><span class="event-icon">${icon(e.type)}</span><div><b>${e.text}</b>${p&&c?`<small>${p.position} · ${roleDefinition(getPlayerRole(c,p)).name} · CA ${p.currentAbility}</small>`:''}</div></div>`;}).join('')}</div></section></div>
  <section class="card analytics-table match-players"><div class="section-title"><h2>Jogadores na partida</h2><span>Produção derivada dos eventos</span></div><table><thead><tr><th></th><th>Jogador</th><th>Clube</th><th>Gols</th><th>Chutes</th><th>xG</th><th>Defesas</th><th>Amar.</th></tr></thead><tbody>${playerRows.map(r=>{const p=playerFromWorld(world,r.playerId);return `<tr><td></td><td>${p?.name??r.playerId}</td><td>${p?clubName(p.clubId):'—'}</td><td><b>${r.goals}</b></td><td>${r.shots}</td><td>${r.xg}</td><td>${r.saves}</td><td>${r.yellows}</td></tr>`;}).join('')}</tbody></table></section>
  <section class="card all-events"><div class="section-title"><h2>Log completo do motor</h2><span>Finalizações e defesas incluídas</span></div><div class="event-log">${f.events.map(e=>`<div><span>${e.minute}'</span><b>${e.type.toUpperCase()}</b><p>${e.text}${e.xg?` · xG ${e.xg}`:''}</p></div>`).join('')}</div></section>`;
}

function render() {
  const content=activeView==='overview'?renderOverview():activeView==='squad'?renderSquad():activeView==='tactics'?renderTactics(selectedClub(),clubOptions()):activeView==='roles'?renderRoles():activeView==='analytics'?renderAnalytics():renderMatch();
  app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">FP</div><div class="game-name">Football Project</div><nav>${navButton('Visão Geral','overview')}${navButton('Elenco','squad')}${navButton('Táticas','tactics')}${navButton('Papéis','roles')}${navButton('Estatísticas','analytics')}<button class="nav disabled">Competições</button><button class="nav disabled">Mercado</button><button class="nav disabled">Finanças</button></nav></aside><main>${content}</main></div>`;
  document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.addEventListener('click',()=>{activeView=b.dataset.view as 'overview'|'squad'|'tactics'|'roles'|'analytics';render();}));
  document.querySelectorAll<HTMLButtonElement>('.club-link').forEach(b=>b.addEventListener('click',()=>{selectedClubId=b.dataset.club??selectedClubId;activeView='squad';render();}));
  document.querySelector<HTMLSelectElement>('#club-select')?.addEventListener('change',e=>{selectedClubId=(e.target as HTMLSelectElement).value;render();});
  document.querySelector<HTMLButtonElement>('#advance')?.addEventListener('click',()=>{playCurrentRoundWithRoles(world);render();});
  document.querySelector<HTMLButtonElement>('#reset')?.addEventListener('click',()=>{world=createWorld();selectedClubId=world.clubs[0].id;selectedFixture=null;activeView='overview';render();});
  const last=world.fixtures.filter(f=>f.round===world.round-1&&f.played);
  document.querySelectorAll<HTMLButtonElement>('.match-link').forEach(b=>b.addEventListener('click',()=>{selectedFixture=last[Number(b.dataset.match)];activeView='match';render();}));
  document.querySelector<HTMLButtonElement>('#back-overview')?.addEventListener('click',()=>{activeView='overview';render();});
  document.querySelectorAll<HTMLSelectElement>('.role-select').forEach(select=>select.addEventListener('change',()=>{setPlayerRole(selectedClub(),select.dataset.player!,select.value as PlayerRole);render();}));
  if(activeView==='tactics') bindTactics(selectedClub(),render);
}
render();
