import type { World } from './engine';
import { managerCharacterState, userManager } from './manager-character';
import { applyManagerToVacancy, openManagerVacancies } from './manager-job-market-v2';
import { dailyCalendar } from './daily-simulation';

const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const clubName=(world:World,id:string)=>world.clubs.find(c=>c.id===id)?.name??id;
const managerName=(world:World,id:string)=>managerCharacterState(world).characters.get(id)?.name??id;
export function renderManagerJobMarket(world:World){const u=userManager(world),vacancies=openManagerVacancies(world);return `<header><div><span class="eyebrow">CARREIRA · MERCADO DE TREINADORES</span><h1>Vagas e processos seletivos</h1><p>Clubes não escolhem apenas pelo nome. Perfil, resultados, estilo, custo, torcida, imprensa e entrevista disputam peso na decisão.</p></div></header>${!vacancies.length?'<section class="card"><p>Nenhuma vaga aberta no momento.</p></section>':`<div class="manager-job-grid">${vacancies.map(v=>`<section class="card manager-job-card"><div class="section-title"><h2>${esc(clubName(world,v.clubId))}</h2><span>${v.stage}</span></div><p>Perfil: ${v.desired.tacticalIdentity} · reputação mínima ${Math.round(v.desired.minimumReputation)} · base ${Math.round(v.desired.youthImportance)}</p><small>Prazo: ${v.deadline}</small>${v.candidates.length?`<table><thead><tr><th>Candidato</th><th>Total</th><th>Diretoria</th><th>Torcida</th><th>Imprensa</th><th>Entrevista</th></tr></thead><tbody>${[...v.candidates].sort((a,b)=>b.total-a.total).slice(0,6).map(c=>`<tr><td>${esc(managerName(world,c.managerId))}${v.preferredManagerId===c.managerId?' ★':''}</td><td><b>${c.total.toFixed(0)}</b></td><td>${c.board.toFixed(0)}</td><td>${c.supporters.toFixed(0)}</td><td>${c.media.toFixed(0)}</td><td>${c.interview?.toFixed(0)??'—'}</td></tr>`).join('')}</tbody></table>`:'<p>O clube ainda está mapeando candidatos.</p>'}${u&&['open','shortlist','interviews'].includes(v.stage)?`<button class="mc-primary manager-apply" data-vacancy="${v.id}">Candidatar-me</button>`:''}</section>`).join('')}</div>`}`;}
export function bindManagerJobMarket(world:World,rerender:()=>void){const u=userManager(world);if(!u)return;document.querySelectorAll<HTMLButtonElement>('.manager-apply').forEach(b=>b.addEventListener('click',()=>{applyManagerToVacancy(world,b.dataset.vacancy!,u.id,dailyCalendar(world).date);rerender();}));}
