import type { World } from './engine';
import { emitWorldEvent, onWorldEvent } from './event-bus';
import { managerByClub } from './manager-character';
import { managerEvolutionRecord } from './manager-longterm-evolution';
const wired=new WeakSet<World>();
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
export function wireManagerSeasonEvolution(world:World){if(wired.has(world))return;wired.add(world);onWorldEvent(world,'SeasonEnded',(event)=>{for(const club of world.clubs){const m=managerByClub(world,club.id);if(!m)continue;const r=managerEvolutionRecord(world,m.id);if(!r||r.lastSeasonProcessed===event.season)continue;const e=r.evidence,changes:string[]=[];const shift=(key:keyof typeof m.personality,delta:number,label:string)=>{if(Math.abs(delta)<.1)return;m.personality[key]=clamp(m.personality[key]+delta);changes.push(`${label} ${delta>0?'+':''}${delta.toFixed(1)}`);};
 const matchTotal=Math.max(1,e.matches),winRate=e.wins/matchTotal;shift('assertiveness',winRate>=.65?.6:winRate<=.3?-.35:0,'assertividade');shift('patience',e.crises>=3?-.8:e.supportInteractions>=6?.45:0,'paciência');shift('diplomacy',e.supportInteractions>=5?.5:e.publicInteractions>=8?-.35:0,'diplomacia');shift('confrontation',e.disciplineInteractions>=6?.55:e.supportInteractions>=8?-.3:0,'confronto');shift('discipline',e.disciplineInteractions>=5?.45:0,'disciplina');shift('mediaSkill',e.mediaEvents>=18?.5:0,'mídia');shift('forgiveness',e.supportInteractions>=8?.4:e.promisesBroken>=3?-.4:0,'perdão');shift('adaptability',e.trainingDays>=100?.4:0,'adaptabilidade');
 if(e.highPressTraining>e.possessionTraining*1.25){m.tactical.pressingPreference=clamp(m.tactical.pressingPreference+.7);changes.push('pressão +0.7');}if(e.possessionTraining>e.highPressTraining*1.25){m.tactical.possessionPreference=clamp(m.tactical.possessionPreference+.7);changes.push('posse +0.7');}if(e.setPieceTraining>=15){m.tactical.setPieceImportance=clamp(m.tactical.setPieceImportance+.6);changes.push('bolas paradas +0.6');}if(e.youthEvents>=7){m.tactical.youthUsage=clamp(m.tactical.youthUsage+.6);changes.push('uso de jovens +0.6');}
 r.lastSeasonProcessed=event.season;r.identityShifts.push({date:event.date,summary:`Temporada ${event.season} consolidou mudanças na identidade de ${m.name}.`,changes});r.evidence={matches:0,wins:0,losses:0,trainingDays:0,highPressTraining:0,possessionTraining:0,setPieceTraining:0,youthEvents:0,mediaEvents:0,recruitmentEvents:0,negotiations:0,medicalEvents:0,disciplineInteractions:0,supportInteractions:0,publicInteractions:0,crises:0,promisesKept:0,promisesBroken:0};if(changes.length){m.history.push({date:event.date,type:'identityShift',summary:`Mudanças após a temporada: ${changes.join(', ')}.`,impact:2});emitWorldEvent(world,{type:'ManagerIdentityShift',date:event.date,actorIds:[m.id],clubIds:[club.id],importance:2,summary:`${m.name} terminou a temporada diferente de como começou.`,payload:{managerId:m.id,changes,season:event.season}});}}});}
