import './manager-profile-experience-v2.css';
import type { World } from './engine';
import { userManager } from './manager-character';
import { clubFinance } from './economy';
import { clubVisual, crestMarkup } from './visual-identity-v1';
import { worldCore } from './world-core-v2';

let activeTab='overview';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const world=()=>window.__touchlineWorld as World|undefined;
const bar=(label:string,value:number)=>`<div class="mpx-bar"><span>${label}</span><i><em style="width:${Math.max(0,Math.min(100,value))}%"></em></i><b>${Math.round(value)}</b></div>`;
const card=(label:string,value:string,sub='')=>`<article class="mpx-stat"><span>${label}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</article>`;
function tabButton(id:string,label:string,icon:string){return `<button data-mpx-tab="${id}" class="${activeTab===id?'active':''}"><i>${icon}</i><span>${label}</span></button>`}
function sectionOverview(m:NonNullable<ReturnType<typeof userManager>>,w:World){const c=w.clubs.find(x=>x.id===m.currentClubId),f=c?clubFinance(w,c.id):undefined;return `<div class="mpx-overview-grid"><section class="mpx-panel mpx-profile-card"><div class="mpx-avatar" data-style="${m.appearance.style}"><span>${esc((m.nickname||m.name).split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span></div><div><span class="mpx-kicker">TREINADOR PRINCIPAL</span><h2>${esc(m.nickname||m.name)}</h2><p>${esc(m.social.nationality)} · ${m.age} anos · ${esc(m.education.licence.replace(/([A-Z])/g,' $1'))}</p><div class="mpx-badges"><span>${esc(m.playingLevel)}</span><span>${m.experienceYears} anos de experiência</span><span>${m.careerPoints} pts carreira</span></div></div></section><section class="mpx-panel mpx-philosophy"><header><span>IDENTIDADE DE JOGO</span><b>${esc(m.tactical.favoriteFormation)} · ${esc(m.tactical.mentality)}</b></header>${bar('Pressão',m.tactical.pressingPreference)}${bar('Posse',m.tactical.possessionPreference)}${bar('Ritmo',m.tactical.tempoPreference)}${bar('Linha defensiva',m.tactical.defensiveLinePreference)}${bar('Uso da base',m.tactical.youthUsage)}</section><section class="mpx-panel mpx-career-snapshot"><header><span>CARREIRA AGORA</span><b>${esc(c?.name??m.currentClubId)}</b></header><div class="mpx-snapshot-grid">${card('Reputação doméstica',String(m.reputation.domestic))}${card('Prestígio técnico',String(m.reputation.coachingPrestige))}${card('Perfil de mídia',String(m.reputation.mediaProfile))}${card('Saldo do clube',f?new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(f.balance):'—')}</div></section><section class="mpx-panel mpx-quick"><header><span>ATALHOS DO MANAGER</span><b>Assuma o comando</b></header><div><button data-mpx-route="tactics">▦ <span>Tática</span></button><button data-mpx-route="training">◆ <span>Treino</span></button><button data-mpx-route="press">◉ <span>Imprensa</span></button><button data-mpx-route="staff">♙ <span>Comissão</span></button></div></section></div>`}
function sectionIdentity(m:NonNullable<ReturnType<typeof userManager>>){return `<div class="mpx-two"><section class="mpx-panel"><header><span>IDENTIDADE</span><b>Perfil pessoal</b></header><div class="mpx-detail-grid">${card('Nascimento',m.dateOfBirth)}${card('Cidade natal',m.social.birthCity)}${card('Nacionalidade',m.social.nationality)}${card('Idiomas',m.social.languages.join(', ')||'—')}${card('Estado civil',m.social.maritalStatus)}${card('Filhos',String(m.social.children))}</div></section><section class="mpx-panel"><header><span>FORMAÇÃO</span><b>${esc(m.education.level)}</b></header><div class="mpx-detail-grid">${card('Licença',m.education.licence)}${card('Área',m.education.field??'—')}${card('Cursos',String(m.education.courses.length),m.education.courses.join(' · '))}${card('Estilo visual',m.appearance.style)}${card('Altura',`${m.appearance.heightCm} cm`)}${card('Aparência',`${m.appearance.build} · ${m.appearance.hair}`)}</div></section></div>`}
function sectionKnowledge(m:NonNullable<ReturnType<typeof userManager>>){return `<section class="mpx-panel"><header><span>CONHECIMENTO</span><b>Mapa técnico do treinador</b></header><div class="mpx-knowledge">${Object.entries(m.knowledge).map(([k,v])=>`<article><span>${esc(k.replace(/([A-Z])/g,' $1'))}</span><strong>${v}</strong><i><em style="width:${v}%"></em></i></article>`).join('')}</div></section>`}
function sectionCareer(m:NonNullable<ReturnType<typeof userManager>>){return `<div class="mpx-two"><section class="mpx-panel"><header><span>HISTÓRICO</span><b>Linha do tempo</b></header><div class="mpx-timeline">${[...m.history].reverse().slice(0,20).map(h=>`<article><time>${esc(h.date)}</time><i></i><div><b>${esc(h.type)}</b><p>${esc(h.summary)}</p>${h.impact?`<small>impacto ${h.impact>0?'+':''}${h.impact}</small>`:''}</div></article>`).join('')||'<p>Nenhum evento de carreira registrado.</p>'}</div></section><section class="mpx-panel"><header><span>AMBição</span><b>Objetivos pessoais</b></header>${bar('Troféus',m.ambition.trophyAmbition)}${bar('Reputação',m.ambition.reputationAmbition)}${bar('Seleção nacional',m.ambition.nationalTeamAmbition)}${bar('Projeto de base',m.ambition.youthProjectPreference)}${bar('Estabilidade',m.ambition.stabilityImportance)}</section></div>`}
function sectionPersonality(m:NonNullable<ReturnType<typeof userManager>>){return `<div class="mpx-two"><section class="mpx-panel"><header><span>PERSONALIDADE</span><b>Como você reage</b></header>${Object.entries(m.personality).slice(0,12).map(([k,v])=>bar(k.replace(/([A-Z])/g,' $1'),v)).join('')}</section><section class="mpx-panel"><header><span>TREINO</span><b>Filosofia de desenvolvimento</b></header>${Object.entries(m.training).map(([k,v])=>bar(k.replace(/([A-Z])/g,' $1'),v)).join('')}</section></div>`}
function render(){const w=world(),m=w&&userManager(w),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!m||!host)return;const c=w.clubs.find(x=>x.id===m.currentClubId),v=clubVisual(c?.name??'');host.innerHTML=`<section class="manager-profile-x" style="--mpx-primary:${v.primaryColor};--mpx-secondary:${v.secondaryColor};--mpx-accent:${v.accentColor}"><header class="mpx-hero"><div class="mpx-hero-club">${c?crestMarkup(c.name,'mpx-crest'):''}</div><div><span>MEU TREINADOR · ${esc((c?.name??'CARREIRA').toUpperCase())}</span><h1>${esc(m.nickname||m.name)}</h1><p>Seu personagem dentro do universo. Decisões, reputação, filosofia, relações e carreira evoluem com o tempo.</p></div><aside><small>DIA ${worldCore(w).dayIndex+1}</small><b>${esc(worldCore(w).date)}</b></aside></header><nav class="mpx-tabs">${tabButton('overview','Visão geral','◎')}${tabButton('identity','Identidade','◉')}${tabButton('knowledge','Conhecimento','▥')}${tabButton('career','Carreira','↗')}${tabButton('personality','Filosofia & perfil','◇')}</nav><main>${activeTab==='identity'?sectionIdentity(m):activeTab==='knowledge'?sectionKnowledge(m):activeTab==='career'?sectionCareer(m):activeTab==='personality'?sectionPersonality(m):sectionOverview(m,w)}</main></section>`;bind()}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-mpx-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.mpxTab||'overview';render()});document.querySelectorAll<HTMLButtonElement>('[data-mpx-route]').forEach(b=>b.onclick=()=>{const route=b.dataset.mpxRoute;if(route==='press'){document.querySelector<HTMLButtonElement>('[data-media-hub-nav]')?.click()}else document.querySelector<HTMLButtonElement>(`.game-sidebar [data-view="${route}"]`)?.click()})}
document.addEventListener('touchline:view-rendered',e=>{const d=(e as CustomEvent).detail;if(d?.view==='manager')queueMicrotask(render)});
