import './manager-creation-ui.css';
import type { World } from './engine';
import { archetypeDraft, blankManagerDraft, finalizeManagerCreation, previewManagerDraft, validateManagerDraft, type CreationStep, type ManagerArchetypeId, type ManagerCreationDraft } from './manager-creation';
import { ensureAIManagerCharacters } from './manager-ai-characters';
import { buildManagerPrologue } from './manager-origin-prologue';
import type { ManagerAxis } from './manager-interactions';

export type ManagerCreationComplete=(world:World,clubId:string)=>void;
const STEPS:CreationStep[]=['identity','appearance','social','playingCareer','staffCareer','education','personality','tactics','training','ambition','review'];
const stepLabel:Record<CreationStep,string>={identity:'Identidade',appearance:'Aparência',social:'Vida e origem',playingCareer:'Carreira como jogador',staffCareer:'Experiência profissional',education:'Formação',personality:'Personalidade',tactics:'Futebol',training:'Treino',ambition:'Ambição',review:'Currículo final'};
const archetypeNames:Record<ManagerArchetypeId,string>={exStar:'Ex-craque',careerProfessional:'Profissional de carreira',scholar:'Acadêmico',dataDriven:'Orientado por dados',youthDeveloper:'Formador de jovens',tactician:'Estrategista',peopleManager:'Gestor de pessoas',journeyman:'Journeyman internacional'};
const axisLabels:Record<ManagerAxis,string>={discipline:'Disciplina',empathy:'Empatia',patience:'Paciência',assertiveness:'Assertividade',publicProtection:'Proteção pública',diplomacy:'Diplomacia',confrontation:'Confronto',pragmatism:'Pragmatismo',consistency:'Consistência',mediaSkill:'Mídia',adaptability:'Adaptabilidade',forgiveness:'Capacidade de perdoar'};
const esc=(s:string)=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]!));
const slider=(id:string,label:string,value:number,group:string)=>`<label class="mc-slider"><span>${label}<b data-value-for="${id}">${Math.round(value)}</b></span><input id="${id}" data-group="${group}" type="range" min="0" max="100" value="${Math.round(value)}"></label>`;

export function mountManagerCreation(world:World,mount:HTMLElement,onComplete:ManagerCreationComplete):void{
  let draft:ManagerCreationDraft=blankManagerDraft(world,world.clubs[0]?.id??'');let step=0;let mode:'landing'|'wizard'|'prologue'='landing';
  const render=()=>{
    if(mode==='landing'){mount.innerHTML=landing();bindLanding();return;}
    if(mode==='prologue'){mount.innerHTML=prologue();bindPrologue();return;}
    mount.innerHTML=wizard();bindWizard();
  };
  const landing=()=>`<div class="manager-creation-shell"><section class="mc-hero"><div class="mc-kicker">NOVA CARREIRA · TEMPORADA ${world.season}</div><h1>Antes do primeiro jogo, existe uma história.</h1><p>Você não controla um clube abstrato. Você controla um treinador que chega com passado, formação, reputação, limites, relações e uma ideia própria de futebol. Tudo isso continuará mudando durante a carreira.</p><div class="mc-mode-actions"><button id="mc-advanced" class="mc-primary">Criar minha trajetória</button><button id="mc-quick" class="mc-secondary">Começar por um arquétipo</button></div></section><section class="mc-principles"><article><b>Biografia gera mecânica</b><span>O que você viveu muda autoridade, conhecimento e rede.</span></article><article><b>Preferência não é competência</b><span>Gostar de pressão alta não significa dominá-la no primeiro dia.</span></article><article><b>Você continuará mudando</b><span>Decisões, cursos, fracassos e conquistas reescrevem o personagem.</span></article></section></div>`;
  const top=()=>`<div class="mc-top"><div><span class="mc-kicker">CRIAÇÃO DO TREINADOR</span><h2>${stepLabel[STEPS[step]]}</h2></div><div class="mc-progress"><b>${step+1}/${STEPS.length}</b><span><i style="width:${((step+1)/STEPS.length)*100}%"></i></span></div></div>`;
  const nav=()=>`<aside class="mc-steps">${STEPS.map((s,i)=>`<button data-step="${i}" class="${i===step?'active':''} ${i<step?'done':''}"><span>${i<step?'✓':i+1}</span>${stepLabel[s]}</button>`).join('')}</aside>`;
  const field=(label:string,id:string,value:string,type='text')=>`<label class="mc-field"><span>${label}</span><input id="${id}" type="${type}" value="${esc(value)}"></label>`;
  const clubSelect=()=>`<label class="mc-field"><span>Clube inicial</span><select id="mc-club">${world.clubs.map(c=>`<option value="${c.id}" ${c.id===draft.currentClubId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`;
  const stepBody=()=>{
    const s=STEPS[step];
    if(s==='identity')return `<div class="mc-grid two">${field('Nome','mc-name',draft.name)}${field('Apelido','mc-nickname',draft.nickname??'')}${field('Data de nascimento','mc-dob',draft.dateOfBirth,'date')}<label class="mc-field"><span>Gênero</span><select id="mc-gender"><option value="unspecified">Não informar</option><option value="male" ${draft.gender==='male'?'selected':''}>Masculino</option><option value="female" ${draft.gender==='female'?'selected':''}>Feminino</option><option value="nonbinary" ${draft.gender==='nonbinary'?'selected':''}>Não-binário</option></select></label>${clubSelect()}</div>`;
    if(s==='appearance')return `<div class="mc-grid two">${field('Altura (cm)','mc-height',String(draft.appearance.heightCm),'number')}<label class="mc-field"><span>Biotipo</span><select id="mc-build">${['slim','average','athletic','stocky','large'].map(x=>`<option ${draft.appearance.build===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="mc-field"><span>Estilo</span><select id="mc-style">${['tracksuit','suit','smartCasual','casual'].map(x=>`<option ${draft.appearance.style===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="mc-check"><input id="mc-glasses" type="checkbox" ${draft.appearance.glasses?'checked':''}> Usa óculos</label></div>`;
    if(s==='social')return `<div class="mc-grid two">${field('Nacionalidade','mc-nationality',draft.social.nationality)}${field('Segunda nacionalidade','mc-second',draft.social.secondNationality??'')}${field('Cidade natal','mc-birthcity',draft.social.birthCity)}${field('Idiomas (separados por vírgula)','mc-languages',draft.social.languages.join(', '))}${field('Clube do coração','mc-supported',draft.social.clubSupported??'')}<label class="mc-field"><span>Estado civil</span><select id="mc-marital">${['single','dating','married','divorced','widowed'].map(x=>`<option ${draft.social.maritalStatus===x?'selected':''}>${x}</option>`).join('')}</select></label>${field('Filhos','mc-children',String(draft.social.children),'number')}</div>`;
    if(s==='playingCareer')return `<div class="mc-grid two"><label class="mc-field"><span>Nível máximo como jogador</span><select id="mc-playing-level">${[['none','Nunca jogou profissionalmente'],['amateur','Amador'],['semiPro','Semiprofissional'],['professional','Profissional'],['elite','Elite']].map(([v,l])=>`<option value="${v}" ${draft.playingLevel===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="mc-field"><span>Posição principal</span><select id="mc-position"><option value="">—</option>${['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'].map(x=>`<option ${draft.primaryPlayingPosition===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="mc-note"><b>Carreira detalhada</b><p>O motor aceita clubes, países, temporadas, jogos, títulos, prêmios e capitania. Nesta primeira interface, arquétipos já preenchem históricos completos; o editor cronológico detalhado será o próximo refinamento visual.</p><div class="mc-timeline">${draft.playingCareer.length?draft.playingCareer.map(e=>`<article><b>${esc(e.clubName)}</b><span>${e.country} · ${e.startYear}–${e.endYear} · ${e.position}</span><small>${e.titles.length} títulos · ${e.awards.length} prêmios${e.captain?' · capitão':''}</small></article>`).join(''):'<em>Nenhuma passagem registrada.</em>'}</div></div>`;
    if(s==='staffCareer')return `<div class="mc-note"><b>Experiência antes do primeiro cargo</b><p>Auxiliar, base, análise, scouting, preparação física, direção e outras funções constroem conhecimento diferente.</p><div class="mc-timeline">${draft.staffCareer.length?draft.staffCareer.map(e=>`<article><b>${esc(e.clubName)}</b><span>${e.country} · ${e.startYear}–${e.endYear}</span><small>${e.role} · ${e.achievements.join(', ')||'sem conquista registrada'}</small></article>`).join(''):'<em>Nenhuma experiência anterior registrada.</em>'}</div></div>`;
    if(s==='education')return `<div class="mc-grid two"><label class="mc-field"><span>Escolaridade</span><select id="mc-education">${['none','basic','secondary','technical','bachelor','postgraduate','masters','doctorate'].map(x=>`<option ${draft.education.level===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="mc-field"><span>Licença</span><select id="mc-licence">${['none','regionalC','regionalB','regionalA','continentalC','continentalB','continentalA','continentalPro'].map(x=>`<option ${draft.education.licence===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="mc-chipset"><b>Cursos já concluídos</b>${['refereeing','footballManagement','performanceAnalysis','sportsPsychology','sportsScience','fitness','scouting','dataAnalysis','mediaRelations','leadership','youthDevelopment','setPieces','goalkeeping','sportsLaw','finance'].map(x=>`<label><input type="checkbox" data-course="${x}" ${draft.education.courses.includes(x as any)?'checked':''}>${x}</label>`).join('')}</div>`;
    if(s==='personality')return `<div class="mc-sliders">${(Object.keys(draft.personality) as ManagerAxis[]).map(k=>slider(`mc-p-${k}`,axisLabels[k],draft.personality[k],'personality')).join('')}</div><div class="mc-note"><b>Não existe combinação perfeita.</b><p>Disciplina pode gerar respeito e atrito. Empatia pode fortalecer confiança e também parecer permissiva. Confronto ajuda em alguns contextos e destrói relações em outros.</p></div>`;
    if(s==='tactics')return `<div class="mc-grid two">${field('Formação favorita','mc-formation',draft.tactical.favoriteFormation)}${field('Formações secundárias','mc-secondary',draft.tactical.secondaryFormations.join(', '))}<label class="mc-field"><span>Mentalidade</span><select id="mc-mentality">${['defensive','balanced','positive','attacking'].map(x=>`<option ${draft.tactical.mentality===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="mc-sliders">${slider('mc-possession','Posse',draft.tactical.possessionPreference,'tactics')}${slider('mc-pressing','Pressão',draft.tactical.pressingPreference,'tactics')}${slider('mc-tempo','Ritmo',draft.tactical.tempoPreference,'tactics')}${slider('mc-direct','Verticalidade',draft.tactical.directness,'tactics')}${slider('mc-line','Linha defensiva',draft.tactical.defensiveLinePreference,'tactics')}${slider('mc-counter','Contra-ataque',draft.tactical.counterAttack,'tactics')}${slider('mc-buildback','Saída curta',draft.tactical.buildFromBack,'tactics')}${slider('mc-youth','Uso de jovens',draft.tactical.youthUsage,'tactics')}</div>`;
    if(s==='training')return `<div class="mc-sliders">${slider('mc-tr-intensity','Intensidade',draft.training.intensity,'training')}${slider('mc-tr-physical','Físico',draft.training.physical,'training')}${slider('mc-tr-technical','Técnica',draft.training.technical,'training')}${slider('mc-tr-tactical','Tática',draft.training.tactical,'training')}${slider('mc-tr-individual','Desenvolvimento individual',draft.training.individualDevelopment,'training')}${slider('mc-tr-video','Vídeo e dados',draft.training.videoAnalysis,'training')}${slider('mc-tr-opponent','Preparação do adversário',draft.training.opponentPreparation,'training')}${slider('mc-tr-recovery','Recuperação',draft.training.recovery,'training')}</div>`;
    if(s==='ambition')return `<div class="mc-grid two">${clubSelect()}${field('Clubes dos sonhos','mc-dream',draft.ambition.dreamClubs.join(', '))}${field('Países preferidos','mc-countries',draft.ambition.preferredCountries.join(', '))}${field('Países a evitar','mc-avoid',draft.ambition.avoidCountries.join(', '))}</div><div class="mc-sliders">${slider('mc-amb-trophies','Ambição por títulos',draft.ambition.trophyAmbition,'ambition')}${slider('mc-amb-rep','Importância da reputação',draft.ambition.reputationAmbition,'ambition')}${slider('mc-amb-stability','Estabilidade',draft.ambition.stabilityImportance,'ambition')}${slider('mc-amb-salary','Salário',draft.ambition.salaryImportance,'ambition')}${slider('mc-amb-youth','Projeto de base',draft.ambition.youthProjectPreference,'ambition')}${slider('mc-amb-national','Seleção nacional',draft.ambition.nationalTeamAmbition,'ambition')}</div>`;
    const p=previewManagerDraft(world,draft);return `<div class="mc-review"><div class="mc-cv"><span class="mc-kicker">CURRÍCULO DE ENTRADA</span><h2>${esc(draft.name)}</h2><p>${esc(p.identityLabel)}</p><dl><div><dt>Origem</dt><dd>${esc(p.careerLabel)}</dd></div><div><dt>Formação</dt><dd>${esc(p.educationLabel)}</dd></div><div><dt>Identidade tática</dt><dd>${esc(p.tacticalLabel)}</dd></div></dl></div><div><h3>Forças de partida</h3>${p.strengths.map(x=>`<span class="mc-good">${esc(x)}</span>`).join('')||'<em>Nenhuma força excepcional declarada.</em>'}<h3>Riscos e desafios</h3>${p.risks.map(x=>`<span class="mc-risk">${esc(x)}</span>`).join('')||'<em>Perfil equilibrado.</em>'}<h3>Coerência</h3>${p.issues.map(x=>`<div class="mc-issue ${x.severity}">${esc(x.message)}</div>`).join('')||'<div class="mc-issue info">Ficha coerente e pronta para iniciar.</div>'}</div></div>`;
  };
  const wizard=()=>`<div class="manager-creation-shell wizard">${top()}<div class="mc-wizard-layout">${nav()}<main class="mc-panel">${stepBody()}<div class="mc-footer"><button id="mc-back" class="mc-secondary" ${step===0?'disabled':''}>Voltar</button><div>${step===STEPS.length-1?'<button id="mc-finish" class="mc-primary">Assinar contrato e começar</button>':'<button id="mc-next" class="mc-primary">Continuar</button>'}</div></div></main><aside class="mc-live">${livePreview()}</aside></div></div>`;
  const livePreview=()=>{const p=previewManagerDraft(world,draft);return `<span class="mc-kicker">PRÉVIA EM TEMPO REAL</span><h3>${esc(draft.name)}</h3><p>${esc(p.careerLabel)}</p><div class="mc-live-line"><span>Futebol</span><b>${esc(draft.tactical.favoriteFormation)} · ${draft.tactical.mentality}</b></div><div class="mc-live-line"><span>Treino</span><b>${draft.training.intensity>=70?'Intenso':draft.training.intensity<=40?'Controlado':'Moderado'}</b></div><div class="mc-live-line"><span>Personalidade</span><b>${topTraits()}</b></div><small>Esta ficha define seu ponto de partida, não seu destino.</small>`;};
  const topTraits=()=>Object.entries(draft.personality).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k])=>axisLabels[k as ManagerAxis]).join(' · ');
  const sync=()=>{
    const q=<T extends HTMLInputElement|HTMLSelectElement>(id:string)=>mount.querySelector<T>(`#${id}`);
    if(STEPS[step]==='identity'){draft.name=q<HTMLInputElement>('mc-name')?.value||draft.name;draft.nickname=q<HTMLInputElement>('mc-nickname')?.value||undefined;draft.dateOfBirth=q<HTMLInputElement>('mc-dob')?.value||draft.dateOfBirth;draft.gender=(q<HTMLSelectElement>('mc-gender')?.value as any)||draft.gender;const c=q<HTMLSelectElement>('mc-club')?.value;if(c){draft.currentClubId=c;draft.ambition.startingClubId=c;}}
    if(STEPS[step]==='appearance'){draft.appearance.heightCm=Number(q<HTMLInputElement>('mc-height')?.value)||draft.appearance.heightCm;draft.appearance.build=(q<HTMLSelectElement>('mc-build')?.value as any)||draft.appearance.build;draft.appearance.style=(q<HTMLSelectElement>('mc-style')?.value as any)||draft.appearance.style;draft.appearance.glasses=!!q<HTMLInputElement>('mc-glasses')?.checked;}
    if(STEPS[step]==='social'){draft.social.nationality=q<HTMLInputElement>('mc-nationality')?.value||draft.social.nationality;draft.social.secondNationality=q<HTMLInputElement>('mc-second')?.value||undefined;draft.social.birthCity=q<HTMLInputElement>('mc-birthcity')?.value||draft.social.birthCity;draft.social.languages=(q<HTMLInputElement>('mc-languages')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);draft.social.clubSupported=q<HTMLInputElement>('mc-supported')?.value||undefined;draft.social.maritalStatus=(q<HTMLSelectElement>('mc-marital')?.value as any)||draft.social.maritalStatus;draft.social.children=Number(q<HTMLInputElement>('mc-children')?.value)||0;}
    if(STEPS[step]==='playingCareer'){draft.playingLevel=(q<HTMLSelectElement>('mc-playing-level')?.value as any)||draft.playingLevel;draft.primaryPlayingPosition=(q<HTMLSelectElement>('mc-position')?.value as any)||undefined;}
    if(STEPS[step]==='education'){draft.education.level=(q<HTMLSelectElement>('mc-education')?.value as any)||draft.education.level;draft.education.licence=(q<HTMLSelectElement>('mc-licence')?.value as any)||draft.education.licence;draft.education.courses=[...mount.querySelectorAll<HTMLInputElement>('[data-course]:checked')].map(x=>x.dataset.course as any);}
    if(STEPS[step]==='personality')for(const k of Object.keys(draft.personality) as ManagerAxis[])draft.personality[k]=Number(q<HTMLInputElement>(`mc-p-${k}`)?.value??draft.personality[k]);
    if(STEPS[step]==='tactics'){draft.tactical.favoriteFormation=q<HTMLInputElement>('mc-formation')?.value||draft.tactical.favoriteFormation;draft.tactical.secondaryFormations=(q<HTMLInputElement>('mc-secondary')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);draft.tactical.mentality=(q<HTMLSelectElement>('mc-mentality')?.value as any)||draft.tactical.mentality;draft.tactical.possessionPreference=Number(q<HTMLInputElement>('mc-possession')?.value);draft.tactical.pressingPreference=Number(q<HTMLInputElement>('mc-pressing')?.value);draft.tactical.tempoPreference=Number(q<HTMLInputElement>('mc-tempo')?.value);draft.tactical.directness=Number(q<HTMLInputElement>('mc-direct')?.value);draft.tactical.defensiveLinePreference=Number(q<HTMLInputElement>('mc-line')?.value);draft.tactical.counterAttack=Number(q<HTMLInputElement>('mc-counter')?.value);draft.tactical.buildFromBack=Number(q<HTMLInputElement>('mc-buildback')?.value);draft.tactical.youthUsage=Number(q<HTMLInputElement>('mc-youth')?.value);}
    if(STEPS[step]==='training'){draft.training.intensity=Number(q<HTMLInputElement>('mc-tr-intensity')?.value);draft.training.physical=Number(q<HTMLInputElement>('mc-tr-physical')?.value);draft.training.technical=Number(q<HTMLInputElement>('mc-tr-technical')?.value);draft.training.tactical=Number(q<HTMLInputElement>('mc-tr-tactical')?.value);draft.training.individualDevelopment=Number(q<HTMLInputElement>('mc-tr-individual')?.value);draft.training.videoAnalysis=Number(q<HTMLInputElement>('mc-tr-video')?.value);draft.training.opponentPreparation=Number(q<HTMLInputElement>('mc-tr-opponent')?.value);draft.training.recovery=Number(q<HTMLInputElement>('mc-tr-recovery')?.value);}
    if(STEPS[step]==='ambition'){const c=q<HTMLSelectElement>('mc-club')?.value;if(c){draft.currentClubId=c;draft.ambition.startingClubId=c;}draft.ambition.dreamClubs=(q<HTMLInputElement>('mc-dream')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);draft.ambition.preferredCountries=(q<HTMLInputElement>('mc-countries')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);draft.ambition.avoidCountries=(q<HTMLInputElement>('mc-avoid')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);draft.ambition.trophyAmbition=Number(q<HTMLInputElement>('mc-amb-trophies')?.value);draft.ambition.reputationAmbition=Number(q<HTMLInputElement>('mc-amb-rep')?.value);draft.ambition.stabilityImportance=Number(q<HTMLInputElement>('mc-amb-stability')?.value);draft.ambition.salaryImportance=Number(q<HTMLInputElement>('mc-amb-salary')?.value);draft.ambition.youthProjectPreference=Number(q<HTMLInputElement>('mc-amb-youth')?.value);draft.ambition.nationalTeamAmbition=Number(q<HTMLInputElement>('mc-amb-national')?.value);}
    draft.age=Math.max(18,world.season-Number(draft.dateOfBirth.slice(0,4)));
  };
  const bindLanding=()=>{mount.querySelector('#mc-advanced')?.addEventListener('click',()=>{draft=blankManagerDraft(world,world.clubs[0]?.id??'');mode='wizard';render();});mount.querySelector('#mc-quick')?.addEventListener('click',()=>{mount.innerHTML=quickSelect();bindQuick();});};
  const quickSelect=()=>`<div class="manager-creation-shell"><section class="mc-hero compact"><div class="mc-kicker">ORIGENS RÁPIDAS</div><h1>Escolha um passado. Depois edite o que quiser.</h1></section><div class="mc-archetypes">${(Object.keys(archetypeNames) as ManagerArchetypeId[]).map(id=>`<button data-archetype="${id}"><b>${archetypeNames[id]}</b><span>${archetypeDescription(id)}</span></button>`).join('')}</div><button id="mc-quick-back" class="mc-secondary">Voltar</button></div>`;
  const bindQuick=()=>{mount.querySelector('#mc-quick-back')?.addEventListener('click',render);mount.querySelectorAll<HTMLElement>('[data-archetype]').forEach(el=>el.addEventListener('click',()=>{draft=archetypeDraft(world,world.clubs[0]?.id??'',el.dataset.archetype as ManagerArchetypeId);step=0;mode='wizard';render();}));};
  const bindWizard=()=>{
    mount.querySelectorAll<HTMLInputElement>('input[type="range"]').forEach(i=>i.addEventListener('input',()=>{const out=mount.querySelector(`[data-value-for="${i.id}"]`);if(out)out.textContent=i.value;}));
    mount.querySelector('#mc-back')?.addEventListener('click',()=>{sync();step=Math.max(0,step-1);render();});
    mount.querySelector('#mc-next')?.addEventListener('click',()=>{sync();step=Math.min(STEPS.length-1,step+1);render();});
    mount.querySelectorAll<HTMLElement>('[data-step]').forEach(el=>el.addEventListener('click',()=>{sync();step=Number(el.dataset.step);render();}));
    mount.querySelector('#mc-finish')?.addEventListener('click',()=>{sync();const errors=validateManagerDraft(world,draft).filter(x=>x.severity==='error');if(errors.length){alert(errors.map(x=>x.message).join('\n'));return;}finalizeManagerCreation(world,draft,true);ensureAIManagerCharacters(world);mode='prologue';render();});
  };
  const prologue=()=>{const p=buildManagerPrologue(world,draft.currentClubId);if(!p)return '<div class="manager-creation-shell">Erro ao gerar prólogo.</div>';return `<div class="manager-creation-shell prologue"><section class="mc-hero compact"><div class="mc-kicker">PRIMEIRO DIA</div><h1>${esc(p.title)}</h1><p>${esc(p.subtitle)}</p></section><div class="mc-prologue-grid"><section class="mc-cv"><h3>${esc(p.identity)}</h3><p>${esc(p.careerSummary)}</p><p><b>Ideia de futebol:</b> ${esc(p.footballIdentity)}</p><p><b>Método:</b> ${esc(p.trainingIdentity)}</p><h3>Primeiros desafios</h3>${p.stakes.map(x=>`<div class="mc-stake">${esc(x)}</div>`).join('')}</section><section><h3>Como o clube recebe você</h3>${p.firstImpressions.map(x=>`<article class="mc-impression ${x.label}"><div><b>${x.audience}</b><strong>${x.score}</strong></div><span>${esc(x.headline)}</span><small>${esc(x.reason)}</small></article>`).join('')}</section></div><section class="mc-opening"><h3>As primeiras perguntas da carreira</h3>${p.openingQuestions.map(x=>`<p>${esc(x)}</p>`).join('')}</section><button id="mc-enter-world" class="mc-primary large">Entrar no centro do manager</button></div>`;};
  const bindPrologue=()=>mount.querySelector('#mc-enter-world')?.addEventListener('click',()=>onComplete(world,draft.currentClubId));
  render();
}

function archetypeDescription(id:ManagerArchetypeId):string{const d:Record<ManagerArchetypeId,string>={exStar:'Prestígio imediato, enorme cobrança e pouca tolerância para parecer apenas um nome.',careerProfessional:'Bagagem de campo e comissão técnica; autoridade sólida e perfil pragmático.',scholar:'Formação avançada, leitura humana e caminho mais lento para construir reputação.',dataDriven:'Sem fama de campo, mas forte em análise, scouting e decisões baseadas em evidência.',youthDeveloper:'Paciência, formação de atletas e forte identidade com categorias de base.',tactician:'Especialista em estrutura de jogo, treino tático e adaptação de sistemas.',peopleManager:'Força em relações humanas, mídia e construção de vestiário.',journeyman:'Experiência internacional, idiomas, rede ampla e grande adaptabilidade.'};return d[id];}
