import type { World } from './engine';
import { onWorldEvent } from './event-bus';
import { managerInteractionState,managerPlayerRelationship,type ManagerInteraction,type InteractionOption } from './manager-interactions';
import { recordManagerStatement,recentManagerStatements,statementForInteraction,type ManagerBehaviorTag,type PublicStatement } from './manager-social-memory-v1';
import type { DialogueTopic } from './human-dialogue-bank-v1';

const wired=new WeakSet<World>();
const topicFor=(i:ManagerInteraction):DialogueTopic=>i.kind==='discipline'?'discipline':i.kind==='performance'?'performance':i.kind==='transfer'?'transfer':i.kind==='contract'?'contract':i.kind==='dressingRoom'||i.kind==='conflict'?'dressingRoom':i.kind==='personal'||i.kind==='support'?'personal':i.kind==='leadership'?'leadership':'pressure';
function tagsFor(o:InteractionOption):ManagerBehaviorTag[]{const tags:ManagerBehaviorTag[]=[];if(o.tone==='supportive'||o.empathySignal>=2)tags.push('supportive');if(o.tone==='harsh'||o.confrontationSignal>=4)tags.push('harsh','confrontational');if(o.tone==='silent')tags.push('evasive');if(o.tone==='calm')tags.push('diplomatic');if(o.id==='public_defense_private_charge'||o.id==='protect')tags.push('protective');if(o.id==='confirm_facts')tags.push('transparent');if(o.id==='mediate'||o.id==='professional_support')tags.push('accountable');if(!tags.length)tags.push('consistent');return[...new Set(tags)]}
function sourceFor(i:ManagerInteraction):PublicStatement['source']{return i.kind==='transfer'||i.kind==='contract'?'agentConversation':i.kind==='media'?'mediaInterview':i.kind==='dressingRoom'||i.kind==='conflict'||i.kind==='leadership'?'staffConversation':'playerConversation'}
function conflicts(publicTags:ManagerBehaviorTag[],privateTags:ManagerBehaviorTag[]){const publicSoft=publicTags.some(x=>x==='supportive'||x==='protective'||x==='diplomatic'||x==='accountable'),publicHard=publicTags.some(x=>x==='harsh'||x==='confrontational'),privateSoft=privateTags.some(x=>x==='supportive'||x==='protective'||x==='diplomatic'||x==='accountable'),privateHard=privateTags.some(x=>x==='harsh'||x==='confrontational');return(publicSoft&&privateHard)||(publicHard&&privateSoft)}
export function captureResolvedManagerInteraction(world:World,interactionId:string,date?:string){const interaction=managerInteractionState(world).interactions.find(x=>x.id===interactionId);if(!interaction||interaction.status!=='resolved'||!interaction.chosenOptionId)return;const existing=statementForInteraction(world,interaction.managerId,interaction.id);if(existing)return existing;const option=interaction.options.find(x=>x.id===interaction.chosenOptionId);if(!option)return;const topic=topicFor(interaction),tags=tagsFor(option),recentPublic=recentManagerStatements(world,interaction.managerId,{topic,playerId:interaction.playerId,limit:8}).find(x=>x.source==='pressConference'||x.source==='mediaInterview');if(recentPublic&&conflicts(recentPublic.behavior,tags)){tags.push('inconsistent');const rel=interaction.playerId?managerPlayerRelationship(world,interaction.clubId,interaction.playerId):undefined;if(rel){rel.trust=Math.max(0,rel.trust-2);rel.respect=Math.max(0,rel.respect-1);rel.friction=Math.min(100,rel.friction+2)}}return recordManagerStatement(world,{managerId:interaction.managerId,clubId:interaction.clubId,date:date??interaction.resolvedDate??interaction.date,topic,text:interaction.chosenText??option.label,behavior:[...new Set(tags)],source:sourceFor(interaction),playerId:interaction.playerId,interactionId:interaction.id,importance:interaction.severity>=8?4:interaction.severity>=5?3:2})}
export function wireManagerSocialMemoryRuntime(world:World){if(wired.has(world))return;wired.add(world);onWorldEvent(world,'ManagerInteractionResolved',event=>{const interactionId=String(event.payload.interactionId??'');if(!interactionId)return;const statement=captureResolvedManagerInteraction(world,interactionId,event.date);if(statement){event.payload.socialMemoryStatementId=statement.id;event.payload.socialMemoryBehavior=[...statement.behavior]}})}
function activate(){const world=window.__touchlineWorld;if(world)wireManagerSocialMemoryRuntime(world)}
if(typeof window!=='undefined'){window.addEventListener('touchline:world-ready',activate);window.addEventListener('touchline:world-hydrated',activate);window.addEventListener('touchline:save-loaded',activate);queueMicrotask(activate)}
