import type { World } from './engine';
import { userManager, type ManagerCharacter, type ManagerKnowledge } from './manager-character';
import { institutionalState } from './institutional-memory';
import { managerOnboardingState, onboardingChoices } from './manager-onboarding';

export type ManagerCareerProfile={manager:ManagerCharacter;clubName:string;authority:number;board:{trust:number;respect:number;alignment:number;communication:number;credibility:number};pressure:{supporters:number;media:number;dressingRoom:number;financial:number;board:number};knowledgeRank:{key:keyof ManagerKnowledge;value:number}[];careerAge:number;identity:string;legacy:string[];openingChoices:string[]};
const clubName=(world:World,id:string)=>world.clubs.find(c=>c.id===id)?.name??id;
export function buildManagerCareerProfile(world:World):ManagerCareerProfile|undefined{
 const manager=userManager(world);if(!manager)return;const inst=institutionalState(world),rel=inst.relationships.get(manager.currentClubId),pressure=inst.pressure.get(manager.currentClubId);const room=(world as any).__dressingRoomState?.get?.(manager.currentClubId);
 const board=rel??{trust:50,respect:50,alignment:50,communication:50,credibility:50};const p=pressure??{supporters:30,media:30,dressingRoom:30,financial:30,board:30};
 const knowledgeRank=(Object.entries(manager.knowledge) as [keyof ManagerKnowledge,number][]).sort((a,b)=>b[1]-a[1]).map(([key,value])=>({key,value}));
 const onboarding=managerOnboardingState(world,manager.currentClubId);const openingChoices=Object.values(onboarding?.resolved??{}).map(id=>onboardingChoices.find(c=>c.id===id)?.title??String(id));
 const legacy:string[]=[];if(manager.reputation.formerPlayerPrestige>=65)legacy.push('Ex-jogador de grande prestígio');if(manager.knowledge.youthDevelopment>=70)legacy.push('Formador de jovens');if(manager.knowledge.dataAnalysis>=70)legacy.push('Treinador orientado por dados');if(manager.personality.discipline>=70)legacy.push('Liderança disciplinadora');if(manager.personality.empathy>=70)legacy.push('Gestor próximo do elenco');if(manager.careerPoints>=25)legacy.push('Carreira marcada por decisões de alto impacto');
 return{manager,clubName:clubName(world,manager.currentClubId),authority:room?.managerAuthority??Math.round((board.respect+board.credibility)/2),board:{trust:board.trust,respect:board.respect,alignment:board.alignment,communication:board.communication,credibility:board.credibility},pressure:{supporters:p.supporters,media:p.media,dressingRoom:p.dressingRoom,financial:p.financial,board:p.board},knowledgeRank,careerAge:Math.max(0,world.season-manager.createdSeason),identity:`${manager.tactical.favoriteFormation} · ${manager.tactical.mentality} · pressão ${manager.tactical.pressingPreference} · jovens ${manager.tactical.youthUsage}`,legacy,openingChoices};
}
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const bar=(label:string,value:number)=>`<div class="manager-profile-bar"><span>${esc(label)}</span><i><b style="width:${Math.max(0,Math.min(100,value))}%"></b></i><strong>${Math.round(value)}</strong></div>`;
export function renderManagerCareerProfile(world:World):string{
 const p=buildManagerCareerProfile(world);if(!p)return '<section class="card"><h2>Treinador</h2><p>Nenhum treinador controlável foi criado neste mundo.</p></section>';const m=p.manager;
 return `<header><div><span class="eyebrow">MEU TREINADOR · TEMPORADA ${world.season}</span><h1>${esc(m.name)}</h1><p>${esc(p.clubName)} · ${m.age+p.careerAge} anos · ${esc(m.social.nationality)} · ${p.careerAge===0?'temporada de estreia':`${p.careerAge+1}ª temporada da jornada`}</p></div></header>
 <section class="cards"><article class="card metric"><span>Reputação doméstica</span><strong>${m.reputation.domestic}</strong></article><article class="card metric"><span>Prestígio técnico</span><strong>${m.reputation.coachingPrestige}</strong></article><article class="card metric"><span>Autoridade</span><strong>${p.authority}</strong></article><article class="card metric"><span>Pontos de carreira</span><strong>${m.careerPoints}</strong></article></section>
 <div class="manager-profile-grid"><section class="card"><div class="section-title"><h2>Identidade viva</h2><span>quem você é hoje</span></div><p class="manager-identity">${esc(p.identity)}</p><div class="manager-tags">${(p.legacy.length?p.legacy:['Identidade ainda em construção']).map(x=>`<span>${esc(x)}</span>`).join('')}</div><h3>Primeiras declarações da carreira</h3>${p.openingChoices.length?`<div class="career-list">${p.openingChoices.map(x=>`<div><b>${esc(x)}</b></div>`).join('')}</div>`:'<p>O primeiro dia ainda não foi concluído.</p>'}</section>
 <section class="card"><div class="section-title"><h2>Conhecimento</h2><span>competência real</span></div>${p.knowledgeRank.slice(0,8).map(x=>bar(String(x.key),x.value)).join('')}</section>
 <section class="card"><div class="section-title"><h2>Relação com a diretoria</h2><span>capital político</span></div>${bar('Confiança',p.board.trust)}${bar('Respeito',p.board.respect)}${bar('Alinhamento',p.board.alignment)}${bar('Comunicação',p.board.communication)}${bar('Credibilidade',p.board.credibility)}</section>
 <section class="card"><div class="section-title"><h2>Pressão ao redor</h2><span>o ambiente reage</span></div>${bar('Torcida',p.pressure.supporters)}${bar('Imprensa',p.pressure.media)}${bar('Vestiário',p.pressure.dressingRoom)}${bar('Diretoria',p.pressure.board)}${bar('Financeira',p.pressure.financial)}</section></div>
 <section class="card manager-history"><div class="section-title"><h2>Linha do tempo da carreira</h2><span>${m.history.length} marcos</span></div>${[...m.history].reverse().map(h=>`<article><time>${esc(h.date)}</time><div><b>${esc(h.summary)}</b><small>${esc(h.type)}${h.impact?` · impacto ${h.impact>0?'+':''}${h.impact}`:''}</small></div></article>`).join('')}</section>`;
}
