import type { World } from './engine';
import { emitWorldEvent, onWorldEvent } from './event-bus';
import { institutionalState } from './institutional-memory';
import { clubDressingRoom } from './dressing-room';
import { managerCharacterState, managerByClub, userManager, type ManagerCharacter } from './manager-character';

export type ManagerContractStatus='active'|'expiring'|'terminated'|'expired';
export type ManagerEmploymentContract={id:string;managerId:string;clubId:string;startDate:string;endDate:string;salaryWeekly:number;releaseCompensation:number;status:ManagerContractStatus;autonomy:number;objectives:{leagueTarget:number;youthTarget:number;styleTarget:number;financialTarget:number};};
export type JobSecurityBand='untouchable'|'secure'|'stable'|'underPressure'|'seriousRisk'|'critical';
export type ManagerJobAssessment={managerId:string;clubId:string;date:string;score:number;band:JobSecurityBand;results:number;board:number;supporters:number;dressingRoom:number;style:number;development:number;reputationShield:number;reasons:string[]};
export type ManagerJobOffer={id:string;managerId:string;fromClubId:string;date:string;expires:string;salaryWeekly:number;contractYears:number;autonomy:number;projectScore:number;status:'pending'|'accepted'|'rejected'|'withdrawn';reason:string;};
export type ManagerEmploymentState={contracts:Map<string,ManagerEmploymentContract>;assessments:Map<string,ManagerJobAssessment>;offers:ManagerJobOffer[];lastEvaluationDate?:string;wired:boolean};
export type ManagerEmploymentSnapshot={contracts:[string,ManagerEmploymentContract][];assessments:[string,ManagerJobAssessment][];offers:ManagerJobOffer[];lastEvaluationDate?:string};
const states=new WeakMap<World,ManagerEmploymentState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const addDays=(iso:string,d:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)};
const year=(iso:string)=>Number(iso.slice(0,4));
const dateDiff=(a:string,b:string)=>Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/86400000);
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:string)=>{const x=Math.sin(hash(s)*12.9898)*43758.5453;return x-Math.floor(x)};

function initialContract(world:World,m:ManagerCharacter):ManagerEmploymentContract{
 const club=world.clubs.find(c=>c.id===m.currentClubId);const rep=club?.reputation??60;const years=2+(hash(`${m.id}-contract`)%3);const start=`${world.season}-07-01`;return{id:`mgr-contract-${m.id}-${world.season}`,managerId:m.id,clubId:m.currentClubId,startDate:start,endDate:`${world.season+years}-06-30`,salaryWeekly:Math.round(2500+rep*180+m.reputation.coachingPrestige*115),releaseCompensation:Math.round(80000+rep*9000),status:'active',autonomy:Math.round(clamp(42+m.reputation.coachingPrestige*.35+(m.playingLevel==='elite'?12:0))),objectives:{leagueTarget:Math.round(clamp(22-(rep-60)*.32,1,20)),youthTarget:m.tactical.youthUsage>=65?65:45,styleTarget:60,financialTarget:55}};
}
export function managerEmploymentState(world:World):ManagerEmploymentState{let s=states.get(world);if(!s){s={contracts:new Map(),assessments:new Map(),offers:[],wired:false};states.set(world,s);}for(const m of managerCharacterState(world).characters.values())if(m.currentClubId&&!s.contracts.has(m.id))s.contracts.set(m.id,initialContract(world,m));if(!s.wired){s.wired=true;wireEmploymentEvents(world);}return s;}
export function managerContract(world:World,managerId:string){return managerEmploymentState(world).contracts.get(managerId);}
function leaguePosition(world:World,clubId:string){const table=Object.values(world.standings).sort((a,b)=>b.points-a.points||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf);const i=table.findIndex(x=>x.clubId===clubId);return i<0?Math.ceil(world.clubs.length/2):i+1;}
function pointsPerGame(world:World,clubId:string){const s=world.standings[clubId];return !s||!s.played?1.35:s.points/s.played;}
function styleFit(world:World,m:ManagerCharacter){const club=world.clubs.find(c=>c.id===m.currentClubId);if(!club)return 50;const t=club.tactics,p=m.tactical;const diff=Math.abs(t.pressing-p.pressingPreference)+Math.abs(t.tempo-p.tempoPreference)+Math.abs(t.defensiveLine-p.defensiveLinePreference)+Math.abs(t.width-p.widthPreference);return clamp(100-diff*.22);}
function resultScore(world:World,m:ManagerCharacter,c:ManagerEmploymentContract){const position=leaguePosition(world,c.clubId),target=Math.max(1,Math.min(world.clubs.length,c.objectives.leagueTarget)),gap=position-target,ppg=pointsPerGame(world,c.clubId);return clamp(68-gap*7+(ppg-1.4)*16);}
function reputationShield(m:ManagerCharacter){return clamp((m.reputation.coachingPrestige*.55+m.reputation.formerPlayerPrestige*.25+m.reputation.domestic*.2)*.55,0,50);}
function band(score:number):JobSecurityBand{return score>=88?'untouchable':score>=72?'secure':score>=55?'stable':score>=40?'underPressure':score>=25?'seriousRisk':'critical';}
export function assessManagerJob(world:World,m:ManagerCharacter,date:string):ManagerJobAssessment|undefined{
 if(!m.currentClubId)return;const c=managerContract(world,m.id);if(!c)return;const inst=institutionalState(world),rel=inst.relationships.get(m.currentClubId),press=inst.pressure.get(m.currentClubId),room=clubDressingRoom(world,m.currentClubId);const results=resultScore(world,m,c),board=clamp(((rel?.trust??55)+(rel?.alignment??55)+(rel?.credibility??55))/3),supporters=clamp(100-(press?.supporters??35)),dressing=clamp(((room?.chemistry??55)+(room?.managerAuthority??55)+(100-(press?.dressingRoom??30)))/3),style=styleFit(world,m),development=clamp(m.knowledge.youthDevelopment*.35+m.tactical.youthUsage*.35+50*.3),shield=reputationShield(m);let score=results*.38+board*.2+supporters*.11+dressing*.14+style*.08+development*.09+shield*.08;const reasons:string[]=[];if(results<35)reasons.push('resultados abaixo do esperado');if(board<40)reasons.push('relação deteriorada com a diretoria');if(supporters<40)reasons.push('forte pressão da torcida');if(dressing<40)reasons.push('vestiário fragilizado');if(style<40)reasons.push('identidade praticada distante do projeto');if(shield>=30)reasons.push('histórico e reputação ainda oferecem proteção');score=clamp(score);const a={managerId:m.id,clubId:m.currentClubId,date,score,band:band(score),results,board,supporters,dressingRoom:dressing,style,development,reputationShield:shield,reasons};managerEmploymentState(world).assessments.set(m.id,a);return a;
}
function terminate(world:World,m:ManagerCharacter,date:string,reason:string){const state=managerEmploymentState(world),c=state.contracts.get(m.id);if(c)c.status='terminated';const oldClub=m.currentClubId;m.currentClubId='';m.history.push({date,type:'sacked',summary:`Demitido do ${oldClub}: ${reason}.`,impact:-8});m.careerPoints=Math.max(0,m.careerPoints-4);emitWorldEvent(world,{type:'ManagerSacked',date,actorIds:[m.id],clubIds:[oldClub],importance:5,summary:`${m.name} foi demitido.`,payload:{managerId:m.id,clubId:oldClub,reason,compensation:c?.releaseCompensation??0}});}
function maybeSack(world:World,m:ManagerCharacter,a:ManagerJobAssessment,date:string){const progress=world.fixtures.filter(f=>f.played).length/Math.max(1,world.fixtures.length);if(progress<.12)return;if(a.score>=25)return;const chance=clamp((25-a.score)/20+(a.results<25?.25:0)+(a.board<25?.2:0),0,0.9);if(pseudo(`${m.id}-${date}-sack`)<chance)terminate(world,m,date,a.reasons.join(', ')||'perda de confiança institucional');}
function maybeRenew(world:World,m:ManagerCharacter,date:string){const c=managerContract(world,m.id);if(!c||c.status==='terminated')return;const days=dateDiff(c.endDate,date);if(days<=180&&days>0)c.status='expiring';if(days>120||days<0)return;const a=managerEmploymentState(world).assessments.get(m.id)??assessManagerJob(world,m,date);if(!a)return;if(a.score>=58&&pseudo(`${m.id}-${date}-renew`)<.035){const years=a.score>=78?3:2;c.endDate=`${year(c.endDate)+years}-06-30`;c.status='active';c.salaryWeekly=Math.round(c.salaryWeekly*(1.08+(a.score-55)/300));c.releaseCompensation=Math.round(c.releaseCompensation*1.25);emitWorldEvent(world,{type:'ManagerContractRenewed',date,actorIds:[m.id],clubIds:[m.currentClubId],importance:3,summary:`${m.name} renovou seu contrato.`,payload:{managerId:m.id,endDate:c.endDate,salaryWeekly:c.salaryWeekly}});}}
function candidateClubs(world:World,m:ManagerCharacter){return world.clubs.filter(c=>c.id!==m.currentClubId&&c.reputation>=Math.max(48,m.reputation.domestic-20)&&c.reputation<=m.reputation.domestic+28);}
function maybeApproach(world:World,m:ManagerCharacter,date:string){if(!m.currentClubId)return;const state=managerEmploymentState(world);if(state.offers.some(o=>o.managerId===m.id&&o.status==='pending'))return;if(m.reputation.coachingPrestige<45)return;if(pseudo(`${m.id}-${date}-approach`)>.004)return;const clubs=candidateClubs(world,m);if(!clubs.length)return;const club=clubs[Math.floor(pseudo(`${m.id}-${date}-club`)*clubs.length)];const current=world.clubs.find(c=>c.id===m.currentClubId);if(!club||!current)return;const project=clamp(50+(club.reputation-current.reputation)*1.1+(m.ambition.dreamClubs.includes(club.name)?25:0));const offer:ManagerJobOffer={id:`job-offer-${m.id}-${club.id}-${date}`,managerId:m.id,fromClubId:club.id,date,expires:addDays(date,7),salaryWeekly:Math.round(3500+club.reputation*220+m.reputation.coachingPrestige*140),contractYears:2+(club.reputation>=80?1:0),autonomy:Math.round(clamp(45+m.reputation.coachingPrestige*.35)),projectScore:project,status:'pending',reason:`O ${club.name} vê ${m.name} como candidato compatível com o projeto.`};state.offers.push(offer);emitWorldEvent(world,{type:'ManagerJobOffer',date,actorIds:[m.id],clubIds:[club.id,m.currentClubId],importance:4,summary:`${club.name} procurou ${m.name}.`,payload:{offerId:offer.id,salaryWeekly:offer.salaryWeekly,autonomy:offer.autonomy,projectScore:offer.projectScore}});}
export function resolveManagerJobOffer(world:World,offerId:string,accept:boolean,date:string){const s=managerEmploymentState(world),o=s.offers.find(x=>x.id===offerId&&x.status==='pending');if(!o)return false;const m=managerCharacterState(world).characters.get(o.managerId);if(!m)return false;o.status=accept?'accepted':'rejected';if(!accept){emitWorldEvent(world,{type:'ManagerJobOfferRejected',date,actorIds:[m.id],clubIds:[o.fromClubId],importance:2,summary:`${m.name} recusou a proposta.`,payload:{offerId:o.id}});return true;}const old=m.currentClubId;const oldContract=s.contracts.get(m.id);if(oldContract)oldContract.status='terminated';m.currentClubId=o.fromClubId;const start=date,end=`${year(date)+o.contractYears}-${date.slice(5)}`;s.contracts.set(m.id,{id:`mgr-contract-${m.id}-${date}`,managerId:m.id,clubId:o.fromClubId,startDate:start,endDate:end,salaryWeekly:o.salaryWeekly,releaseCompensation:Math.round(o.salaryWeekly*52*1.5),status:'active',autonomy:o.autonomy,objectives:{leagueTarget:Math.max(1,Math.round(20-(world.clubs.find(c=>c.id===o.fromClubId)?.reputation??60-60)*.25)),youthTarget:m.tactical.youthUsage,styleTarget:60,financialTarget:55}});m.history.push({date,type:'jobMove',summary:`Deixou ${old||'o mercado'} para assumir ${o.fromClubId}.`,impact:5});emitWorldEvent(world,{type:'ManagerHired',date,actorIds:[m.id],clubIds:[o.fromClubId,...(old?[old]:[])],importance:5,summary:`${m.name} assumiu um novo clube.`,payload:{managerId:m.id,from:old,to:o.fromClubId,offerId:o.id}});return true;}
function expireOffers(world:World,date:string){for(const o of managerEmploymentState(world).offers)if(o.status==='pending'&&o.expires<date){o.status='withdrawn';emitWorldEvent(world,{type:'ManagerJobOfferWithdrawn',date,actorIds:[o.managerId],clubIds:[o.fromClubId],importance:1,summary:'Uma proposta de trabalho expirou.',payload:{offerId:o.id}});}}
export function tickManagerEmployment(world:World,date:string){const s=managerEmploymentState(world);expireOffers(world,date);const shouldEvaluate=!s.lastEvaluationDate||dateDiff(date,s.lastEvaluationDate)>=7;if(!shouldEvaluate)return;s.lastEvaluationDate=date;for(const m of managerCharacterState(world).characters.values()){if(m.currentClubId){const a=assessManagerJob(world,m,date);if(a){maybeRenew(world,m,date);maybeSack(world,m,a,date);if(m.currentClubId)maybeApproach(world,m,date);}}}const u=userManager(world);if(u&&!u.currentClubId){/* future: job applications and vacancy discovery */}}
function wireEmploymentEvents(world:World){onWorldEvent(world,'ManagerIdentityShift',(e)=>{for(const clubId of e.clubIds){const m=managerByClub(world,clubId);if(m)assessManagerJob(world,m,e.date);}});}
export function pendingUserJobOffers(world:World){const u=userManager(world);return u?managerEmploymentState(world).offers.filter(o=>o.managerId===u.id&&o.status==='pending'):[];}
export function snapshotManagerEmployment(world:World):ManagerEmploymentSnapshot{const s=managerEmploymentState(world);return{contracts:[...s.contracts.entries()].map(([k,v])=>[k,{...v,objectives:{...v.objectives}}]),assessments:[...s.assessments.entries()].map(([k,v])=>[k,{...v,reasons:[...v.reasons]}]),offers:s.offers.map(o=>({...o})),lastEvaluationDate:s.lastEvaluationDate};}
export function restoreManagerEmployment(world:World,snapshot?:ManagerEmploymentSnapshot){if(!snapshot)return;states.set(world,{contracts:new Map(snapshot.contracts.map(([k,v])=>[k,{...v,objectives:{...v.objectives}}])),assessments:new Map(snapshot.assessments.map(([k,v])=>[k,{...v,reasons:[...v.reasons]}])),offers:snapshot.offers.map(o=>({...o})),lastEvaluationDate:snapshot.lastEvaluationDate,wired:false});}
