import type { Player, World } from './engine';
import { emitWorldEvent, onWorldEvent, type WorldEvent } from './event-bus';
import { humanLifeState } from './human-life';
import { clubDressingRoom } from './dressing-room';
import { institutionalState } from './institutional-memory';
import { generateDialogueSet, type DialogueAudience, type DialogueTopic, type DialogueTone } from './human-dialogue-bank-v1';

export type ManagerAxis='discipline'|'empathy'|'patience'|'assertiveness'|'publicProtection'|'diplomacy'|'confrontation'|'pragmatism'|'consistency'|'mediaSkill'|'adaptability'|'forgiveness';
export type ManagerProfile={managerId:string;clubId:string;discipline:number;empathy:number;patience:number;assertiveness:number;publicProtection:number;diplomacy:number;confrontation:number;pragmatism:number;consistency:number;mediaSkill:number;adaptability:number;forgiveness:number;stress:number;authority:number;reputation:number;createdSeason:number;lastEvolutionDate:string};
export type PlayerManagerRelationship={clubId:string;managerId:string;playerId:string;trust:number;respect:number;warmth:number;openness:number;friction:number;fear:number;credibility:number;history:InteractionMemory[]};
export type InteractionMemory={date:string;interactionId:string;optionId:string;summary:string;trustDelta:number;respectDelta:number;frictionDelta:number;moraleDelta:number;publicityDelta:number};
export type InteractionKind='discipline'|'support'|'performance'|'media'|'conflict'|'transfer'|'dressingRoom'|'personal'|'contract'|'leadership';
export type InteractionOption={id:string;label:string;description:string;tone:'supportive'|'calm'|'firm'|'harsh'|'public'|'silent';requires?:Partial<Record<ManagerAxis,number>>;trust:number;respect:number;friction:number;morale:number;authority:number;publicity:number;disciplineSignal:number;empathySignal:number;confrontationSignal:number};
export type ManagerInteraction={id:string;clubId:string;managerId:string;playerId?:string;sourceEventId:string;kind:InteractionKind;date:string;severity:number;publicity:number;truth:'confirmed'|'rumour'|'false'|'unknown';context:string;status:'pending'|'resolved'|'expired';options:InteractionOption[];chosenOptionId?:string;chosenText?:string;resolvedDate?:string;aiControlled:boolean;deadlineDate:string};
export type ManagerInteractionState={profiles:Map<string,ManagerProfile>;relationships:Map<string,PlayerManagerRelationship>;interactions:ManagerInteraction[];wired:boolean;lastTick?:string};export type ManagerInteractionSnapshot={profiles:[string,ManagerProfile][];relationships:[string,PlayerManagerRelationship][];interactions:ManagerInteraction[];lastTick?:string};
const states=new WeakMap<World,ManagerInteractionState>(),clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v)),hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h>>>0)},pseudo=(seed:number,o:number)=>{const x=Math.sin(seed*12.9898+o*78.233)*43758.5453;return x-Math.floor(x)},addDays=(iso:string,d:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)},relKey=(clubId:string,playerId:string)=>`${clubId}:${playerId}`;
function findPlayer(world:World,id?:string):Player|undefined{if(!id)return;for(const c of world.clubs){const p=c.players.find(x=>x.id===id);if(p)return p}}
function initialProfile(clubId:string,season:number):ManagerProfile{const s=hash(`manager-profile-${clubId}`);return{managerId:`manager-${clubId}`,clubId,discipline:Math.round(38+pseudo(s,1)*52),empathy:Math.round(30+pseudo(s,2)*60),patience:Math.round(28+pseudo(s,3)*62),assertiveness:Math.round(38+pseudo(s,4)*55),publicProtection:Math.round(28+pseudo(s,5)*65),diplomacy:Math.round(28+pseudo(s,6)*65),confrontation:Math.round(18+pseudo(s,7)*68),pragmatism:Math.round(35+pseudo(s,8)*58),consistency:Math.round(35+pseudo(s,9)*58),mediaSkill:Math.round(28+pseudo(s,10)*65),adaptability:Math.round(30+pseudo(s,11)*62),forgiveness:Math.round(25+pseudo(s,12)*65),stress:25,reputation:50,authority:58,createdSeason:season,lastEvolutionDate:`${season}-07-25`}}
function initialRelationship(clubId:string,managerId:string,playerId:string):PlayerManagerRelationship{const s=hash(`${clubId}-${playerId}-manager-rel`);return{clubId,managerId,playerId,trust:Math.round(48+pseudo(s,1)*25),respect:Math.round(50+pseudo(s,2)*25),warmth:Math.round(42+pseudo(s,3)*30),openness:Math.round(38+pseudo(s,4)*35),friction:Math.round(5+pseudo(s,5)*20),fear:Math.round(5+pseudo(s,6)*18),credibility:60,history:[]}}
export function managerInteractionState(world:World):ManagerInteractionState{let s=states.get(world);if(!s){s={profiles:new Map(),relationships:new Map(),interactions:[],wired:false};states.set(world,s)}for(const club of world.clubs){if(!s.profiles.has(club.id))s.profiles.set(club.id,initialProfile(club.id,world.season));const m=s.profiles.get(club.id)!;for(const p of club.players){const key=relKey(club.id,p.id);if(!s.relationships.has(key))s.relationships.set(key,initialRelationship(club.id,m.managerId,p.id))}}if(!s.wired){wireInteractions(world);s.wired=true}return s}export function managerProfile(world:World,clubId:string){return managerInteractionState(world).profiles.get(clubId)}export function managerPlayerRelationship(world:World,clubId:string,playerId:string){return managerInteractionState(world).relationships.get(relKey(clubId,playerId))}export function setManagerCreationProfile(world:World,clubId:string,patch:Partial<Record<ManagerAxis,number>>){const p=managerProfile(world,clubId);if(!p)return;for(const[k,v]of Object.entries(patch)as[ManagerAxis,number][])p[k]=clamp(v)}
function option(id:string,label:string,description:string,tone:InteractionOption['tone'],values:Partial<Omit<InteractionOption,'id'|'label'|'description'|'tone'>>={}):InteractionOption{return{id,label,description,tone,trust:0,respect:0,friction:0,morale:0,authority:0,publicity:0,disciplineSignal:0,empathySignal:0,confrontationSignal:0,...values}}
function commonSupport(){return[option('private_support','Conversar em particular','Apoiar sem retirar responsabilidade do atleta.','supportive',{trust:5,respect:2,friction:-3,morale:4,empathySignal:2}),option('professional_support','Oferecer apoio profissional','Encaminhar suporte e combinar expectativas claras.','calm',{trust:4,respect:3,friction:-2,morale:3,authority:1,empathySignal:2,disciplineSignal:1}),option('give_space','Dar espaço por alguns dias','Evitar pressão adicional e observar a evolução.','silent',{trust:1,morale:2,empathySignal:1})]}
function disciplineOptions(severity:number,publicity:number){return[option('ignore_private','Tratar como vida privada','Não agir enquanto não houver impacto profissional.','silent',{trust:1,respect:-1,authority:-1,disciplineSignal:-1}),option('private_warning','Advertência reservada','Cobrar comportamento sem exposição pública.','firm',{trust:-1,respect:3,friction:2,morale:-1,authority:3,disciplineSignal:3}),option('formal_warning','Advertência formal','Registrar a ocorrência e exigir mudança de conduta.','firm',{trust:-3,respect:5,friction:4,morale:-2,authority:5,disciplineSignal:5}),option('drop_squad','Retirar temporariamente da equipe','Consequência esportiva clara por quebra de disciplina.','harsh',{trust:-7,respect:severity>=7?6:1,friction:8,morale:-6,authority:8,disciplineSignal:7,confrontationSignal:3}),option('public_defense_private_charge','Proteger em público e cobrar em privado','Reduz exposição externa sem ser permissivo internamente.','public',{trust:4,respect:4,friction:1,morale:2,authority:3,publicity:-8,disciplineSignal:3,empathySignal:2}),option('public_criticism','Criticar publicamente','Transformar o episódio em mensagem pública de disciplina.','public',{trust:-10,respect:severity>=8?4:-4,friction:12,morale:-7,authority:5,publicity:12,disciplineSignal:6,confrontationSignal:7})].filter(x=>x.id!=='public_criticism'||publicity>=40||severity>=8)}
function performanceOptions(){return[option('encourage','Reforçar confiança','Mostrar confiança e pedir reação.','supportive',{trust:3,respect:1,morale:4,empathySignal:2}),option('firm_private','Cobrar em particular','Apontar queda de rendimento e exigir resposta.','firm',{trust:-1,respect:3,friction:2,morale:-1,authority:2,disciplineSignal:2}),option('bench','Tirar pressão e deixar no banco','Reduz exposição competitiva, mas ameaça o status.','calm',{trust:-2,respect:1,friction:2,morale:-2,authority:2}),option('challenge','Desafiar diretamente','Cobrança forte para atletas que respondem à pressão.','harsh',{trust:-3,respect:4,friction:4,morale:-2,authority:3,confrontationSignal:3})]}
function conflictOptions(){return[option('mediate','Mediar pessoalmente','Ouvir envolvidos e buscar acordo.','calm',{trust:3,respect:3,friction:-4,authority:2,empathySignal:2}),option('captain_mediate','Usar a liderança do elenco','Pedir ao capitão para ajudar a conter o conflito.','calm',{trust:1,respect:2,friction:-2,authority:1}),option('separate','Separar os envolvidos','Reduz contato por alguns dias.','firm',{trust:-1,respect:2,friction:-1,authority:2,disciplineSignal:2}),option('zero_tolerance','Tolerância zero','Cobrança dura e ameaça de punição para nova ocorrência.','harsh',{trust:-5,respect:4,friction:5,morale:-3,authority:5,disciplineSignal:5,confrontationSignal:4})]}
function mediaOptions(){return[option('no_comment','Não comentar','Evitar alimentar especulação.','silent',{publicity:-2}),option('protect','Proteger o atleta','Rejeitar exposição excessiva e preservar o jogador.','public',{trust:4,respect:2,morale:2,publicity:-5,empathySignal:2}),option('confirm_facts','Responder objetivamente','Confirmar apenas fatos conhecidos e encerrar o assunto.','calm',{respect:2,authority:1,publicity:-1}),option('distance','Distanciar o clube do episódio','Sinalizar que o comportamento não representa o clube.','public',{trust:-5,respect:3,friction:5,morale:-3,authority:4,publicity:4,disciplineSignal:4}),option('attack_media','Confrontar a imprensa','Questionar a fonte ou a abordagem do veículo.','public',{trust:2,respect:-1,friction:1,authority:1,publicity:8,confrontationSignal:5})]}
function optionsFor(kind:InteractionKind,severity:number,publicity:number):InteractionOption[]{if(kind==='discipline')return disciplineOptions(severity,publicity);if(kind==='support'||kind==='personal')return commonSupport();if(kind==='performance')return performanceOptions();if(kind==='conflict'||kind==='dressingRoom')return conflictOptions();if(kind==='media')return mediaOptions();return[...performanceOptions(),...commonSupport().slice(0,1)]}
function classify(event:WorldEvent){const playerId=event.playerIds[0];if(event.type==='PersonalLifeEvent'){const type=String(event.payload.type??''),severity=Number(event.payload.severity??event.importance*2),publicity=Number(event.payload.publicity??0),truth=String(event.payload.truth??'confirmed')as ManagerInteraction['truth'];if(['nightOut','lateNight','publicIncident','socialMediaBacklash'].includes(type))return{kind:'discipline'as const,severity,publicity,truth,playerId,context:event.summary};if(['familyIllness','bereavement','relationshipConflict','breakup','paternityLeave','pregnancy'].includes(type))return{kind:'personal'as const,severity,publicity,truth,playerId,context:event.summary};if(['relationshipRumour','publicRelationship','partnerRivalryPressure'].includes(type))return{kind:'media'as const,severity,publicity,truth,playerId,context:event.summary}}if(event.type==='DressingRoomConcern')return{kind:'performance'as const,severity:Math.max(4,event.importance*2),publicity:10,truth:'confirmed'as const,playerId,context:event.summary};if(event.type==='DressingRoomCrisis')return{kind:'dressingRoom'as const,severity:Math.max(6,Number(event.payload.crisisLevel??2)*2),publicity:35,truth:'confirmed'as const,playerId,context:event.summary};if(event.type==='TransferRequested')return{kind:'transfer'as const,severity:6,publicity:25,truth:'confirmed'as const,playerId,context:event.summary};if(event.type==='MediaStoryPublished'&&playerId)return{kind:'media'as const,severity:event.importance*2,publicity:55,truth:'unknown'as const,playerId,context:event.summary}}
function shouldOpen(world:World,event:WorldEvent,c:{severity:number;publicity:number;playerId?:string;kind:InteractionKind}){if(!event.clubIds[0])return false;if(c.playerId&&!findPlayer(world,c.playerId))return false;const rel=c.playerId?managerPlayerRelationship(world,event.clubIds[0],c.playerId):undefined,threshold=c.kind==='personal'?5:c.kind==='media'?4:3;return c.severity>=threshold||c.publicity>=45||(rel?.friction??0)>=55}
function createFromEvent(world:World,event:WorldEvent){const c=classify(event);if(!c||!shouldOpen(world,event,c))return;const clubId=event.clubIds[0],s=managerInteractionState(world);if(!clubId||s.interactions.some(i=>i.sourceEventId===event.id))return;const p=s.profiles.get(clubId)!;const interaction:ManagerInteraction={id:`mi-${event.id}`,clubId,managerId:p.managerId,playerId:c.playerId,sourceEventId:event.id,kind:c.kind,date:event.date,severity:clamp(c.severity,1,10),publicity:clamp(c.publicity),truth:c.truth,context:c.context,status:'pending',options:optionsFor(c.kind,c.severity,c.publicity),aiControlled:true,deadlineDate:addDays(event.date,c.severity>=8?1:c.publicity>=60?2:4)};s.interactions.push(interaction);emitWorldEvent(world,{type:'ManagerInteractionOpened',date:event.date,clubIds:[clubId],playerIds:c.playerId?[c.playerId]:[],importance:c.severity>=8?4:2,summary:`Decisão do treinador necessária: ${c.context}`,payload:{interactionId:interaction.id,kind:c.kind}})}
function scoreOption(world:World,i:ManagerInteraction,o:InteractionOption){const p=managerProfile(world,i.clubId)!,player=i.playerId?findPlayer(world,i.playerId):undefined,person=player?humanLifeState(world).people.get(player.id):undefined,rel=i.playerId?managerPlayerRelationship(world,i.clubId,i.playerId):undefined;let score=50;score+=o.disciplineSignal*(p.discipline-50)/8+o.empathySignal*(p.empathy-50)/8+o.confrontationSignal*(p.confrontation-50)/8;if(o.tone==='supportive')score+=(p.empathy+p.patience-100)*.16;if(o.tone==='firm')score+=(p.assertiveness+p.discipline-100)*.15;if(o.tone==='harsh')score+=(p.confrontation+p.discipline-100)*.18;if(o.tone==='public')score+=(p.mediaSkill+p.publicProtection-100)*.08;score+=i.severity>=8?o.disciplineSignal*2:0;score+=i.truth==='rumour'||i.truth==='false'?Math.max(0,o.publicity<0?6:-6):0;score+=(person?.professionalism??55)>=70&&o.tone==='firm'?5:0;score+=(person?.temperament??55)<=35&&o.tone==='harsh'?-8:0;score+=(rel?.trust??55)>=70&&o.tone==='firm'?3:0;score+=(rel?.friction??10)>=60&&o.tone==='harsh'?-5:0;const room=clubDressingRoom(world,i.clubId),pressure=institutionalState(world).pressure.get(i.clubId);if(room?.culture.discipline&&room.culture.discipline>=70)score+=o.disciplineSignal*.7;if(room?.crisisLevel&&room.crisisLevel>=3&&o.id==='mediate')score+=8;if((pressure?.media??0)>=70&&o.id==='no_comment')score+=6;return score+Math.random()*8}
function evolveProfile(p:ManagerProfile,o:InteractionOption,date:string){const move=(k:ManagerAxis,d:number)=>p[k]=clamp(p[k]+d);move('discipline',o.disciplineSignal*.05);move('empathy',o.empathySignal*.05);move('confrontation',o.confrontationSignal*.05);if(o.tone==='public')move('mediaSkill',.06);if(o.id==='mediate'||o.id==='professional_support')move('diplomacy',.05);if(o.id==='give_space')move('patience',.04);if(o.id==='drop_squad'||o.id==='zero_tolerance')move('assertiveness',.05);p.lastEvolutionDate=date}
function spokenPart(text:string){const p=text.indexOf(' — ');return(p>=0?text.slice(p+3):text).replace(/^[“"]|[”"]$/g,'').trim()}
function applyResolution(world:World,i:ManagerInteraction,o:InteractionOption,date:string){const p=managerProfile(world,i.clubId)!,player=i.playerId?findPlayer(world,i.playerId):undefined,rel=i.playerId?managerPlayerRelationship(world,i.clubId,i.playerId):undefined;if(rel){const person=player?humanLifeState(world).people.get(player.id):undefined;let trust=o.trust,respect=o.respect,friction=o.friction,morale=o.morale;if(o.tone==='harsh'&&(person?.temperament??55)<40){trust-=3;friction+=3;morale-=2}if(o.tone==='firm'&&(person?.professionalism??55)>=70){respect+=3;morale++}if(i.truth==='false'&&['public_criticism','formal_warning','drop_squad'].includes(o.id)){trust-=7;respect-=5;friction+=8}rel.trust=clamp(rel.trust+trust);rel.respect=clamp(rel.respect+respect);rel.friction=clamp(rel.friction+friction);rel.warmth=clamp(rel.warmth+o.empathySignal*.8-o.confrontationSignal*.6);rel.fear=clamp(rel.fear+Math.max(0,o.confrontationSignal)*.8);rel.openness=clamp(rel.openness+(o.tone==='supportive'||o.tone==='calm'?2:o.tone==='harsh'?-2:0));if(player)player.morale=Math.round(clamp(player.morale+morale,20,100));rel.history.push({date,interactionId:i.id,optionId:o.id,summary:i.context,trustDelta:trust,respectDelta:respect,frictionDelta:friction,moraleDelta:morale,publicityDelta:o.publicity})}p.authority=clamp(p.authority+o.authority);evolveProfile(p,o,date);i.status='resolved';i.chosenOptionId=o.id;i.chosenText=spokenPart(optionDialogue(world,i.id,o.id,1)[0]?.text??o.label);i.resolvedDate=date;emitWorldEvent(world,{type:'ManagerInteractionResolved',date,clubIds:[i.clubId],playerIds:i.playerId?[i.playerId]:[],importance:i.severity>=8?4:2,summary:`Treinador decidiu: ${o.label}.`,payload:{interactionId:i.id,optionId:o.id,kind:i.kind,managerDialogue:i.chosenText}})}
export function resolveManagerInteraction(world:World,interactionId:string,optionId:string,date?:string){const i=managerInteractionState(world).interactions.find(x=>x.id===interactionId&&x.status==='pending');if(!i)return false;const o=i.options.find(x=>x.id===optionId);if(!o)return false;applyResolution(world,i,o,date??i.date);return true}
function autoResolve(world:World,i:ManagerInteraction,date:string){const pick=i.options.map(o=>({o,score:scoreOption(world,i,o)})).sort((a,b)=>b.score-a.score)[0]?.o;if(pick)applyResolution(world,i,pick,date)}
export function tickManagerInteractions(world:World,date:string){const s=managerInteractionState(world);if(s.lastTick===date)return;s.lastTick=date;for(const i of s.interactions.filter(x=>x.status==='pending'))if(i.aiControlled&&i.date<date&&Math.random()<.55)autoResolve(world,i,date);else if(i.deadlineDate<=date){if(i.aiControlled)autoResolve(world,i,date);else i.status='expired'}if(s.interactions.length>2000)s.interactions.splice(0,s.interactions.length-2000)}
function wireInteractions(world:World){onWorldEvent(world,'PersonalLifeEvent',e=>createFromEvent(world,e));onWorldEvent(world,'DressingRoomConcern',e=>createFromEvent(world,e));onWorldEvent(world,'DressingRoomCrisis',e=>createFromEvent(world,e));onWorldEvent(world,'TransferRequested',e=>createFromEvent(world,e));onWorldEvent(world,'MediaStoryPublished',e=>createFromEvent(world,e))}
const topicFor=(i:ManagerInteraction):DialogueTopic=>i.kind==='discipline'?'discipline':i.kind==='performance'?'performance':i.kind==='transfer'?'transfer':i.kind==='contract'?'contract':i.kind==='dressingRoom'||i.kind==='conflict'?'dressingRoom':i.kind==='personal'||i.kind==='support'?'personal':i.kind==='leadership'?'leadership':'pressure';
const audienceFor=(i:ManagerInteraction):DialogueAudience=>i.kind==='media'?'press':i.kind==='dressingRoom'||i.kind==='conflict'?'dressingRoom':i.kind==='transfer'||i.kind==='contract'?'agent':'player';
const toneFor=(o:InteractionOption):DialogueTone=>o.tone==='supportive'?'supportive':o.tone==='firm'?'firm':o.tone==='harsh'?'harsh':o.tone==='public'?'diplomatic':o.tone==='silent'?'cautious':'calm';
export function interactionDialogue(world:World,interactionId:string,count=10){const i=managerInteractionState(world).interactions.find(x=>x.id===interactionId);if(!i)return[];const club=world.clubs.find(c=>c.id===i.clubId),player=findPlayer(world,i.playerId),pressure=institutionalState(world).pressure.get(i.clubId);return generateDialogueSet({audience:audienceFor(i),topic:topicFor(i),tone:toneFor(i.options[0]??option('x','','','calm')),club:club?.name,player:player?.name,pressure:pressure?.media,seed:i.id},count)}
export function optionDialogue(world:World,interactionId:string,optionId:string,count=6){const i=managerInteractionState(world).interactions.find(x=>x.id===interactionId),o=i?.options.find(x=>x.id===optionId);if(!i||!o)return[];const club=world.clubs.find(c=>c.id===i.clubId),player=findPlayer(world,i.playerId);return generateDialogueSet({audience:audienceFor(i),topic:topicFor(i),tone:toneFor(o),club:club?.name,player:player?.name,seed:`${i.id}:${o.id}`},count)}
export function pendingManagerInteractions(world:World,clubId?:string){return managerInteractionState(world).interactions.filter(i=>i.status==='pending'&&(!clubId||i.clubId===clubId))}export function managerRelationshipSummary(world:World,clubId:string){const rows=[...managerInteractionState(world).relationships.values()].filter(r=>r.clubId===clubId);return{avgTrust:rows.length?Math.round(rows.reduce((s,r)=>s+r.trust,0)/rows.length):50,avgRespect:rows.length?Math.round(rows.reduce((s,r)=>s+r.respect,0)/rows.length):50,avgFriction:rows.length?Math.round(rows.reduce((s,r)=>s+r.friction,0)/rows.length):0,highConflict:rows.filter(r=>r.friction>=65).length,strongBonds:rows.filter(r=>r.trust>=75&&r.respect>=70).length}}
export function snapshotManagerInteractions(world:World):ManagerInteractionSnapshot{const s=managerInteractionState(world);return{profiles:[...s.profiles.entries()].map(([k,v])=>[k,{...v}]),relationships:[...s.relationships.entries()].map(([k,v])=>[k,{...v,history:v.history.map(h=>({...h}))}]),interactions:s.interactions.map(i=>({...i,options:i.options.map(o=>({...o}))})),lastTick:s.lastTick}}export function restoreManagerInteractions(world:World,snapshot?:ManagerInteractionSnapshot){if(!snapshot)return;states.set(world,{profiles:new Map(snapshot.profiles.map(([k,v])=>[k,{...v}])),relationships:new Map(snapshot.relationships.map(([k,v])=>[k,{...v,history:v.history.map(h=>({...h}))}])),interactions:snapshot.interactions.map(i=>({...i,options:i.options.map(o=>({...o}))})),wired:false,lastTick:snapshot.lastTick});managerInteractionState(world)}
