import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { institutionalState } from './institutional-memory';
import { managerCharacterState, managerByClub, type ManagerCharacter } from './manager-character';
import { managerEmploymentState, resolveManagerJobOffer } from './manager-employment';
import { managerEvolutionRecord } from './manager-longterm-evolution';

export type VacancyReason='sacked'|'resigned'|'expired'|'retired'|'poached'|'strategicChange';
export type VacancyStage='open'|'shortlist'|'interviews'|'negotiation'|'filled'|'closed';
export type CandidateSource='internal'|'unemployed'|'employed'|'agent'|'application'|'mediaFavourite';
export type InterviewTopic='clubVision'|'tactics'|'youth'|'recruitment'|'staff'|'finances'|'media'|'pressure';
export type CandidateEvaluation={managerId:string;source:CandidateSource;fit:number;reputation:number;tactical:number;people:number;youth:number;finance:number;availability:number;cost:number;supporters:number;media:number;board:number;interview?:number;total:number;risks:string[];strengths:string[]};
export type ManagerInterview={id:string;vacancyId:string;managerId:string;date:string;topics:InterviewTopic[];answers:Record<InterviewTopic,'conservative'|'balanced'|'ambitious'>;score:number;boardReaction:string;mediaLeak:boolean;supporterReaction:number};
export type ManagerVacancy={id:string;clubId:string;openedDate:string;reason:VacancyReason;stage:VacancyStage;urgency:number;desired:{minimumReputation:number;tacticalIdentity:'any'|'possession'|'pressing'|'defensive'|'transition';youthImportance:number;disciplineImportance:number;mediaTolerance:number;financialDiscipline:number;experiencePreference:number};candidates:CandidateEvaluation[];shortlist:string[];interviews:ManagerInterview[];preferredManagerId?:string;filledByManagerId?:string;deadline:string;publicity:number};
export type ManagerJobMarketState={vacancies:ManagerVacancy[];lastTick?:string};
export type ManagerJobMarketSnapshot={vacancies:ManagerVacancy[];lastTick?:string};
const states=new WeakMap<World,ManagerJobMarketState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const addDays=(iso:string,d:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)};
const days=(a:string,b:string)=>Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/86400000);
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:string)=>{const x=Math.sin(hash(s)*12.9898)*43758.5453;return x-Math.floor(x)};
export function managerJobMarketState(world:World){let s=states.get(world);if(!s){s={vacancies:[]};states.set(world,s);}return s;}
function desiredProfile(world:World,clubId:string){const club=world.clubs.find(c=>c.id===clubId);const rep=club?.reputation??60;const pressure=institutionalState(world).pressure.get(clubId);const tacticalIdentity=club?.tactics.pressing>=70?'pressing':club?.tactics.mentality==='defensive'?'defensive':club?.tactics.transition==='counter'?'transition':club?.tactics.passingStyle==='short'?'possession':'any';return{minimumReputation:Math.round(clamp(rep-18)),tacticalIdentity:tacticalIdentity as ManagerVacancy['desired']['tacticalIdentity'],youthImportance:Math.round(clamp(40+(club?.reputation??60)*.25)),disciplineImportance:Math.round(clamp(45+(pressure?.dressingRoom??30)*.25)),mediaTolerance:Math.round(clamp(55-(pressure?.media??30)*.15)),financialDiscipline:Math.round(clamp(50+(pressure?.financial??25)*.25)),experiencePreference:Math.round(clamp(35+rep*.45))};}
export function openManagerVacancy(world:World,clubId:string,date:string,reason:VacancyReason='sacked'){const s=managerJobMarketState(world);const current=s.vacancies.find(v=>v.clubId===clubId&&!['filled','closed'].includes(v.stage));if(current)return current;const urgency=reason==='sacked'?78:reason==='resigned'?65:50;const v:ManagerVacancy={id:`vac-${clubId}-${date}`,clubId,openedDate:date,reason,stage:'open',urgency,desired:desiredProfile(world,clubId),candidates:[],shortlist:[],interviews:[],deadline:addDays(date,urgency>=75?18:30),publicity:reason==='sacked'?70:45};s.vacancies.push(v);emitWorldEvent(world,{type:'ManagerVacancyOpened',date,clubIds:[clubId],importance:4,summary:`O cargo de treinador do ${clubId} ficou vago.`,payload:{vacancyId:v.id,reason}});return v;}
function tacticalFit(m:ManagerCharacter,v:ManagerVacancy){if(v.desired.tacticalIdentity==='any')return 65;if(v.desired.tacticalIdentity==='pressing')return m.tactical.pressingPreference;if(v.desired.tacticalIdentity==='possession')return m.tactical.possessionPreference;if(v.desired.tacticalIdentity==='defensive')return 100-m.tactical.defensiveLinePreference*.35-m.tactical.creativeFreedom*.2+m.tactical.pragmatism??50;if(v.desired.tacticalIdentity==='transition')return m.tactical.counterAttack;return 55;}
function evaluate(world:World,v:ManagerVacancy,m:ManagerCharacter,source:CandidateSource):CandidateEvaluation{const club=world.clubs.find(c=>c.id===v.clubId);const currentClub=m.currentClubId?world.clubs.find(c=>c.id===m.currentClubId):undefined;const reputation=clamp(m.reputation.domestic*.55+m.reputation.coachingPrestige*.45);const tactical=clamp(tacticalFit(m,v));const people=clamp(m.knowledge.manManagement*.55+m.personality.diplomacy*.2+m.personality.discipline*.15);const youth=clamp(m.knowledge.youthDevelopment*.6+m.tactical.youthUsage*.4);const finance=clamp(m.knowledge.financialAwareness*.55+m.knowledge.contractLaw*.25+m.personality.pragmatism*.2);const availability=m.currentClubId?clamp(58-(currentClub?.reputation??55)*.25+m.ambition.reputationAmbition*.2):95;const cost=clamp(100-(m.reputation.coachingPrestige+(currentClub?.reputation??0)*.25));const pressure=institutionalState(world).pressure.get(v.clubId);const supporters=clamp(45+(m.reputation.formerPlayerPrestige*.2)+(m.reputation.domestic-(club?.reputation??60))*.25+(pseudo(`${v.id}-${m.id}-fans`)-.5)*24);const media=clamp(45+m.reputation.mediaProfile*.3+m.reputation.coachingPrestige*.2+(pseudo(`${v.id}-${m.id}-media`)-.5)*22);const board=clamp(reputation*.25+tactical*.2+people*.15+youth*(v.desired.youthImportance/100)*.15+finance*(v.desired.financialDiscipline/100)*.12+availability*.08+cost*.05);const risks:string[]=[],strengths:string[]=[];if(reputation<v.desired.minimumReputation)risks.push('reputação abaixo do perfil desejado');if(availability<45)risks.push('retirada de outro clube pode ser cara ou difícil');if(tactical<45)risks.push('identidade tática pouco aderente');if(people<45)risks.push('gestão humana gera dúvidas');if(supporters<40)risks.push('recepção fria da torcida');if(media<40)risks.push('narrativa de imprensa desfavorável');if(tactical>=75)strengths.push('forte compatibilidade tática');if(youth>=75&&v.desired.youthImportance>=60)strengths.push('perfil adequado ao projeto de base');if(people>=75)strengths.push('boa capacidade de gestão de grupo');if(reputation>=75)strengths.push('nome de peso para o projeto');const total=clamp(board*.48+supporters*.12+media*.1+availability*.1+cost*.08+reputation*.12-(pressure?.board??30)*.03);return{managerId:m.id,source,fit:Math.round((tactical+people+youth+finance)/4),reputation,tactical,people,youth,finance,availability,cost,supporters,media,board,total,risks,strengths};}
function discoverCandidates(world:World,v:ManagerVacancy){const candidates=[...managerCharacterState(world).characters.values()].filter(m=>m.currentClubId!==v.clubId&&m.age<74);const rows=candidates.map(m=>evaluate(world,v,m,m.currentClubId?'employed':'unemployed')).filter(c=>c.reputation>=v.desired.minimumReputation-20||c.total>=62).sort((a,b)=>b.total-a.total).slice(0,10);v.candidates=rows;v.shortlist=rows.slice(0,Math.min(5,rows.length)).map(x=>x.managerId);v.stage='shortlist';emitWorldEvent(world,{type:'ManagerShortlistCreated',date:v.openedDate,clubIds:[v.clubId],actorIds:v.shortlist,importance:3,summary:`${v.clubId} definiu uma lista de candidatos ao cargo.`,payload:{vacancyId:v.id,candidates:v.shortlist}});}
function interviewScore(world:World,v:ManagerVacancy,m:ManagerCharacter,date:string){const topics:InterviewTopic[]=['clubVision','tactics','youth','recruitment','staff','finances','media','pressure'];const answers={} as ManagerInterview['answers'];let score=0;for(const t of topics){let a:'conservative'|'balanced'|'ambitious'='balanced';if(t==='clubVision'&&m.ambition.trophyAmbition>=72)a='ambitious';if(t==='youth'&&m.tactical.youthUsage>=70)a='ambitious';if(t==='finances'&&m.knowledge.financialAwareness>=70)a='conservative';if(t==='media'&&m.personality.mediaSkill>=70)a='ambitious';answers[t]=a;score+=a==='balanced'?7:a==='ambitious'?(m.personality.assertiveness+m.personality.diplomacy>115?8:5):m.personality.pragmatism>=60?8:6;}const evalRow=v.candidates.find(c=>c.managerId===m.id);score=clamp(score/56*100+(evalRow?.board??50)*.2);const leak=v.publicity>=60&&pseudo(`${v.id}-${m.id}-${date}-leak`)<.35;return{id:`int-${v.id}-${m.id}`,vacancyId:v.id,managerId:m.id,date,topics,answers,score,boardReaction:score>=75?'A diretoria saiu convencida.':score>=58?'Entrevista positiva, mas sem consenso.':'A entrevista deixou dúvidas importantes.',mediaLeak:leak,supporterReaction:evalRow?.supporters??50};}
function runInterviews(world:World,v:ManagerVacancy,date:string){for(const id of v.shortlist.slice(0,4)){const m=managerCharacterState(world).characters.get(id);if(!m)continue;const i=interviewScore(world,v,m,date);v.interviews.push(i);const row=v.candidates.find(c=>c.managerId===id);if(row){row.interview=i.score;row.total=clamp(row.total*.75+i.score*.25);}if(i.mediaLeak)emitWorldEvent(world,{type:'ManagerInterviewLeaked',date,actorIds:[id],clubIds:[v.clubId],importance:2,summary:`Vazou que ${m.name} foi entrevistado pelo ${v.clubId}.`,payload:{vacancyId:v.id,managerId:id,supporterReaction:i.supporterReaction}});}v.stage='interviews';}
function choosePreferred(world:World,v:ManagerVacancy,date:string){const best=[...v.candidates].filter(c=>v.shortlist.includes(c.managerId)).sort((a,b)=>b.total-a.total)[0];if(!best){v.stage='closed';return;}v.preferredManagerId=best.managerId;v.stage='negotiation';const m=managerCharacterState(world).characters.get(best.managerId);if(!m)return;const club=world.clubs.find(c=>c.id===v.clubId);const state=managerEmploymentState(world);if(!state.offers.some(o=>o.managerId===m.id&&o.fromClubId===v.clubId&&o.status==='pending')){const current=managerByClub(world,m.currentClubId);const salary=Math.round(4000+(club?.reputation??60)*230+m.reputation.coachingPrestige*150+(best.total-60)*180);state.offers.push({id:`job-offer-${m.id}-${v.clubId}-${date}`,managerId:m.id,fromClubId:v.clubId,date,expires:addDays(date,6),salaryWeekly:salary,contractYears:best.total>=80?3:2,autonomy:Math.round(clamp(48+m.reputation.coachingPrestige*.3+best.total*.12)),projectScore:Math.round(best.total),status:'pending',reason:`Primeiro colocado após shortlist e entrevistas. ${best.strengths.join('; ')}`});emitWorldEvent(world,{type:'ManagerJobOffer',date,actorIds:[m.id],clubIds:[v.clubId,...(m.currentClubId?[m.currentClubId]:[])],importance:4,summary:`${v.clubId} formalizou proposta para ${m.name}.`,payload:{vacancyId:v.id,managerId:m.id,total:best.total,currentManagerId:current?.id}});}}
function resolveAI(world:World,v:ManagerVacancy,date:string){if(!v.preferredManagerId)return;const m=managerCharacterState(world).characters.get(v.preferredManagerId);if(!m)return;const offer=managerEmploymentState(world).offers.find(o=>o.managerId===m.id&&o.fromClubId===v.clubId&&o.status==='pending');if(!offer)return;const evo=managerEvolutionRecord(world,m.id);const currentClub=world.clubs.find(c=>c.id===m.currentClubId),target=world.clubs.find(c=>c.id===v.clubId);const appeal=offer.projectScore+(target?.reputation??60)-(currentClub?.reputation??0)*.65+offer.autonomy*.2+(m.ambition.dreamClubs.includes(target?.name??'')?24:0)-(evo?.burnoutRisk??0)*.08;const accept=!m.currentClubId||appeal>=62||pseudo(`${offer.id}-accept`)<clamp((appeal-40)/70,0,.85);resolveManagerJobOffer(world,offer.id,accept,date);if(accept){v.stage='filled';v.filledByManagerId=m.id;emitWorldEvent(world,{type:'ManagerVacancyFilled',date,actorIds:[m.id],clubIds:[v.clubId],importance:5,summary:`${m.name} foi escolhido para comandar ${v.clubId}.`,payload:{vacancyId:v.id,managerId:m.id}});}else{v.shortlist=v.shortlist.filter(id=>id!==m.id);v.preferredManagerId=undefined;v.stage=v.shortlist.length?'interviews':'open';}}
export function applyManagerToVacancy(world:World,vacancyId:string,managerId:string,date:string){const v=managerJobMarketState(world).vacancies.find(x=>x.id===vacancyId&&['open','shortlist','interviews'].includes(x.stage));const m=managerCharacterState(world).characters.get(managerId);if(!v||!m)return false;let row=v.candidates.find(c=>c.managerId===managerId);if(!row){row=evaluate(world,v,m,'application');row.total=clamp(row.total+4);v.candidates.push(row);}else row.source='application';if(!v.shortlist.includes(managerId)&&row.total>=50)v.shortlist.push(managerId);emitWorldEvent(world,{type:'ManagerApplicationSubmitted',date,actorIds:[managerId],clubIds:[v.clubId],importance:2,summary:`${m.name} candidatou-se ao cargo de ${v.clubId}.`,payload:{vacancyId,total:row.total}});return true;}
export function tickManagerJobMarket(world:World,date:string){const s=managerJobMarketState(world);if(s.lastTick===date)return;s.lastTick=date;for(const club of world.clubs)if(!managerByClub(world,club.id))openManagerVacancy(world,club.id,date,'strategicChange');for(const v of s.vacancies){if(['filled','closed'].includes(v.stage))continue;if(date>v.deadline){v.stage='closed';continue;}const age=days(date,v.openedDate);if(v.stage==='open'&&age>=1)discoverCandidates(world,v);else if(v.stage==='shortlist'&&age>=3)runInterviews(world,v,date);else if(v.stage==='interviews'&&age>=5)choosePreferred(world,v,date);else if(v.stage==='negotiation'&&age>=6)resolveAI(world,v,date);}}
export function openVacancies(world:World){return managerJobMarketState(world).vacancies.filter(v=>!['filled','closed'].includes(v.stage));}
export function snapshotManagerJobMarket(world:World):ManagerJobMarketSnapshot{return JSON.parse(JSON.stringify(managerJobMarketState(world))) as ManagerJobMarketSnapshot;}
export function restoreManagerJobMarket(world:World,snapshot?:ManagerJobMarketSnapshot){if(snapshot)states.set(world,JSON.parse(JSON.stringify(snapshot)) as ManagerJobMarketState);}
