import type { Position, World } from './engine';
import { createManagerCharacter, type CoachingLicence, type CourseId, type DegreeField, type EducationLevel, type ManagerCreationInput, type ManagerGender, type PlayingLevel } from './manager-character';
import type { ManagerAxis } from './manager-interactions';

export type CreationStep='identity'|'appearance'|'social'|'playingCareer'|'staffCareer'|'education'|'personality'|'tactics'|'training'|'ambition'|'review';
export type CreationIssue={severity:'error'|'warning'|'info';field:string;message:string};
export type ManagerArchetypeId='exStar'|'careerProfessional'|'scholar'|'dataDriven'|'youthDeveloper'|'tactician'|'peopleManager'|'journeyman';
export type ManagerCreationDraft=ManagerCreationInput & {creationMode:'quick'|'advanced';archetype?:ManagerArchetypeId};
export type CreationPreview={issues:CreationIssue[];ready:boolean;identityLabel:string;careerLabel:string;educationLabel:string;tacticalLabel:string;strengths:string[];risks:string[]};

const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const year=(iso:string)=>Number(iso.slice(0,4));
const personality=(patch:Partial<Record<ManagerAxis,number>>={}):Record<ManagerAxis,number>=>({discipline:58,empathy:55,patience:55,assertiveness:58,publicProtection:52,diplomacy:55,confrontation:45,pragmatism:58,consistency:60,mediaSkill:50,adaptability:60,forgiveness:54,...patch});

export function blankManagerDraft(world:World,clubId=world.clubs[0]?.id??''):ManagerCreationDraft{
  const season=world.season;
  return{creationMode:'advanced',name:'Novo Treinador',dateOfBirth:`${season-38}-01-15`,age:38,gender:'unspecified',appearance:{heightCm:178,build:'average',hair:'short',hairColor:'brown',facialHair:'none',style:'smartCasual',glasses:false},social:{maritalStatus:'single',children:0,languages:['Português'],nationality:'Brasil',birthCity:'São Paulo',rivalClubs:[]},playingLevel:'none',playingCareer:[],staffCareer:[],education:{level:'secondary',licence:'regionalA',courses:[]},personality:personality(),tactical:{favoriteFormation:'4-2-3-1',secondaryFormations:['4-3-3'],mentality:'balanced',possessionPreference:55,pressingPreference:55,tempoPreference:55,directness:50,defensiveLinePreference:55,widthPreference:55,counterAttack:50,buildFromBack:55,creativeFreedom:50,setPieceImportance:50,youthUsage:55,rotation:55},training:{intensity:55,physical:50,technical:58,tactical:60,individualDevelopment:55,videoAnalysis:50,opponentPreparation:55,recovery:60,repetition:55,playerFreedom:50},ambition:{startingClubId:clubId,dreamClubs:[],preferredCountries:['Brasil'],avoidCountries:[],nationalTeamAmbition:50,salaryImportance:45,stabilityImportance:55,trophyAmbition:65,reputationAmbition:60,youthProjectPreference:55,financialProjectPreference:50},currentClubId:clubId,createdSeason:season};
}

const educationPreset=(level:EducationLevel,field:DegreeField|undefined,licence:CoachingLicence,courses:CourseId[])=>({level,field,licence,courses});
function playingEntry(clubName:string,country:string,startYear:number,endYear:number,position:Position,titles:string[]=[],awards:string[]=[],captain=false){return{clubName,country,startYear,endYear,position,appearances:Math.max(20,(endYear-startYear)*26),goals:position==='ST'?Math.max(5,(endYear-startYear)*8):Math.max(0,(endYear-startYear)*2),captain,titles,awards};}

export function archetypeDraft(world:World,clubId:string,id:ManagerArchetypeId):ManagerCreationDraft{
  const d=blankManagerDraft(world,clubId),s=world.season;d.creationMode='quick';d.archetype=id;
  if(id==='exStar')Object.assign(d,{age:46,dateOfBirth:`${s-46}-03-10`,playingLevel:'elite' as PlayingLevel,primaryPlayingPosition:'CM' as Position,playingCareer:[playingEntry('Clube de Elite','Brasil',s-25,s-16,'CM',['Campeonato Nacional','Copa Continental'],['Jogador do Ano'],true),playingEntry('Clube Europeu','Itália',s-16,s-8,'CM',['Liga Nacional'],[],true)],education:educationPreset('secondary',undefined,'continentalPro',['leadership','mediaRelations','performanceAnalysis']),personality:personality({assertiveness:72,discipline:68,mediaSkill:68,confrontation:56,empathy:48}),staffCareer:[]});
  if(id==='careerProfessional')Object.assign(d,{age:44,dateOfBirth:`${s-44}-06-08`,playingLevel:'professional' as PlayingLevel,primaryPlayingPosition:'CB' as Position,playingCareer:[playingEntry('Clube Tradicional','Brasil',s-24,s-11,'CB',['Campeonato Estadual'],[],true)],staffCareer:[{clubName:'Clube Tradicional',country:'Brasil',role:'assistant' as const,startYear:s-8,endYear:s-4,achievements:[]},{clubName:'Clube Regional',country:'Brasil',role:'headCoach' as const,startYear:s-4,endYear:s-1,achievements:['Acesso de divisão']}],education:educationPreset('bachelor','physicalEducation','continentalPro',['leadership','performanceAnalysis','footballManagement']),personality:personality({discipline:70,consistency:72,pragmatism:68})});
  if(id==='scholar')Object.assign(d,{age:33,dateOfBirth:`${s-33}-09-04`,playingLevel:'amateur' as PlayingLevel,primaryPlayingPosition:'CM' as Position,education:educationPreset('masters','physicalEducation','continentalA',['sportsPsychology','sportsScience','performanceAnalysis','youthDevelopment','leadership']),staffCareer:[{clubName:'Universidade / Base',country:'Brasil',role:'youthCoach' as const,startYear:s-8,endYear:s-3,achievements:[]},{clubName:'Clube Profissional',country:'Brasil',role:'assistant' as const,startYear:s-3,endYear:s-1,achievements:[]}],personality:personality({empathy:70,patience:72,adaptability:76,confrontation:28})});
  if(id==='dataDriven')Object.assign(d,{age:31,dateOfBirth:`${s-31}-02-12`,playingLevel:'none' as PlayingLevel,education:educationPreset('masters','dataScience','continentalA',['dataAnalysis','performanceAnalysis','scouting','setPieces','footballManagement']),staffCareer:[{clubName:'Departamento de Análise',country:'Brasil',role:'analyst' as const,startYear:s-7,endYear:s-2,achievements:[]}],personality:personality({pragmatism:74,adaptability:72,mediaSkill:42,confrontation:30}),tactical:{...d.tactical,possessionPreference:64,pressingPreference:68,buildFromBack:70,setPieceImportance:70}});
  if(id==='youthDeveloper')Object.assign(d,{age:37,dateOfBirth:`${s-37}-07-21`,playingLevel:'semiPro' as PlayingLevel,primaryPlayingPosition:'DM' as Position,education:educationPreset('bachelor','physicalEducation','continentalA',['youthDevelopment','sportsPsychology','leadership','sportsScience']),staffCareer:[{clubName:'Academia de Formação',country:'Brasil',role:'youthCoach' as const,startYear:s-12,endYear:s-2,achievements:['Título nacional sub-20']}],personality:personality({empathy:74,patience:78,forgiveness:68,publicProtection:66}),training:{...d.training,individualDevelopment:82,technical:72,tactical:70,recovery:68},tactical:{...d.tactical,youthUsage:88,rotation:72}});
  if(id==='tactician')Object.assign(d,{age:39,dateOfBirth:`${s-39}-11-18`,playingLevel:'professional' as PlayingLevel,primaryPlayingPosition:'DM' as Position,education:educationPreset('postgraduate','physicalEducation','continentalPro',['performanceAnalysis','setPieces','dataAnalysis']),staffCareer:[{clubName:'Clube A',country:'Portugal',role:'analyst' as const,startYear:s-9,endYear:s-5,achievements:[]},{clubName:'Clube B',country:'Brasil',role:'assistant' as const,startYear:s-5,endYear:s-1,achievements:[]}],personality:personality({pragmatism:76,consistency:74,adaptability:72}),tactical:{...d.tactical,favoriteFormation:'3-4-2-1',secondaryFormations:['4-3-3','4-2-3-1'],pressingPreference:74,defensiveLinePreference:70,tempoPreference:66,buildFromBack:70}});
  if(id==='peopleManager')Object.assign(d,{age:42,dateOfBirth:`${s-42}-05-15`,playingLevel:'professional' as PlayingLevel,primaryPlayingPosition:'ST' as Position,education:educationPreset('bachelor','psychology','continentalA',['sportsPsychology','leadership','mediaRelations']),personality:personality({empathy:84,diplomacy:80,publicProtection:78,forgiveness:72,confrontation:24,mediaSkill:70}),training:{...d.training,playerFreedom:70,individualDevelopment:66}});
  if(id==='journeyman')Object.assign(d,{age:49,dateOfBirth:`${s-49}-01-29`,playingLevel:'professional' as PlayingLevel,primaryPlayingPosition:'RB' as Position,playingCareer:[playingEntry('Clube Sul-Americano','Argentina',s-29,s-23,'RB'),playingEntry('Clube Ibérico','Portugal',s-23,s-17,'RB'),playingEntry('Clube Brasileiro','Brasil',s-17,s-13,'RB')],staffCareer:[{clubName:'Clube Brasileiro',country:'Brasil',role:'assistant' as const,startYear:s-11,endYear:s-8,achievements:[]},{clubName:'Clube Andino',country:'Chile',role:'headCoach' as const,startYear:s-7,endYear:s-5,achievements:[]},{clubName:'Clube Português',country:'Portugal',role:'assistant' as const,startYear:s-4,endYear:s-1,achievements:[]}],education:educationPreset('technical',undefined,'continentalPro',['scouting','footballManagement','mediaRelations','leadership']),social:{...d.social,languages:['Português','Espanhol'],nationality:'Brasil'},personality:personality({adaptability:88,diplomacy:70,pragmatism:72})});
  return d;
}

function overlaps(entries:{startYear:number;endYear:number}[]):boolean{const sorted=[...entries].sort((a,b)=>a.startYear-b.startYear);for(let i=1;i<sorted.length;i++)if(sorted[i].startYear<sorted[i-1].endYear)return true;return false;}
export function validateManagerDraft(world:World,d:ManagerCreationDraft):CreationIssue[]{
  const out:CreationIssue[]=[];const birth=year(d.dateOfBirth),current=world.season;
  if(!d.name.trim())out.push({severity:'error',field:'name',message:'Informe o nome do treinador.'});
  if(!Number.isFinite(birth)||current-birth<18||current-birth>85)out.push({severity:'error',field:'dateOfBirth',message:'A idade precisa estar entre 18 e 85 anos no início da carreira.'});
  if(!world.clubs.some(c=>c.id===d.currentClubId))out.push({severity:'error',field:'currentClubId',message:'O clube inicial selecionado não existe no mundo carregado.'});
  if(d.social.languages.length===0)out.push({severity:'warning',field:'languages',message:'Sem idioma declarado, a adaptação e comunicação inicial serão muito prejudicadas.'});
  if(d.playingLevel!=='none'&&d.playingCareer.length===0)out.push({severity:'warning',field:'playingCareer',message:'Foi indicado passado como jogador, mas nenhuma passagem por clube foi registrada.'});
  if(d.playingLevel==='none'&&d.playingCareer.length>0)out.push({severity:'error',field:'playingLevel',message:'Há carreira de jogador registrada, mas o nível foi definido como “nenhum”.'});
  for(const e of d.playingCareer){if(e.endYear<=e.startYear)out.push({severity:'error',field:'playingCareer',message:`Período inválido em ${e.clubName}.`});if(e.startYear<birth+14)out.push({severity:'warning',field:'playingCareer',message:`A passagem por ${e.clubName} começa muito cedo para a idade informada.`});if(e.endYear>current)out.push({severity:'error',field:'playingCareer',message:`A passagem por ${e.clubName} termina no futuro.`});}
  for(const e of d.staffCareer){if(e.endYear<=e.startYear)out.push({severity:'error',field:'staffCareer',message:`Período profissional inválido em ${e.clubName}.`});if(e.endYear>current)out.push({severity:'error',field:'staffCareer',message:`A passagem por ${e.clubName} termina no futuro.`});}
  if(overlaps(d.staffCareer))out.push({severity:'warning',field:'staffCareer',message:'Existem experiências profissionais simultâneas. Isso é permitido, mas deve representar funções acumuladas de forma plausível.'});
  if(d.education.licence==='continentalPro'&&d.age<25)out.push({severity:'warning',field:'licence',message:'Licença máxima em idade muito baixa produzirá uma origem excepcional e rara.'});
  const axes=Object.entries(d.personality) as [ManagerAxis,number][];for(const [k,v] of axes)if(v<0||v>100)out.push({severity:'error',field:`personality.${k}`,message:'Valores de personalidade precisam ficar entre 0 e 100.'});
  const extremes=axes.filter(([,v])=>v<=10||v>=90).length;if(extremes>=5)out.push({severity:'warning',field:'personality',message:'Muitos traços extremos criarão um personagem altamente polarizado.'});
  if(d.tactical.favoriteFormation.trim()==='')out.push({severity:'error',field:'favoriteFormation',message:'Defina ao menos uma formação preferida.'});
  if(d.ambition.startingClubId!==d.currentClubId)out.push({severity:'warning',field:'ambition.startingClubId',message:'O clube desejado na ambição difere do emprego inicial efetivo.'});
  return out;
}

export function previewManagerDraft(world:World,d:ManagerCreationDraft):CreationPreview{
  const issues=validateManagerDraft(world,d);const strengths:string[]=[],risks:string[]=[];
  if(d.playingLevel==='elite')strengths.push('Prestígio imediato de ex-jogador de elite');else if(d.playingLevel==='none')risks.push('Autoridade inicial precisa ser construída sem carreira profissional como atleta');
  if(d.education.level==='masters'||d.education.level==='doctorate')strengths.push('Formação acadêmica avançada');
  if(d.education.courses.includes('dataAnalysis'))strengths.push('Base analítica e leitura de dados');
  if(d.education.courses.includes('sportsPsychology'))strengths.push('Preparação para gestão humana');
  if(d.education.courses.includes('refereeing'))strengths.push('Conhecimento ampliado de arbitragem e disciplina');
  if(d.personality.confrontation>=75)risks.push('Perfil confrontador pode acelerar rupturas em ambientes tensos');
  if(d.personality.empathy<=30)risks.push('Baixa empatia pode dificultar situações pessoais e recuperação de confiança');
  if(d.tactical.pressingPreference>=78&&d.training.recovery<50)risks.push('Filosofia intensa combinada com pouca ênfase em recuperação');
  if(d.tactical.youthUsage>=75&&d.training.individualDevelopment>=70)strengths.push('Projeto coerente de desenvolvimento de jovens');
  const yearsPlayer=d.playingCareer.reduce((s,e)=>s+Math.max(0,e.endYear-e.startYear),0),yearsStaff=d.staffCareer.reduce((s,e)=>s+Math.max(0,e.endYear-e.startYear),0);
  return{issues,ready:!issues.some(i=>i.severity==='error'),identityLabel:`${d.name} · ${d.age} anos · ${d.social.nationality}`,careerLabel:d.playingLevel==='none'?`${yearsStaff} anos de experiência em staff`:`${yearsPlayer} anos como jogador + ${yearsStaff} em staff`,educationLabel:`${d.education.level} · licença ${d.education.licence} · ${d.education.courses.length} cursos`,tacticalLabel:`${d.tactical.favoriteFormation} · ${d.tactical.mentality} · posse ${d.tactical.possessionPreference} · pressão ${d.tactical.pressingPreference}`,strengths,risks};
}

export function finalizeManagerCreation(world:World,draft:ManagerCreationDraft,userControlled=true){const issues=validateManagerDraft(world,draft);const errors=issues.filter(i=>i.severity==='error');if(errors.length)throw new Error(`Ficha de treinador inválida: ${errors.map(e=>e.message).join(' | ')}`);const {creationMode:_,archetype:__,...input}=draft;return createManagerCharacter(world,input,userControlled);}
