import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { managerCharacterState, userManager, type ManagerCharacter } from './manager-character';
import { managerEmploymentState } from './manager-employment';

export type InterviewAnswerStyle='cautious'|'balanced'|'ambitious'|'demanding'|'diplomatic';
export type InterviewQuestion={id:string;topic:'vision'|'tactics'|'youth'|'recruitment'|'staff'|'finances'|'media'|'pressure';prompt:string;answers:{id:string;label:string;style:InterviewAnswerStyle;signals:{ambition?:number;diplomacy?:number;pragmatism?:number;youth?:number;control?:number;finance?:number;media?:number;pressure?:number}}[]};
export type UserInterviewSession={id:string;vacancyId:string;managerId:string;clubId:string;openedDate:string;deadlineDate:string;status:'pending'|'completed'|'expired';answers:Record<string,string>;score?:number;boardReaction?:string;supporterReaction?:number;mediaReaction?:number};

export type ManagerContractTerms={salaryWeekly:number;years:number;autonomy:number;transferControl:number;staffControl:number;youthCommitment:number;styleCommitment:number;leagueTarget:number;releaseClause:number;transferBudgetPromise:number};
export type ContractNegotiationRound={date:string;actor:'club'|'manager';terms:ManagerContractTerms;comment:string;score:number};
export type ManagerContractNegotiation={id:string;vacancyId:string;managerId:string;clubId:string;openedDate:string;deadlineDate:string;status:'pending'|'agreed'|'collapsed'|'withdrawn';rounds:ContractNegotiationRound[];current:ManagerContractTerms;clubTolerance:number;managerLeverage:number;maxRounds:number;};
export type ManagerJobInterviewState={interviews:UserInterviewSession[];negotiations:ManagerContractNegotiation[]};
export type ManagerJobInterviewSnapshot=ManagerJobInterviewState;

const states=new WeakMap<World,ManagerJobInterviewState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const addDays=(iso:string,d:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)};
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:string)=>{const x=Math.sin(hash(s)*12.9898)*43758.5453;return x-Math.floor(x)};
export function managerJobInterviewState(world:World){let s=states.get(world);if(!s){s={interviews:[],negotiations:[]};states.set(world,s);}return s;}

export const interviewQuestions:InterviewQuestion[]=[
 {id:'vision',topic:'vision',prompt:'Qual deve ser a prioridade do projeto nos primeiros 18 meses?',answers:[{id:'results_now',label:'Resultados imediatos, mesmo com decisões duras.',style:'ambitious',signals:{ambition:8,pressure:5,control:2}},{id:'build_identity',label:'Construir identidade competitiva sem ignorar o curto prazo.',style:'balanced',signals:{pragmatism:6,diplomacy:3}},{id:'long_project',label:'Aceito oscilações se houver evolução estrutural clara.',style:'cautious',signals:{pragmatism:4,youth:3}}]},
 {id:'tactics',topic:'tactics',prompt:'Até que ponto você adapta sua ideia ao elenco atual?',answers:[{id:'impose_model',label:'O clube precisa se aproximar da minha ideia.',style:'demanding',signals:{control:8,ambition:4}},{id:'adapt_then_evolve',label:'Adapto agora e evoluo o modelo progressivamente.',style:'diplomatic',signals:{diplomacy:6,pragmatism:7}},{id:'full_adaptation',label:'O elenco define a melhor estrutura neste momento.',style:'cautious',signals:{pragmatism:6}}]},
 {id:'youth',topic:'youth',prompt:'Como você pretende tratar jogadores da base?',answers:[{id:'pathway',label:'Quero uma rota real até o time principal.',style:'ambitious',signals:{youth:9}},{id:'merit',label:'Terão espaço quando estiverem prontos.',style:'balanced',signals:{youth:5,pragmatism:5}},{id:'results_first',label:'A prioridade é resultado; a base não será forçada.',style:'cautious',signals:{pressure:3,pragmatism:5}}]},
 {id:'recruitment',topic:'recruitment',prompt:'Como deve funcionar a contratação de jogadores?',answers:[{id:'manager_control',label:'Quero forte influência nas decisões finais.',style:'demanding',signals:{control:9}},{id:'committee',label:'Decisão compartilhada com scouting, diretor e finanças.',style:'diplomatic',signals:{diplomacy:7,pragmatism:6}},{id:'director_led',label:'Aceito modelo liderado pelo diretor esportivo.',style:'cautious',signals:{control:-5,diplomacy:3}}]},
 {id:'staff',topic:'staff',prompt:'Você exige trazer membros da sua comissão?',answers:[{id:'own_staff',label:'Preciso de liberdade para montar parte da comissão.',style:'demanding',signals:{control:8}},{id:'mixed_staff',label:'Quero avaliar a estrutura atual antes de decidir.',style:'balanced',signals:{pragmatism:6,diplomacy:4}},{id:'keep_staff',label:'Posso trabalhar com a comissão existente.',style:'cautious',signals:{diplomacy:5}}]},
 {id:'finances',topic:'finances',prompt:'Se o orçamento for apertado, como você reage?',answers:[{id:'demand_budget',label:'Sem investimento adequado, o objetivo precisa mudar.',style:'demanding',signals:{control:5,finance:-2}},{id:'optimize',label:'Busco eficiência, vendas e oportunidades de mercado.',style:'balanced',signals:{finance:8,pragmatism:7}},{id:'accept_limits',label:'Aceito as limitações e trabalho com o que houver.',style:'cautious',signals:{finance:4,diplomacy:4}}]},
 {id:'media',topic:'media',prompt:'Como pretende lidar com forte pressão da imprensa?',answers:[{id:'front_foot',label:'Vou controlar a narrativa e responder quando necessário.',style:'ambitious',signals:{media:8,pressure:3}},{id:'protect_club',label:'Protejo o grupo e escolho cuidadosamente minhas batalhas.',style:'diplomatic',signals:{media:6,diplomacy:5}},{id:'minimal_media',label:'Prefiro falar pouco e deixar o campo responder.',style:'cautious',signals:{media:2,pressure:-2}}]},
 {id:'pressure',topic:'pressure',prompt:'O que acontece se os primeiros resultados forem ruins?',answers:[{id:'hold_course',label:'Se os indicadores forem bons, mantenho convicções.',style:'ambitious',signals:{ambition:5,pressure:7}},{id:'review',label:'Reavalio sem abandonar tudo por pânico.',style:'balanced',signals:{pragmatism:8,pressure:4}},{id:'change_fast',label:'Mudo rapidamente o que for necessário.',style:'cautious',signals:{pragmatism:4,pressure:2}}]}
];

export function openUserManagerInterview(world:World,vacancyId:string,clubId:string,date:string){const u=userManager(world);if(!u)return;const s=managerJobInterviewState(world);let existing=s.interviews.find(i=>i.vacancyId===vacancyId&&i.managerId===u.id&&i.status==='pending');if(existing)return existing;existing={id:`mgr-int-${vacancyId}-${u.id}`,vacancyId,managerId:u.id,clubId,openedDate:date,deadlineDate:addDays(date,3),status:'pending',answers:{}};s.interviews.push(existing);emitWorldEvent(world,{type:'ManagerInterviewOpened',date,actorIds:[u.id],clubIds:[clubId],importance:3,summary:`${u.name} foi chamado para entrevista.`,payload:{vacancyId,interviewId:existing.id,deadline:existing.deadlineDate}});return existing;}

function answerScore(m:ManagerCharacter,q:InterviewQuestion,answerId:string){const a=q.answers.find(x=>x.id===answerId);if(!a)return 0;let score=55;const s=a.signals;score+=(s.diplomacy??0)*m.personality.diplomacy/100;score+=(s.pragmatism??0)*m.personality.pragmatism/100;score+=(s.youth??0)*(m.tactical.youthUsage+m.knowledge.youthDevelopment)/200;score+=(s.media??0)*(m.personality.mediaSkill+m.knowledge.media)/200;score+=(s.finance??0)*m.knowledge.financialAwareness/100;score+=(s.pressure??0)*(m.personality.assertiveness+m.personality.consistency)/200;score+=(s.ambition??0)*m.ambition.trophyAmbition/100;score+=(s.control??0)*m.personality.assertiveness/100;return clamp(score);}
export function resolveUserInterview(world:World,interviewId:string,answers:Record<string,string>,date:string){const s=managerJobInterviewState(world),i=s.interviews.find(x=>x.id===interviewId&&x.status==='pending');if(!i)return;const m=managerCharacterState(world).characters.get(i.managerId);if(!m)return;let total=0,answered=0;for(const q of interviewQuestions){const a=answers[q.id];if(!a)continue;i.answers[q.id]=a;total+=answerScore(m,q,a);answered++;}if(answered<interviewQuestions.length)return;i.score=clamp(total/answered+(m.knowledge.tactics-50)*.08+(m.knowledge.manManagement-50)*.06);i.boardReaction=i.score>=78?'A diretoria saiu muito convencida.':i.score>=62?'A entrevista foi positiva, mas haverá comparação com outros nomes.':i.score>=48?'Algumas respostas agradaram; outras deixaram dúvidas.':'A diretoria saiu preocupada com a compatibilidade do projeto.';i.supporterReaction=clamp(45+m.reputation.domestic*.25+(i.score-50)*.25);i.mediaReaction=clamp(45+m.reputation.mediaProfile*.2+(i.score-50)*.35);i.status='completed';emitWorldEvent(world,{type:'ManagerInterviewResolved',date,actorIds:[m.id],clubIds:[i.clubId],importance:i.score>=75?4:2,summary:`Entrevista de ${m.name} concluída com avaliação ${Math.round(i.score)}.`,payload:{vacancyId:i.vacancyId,interviewId:i.id,score:i.score,supporters:i.supporterReaction,media:i.mediaReaction}});return i;}
export function completedInterviewForVacancy(world:World,vacancyId:string,managerId:string){return managerJobInterviewState(world).interviews.find(i=>i.vacancyId===vacancyId&&i.managerId===managerId&&i.status==='completed');}
export function pendingUserInterviews(world:World){const u=userManager(world);return u?managerJobInterviewState(world).interviews.filter(i=>i.managerId===u.id&&i.status==='pending'):[];}

function defaultTerms(world:World,vacancyId:string,managerId:string,clubId:string):ManagerContractTerms{const m=managerCharacterState(world).characters.get(managerId),club=world.clubs.find(c=>c.id===clubId);const rep=club?.reputation??60,coach=m?.reputation.coachingPrestige??50;return{salaryWeekly:Math.round(4500+rep*230+coach*145),years:rep>=80?3:2,autonomy:Math.round(clamp(48+coach*.32)),transferControl:Math.round(clamp(42+coach*.28)),staffControl:Math.round(clamp(45+coach*.25)),youthCommitment:Math.round(clamp(45+(m?.tactical.youthUsage??50)*.45)),styleCommitment:60,leagueTarget:Math.max(1,Math.round(20-(rep-60)*.22)),releaseClause:Math.round((4500+rep*230+coach*145)*52*1.5),transferBudgetPromise:Math.round(1_000_000+rep*120_000)};}
function termsScore(world:World,n:ManagerContractNegotiation,t:ManagerContractTerms,forManager:boolean){const m=managerCharacterState(world).characters.get(n.managerId);if(!m)return 0;const club=world.clubs.find(c=>c.id===n.clubId);const base=defaultTerms(world,n.vacancyId,n.managerId,n.clubId);if(forManager){const salary=t.salaryWeekly/base.salaryWeekly*22,autonomy=t.autonomy*.16,control=(t.transferControl+t.staffControl)*.1,years=t.years*5,project=(club?.reputation??60)*.18,targets=(22-Math.min(22,t.leagueTarget))*1.2;return clamp(salary+autonomy+control+years+project+targets-(m.ambition.stabilityImportance<35?t.years*1.5:0));}const salaryCost=clamp(100-(t.salaryWeekly/base.salaryWeekly-1)*80),controlCost=clamp(100-(t.autonomy+t.transferControl+t.staffControl-150)*.55),targets=clamp(65+(base.leagueTarget-t.leagueTarget)*-5),years=clamp(70-Math.max(0,t.years-2)*8),release=clamp(t.releaseClause/base.releaseClause*60);return clamp(salaryCost*.28+controlCost*.3+targets*.18+years*.1+release*.14);}
export function openUserContractNegotiation(world:World,vacancyId:string,managerId:string,clubId:string,date:string){const s=managerJobInterviewState(world);let n=s.negotiations.find(x=>x.vacancyId===vacancyId&&x.managerId===managerId&&x.status==='pending');if(n)return n;const current=defaultTerms(world,vacancyId,managerId,clubId),m=managerCharacterState(world).characters.get(managerId);n={id:`mgr-neg-${vacancyId}-${managerId}`,vacancyId,managerId,clubId,openedDate:date,deadlineDate:addDays(date,8),status:'pending',rounds:[],current,clubTolerance:Math.round(clamp(58+(world.clubs.find(c=>c.id===clubId)?.reputation??60)*.25)),managerLeverage:Math.round(clamp((m?.reputation.coachingPrestige??50)*.55+(m?.reputation.domestic??50)*.35)),maxRounds:5};n.rounds.push({date,actor:'club',terms:{...current},comment:'Proposta inicial do clube.',score:termsScore(world,n,current,false)});s.negotiations.push(n);emitWorldEvent(world,{type:'ManagerContractNegotiationStarted',date,actorIds:[managerId],clubIds:[clubId],importance:4,summary:'Negociação contratual de treinador iniciada.',payload:{negotiationId:n.id,vacancyId,terms:current}});return n;}
export function submitManagerContractCounter(world:World,negotiationId:string,terms:ManagerContractTerms,date:string){const n=managerJobInterviewState(world).negotiations.find(x=>x.id===negotiationId&&x.status==='pending');if(!n)return;const m=managerCharacterState(world).characters.get(n.managerId);if(!m)return;const managerScore=termsScore(world,n,terms,true),clubScore=termsScore(world,n,terms,false);n.rounds.push({date,actor:'manager',terms:{...terms},comment:'Contraproposta do treinador.',score:managerScore});const leverage=n.managerLeverage*.35+n.clubTolerance*.2;const acceptance=clubScore+leverage*.18-(n.rounds.length-1)*2.5;emitWorldEvent(world,{type:'ManagerContractCountered',date,actorIds:[m.id],clubIds:[n.clubId],importance:2,summary:`${m.name} apresentou contraproposta.`,payload:{negotiationId:n.id,clubScore,managerScore,round:n.rounds.length}});
 if(acceptance>=67){n.current={...terms};n.status='agreed';finalizeNegotiatedOffer(world,n,date);return n;}
 if(n.rounds.length>=n.maxRounds||acceptance<35){n.status='collapsed';emitWorldEvent(world,{type:'ManagerContractNegotiationCollapsed',date,actorIds:[m.id],clubIds:[n.clubId],importance:3,summary:'As partes encerraram a negociação sem acordo.',payload:{negotiationId:n.id,acceptance}});return n;}
 const base=defaultTerms(world,n.vacancyId,n.managerId,n.clubId);const response:ManagerContractTerms={salaryWeekly:Math.round((terms.salaryWeekly+base.salaryWeekly*1.05)/2),years:Math.max(1,Math.min(4,Math.round((terms.years+base.years)/2))),autonomy:Math.round((terms.autonomy+base.autonomy)/2),transferControl:Math.round((terms.transferControl+base.transferControl)/2),staffControl:Math.round((terms.staffControl+base.staffControl)/2),youthCommitment:Math.round((terms.youthCommitment+base.youthCommitment)/2),styleCommitment:Math.round((terms.styleCommitment+base.styleCommitment)/2),leagueTarget:Math.round((terms.leagueTarget+base.leagueTarget)/2),releaseClause:Math.round((terms.releaseClause+base.releaseClause)/2),transferBudgetPromise:Math.round((terms.transferBudgetPromise+base.transferBudgetPromise)/2)};n.current=response;n.rounds.push({date,actor:'club',terms:{...response},comment:'O clube aproximou posições, mas preservou limites institucionais.',score:termsScore(world,n,response,false)});return n;}
function finalizeNegotiatedOffer(world:World,n:ManagerContractNegotiation,date:string){const state=managerEmploymentState(world),m=managerCharacterState(world).characters.get(n.managerId);if(!m)return;state.offers.push({id:`job-offer-neg-${n.id}`,managerId:n.managerId,fromClubId:n.clubId,date,expires:addDays(date,4),salaryWeekly:n.current.salaryWeekly,contractYears:n.current.years,autonomy:n.current.autonomy,projectScore:Math.round((n.current.transferControl+n.current.staffControl+n.current.autonomy)/3),status:'pending',reason:`Termos negociados: controle transferências ${n.current.transferControl}, comissão ${n.current.staffControl}, orçamento prometido ${n.current.transferBudgetPromise}.`});emitWorldEvent(world,{type:'ManagerContractNegotiationAgreed',date,actorIds:[n.managerId],clubIds:[n.clubId],importance:4,summary:`${m.name} e ${n.clubId} chegaram a acordo contratual.`,payload:{negotiationId:n.id,terms:n.current}});}
export function acceptCurrentClubTerms(world:World,negotiationId:string,date:string){const n=managerJobInterviewState(world).negotiations.find(x=>x.id===negotiationId&&x.status==='pending');if(!n)return;n.status='agreed';finalizeNegotiatedOffer(world,n,date);return n;}
export function pendingUserContractNegotiations(world:World){const u=userManager(world);return u?managerJobInterviewState(world).negotiations.filter(n=>n.managerId===u.id&&n.status==='pending'):[];}
export function tickManagerJobInterviews(world:World,date:string){const s=managerJobInterviewState(world);for(const i of s.interviews)if(i.status==='pending'&&i.deadlineDate<date){i.status='expired';emitWorldEvent(world,{type:'ManagerInterviewExpired',date,actorIds:[i.managerId],clubIds:[i.clubId],importance:2,summary:'O prazo para a entrevista expirou.',payload:{interviewId:i.id,vacancyId:i.vacancyId}});}for(const n of s.negotiations)if(n.status==='pending'&&n.deadlineDate<date){n.status='collapsed';emitWorldEvent(world,{type:'ManagerContractNegotiationCollapsed',date,actorIds:[n.managerId],clubIds:[n.clubId],importance:3,summary:'A negociação contratual expirou sem acordo.',payload:{negotiationId:n.id}});}}
export function snapshotManagerJobInterviews(world:World):ManagerJobInterviewSnapshot{return JSON.parse(JSON.stringify(managerJobInterviewState(world))) as ManagerJobInterviewSnapshot;}
export function restoreManagerJobInterviews(world:World,snapshot?:ManagerJobInterviewSnapshot){if(snapshot)states.set(world,JSON.parse(JSON.stringify(snapshot)) as ManagerJobInterviewSnapshot);}
