import type { World } from './engine';
import { emitWorldEvent, onWorldEvent } from './event-bus';
import { managerCharacterState, userManager, type ManagerCharacter } from './manager-character';
import { managerEvolutionRecord } from './manager-longterm-evolution';
import { managerEmploymentState, resolveManagerJobOffer, type ManagerJobOffer } from './manager-employment';

export type ManagerCareerStatus='employed'|'unemployed'|'sabbatical'|'retired';
export type ManagerCareerLife={managerId:string;status:ManagerCareerStatus;since:string;unemployedDays:number;sabbaticalUntil?:string;retirementEligible:boolean;lastClubId?:string;applications:string[];};
export type ManagerCareerLifeState={managers:Map<string,ManagerCareerLife>;wired:boolean;lastTick?:string};
export type ManagerCareerLifeSnapshot={managers:[string,ManagerCareerLife][];lastTick?:string};
const states=new WeakMap<World,ManagerCareerLifeState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const addDays=(iso:string,d:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)};
const diff=(a:string,b:string)=>Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/86400000);
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:string)=>{const x=Math.sin(hash(s)*12.9898)*43758.5453;return x-Math.floor(x)};
function initial(m:ManagerCharacter,date:string):ManagerCareerLife{return{managerId:m.id,status:m.currentClubId?'employed':'unemployed',since:date,unemployedDays:0,retirementEligible:m.age>=66,lastClubId:m.currentClubId||undefined,applications:[]};}
export function managerCareerLifeState(world:World,date=`${world.season}-07-25`){let s=states.get(world);if(!s){s={managers:new Map(),wired:false};states.set(world,s);}for(const m of managerCharacterState(world).characters.values())if(!s.managers.has(m.id))s.managers.set(m.id,initial(m,date));if(!s.wired){s.wired=true;wire(world);}return s;}
export function managerCareerLife(world:World,managerId:string){return managerCareerLifeState(world).managers.get(managerId);}
function wire(world:World){onWorldEvent(world,'ManagerSacked',(e)=>{const id=String(e.payload.managerId??e.actorIds[0]??'');const l=managerCareerLifeState(world,e.date).managers.get(id);if(l){l.status='unemployed';l.since=e.date;l.unemployedDays=0;l.lastClubId=String(e.payload.clubId??e.clubIds[0]??l.lastClubId??'');}});onWorldEvent(world,'ManagerHired',(e)=>{const id=String(e.payload.managerId??e.actorIds[0]??'');const l=managerCareerLifeState(world,e.date).managers.get(id);if(l){l.status='employed';l.since=e.date;l.unemployedDays=0;l.sabbaticalUntil=undefined;l.lastClubId=String(e.payload.to??e.clubIds[0]??'');l.applications=[];}});}
function fit(world:World,m:ManagerCharacter,clubId:string){const c=world.clubs.find(x=>x.id===clubId);if(!c)return 0;let s=50;s-=Math.abs(c.tactics.pressing-m.tactical.pressingPreference)*.12;s-=Math.abs(c.tactics.tempo-m.tactical.tempoPreference)*.1;s+=(m.reputation.domestic-c.reputation)*.18;s+=(m.personality.adaptability-50)*.08;if(m.ambition.dreamClubs.includes(c.name))s+=20;if(m.ambition.preferredCountries.includes('Brasil'))s+=3;return clamp(s);}
function vacantClubs(world:World){const occupied=new Set([...managerCharacterState(world).characters.values()].filter(m=>m.currentClubId).map(m=>m.currentClubId));return world.clubs.filter(c=>!occupied.has(c.id));}
function generateUnemployedOffer(world:World,m:ManagerCharacter,date:string):ManagerJobOffer|undefined{const state=managerEmploymentState(world);if(state.offers.some(o=>o.managerId===m.id&&o.status==='pending'))return;const clubs=vacantClubs(world).map(c=>({c,fit:fit(world,m,c.id)})).filter(x=>x.fit>=42&&x.c.reputation<=m.reputation.domestic+22).sort((a,b)=>b.fit-a.fit);if(!clubs.length)return;const chosen=clubs[Math.min(clubs.length-1,Math.floor(pseudo(`${m.id}-${date}-vacancy`)*Math.min(3,clubs.length)))];if(pseudo(`${m.id}-${date}-unemployed-offer`)>.08)return;const o:ManagerJobOffer={id:`job-offer-free-${m.id}-${chosen.c.id}-${date}`,managerId:m.id,fromClubId:chosen.c.id,date,expires:addDays(date,10),salaryWeekly:Math.round(2800+chosen.c.reputation*195+m.reputation.coachingPrestige*110),contractYears:2,autonomy:Math.round(clamp(42+m.reputation.coachingPrestige*.32)),projectScore:chosen.fit,status:'pending',reason:`O clube procura um treinador disponível com aderência de projeto ${Math.round(chosen.fit)}.`};state.offers.push(o);emitWorldEvent(world,{type:'ManagerJobOffer',date,actorIds:[m.id],clubIds:[chosen.c.id],importance:4,summary:`${chosen.c.name} abriu conversas com ${m.name}.`,payload:{offerId:o.id,unemployed:true,projectScore:o.projectScore,salaryWeekly:o.salaryWeekly}});return o;}
export function applyForManagerJob(world:World,managerId:string,clubId:string,date:string){const m=managerCharacterState(world).characters.get(managerId),life=managerCareerLife(world,managerId);if(!m||!life||life.status!=='unemployed'||!vacantClubs(world).some(c=>c.id===clubId))return false;if(!life.applications.includes(clubId))life.applications.push(clubId);const c=world.clubs.find(x=>x.id===clubId)!;const score=fit(world,m,clubId)+(m.reputation.coachingPrestige-c.reputation)*.25;emitWorldEvent(world,{type:'ManagerJobApplication',date,actorIds:[m.id],clubIds:[clubId],importance:2,summary:`${m.name} se candidatou ao ${c.name}.`,payload:{managerId,clubId,fit:score}});if(score>=58&&pseudo(`${managerId}-${clubId}-${date}-application`)<clamp((score-45)/40,.2,.9)){const state=managerEmploymentState(world);const offer:ManagerJobOffer={id:`job-offer-application-${managerId}-${clubId}-${date}`,managerId,fromClubId:clubId,date,expires:addDays(date,7),salaryWeekly:Math.round(2600+c.reputation*200+m.reputation.coachingPrestige*100),contractYears:2,autonomy:Math.round(clamp(40+m.reputation.coachingPrestige*.3)),projectScore:score,status:'pending',reason:'Candidatura aprovada para proposta formal.'};state.offers.push(offer);emitWorldEvent(world,{type:'ManagerJobOffer',date,actorIds:[m.id],clubIds:[clubId],importance:4,summary:`${c.name} fez proposta a ${m.name}.`,payload:{offerId:offer.id,application:true}});}return true;}
export function startManagerSabbatical(world:World,managerId:string,date:string,months=6){const m=managerCharacterState(world).characters.get(managerId),l=managerCareerLife(world,managerId);if(!m||!l||l.status==='retired'||m.currentClubId)return false;l.status='sabbatical';l.since=date;l.sabbaticalUntil=addDays(date,Math.max(30,months*30));m.history.push({date,type:'sabbatical',summary:`Iniciou período sabático previsto até ${l.sabbaticalUntil}.`,impact:0});emitWorldEvent(world,{type:'ManagerSabbaticalStarted',date,actorIds:[m.id],importance:2,summary:`${m.name} decidiu se afastar temporariamente do futebol.`,payload:{managerId,endDate:l.sabbaticalUntil}});return true;}
export function retireManager(world:World,managerId:string,date:string){const m=managerCharacterState(world).characters.get(managerId),l=managerCareerLife(world,managerId);if(!m||!l||l.status==='retired')return false;const old=m.currentClubId;m.currentClubId='';l.status='retired';l.since=date;l.lastClubId=old||l.lastClubId;m.history.push({date,type:'retirement',summary:'Encerrou a carreira como treinador.',impact:10});emitWorldEvent(world,{type:'ManagerRetired',date,actorIds:[m.id],clubIds:old?[old]:[],importance:5,summary:`${m.name} anunciou aposentadoria como treinador.`,payload:{managerId}});return true;}
export function tickManagerCareerLife(world:World,date:string){const s=managerCareerLifeState(world,date);if(s.lastTick===date)return;s.lastTick=date;for(const m of managerCharacterState(world).characters.values()){const l=s.managers.get(m.id)!;l.retirementEligible=m.age>=66;if(l.status==='unemployed'){l.unemployedDays=Math.max(l.unemployedDays,diff(date,l.since));if(l.unemployedDays>30){m.reputation.mediaProfile=clamp(m.reputation.mediaProfile-.003);m.reputation.coachingPrestige=clamp(m.reputation.coachingPrestige-.0015);}generateUnemployedOffer(world,m,date);}else if(l.status==='sabbatical'){const evo=managerEvolutionRecord(world,m.id);if(evo){evo.careerStress=clamp(evo.careerStress-.12);evo.burnoutRisk=clamp(evo.burnoutRisk-.18);}if(l.sabbaticalUntil&&date>=l.sabbaticalUntil){l.status='unemployed';l.since=date;l.unemployedDays=0;m.history.push({date,type:'sabbaticalEnd',summary:'Retornou ao mercado após período sabático.',impact:1});emitWorldEvent(world,{type:'ManagerSabbaticalEnded',date,actorIds:[m.id],importance:2,summary:`${m.name} voltou a considerar novos projetos.`,payload:{managerId:m.id}});}}else if(l.status==='employed'&&!m.currentClubId){l.status='unemployed';l.since=date;l.unemployedDays=0;}if(l.status==='unemployed'&&m.age>=72&&m.id!==userManager(world)?.id&&pseudo(`${m.id}-${date}-retire`)<.0008*Math.max(1,m.age-70))retireManager(world,m.id,date);}}
export function acceptCareerOffer(world:World,offerId:string,date:string){return resolveManagerJobOffer(world,offerId,true,date);}
export function snapshotManagerCareerLife(world:World):ManagerCareerLifeSnapshot{const s=managerCareerLifeState(world);return{managers:[...s.managers.entries()].map(([k,v])=>[k,{...v,applications:[...v.applications]}]),lastTick:s.lastTick};}
export function restoreManagerCareerLife(world:World,snapshot?:ManagerCareerLifeSnapshot){if(!snapshot)return;states.set(world,{managers:new Map(snapshot.managers.map(([k,v])=>[k,{...v,applications:[...v.applications]}])),wired:false,lastTick:snapshot.lastTick});}
