import './manager-job-market.css';
import type { World } from './engine';
import { managerCharacterState, userManager } from './manager-character';
import { applyManagerToVacancy, finalizeUserManagerHireFromOffer, openManagerVacancies } from './manager-job-market-v2';
import { dailyCalendar } from './daily-simulation';
import { interviewQuestions, pendingUserContractNegotiations, pendingUserInterviews, resolveUserInterview, submitManagerContractCounter, acceptCurrentClubTerms, type ManagerContractTerms } from './manager-job-interview';
import { managerEmploymentState } from './manager-employment';

const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const clubName=(world:World,id:string)=>world.clubs.find(c=>c.id===id)?.name??id;
const managerName=(world:World,id:string)=>managerCharacterState(world).characters.get(id)?.name??id;
const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
function interviewPanel(world:World){const pending=pendingUserInterviews(world)[0];if(!pending)return'';return `<section class="card manager-interview-panel"><div class="section-title"><h2>Entrevista com ${esc(clubName(world,pending.clubId))}</h2><span>responder até ${pending.deadlineDate}</span></div><p>Suas respostas serão avaliadas em conjunto com sua biografia, personalidade, reputação e compatibilidade com o projeto.</p><div class="manager-interview-questions">${interviewQuestions.map((q,i)=>`<article><b>${i+1}. ${esc(q.prompt)}</b>${q.answers.map(a=>`<label><input type="radio" name="int-${q.id}" value="${a.id}"> <span>${esc(a.label)}</span></label>`).join('')}</article>`).join('')}</div><button class="mc-primary" id="submit-manager-interview" data-id="${pending.id}">Concluir entrevista</button></section>`;}
function negotiationPanel(world:World){const n=pendingUserContractNegotiations(world)[0];if(!n)return'';const t=n.current;return `<section class="card manager-contract-panel"><div class="section-title"><h2>Negociação com ${esc(clubName(world,n.clubId))}</h2><span>rodada ${n.rounds.length}/${n.maxRounds}</span></div><p>Você pode aceitar a proposta atual ou alterar os termos. Exigências excessivas podem encerrar a negociação.</p><div class="manager-contract-grid"><label>Salário semanal<input id="mgr-salary" type="number" value="${t.salaryWeekly}"></label><label>Anos de contrato<input id="mgr-years" type="number" min="1" max="5" value="${t.years}"></label><label>Autonomia<input id="mgr-autonomy" type="number" min="0" max="100" value="${t.autonomy}"></label><label>Controle de transferências<input id="mgr-transfer-control" type="number" min="0" max="100" value="${t.transferControl}"></label><label>Controle da comissão<input id="mgr-staff-control" type="number" min="0" max="100" value="${t.staffControl}"></label><label>Compromisso com base<input id="mgr-youth" type="number" min="0" max="100" value="${t.youthCommitment}"></label><label>Compromisso de estilo<input id="mgr-style" type="number" min="0" max="100" value="${t.styleCommitment}"></label><label>Meta de liga<input id="mgr-league-target" type="number" min="1" max="30" value="${t.leagueTarget}"></label><label>Cláusula de rescisão<input id="mgr-release" type="number" value="${t.releaseClause}"></label><label>Promessa de orçamento<input id="mgr-budget" type="number" value="${t.transferBudgetPromise}"></label></div><div class="manager-contract-summary"><b>Oferta atual</b><span>${money(t.salaryWeekly)}/semana · ${t.years} anos · autonomia ${t.autonomy}</span></div><div class="mc-mode-actions"><button class="mc-primary" id="accept-manager-terms" data-id="${n.id}">Aceitar termos atuais</button><button class="mc-secondary" id="counter-manager-terms" data-id="${n.id}">Enviar contraproposta</button></div></section>`;}
function finalOfferPanel(world:World){const u=userManager(world);if(!u)return'';const offers=managerEmploymentState(world).offers.filter(o=>o.managerId===u.id&&o.status==='pending'&&o.id.startsWith('job-offer-neg-'));if(!offers.length)return'';return offers.map(o=>`<section class="card"><div class="section-title"><h2>Acordo final · ${esc(clubName(world,o.fromClubId))}</h2><span>expira ${o.expires}</span></div><p>${money(o.salaryWeekly)}/semana · ${o.contractYears} anos · autonomia ${o.autonomy}</p><button class="mc-primary manager-final-accept" data-offer="${o.id}">Assinar contrato e assumir</button></section>`).join('');}
export function renderManagerJobMarket(world:World){const u=userManager(world),vacancies=openManagerVacancies(world);return `<header><div><span class="eyebrow">CARREIRA · MERCADO DE TREINADORES</span><h1>Vagas e processos seletivos</h1><p>Clubes não escolhem apenas pelo nome. Perfil, resultados, estilo, custo, torcida, imprensa e entrevista disputam peso na decisão.</p></div></header>${interviewPanel(world)}${negotiationPanel(world)}${finalOfferPanel(world)}${!vacancies.length?'<section class="card"><p>Nenhuma vaga aberta no momento.</p></section>':`<div class="manager-job-grid">${vacancies.map(v=>`<section class="card manager-job-card"><div class="section-title"><h2>${esc(clubName(world,v.clubId))}</h2><span>${v.stage}</span></div><p>Perfil: ${v.desired.tacticalIdentity} · reputação mínima ${Math.round(v.desired.minimumReputation)} · base ${Math.round(v.desired.youthImportance)}</p><small>Prazo: ${v.deadline}</small>${v.candidates.length?`<table><thead><tr><th>Candidato</th><th>Total</th><th>Diretoria</th><th>Torcida</th><th>Imprensa</th><th>Entrevista</th></tr></thead><tbody>${[...v.candidates].sort((a,b)=>b.total-a.total).slice(0,6).map(c=>`<tr><td>${esc(managerName(world,c.managerId))}${v.preferredManagerId===c.managerId?' ★':''}</td><td><b>${c.total.toFixed(0)}</b></td><td>${c.board.toFixed(0)}</td><td>${c.supporters.toFixed(0)}</td><td>${c.media.toFixed(0)}</td><td>${c.interview?.toFixed(0)??'—'}</td></tr>`).join('')}</tbody></table>`:'<p>O clube ainda está mapeando candidatos.</p>'}${u&&['open','shortlist','interviews'].includes(v.stage)?`<button class="mc-primary manager-apply" data-vacancy="${v.id}">Candidatar-me</button>`:''}</section>`).join('')}</div>`}`;}
function readTerms(base:ManagerContractTerms):ManagerContractTerms{const num=(id:string,fallback:number)=>Number((document.querySelector<HTMLInputElement>(`#${id}`)?.value??fallback));return{salaryWeekly:num('mgr-salary',base.salaryWeekly),years:num('mgr-years',base.years),autonomy:num('mgr-autonomy',base.autonomy),transferControl:num('mgr-transfer-control',base.transferControl),staffControl:num('mgr-staff-control',base.staffControl),youthCommitment:num('mgr-youth',base.youthCommitment),styleCommitment:num('mgr-style',base.styleCommitment),leagueTarget:num('mgr-league-target',base.leagueTarget),releaseClause:num('mgr-release',base.releaseClause),transferBudgetPromise:num('mgr-budget',base.transferBudgetPromise)};}
export function bindManagerJobMarket(world:World,rerender:()=>void){const u=userManager(world);if(!u)return;document.querySelectorAll<HTMLButtonElement>('.manager-apply').forEach(b=>b.addEventListener('click',()=>{applyManagerToVacancy(world,b.dataset.vacancy!,u.id,dailyCalendar(world).date);rerender();}));const intBtn=document.querySelector<HTMLButtonElement>('#submit-manager-interview');intBtn?.addEventListener('click',()=>{const answers:Record<string,string>={};for(const q of interviewQuestions){const chosen=document.querySelector<HTMLInputElement>(`input[name="int-${q.id}"]:checked`);if(chosen)answers[q.id]=chosen.value;}resolveUserInterview(world,intBtn.dataset.id!,answers,dailyCalendar(world).date);rerender();});const n=pendingUserContractNegotiations(world)[0];document.querySelector<HTMLButtonElement>('#accept-manager-terms')?.addEventListener('click',e=>{acceptCurrentClubTerms(world,(e.currentTarget as HTMLButtonElement).dataset.id!,dailyCalendar(world).date);rerender();});document.querySelector<HTMLButtonElement>('#counter-manager-terms')?.addEventListener('click',e=>{if(!n)return;submitManagerContractCounter(world,(e.currentTarget as HTMLButtonElement).dataset.id!,readTerms(n.current),dailyCalendar(world).date);rerender();});document.querySelectorAll<HTMLButtonElement>('.manager-final-accept').forEach(b=>b.addEventListener('click',()=>{const offer=managerEmploymentState(world).offers.find(o=>o.id===b.dataset.offer);if(!offer)return;const vacancy=openManagerVacancies(world).find(v=>v.clubId===offer.fromClubId&&v.preferredManagerId===u.id);if(vacancy)finalizeUserManagerHireFromOffer(world,vacancy.id,offer.id,dailyCalendar(world).date);rerender();}));}
