import type { World } from './engine';
import { emitWorldEvent, onWorldEvent, type WorldEvent } from './event-bus';
import { managerCharacterState, managerByClub, type ManagerCharacter, type TacticalPhilosophy, type TrainingPhilosophy } from './manager-character';
import { managerProfile } from './manager-interactions';

export type ManagerSpecialisation='youthBuilder'|'pressingCoach'|'possessionCoach'|'transitionCoach'|'setPieceExpert'|'peopleManager'|'mediaOperator'|'recruiter'|'analyst'|'medicalAware'|'negotiator'|'disciplinarian';
export type ManagerEvolutionEvidence={matches:number;wins:number;losses:number;trainingDays:number;highPressTraining:number;possessionTraining:number;setPieceTraining:number;youthEvents:number;mediaEvents:number;recruitmentEvents:number;negotiations:number;medicalEvents:number;disciplineInteractions:number;supportInteractions:number;publicInteractions:number;crises:number;promisesKept:number;promisesBroken:number};
export type ManagerOriginSnapshot={personality:Record<string,number>;tactical:TacticalPhilosophy;training:TrainingPhilosophy;knowledge:Record<string,number>;reputation:Record<string,number>;createdSeason:number};
export type ManagerEvolutionRecord={managerId:string;origin:ManagerOriginSnapshot;evidence:ManagerEvolutionEvidence;specialisations:ManagerSpecialisation[];identityScore:Partial<Record<ManagerSpecialisation,number>>;lastSeasonProcessed?:number;lastStressDate?:string;careerStress:number;burnoutRisk:number;adaptationMomentum:number;identityShifts:{date:string;summary:string;changes:string[]}[]};
export type ManagerEvolutionSnapshot={records:[string,ManagerEvolutionRecord][]};
const states=new WeakMap<World,Map<string,ManagerEvolutionRecord>>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const emptyEvidence=():ManagerEvolutionEvidence=>({matches:0,wins:0,losses:0,trainingDays:0,highPressTraining:0,possessionTraining:0,setPieceTraining:0,youthEvents:0,mediaEvents:0,recruitmentEvents:0,negotiations:0,medicalEvents:0,disciplineInteractions:0,supportInteractions:0,publicInteractions:0,crises:0,promisesKept:0,promisesBroken:0});
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v)) as T;}
function recordFor(world:World,m:ManagerCharacter):ManagerEvolutionRecord{let map=states.get(world);if(!map){map=new Map();states.set(world,map);}let r=map.get(m.id);if(!r){r={managerId:m.id,origin:{personality:clone(m.personality),tactical:clone(m.tactical),training:clone(m.training),knowledge:clone(m.knowledge),reputation:clone(m.reputation),createdSeason:m.createdSeason},evidence:emptyEvidence(),specialisations:[],identityScore:{},careerStress:20,burnoutRisk:5,adaptationMomentum:50,identityShifts:[]};map.set(m.id,r);}return r;}
export function managerEvolutionState(world:World){let map=states.get(world);if(!map){map=new Map();states.set(world,map);}for(const m of managerCharacterState(world).characters.values())recordFor(world,m);return map;}
function managerForEvent(world:World,event:WorldEvent){for(const clubId of event.clubIds){const m=managerByClub(world,clubId);if(m)return m;}return undefined;}
function collect(world:World,event:WorldEvent){const m=managerForEvent(world,event);if(!m)return;const e=recordFor(world,m).evidence;
 if(event.type==='MatchCompleted'){e.matches++;const [home,away]=event.clubIds,h=Number(event.payload.homeGoals??0),a=Number(event.payload.awayGoals??0);if((m.currentClubId===home&&h>a)||(m.currentClubId===away&&a>h))e.wins++;if((m.currentClubId===home&&h<a)||(m.currentClubId===away&&a<h))e.losses++;}
 if(event.type==='TrainingCompleted'){e.trainingDays++;const sessions=(event.payload.sessions as {type?:string}[]|undefined)??[];if(sessions.some(s=>['pressing','transition'].includes(String(s.type))))e.highPressTraining++;if(sessions.some(s=>['technical','passing','teamShape'].includes(String(s.type))))e.possessionTraining++;if(sessions.some(s=>String(s.type)==='setPieces'))e.setPieceTraining++;}
 if(event.type==='YouthPlayerGenerated')e.youthEvents++;
 if(event.type==='MediaStoryPublished')e.mediaEvents++;
 if(event.type==='RecruitmentApproved'||event.type==='RecruitmentRejected')e.recruitmentEvents++;
 if(event.type==='NegotiationEnded')e.negotiations++;
 if(event.type==='PlayerInjured'||event.type==='PlayerRecovered')e.medicalEvents++;
 if(event.type==='DressingRoomCrisis')e.crises++;
 if(event.type==='PromiseKept')e.promisesKept++;if(event.type==='PromiseBroken')e.promisesBroken++;
 if(event.type==='ManagerInteractionResolved'){const kind=String(event.payload.kind??'');const option=String(event.payload.optionId??event.payload.choiceId??'');if(kind==='discipline'||option.includes('warning')||option.includes('standard'))e.disciplineInteractions++;if(['support','personal'].includes(kind)||option.includes('support')||option.includes('listen'))e.supportInteractions++;if(kind==='media'||option.includes('public')||option.includes('media'))e.publicInteractions++;}
}
const add=(obj:Record<string,number>,key:string,delta:number)=>obj[key]=clamp((obj[key]??50)+delta);
function score(r:ManagerEvolutionRecord,m:ManagerCharacter){const e=r.evidence,total=Math.max(1,e.matches),winRate=e.wins/total;const s:Partial<Record<ManagerSpecialisation,number>>={
 youthBuilder:m.knowledge.youthDevelopment*.55+m.tactical.youthUsage*.25+Math.min(20,e.youthEvents*.8),
 pressingCoach:m.knowledge.tactics*.35+m.tactical.pressingPreference*.4+Math.min(25,e.highPressTraining*.12),
 possessionCoach:m.knowledge.tactics*.3+m.tactical.possessionPreference*.45+Math.min(25,e.possessionTraining*.1),
 transitionCoach:m.knowledge.tactics*.35+m.tactical.counterAttack*.4+Math.min(25,e.highPressTraining*.08),
 setPieceExpert:m.knowledge.setPieces*.7+Math.min(30,e.setPieceTraining*.25),peopleManager:m.knowledge.manManagement*.5+m.personality.empathy*.25+m.personality.diplomacy*.15+Math.min(10,e.supportInteractions*.5),
 mediaOperator:m.knowledge.media*.6+m.personality.mediaSkill*.25+Math.min(15,e.mediaEvents*.08),recruiter:m.knowledge.scouting*.5+m.knowledge.networking*.25+Math.min(20,e.recruitmentEvents*.35),analyst:m.knowledge.dataAnalysis*.65+m.knowledge.tactics*.15,medicalAware:m.knowledge.medicalAwareness*.7+Math.min(20,e.medicalEvents*.12),negotiator:m.knowledge.contractLaw*.45+m.knowledge.financialAwareness*.25+m.knowledge.networking*.15+Math.min(15,e.negotiations*.3),disciplinarian:m.personality.discipline*.5+m.personality.assertiveness*.25+Math.min(20,e.disciplineInteractions*.5)};
 for(const k of Object.keys(s) as ManagerSpecialisation[])s[k]=clamp((s[k]??0)+(winRate-.5)*8);r.identityScore=s;
}
function unlock(world:World,m:ManagerCharacter,r:ManagerEvolutionRecord,date:string){for(const [k,v] of Object.entries(r.identityScore) as [ManagerSpecialisation,number][])if(v>=78&&!r.specialisations.includes(k)){r.specialisations.push(k);m.history.push({date,type:'specialisation',summary:`Especialização consolidada: ${k}.`,impact:4});emitWorldEvent(world,{type:'ManagerSpecialisationUnlocked',date,actorIds:[m.id],clubIds:[m.currentClubId],importance:3,summary:`${m.name} consolidou uma nova identidade profissional: ${k}.`,payload:{managerId:m.id,specialisation:k,score:v}});}}
function annualShift(world:World,m:ManagerCharacter,r:ManagerEvolutionRecord,date:string){if(r.lastSeasonProcessed===world.season)return;r.lastSeasonProcessed=world.season;const e=r.evidence,changes:string[]=[];const change=(key:keyof typeof m.personality,delta:number,label:string)=>{if(Math.abs(delta)<.15)return;m.personality[key]=clamp(m.personality[key]+delta);changes.push(`${label} ${delta>0?'+':''}${delta.toFixed(1)}`);};
 change('patience',e.crises>=3?-1.2:e.supportInteractions>=6?.6:0,'paciência');change('diplomacy',e.supportInteractions>=5?.7:e.publicInteractions>=8?-.5:0,'diplomacia');change('confrontation',e.disciplineInteractions>=6?.8:e.supportInteractions>=8?-.4:0,'confronto');change('discipline',e.disciplineInteractions>=5?.6:0,'disciplina');change('mediaSkill',e.mediaEvents>=20?.7:0,'mídia');change('adaptability',e.trainingDays>=120?.5:0,'adaptabilidade');change('forgiveness',e.supportInteractions>=8?.5:e.promisesBroken>=3?-.5:0,'perdão');
 if(e.highPressTraining>e.possessionTraining*1.25){m.tactical.pressingPreference=clamp(m.tactical.pressingPreference+.8);changes.push('pressão +0.8');}if(e.possessionTraining>e.highPressTraining*1.25){m.tactical.possessionPreference=clamp(m.tactical.possessionPreference+.8);changes.push('posse +0.8');}if(e.setPieceTraining>=18){m.tactical.setPieceImportance=clamp(m.tactical.setPieceImportance+.7);changes.push('bolas paradas +0.7');}if(e.youthEvents>=8){m.tactical.youthUsage=clamp(m.tactical.youthUsage+.7);changes.push('uso de jovens +0.7');}
 if(changes.length){r.identityShifts.push({date,summary:`A temporada ${world.season} alterou a identidade profissional de ${m.name}.`,changes});m.history.push({date,type:'identityShift',summary:`Evolução de identidade: ${changes.join(', ')}.`,impact:2});emitWorldEvent(world,{type:'ManagerIdentityShift',date,actorIds:[m.id],clubIds:[m.currentClubId],importance:2,summary:`A experiência da temporada alterou o perfil de ${m.name}.`,payload:{managerId:m.id,changes}});}score(r,m);unlock(world,m,r,date);r.evidence=emptyEvidence();}
export function tickManagerLongTermEvolution(world:World,date:string){for(const m of managerCharacterState(world).characters.values()){const r=recordFor(world,m),p=managerProfile(world,m.currentClubId);const stress=p?.stress??25;r.careerStress=clamp(r.careerStress*.96+stress*.04);r.burnoutRisk=clamp(r.burnoutRisk*.98+Math.max(0,r.careerStress-62)*.03+Math.max(0,r.evidence.crises-2)*.08);r.adaptationMomentum=clamp(50+(m.personality.adaptability-50)*.45+(r.evidence.trainingDays>80?8:0)-(r.careerStress>75?10:0));if(date.endsWith('-06-30')||date.endsWith('-07-01'))annualShift(world,m,r,date);}}
export function wireManagerLongTermEvolution(world:World){managerEvolutionState(world);onWorldEvent(world,'*',(e)=>collect(world,e));}
export function managerEvolutionRecord(world:World,managerId:string){return managerEvolutionState(world).get(managerId);}
export function snapshotManagerEvolution(world:World):ManagerEvolutionSnapshot{return{records:[...managerEvolutionState(world).entries()].map(([k,v])=>[k,clone(v)])};}
export function restoreManagerEvolution(world:World,snapshot?:ManagerEvolutionSnapshot){if(!snapshot)return;states.set(world,new Map(snapshot.records.map(([k,v])=>[k,clone(v)])));}
