import type { World } from './engine';
export type ManagerBehaviorTag='protective'|'transparent'|'accountable'|'diplomatic'|'ambitious'|'confrontational'|'evasive'|'harsh'|'supportive'|'consistent'|'inconsistent';
export type ManagerBehaviorProfile={managerId:string;protective:number;transparent:number;accountable:number;diplomatic:number;ambitious:number;confrontational:number;evasive:number;harsh:number;supportive:number;consistent:number;lastUpdated:string};
export type PublicStatement={id:string;managerId:string;clubId:string;date:string;topic:string;text:string;behavior:ManagerBehaviorTag[];source:'pressConference'|'mediaInterview'|'playerConversation'|'boardConversation'|'agentConversation'|'staffConversation';playerId?:string;reporterId?:string;importance:number};
export type SocialMemorySnapshot={profiles:[string,ManagerBehaviorProfile][];statements:PublicStatement[]};
type State={profiles:Map<string,ManagerBehaviorProfile>;statements:PublicStatement[]};
const states=new WeakMap<World,State>();const clamp=(n:number)=>Math.max(0,Math.min(100,n));
function state(w:World){let s=states.get(w);if(!s){s={profiles:new Map(),statements:[]};states.set(w,s)}return s}
export function managerBehavior(w:World,managerId:string){const s=state(w);let p=s.profiles.get(managerId);if(!p){p={managerId,protective:50,transparent:50,accountable:50,diplomatic:50,ambitious:50,confrontational:35,evasive:25,harsh:30,supportive:50,consistent:55,lastUpdated:`${w.season}-07-25`};s.profiles.set(managerId,p)}return p}
const effects:Record<ManagerBehaviorTag,Partial<Record<keyof Omit<ManagerBehaviorProfile,'managerId'|'lastUpdated'>,number>>>={protective:{protective:3,supportive:1},transparent:{transparent:3,evasive:-2},accountable:{accountable:3,transparent:1},diplomatic:{diplomatic:3,confrontational:-1},ambitious:{ambitious:3},confrontational:{confrontational:4,diplomatic:-2},evasive:{evasive:4,transparent:-2},harsh:{harsh:4,supportive:-2},supportive:{supportive:4,harsh:-1},consistent:{consistent:3},inconsistent:{consistent:-4}};
export function recordManagerBehavior(w:World,managerId:string,date:string,tags:ManagerBehaviorTag[]){const p=managerBehavior(w,managerId);for(const tag of tags)for(const[k,v]of Object.entries(effects[tag]) as [keyof Omit<ManagerBehaviorProfile,'managerId'|'lastUpdated'>,number][]){p[k]=clamp(p[k]+v)}p.lastUpdated=date;return p}
export function recordManagerStatement(w:World,input:Omit<PublicStatement,'id'>){const s=state(w),row:PublicStatement={...input,id:`statement-${input.managerId}-${input.date}-${s.statements.length+1}`};s.statements.push(row);if(s.statements.length>3000)s.statements.splice(0,s.statements.length-3000);recordManagerBehavior(w,input.managerId,input.date,input.behavior);return row}
export function recentManagerStatements(w:World,managerId:string,opts:{topic?:string;playerId?:string;reporterId?:string;limit?:number}={}){return state(w).statements.filter(x=>x.managerId===managerId&&(!opts.topic||x.topic===opts.topic)&&(!opts.playerId||x.playerId===opts.playerId)&&(!opts.reporterId||x.reporterId===opts.reporterId)).slice(-(opts.limit??20)).reverse()}
export function statementRecall(w:World,managerId:string,topic:string,reporterId?:string){const rows=recentManagerStatements(w,managerId,{topic,reporterId,limit:8});return rows.find(x=>x.importance>=2)??recentManagerStatements(w,managerId,{topic,limit:8})[0]}
export function behaviorLabel(p:ManagerBehaviorProfile){const entries:[string,number][]=[['protetor',p.protective],['transparente',p.transparent],['responsável',p.accountable],['diplomático',p.diplomatic],['ambicioso',p.ambitious],['confrontador',p.confrontational],['evasivo',p.evasive],['duro',p.harsh],['próximo do grupo',p.supportive]];return entries.sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>x[0])}
export function snapshotManagerSocialMemory(w:World):SocialMemorySnapshot{const s=state(w);return{profiles:[...s.profiles.entries()].map(([k,v])=>[k,{...v}]),statements:s.statements.map(x=>({...x,behavior:[...x.behavior]}))}}
export function restoreManagerSocialMemory(w:World,x?:SocialMemorySnapshot){states.set(w,{profiles:new Map((x?.profiles??[]).map(([k,v])=>[k,{...v}])),statements:(x?.statements??[]).map(v=>({...v,behavior:[...v.behavior]}))})}
