import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { managerCharacterState, managerByClub, userManager, type ManagerCharacter } from './manager-character';
import { managerEmploymentState, resolveManagerJobOffer } from './manager-employment';
import { managerEvolutionRecord } from './manager-longterm-evolution';
import { completedInterviewForVacancy, openUserContractNegotiation, openUserManagerInterview, pendingUserContractNegotiations, pendingUserInterviews } from './manager-job-interview';

export type VacancyStage='open'|'shortlist'|'interviews'|'negotiation'|'filled'|'closed';
export type CandidateEvaluation={managerId:string;source:'unemployed'|'employed'|'application';reputation:number;tactical:number;people:number;youth:number;finance:number;availability:number;supporters:number;media:number;board:number;interview?:number;total:number;risks:string[];strengths:string[]};
export type ManagerVacancy={id:string;clubId:string;openedDate:string;reason:string;stage:VacancyStage;deadline:string;publicity:number;desired:{minimumReputation:number;tacticalIdentity:'any'|'possession'|'pressing'|'defensive'|'transition';youthImportance:number;financialDiscipline:number};candidates:CandidateEvaluation[];shortlist:string[];preferredManagerId?:string;filledByManagerId?:string};
export type ManagerJobMarketSnapshot={vacancies:ManagerVacancy[];lastTick?:string};
const states=new WeakMap<World,ManagerJobMarketSnapshot>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const addDays=(iso:string,d:number)=>{const x=new Date(`${iso}T12:00:00Z`);x.setUTCDate(x.getUTCDate()+d);return x.toISOString().slice(0,10)};
const diff=(a:string,b:string)=>Math.round((new Date(`${a}T12:00:00Z`).getTime()-new Date(`${b}T12:00:00Z`).getTime())/86400000);
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:string)=>{const x=Math.sin(hash(s)*12.9898)*43758.5453;return x-Math.floor(x)};
export function managerJobMarketState(world:World){let s=states.get(world);if(!s){s={vacancies:[]};states.set(world,s);}return s;}
function desired(world:World,clubId:string){const c=world.clubs.find(x=>x.id===clubId),rep=c?.reputation??60;const identity:candidateIdentity=c?.tactics.pressing>=70?'pressing':c?.tactics.mentality==='defensive'?'defensive':c?.tactics.transition==='counter'?'transition':c?.tactics.passingStyle==='short'?'possession':'any';return{minimumReputation:clamp(rep-18),tacticalIdentity:identity,youthImportance:clamp(42+rep*.22),financialDiscipline:55};}
type candidateIdentity=ManagerVacancy['desired']['tacticalIdentity'];
export function openManagerVacancy(world:World,clubId:string,date:string,reason='sacked'){const s=managerJobMarketState(world),existing=s.vacancies.find(v=>v.clubId===clubId&&!['filled','closed'].includes(v.stage));if(existing)return existing;const v:ManagerVacancy={id:`vac-${clubId}-${date}`,clubId,openedDate:date,reason,stage:'open',deadline:addDays(date,reason==='sacked'?18:30),publicity:reason==='sacked'?72:48,desired:desired(world,clubId),candidates:[],shortlist:[]};s.vacancies.push(v);emitWorldEvent(world,{type:'ManagerVacancyOpened',date,clubIds:[clubId],importance:4,summary:`${clubId} iniciou processo para contratar treinador.`,payload:{vacancyId:v.id,reason}});return v;}
function tacticalFit(m:ManagerCharacter,v:ManagerVacancy){switch(v.desired.tacticalIdentity){case'pressing':return m.tactical.pressingPreference;case'possession':return m.tactical.possessionPreference;case'transition':return m.tactical.counterAttack;case'defensive':return clamp((100-m.tactical.defensiveLinePreference)*.45+(100-m.tactical.creativeFreedom)*.2+m.personality.pragmatism*.35);default:return 65;}}
function evaluate(world:World,v:ManagerVacancy,m:ManagerCharacter,source:CandidateEvaluation['source']):CandidateEvaluation{const club=world.clubs.find(c=>c.id===v.clubId),current=m.currentClubId?world.clubs.find(c=>c.id===m.currentClubId):undefined;const reputation=clamp(m.reputation.domestic*.55+m.reputation.coachingPrestige*.45),tactical=clamp(tacticalFit(m,v)),people=clamp(m.knowledge.manManagement*.55+m.personality.diplomacy*.25+m.personality.discipline*.2),youth=clamp(m.knowledge.youthDevelopment*.6+m.tactical.youthUsage*.4),finance=clamp(m.knowledge.financialAwareness*.6+m.knowledge.contractLaw*.2+m.personality.pragmatism*.2),availability=m.currentClubId?clamp(70-(current?.reputation??55)*.35+m.ambition.reputationAmbition*.18):96,supporters=clamp(48+m.reputation.formerPlayerPrestige*.18+(m.reputation.domestic-(club?.reputation??60))*.25+(pseudo(`${v.id}-${m.id}-fan`)-.5)*20),media=clamp(48+m.reputation.mediaProfile*.28+m.reputation.coachingPrestige*.18+(pseudo(`${v.id}-${m.id}-media`)-.5)*22),board=clamp(reputation*.26+tactical*.22+people*.17+youth*(v.desired.youthImportance/100)*.16+finance*.1+availability*.09);const risks:string[]=[],strengths:string[]=[];if(reputation<v.desired.minimumReputation)risks.push('reputação abaixo do desejado');if(tactical<45)risks.push('baixa aderência tática');if(people<45)risks.push('dúvidas sobre gestão humana');if(availability<45)risks.push('difícil retirada do clube atual');if(supporters<42)risks.push('torcida pouco receptiva');if(tactical>=75)strengths.push('forte aderência tática');if(people>=75)strengths.push('gestão humana valorizada');if(youth>=75)strengths.push('forte histórico com jovens');if(reputation>=75)strengths.push('nome de alto prestígio');const total=clamp(board*.52+supporters*.13+media*.1+availability*.1+reputation*.15);return{managerId:m.id,source,reputation,tactical,people,youth,finance,availability,supporters,media,board,total,risks,strengths};}
function shortlist(world:World,v:ManagerVacancy,date:string){const rows=[...managerCharacterState(world).characters.values()].filter(m=>m.currentClubId!==v.clubId&&m.age<74).map(m=>evaluate(world,v,m,m.currentClubId?'employed':'unemployed')).filter(r=>r.total>=48).sort((a,b)=>b.total-a.total).slice(0,10);v.candidates=rows;v.shortlist=rows.slice(0,5).map(x=>x.managerId);v.stage='shortlist';emitWorldEvent(world,{type:'ManagerShortlistCreated',date,actorIds:v.shortlist,clubIds:[v.clubId],importance:3,summary:`${v.clubId} reduziu a busca a ${v.shortlist.length} candidatos.`,payload:{vacancyId:v.id,shortlist:v.shortlist}});}
function interviews(world:World,v:ManagerVacancy,date:string){const u=userManager(world);for(const id of v.shortlist.slice(0,4)){const m=managerCharacterState(world).characters.get(id),row=v.candidates.find(x=>x.managerId===id);if(!m||!row)continue;if(u?.id===id){openUserManagerInterview(world,v.id,v.clubId,date);continue;}const communication=m.personality.diplomacy*.25+m.personality.assertiveness*.2+m.personality.mediaSkill*.12+m.knowledge.manManagement*.18+m.knowledge.tactics*.15+m.personality.pragmatism*.1;const consistency=100-Math.abs(m.tactical.youthUsage-v.desired.youthImportance)*.3;row.interview=clamp(communication*.78+consistency*.22+(pseudo(`${v.id}-${id}-int`)-.5)*12);row.total=clamp(row.total*.72+row.interview*.28);if(v.publicity>=60&&pseudo(`${v.id}-${id}-leak`)<.3)emitWorldEvent(world,{type:'ManagerInterviewLeaked',date,actorIds:[id],clubIds:[v.clubId],importance:2,summary:`A imprensa descobriu a entrevista de ${m.name} com ${v.clubId}.`,payload:{vacancyId:v.id,managerId:id,supporters:row.supporters,media:row.media}});}v.stage='interviews';}
function syncUserInterview(world:World,v:ManagerVacancy){const u=userManager(world);if(!u||!v.shortlist.includes(u.id))return true;const done=completedInterviewForVacancy(world,v.id,u.id);if(!done)return false;const row=v.candidates.find(c=>c.managerId===u.id);if(row&&row.interview===undefined){row.interview=done.score??50;row.supporters=clamp((row.supporters+(done.supporterReaction??row.supporters))/2);row.media=clamp((row.media+(done.mediaReaction??row.media))/2);row.total=clamp(row.total*.72+row.interview*.28);}return true;}
function offerBest(world:World,v:ManagerVacancy,date:string){if(!syncUserInterview(world,v))return;const best=v.candidates.filter(c=>v.shortlist.includes(c.managerId)).sort((a,b)=>b.total-a.total)[0];if(!best){v.stage='closed';return;}const m=managerCharacterState(world).characters.get(best.managerId),club=world.clubs.find(c=>c.id===v.clubId);if(!m)return;v.preferredManagerId=m.id;v.stage='negotiation';const u=userManager(world);if(u?.id===m.id){openUserContractNegotiation(world,v.id,m.id,v.clubId,date);return;}const state=managerEmploymentState(world);if(state.offers.some(o=>o.managerId===m.id&&o.fromClubId===v.clubId&&o.status==='pending'))return;const salary=Math.round(4500+(club?.reputation??60)*230+m.reputation.coachingPrestige*145+(best.total-60)*160);state.offers.push({id:`job-offer-${m.id}-${v.clubId}-${date}`,managerId:m.id,fromClubId:v.clubId,date,expires:addDays(date,7),salaryWeekly:salary,contractYears:best.total>=80?3:2,autonomy:Math.round(clamp(45+m.reputation.coachingPrestige*.32+best.total*.12)),projectScore:Math.round(best.total),status:'pending',reason:`Escolhido após avaliação comparativa, shortlist e entrevista. ${best.strengths.join('; ')}`});emitWorldEvent(world,{type:'ManagerJobOffer',date,actorIds:[m.id],clubIds:[v.clubId,...(m.currentClubId?[m.currentClubId]:[])],importance:4,summary:`${v.clubId} fez proposta formal a ${m.name}.`,payload:{vacancyId:v.id,total:best.total}});}
function resolvePreferredAI(world:World,v:ManagerVacancy,date:string){if(!v.preferredManagerId)return;const u=userManager(world);if(u?.id===v.preferredManagerId){const pending=pendingUserContractNegotiations(world).find(n=>n.vacancyId===v.id);if(pending)return;const offer=managerEmploymentState(world).offers.find(o=>o.managerId===u.id&&o.fromClubId===v.clubId&&o.status==='pending');if(!offer)return;return;}const m=managerCharacterState(world).characters.get(v.preferredManagerId);if(!m)return;const offer=managerEmploymentState(world).offers.find(o=>o.managerId===m.id&&o.fromClubId===v.clubId&&o.status==='pending');if(!offer)return;const evo=managerEvolutionRecord(world,m.id),current=world.clubs.find(c=>c.id===m.currentClubId),target=world.clubs.find(c=>c.id===v.clubId);const appeal=offer.projectScore+(target?.reputation??60)-(current?.reputation??0)*.6+offer.autonomy*.2+(m.ambition.dreamClubs.includes(target?.name??'')?25:0)-(evo?.burnoutRisk??0)*.08;const accept=!m.currentClubId||appeal>=64||pseudo(`${offer.id}-accept`)<clamp((appeal-42)/65,0,.82);resolveManagerJobOffer(world,offer.id,accept,date);if(accept){v.stage='filled';v.filledByManagerId=m.id;emitWorldEvent(world,{type:'ManagerVacancyFilled',date,actorIds:[m.id],clubIds:[v.clubId],importance:5,summary:`${m.name} foi escolhido para comandar ${v.clubId}.`,payload:{vacancyId:v.id}});}else{v.shortlist=v.shortlist.filter(id=>id!==m.id);v.preferredManagerId=undefined;v.stage=v.shortlist.length?'interviews':'open';}}
export function finalizeUserManagerHireFromOffer(world:World,vacancyId:string,offerId:string,date:string){const v=managerJobMarketState(world).vacancies.find(x=>x.id===vacancyId&&x.stage==='negotiation');if(!v)return false;const ok=resolveManagerJobOffer(world,offerId,true,date);if(!ok)return false;const u=userManager(world);if(!u)return false;v.stage='filled';v.filledByManagerId=u.id;emitWorldEvent(world,{type:'ManagerVacancyFilled',date,actorIds:[u.id],clubIds:[v.clubId],importance:5,summary:`${u.name} foi escolhido para comandar ${v.clubId}.`,payload:{vacancyId:v.id}});return true;}
export function applyManagerToVacancy(world:World,vacancyId:string,managerId:string,date:string){const v=managerJobMarketState(world).vacancies.find(x=>x.id===vacancyId&&['open','shortlist','interviews'].includes(x.stage)),m=managerCharacterState(world).characters.get(managerId);if(!v||!m)return false;let row=v.candidates.find(x=>x.managerId===managerId);if(!row){row=evaluate(world,v,m,'application');v.candidates.push(row);}row.source='application';row.total=clamp(row.total+4);if(!v.shortlist.includes(managerId)&&row.total>=50)v.shortlist.push(managerId);emitWorldEvent(world,{type:'ManagerApplicationSubmitted',date,actorIds:[managerId],clubIds:[v.clubId],importance:2,summary:`${m.name} apresentou candidatura ao ${v.clubId}.`,payload:{vacancyId,total:row.total}});return true;}
export function tickManagerJobMarket(world:World,date:string){const s=managerJobMarketState(world);if(s.lastTick===date)return;s.lastTick=date;for(const club of world.clubs)if(!managerByClub(world,club.id))openManagerVacancy(world,club.id,date,'vacancy');for(const v of s.vacancies){if(['filled','closed'].includes(v.stage))continue;if(date>v.deadline){v.stage='closed';continue;}const age=diff(date,v.openedDate);if(v.stage==='open'&&age>=1)shortlist(world,v,date);else if(v.stage==='shortlist'&&age>=3)interviews(world,v,date);else if(v.stage==='interviews'&&age>=5){if(pendingUserInterviews(world).some(i=>i.vacancyId===v.id))continue;offerBest(world,v,date);}else if(v.stage==='negotiation'&&age>=6)resolvePreferredAI(world,v,date);}}
export function openManagerVacancies(world:World){return managerJobMarketState(world).vacancies.filter(v=>!['filled','closed'].includes(v.stage));}
export function snapshotManagerJobMarket(world:World):ManagerJobMarketSnapshot{return JSON.parse(JSON.stringify(managerJobMarketState(world))) as ManagerJobMarketSnapshot;}
export function restoreManagerJobMarket(world:World,snapshot?:ManagerJobMarketSnapshot){if(snapshot)states.set(world,JSON.parse(JSON.stringify(snapshot)) as ManagerJobMarketSnapshot);}
