import type { Club, Fixture, MatchEvent, MatchStats, Player, World } from './engine';
import { createMatchCore, teamOf } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { matchEventLedger } from './match-event-ledger-v2';
import { lifecycleEvents } from './match-lifecycle-v2';
import { persistCompletedMatchV2 } from './match-season-history-v2';
import { matchInjuries } from './match-contact-injury-v2';
import { playerMatchPerformances } from './match-player-performance-v2';
import { recordMatchExposure } from './player-match-state-v2';
import { recordPartnershipMinutes } from './player-partnerships-v2';
import { ensurePlayerBehavior } from './player-behavior-v2';
import { recordPositionMinutes } from './player-technical-profile-v2';
import { playerUnavailableForClub } from './international-duty-v1';
import { eligibleClubForCompetition } from './club-squad-registration-v1';
import { footballCompetition } from './world-football-data-v1';

const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function seedFor(world:World,fixture:Fixture){let h=2166136261;const s=`${world.season}:${fixture.round}:${fixture.home}:${fixture.away}`;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function minute(second:number){return Math.max(0,Math.floor(second/60))}
function mapEvents(state:any,home:Club,away:Club):MatchEvent[]{const out:MatchEvent[]=[];for(const l of lifecycleEvents(state)){if(l.type==='kickoff')out.push({minute:minute(l.second),type:'kickoff',clubId:l.clubId,text:l.text});if(l.type==='fulltimeWhistle')out.push({minute:minute(l.second),type:'fulltime',text:`Fim de jogo: ${home.name} ${state.home.score}–${state.away.score} ${away.name}.`})}for(const e of matchEventLedger(state)){if(e.type==='shot')out.push({minute:minute(e.second),type:'shot',clubId:e.clubId,playerId:e.playerId,text:'Finalização.',xg:e.xg});if(e.type==='goal'||e.type==='physicalGoal')out.push({minute:minute(e.second),type:'goal',clubId:e.clubId,playerId:e.playerId,secondaryPlayerId:e.secondaryPlayerId,text:'Gol.',xg:e.xg});if(e.type==='keeperSave')out.push({minute:minute(e.second),type:'save',clubId:e.clubId,playerId:e.playerId,secondaryPlayerId:e.secondaryPlayerId,text:'Defesa do goleiro.'})}for(const p of [...state.home.players,...state.away.players])if(p.yellowCards>0)out.push({minute:90,type:'yellow',clubId:p.clubId,playerId:p.playerId,text:'Cartão amarelo.'});return out.sort((a,b)=>a.minute-b.minute)}
function stats(state:any):MatchStats{const total=Math.max(1,state.home.possessionSeconds+state.away.possessionSeconds),homePoss=Math.round(state.home.possessionSeconds/total*100);return{possessionHome:homePoss,possessionAway:100-homePoss,shotsHome:state.home.shots,shotsAway:state.away.shots,shotsOnTargetHome:state.home.shotsOnTarget,shotsOnTargetAway:state.away.shotsOnTarget,passesHome:state.home.attemptedPasses,passesAway:state.away.attemptedPasses,yellowHome:state.home.yellowCards,yellowAway:state.away.yellowCards}}
function applyStanding(world:World,fixture:Fixture){const h=world.standings[fixture.home],a=world.standings[fixture.away],hg=fixture.homeGoals??0,ag=fixture.awayGoals??0;if(!h||!a)return;h.played++;a.played++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(hg>ag){h.wins++;a.losses++;h.points+=3}else if(ag>hg){a.wins++;h.losses++;a.points+=3}else{h.draws++;a.draws++;h.points++;a.points++}}
function applyPhysicalCarryover(state:any,home:Club,away:Club){for(const club of [home,away]){const live=teamOf(state,club.id);for(const lp of live.players){const p=club.players.find(x=>x.id===lp.playerId);if(!p)continue;const load=lp.minutesPlayed/90*(3+lp.fatigue*.075);p.condition=Math.round(clamp(p.condition-load,40,100))}for(const p of club.players.filter(x=>!live.players.some((lp:any)=>lp.playerId===x.id)))p.condition=Math.round(clamp(p.condition+1,40,100))}const injured=new Set(matchInjuries(state).map(x=>x.playerId));for(const club of [home,away])for(const p of club.players)if(injured.has(p.id))p.condition=Math.round(clamp(p.condition-8,30,100))}
function feedPlayerWorldState(world:World,state:any,home:Club,away:Club,date?:string){const perf=playerMatchPerformances(state,home,away),byId=new Map(perf.map(p=>[p.playerId,p]));for(const club of [home,away]){const used=club.players.filter(p=>(byId.get(p.id)?.minutes??0)>0);for(const p of used){const row=byId.get(p.id)!;ensurePlayerBehavior(world,p);recordMatchExposure(world,p,row.minutes,row.rating,date);recordPositionMinutes(world,p,p.position,row.minutes)}for(let i=0;i<used.length;i++)for(let j=i+1;j<used.length;j++){const a=used[i],b=used[j],minutes=Math.min(byId.get(a.id)?.minutes??0,byId.get(b.id)?.minutes??0);if(minutes>=15)recordPartnershipMinutes(world,a,b,minutes,{sharedSuccess:clamp(50+((byId.get(a.id)?.rating??6.5)+(byId.get(b.id)?.rating??6.5)-13)*8,20,90)})}}}
function clubForMatch(world:World,club:Club,date?:string,competitionId?:string){let base=club;if(competitionId&&footballCompetition(world,competitionId))base=eligibleClubForCompetition(world,club,competitionId,world.season);if(!date)return base;const available=base.players.filter(p=>!playerUnavailableForClub(world,p.id,date));if(available.length<11)return base;return{...base,players:available}}
export function simulateFixtureV2(world:World,fixture:Fixture,meta?:{competitionId?:string;date?:string}){const homeOriginal=world.clubs.find(c=>c.id===fixture.home),awayOriginal=world.clubs.find(c=>c.id===fixture.away);if(!homeOriginal||!awayOriginal)throw new Error(`Fixture references missing club: ${fixture.home} vs ${fixture.away}`);const home=clubForMatch(world,homeOriginal,meta?.date,meta?.competitionId),away=clubForMatch(world,awayOriginal,meta?.date,meta?.competitionId);for(const p of [...home.players,...away.players])ensurePlayerBehavior(world,p);const state=createMatchCore(home,away,{seed:seedFor(world,fixture)});simulateMatchCore(state,home,away);fixture.homeGoals=state.home.score;fixture.awayGoals=state.away.score;fixture.homeXg=Number(state.home.xg.toFixed(2));fixture.awayXg=Number(state.away.xg.toFixed(2));fixture.events=mapEvents(state,home,away);fixture.stats=stats(state);fixture.played=true;applyStanding(world,fixture);applyPhysicalCarryover(state,homeOriginal,awayOriginal);persistCompletedMatchV2(world,state,homeOriginal,awayOriginal,{fixtureId:`${world.season}:${fixture.round}:${fixture.home}:${fixture.away}`,competitionId:meta?.competitionId??'league',date:meta?.date,round:fixture.round});feedPlayerWorldState(world,state,homeOriginal,awayOriginal,meta?.date);return state}
export function playCurrentRoundV2(world:World,meta?:{competitionId?:string;date?:string}){const fixtures=world.fixtures.filter(f=>f.round===world.round&&!f.played),states:any[]=[];for(const fixture of fixtures)states.push(simulateFixtureV2(world,fixture,meta));if(fixtures.length)world.round++;return states}
