import type { MatchCoreState, LivePlayer } from './match-core-v2';
import type { Player } from './engine';

const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
export type WeatherKind='clear'|'cloudy'|'lightRain'|'heavyRain'|'storm'|'snow'|'heat';
export type PitchMoisture='dry'|'damp'|'wet'|'waterlogged';
export type MatchEnvironment={weather:WeatherKind;moisture:PitchMoisture;temperature:number;humidity:number;wind:number;windDirection:number;attendance:number;capacity:number;homeSupport:number;awaySupport:number;rivalry:number;importance:number};
export type EnvironmentEffects={ballSpeed:number;ballBounce:number;traction:number;fatigueMultiplier:number;injuryRiskMultiplier:number;homePressure:number;awayPressure:number;crowdNoise:number};

export function inferEnvironment(state:MatchCoreState,input:Partial<MatchEnvironment>={}):MatchEnvironment{const rain=state.weather.rain,temperature=state.weather.temperature,weather:WeatherKind=input.weather??(temperature<=1?'snow':temperature>=33?'heat':rain>=75?'heavyRain':rain>=25?'lightRain':'clear'),moisture:PitchMoisture=input.moisture??(rain>=82?'waterlogged':rain>=48?'wet':rain>=15?'damp':'dry');return{weather,moisture,temperature,humidity:input.humidity??clamp(45+rain*.45,20,100),wind:input.wind??state.weather.wind,windDirection:input.windDirection??state.weather.windDirection,attendance:input.attendance??28000,capacity:input.capacity??35000,homeSupport:input.homeSupport??72,awaySupport:input.awaySupport??28,rivalry:input.rivalry??25,importance:input.importance??45};}
export function environmentEffects(env:MatchEnvironment):EnvironmentEffects{const wet=env.moisture==='damp'?.06:env.moisture==='wet'?.13:env.moisture==='waterlogged'?.28:0,heat=Math.max(0,env.temperature-28)/16,cold=Math.max(0,5-env.temperature)/20,occupancy=clamp(env.attendance/Math.max(1,env.capacity),0,1),crowdNoise=clamp(occupancy*55+env.homeSupport*.22+env.rivalry*.12+env.importance*.11),homePressure=clamp(crowdNoise*.48+env.homeSupport*.25),awayPressure=clamp(crowdNoise*.58+env.rivalry*.12);return{ballSpeed:clamp(1+wet*.12-(env.moisture==='waterlogged'?.16:0),.72,1.18),ballBounce:clamp(1-wet*.45-(env.weather==='snow'?.12:0),.48,1.08),traction:clamp(1-wet*.52-(env.weather==='snow'?.2:0),.42,1),fatigueMultiplier:clamp(1+heat*.34+cold*.08+env.humidity/100*heat*.2,.92,1.62),injuryRiskMultiplier:clamp(1+wet*.22+cold*.12,.9,1.45),homePressure,awayPressure,crowdNoise};}
export function playerEnvironmentModifier(env:MatchEnvironment,effects:EnvironmentEffects,live:LivePlayer,data:Player,isHome:boolean,rng=Math.random){const experience=clamp((data.age-17)*3.2),composure=clamp(data.attributes.decisions*.55+experience*.45),crowdStress=isHome?Math.max(0,effects.homePressure-55)*.12:Math.max(0,effects.awayPressure-45)*.22,stressResistance=composure/100,pressurePenalty=crowdStress*(1-stressResistance),slipBase=(1-effects.traction)*.055,agility=((data.attributes as any).agility??data.attributes.pace??50),slipped=rng()<slipBase*(1-agility/140),fatigueMultiplier=effects.fatigueMultiplier*(slipped?1.04:1);return{pressurePenalty,slipped,fatigueMultiplier,traction:effects.traction};}
export function applyEnvironmentTick(state:MatchCoreState,homePlayers:Map<string,Player>,awayPlayers:Map<string,Player>,rng=Math.random){const env=inferEnvironment(state,((state as any).__environment??{}) as Partial<MatchEnvironment>),effects=environmentEffects(env);(state as any).__environment=env;(state as any).__environmentEffects=effects;for(const p of [...state.home.players,...state.away.players]){if(!p.onPitch||p.sentOff)continue;const isHome=p.clubId===state.home.clubId,data=(isHome?homePlayers:awayPlayers).get(p.playerId);if(!data)continue;const m=playerEnvironmentModifier(env,effects,p,data,isHome,rng);p.fatigue=clamp(p.fatigue+(m.fatigueMultiplier-1)*.0018);if(m.slipped){p.velocity.x*=.42;p.velocity.y*=.42;const log=((state as any).__environmentLog??=[]);log.push({second:state.seconds,kind:'slip',playerId:p.playerId,clubId:p.clubId,traction:m.traction});if(log.length>150)log.shift()}}return effects;}
export function setMatchEnvironment(state:MatchCoreState,input:Partial<MatchEnvironment>){(state as any).__environment={...inferEnvironment(state),...input};return(state as any).__environment as MatchEnvironment;}
