import type { MatchCoreState } from './match-core-v2';

export type LedgerEventType='shot'|'goal'|'physicalGoal'|'assist'|'keyPass'|'bigChance'|'bigChanceMissed'|'keeperSave'|'keeperError'|'frameHit'|'ownGoal'|'turnover'|'errorLeadingToShot'|'errorLeadingToGoal'|'cleanSheet'|'hatTrick';
export type LedgerEvent={id:string;second:number;type:LedgerEventType;clubId?:string;playerId?:string;secondaryPlayerId?:string;xg?:number;postShotXg?:number;detail?:string;meta?:Record<string,unknown>};
let seq=1;
function store(s:MatchCoreState){const a=s as any;if(!a.__matchEventLedger)a.__matchEventLedger=[] as LedgerEvent[];return a.__matchEventLedger as LedgerEvent[]}
function push(s:MatchCoreState,e:Omit<LedgerEvent,'id'|'second'>){const x:LedgerEvent={id:`mev-${seq++}`,second:s.seconds,...e};store(s).push(x);if(store(s).length>700)store(s).shift();return x}
function liveClub(s:MatchCoreState,playerId?:string){if(!playerId)return;const p=[...s.home.players,...s.away.players].find(x=>x.playerId===playerId);return p?.clubId}
function recentReceptionError(s:MatchCoreState,defendingClubId:string,window=8){const rows=(((s as any).__receptions??[]) as any[]).filter(r=>s.seconds-Number(r.second??-999)<=window&&s.seconds>=Number(r.second??0));for(const r of [...rows].reverse()){const cid=liveClub(s,r.playerId);if(cid===defendingClubId&&(r.looseBall||!r.success))return r}return undefined}
function candidateAssist(s:MatchCoreState,attackingClubId:string,shooterId:string){const last=s.ball.lastTouchId;if(!last||last===shooterId)return;return liveClub(s,last)===attackingClubId?last:undefined}
export function recordTurnover(s:MatchCoreState,playerId:string,clubId:string,detail:string){return push(s,{type:'turnover',playerId,clubId,detail})}
export function recordResolvedShot(s:MatchCoreState,input:{clubId:string;defendingClubId:string;shooterId:string;goalkeeperId?:string;xg:number;postShotXg:number;onTarget:boolean;goal:boolean;keeperError:boolean;frameHit?:string;shotType?:string;reason?:string}){const {clubId,defendingClubId,shooterId}=input;push(s,{type:'shot',clubId,playerId:shooterId,xg:input.xg,postShotXg:input.postShotXg,detail:input.shotType,meta:{onTarget:input.onTarget,reason:input.reason}});const big=input.xg>=.35;if(big)push(s,{type:'bigChance',clubId,playerId:shooterId,xg:input.xg});if(big&&!input.goal)push(s,{type:'bigChanceMissed',clubId,playerId:shooterId,xg:input.xg});if(input.frameHit)push(s,{type:'frameHit',clubId,playerId:shooterId,xg:input.xg,detail:input.frameHit});if(input.onTarget&&!input.goal&&input.goalkeeperId)push(s,{type:'keeperSave',clubId:defendingClubId,playerId:input.goalkeeperId,secondaryPlayerId:shooterId,postShotXg:input.postShotXg});if(input.keeperError&&input.goalkeeperId)push(s,{type:'keeperError',clubId:defendingClubId,playerId:input.goalkeeperId,secondaryPlayerId:shooterId,detail:'erro do goleiro na finalização'});
 const assist=candidateAssist(s,clubId,shooterId);if(assist){push(s,{type:'keyPass',clubId,playerId:assist,secondaryPlayerId:shooterId,xg:input.xg,detail:'último toque ofensivo antes da finalização'});if(input.goal)push(s,{type:'assist',clubId,playerId:assist,secondaryPlayerId:shooterId,xg:input.xg})}
 const err=recentReceptionError(s,defendingClubId);if(err){push(s,{type:'errorLeadingToShot',clubId:defendingClubId,playerId:err.playerId,secondaryPlayerId:shooterId,xg:input.xg,detail:'erro de recepção/controle precedeu finalização'});if(input.goal)push(s,{type:'errorLeadingToGoal',clubId:defendingClubId,playerId:err.playerId,secondaryPlayerId:shooterId,xg:input.xg})}
 if(input.goal)push(s,{type:'goal',clubId,playerId:shooterId,secondaryPlayerId:assist,xg:input.xg,postShotXg:input.postShotXg,detail:input.shotType});}
export function recordPhysicalGoal(s:MatchCoreState,input:{scoringClubId:string;concedingClubId:string;lastTouchId?:string;ownGoal:boolean;detail?:string}){if(input.ownGoal&&input.lastTouchId){push(s,{type:'ownGoal',clubId:input.concedingClubId,playerId:input.lastTouchId,detail:input.detail});push(s,{type:'physicalGoal',clubId:input.scoringClubId,secondaryPlayerId:input.lastTouchId,detail:'gol contra por cruzamento completo da linha'});return}push(s,{type:'physicalGoal',clubId:input.scoringClubId,playerId:input.lastTouchId,detail:input.detail})}
export function finalizeMatchLedger(s:MatchCoreState){const a=s as any;if(a.__ledgerFinalized)return;const events=store(s),goals=new Map<string,number>();for(const e of events.filter(x=>x.type==='goal'||x.type==='physicalGoal'))if(e.playerId)goals.set(e.playerId,(goals.get(e.playerId)??0)+1);for(const [id,n] of goals)if(n>=3)push(s,{type:'hatTrick',playerId:id,clubId:liveClub(s,id),detail:`${n} gols`});for(const team of [s.home,s.away]){const conceded=team===s.home?s.away.score:s.home.score;if(conceded===0){const gk=team.players.find(p=>p.onPitch&&(p.role==='goalkeeper'||p.role==='sweeperKeeper'));if(gk)push(s,{type:'cleanSheet',clubId:team.clubId,playerId:gk.playerId,detail:'jogo sem sofrer gol'})}}a.__ledgerFinalized=true}
export function matchEventLedger(s:MatchCoreState){return[...store(s)]}
export function playerLedgerStats(s:MatchCoreState,playerId:string){const xs=store(s).filter(e=>e.playerId===playerId);const count=(t:LedgerEventType)=>xs.filter(e=>e.type===t).length;return{goals:count('goal')+count('physicalGoal'),assists:count('assist'),keyPasses:count('keyPass'),bigChances:count('bigChance'),bigChancesMissed:count('bigChanceMissed'),saves:count('keeperSave'),keeperErrors:count('keeperError'),frameHits:count('frameHit'),ownGoals:count('ownGoal'),turnovers:count('turnover'),errorsLeadingToShot:count('errorLeadingToShot'),errorsLeadingToGoal:count('errorLeadingToGoal'),cleanSheets:count('cleanSheet'),hatTricks:count('hatTrick')}}
