import type { MatchCoreState, Vec2, LivePlayer } from './match-core-v2';
import { distance, livePlayer, teamOf, opponentOf } from './match-core-v2';

export type KickSpec={direction:Vec2;speed:number;lift?:number;spin?:number;ownerId?:string};
export type BallPrediction={position:Vec2;height:number;time:number};
export type InterceptionCandidate={player:LivePlayer;time:number;ballTime:number;margin:number;point:Vec2};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const norm=(v:Vec2)=>{const m=Math.hypot(v.x,v.y)||1;return{x:v.x/m,y:v.y/m}};

export function kickBall(state:MatchCoreState,spec:KickSpec){const d=norm(spec.direction);state.ball.ownerId=undefined;state.ball.lastTouchId=spec.ownerId??state.ball.lastTouchId;state.ball.velocity={x:d.x*spec.speed,y:d.y*spec.speed};state.ball.verticalVelocity=spec.lift??0;state.ball.spin=spec.spin??0;}
export function ballFriction(state:MatchCoreState){const surface=state.pitch.surface==='synthetic'?.992:state.pitch.surface==='hybrid'?.988:.984;const wet=1+state.weather.rain*.0015;const condition=.985+(state.pitch.condition/100)*.01;return clamp(surface*wet*condition,.965,.997)}
export function stepFreeBall(state:MatchCoreState,dt:number){if(state.ball.ownerId){const p=livePlayer(state,state.ball.ownerId);if(p){state.ball.position={...p.position};state.ball.velocity={...p.velocity};state.ball.height=0;state.ball.verticalVelocity=0;}return;}const f=Math.pow(ballFriction(state),dt*4),wind=state.weather.wind*.0025,wx=Math.cos(state.weather.windDirection)*wind,wy=Math.sin(state.weather.windDirection)*wind;state.ball.position.x+=state.ball.velocity.x*dt;state.ball.position.y+=state.ball.velocity.y*dt;state.ball.height=Math.max(0,state.ball.height+state.ball.verticalVelocity*dt);state.ball.velocity.x=(state.ball.velocity.x+wx*dt)*f;state.ball.velocity.y=(state.ball.velocity.y+wy*dt)*f;state.ball.verticalVelocity-=9.81*dt;if(state.ball.height<=0&&state.ball.verticalVelocity<0){state.ball.height=0;state.ball.verticalVelocity*=-.38;state.ball.velocity.x*=.93;state.ball.velocity.y*=.93;}if(Math.hypot(state.ball.velocity.x,state.ball.velocity.y)<.12){state.ball.velocity={x:0,y:0}}}
export function predictBall(state:MatchCoreState,horizon=4,dt=.1):BallPrediction[]{const result:BallPrediction[]=[],copy={position:{...state.ball.position},velocity:{...state.ball.velocity},height:state.ball.height,verticalVelocity:state.ball.verticalVelocity};let t=0;const f=Math.pow(ballFriction(state),dt*4);while(t<=horizon){result.push({position:{...copy.position},height:copy.height,time:t});copy.position.x+=copy.velocity.x*dt;copy.position.y+=copy.velocity.y*dt;copy.height=Math.max(0,copy.height+copy.verticalVelocity*dt);copy.velocity.x*=f;copy.velocity.y*=f;copy.verticalVelocity-=9.81*dt;if(copy.height<=0&&copy.verticalVelocity<0){copy.height=0;copy.verticalVelocity*=-.38;copy.velocity.x*=.93;copy.velocity.y*=.93}t+=dt}return result}
function playerReachTime(p:LivePlayer,point:Vec2,pace:number){const maxSpeed=4.7+pace*.035,turn=Math.abs(Math.atan2(point.y-p.position.y,point.x-p.position.x)-p.facing),turnPenalty=Math.min(Math.PI,Math.abs(Math.atan2(Math.sin(turn),Math.cos(turn))))*.12;return distance(p.position,point)/Math.max(2.6,maxSpeed*(1-p.fatigue*.004))+turnPenalty}
export function interceptionCandidates(state:MatchCoreState,clubId:string,paceOf:(id:string)=>number,horizon=4){const predicted=predictBall(state,horizon,.12),team=teamOf(state,clubId),out:InterceptionCandidate[]=[];for(const p of team.players.filter(x=>x.onPitch&&!x.sentOff)){let best:InterceptionCandidate|undefined;for(const b of predicted){if(b.height>2.2)continue;const pt=playerReachTime(p,b.position,paceOf(p.playerId)),margin=b.time-pt;if(margin<-.15)continue;const c={player:p,time:pt,ballTime:b.time,margin,point:{...b.position}};if(!best||c.ballTime<best.ballTime)best=c}if(best)out.push(best)}return out.sort((a,b)=>a.ballTime-b.ballTime||b.margin-a.margin)}
export function passingLaneRisk(state:MatchCoreState,from:Vec2,to:Vec2,attackingClubId:string){const defenders=opponentOf(state,attackingClubId).players.filter(x=>x.onPitch&&!x.sentOff),dx=to.x-from.x,dy=to.y-from.y,len2=dx*dx+dy*dy||1;let risk=0;for(const d of defenders){const t=clamp(((d.position.x-from.x)*dx+(d.position.y-from.y)*dy)/len2,0,1),px=from.x+dx*t,py=from.y+dy*t,dist=Math.hypot(d.position.x-px,d.position.y-py),central=1-Math.abs(t-.5)*1.2;risk+=Math.max(0,1-dist/5.5)*Math.max(.2,central)}return clamp(risk/Math.max(1,defenders.length*.18),0,1)}
export function tryClaimLooseBall(state:MatchCoreState,paceOf:(id:string)=>number){if(state.ball.ownerId||state.ball.height>1.8)return;const home=interceptionCandidates(state,state.home.clubId,paceOf,1.3)[0],away=interceptionCandidates(state,state.away.clubId,paceOf,1.3)[0],pick=!home?away:!away?home:home.ballTime<away.ballTime?home:away;if(!pick||pick.ballTime>.8)return;state.ball.ownerId=pick.player.playerId;state.ball.position={...pick.player.position};state.ball.velocity={...pick.player.velocity};state.possessionClubId=pick.player.clubId;}

// Cognitive-AI aliases kept explicit so the decision layer can reason in football terms.
export const passInterceptionRisk=passingLaneRisk;
export const predictBallPath=predictBall;
export function bestInterception(state:MatchCoreState,clubId:string,horizon=2){const best=interceptionCandidates(state,clubId,()=>65,horizon)[0];return best?{playerId:best.player.playerId,point:best.point,time:best.ballTime,margin:best.margin}:undefined;}
