import type { MatchStory, MatchStoryAction } from './matchday-story-v1';

const reduceMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
const timers=new WeakMap<HTMLElement,number[]>();
const clamp=(n:number,min=4,max=96)=>Math.max(min,Math.min(max,n));

function clear(center:HTMLElement){for(const t of timers.get(center)??[])window.clearTimeout(t);timers.set(center,[]);center.querySelectorAll('.md-sequence-label,.md-sequence-path,.md-sequence-duel,.md-sequence-zone').forEach(n=>n.remove())}
function remember(center:HTMLElement,id:number){const list=timers.get(center)??[];list.push(id);timers.set(center,list)}
function playerEl(center:HTMLElement,id?:string){return id?center.querySelector<HTMLElement>(`[data-live-player="${CSS.escape(id)}"]`):null}
function movePlayer(el:HTMLElement|undefined|null,to:{x:number;y:number},duration:number,easing='cubic-bezier(.2,.72,.2,1)'){if(!el||reduceMotion)return;el.animate([{left:el.style.left,top:el.style.top},{left:`${to.x}%`,top:`${to.y}%`}],{duration,easing,fill:'none'})}
function drawPath(pitch:HTMLElement,a:MatchStoryAction,duration:number){const dx=a.to.x-a.from.x,dy=a.to.y-a.from.y,dist=Math.hypot(dx,dy);if(dist<1)return;const line=document.createElement('i');line.className=`md-sequence-path ${a.type}`;line.style.left=`${a.from.x}%`;line.style.top=`${a.from.y}%`;line.style.width=`${dist}%`;line.style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;line.style.setProperty('--md-seq-duration',`${duration}ms`);pitch.appendChild(line);window.setTimeout(()=>line.remove(),duration+180)}
function label(pitch:HTMLElement,a:MatchStoryAction){const el=document.createElement('span');el.className=`md-sequence-label ${a.type}`;el.style.left=`${a.to.x}%`;el.style.top=`${a.to.y}%`;el.textContent=a.label;pitch.appendChild(el);window.setTimeout(()=>el.remove(),900)}
function sideOf(el:HTMLElement|null){return el?.classList.contains('home')?'home':el?.classList.contains('away')?'away':undefined}
function base(el:HTMLElement){return{x:Number(el.dataset.baseX??el.style.left.replace('%',''))||50,y:Number(el.dataset.baseY??el.style.top.replace('%',''))||50}}
function isKeeper(el:HTMLElement){const b=base(el);return b.x<11||b.x>89}
function band(el:HTMLElement,side:'home'|'away'){const b=base(el),depth=side==='home'?b.x:100-b.x;return depth<13?'gk':depth<27?'def':depth<44?'mid':depth<57?'wide':'att'}
function zone(pitch:HTMLElement,a:MatchStoryAction){if(!['cross','cutback','through','longBall','shot','goal','save','block','corner','freeKick'].includes(a.type))return;const z=document.createElement('i');z.className=`md-sequence-zone ${a.type}`;z.style.left=`${a.to.x}%`;z.style.top=`${a.to.y}%`;pitch.appendChild(z);window.setTimeout(()=>z.remove(),680)}
function collectiveShift(center:HTMLElement,a:MatchStoryAction,duration:number){if(reduceMotion)return;const actor=playerEl(center,a.playerId),actorSide=sideOf(actor);if(!actorSide)return;const defendingSide=actorSide==='home'?'away':'home';const homeForward=actorSide==='home'?1:-1;const setPiece=['corner','freeKick'].includes(a.type);const attacking=setPiece||![ 'recover','intercept','tackle','loose','press','foul','save','restart'].includes(a.type);const midpoint={x:(a.from.x+a.to.x)/2,y:(a.from.y+a.to.y)/2};const all=[...center.querySelectorAll<HTMLElement>('[data-live-player]')];let sameRank=0,oppRank=0;
  for(const el of all){if(el===actor||el.dataset.livePlayer===a.targetPlayerId)continue;const side=sideOf(el);if(!side)continue;const same=side===actorSide,b=base(el),role=band(el,side);if(role==='gk')continue;if(setPiece){const attackingBoxX=actorSide==='home'?82:18;const defendingBoxX=actorSide==='home'?86:14;if(same){const lane=(sameRank++%5)-2;const x=clamp(attackingBoxX-homeForward*(sameRank%3)*2.4);const y=clamp(50+lane*9+(sameRank%2?4:-4),12,88);movePlayer(el,{x,y},duration*.9)}else{const lane=(oppRank++%5)-2;const x=clamp(defendingBoxX-homeForward*(oppRank%2)*1.8);const y=clamp(50+lane*8,12,88);movePlayer(el,{x,y},duration*.9)}continue}if(same){const lane=(sameRank++%5)-2;let advance=attacking?homeForward*(3.2+(sameRank%3)*.9):homeForward*1.2;if(role==='def')advance*=.55;if(role==='att')advance*=1.25;if(['overlap','underlap'].includes(a.type)&&role==='wide')advance*=1.7;const x=clamp(b.x+advance+(midpoint.x-50)*.035);const widthPull=role==='wide'?.08:.14;const y=clamp(b.y+(midpoint.y-b.y)*widthPull+lane*1.2,6,94);movePlayer(el,{x,y},duration*.92)}else if(side===defendingSide){const lane=(oppRank++%5)-2;let lineShift=attacking?homeForward*2.4:-homeForward*.8;if(role==='def')lineShift=attacking?homeForward*3.3:-homeForward*.6;if(role==='mid')lineShift=attacking?homeForward*2.4:-homeForward*.7;const danger=Math.max(0,1-Math.abs(a.to.x-(actorSide==='home'?88:12))/45);const compact=role==='def'?.22:role==='mid'?.18:.1;const x=clamp(b.x+lineShift+(a.to.x-b.x)*compact*danger);const y=clamp(b.y+(a.to.y-b.y)*(compact+.04)+lane*.7,6,94);movePlayer(el,{x,y},duration*.92)}}}
function goalkeeperAndBackLine(center:HTMLElement,a:MatchStoryAction,duration:number){if(reduceMotion)return;const actor=playerEl(center,a.playerId),attackSide=sideOf(actor);if(!attackSide)return;const defendSide=attackSide==='home'?'away':'home';const all=[...center.querySelectorAll<HTMLElement>('[data-live-player]')];const gk=all.find(el=>sideOf(el)===defendSide&&isKeeper(el));if(gk){const b=base(gk),goalX=defendSide==='home'?7:93;const approach=Math.max(0,1-Math.abs(a.to.x-goalX)/45);const setPiece=['corner','freeKick'].includes(a.type);const x=clamp(goalX+(a.to.x-goalX)*Math.min(setPiece?.1:.13,.04+approach*.09),5,95);const y=clamp(50+(a.to.y-50)*Math.min(setPiece?.36:.28,.11+approach*.17),18,82);movePlayer(gk,{x,y},duration*.9,'cubic-bezier(.18,.68,.24,1)')}
  const defenders=all.filter(el=>sideOf(el)===defendSide&&band(el,defendSide)==='def');const boxX=defendSide==='home'?20:80;defenders.forEach((el,i)=>{const b=base(el);const pressure=Math.max(0,1-Math.abs(a.to.x-boxX)/48);const x=clamp(b.x+(a.to.x-b.x)*(.04+pressure*.13));const targetY=50+(i-(defenders.length-1)/2)*13;const y=clamp(b.y+(targetY-b.y)*.2+(a.to.y-b.y)*pressure*.12,8,92);movePlayer(el,{x,y},duration*.94)});
}
function explicitOffBall(center:HTMLElement,a:MatchStoryAction,duration:number){if(reduceMotion)return;const runner=playerEl(center,a.playerId),receiver=playerEl(center,a.targetPlayerId);if(a.type==='overlap'){movePlayer(runner,a.to,duration*.88,'cubic-bezier(.12,.75,.2,1)');if(receiver)movePlayer(receiver,{x:clamp(a.from.x+(a.to.x-a.from.x)*.3),y:clamp(a.from.y+(50-a.from.y)*.18,8,92)},duration*.72)}else if(a.type==='underlap'){movePlayer(runner,a.to,duration*.86,'cubic-bezier(.16,.78,.2,1)')}else if(a.type==='press'){const side=sideOf(runner);if(!side)return;const mates=[...center.querySelectorAll<HTMLElement>('[data-live-player]')].filter(el=>sideOf(el)===side&&el!==runner&&!isKeeper(el)).slice(0,3);mates.forEach((el,i)=>{const b=base(el);movePlayer(el,{x:clamp(b.x+(a.to.x-b.x)*(.16+i*.025)),y:clamp(b.y+(a.to.y-b.y)*(.2+i*.02),8,92)},duration*.8)})}}
function duelPulse(pitch:HTMLElement,a:MatchStoryAction){if(!['intercept','tackle','loose','press','block','foul','rebound','header','corner','freeKick'].includes(a.type))return;const d=document.createElement('i');d.className=`md-sequence-duel ${a.type}`;d.style.left=`${a.to.x}%`;d.style.top=`${a.to.y}%`;pitch.appendChild(d);window.setTimeout(()=>d.remove(),620)}
function ballFrames(a:MatchStoryAction){const airborne=['cross','switch','longBall','header','corner','freeKick'].includes(a.type),power=['shot','goal'].includes(a.type),scramble=['rebound','loose','tackle','intercept','block'].includes(a.type);const midX=(a.from.x+a.to.x)/2,midY=(a.from.y+a.to.y)/2;const lift=airborne?Math.max(3,Math.min(a.type==='corner'?13:10,Math.abs(a.to.x-a.from.x)*.12)):power?2.5:0;const mid={left:`${midX}%`,top:`${clamp(midY-lift,4,96)}%`,transform:`translate(-50%,-50%) scale(${airborne?1.28:power?1.18:scramble?.95:1.06})`};return[{left:`${a.from.x}%`,top:`${a.from.y}%`,transform:'translate(-50%,-50%) scale(1)'},mid,{left:`${a.to.x}%`,top:`${a.to.y}%`,transform:`translate(-50%,-50%) scale(${power?1.22:1.04})`} ]}
function runAction(center:HTMLElement,story:MatchStory,a:MatchStoryAction,duration:number,index:number){const pitch=center.querySelector<HTMLElement>('.md-live-pitch'),ball=pitch?.querySelector<HTMLElement>('.md-ball');if(!pitch||!ball)return;drawPath(pitch,a,duration);label(pitch,a);duelPulse(pitch,a);zone(pitch,a);collectiveShift(center,a,duration);goalkeeperAndBackLine(center,a,duration);explicitOffBall(center,a,duration);movePlayer(playerEl(center,a.playerId),a.from,Math.min(250,duration*.34));movePlayer(playerEl(center,a.targetPlayerId),a.to,duration);if(!reduceMotion){ball.animate(ballFrames(a),{duration,easing:['shot','goal'].includes(a.type)?'cubic-bezier(.12,.72,.12,1)':['cross','switch','longBall','corner','freeKick'].includes(a.type)?'cubic-bezier(.35,.15,.22,1)':'cubic-bezier(.3,.7,.25,1)',fill:'none'})}pitch.dataset.sequenceAction=a.type;center.dataset.sequenceActor=a.playerId??'';document.dispatchEvent(new CustomEvent('touchline:match-action',{detail:{center,story,action:a,index,total:story.actions.length}}))}
function play(center:HTMLElement,story:MatchStory,speed:number){clear(center);if(!story.actions.length)return;const total=Math.max(780,Math.min(2200,1260/story.actions.length))*story.actions.length/Math.max(.5,speed);const step=Math.max(195,total/story.actions.length);story.actions.forEach((a,i)=>remember(center,window.setTimeout(()=>runAction(center,story,a,Math.max(185,step*.84),i),i*step)))}

document.addEventListener('touchline:match-story',e=>{const detail=(e as CustomEvent<{story:MatchStory;speed:number;center:HTMLElement|null}>).detail;if(!detail?.center||!detail.story)return;play(detail.center,detail.story,detail.speed||1)});
