import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf } from './match-core-v2';

export type ShotType='placed'|'power'|'lowDriven'|'curl'|'chip'|'header'|'volley'|'oneOnOne';
export type SaveType='catch'|'parry'|'foot'|'dive'|'smother'|'tipOver'|'punch'|'none';
export type ShotResolution={
 shooterId:string; goalkeeperId?:string; shotType:ShotType; xg:number; postShotXg:number;
 target:Vec2; targetHeight:number; speed:number; onTarget:boolean; goal:boolean;
 saveType:SaveType; rebound:boolean; reboundTarget?:Vec2; keeperError:boolean;
 keeperPositionError:number; reactionMargin:number; reason:string;
};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const attr=(p:Player|undefined,k:string,f:number)=>Number((p?.attributes as any)?.[k]??f);
function pdata(c:Club,id:string){return c.players.find(p=>p.id===id)}
function attackGoal(s:MatchCoreState,cid:string):Vec2{return{x:teamOf(s,cid).attackingRight?s.pitch.length:0,y:s.pitch.width/2}}
function pressure(s:MatchCoreState,p:LivePlayer){const opp=opponentOf(s,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff);const d=opp.length?Math.min(...opp.map(x=>distance(x.position,p.position))):12;return clamp((5.5-d)/5.5*100,0,100)}
function chooseType(s:MatchCoreState,shooter:LivePlayer,src:Player,rng:()=>number):ShotType{const g=attackGoal(s,shooter.clubId),d=distance(shooter.position,g),p=pressure(s,shooter),fin=src.attributes.finishing,tech=src.attributes.technique;if(d<12&&p>50)return rng()<.46?'lowDriven':'oneOnOne';if(d<10&&tech>72&&rng()<.16)return'chip';if(d>22&&tech>70)return rng()<.46?'curl':'power';if(fin>76&&p<45)return'placed';return rng()<.45?'power':'placed'}
function baseXg(s:MatchCoreState,shooter:LivePlayer,src:Player){const g=attackGoal(s,shooter.clubId),d=distance(shooter.position,g),angle=Math.atan2(s.pitch.goalWidth/2,Math.max(1,d))*2,p=pressure(s,shooter);return clamp(.018+(27-d)*.0125+angle*.19+src.attributes.finishing*.00145+src.attributes.decisions*.00055-p*.0011,.01,.82)}
function shotProfile(type:ShotType){switch(type){case'power':return{speed:29,height:1.25,accuracy:-5,handling:-14};case'lowDriven':return{speed:27,height:.38,accuracy:1,handling:-9};case'curl':return{speed:23,height:1.45,accuracy:4,handling:-5};case'chip':return{speed:16,height:2.15,accuracy:-7,handling:4};case'header':return{speed:18,height:1.65,accuracy:-3,handling:1};case'volley':return{speed:27,height:1.3,accuracy:-7,handling:-12};case'oneOnOne':return{speed:24,height:.8,accuracy:5,handling:-7};default:return{speed:22,height:.9,accuracy:7,handling:4}}}
export function resolveShotV2(s:MatchCoreState,attacking:Club,defending:Club,shooter:LivePlayer,src:Player,rng=Math.random,forcedType?:ShotType):ShotResolution{const g=attackGoal(s,attacking.id),type=forcedType??chooseType(s,shooter,src,rng),profile=shotProfile(type),xg=baseXg(s,shooter,src),gkLive=teamOf(s,defending.id).players.find(x=>x.onPitch&&!x.sentOff&&(x.role==='goalkeeper'||x.role==='sweeperKeeper')),gk=gkLive?pdata(defending,gkLive.playerId):undefined,d=distance(shooter.position,g),p=pressure(s,shooter),fin=src.attributes.finishing,tech=src.attributes.technique,comp=attr(src,'composure',src.attributes.decisions),precision=clamp(42+fin*.28+tech*.2+comp*.13-profile.accuracy-p*.12-d*.3+(rng()-.5)*18,8,97),lateralAim=(rng()-.5)*s.pitch.goalWidth*.92*(.65+precision/180),heightAim=clamp(profile.height+(rng()-.5)*(100-precision)/38,.1,2.65),target={x:g.x,y:g.y+lateralAim},onTarget=Math.abs(lateralAim)<=s.pitch.goalWidth/2&&heightAim<=2.44&&rng()*100<precision;
 if(!gkLive||!gk){const goal=onTarget;return log(s,{shooterId:shooter.playerId,shotType:type,xg,postShotXg:onTarget?clamp(xg*1.25,0,1):0,target,targetHeight:heightAim,speed:profile.speed,onTarget,goal,saveType:'none',rebound:false,keeperError:false,keeperPositionError:100,reactionMargin:100,reason:goal?'finalização sem goleiro em condições de intervir':'finalização fora do alvo'})}
 const reflex=attr(gk,'reflexes',gk.attributes.goalkeeping),handling=attr(gk,'handling',gk.attributes.goalkeeping),agility=attr(gk,'agility',(gk.attributes.pace+gk.attributes.goalkeeping)/2),one=attr(gk,'oneOnOnes',gk.attributes.goalkeeping),anticipation=attr(gk,'anticipation',gk.attributes.decisions),reach=attr(gk,'aerialReach',gk.attributes.goalkeeping),gkComp=attr(gk,'composure',gk.attributes.decisions),idealY=g.y+lateralAim*.32,posErr=Math.abs(gkLive.position.y-idealY)+Math.max(0,Math.abs(gkLive.position.x-g.x)-5)*.22,travel=Math.max(.12,d/profile.speed),reaction=.34-(reflex-50)*.0022-(anticipation-50)*.0012+posErr*.012,reactionMargin=travel-reaction,cornerDifficulty=Math.abs(lateralAim)/(s.pitch.goalWidth/2)*34+Math.max(0,heightAim-1.7)*18,special=type==='oneOnOne'?one*.22:type==='chip'?reach*.16:0,saveAbility=reflex*.34+agility*.2+gk.attributes.positioning*.17+anticipation*.12+special+(100-gkLive.fatigue)*.05-posErr*4.3-cornerDifficulty-profile.speed*.35,shotThreat=fin*.22+tech*.16+comp*.12+xg*42+(reactionMargin<0?12:0)+(rng()-.5)*24,postShotXg=onTarget?clamp(xg+(cornerDifficulty-16)*.006+(profile.speed-22)*.008+(shotThreat-saveAbility)*.003,.02,.95):0,keeperError=rng()*100>clamp(99-(100-gkComp)*.035-(100-handling)*.018,91,99.5);
 if(!onTarget)return log(s,{shooterId:shooter.playerId,goalkeeperId:gkLive.playerId,shotType:type,xg,postShotXg:0,target,targetHeight:heightAim,speed:profile.speed,onTarget:false,goal:false,saveType:'none',rebound:false,keeperError:false,keeperPositionError:posErr,reactionMargin,reason:'finalização saiu do alvo antes da intervenção do goleiro'});
 const beaten=shotThreat>saveAbility+(rng()-.5)*12||keeperError;if(beaten)return log(s,{shooterId:shooter.playerId,goalkeeperId:gkLive.playerId,shotType:type,xg,postShotXg,target,targetHeight:heightAim,speed:profile.speed,onTarget:true,goal:true,saveType:'none',rebound:false,keeperError,keeperPositionError:posErr,reactionMargin,reason:keeperError?'erro do goleiro converteu uma bola defensável em gol':'finalização superou alcance, reação e posicionamento do goleiro'});
 const close=d<10,low=heightAim<.65,high=heightAim>1.95,hard=profile.speed>26;let saveType:SaveType=close&&low?'foot':close?'smother':high?'tipOver':Math.abs(lateralAim)>2.1?'dive':'catch';if(type==='header'&&heightAim>1.6&&hard)saveType='punch';const handlingScore=handling*.52+gkComp*.16+reflex*.12-profile.speed*.8+profile.handling-cornerDifficulty*.28-gkLive.fatigue*.18+(rng()-.5)*18,catchable=!['foot','tipOver','punch'].includes(saveType)&&handlingScore>44;if(catchable)saveType='catch';const rebound=!catchable&&(handlingScore<67||hard||saveType==='foot'||saveType==='tipOver'),dir=teamOf(s,defending.id).attackingRight?1:-1,reboundTarget=rebound?{x:clamp(gkLive.position.x+dir*(2+rng()*7),1,s.pitch.length-1),y:clamp(gkLive.position.y+(rng()-.5)*12,1,s.pitch.width-1)}:undefined;return log(s,{shooterId:shooter.playerId,goalkeeperId:gkLive.playerId,shotType:type,xg,postShotXg,target,targetHeight:heightAim,speed:profile.speed,onTarget:true,goal:false,saveType,rebound,reboundTarget,keeperError:false,keeperPositionError:posErr,reactionMargin,reason:rebound?`defesa ${saveType} gerou rebote vivo`:`goleiro realizou ${saveType} e matou a jogada`})}
function log(s:MatchCoreState,r:ShotResolution){const any=s as any;if(!any.__shotResolutionLog)any.__shotResolutionLog=[];any.__shotResolutionLog.push({...r,second:s.seconds});if(any.__shotResolutionLog.length>300)any.__shotResolutionLog.shift();return r}
export function applyShotResolution(s:MatchCoreState,attacking:Club,defending:Club,shooter:LivePlayer,r:ShotResolution){const atk=teamOf(s,attacking.id),def=teamOf(s,defending.id);atk.shots++;atk.xg+=r.xg;s.memory.recentShots.push({clubId:attacking.id,xg:r.xg,second:s.seconds});if(s.memory.recentShots.length>20)s.memory.recentShots.shift();if(r.onTarget)atk.shotsOnTarget++;if(r.goal){atk.score++;atk.momentum=clamp(atk.momentum+10);def.momentum=clamp(def.momentum-7);s.ball.ownerId=undefined;s.possessionClubId=defending.id;s.restart={type:'kickoff',clubId:defending.id,position:{x:s.pitch.length/2,y:s.pitch.width/2}};return}const gkLive=r.goalkeeperId?teamOf(s,defending.id).players.find(p=>p.playerId===r.goalkeeperId):undefined;if(r.saveType==='catch'&&gkLive){s.ball.ownerId=gkLive.playerId;s.ball.position={...gkLive.position};s.ball.velocity={x:0,y:0};s.ball.height=0;s.ball.verticalVelocity=0;s.possessionClubId=defending.id;return}if(r.rebound&&r.reboundTarget&&gkLive){const dx=r.reboundTarget.x-gkLive.position.x,dy=r.reboundTarget.y-gkLive.position.y,m=Math.hypot(dx,dy)||1;s.ball.ownerId=undefined;s.ball.lastTouchId=gkLive.playerId;s.ball.position={...gkLive.position};s.ball.velocity={x:dx/m*(7+r.speed*.18),y:dy/m*(7+r.speed*.18)};s.ball.height=r.saveType==='tipOver'||r.saveType==='punch'?1.2:.25;s.ball.verticalVelocity=r.saveType==='tipOver'||r.saveType==='punch'?2.2:.4;s.possessionClubId=undefined;return}s.ball.ownerId=undefined;s.ball.lastTouchId=shooter.playerId;s.ball.position={...shooter.position};const dx=r.target.x-shooter.position.x,dy=r.target.y-shooter.position.y,m=Math.hypot(dx,dy)||1;s.ball.velocity={x:dx/m*r.speed,y:dy/m*r.speed};s.ball.height=.1;s.ball.verticalVelocity=Math.max(.3,r.targetHeight*.9);s.possessionClubId=undefined}
export function shotResolutionLog(s:MatchCoreState):ShotResolution[]{return[...((((s as any).__shotResolutionLog)??[]) as ShotResolution[])]}
