const reduceMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const pct=(v:string|undefined,f=50)=>{const n=Number((v??'').replace('%',''));return Number.isFinite(n)?n:f};
const roles=['GK','RB','CB','CB','LB','DM','CM','AM','RW','LW','ST'] as const;

type Kind='kickoff'|'build'|'chance'|'shot'|'save'|'goal'|'yellow'|'substitution'|'fulltime';
function kindOf(type:string,text:string):Kind{const t=`${type} ${text}`.toLowerCase();if(/goal|gol/.test(t))return'goal';if(/save|defesa/.test(t))return'save';if(/shot|finaliza|chute/.test(t))return'shot';if(/yellow|cart[aã]o/.test(t))return'yellow';if(/substitution|substitui/.test(t))return'substitution';if(/chance|oportunidade|perigo/.test(t))return'chance';if(/fulltime|fim de jogo/.test(t))return'fulltime';if(/kickoff|início|inicio/.test(t))return'kickoff';return'build'}
function phaseLabel(k:Kind){return k==='goal'?'GOL':k==='shot'?'FINALIZAÇÃO':k==='save'?'DEFESA':k==='chance'?'ATAQUE PERIGOSO':k==='yellow'?'BOLA PARADA':k==='substitution'?'REORGANIZAÇÃO':k==='fulltime'?'FIM DE JOGO':k==='kickoff'?'SAÍDA DE BOLA':'JOGO POSICIONAL'}
function intensity(k:Kind){return k==='goal'?1:k==='shot'?0.92:k==='save'?0.84:k==='chance'?0.78:k==='yellow'?0.34:k==='substitution'?0.22:k==='fulltime'?0.08:k==='kickoff'?0.3:0.5}
function roleDepth(role:string){return role==='GK'?0:role==='CB'?1:role==='RB'||role==='LB'?1.35:role==='DM'?2:role==='CM'?2.6:role==='AM'?3.3:role==='RW'||role==='LW'?3.6:4}
function roleWidth(role:string){return role==='RB'||role==='RW'?-1:role==='LB'||role==='LW'?1:0}

function ensureHud(center:HTMLElement){let hud=center.querySelector<HTMLElement>('.md-dynamics-hud');if(hud)return hud;hud=document.createElement('div');hud.className='md-dynamics-hud';hud.innerHTML=`<div><span data-dyn-phase>JOGO POSICIONAL</span><b data-dyn-state>FORMAÇÃO ORGANIZADA</b></div><i></i><div class="md-dyn-meter" data-dyn-meter>${'<em></em>'.repeat(5)}</div>`;center.querySelector('.md-live-stage')?.prepend(hud);return hud}
function playing(center:HTMLElement){return (center.querySelector<HTMLButtonElement>('[data-replay-play]')?.textContent??'').includes('PAUSAR')}

function bindCenter(center:HTMLElement){if(center.dataset.liveDynamicsBound)return;const pitch=center.querySelector<HTMLElement>('.md-live-pitch');const ball=pitch?.querySelector<HTMLElement>('.md-ball');const type=center.querySelector<HTMLElement>('[data-live-type]');const text=center.querySelector<HTMLElement>('[data-live-text]');if(!pitch||!ball||!type)return;center.dataset.liveDynamicsBound='1';pitch.classList.add('md-dynamics-enabled');const hud=ensureHud(center);const players=[...pitch.querySelectorAll<HTMLElement>('[data-live-player]')];players.filter(p=>p.classList.contains('home')).forEach((p,i)=>p.dataset.dynRole=roles[i]??'CM');players.filter(p=>p.classList.contains('away')).forEach((p,i)=>p.dataset.dynRole=roles[i]??'CM');
  let raf=0,lastType='';
  const tick=(now:number)=>{const k=kindOf(type.textContent??'',text?.textContent??'');const amp=playing(center)&&!reduceMotion?1:0;const actor=players.find(p=>p.classList.contains('actor'));const possession=actor?.classList.contains('home')?'home':actor?.classList.contains('away')?'away':undefined;const bx=pct(ball.style.left),by=pct(ball.style.top);const pr=pitch.getBoundingClientRect();const focusX=clamp(bx,10,90),focusY=clamp(by,12,88);pitch.style.setProperty('--md-focus-x',`${focusX}%`);pitch.style.setProperty('--md-focus-y',`${focusY}%`);pitch.dataset.phase=k;
    if(lastType!==k){lastType=k;hud.querySelector<HTMLElement>('[data-dyn-phase]')!.textContent=phaseLabel(k);hud.querySelector<HTMLElement>('[data-dyn-state]')!.textContent=possession==='home'?'CASA COM A BOLA':possession==='away'?'VISITANTE COM A BOLA':'DISPUTA DE POSSE';const n=Math.max(1,Math.round(intensity(k)*5));hud.querySelectorAll('.md-dyn-meter em').forEach((e,i)=>e.classList.toggle('on',i<n));hud.classList.remove('md-hud-hit');void hud.offsetWidth;hud.classList.add('md-hud-hit')}
    const t=now/1000,high=intensity(k);players.forEach((p,index)=>{if(reduceMotion){p.style.removeProperty('translate');return}const side=p.classList.contains('home')?'home':'away';const same=!!possession&&side===possession;const role=p.dataset.dynRole??'CM';const depth=roleDepth(role),width=roleWidth(role);const sign=side==='home'?1:-1;const px=pct(p.style.left,pct(p.dataset.baseX)),py=pct(p.style.top,pct(p.dataset.baseY));let dx=0,dy=0;const towardBallX=bx-px,towardBallY=by-py;
      if(p===actor){dx=0;dy=0}else if(role==='GK'){dx=clamp(towardBallX*.025,-1.2,1.2);dy=clamp(towardBallY*.035,-1.3,1.3)}else if(same){dx=sign*(.35+depth*.18)*high+clamp(towardBallX*.018,-.8,.8);dy=clamp(towardBallY*.035,-1.5,1.5)+width*(k==='build'?0.35:0.15)}else{dx=clamp(towardBallX*.055,-2.4,2.4)-sign*(.18+Math.max(0,depth-2)*.08)*high;dy=clamp(towardBallY*.07,-2.8,2.8)-width*.12}
      if(k==='chance'||k==='shot'||k==='goal'||k==='save'){if(same&&['AM','RW','LW','ST'].includes(role))dx+=sign*(1.0+depth*.18);if(!same&&role!=='GK')dx-=sign*.45;dy*=1.15}
      if(k==='goal'){dx*=.35;dy*=.35}else if(k==='yellow'||k==='substitution'||k==='fulltime'){dx*=.28;dy*=.28}
      const breath=Math.sin(t*2.2+index*.73)*.16*amp,lateral=Math.cos(t*1.7+index*.51)*.13*amp;dx=(dx+breath)*amp;dy=(dy+lateral)*amp;p.style.translate=`${(dx*pr.width/100).toFixed(2)}px ${(dy*pr.height/100).toFixed(2)}px`;p.style.setProperty('--md-player-speed',String(Math.hypot(dx,dy)))});
    raf=requestAnimationFrame(tick)};
  const observer=new MutationObserver(()=>{if(!document.body.contains(center)){cancelAnimationFrame(raf);observer.disconnect()}});observer.observe(document.body,{childList:true});raf=requestAnimationFrame(tick)
}
function scan(root:ParentNode=document){root.querySelectorAll<HTMLElement>('.matchday-center').forEach(bindCenter)}
const observer=new MutationObserver(records=>{for(const r of records)for(const n of r.addedNodes)if(n instanceof HTMLElement){if(n.matches('.matchday-center'))bindCenter(n);scan(n)}});observer.observe(document.body,{subtree:true,childList:true});queueMicrotask(()=>scan());
