import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, livePlayer, opponentOf, teamOf, territorialControlAt, visiblePlayers } from './match-core-v2';
import { analyseFoul, applyRefereeDecision, isOffsideAtPass, refereeForMatch, suggestSubstitution, applySubstitution, defaultCompetitionRules, legalMatchContinuation } from './match-rules-v2';

const DT=.25;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function rng(state:MatchCoreState){state.seed=(Math.imul(state.seed,1664525)+1013904223)>>>0;return state.seed/4294967296;}
function norm(v:Vec2){const m=Math.hypot(v.x,v.y)||1;return{x:v.x/m,y:v.y/m}}
function add(a:Vec2,b:Vec2){return{x:a.x+b.x,y:a.y+b.y}}
function mul(a:Vec2,s:number){return{x:a.x*s,y:a.y*s}}
function player(club:Club,id:string){return club.players.find(p=>p.id===id)}
function nearestOpponent(state:MatchCoreState,p:LivePlayer){return opponentOf(state,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff).sort((a,b)=>distance(p.position,a.position)-distance(p.position,b.position))[0]}
function hasBall(state:MatchCoreState,p:LivePlayer){return state.ball.ownerId===p.playerId}
function targetShape(state:MatchCoreState,p:LivePlayer){const team=teamOf(state,p.clubId),withBall=state.possessionClubId===p.clubId,progress=withBall?6:-2,scoreDelta=team.score-opponentOf(state,p.clubId).score,late=state.seconds>70*60,gameAdj=late?(scoreDelta<0?5:scoreDelta>0?-4:0):0;const sign=team.attackingRight?1:-1;return{x:clamp(p.homeSlot.x+sign*(progress+gameAdj),1,state.pitch.length-1),y:p.homeSlot.y}}
function chooseIntent(state:MatchCoreState,club:Club,p:LivePlayer){const source=player(club,p.playerId);if(!source)return'holdShape' as LivePlayer['currentIntent'];if(hasBall(state,p)){const goal={x:teamOf(state,p.clubId).attackingRight?state.pitch.length:0,y:state.pitch.width/2},dg=distance(p.position,goal),opp=nearestOpponent(state,p),pressure=opp?distance(p.position,opp.position):99;if(dg<22&&source.attributes.finishing+source.attributes.decisions+rng(state)*35>115)return'shoot';const mates=teamOf(state,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff&&x.playerId!==p.playerId);const forward=mates.filter(x=>teamOf(state,p.clubId).attackingRight?x.position.x>p.position.x:x.position.x<p.position.x);if(forward.length&&source.attributes.passing+source.attributes.decisions+rng(state)*45>100)return'pass';if(pressure<4&&source.attributes.technique+rng(state)*35>75)return'carry';return'pass'}const ball=state.ball.position,d=distance(p.position,ball);if(state.possessionClubId&&state.possessionClubId!==p.clubId&&d<10)return'press';if(state.possessionClubId===p.clubId&&d<18)return'support';return'holdShape'}
function steering(state:MatchCoreState,p:LivePlayer,target:Vec2,maxSpeed:number){const desired=norm({x:target.x-p.position.x,y:target.y-p.position.y}),speed=maxSpeed*(1-p.fatigue*.004),sep=separation(state,p),vel=add(mul(desired,speed),sep);p.velocity={x:vel.x,y:vel.y};p.facing=Math.atan2(vel.y,vel.x);p.position.x=clamp(p.position.x+vel.x*DT,.5,state.pitch.length-.5);p.position.y=clamp(p.position.y+vel.y*DT,.5,state.pitch.width-.5);p.fatigue=clamp(p.fatigue+Math.hypot(vel.x,vel.y)*.0006*(p.currentIntent==='press'?1.5:1),0,100)}
function separation(state:MatchCoreState,p:LivePlayer){let x=0,y=0;for(const q of [...state.home.players,...state.away.players]){if(q.playerId===p.playerId||!q.onPitch||q.sentOff)continue;const d=distance(p.position,q.position);if(d>0&&d<1.25){x+=(p.position.x-q.position.x)/d*(1.25-d);y+=(p.position.y-q.position.y)/d*(1.25-d)}}return{x:x*1.8,y:y*1.8}}
function movePlayers(state:MatchCoreState,home:Club,away:Club){for(const p of [...state.home.players,...state.away.players]){if(!p.onPitch||p.sentOff)continue;const club=p.clubId===home.id?home:away,src=player(club,p.playerId);if(!src)continue;p.currentIntent=chooseIntent(state,club,p);let target=targetShape(state,p);if(p.currentIntent==='press')target={...state.ball.position};if(p.currentIntent==='support'){const sign=teamOf(state,p.clubId).attackingRight?1:-1;target={x:clamp(state.ball.position.x-sign*(5+rng(state)*8),1,state.pitch.length-1),y:clamp(state.ball.position.y+(rng(state)-.5)*14,1,state.pitch.width-1)}}if(p.currentIntent==='carry'){const sign=teamOf(state,p.clubId).attackingRight?1:-1;target={x:clamp(p.position.x+sign*8,1,state.pitch.length-1),y:p.position.y}}const maxSpeed=4.7+src.attributes.pace*.035;steering(state,p,target,maxSpeed)}}
function passTarget(state:MatchCoreState,club:Club,p:LivePlayer){const src=player(club,p.playerId)!;const team=teamOf(state,p.clubId),mates=team.players.filter(x=>x.onPitch&&!x.sentOff&&x.playerId!==p.playerId);const visible=new Set(visiblePlayers(state,p,src.attributes.decisions).filter(x=>x.clubId===p.clubId).map(x=>x.playerId));const scored=mates.map(m=>{const forward=team.attackingRight?m.position.x-p.position.x:p.position.x-m.position.x,control=territorialControlAt(state,m.position),safe=team===state.home?control.home:control.away,vision=visible.has(m.playerId)?18:-20,range=Math.max(0,30-distance(p.position,m.position));return{m,score:forward*.8+safe*30+vision+range+src.attributes.passing*.1+rng(state)*8}}).sort((a,b)=>b.score-a.score);return scored[0]?.m}
function executeBallAction(state:MatchCoreState,home:Club,away:Club,p:LivePlayer){if(!hasBall(state,p))return;const club=p.clubId===home.id?home:away,src=player(club,p.playerId);if(!src)return;if(p.currentIntent==='shoot'){shoot(state,club,p,src);return}if(p.currentIntent==='pass'){const t=passTarget(state,club,p);if(t)pass(state,club,p,t,src);return}if(p.currentIntent==='carry'){state.ball.position={...p.position};state.ball.velocity={...p.velocity}}}
function pass(state:MatchCoreState,club:Club,from:LivePlayer,to:LivePlayer,src:Player){const team=teamOf(state,club.id);team.attemptedPasses++;if(isOffsideAtPass(state,from,to,state.ball.position)){team.offsides++;state.ball.ownerId=undefined;state.possessionClubId=opponentOf(state,club.id).clubId;state.restart={type:'freeKick',clubId:state.possessionClubId,position:{...to.position},indirect:true};return}const d=distance(from.position,to.position),opp=nearestOpponent(state,to),pressure=opp?Math.max(0,8-distance(to.position,opp.position)):0,success=clamp(.45+src.attributes.passing*.004+src.attributes.decisions*.002-d*.006-pressure*.025,.08,.96);if(rng(state)<success){team.completedPasses++;team.passSuccess=team.completedPasses/Math.max(1,team.attemptedPasses)*100;state.ball.ownerId=to.playerId;state.ball.lastTouchId=from.playerId;state.ball.position={...to.position};state.possessionClubId=club.id;state.memory.recentPossessions.push(club.id);if(state.memory.recentPossessions.length>30)state.memory.recentPossessions.shift()}else{const def=opponentOf(state,club.id).players.filter(x=>x.onPitch&&!x.sentOff).sort((a,b)=>distance(a.position,to.position)-distance(b.position,to.position))[0];if(def){state.ball.ownerId=def.playerId;state.ball.position={...def.position};state.possessionClubId=def.clubId}}}
function shotXg(state:MatchCoreState,p:LivePlayer,src:Player){const team=teamOf(state,p.clubId),goal={x:team.attackingRight?state.pitch.length:0,y:state.pitch.width/2},d=distance(p.position,goal),angle=Math.atan2(state.pitch.goalWidth/2,Math.max(1,d))*2,defControl=territorialControlAt(state,p.position),pressure=team===state.home?defControl.away:defControl.home;return clamp(.015+(28-d)*.012+angle*.18+src.attributes.finishing*.0015-pressure*.12,.01,.75)}
function shot(state:MatchCoreState,club:Club,p:LivePlayer,src:Player){const team=teamOf(state,club.id),opp=opponentOf(state,club.id),xg=shotXg(state,p,src);team.shots++;team.xg+=xg;state.memory.recentShots.push({clubId:club.id,xg,second:state.seconds});if(state.memory.recentShots.length>20)state.memory.recentShots.shift();const onTarget=clamp(.28+src.attributes.finishing*.004+src.attributes.technique*.002-(1-xg)*.15,.18,.85);if(rng(state)<onTarget){team.shotsOnTarget++;const gk=opp.players.find(x=>x.onPitch&&!x.sentOff&&(x.role==='goalkeeper'||x.role==='sweeperKeeper')),gkp=gk?player(club.id===homeId(state)?({players:[]} as Club):({players:[]} as Club),gk.playerId):undefined;const goalChance=clamp(xg+(src.attributes.finishing-60)*.002-(gkp?.attributes.goalkeeping??65)*.0015,.02,.72);if(rng(state)<goalChance){team.score++;team.momentum=clamp(team.momentum+10,0,100);opp.momentum=clamp(opp.momentum-7,0,100);state.restart={type:'kickoff',clubId:opp.clubId,position:{x:state.pitch.length/2,y:state.pitch.width/2}};state.ball.ownerId=undefined;state.possessionClubId=opp.clubId;return}}state.ball.ownerId=undefined;state.possessionClubId=opp.clubId;const defender=opp.players.filter(x=>x.onPitch&&!x.sentOff).sort((a,b)=>distance(a.position,p.position)-distance(b.position,p.position))[0];if(defender){state.ball.ownerId=defender.playerId;state.ball.position={...defender.position}}}
function homeId(state:MatchCoreState){return state.home.clubId}
function resolveDuels(state:MatchCoreState,home:Club,away:Club){if(!state.ball.ownerId)return;const owner=livePlayer(state,state.ball.ownerId);if(!owner)return;const opp=nearestOpponent(state,owner);if(!opp||distance(owner.position,opp.position)>1.4)return;const tacklerClub=opp.clubId===home.id?home:away,victimClub=owner.clubId===home.id?home:away,tackler=player(tacklerClub,opp.playerId),victim=player(victimClub,owner.playerId);if(!tackler||!victim)return;const tackle=tackler.attributes.tackling+tackler.attributes.decisions*.35+rng(state)*30,protect=victim.attributes.technique+victim.attributes.pace*.2+rng(state)*28;if(tackle>protect){state.ball.ownerId=opp.playerId;state.ball.position={...opp.position};state.possessionClubId=opp.clubId;return}if(rng(state)<.08){const ref=refereeForMatch(state.seed),goalX=teamOf(state,owner.clubId).attackingRight?state.pitch.length:0,inside=Math.abs(owner.position.x-goalX)<=state.pitch.penaltyAreaDepth&&Math.abs(owner.position.y-state.pitch.width/2)<=state.pitch.penaltyAreaWidth/2,d=analyseFoul(state,ref,{tackler:opp,victim:owner,position:{...owner.position},fromBehind:rng(state)<.25,lastMan:rng(state)<.12,studsUp:rng(state)<.06,deniedGoalChance:rng(state)<.09,contact:55+rng(state)*40,ballContact:rng(state)*70,speed:Math.hypot(opp.velocity.x,opp.velocity.y),insidePenaltyArea:inside},()=>rng(state));applyRefereeDecision(state,d,opp.playerId,owner.playerId)}}
function updateBallFree(state:MatchCoreState){if(state.ball.ownerId){const p=livePlayer(state,state.ball.ownerId);if(p){state.ball.position={...p.position};state.ball.height=0;state.ball.velocity={...p.velocity}}return}state.ball.position.x+=state.ball.velocity.x*DT;state.ball.position.y+=state.ball.velocity.y*DT;state.ball.height=Math.max(0,state.ball.height+state.ball.verticalVelocity*DT);const drag=Math.pow(.985,DT*4),ground=state.ball.height<.05?Math.pow(.94,DT*4):1;state.ball.velocity.x*=drag*ground;state.ball.velocity.y*=drag*ground;state.ball.verticalVelocity-=9.81*DT;if(state.ball.height<=0&&state.ball.verticalVelocity<0){state.ball.height=0;state.ball.verticalVelocity*=-.42}if(state.ball.position.y<0||state.ball.position.y>state.pitch.width){const club=state.ball.lastTouchId?livePlayer(state,state.ball.lastTouchId)?.clubId:undefined,stateClub=club?opponentOf(state,club).clubId:state.home.clubId;state.restart={type:'throwIn',clubId:stateClub,position:{x:clamp(state.ball.position.x,0,state.pitch.length),y:clamp(state.ball.position.y,0,state.pitch.width)}};state.ball.velocity={x:0,y:0}}}
function processRestart(state:MatchCoreState){if(!state.restart)return;const team=teamOf(state,state.restart.clubId),player=team.players.filter(x=>x.onPitch&&!x.sentOff).sort((a,b)=>distance(a.position,state.restart!.position)-distance(b.position,state.restart!.position))[0];if(!player)return;state.ball.position={...state.restart.position};state.ball.ownerId=player.playerId;state.possessionClubId=team.clubId;state.restart=undefined}
function phase(state:MatchCoreState){if(state.seconds<45*60)state.phase='firstHalf';else if(state.seconds<46*60)state.phase='halftime';else if(state.seconds<91*60)state.phase='secondHalf';else state.phase='finished'}
export function stepMatch(state:MatchCoreState,home:Club,away:Club){if(state.phase==='finished')return state;if(state.phase==='preKickoff'){state.phase='firstHalf';const starter=rng(state)<.5?state.home:state.away,state.possessionClubId=starter.clubId;state.restart={type:'kickoff',clubId:starter.clubId,position:{x:state.pitch.length/2,y:state.pitch.width/2}}}processRestart(state);phase(state);if(state.phase==='halftime'){state.seconds+=DT;state.tick++;return state}movePlayers(state,home,away);for(const p of [...state.home.players,...state.away.players])executeBallAction(state,home,away,p);resolveDuels(state,home,away);updateBallFree(state);if(state.possessionClubId)teamOf(state,state.possessionClubId).possessionSeconds+=DT;for(const p of [...state.home.players,...state.away.players].filter(x=>x.onPitch&&!x.sentOff)){p.minutesPlayed+=DT/60}state.seconds+=DT;state.tick++;if(state.tick%240===0){for(const [club,team] of [[home,state.home],[away,state.away]] as const){const sub=suggestSubstitution(state,club,defaultCompetitionRules);if(sub)applySubstitution(state,club,sub)}if(!legalMatchContinuation(state))state.phase='finished'}return state}
export function simulateMatchCore(state:MatchCoreState,home:Club,away:Club,maxTicks=24000){for(let i=0;i<maxTicks&&state.phase!=='finished';i++)stepMatch(state,home,away);return state}
