import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, teamOf } from './match-core-v2';
import { applyShotResolution, resolveShotV2 } from './match-goalkeeper-resolution-v2';
export type AerialIntent='headToGoal'|'headClear'|'headPass'|'knockDown'|'challenge';
export type AerialDuelResult={winnerId:string;loserId?:string;intent:AerialIntent;quality:number;contact:number;target:Vec2;secondBall:boolean;foulRisk:number;reason:string;resolvedShot?:boolean;shotResult?:any};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const attr=(p:Player,key:string,fallback:number)=>Number((p.attributes as any)[key]??fallback);
function data(club:Club,id:string){return club.players.find(p=>p.id===id)}
function score(p:LivePlayer,src:Player,ballHeight:number,runup:number,rng:()=>number){const jumping=attr(src,'jumpingReach',attr(src,'jumping',60)),heading=attr(src,'heading',src.attributes.technique),strength=attr(src,'strength',60),balance=attr(src,'balance',60),bravery=attr(src,'bravery',60),anticipation=attr(src,'anticipation',src.attributes.decisions);return jumping*.24+heading*.21+strength*.15+balance*.09+bravery*.08+anticipation*.12+(100-p.fatigue)*.05+runup*1.8-Math.max(0,ballHeight-2.4)*6+rng()*16}
function intentFor(state:MatchCoreState,p:LivePlayer,src:Player,rng:()=>number):AerialIntent{const own=teamOf(state,p.clubId),goalX=own.attackingRight?state.pitch.length:0,dGoal=Math.abs(p.position.x-goalX),defendingThird=own.attackingRight?p.position.x<35:p.position.x>state.pitch.length-35;if(defendingThird)return'headClear';if(dGoal<18&&attr(src,'heading',src.attributes.technique)>55)return'headToGoal';if(attr(src,'vision',src.attributes.decisions)>68&&attr(src,'heading',src.attributes.technique)>62)return rng()<.55?'knockDown':'headPass';return'challenge'}
function targetFor(state:MatchCoreState,winner:LivePlayer,intent:AerialIntent,rng:()=>number){const own=teamOf(state,winner.clubId),dir=own.attackingRight?1:-1;if(intent==='headToGoal')return{x:own.attackingRight?state.pitch.length:0,y:state.pitch.width/2+(rng()-.5)*state.pitch.goalWidth*.7};if(intent==='headClear')return{x:clamp(winner.position.x-dir*32,1,state.pitch.length-1),y:clamp(winner.position.y+(rng()-.5)*22,1,state.pitch.width-1)};if(intent==='knockDown')return{x:clamp(winner.position.x+dir*4,1,state.pitch.length-1),y:clamp(winner.position.y+(rng()-.5)*8,1,state.pitch.width-1)};return{x:clamp(winner.position.x+dir*10,1,state.pitch.length-1),y:clamp(winner.position.y+(rng()-.5)*12,1,state.pitch.width-1)}}
export function resolveAerialDuel(state:MatchCoreState,home:Club,away:Club,candidates:LivePlayer[],rng=Math.random):AerialDuelResult|undefined{const active=candidates.filter(p=>p.onPitch&&!p.sentOff&&distance(p.position,state.ball.position)<3.2);if(active.length<1||state.ball.height<1.15)return;const scored=active.map(p=>{const club=p.clubId===home.id?home:away,src=data(club,p.playerId);if(!src)return undefined;const runup=Math.min(6,Math.hypot(p.velocity.x,p.velocity.y));return{p,src,score:score(p,src,state.ball.height,runup,rng)}}).filter(Boolean) as {p:LivePlayer;src:Player;score:number}[];if(!scored.length)return;scored.sort((a,b)=>b.score-a.score);const win=scored[0],lose=scored.find(x=>x.p.clubId!==win.p.clubId)??scored[1],intent=intentFor(state,win.p,win.src,rng),gap=win.score-(lose?.score??45),quality=clamp(45+gap*.75+attr(win.src,'heading',win.src.attributes.technique)*.3-win.p.fatigue*.12+rng()*12),contact=lose?clamp(35+Math.abs(gap)*.3+attr(win.src,'strength',60)*.15+attr(lose.src,'strength',60)*.1):15,target=targetFor(state,win.p,intent,rng),secondBall=intent==='knockDown'||intent==='challenge'||quality<58,foulRisk=lose?clamp((contact-55)*.7+(attr(win.src,'aggression',50)-50)*.25+(attr(lose.src,'bravery',50)-50)*.08,0,45):0;const result:AerialDuelResult={winnerId:win.p.playerId,loserId:lose?.p.playerId,intent,quality,contact,target,secondBall,foulRisk,reason:`duelo aéreo ${intent}: vantagem ${gap.toFixed(1)}, qualidade ${quality.toFixed(0)}, contato ${contact.toFixed(0)}`};if(intent==='headToGoal'){const atk=win.p.clubId===home.id?home:away,def=win.p.clubId===home.id?away:home,shot=resolveShotV2(state,atk,def,win.p,win.src,rng,'header');const heading=attr(win.src,'heading',win.src.attributes.technique),duelModifier=(quality-60)*.0025+(heading-60)*.0015;shot.xg=clamp(shot.xg+duelModifier,.025,.68);shot.postShotXg=shot.onTarget?clamp(shot.postShotXg+duelModifier*.8,.02,.9):0;applyShotResolution(state,atk,def,win.p,shot);result.resolvedShot=true;result.shotResult=shot;result.secondBall=shot.rebound;result.reason+=` → cabeceio ${shot.goal?'gol':shot.rebound?'defendido com rebote':shot.onTarget?'defendido':'fora'}`}
 const any=state as any;if(!any.__aerialDuels)any.__aerialDuels=[];any.__aerialDuels.push({...result,second:state.seconds});if(any.__aerialDuels.length>240)any.__aerialDuels.splice(0,any.__aerialDuels.length-240);return result}
export function applyAerialResult(state:MatchCoreState,r:AerialDuelResult){if(r.resolvedShot)return;const winner=[...state.home.players,...state.away.players].find(p=>p.playerId===r.winnerId);if(!winner)return;state.ball.ownerId=undefined;state.ball.lastTouchId=winner.playerId;state.possessionClubId=r.secondBall?undefined:winner.clubId;const dx=r.target.x-winner.position.x,dy=r.target.y-winner.position.y,m=Math.hypot(dx,dy)||1,speed=r.intent==='headClear'?17:r.intent==='headToGoal'?15:r.intent==='headPass'?12:8;state.ball.position={...winner.position};state.ball.velocity={x:dx/m*speed,y:dy/m*speed};state.ball.height=r.intent==='knockDown'?0.7:1.2;state.ball.verticalVelocity=r.intent==='headClear'?3.5:r.intent==='headToGoal'?1.2:1.8;state.ball.spin=0}
export function aerialDuelLog(state:MatchCoreState){return[...(((state as any).__aerialDuels??[]) as any[])]}
