import type { MatchCoreState } from './match-core-v2';
import { teamOf } from './match-core-v2';
import type { CompetitionMatchRules } from './match-rules-v2';
import { recordPhysicalGoal } from './match-event-ledger-v2';

export type GoalLineEvent={second:number;goalX:number;scoringClubId:string;concedingClubId:string;lastTouchId?:string;crossingY:number;crossingHeight:number;fullBallCrossed:boolean;goalLineTechnology:boolean;netImpact:number;ownGoalPossible:boolean};
type OwnGoalCandidate={playerId:string;clubId:string;createdSecond:number;expiresSecond:number};
function logStore(s:MatchCoreState){const a=s as any;if(!a.__goalLineEvents)a.__goalLineEvents=[] as GoalLineEvent[];return a.__goalLineEvents as GoalLineEvent[]}
function previous(s:MatchCoreState){return (s as any).__lastBallPhysicsPosition as {x:number;y:number;height:number}|undefined}
function scoringAtGoal(s:MatchCoreState,goalX:number){if(goalX===0)return s.home.attackingRight?s.away:s.home;return s.home.attackingRight?s.home:s.away}
function ownGoalCandidate(s:MatchCoreState){const any=s as any,c=any.__ownGoalCandidate as OwnGoalCandidate|undefined;if(c&&s.seconds>c.expiresSecond){delete any.__ownGoalCandidate;return undefined}return c}
export function markOwnGoalCandidate(s:MatchCoreState,input:{playerId:string;clubId:string;ttlSeconds?:number}){const ttl=Math.max(.25,Math.min(4,input.ttlSeconds??1.5));(s as any).__ownGoalCandidate={playerId:input.playerId,clubId:input.clubId,createdSecond:s.seconds,expiresSecond:s.seconds+ttl} satisfies OwnGoalCandidate}
export function clearOwnGoalCandidate(s:MatchCoreState){delete (s as any).__ownGoalCandidate}
export function detectPhysicalGoal(s:MatchCoreState,rules:CompetitionMatchRules){if(s.ball.ownerId||s.restart)return;const prev=previous(s);if(!prev)return;const r=s.pitch.ballRadius,goalXs=[0,s.pitch.length];for(const goalX of goalXs){const crossed=goalX===0?prev.x>=-r&&s.ball.position.x<-r:prev.x<=goalX+r&&s.ball.position.x>goalX+r;if(!crossed)continue;const denom=s.ball.position.x-prev.x,alpha=Math.abs(denom)>.00001?Math.max(0,Math.min(1,(goalX-prev.x)/denom)):1,y=prev.y+(s.ball.position.y-prev.y)*alpha,h=prev.height+(s.ball.height-prev.height)*alpha,centre=s.pitch.width/2,half=s.pitch.goalWidth/2,inside=y-r>centre-half&&y+r<centre+half&&h+r<s.pitch.goalHeight;if(!inside)return;const scoring=scoringAtGoal(s,goalX),conceding=scoring.clubId===s.home.clubId?s.away:s.home,last=s.ball.lastTouchId,lastBelongsToConceding=Boolean(last&&teamOf(s,conceding.clubId).players.some(p=>p.playerId===last)),candidate=ownGoalCandidate(s),ownGoalPossible=Boolean(lastBelongsToConceding&&candidate&&candidate.playerId===last&&candidate.clubId===conceding.clubId);const speed=Math.hypot(s.ball.velocity.x,s.ball.velocity.y),netImpact=Math.min(100,Math.round(speed*2.8+Math.abs(s.ball.verticalVelocity)*3.5)),event:GoalLineEvent={second:s.seconds,goalX,scoringClubId:scoring.clubId,concedingClubId:conceding.clubId,lastTouchId:last,crossingY:y,crossingHeight:h,fullBallCrossed:true,goalLineTechnology:rules.goalLineTechnology,netImpact,ownGoalPossible};logStore(s).push(event);if(!ownGoalPossible)return;clearOwnGoalCandidate(s);recordPhysicalGoal(s,{scoringClubId:scoring.clubId,concedingClubId:conceding.clubId,lastTouchId:last,ownGoal:true,detail:`gol contra confirmado por desvio defensivo: bola cruzou integralmente a linha a ${h.toFixed(2)} m de altura`});scoring.score++;scoring.momentum=Math.min(100,scoring.momentum+10);conceding.momentum=Math.max(0,conceding.momentum-7);s.ball.ownerId=undefined;s.ball.velocity={x:0,y:0};s.ball.verticalVelocity=0;s.ball.height=0;s.ball.position={x:s.pitch.length/2,y:s.pitch.width/2};s.possessionClubId=conceding.clubId;s.restart={type:'kickoff',clubId:conceding.clubId,position:{x:s.pitch.length/2,y:s.pitch.width/2}};return event}return undefined}
export function goalLineEvents(s:MatchCoreState){return[...logStore(s)]}
