import type { Club } from './engine';
import type { MatchCoreState } from './match-core-v2';
import { matchEventLedger } from './match-event-ledger-v2';
import { lifecycleEvents } from './match-lifecycle-v2';
import { playerMatchPerformances, playerOfTheMatch } from './match-player-performance-v2';
import { goalLineEvents } from './match-goal-line-v2';
import { officiatingLog } from './match-officiating-v2';

export type MatchReportTimelineItem={second:number;minute:string;type:string;clubId?:string;playerId?:string;text:string;importance:number};
export type MatchReport={score:{home:number;away:number};summary:string;timeline:MatchReportTimelineItem[];playerOfTheMatch:any;topPerformers:any[];turningPoints:string[];discipline:{varReviews:number;redCards:number;yellowCards:number};records:{hatTricks:string[];cleanSheets:string[];ownGoals:string[]};};
const minute=(s:number)=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
export function buildMatchReport(state:MatchCoreState,home:Club,away:Club):MatchReport{const ledger=matchEventLedger(state),life=lifecycleEvents(state),refs=officiatingLog(state),ratings=playerMatchPerformances(state,home,away),timeline:MatchReportTimelineItem[]=[];for(const e of life)timeline.push({second:e.second,minute:minute(e.second),type:e.type,clubId:e.clubId,text:e.text,importance:e.type==='fulltimeWhistle'||e.type==='kickoff'?3:1});for(const e of ledger){let text=e.detail??e.type;if(e.type==='goal')text=`Gol de ${e.playerId}${e.secondaryPlayerId?`, assistência de ${e.secondaryPlayerId}`:''}`;if(e.type==='physicalGoal')text=`Gol confirmado pela trajetória física da bola${e.playerId?` (${e.playerId})`:''}`;if(e.type==='ownGoal')text=`Gol contra de ${e.playerId}`;if(e.type==='frameHit')text=`${e.playerId} acertou ${e.detail==='crossbar'?'o travessão':'a trave'}`;if(e.type==='keeperError')text=`Erro do goleiro ${e.playerId}`;if(e.type==='errorLeadingToGoal')text=`Erro de ${e.playerId} originou gol adversário`;if(e.type==='hatTrick')text=`Hat-trick de ${e.playerId}`;timeline.push({second:e.second,minute:minute(e.second),type:e.type,clubId:e.clubId,playerId:e.playerId,text,importance:['goal','physicalGoal','ownGoal','hatTrick','errorLeadingToGoal'].includes(e.type)?5:['frameHit','keeperError','assist'].includes(e.type)?3:1})}timeline.sort((a,b)=>a.second-b.second||b.importance-a.importance);const turningPoints=timeline.filter(x=>x.importance>=4).slice(-8).map(x=>`${x.minute} ${x.text}`),motm=playerOfTheMatch(state,home,away),hatTricks=ledger.filter(e=>e.type==='hatTrick'&&e.playerId).map(e=>e.playerId!),cleanSheets=ledger.filter(e=>e.type==='cleanSheet'&&e.playerId).map(e=>e.playerId!),ownGoals=ledger.filter(e=>e.type==='ownGoal'&&e.playerId).map(e=>e.playerId!),varReviews=refs.filter((x:any)=>x.var?.reviewed).length,redCards=state.home.redCards+state.away.redCards,yellowCards=state.home.yellowCards+state.away.yellowCards,physical=goalLineEvents(state).length,summary=`${home.name} ${state.home.score}–${state.away.score} ${away.name}. ${state.home.shots+state.away.shots} finalizações, ${(state.home.xg+state.away.xg).toFixed(2)} xG total${physical?`, ${physical} gol(ns) confirmado(s) pela linha física`:''}.`;return{score:{home:state.home.score,away:state.away.score},summary,timeline,playerOfTheMatch:motm,topPerformers:ratings.slice(0,5),turningPoints,discipline:{varReviews,redCards,yellowCards},records:{hatTricks,cleanSheets,ownGoals}}}
