import type { Club, Player } from './engine';
import type { MatchCoreState } from './match-core-v2';
import { teamOf } from './match-core-v2';
import { defaultCompetitionRules, type CompetitionMatchRules } from './match-rules-v2';

export type KnockoutContext={requiresWinner:boolean;aggregateHome?:number;aggregateAway?:number;rules?:CompetitionMatchRules};
export type StoppageState={firstHalf:number;secondHalf:number;extraTime1:number;extraTime2:number;calculated:boolean};
export type ShootoutKick={clubId:string;playerId:string;scored:boolean;round:number;suddenDeath:boolean};
export type ShootoutState={home:number;away:number;homeTaken:number;awayTaken:number;nextClubId:string;kicks:ShootoutKick[];winnerClubId?:string};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function rng(s:MatchCoreState){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function attr(p:Player|undefined,k:string,f:number){return Number((p?.attributes as any)?.[k]??f)}
function calcAdded(s:MatchCoreState,from:number,to:number){const refs=(((s as any).__refereeLog??[]) as any[]).filter(x=>x.second>=from&&x.second<to),officiating=(((s as any).__officiatingLog??[]) as any[]).filter(x=>x.second>=from&&x.second<to),inj=(((s as any).__matchInjuries??[]) as any[]).filter(x=>x.second>=from&&x.second<to),subs=s.home.substitutionsUsed+s.away.substitutionsUsed,goals=s.memory.recentShots.filter(x=>x.second>=from&&x.second<to&&x.xg>.4).length,loggedVar=officiating.filter(x=>x.var?.reviewed).reduce((a,x)=>a+Number(x.var?.delaySeconds??0),0),globalVar=Number((s as any).__varDelaySeconds??0),varDelay=Math.max(loggedVar,globalVar),sec=35+refs.length*5+inj.length*22+subs*12+goals*18+varDelay;return clamp(Math.round(sec/30)*30,60,900)}
export function stoppageState(s:MatchCoreState):StoppageState{const any=s as any;if(!any.__stoppage)any.__stoppage={firstHalf:0,secondHalf:0,extraTime1:0,extraTime2:0,calculated:false};const st=any.__stoppage as StoppageState;if(!st.firstHalf&&s.seconds>=2400)st.firstHalf=calcAdded(s,0,2700);if(!st.secondHalf&&s.seconds>=5100)st.secondHalf=calcAdded(s,2760,5460);return st}
function knockoutTied(s:MatchCoreState,k?:KnockoutContext){if(!k?.requiresWinner)return false;const ah=s.home.score+(k.aggregateHome??0),aa=s.away.score+(k.aggregateAway??0);return ah===aa}
export function competitionPhaseUpdate(s:MatchCoreState,k:KnockoutContext={requiresWinner:false,rules:defaultCompetitionRules}){const rules=k.rules??defaultCompetitionRules,st=stoppageState(s),fhEnd=2700+st.firstHalf,shStart=fhEnd+60,shEnd=shStart+2700+st.secondHalf;if(s.phase==='preKickoff')return s.phase;if(s.phase==='firstHalf'&&s.seconds>=fhEnd){s.phase='halftime';return s.phase}if(s.phase==='halftime'&&s.seconds>=shStart){s.phase='secondHalf';return s.phase}if(s.phase==='secondHalf'&&s.seconds>=shEnd){if(knockoutTied(s,k)&&rules.extraTime){s.phase='extraTime1';const any=s as any;any.__extraTimeStart=s.seconds;return s.phase}s.phase='finished';return s.phase}const any=s as any,etStart=Number(any.__extraTimeStart??shEnd);if(s.phase==='extraTime1'){if(!st.extraTime1&&s.seconds>=etStart+720)st.extraTime1=calcAdded(s,etStart,etStart+900);if(s.seconds>=etStart+900+st.extraTime1){s.phase='extraTimeBreak';any.__extraBreakStart=s.seconds;return s.phase}}if(s.phase==='extraTimeBreak'&&s.seconds>=Number(any.__extraBreakStart??s.seconds)+60){s.phase='extraTime2';any.__extraTime2Start=s.seconds;return s.phase}if(s.phase==='extraTime2'){const start=Number(any.__extraTime2Start??s.seconds);if(!st.extraTime2&&s.seconds>=start+720)st.extraTime2=calcAdded(s,start,start+900);if(s.seconds>=start+900+st.extraTime2){if(knockoutTied(s,k)){s.phase='penalties';ensureShootout(s)}else s.phase='finished';return s.phase}}return s.phase}
function rankedTakers(c:Club,s:MatchCoreState){const live=new Set(teamOf(s,c.id).players.filter(x=>x.onPitch&&!x.sentOff).map(x=>x.playerId));return c.players.filter(p=>live.has(p.id)).sort((a,b)=>penaltyScore(b)-penaltyScore(a));function penaltyScore(p:Player){return p.attributes.finishing*.38+p.attributes.technique*.22+attr(p,'composure',p.attributes.decisions)*.25+p.attributes.decisions*.15}}
function ensureShootout(s:MatchCoreState){const any=s as any;if(!any.__shootout)any.__shootout={home:0,away:0,homeTaken:0,awayTaken:0,nextClubId:s.home.clubId,kicks:[]} as ShootoutState;return any.__shootout as ShootoutState}
function shootoutCanEnd(x:ShootoutState){const hr=5-x.homeTaken,ar=5-x.awayTaken;if(x.homeTaken<=5&&x.awayTaken<=5){if(x.home>x.away+ar)return true;if(x.away>x.home+hr)return true}return x.homeTaken>=5&&x.awayTaken>=5&&x.homeTaken===x.awayTaken&&x.home!==x.away}
export function stepShootout(s:MatchCoreState,home:Club,away:Club){if(s.phase!=='penalties')return;const x=ensureShootout(s);if(x.winnerClubId){s.phase='finished';return x}const club=x.nextClubId===home.id?home:away,def=club.id===home.id?away:home,takers=rankedTakers(club,s);if(!takers.length){x.winnerClubId=def.id;s.phase='finished';return x}const taken=club.id===home.id?x.homeTaken:x.awayTaken,taker=takers[taken%takers.length],gkLive=teamOf(s,def.id).players.find(p=>p.onPitch&&!p.sentOff&&(p.role==='goalkeeper'||p.role==='sweeperKeeper')),gk=gkLive?def.players.find(p=>p.id===gkLive.playerId):undefined,finish=taker.attributes.finishing*.38+taker.attributes.technique*.24+attr(taker,'composure',taker.attributes.decisions)*.28,keeper=(gk?.attributes.goalkeeping??60)*.5+attr(gk,'reflexes',gk?.attributes.goalkeeping??60)*.25+attr(gk,'oneOnOnes',gk?.attributes.goalkeeping??60)*.15,missChance=clamp(.13-(finish-60)*.0012,.035,.18),saveChance=clamp(.17+(keeper-finish)*.0025,.08,.34),roll=rng(s),scored=roll>missChance+saveChance,round=Math.max(x.homeTaken,x.awayTaken)+1,suddenDeath=x.homeTaken>=5&&x.awayTaken>=5;x.kicks.push({clubId:club.id,playerId:taker.id,scored,round,suddenDeath});if(club.id===home.id){x.homeTaken++;if(scored)x.home++}else{x.awayTaken++;if(scored)x.away++}x.nextClubId=club.id===home.id?away.id:home.id;if(shootoutCanEnd(x)){x.winnerClubId=x.home>x.away?home.id:away.id;s.phase='finished'}return x}
export function shootoutState(s:MatchCoreState):ShootoutState|undefined{return (s as any).__shootout}
