import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, teamOf } from './match-core-v2';
import { attackingPatternTask, type AttackingPattern } from './match-attacking-patterns-v2';

export type ChainAction='move'|'receive'|'pass'|'returnPass'|'decoy'|'runBeyond'|'hold';
export type ChainStep={index:number;actorId:string;action:ChainAction;target?:Vec2;targetPlayerId?:string;earliest:number;latest:number;completed:boolean;failed:boolean;reason:string};
export type MatchActionChain={id:string;clubId:string;pattern:AttackingPattern;createdAt:number;expiresAt:number;participants:string[];steps:ChainStep[];current:number;status:'active'|'completed'|'aborted';score:number;abortReason?:string};
export type ChainInstruction={chainId:string;pattern:AttackingPattern;step:number;action:ChainAction;target?:Vec2;targetPlayerId?:string;priority:number;reason:string};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const stateKey=(clubId:string)=>`__actionChains_${clubId}`;
function chains(state:MatchCoreState,clubId:string):MatchActionChain[]{const a=state as any;if(!a[stateKey(clubId)])a[stateKey(clubId)]=[];return a[stateKey(clubId)] as MatchActionChain[]}
function pdata(club:Club,id:string){return club.players.find(p=>p.id===id)}
function cognitive(p:Player|undefined){return p?p.attributes.decisions*.4+p.attributes.technique*.22+p.attributes.passing*.18+p.attributes.positioning*.2:45}
function live(state:MatchCoreState,clubId:string,id:string){return teamOf(state,clubId).players.find(p=>p.playerId===id&&p.onPitch&&!p.sentOff)}
function owner(state:MatchCoreState){return state.ball.ownerId}
function idFor(state:MatchCoreState,clubId:string,pattern:string){return `${clubId}-${pattern}-${Math.floor(state.seconds*4)}-${Math.abs(state.seed%10000)}`}
function sequenceFromPattern(state:MatchCoreState,club:Club,actor:LivePlayer):MatchActionChain|undefined{const task=attackingPatternTask(state,club,actor.playerId);if(!task)return;const team=teamOf(state,club.id),participants=[actor.playerId,...task.partnerIds].filter((v,i,a)=>a.indexOf(v)===i),created=state.seconds,steps:ChainStep[]=[];const add=(actorId:string,action:ChainAction,delay:number,window:number,target?:Vec2,targetPlayerId?:string,reason='')=>steps.push({index:steps.length,actorId,action,target,targetPlayerId,earliest:created+delay,latest:created+delay+window,completed:false,failed:false,reason});
 if(task.pattern==='oneTwo'&&task.partnerIds.length){const partner=task.partnerIds[0];add(actor.playerId,'move',0,1.8,task.target,undefined,'aproximar para a tabela');add(actor.playerId,'pass',.35,2.1,undefined,partner,'primeiro passe da tabela');add(actor.playerId,'runBeyond',.7,3.2,{x:task.target.x+(team.attackingRight?8:-8),y:task.target.y},undefined,'continuar a corrida após soltar a bola');add(partner,'returnPass',1.1,3.6,undefined,actor.playerId,'devolver no espaço ao corredor');}
 else if(task.pattern==='thirdMan'&&task.partnerIds.length>=2){const a=task.partnerIds[0],b=task.partnerIds[1];add(a,'receive',0,2.2,undefined,undefined,'apoio recebe para fixar marcador');add(a,'pass',.45,2.7,undefined,b,'circulação curta para ativar terceiro homem');add(actor.playerId,'runBeyond',.25,3.5,task.target,undefined,'terceiro homem inicia corrida fora do foco da bola');add(b,'pass',1.0,4.2,task.target,actor.playerId,'achar o terceiro homem em progressão');}
 else if(task.pattern==='falseNineDrop'){add(actor.playerId,'move',0,2.5,task.target,undefined,'recuar entrelinhas');add(actor.playerId,'receive',.4,3.2,task.target,undefined,'oferecer apoio frontal');const runner=team.players.filter(p=>p.playerId!==actor.playerId&&p.onPitch).sort((a,b)=>distance(a.position,task.target)-distance(b.position,task.target))[0];if(runner){participants.push(runner.playerId);add(runner.playerId,'runBeyond',.5,3.8,{x:runner.position.x+(team.attackingRight?12:-12),y:runner.position.y},undefined,'atacar profundidade liberada pelo falso 9');add(actor.playerId,'pass',1.0,4.2,undefined,runner.playerId,'servir o corredor após atrair defensor')}}
 else if(task.pattern==='overlap'||task.pattern==='underlap'){const partner=task.partnerIds[0];add(actor.playerId,'runBeyond',0,3.2,task.target,undefined,`${task.pattern}: corrida coordenada`);if(partner)add(partner,'hold',0,1.5,undefined,undefined,'segurar a bola para sincronizar a corrida');if(partner)add(partner,'pass',.8,3.8,task.target,actor.playerId,'soltar a bola no tempo da ultrapassagem');}
 else if(task.pattern==='attackBrokenLine'){add(actor.playerId,'runBeyond',0,2.8,task.target,undefined,'atacar imediatamente defensor que quebra a linha');const passer=team.players.filter(p=>p.playerId!==actor.playerId&&p.onPitch).sort((a,b)=>distance(a.position,state.ball.position)-distance(b.position,state.ball.position))[0];if(passer){participants.push(passer.playerId);add(passer.playerId,'pass',.25,2.8,task.target,actor.playerId,'explorar rapidamente a linha legalizada')}}
 else {add(actor.playerId,task.pattern==='decoyRun'?'decoy':'move',0,3,task.target,undefined,task.reason)}
 if(!steps.length)return;const score=clamp(task.priority+participants.reduce((n,id)=>n+cognitive(pdata(club,id)),0)/Math.max(1,participants.length)*.18);return{id:idFor(state,club.id,task.pattern),clubId:club.id,pattern:task.pattern,createdAt:created,expiresAt:created+5.5,participants:[...new Set(participants)],steps,current:0,status:'active',score}}
function progress(state:MatchCoreState,chain:MatchActionChain){if(chain.status!=='active')return;if(state.seconds>chain.expiresAt){chain.status='aborted';chain.abortReason='sequência perdeu o timing';return}const step=chain.steps[chain.current];if(!step){chain.status='completed';return}if(state.seconds>step.latest){step.failed=true;chain.status='aborted';chain.abortReason=`timing falhou em ${step.action}`;return}if(state.seconds<step.earliest)return;const p=live(state,chain.clubId,step.actorId);if(!p){step.failed=true;chain.status='aborted';chain.abortReason='participante indisponível';return}let done=false;if(step.action==='move'||step.action==='runBeyond'||step.action==='decoy')done=!!step.target&&distance(p.position,step.target)<2.4;else if(step.action==='receive')done=owner(state)===step.actorId;else if(step.action==='pass'||step.action==='returnPass')done=owner(state)!==step.actorId&&state.ball.lastTouchId===step.actorId;else if(step.action==='hold')done=owner(state)===step.actorId&&state.seconds-step.earliest>.45;if(done){step.completed=true;chain.current++;if(chain.current>=chain.steps.length)chain.status='completed'}}
export function updateActionChains(state:MatchCoreState,club:Club){const list=chains(state,club.id);for(const c of list)progress(state,c);const active=list.filter(c=>c.status==='active');if(active.length<2&&state.possessionClubId===club.id){const carrierId=owner(state),candidate=teamOf(state,club.id).players.filter(p=>p.onPitch&&!p.sentOff&&p.playerId!==carrierId).map(p=>({p,t:attackingPatternTask(state,club,p.playerId)})).filter(x=>x.t).sort((a,b)=>(b.t?.priority??0)-(a.t?.priority??0))[0];if(candidate&&candidate.t&&!active.some(c=>c.participants.includes(candidate.p.playerId))){const created=sequenceFromPattern(state,club,candidate.p);if(created)list.push(created)}}if(list.length>18)list.splice(0,list.length-18);return list}
export function actionChainInstruction(state:MatchCoreState,club:Club,playerId:string):ChainInstruction|undefined{const list=updateActionChains(state,club).filter(c=>c.status==='active'&&c.participants.includes(playerId)).sort((a,b)=>b.score-a.score);for(const c of list){const step=c.steps[c.current];if(!step||step.actorId!==playerId||state.seconds<step.earliest||state.seconds>step.latest)continue;return{chainId:c.id,pattern:c.pattern,step:step.index,action:step.action,target:step.target,targetPlayerId:step.targetPlayerId,priority:clamp(c.score+(step.action==='pass'||step.action==='returnPass'?10:0)),reason:`sequência ${c.pattern}: ${step.reason}`}}}
export function actionChainLog(state:MatchCoreState,clubId:string){return chains(state,clubId).map(c=>({id:c.id,pattern:c.pattern,status:c.status,current:c.current,steps:c.steps.length,score:c.score,abortReason:c.abortReason}))}
