import type { Club } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf, territorialControlAt } from './match-core-v2';
import { goalkeeperDecision } from './match-goalkeeper-ai-v2';

const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function attackSign(state:MatchCoreState,p:LivePlayer){return teamOf(state,p.clubId).attackingRight?1:-1}
function nearestMate(state:MatchCoreState,p:LivePlayer){return teamOf(state,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff&&x.playerId!==p.playerId).sort((a,b)=>distance(a.position,p.position)-distance(b.position,p.position))[0]}
function nearestOpponent(state:MatchCoreState,p:LivePlayer){return opponentOf(state,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff).sort((a,b)=>distance(a.position,p.position)-distance(b.position,p.position))[0]}
function laneY(state:MatchCoreState,p:LivePlayer,wide:number){const mid=state.pitch.width/2;return clamp(mid+(p.homeSlot.y-mid)*wide,2,state.pitch.width-2)}
function base(state:MatchCoreState,p:LivePlayer):Vec2{const t=teamOf(state,p.clubId),s=attackSign(state,p),withBall=state.possessionClubId===p.clubId,advance=withBall?5:-2,score=t.score-opponentOf(state,p.clubId).score,late=state.seconds>68*60,game=late?(score<0?5:score>0?-4:0):0;return{x:clamp(p.homeSlot.x+s*(advance+game),1,state.pitch.length-1),y:p.homeSlot.y}}
function insideChannel(state:MatchCoreState,p:LivePlayer,depth:number){const s=attackSign(state,p),mid=state.pitch.width/2;return{x:clamp(p.homeSlot.x+s*depth,2,state.pitch.length-2),y:mid+(p.homeSlot.y-mid)*.42}}
function wideChannel(state:MatchCoreState,p:LivePlayer,depth:number){const s=attackSign(state,p);return{x:clamp(p.homeSlot.x+s*depth,2,state.pitch.length-2),y:laneY(state,p,1.12)}}
function halfSpace(state:MatchCoreState,p:LivePlayer,depth:number){const s=attackSign(state,p),mid=state.pitch.width/2;return{x:clamp(p.homeSlot.x+s*depth,2,state.pitch.length-2),y:mid+(p.homeSlot.y-mid)*.62}}
function falseNine(state:MatchCoreState,p:LivePlayer){const s=attackSign(state,p);return{x:clamp(p.homeSlot.x-s*12,2,state.pitch.length-2),y:state.pitch.width/2}}
function shadowRun(state:MatchCoreState,p:LivePlayer){const s=attackSign(state,p),ball=state.ball.position;return{x:clamp(Math.max(p.homeSlot.x,ball.x+s*9),2,state.pitch.length-2),y:clamp(state.pitch.width/2+(p.homeSlot.y-state.pitch.width/2)*.35,3,state.pitch.width-3)}}
function cover(state:MatchCoreState,p:LivePlayer){const s=attackSign(state,p),ball=state.ball.position;return{x:clamp(ball.x-s*9,2,state.pitch.length-2),y:clamp((ball.y+p.homeSlot.y)/2,3,state.pitch.width-3)}}
export function roleMovementTarget(state:MatchCoreState,club:Club,p:LivePlayer):Vec2{if(p.role==='goalkeeper'||p.role==='sweeperKeeper')return goalkeeperDecision(state,club,p).target;const withBall=state.possessionClubId===p.clubId,oppHas=state.possessionClubId&&state.possessionClubId!==p.clubId;if(oppHas){if(['ballWinningMidfielder','stopper'].includes(p.role)&&distance(p.position,state.ball.position)<14)return{...state.ball.position};if(['anchor','centralDefender','ballPlayingDefender'].includes(p.role))return cover(state,p);if(p.role==='winger'||p.role==='insideForward')return base(state,p);return base(state,p)}if(!withBall)return base(state,p);switch(p.role){case'wingback':return wideChannel(state,p,12);case'fullback':return wideChannel(state,p,6);case'invertedFullback':return insideChannel(state,p,6);case'ballPlayingDefender':return insideChannel(state,p,3);case'stopper':return base(state,p);case'anchor':return{x:base(state,p).x,y:state.pitch.width/2};case'deepLyingPlaymaker':return insideChannel(state,p,2);case'ballWinningMidfielder':return cover(state,p);case'boxToBox':return halfSpace(state,p,11);case'advancedPlaymaker':return halfSpace(state,p,9);case'attackingMidfielder':return halfSpace(state,p,11);case'shadowStriker':return shadowRun(state,p);case'winger':return wideChannel(state,p,12);case'insideForward':return insideChannel(state,p,14);case'widePlaymaker':return halfSpace(state,p,6);case'advancedForward':return halfSpace(state,p,16);case'targetForward':return{x:clamp(p.homeSlot.x+attackSign(state,p)*7,2,state.pitch.length-2),y:state.pitch.width/2};case'falseNine':return falseNine(state,p);default:return base(state,p)}}
export function roleRunValue(state:MatchCoreState,p:LivePlayer,target:Vec2){const control=territorialControlAt(state,target),friendly=p.clubId===state.home.clubId?control.home:control.away,opp=nearestOpponent(state,p),space=opp?Math.min(1,distance(opp.position,target)/12):1,forward=attackSign(state,p)*(target.x-p.position.x);return forward*.4+space*8+friendly*5}
export function shouldPressByRole(state:MatchCoreState,p:LivePlayer,pressing:number){if(!state.possessionClubId||state.possessionClubId===p.clubId)return false;const d=distance(p.position,state.ball.position),roleBias=['ballWinningMidfielder','stopper','boxToBox','wingback'].includes(p.role)?8:['anchor','centralDefender','ballPlayingDefender'].includes(p.role)?-5:0;return d<clamp(6+pressing*.09+roleBias,5,20)}
export function supportAngleTarget(state:MatchCoreState,p:LivePlayer):Vec2{const s=attackSign(state,p),ball=state.ball.position,mate=nearestMate(state,p),side=mate&&mate.position.y<ball.y?1:-1;return{x:clamp(ball.x-s*6,2,state.pitch.length-2),y:clamp(ball.y+side*8,2,state.pitch.width-2)}}
