import type { MatchStory, MatchStoryAction } from './matchday-story-v1';

const reduceMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
const timers=new WeakMap<HTMLElement,number[]>();
const clamp=(n:number,min=4,max=96)=>Math.max(min,Math.min(max,n));

function clear(center:HTMLElement){for(const t of timers.get(center)??[])window.clearTimeout(t);timers.set(center,[]);center.querySelectorAll('.md-sequence-label,.md-sequence-path,.md-sequence-duel').forEach(n=>n.remove())}
function remember(center:HTMLElement,id:number){const list=timers.get(center)??[];list.push(id);timers.set(center,list)}
function playerEl(center:HTMLElement,id?:string){return id?center.querySelector<HTMLElement>(`[data-live-player="${CSS.escape(id)}"]`):null}
function movePlayer(el:HTMLElement|undefined|null,to:{x:number;y:number},duration:number){if(!el||reduceMotion)return;el.animate([{left:el.style.left,top:el.style.top},{left:`${to.x}%`,top:`${to.y}%`}],{duration,easing:'cubic-bezier(.2,.72,.2,1)',fill:'none'})}
function drawPath(pitch:HTMLElement,a:MatchStoryAction,duration:number){const dx=a.to.x-a.from.x,dy=a.to.y-a.from.y,dist=Math.hypot(dx,dy);if(dist<1)return;const line=document.createElement('i');line.className=`md-sequence-path ${a.type}`;line.style.left=`${a.from.x}%`;line.style.top=`${a.from.y}%`;line.style.width=`${dist}%`;line.style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;line.style.setProperty('--md-seq-duration',`${duration}ms`);pitch.appendChild(line);window.setTimeout(()=>line.remove(),duration+180)}
function label(pitch:HTMLElement,a:MatchStoryAction){const el=document.createElement('span');el.className=`md-sequence-label ${a.type}`;el.style.left=`${a.to.x}%`;el.style.top=`${a.to.y}%`;el.textContent=a.label;pitch.appendChild(el);window.setTimeout(()=>el.remove(),900)}
function sideOf(el:HTMLElement|null){return el?.classList.contains('home')?'home':el?.classList.contains('away')?'away':undefined}
function collectiveShift(center:HTMLElement,a:MatchStoryAction,duration:number){if(reduceMotion)return;const actor=playerEl(center,a.playerId),actorSide=sideOf(actor);if(!actorSide)return;const attacking=![ 'recover','intercept','tackle','loose','foul','save','restart'].includes(a.type);const homeForward=actorSide==='home'?1:-1;const midpoint={x:(a.from.x+a.to.x)/2,y:(a.from.y+a.to.y)/2};const all=[...center.querySelectorAll<HTMLElement>('[data-live-player]')];let sameRank=0,oppRank=0;
  for(const el of all){if(el===actor||el.dataset.livePlayer===a.targetPlayerId)continue;const same=sideOf(el)===actorSide;const bx=Number(el.dataset.baseX??el.style.left.replace('%',''))||50,by=Number(el.dataset.baseY??el.style.top.replace('%',''))||50;if(same){const lane=(sameRank++%5)-2;const advance=attacking?homeForward*(3.2+(sameRank%3)*.9):homeForward*1.2;const x=clamp(bx+advance+(midpoint.x-50)*.035);const y=clamp(by+(midpoint.y-by)*.12+lane*1.4,6,94);movePlayer(el,{x,y},duration*.92)}else{const lane=(oppRank++%5)-2;const compress=attacking?homeForward*2.1:-homeForward*.8;const x=clamp(bx+compress+(a.to.x-bx)*.06);const y=clamp(by+(a.to.y-by)*.16+lane*.9,6,94);movePlayer(el,{x,y},duration*.92)}}}
function duelPulse(pitch:HTMLElement,a:MatchStoryAction){if(!['intercept','tackle','loose','foul','rebound','header'].includes(a.type))return;const d=document.createElement('i');d.className=`md-sequence-duel ${a.type}`;d.style.left=`${a.to.x}%`;d.style.top=`${a.to.y}%`;pitch.appendChild(d);window.setTimeout(()=>d.remove(),620)}
function ballFrames(a:MatchStoryAction){const airborne=['cross','switch','longBall','header'].includes(a.type),power=['shot','goal'].includes(a.type),scramble=['rebound','loose','tackle','intercept'].includes(a.type);const midX=(a.from.x+a.to.x)/2,midY=(a.from.y+a.to.y)/2;const lift=airborne?Math.max(3,Math.min(10,Math.abs(a.to.x-a.from.x)*.12)):power?2.5:0;const mid={left:`${midX}%`,top:`${clamp(midY-lift,4,96)}%`,transform:`translate(-50%,-50%) scale(${airborne?1.28:power?1.18:scramble?.95:1.06})`};return[{left:`${a.from.x}%`,top:`${a.from.y}%`,transform:'translate(-50%,-50%) scale(1)'},mid,{left:`${a.to.x}%`,top:`${a.to.y}%`,transform:`translate(-50%,-50%) scale(${power?1.22:1.04})`} ]}
function runAction(center:HTMLElement,story:MatchStory,a:MatchStoryAction,duration:number,index:number){const pitch=center.querySelector<HTMLElement>('.md-live-pitch'),ball=pitch?.querySelector<HTMLElement>('.md-ball');if(!pitch||!ball)return;drawPath(pitch,a,duration);label(pitch,a);duelPulse(pitch,a);collectiveShift(center,a,duration);movePlayer(playerEl(center,a.playerId),a.from,Math.min(260,duration*.4));movePlayer(playerEl(center,a.targetPlayerId),a.to,duration);if(!reduceMotion){ball.animate(ballFrames(a),{duration,easing:['shot','goal'].includes(a.type)?'cubic-bezier(.12,.72,.12,1)':['cross','switch','longBall'].includes(a.type)?'cubic-bezier(.35,.15,.22,1)':'cubic-bezier(.3,.7,.25,1)',fill:'none'})}pitch.dataset.sequenceAction=a.type;center.dataset.sequenceActor=a.playerId??'';document.dispatchEvent(new CustomEvent('touchline:match-action',{detail:{center,story,action:a,index,total:story.actions.length}}))}
function play(center:HTMLElement,story:MatchStory,speed:number){clear(center);if(!story.actions.length)return;const total=Math.max(760,Math.min(2100,1220/story.actions.length))*story.actions.length/Math.max(.5,speed);const step=Math.max(190,total/story.actions.length);story.actions.forEach((a,i)=>remember(center,window.setTimeout(()=>runAction(center,story,a,Math.max(180,step*.84),i),i*step)))}

document.addEventListener('touchline:match-story',e=>{const detail=(e as CustomEvent<{story:MatchStory;speed:number;center:HTMLElement|null}>).detail;if(!detail?.center||!detail.story)return;play(detail.center,detail.story,detail.speed||1)});
