import type { Club, Player, Position, Tactics } from './engine';
import { selectStartingEleven } from './engine';
import { getPlayerRole, type PlayerRole } from './roles';

export type Vec2={x:number;y:number};
export type BallState={position:Vec2;velocity:Vec2;height:number;verticalVelocity:number;spin:number;ownerId?:string;lastTouchId?:string};
export type LivePlayer={playerId:string;clubId:string;role:PlayerRole;position:Vec2;velocity:Vec2;facing:number;condition:number;fatigue:number;yellowCards:number;sentOff:boolean;onPitch:boolean;minutesPlayed:number;homeSlot:Vec2;currentIntent:'holdShape'|'support'|'press'|'cover'|'run'|'receive'|'carry'|'pass'|'cross'|'shoot'|'tackle'|'intercept'|'goalkeep'};
export type TeamLiveState={clubId:string;attackingRight:boolean;formation:FormationId;players:LivePlayer[];benchIds:string[];substitutionsUsed:number;substitutionWindowsUsed:number;score:number;possessionSeconds:number;completedPasses:number;attemptedPasses:number;shots:number;shotsOnTarget:number;xg:number;corners:number;fouls:number;offsides:number;yellowCards:number;redCards:number;momentum:number;compactness:number;pressSuccess:number;passSuccess:number;flankSuccess:number};
export type MatchPhase='preKickoff'|'firstHalf'|'halftime'|'secondHalf'|'extraTime1'|'extraTimeBreak'|'extraTime2'|'penalties'|'finished';
export type MatchCoreState={tick:number;seconds:number;phase:MatchPhase;pitch:Pitch;ball:BallState;home:TeamLiveState;away:TeamLiveState;possessionClubId?:string;restart?:RestartState;seed:number;weather:WeatherState;memory:MatchMemory};
export type Pitch={length:number;width:number;goalWidth:number;goalDepth:number;penaltyAreaDepth:number;penaltyAreaWidth:number;goalAreaDepth:number;goalAreaWidth:number;centreCircleRadius:number;surface:'natural'|'hybrid'|'synthetic';condition:number};
export type WeatherState={temperature:number;rain:number;wind:number;windDirection:number};
export type RestartState={type:'kickoff'|'throwIn'|'goalKick'|'corner'|'freeKick'|'penalty'|'dropBall';clubId:string;position:Vec2;indirect?:boolean};
export type MatchMemory={recentPossessions:string[];recentShots:{clubId:string;xg:number;second:number}[];recentFouls:{clubId:string;second:number}[];homePressure:number;awayPressure:number;tempoDriftHome:number;tempoDriftAway:number};
export type FormationId='4-3-3'|'4-2-3-1'|'4-4-2'|'4-1-4-1'|'3-4-2-1'|'3-5-2'|'5-3-2';
export type FormationSlot={position:Position;x:number;y:number};
export const standardPitch:Pitch={length:105,width:68,goalWidth:7.32,goalDepth:2.44,penaltyAreaDepth:16.5,penaltyAreaWidth:40.32,goalAreaDepth:5.5,goalAreaWidth:18.32,centreCircleRadius:9.15,surface:'natural',condition:90};
const formations:Record<FormationId,FormationSlot[]>={
 '4-3-3':[{position:'GK',x:5,y:34},{position:'RB',x:24,y:59},{position:'CB',x:20,y:43},{position:'CB',x:20,y:25},{position:'LB',x:24,y:9},{position:'DM',x:38,y:34},{position:'CM',x:48,y:45},{position:'CM',x:48,y:23},{position:'RW',x:67,y:58},{position:'LW',x:67,y:10},{position:'ST',x:76,y:34}],
 '4-2-3-1':[{position:'GK',x:5,y:34},{position:'RB',x:23,y:59},{position:'CB',x:20,y:43},{position:'CB',x:20,y:25},{position:'LB',x:23,y:9},{position:'DM',x:38,y:43},{position:'DM',x:38,y:25},{position:'RW',x:60,y:58},{position:'AM',x:58,y:34},{position:'LW',x:60,y:10},{position:'ST',x:77,y:34}],
 '4-4-2':[{position:'GK',x:5,y:34},{position:'RB',x:23,y:59},{position:'CB',x:20,y:43},{position:'CB',x:20,y:25},{position:'LB',x:23,y:9},{position:'RW',x:45,y:59},{position:'CM',x:43,y:42},{position:'CM',x:43,y:26},{position:'LW',x:45,y:9},{position:'ST',x:70,y:42},{position:'ST',x:70,y:26}],
 '4-1-4-1':[{position:'GK',x:5,y:34},{position:'RB',x:23,y:59},{position:'CB',x:20,y:43},{position:'CB',x:20,y:25},{position:'LB',x:23,y:9},{position:'DM',x:35,y:34},{position:'RW',x:52,y:59},{position:'CM',x:48,y:43},{position:'CM',x:48,y:25},{position:'LW',x:52,y:9},{position:'ST',x:76,y:34}],
 '3-4-2-1':[{position:'GK',x:5,y:34},{position:'CB',x:19,y:50},{position:'CB',x:17,y:34},{position:'CB',x:19,y:18},{position:'RB',x:39,y:61},{position:'CM',x:39,y:43},{position:'CM',x:39,y:25},{position:'LB',x:39,y:7},{position:'AM',x:61,y:45},{position:'AM',x:61,y:23},{position:'ST',x:77,y:34}],
 '3-5-2':[{position:'GK',x:5,y:34},{position:'CB',x:19,y:50},{position:'CB',x:17,y:34},{position:'CB',x:19,y:18},{position:'RB',x:40,y:62},{position:'CM',x:40,y:48},{position:'DM',x:37,y:34},{position:'CM',x:40,y:20},{position:'LB',x:40,y:6},{position:'ST',x:70,y:43},{position:'ST',x:70,y:25}],
 '5-3-2':[{position:'GK',x:5,y:34},{position:'RB',x:27,y:62},{position:'CB',x:19,y:50},{position:'CB',x:17,y:34},{position:'CB',x:19,y:18},{position:'LB',x:27,y:6},{position:'CM',x:41,y:48},{position:'DM',x:38,y:34},{position:'CM',x:41,y:20},{position:'ST',x:69,y:43},{position:'ST',x:69,y:25}]
};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const dist=(a:Vec2,b:Vec2)=>Math.hypot(a.x-b.x,a.y-b.y);
export const distance=dist;
export function formationSlots(id:FormationId){return formations[id].map(x=>({...x}));}
export function inferFormation(club:Club):FormationId{const xi=selectStartingEleven(club),counts=(p:Position)=>xi.filter(x=>x.position===p).length;if(counts('CB')>=3&&counts('ST')>=2)return'3-5-2';if(counts('CB')>=3)return'3-4-2-1';if(counts('DM')>=2&&counts('AM')>=1)return'4-2-3-1';return'4-3-3';}
function mirror(p:Vec2,pitch:Pitch):Vec2{return{x:pitch.length-p.x,y:p.y}};
function adaptSlot(slot:Vec2,tactics:Tactics,pitch:Pitch){const mentality=tactics.mentality==='attacking'?6:tactics.mentality==='positive'?3:tactics.mentality==='defensive'?-5:0,line=(tactics.defensiveLine-50)*.10,widthScale=.72+tactics.width*.0056;return{x:clamp(slot.x+mentality+line,2,pitch.length-2),y:clamp(pitch.width/2+(slot.y-pitch.width/2)*widthScale,2,pitch.width-2)}}
function assignXI(club:Club,formation:FormationId,pitch:Pitch,attackingRight:boolean){const xi=[...selectStartingEleven(club)],slots=formations[formation].map(s=>({...s,point:{x:s.x,y:s.y}}));const result:LivePlayer[]=[];for(const slot of slots){xi.sort((a,b)=>positionFit(b,slot.position)-positionFit(a,slot.position));const player=xi.shift();if(!player)continue;let home=adaptSlot(slot.point,club.tactics,pitch);if(!attackingRight)home=mirror(home,pitch);result.push({playerId:player.id,clubId:club.id,role:getPlayerRole(club,player),position:{...home},velocity:{x:0,y:0},facing:attackingRight?0:Math.PI,condition:player.condition,fatigue:0,yellowCards:0,sentOff:false,onPitch:true,minutesPlayed:0,homeSlot:home,currentIntent:'holdShape'})}return result}
function positionFit(p:Player,target:Position){if(p.position===target)return100;if(['DM','CM','AM'].includes(p.position)&&['DM','CM','AM'].includes(target))return82;if(['RB','LB'].includes(p.position)&&['RB','LB'].includes(target))return76;if(p.position==='CB'&&['RB','LB','DM'].includes(target))return65;if(['RW','LW'].includes(p.position)&&['RW','LW','AM','ST'].includes(target))return66;return35}
export function createMatchCore(home:Club,away:Club,opts?:{pitch?:Partial<Pitch>;homeFormation?:FormationId;awayFormation?:FormationId;seed?:number;weather?:Partial<WeatherState>}):MatchCoreState{const pitch={...standardPitch,...opts?.pitch},hf=opts?.homeFormation??inferFormation(home),af=opts?.awayFormation??inferFormation(away),hPlayers=assignXI(home,hf,pitch,true),aPlayers=assignXI(away,af,pitch,false),homeXI=new Set(hPlayers.map(p=>p.playerId)),awayXI=new Set(aPlayers.map(p=>p.playerId));return{tick:0,seconds:0,phase:'preKickoff',pitch,ball:{position:{x:pitch.length/2,y:pitch.width/2},velocity:{x:0,y:0},height:0,verticalVelocity:0,spin:0},home:{clubId:home.id,attackingRight:true,formation:hf,players:hPlayers,benchIds:home.players.filter(p=>!homeXI.has(p.id)).map(p=>p.id),substitutionsUsed:0,substitutionWindowsUsed:0,score:0,possessionSeconds:0,completedPasses:0,attemptedPasses:0,shots:0,shotsOnTarget:0,xg:0,corners:0,fouls:0,offsides:0,yellowCards:0,redCards:0,momentum:50,compactness:50,pressSuccess:50,passSuccess:50,flankSuccess:50},away:{clubId:away.id,attackingRight:false,formation:af,players:aPlayers,benchIds:away.players.filter(p=>!awayXI.has(p.id)).map(p=>p.id),substitutionsUsed:0,substitutionWindowsUsed:0,score:0,possessionSeconds:0,completedPasses:0,attemptedPasses:0,shots:0,shotsOnTarget:0,xg:0,corners:0,fouls:0,offsides:0,yellowCards:0,redCards:0,momentum:50,compactness:50,pressSuccess:50,passSuccess:50,flankSuccess:50},seed:opts?.seed??Math.floor(Math.random()*2_000_000_000),weather:{temperature:22,rain:0,wind:5,windDirection:0,...opts?.weather},memory:{recentPossessions:[],recentShots:[],recentFouls:[],homePressure:0,awayPressure:0,tempoDriftHome:0,tempoDriftAway:0}}}
export function teamOf(state:MatchCoreState,clubId:string){return state.home.clubId===clubId?state.home:state.away}
export function opponentOf(state:MatchCoreState,clubId:string){return state.home.clubId===clubId?state.away:state.home}
export function livePlayer(state:MatchCoreState,id:string){return[...state.home.players,...state.away.players].find(p=>p.playerId===id)}
export function visiblePlayers(state:MatchCoreState,observer:LivePlayer,visionAttribute:number){const range=18+visionAttribute*.38,halfAngle=(55+visionAttribute*.42)*Math.PI/180;return[...state.home.players,...state.away.players].filter(p=>p.onPitch&&!p.sentOff&&p.playerId!==observer.playerId&&dist(observer.position,p.position)<=range).filter(p=>{const angle=Math.atan2(p.position.y-observer.position.y,p.position.x-observer.position.x),delta=Math.atan2(Math.sin(angle-observer.facing),Math.cos(angle-observer.facing));return Math.abs(delta)<=halfAngle})}
export function influenceGrid(state:MatchCoreState,cols=10,rows=7){const grid=Array.from({length:rows},()=>Array.from({length:cols},()=>({home:0,away:0})));for(const p of [...state.home.players,...state.away.players].filter(x=>x.onPitch&&!x.sentOff)){const team=p.clubId===state.home.clubId?'home':'away',sigma=positionSigma(p.role);for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const point={x:(c+.5)*state.pitch.length/cols,y:(r+.5)*state.pitch.width/rows},d=dist(point,p.position),weight=Math.exp(-(d*d)/(2*sigma*sigma));grid[r][c][team]+=weight}}return grid}
function positionSigma(role:PlayerRole){if(role==='goalkeeper'||role==='sweeperKeeper')return10;if(['centralDefender','ballPlayingDefender','stopper','fullback','invertedFullback'].includes(role))return12;if(['anchor','deepLyingPlaymaker','ballWinningMidfielder','centralMidfielder','boxToBox'].includes(role))return15;return18}
export function territorialControlAt(state:MatchCoreState,point:Vec2){let h=0,a=0;for(const p of state.home.players.filter(x=>x.onPitch&&!x.sentOff)){const s=positionSigma(p.role);h+=Math.exp(-(dist(point,p.position)**2)/(2*s*s))}for(const p of state.away.players.filter(x=>x.onPitch&&!x.sentOff)){const s=positionSigma(p.role);a+=Math.exp(-(dist(point,p.position)**2)/(2*s*s))}const total=h+a||1;return{home:h/total,away:a/total}}
export function offsideLine(state:MatchCoreState,defendingClubId:string){const t=teamOf(state,defendingClubId),xs=t.players.filter(p=>p.onPitch&&!p.sentOff&&p.role!=='goalkeeper'&&p.role!=='sweeperKeeper').map(p=>p.position.x).sort((a,b)=>a-b);if(xs.length<2)return t.attackingRight?state.pitch.length:0;return t.attackingRight?xs[1]:xs[xs.length-2]}
