import type { Club, Player } from './engine';
import type { MatchCoreState, RestartState, Vec2 } from './match-core-v2';
import { distance, teamOf } from './match-core-v2';
import { kickBall } from './match-ball-physics-v2';
import { buildSetPiecePlan, defensiveSetPieceAssignments, setPieceExpectedThreat, type SetPieceKind, type SetPiecePlan } from './match-set-pieces-v2';
import { applyShotResolution, resolveShotV2, type ShotType } from './match-goalkeeper-resolution-v2';

const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const attr=(p:Player|undefined,k:string,f=50)=>Number((p?.attributes as any)?.[k]??f);
function player(c:Club,id:string){return c.players.find(p=>p.id===id)}
function rng(s:MatchCoreState){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function mapKind(r:RestartState):SetPieceKind{if(r.type==='corner')return'corner';if(r.type==='goalKick')return'goalKick';if(r.type==='throwIn')return'throwIn';if(r.type==='penalty')return'penalty';if(r.type==='kickoff')return'kickoff';return r.indirect?'freeKickIndirect':'freeKickDirect'}
function moveAssignments(s:MatchCoreState,plan:SetPiecePlan,def:Club){for(const a of plan.assignments){const p=teamOf(s,plan.clubId).players.find(x=>x.playerId===a.playerId);if(p)p.position={...a.target}}for(const a of defensiveSetPieceAssignments(s,def,plan)){const p=teamOf(s,def.id).players.find(x=>x.playerId===a.playerId);if(p)p.position={...a.target}}}
function log(s:MatchCoreState,plan:SetPiecePlan,result:string,xT:number,extra:any={}){const any=s as any;if(!any.__setPieceLog)any.__setPieceLog=[];any.__setPieceLog.push({second:s.seconds,clubId:plan.clubId,kind:plan.kind,routine:plan.routine,takerId:plan.takerId,expectedThreat:xT,result,...extra});if(any.__setPieceLog.length>220)any.__setPieceLog.shift()}
function unifiedStaticShot(s:MatchCoreState,c:Club,def:Club,plan:SetPiecePlan,pos:Vec2,kind:'penalty'|'freeKickDirect'){const takerLive=teamOf(s,c.id).players.find(p=>p.playerId===plan.takerId&&p.onPitch&&!p.sentOff),taker=player(c,plan.takerId);if(!takerLive||!taker)return{result:'invalid',resolution:undefined};takerLive.position={...pos};const d=distance(pos,{x:teamOf(s,c.id).attackingRight?s.pitch.length:0,y:s.pitch.width/2}),tech=attr(taker,'technique'),fk=attr(taker,'freeKicks',tech),fin=attr(taker,'finishing'),forced:ShotType=kind==='penalty'?(fin+tech>145?'placed':'power'):(fk>74&&d>18?'curl':fin>72?'power':'placed'),resolution=resolveShotV2(s,c,def,takerLive,taker,()=>rng(s),forced);if(kind==='penalty'){const base=.76,execution=clamp((fin*.36+tech*.25+attr(taker,'composure',attr(taker,'decisions'))*.24-55)/100,-.12,.14);resolution.xg=base;resolution.postShotXg=resolution.onTarget?clamp(base+execution+(resolution.shotType==='power'?.02:0),.42,.94):0}else{const wallPenalty=d<31?.055:0,freeKickXg=clamp(.015+(31-d)*.012+fk*.0017+tech*.0008-wallPenalty,.015,.29);resolution.xg=freeKickXg;resolution.postShotXg=resolution.onTarget?clamp(resolution.postShotXg*.45+freeKickXg*.72,.02,.58):0}applyShotResolution(s,c,def,takerLive,resolution);return{result:resolution.goal?'goal':resolution.onTarget?(resolution.rebound?'save/rebound':resolution.saveType==='catch'?'save/catch':'save'):'miss',resolution}}
function delivery(s:MatchCoreState,c:Club,plan:SetPiecePlan,pos:Vec2){const taker=player(c,plan.takerId),target=plan.target??plan.assignments.find(a=>a.role==='primaryTarget')?.target??{x:pos.x+(teamOf(s,c.id).attackingRight?18:-18),y:s.pitch.width/2},quality=clamp(attr(taker,'passing')*.34+attr(taker,'technique')*.3+attr(taker,'decisions')*.15+plan.quality*.2),error=(100-quality)/100*(plan.kind==='corner'?8:plan.kind==='goalKick'?12:6),actual={x:target.x+(rng(s)-.5)*error,y:target.y+(rng(s)-.5)*error},long=plan.routine==='longTarget'||plan.kind==='corner'||['nearPost','farPost','penaltySpot','screen'].includes(plan.routine),speed=plan.kind==='throwIn'?12:plan.kind==='goalKick'?24:long?20:14,lift=plan.kind==='throwIn'?(plan.routine==='longTarget'?3.8:.4):plan.kind==='goalKick'?(long?6:1):long?5.2:.25;kickBall(s,{direction:{x:actual.x-pos.x,y:actual.y-pos.y},speed,lift,spin:(rng(s)-.5)*(plan.kind==='corner'?1.7:.8),ownerId:plan.takerId});s.possessionClubId=undefined;return'liveBall'}
export function executeRestartV2(s:MatchCoreState,home:Club,away:Club){const restart=s.restart;if(!restart)return false;const c=restart.clubId===home.id?home:away,def=restart.clubId===home.id?away:home,kind=mapKind(restart),plan=buildSetPiecePlan(s,c,kind,restart.position),taker=teamOf(s,c.id).players.find(p=>p.playerId===plan.takerId&&p.onPitch&&!p.sentOff);if(!taker)return false;moveAssignments(s,plan,def);taker.position={...restart.position};s.ball.position={...restart.position};s.ball.ownerId=plan.takerId;s.possessionClubId=c.id;const xT=setPieceExpectedThreat(s,c,plan);let result:string,extra:any={};if(kind==='penalty'){const out=unifiedStaticShot(s,c,def,plan,restart.position,'penalty');result=out.result;extra={shot:out.resolution}}else if(plan.routine==='directShot'&&kind==='freeKickDirect'){const out=unifiedStaticShot(s,c,def,plan,restart.position,'freeKickDirect');result=out.result;extra={shot:out.resolution}}else result=delivery(s,c,plan,restart.position);if(s.restart===restart)s.restart=undefined;log(s,plan,result,xT,extra);return true}
export function setPieceLog(s:MatchCoreState){return[...((((s as any).__setPieceLog)??[]) as any[])]}
