import type { MatchCoreState, LivePlayer, Vec2 } from './match-core-v2';
export type DefensiveTask='press'|'cover'|'screen'|'mark'|'protectDepth'|'offsideLine'|'recover'|'doubleTeam';
export type DefensiveAssignment={playerId:string;task:DefensiveTask;target:Vec2;opponentId?:string;urgency:number;reason:string};
export type DefensivePhase='highPress'|'midBlock'|'lowBlock'|'counterpress'|'recovery';
export type CollectiveDefencePlan={clubId:string;phase:DefensivePhase;lineX:number;compactness:number;pressTrigger:number;assignments:DefensiveAssignment[];trapSide?:'left'|'right';generatedAt:number};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));const dist=(a:Vec2,b:Vec2)=>Math.hypot(a.x-b.x,a.y-b.y);const midpoint=(a:Vec2,b:Vec2):Vec2=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
function ownGoalX(state:MatchCoreState,clubId:string){return clubId===state.homeClubId?0:state.pitch.length}
function attackDir(state:MatchCoreState,clubId:string){return clubId===state.homeClubId?1:-1}
function danger(state:MatchCoreState,clubId:string){const goal=ownGoalX(state,clubId),d=Math.abs(state.ball.position.x-goal);return clamp(100-d/state.pitch.length*100)}
function phase(state:MatchCoreState,clubId:string,pressing:number,line:number):DefensivePhase{const d=danger(state,clubId),recentLoss=((state as any).__lastPossessionLoss?.clubId===clubId&&state.seconds-((state as any).__lastPossessionLoss?.second??-99)<6);if(recentLoss&&pressing>55)return'counterpress';if(d>72)return'lowBlock';if(pressing>72&&d<52)return'highPress';if(d>48||line<45)return'midBlock';return'recovery'}
function linePosition(state:MatchCoreState,clubId:string,line:number,p:DefensivePhase){const dir=attackDir(state,clubId),own=ownGoalX(state,clubId),base=(p==='highPress'?54:p==='counterpress'?49:p==='midBlock'?39:p==='lowBlock'?25:34)+((line-50)*.22);return own+dir*clamp(base,18,68)}
function nearest(players:LivePlayer[],pos:Vec2,exclude=new Set<string>()){return players.filter(p=>!exclude.has(p.playerId)).sort((a,b)=>dist(a.position,pos)-dist(b.position,pos))[0]}
function passingLaneScreen(state:MatchCoreState,carrier:LivePlayer,target:LivePlayer,goalX:number):Vec2{const m=midpoint(carrier.position,target.position);const goalPull=(goalX-m.x)*.08;return{x:m.x+goalPull,y:m.y}}
export function buildCollectiveDefencePlan(state:MatchCoreState,clubId:string,tactics:{pressing:number;defensiveLine:number;compactness:number}):CollectiveDefencePlan{const defenders=state.players.filter(p=>p.clubId===clubId&&p.onPitch),opponents=state.players.filter(p=>p.clubId!==clubId&&p.onPitch),carrier=state.ball.ownerId?state.players.find(p=>p.playerId===state.ball.ownerId):undefined;const ph=phase(state,clubId,tactics.pressing,tactics.defensiveLine),lineX=linePosition(state,clubId,tactics.defensiveLine,ph),assignments:DefensiveAssignment[]=[],used=new Set<string>(),goalX=ownGoalX(state,clubId);let trapSide:'left'|'right'|undefined;if(carrier&&carrier.clubId!==clubId){trapSide=carrier.position.y<state.pitch.width/2?'left':'right';const presser=nearest(defenders,carrier.position);if(presser){used.add(presser.playerId);assignments.push({playerId:presser.playerId,task:'press',target:carrier.position,opponentId:carrier.playerId,urgency:ph==='counterpress'?96:82,reason:ph==='counterpress'?'immediate pressure after turnover':'nearest viable presser'});const support=nearest(defenders,carrier.position,used);if(support&&dist(support.position,carrier.position)<14){used.add(support.playerId);const double=ph==='counterpress'||danger(state,clubId)>65;assignments.push({playerId:support.playerId,task:double?'doubleTeam':'cover',target:double?{x:carrier.position.x,y:carrier.position.y+(trapSide==='left'?2.8:-2.8)}:midpoint(presser.position,{x:goalX,y:state.pitch.width/2}),opponentId:carrier.playerId,urgency:double?84:72,reason:double?'trap ball carrier with second defender':'cover primary presser'})}const options=opponents.filter(o=>o.playerId!==carrier.playerId).sort((a,b)=>dist(a.position,carrier.position)-dist(b.position,carrier.position)).slice(0,3);for(const o of options){const screener=nearest(defenders,passingLaneScreen(state,carrier,o,goalX),used);if(!screener)continue;used.add(screener.playerId);assignments.push({playerId:screener.playerId,task:'screen',target:passingLaneScreen(state,carrier,o,goalX),opponentId:o.playerId,urgency:68,reason:'block dangerous passing lane / cover shadow'})}}
const deepestThreats=opponents.filter(o=>Math.abs(o.position.x-goalX)<38).sort((a,b)=>Math.abs(a.position.x-goalX)-Math.abs(b.position.x-goalX));for(const o of deepestThreats.slice(0,3)){const marker=nearest(defenders,o.position,used);if(!marker)continue;used.add(marker.playerId);const dir=attackDir(state,clubId);assignments.push({playerId:marker.playerId,task:'mark',target:{x:o.position.x-dir*2.2,y:o.position.y},opponentId:o.playerId,urgency:75,reason:'track runner threatening depth'})}
for(const p of defenders.filter(p=>!used.has(p.playerId))){const role=(p as any).position??'';const central=Math.abs(p.position.y-state.pitch.width/2)<18;if((role.includes('CB')||role==='DC'||central)&&ph!=='lowBlock')assignments.push({playerId:p.playerId,task:'offsideLine',target:{x:lineX,y:p.basePosition.y},urgency:58,reason:'maintain synchronized defensive line'});else assignments.push({playerId:p.playerId,task:'recover',target:{x:lineX,y:p.basePosition.y},urgency:52,reason:'restore compact team shape'})}
return{clubId,phase:ph,lineX,compactness:clamp(tactics.compactness+(ph==='lowBlock'?14:ph==='counterpress'?-4:0)),pressTrigger:clamp(tactics.pressing+(ph==='counterpress'?18:0)),assignments,trapSide,generatedAt:state.seconds}}
export function defensiveAssignment(plan:CollectiveDefencePlan,playerId:string){return plan.assignments.find(a=>a.playerId===playerId)}
export function applyCollectiveDefenceTargets(state:MatchCoreState,plan:CollectiveDefencePlan){for(const a of plan.assignments){const p=state.players.find(x=>x.playerId===a.playerId);if(!p||!p.onPitch)continue;(p as any).collectiveDefensiveTask=a.task;(p as any).collectiveTarget={...a.target};if(a.task==='press'||a.task==='doubleTeam')p.currentIntent='press';else if(a.task==='mark'||a.task==='screen'||a.task==='cover')p.currentIntent='holdShape'}}
