import type { Club } from './engine';
import { createMatchCore } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { validateMatchState } from './match-v2-diagnostics';
import { officiatingLog } from './match-officiating-v2';
import { shotResolutionLog } from './match-goalkeeper-resolution-v2';
import { aerialDuelLog } from './match-aerial-duel-v2';
import { decisionTrace } from './match-decision-ai-v2';
import { setPieceLog } from './match-set-piece-runtime-v2';

export type CalibrationMetric='goals'|'shots'|'shotsOnTarget'|'shotConversion'|'xg'|'passes'|'passPct'|'dribbles'|'corners'|'fouls'|'yellows'|'reds'|'offsides'|'penalties'|'injuries'|'keeperSavePct'|'possessionHome'|'drawRate'|'homeWinRate';
export type CalibrationTarget={min:number;max:number;hardMin?:number;hardMax?:number;hintLow?:string;hintHigh?:string};
export type CalibrationTargets=Record<CalibrationMetric,CalibrationTarget>;
export type CalibrationSummary={matches:number;invalidMatches:number;metrics:Record<CalibrationMetric,number>;issues:string[];score:number;withinTarget:Record<CalibrationMetric,boolean>;distribution:{homeWins:number;draws:number;awayWins:number};auxiliary:{aerialDuels:number;varReviews:number;receptions:number}};
export const broadFootballTargets:CalibrationTargets={
 goals:{min:2.5,max:3.5,hardMin:.7,hardMax:5.5,hintLow:'revisar decisão de chute, execução e dificuldade do goleiro',hintHigh:'revisar poder de finalização e capacidade dos goleiros'},
 shots:{min:20,max:30,hardMin:10,hardMax:44,hintLow:'jogadores finalizam pouco; revisar elegibilidade e utilidade de shoot',hintHigh:'excesso de finalizações; elevar custo de chutes ruins'},
 shotsOnTarget:{min:6,max:12,hardMin:3,hardMax:18},shotConversion:{min:8,max:15,hardMin:3,hardMax:24,hintLow:'chutes fracos ou goleiros fortes demais',hintHigh:'finalizações fortes demais ou goleiros fracos'},
 xg:{min:1.8,max:3.8,hardMin:.7,hardMax:5.5},passes:{min:300,max:600,hardMin:160,hardMax:850,hintLow:'volume de circulação baixo; revisar decisão de passe e duração das posses',hintHigh:'posses excessivamente estéreis; revisar progressão e risco'},passPct:{min:75,max:90,hardMin:52,hardMax:95,hintLow:'revisar erro técnico/interceptação',hintHigh:'passes/interceptações fáceis demais'},
 dribbles:{min:8,max:25,hardMin:2,hardMax:42,hintLow:'drible/condução raros demais',hintHigh:'agentes insistem demais no 1x1'},corners:{min:6,max:14,hardMin:2,hardMax:22},fouls:{min:15,max:35,hardMin:8,hardMax:48},yellows:{min:2,max:7,hardMin:.4,hardMax:12},reds:{min:.03,max:.45,hardMin:0,hardMax:1.2},offsides:{min:1,max:6,hardMin:.2,hardMax:10},penalties:{min:.08,max:.55,hardMin:0,hardMax:1.1},injuries:{min:.08,max:.8,hardMin:0,hardMax:1.8},keeperSavePct:{min:58,max:82,hardMin:35,hardMax:94},possessionHome:{min:42,max:58,hardMin:30,hardMax:70},drawRate:{min:15,max:40,hardMin:5,hardMax:55,hintLow:'poucos empates; revisar conversão e dinâmica de fim de jogo',hintHigh:'muitos empates; revisar urgência e capacidade ofensiva'},homeWinRate:{min:30,max:55,hardMin:18,hardMax:68,hintLow:'mandante sem vantagem contextual suficiente',hintHigh:'vantagem de mando excessiva'}
};
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
function matchStats(home:Club,away:Club,seed:number){const s=createMatchCore(home,away,{seed});simulateMatchCore(s,home,away);const refs=officiatingLog(s),shots=shotResolutionLog(s),setPieces=setPieceLog(s),trace=decisionTrace(s),inj=(((s as any).__matchInjuries??[]) as any[]),receptions=(((s as any).__receptions??[]) as any[]),totalPoss=Math.max(1,s.home.possessionSeconds+s.away.possessionSeconds),onTarget=s.home.shotsOnTarget+s.away.shotsOnTarget,totalShots=s.home.shots+s.away.shots,saves=shots.filter(x=>x.onTarget&&!x.goal).length,totalPasses=s.home.attemptedPasses+s.away.attemptedPasses,completed=s.home.completedPasses+s.away.completedPasses,dribbles=trace.filter(x=>x.chosen==='dribble'||x.chosen==='carry').length,penaltyRestarts=setPieces.filter((x:any)=>x.kind==='penalty').length,penaltyVAR=refs.filter((x:any)=>x.kind==='varPenalty'&&x.final==='given').length;return{invalid:validateMatchState(s).length>0,homeWin:s.home.score>s.away.score?1:0,draw:s.home.score===s.away.score?1:0,awayWin:s.home.score<s.away.score?1:0,goals:s.home.score+s.away.score,shots:totalShots,shotsOnTarget:onTarget,shotConversion:totalShots?(s.home.score+s.away.score)/totalShots*100:0,xg:s.home.xg+s.away.xg,passes:totalPasses,passPct:totalPasses?completed/totalPasses*100:0,dribbles,corners:s.home.corners+s.away.corners,fouls:s.home.fouls+s.away.fouls,yellows:s.home.yellowCards+s.away.yellowCards,reds:s.home.redCards+s.away.redCards,offsides:s.home.offsides+s.away.offsides,penalties:Math.max(penaltyRestarts,penaltyVAR),injuries:inj.filter((x:any)=>x.severity!=='knock').length,keeperSavePct:onTarget?Math.min(100,saves/onTarget*100):0,possessionHome:s.home.possessionSeconds/totalPoss*100,aerialDuels:aerialDuelLog(s).length,varReviews:refs.filter((x:any)=>x.var?.reviewed||['varPenalty','varRedCard'].includes(x.kind)).length,receptions:receptions.length}}
export function calibrateMatchEngineV2(home:Club,away:Club,matches=250,seedBase=20260824,targets:CalibrationTargets=broadFootballTargets):CalibrationSummary{const rows:ReturnType<typeof matchStats>[]=[];for(let i=0;i<matches;i++)rows.push(matchStats(home,away,seedBase+i*7919));const metrics={} as Record<CalibrationMetric,number>,keys=Object.keys(targets) as CalibrationMetric[];for(const k of keys){if(k==='drawRate')metrics[k]=Number((mean(rows.map(r=>r.draw))*100).toFixed(3));else if(k==='homeWinRate')metrics[k]=Number((mean(rows.map(r=>r.homeWin))*100).toFixed(3));else metrics[k]=Number(mean(rows.map(r=>Number((r as any)[k]))).toFixed(3))}const withinTarget={} as Record<CalibrationMetric,boolean>,issues:string[]=[];let score=100;for(const k of keys){const t=targets[k],v=metrics[k],ok=v>=t.min&&v<=t.max;withinTarget[k]=ok;if(!ok){const below=v<t.min,delta=below?(t.min-v)/Math.max(.01,t.min):(v-t.max)/Math.max(.01,t.max),hard=(t.hardMin!==undefined&&v<t.hardMin)||(t.hardMax!==undefined&&v>t.hardMax);score-=Math.min(hard?18:10,delta*24+(hard?7:2));const hint=below?t.hintLow:t.hintHigh;issues.push(`${k}: ${v} fora da faixa ${t.min}–${t.max}${hard?' (desvio crítico)':''}${hint?` — ${hint}`:''}`)}}const invalidMatches=rows.filter(r=>r.invalid).length;if(invalidMatches){score-=Math.min(30,invalidMatches/matches*100);issues.push(`${invalidMatches}/${matches} partidas violaram invariantes.`)}return{matches,invalidMatches,metrics,issues,score:Number(Math.max(0,score).toFixed(1)),withinTarget,distribution:{homeWins:rows.reduce((n,r)=>n+r.homeWin,0),draws:rows.reduce((n,r)=>n+r.draw,0),awayWins:rows.reduce((n,r)=>n+r.awayWin,0)},auxiliary:{aerialDuels:Number(mean(rows.map(r=>r.aerialDuels)).toFixed(2)),varReviews:Number(mean(rows.map(r=>r.varReviews)).toFixed(2)),receptions:Number(mean(rows.map(r=>r.receptions)).toFixed(2))}}}
export function compareCalibrationVariants(home:Club,away:Club,variants:{name:string;seedBase:number;matches?:number}[]){return variants.map(v=>({name:v.name,result:calibrateMatchEngineV2(home,away,v.matches??150,v.seedBase)})).sort((a,b)=>b.result.score-a.result.score)}
