import type { MatchCoreState, Vec2 } from './match-core-v2';
import { shotResolutionLog } from './match-goalkeeper-resolution-v2';
import { receptionLog } from './match-first-touch-v2';
import { officiatingLog } from './match-officiating-v2';
import { goalFrameHitLog } from './match-ball-physics-v2';
export type ActionMapType='shot'|'reception'|'foul'|'frameHit'|'goal';
export type ActionMapPoint={second:number;type:ActionMapType;playerId?:string;clubId?:string;position:Vec2;value?:number;success?:boolean;detail?:string};
export function matchActionMap(state:MatchCoreState):ActionMapPoint[]{const out:ActionMapPoint[]=[];for(const s of shotResolutionLog(state)){const p=[...state.home.players,...state.away.players].find(x=>x.playerId===s.shooterId);out.push({second:Number((s as any).second??0),type:s.goal?'goal':'shot',playerId:s.shooterId,clubId:p?.clubId,position:p?{...p.position}:{x:state.pitch.length/2,y:state.pitch.width/2},value:s.xg,success:s.goal,detail:s.shotType})}for(const r of receptionLog(state)){const p=[...state.home.players,...state.away.players].find(x=>x.playerId===r.playerId);out.push({second:Number(r.second??0),type:'reception',playerId:r.playerId,clubId:p?.clubId,position:{...r.nextPosition},value:r.control,success:r.success,detail:r.type})}for(const e of officiatingLog(state)){if(!e.foul||!e.victimId)continue;const p=[...state.home.players,...state.away.players].find(x=>x.playerId===e.victimId);if(p)out.push({second:Number(e.second??0),type:'foul',playerId:e.tacklerId,clubId:p.clubId===state.home.clubId?state.away.clubId:state.home.clubId,position:{...p.position},success:false,detail:e.reason??e.kind})}for(const h of goalFrameHitLog(state))out.push({second:Number((h as any).second??0),type:'frameHit',position:{...h.position},value:h.impactSpeed,success:false,detail:h.kind});return out.sort((a,b)=>a.second-b.second)}
export function playerActionMap(state:MatchCoreState,playerId:string){return matchActionMap(state).filter(x=>x.playerId===playerId)}
