import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf, territorialControlAt, visiblePlayers } from './match-core-v2';
import { passInterceptionRisk, predictBallPath, bestInterception } from './match-ball-physics-v2';
import { markingInstruction } from './match-marking-v2';

export type BallDecisionKind='shortPass'|'progressivePass'|'throughBall'|'switchPlay'|'longBall'|'cross'|'carry'|'dribble'|'shoot'|'hold'|'clear';
export type OffBallDecisionKind='holdShape'|'support'|'press'|'cover'|'run'|'intercept'|'receive';
export type BallDecision={kind:BallDecisionKind;utility:number;targetPlayerId?:string;target?:Vec2;risk:number;reason:string;expectedValue:number};
export type OffBallDecision={kind:OffBallDecisionKind;utility:number;target:Vec2;reason:string};
export type DecisionTrace={playerId:string;second:number;candidates:{kind:string;utility:number;reason:string}[];chosen:string};

const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function noise(state:MatchCoreState,p:Player,tag:string){const x=Math.sin((state.seed^hash(`${p.id}-${tag}-${Math.floor(state.seconds)}`))*12.9898)*43758.5453,f=x-Math.floor(x),clarity=clamp(p.attributes.decisions*.55+p.morale*.2+(100-clamp((state as any).__decisionFatigue??0))*.05+20)/100;return(f-.5)*(1-clarity)*28}
function advanceSign(state:MatchCoreState,clubId:string){return teamOf(state,clubId).attackingRight?1:-1}
function goal(state:MatchCoreState,clubId:string):Vec2{return{x:teamOf(state,clubId).attackingRight?state.pitch.length:0,y:state.pitch.width/2}}
function pressureAt(state:MatchCoreState,clubId:string,pos:Vec2){const c=territorialControlAt(state,pos);return clubId===state.home.clubId?c.away:c.home}
function progression(state:MatchCoreState,clubId:string,from:Vec2,to:Vec2){return(to.x-from.x)*advanceSign(state,clubId)}
function angleToGoal(state:MatchCoreState,clubId:string,pos:Vec2){const g=goal(state,clubId),d=Math.max(1,distance(pos,g));return Math.atan2(state.pitch.goalWidth/2,d)*2}
function shotValue(state:MatchCoreState,src:Player,p:LivePlayer){const d=distance(p.position,goal(state,p.clubId)),ang=angleToGoal(state,p.clubId,p.position),press=pressureAt(state,p.clubId,p.position);return clamp((30-d)*2.25+ang*30+src.attributes.finishing*.45+src.attributes.technique*.15-press*35,0,100)}
function teammateScore(state:MatchCoreState,src:Player,from:LivePlayer,to:LivePlayer,kind:BallDecisionKind){const prog=progression(state,from.clubId,from.position,to.position),d=distance(from.position,to.position),risk=passInterceptionRisk(state,from.position,to.position,from.clubId),control=territorialControlAt(state,to.position),own=from.clubId===state.home.clubId?control.home:control.away,goalDist=distance(to.position,goal(state,from.clubId)),press=pressureAt(state,from.clubId,to.position);let u=src.attributes.passing*.24+src.attributes.decisions*.22+prog*1.15+own*25-press*20-risk*42-d*.25+(35-goalDist)*.45;if(kind==='shortPass')u+=d<15?15:-Math.max(0,d-15)*1.4;if(kind==='progressivePass')u+=prog>5?14:-12;if(kind==='throughBall')u+=prog>10?20:-18,u+=goalDist<28?10:0,u-=risk*18;if(kind==='switchPlay')u+=Math.abs(to.position.y-from.position.y)>24?20:-14,u+=d>22?6:0;if(kind==='longBall')u+=d>28?14:-10,u+=prog>15?8:0;if(kind==='cross')u+=Math.abs(from.position.y-state.pitch.width/2)>18?15:-10,u+=goalDist<22?12:0;return{utility:u,risk}}
function visibleMates(state:MatchCoreState,club:Club,p:LivePlayer,src:Player){const visible=new Set(visiblePlayers(state,p,src.attributes.decisions).filter(x=>x.clubId===club.id).map(x=>x.playerId));return teamOf(state,club.id).players.filter(x=>x.onPitch&&!x.sentOff&&x.playerId!==p.playerId&&visible.has(x.playerId))}
function riskPreference(club:Club,src:Player,p:LivePlayer,state:MatchCoreState){const t=club.tactics,team=teamOf(state,club.id),opp=opponentOf(state,club.id),late=state.seconds>4200,losing=team.score<opp.score,winning=team.score>opp.score;let r=t.mentality==='attacking'?72:t.mentality==='positive'?60:t.mentality==='defensive'?32:48;r+=(src.attributes.decisions-50)*.08;r+=(src.morale-50)*.05;r-=p.fatigue*.16;if(late&&losing)r+=14;if(late&&winning)r-=12;return clamp(r)}
function transitionBonus(club:Club,state:MatchCoreState,p:LivePlayer){const recent=state.memory.recentPossessions.slice(-4),turnover=recent.length>=2&&recent[recent.length-1]===club.id&&recent[recent.length-2]!==club.id;if(!turnover)return 0;return club.tactics.transition==='counter'?18:club.tactics.transition==='hold'?-8:5}
function candidatePasses(state:MatchCoreState,club:Club,p:LivePlayer,src:Player):BallDecision[]{const out:BallDecision[]=[];for(const mate of visibleMates(state,club,p,src)){const d=distance(p.position,mate.position),prog=progression(state,club.id,p.position,mate.position);const kinds:BallDecisionKind[]=[d<18?'shortPass':'progressivePass'];if(prog>9)kinds.push('throughBall');if(Math.abs(mate.position.y-p.position.y)>22)kinds.push('switchPlay');if(d>28)kinds.push('longBall');if(Math.abs(p.position.y-state.pitch.width/2)>18&&progression(state,club.id,p.position,goal(state,club.id))<35)kinds.push('cross');for(const k of new Set(kinds)){const s=teammateScore(state,src,p,mate,k),riskPenalty=s.risk*(100-riskPreference(club,src,p,state))*.38,utility=s.utility-riskPenalty+transitionBonus(club,state,p)+noise(state,src,`${k}-${mate.playerId}`);out.push({kind:k,utility,targetPlayerId:mate.playerId,target:{...mate.position},risk:s.risk,reason:`${k}: progresso ${prog.toFixed(1)}m, risco ${(s.risk*100).toFixed(0)}%, espaço`,expectedValue:s.utility})}}return out}
function selfActions(state:MatchCoreState,club:Club,p:LivePlayer,src:Player):BallDecision[]{const out:BallDecision[]=[],g=goal(state,club.id),d=distance(p.position,g),press=pressureAt(state,club.id,p.position),riskPref=riskPreference(club,src,p,state),shoot=shotValue(state,src,p);if(d<34)out.push({kind:'shoot',utility:shoot+noise(state,src,'shoot'),risk:clamp(1-shoot/100,0,1),reason:`finalização: distância ${d.toFixed(1)}m, pressão ${(press*100).toFixed(0)}%`,expectedValue:shoot});const sign=advanceSign(state,club.id),carryTarget={x:p.position.x+sign*(5+src.attributes.pace*.05),y:p.position.y},carryRisk=clamp(press*.7+(100-src.attributes.technique)*.004,0,1);out.push({kind:'carry',utility:src.attributes.technique*.28+src.attributes.pace*.2+riskPref*.18-press*32+transitionBonus(club,state,p)+noise(state,src,'carry'),target:carryTarget,risk:carryRisk,reason:'condução para ganhar território',expectedValue:50-carryRisk*30});if(press>.35)out.push({kind:'dribble',utility:src.attributes.technique*.42+src.attributes.pace*.2+riskPref*.15-press*38+noise(state,src,'dribble'),target:carryTarget,risk:clamp(carryRisk+.1,0,1),reason:'1x1 sob pressão',expectedValue:45-carryRisk*28});out.push({kind:'hold',utility:32+src.attributes.decisions*.18+(club.tactics.transition==='hold'?16:0)-press*20+noise(state,src,'hold'),risk:press*.35,reason:'reter posse e esperar apoio',expectedValue:35});if(progression(state,club.id,p.position,g)>65||press>.72)out.push({kind:'clear',utility:24+src.attributes.decisions*.16+press*40+(club.tactics.mentality==='defensive'?16:0)+noise(state,src,'clear'),target:{x:p.position.x+sign*42,y:state.pitch.width/2+(Math.random()-.5)*24},risk:.22,reason:'afastar perigo imediato',expectedValue:28});return out}
function lookahead(state:MatchCoreState,club:Club,p:LivePlayer,src:Player,c:BallDecision){if(!c.target||!c.targetPlayerId)return c.utility;const receiver=teamOf(state,club.id).players.find(x=>x.playerId===c.targetPlayerId);if(!receiver)return c.utility;const secondShot=shotValue(state,club.players.find(x=>x.id===receiver.playerId)??src,receiver),control=territorialControlAt(state,c.target),own=club.id===state.home.clubId?control.home:control.away,progress=progression(state,club.id,p.position,c.target);return c.utility+secondShot*.18+own*14+Math.max(0,progress)*.25-c.risk*18}
export function decideOnBall(state:MatchCoreState,club:Club,p:LivePlayer):BallDecision{const src=club.players.find(x=>x.id===p.playerId);if(!src)return{kind:'hold',utility:0,risk:0,reason:'sem dados',expectedValue:0};const candidates=[...candidatePasses(state,club,p,src),...selfActions(state,club,p,src)];for(const c of candidates)c.utility=lookahead(state,club,p,src,c);candidates.sort((a,b)=>b.utility-a.utility);const best=candidates[0]??{kind:'hold',utility:0,risk:0,reason:'fallback',expectedValue:0};storeTrace(state,p,candidates,best.kind);return best}
function supportPoint(state:MatchCoreState,p:LivePlayer){const sign=advanceSign(state,p.clubId),ball=state.ball.position;return{x:clamp(ball.x-sign*7,2,state.pitch.length-2),y:clamp(ball.y+(p.homeSlot.y-state.pitch.width/2)*.25,2,state.pitch.width-2)}}
export function decideOffBall(state:MatchCoreState,club:Club,p:LivePlayer):OffBallDecision{const src=club.players.find(x=>x.id===p.playerId);if(!src)return{kind:'holdShape',utility:0,target:{...p.homeSlot},reason:'sem dados'};const own=state.possessionClubId===club.id,opp=state.possessionClubId&&state.possessionClubId!==club.id,ball=state.ball.position,d=distance(p.position,ball),sign=advanceSign(state,club.id),choices:OffBallDecision[]=[];choices.push({kind:'holdShape',utility:35+src.attributes.positioning*.32,target:{...p.homeSlot},reason:'preservar estrutura'});if(own){const sup=supportPoint(state,p);choices.push({kind:'support',utility:42+src.attributes.positioning*.25+src.attributes.decisions*.16-distance(p.position,sup)*.3,target:sup,reason:'criar linha de passe'});const run={x:clamp(p.position.x+sign*(9+src.attributes.pace*.05),2,state.pitch.length-2),y:clamp(p.position.y+(p.homeSlot.y-state.pitch.width/2)*.1,2,state.pitch.width-2)},space=territorialControlAt(state,run),ownSpace=club.id===state.home.clubId?space.home:space.away;choices.push({kind:'run',utility:src.attributes.pace*.24+src.attributes.positioning*.25+ownSpace*28+club.tactics.tempo*.12,target:run,reason:'atacar espaço futuro'});const intercept=bestInterception(state,p.clubId,1.8);if(intercept&&intercept.playerId===p.playerId)choices.push({kind:'receive',utility:72-src.attributes.decisions*.03,target:intercept.point,reason:'atacar trajetória prevista da bola'})}if(opp){const mark=markingInstruction(state,club,p.playerId);if(mark){const base=mark.urgency+src.attributes.positioning*.16+src.attributes.decisions*.12-(mark.communicationFailure?24:0);choices.push({kind:'cover',utility:base,target:{...mark.target},reason:mark.reason})}const press=club.tactics.pressing*.36+src.attributes.stamina*.18+src.attributes.tackling*.18+src.attributes.decisions*.12-d*.9-p.fatigue*.22;choices.push({kind:'press',utility:press,target:{...ball},reason:'pressionar portador/zona da bola'});const path=predictBallPath(state,2.2,.25),best=path.map(x=>({x,dist:distance(p.position,x.position)})).sort((a,b)=>(a.dist/(src.attributes.pace+35))- (b.dist/(src.attributes.pace+35)))[0];if(best)choices.push({kind:'intercept',utility:48+src.attributes.positioning*.25+src.attributes.decisions*.2-best.dist*.9,target:best.x.position,reason:'antecipar linha de passe'});choices.push({kind:'cover',utility:40+src.attributes.positioning*.32+club.tactics.defensiveLine*.1,target:{...p.homeSlot},reason:'proteger zona e companheiros'})}for(const c of choices)c.utility+=noise(state,src,`off-${c.kind}`);choices.sort((a,b)=>b.utility-a.utility);const best=choices[0];storeTrace(state,p,choices,best.kind);return best}
function storeTrace(state:MatchCoreState,p:LivePlayer,candidates:{kind:string;utility:number;reason:string}[],chosen:string){const any=state as any;if(!any.__decisionTrace)any.__decisionTrace=[] as DecisionTrace[];any.__decisionTrace.push({playerId:p.playerId,second:state.seconds,candidates:candidates.slice(0,6).map(c=>({kind:c.kind,utility:Number(c.utility.toFixed(2)),reason:c.reason})),chosen});if(any.__decisionTrace.length>400)any.__decisionTrace.splice(0,any.__decisionTrace.length-400)}
export function decisionTrace(state:MatchCoreState):DecisionTrace[]{return[...(((state as any).__decisionTrace??[]) as DecisionTrace[])]}
