import type { World } from './engine';
import { matchArchive, playerCareerStats, playerSeasonStats } from './match-season-history-v2';

export type RecordEntry={category:string;playerId?:string;clubId?:string;value:number;season?:number;matchId?:string;detail:string};
function allPlayerIds(world:World){return world.clubs.flatMap(c=>c.players.map(p=>p.id))}
function top<T>(xs:T[],score:(x:T)=>number,n=10){return [...xs].sort((a,b)=>score(b)-score(a)).slice(0,n)}
export function seasonLeaderboards(world:World,season=world.season){const rows=allPlayerIds(world).map(id=>playerSeasonStats(world,id,season)).filter(Boolean) as NonNullable<ReturnType<typeof playerSeasonStats>>[];return{goals:top(rows,r=>r.goals),assists:top(rows,r=>r.assists),ratings:top(rows.filter(r=>r.appearances>=5),r=>r.averageRating),cleanSheets:top(rows,r=>r.cleanSheets),saves:top(rows,r=>r.saves),keyPasses:top(rows,r=>r.keyPasses),motm:top(rows,r=>r.motm),hatTricks:top(rows,r=>r.hatTricks),discipline:top(rows,r=>r.yellowCards+r.redCards*3),errors:top(rows,r=>r.errorsLeadingToGoal+r.ownGoals)}}
export function careerLeaderboards(world:World){const rows=allPlayerIds(world).map(id=>playerCareerStats(world,id)).filter(Boolean) as NonNullable<ReturnType<typeof playerCareerStats>>[];return{goals:top(rows,r=>r.goals),assists:top(rows,r=>r.assists),appearances:top(rows,r=>r.appearances),minutes:top(rows,r=>r.minutes),cleanSheets:top(rows,r=>r.cleanSheets),hatTricks:top(rows,r=>r.hatTricks),motm:top(rows,r=>r.motm),ratings:top(rows.filter(r=>r.ratingCount>=10),r=>r.averageRating)}}
export function buildRecordBook(world:World):RecordEntry[]{const out:RecordEntry[]=[],seasons=new Set<number>();for(const id of allPlayerIds(world)){const c=playerCareerStats(world,id);if(!c)continue;for(const y of Object.keys(c.seasons).map(Number))seasons.add(y)}for(const season of seasons){const l=seasonLeaderboards(world,season),add=(category:string,row:any,value:number)=>{if(row)out.push({category,playerId:row.playerId,clubId:row.clubId,value,season,detail:`${category} na temporada ${season}`})};add('Mais gols em uma temporada',l.goals[0],l.goals[0]?.goals??0);add('Mais assistências em uma temporada',l.assists[0],l.assists[0]?.assists??0);add('Melhor média de rating',l.ratings[0],l.ratings[0]?.averageRating??0);add('Mais clean sheets',l.cleanSheets[0],l.cleanSheets[0]?.cleanSheets??0);add('Mais hat-tricks',l.hatTricks[0],l.hatTricks[0]?.hatTricks??0)}const c=careerLeaderboards(world),addCareer=(category:string,row:any,value:number)=>{if(row)out.push({category,playerId:row.playerId,value,detail:`Recorde de carreira: ${category}`})};addCareer('Gols',c.goals[0],c.goals[0]?.goals??0);addCareer('Assistências',c.assists[0],c.assists[0]?.assists??0);addCareer('Jogos',c.appearances[0],c.appearances[0]?.appearances??0);addCareer('Hat-tricks',c.hatTricks[0],c.hatTricks[0]?.hatTricks??0);for(const m of matchArchive(world))out.push({category:'Maior placar arquivado',clubId:m.homeGoals>=m.awayGoals?m.homeClubId:m.awayClubId,value:Math.max(m.homeGoals,m.awayGoals),season:m.season,matchId:m.id,detail:`${m.homeGoals}-${m.awayGoals}`});return out}
export function notableCareerMilestones(world:World,playerId:string){const c=playerCareerStats(world,playerId);if(!c)return[];const marks:{type:string;value:number}[]=[];for(const n of [1,50,100,200,300,500])if(c.appearances>=n)marks.push({type:'appearances',value:n});for(const n of [1,25,50,100,200,300,500])if(c.goals>=n)marks.push({type:'goals',value:n});for(const n of [1,25,50,100,200])if(c.assists>=n)marks.push({type:'assists',value:n});for(const n of [1,10,25,50,100])if(c.cleanSheets>=n)marks.push({type:'cleanSheets',value:n});return marks}
