import type { MatchCoreState,LivePlayer,Vec2 } from './match-core-v2';
import type { Player } from './engine';
import { matchOfficials,contextualVAR,addVARDelay,logOfficiating } from './match-officiating-v2';
import { teamOf } from './match-core-v2';
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
export type HandballContext={player:LivePlayer;playerData:Player;ballPosition:Vec2;ballSpeed:number;armExtension:number;armMovementTowardBall:number;distanceFromKick:number;deflectionBeforeContact:boolean;supportingArm:boolean;deliberate:boolean};
export type HandballDecision={contact:boolean;offence:boolean;insidePenaltyArea:boolean;penalty:boolean;card?:'yellow'|'red';confidence:number;varOverturn:boolean;reason:string};
export function evaluateHandball(state:MatchCoreState,c:HandballContext,rng=Math.random):HandballDecision{const defending=teamOf(state,c.player.clubId),ownGoalX=defending.attackingRight?0:state.pitch.length,inside=Math.abs(c.player.position.x-ownGoalX)<=state.pitch.penaltyAreaDepth&&Math.abs(c.player.position.y-state.pitch.width/2)<=state.pitch.penaltyAreaWidth/2,isGK=c.player.role==='goalkeeper'||c.player.role==='sweeperKeeper';if(isGK&&inside)return{contact:false,offence:false,insidePenaltyArea:true,penalty:false,confidence:100,varOverturn:false,reason:'Goleiro autorizado a jogar a bola com as mãos dentro da própria área.'};const proximity=clamp(100-c.distanceFromKick*10),unnatural=clamp(c.armExtension*.62+c.armMovementTowardBall*.48+(c.deliberate?35:0)-(c.deflectionBeforeContact?24:0)-(c.supportingArm?34:0)-proximity*.12),contactChance=clamp(8+c.armExtension*.32+c.ballSpeed*.9+c.armMovementTowardBall*.22),contact=rng()*100<contactChance;if(!contact)return{contact:false,offence:false,insidePenaltyArea:inside,penalty:false,confidence:75,varOverturn:false,reason:'Sem contato relevante entre bola e braço.'};const offenceScore=unnatural+(c.deliberate?24:0)+(c.armExtension>70?12:0),offence=offenceScore>47,ref=matchOfficials(state).referee,perceived=offence?(offenceScore+ref.strictness*.08+(rng()-.5)*(24-ref.consistency*.16)>48):false;let final=perceived,overturn=false;if(inside){const clearError=perceived!==offence?88:18,evidence=clamp(offenceScore*.65+contactChance*.2+ref.experience*.15),vr=contextualVAR(ref,{type:'penalty',onField:perceived?'given':'notGiven',evidence,clearError},rng);addVARDelay(state,vr.delaySeconds);logOfficiating(state,{kind:'handballVAR',playerId:c.player.playerId,offenceScore,physicalOffence:offence,...vr});if(vr.overturned){final=vr.final==='given';overturn=true}}const penalty=inside&&final,card=final&&c.deliberate&&offenceScore>82?'yellow':undefined;return{contact:true,offence:final,insidePenaltyArea:inside,penalty,card,confidence:clamp(55+Math.abs(offenceScore-47)),varOverturn:overturn,reason:!final?'Contato com braço considerado não punível.':c.deliberate?'Movimento deliberado do braço em direção à bola.':c.armExtension>62?'Braço ampliou de forma não natural o volume corporal.':'Mão punível pelo contexto do contato.'};}
export function applyHandballDecision(state:MatchCoreState,c:HandballContext,d:HandballDecision){if(!d.offence)return false;const team=teamOf(state,c.player.clubId),other=state.home.clubId===c.player.clubId?state.away:state.home;team.fouls++;if(d.card==='yellow'){c.player.yellowCards++;team.yellowCards++}state.ball.ownerId=undefined;state.possessionClubId=other.clubId;state.restart={type:d.penalty?'penalty':'freeKick',clubId:other.clubId,position:{...c.player.position}};logOfficiating(state,{kind:'handball',playerId:c.player.playerId,clubId:c.player.clubId,...d});return true;}
