import type { MatchCoreState, LivePlayer, Vec2 } from './match-core-v2';
import { opponentOf, teamOf } from './match-core-v2';
import { refereeForMatch, type RefereeProfile } from './match-rules-v2';

const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
export type AssistantRefereeProfile={id:string;positioning:number;fitness:number;concentration:number;experience:number;offsideAccuracy:number;touchlineAccuracy:number;communication:number};
export type MatchOfficials={referee:RefereeProfile;near:AssistantRefereeProfile;far:AssistantRefereeProfile;seed:number};
export type OffsideAssistantDecision={actualOffside:boolean;flagged:boolean;delayedFlag:boolean;margin:number;perceivedMargin:number;confidence:number;assistantError:boolean;varEligible:boolean};
export type BoundaryDecision={restart:'throwIn'|'corner'|'goalKick';clubId:string;confidence:number;assistantError:boolean};
export type VarReviewType='goal'|'penalty'|'redCard'|'mistakenIdentity'|'offside';
export type VarReviewOutcome={reviewed:boolean;type:VarReviewType;onField:'given'|'notGiven';final:'given'|'notGiven';overturned:boolean;recommendation:'checkComplete'|'overturn'|'onFieldReview';delaySeconds:number;confidence:number;clearObvious:number;reason:string};
function seeded(seed:number,n:number){const x=Math.sin(seed*17.173+n*91.711)*43758.5453;return x-Math.floor(x)}
export function assistantForMatch(seed:number,side:'near'|'far'):AssistantRefereeProfile{const o=side==='near'?41:73;return{id:`ar-${side}-${seed}`,positioning:Math.round(62+seeded(seed,o)*34),fitness:Math.round(58+seeded(seed,o+1)*38),concentration:Math.round(58+seeded(seed,o+2)*39),experience:Math.round(45+seeded(seed,o+3)*52),offsideAccuracy:Math.round(68+seeded(seed,o+4)*30),touchlineAccuracy:Math.round(70+seeded(seed,o+5)*28),communication:Math.round(55+seeded(seed,o+6)*42)};}
export function matchOfficials(state:MatchCoreState):MatchOfficials{const any=state as any;if(any.__matchOfficials)return any.__matchOfficials as MatchOfficials;const stableSeed=Number(any.__officialSeed??state.seed);any.__officialSeed=stableSeed;const crew={seed:stableSeed,referee:refereeForMatch(stableSeed),near:assistantForMatch(stableSeed,'near'),far:assistantForMatch(stableSeed,'far')};any.__matchOfficials=crew;return crew}
export function evaluateAssistantOffside(state:MatchCoreState,passer:LivePlayer,receiver:LivePlayer,ball:Vec2,assistant:AssistantRefereeProfile,rng=Math.random):OffsideAssistantDecision{const defending=opponentOf(state,passer.clubId),right=teamOf(state,passer.clubId).attackingRight,defs=defending.players.filter(p=>p.onPitch&&!p.sentOff).sort((a,b)=>a.position.x-b.position.x);if(defs.length<2)return{actualOffside:false,flagged:false,delayedFlag:false,margin:0,perceivedMargin:0,confidence:100,assistantError:false,varEligible:false};const line=right?defs[defs.length-2].position.x:defs[1].position.x,halfOk=right?receiver.position.x>state.pitch.length/2:receiver.position.x<state.pitch.length/2,margin=halfOk?(right?receiver.position.x-Math.max(line,ball.x):Math.min(line,ball.x)-receiver.position.x):-10,actualOffside=margin>.12;const quality=(assistant.positioning*.26+assistant.fitness*.12+assistant.concentration*.22+assistant.experience*.16+assistant.offsideAccuracy*.24)/100,noise=(rng()-.5)*(1-quality)*2.8,perceivedMargin=margin+noise,flagged=perceivedMargin>.12,close=Math.abs(perceivedMargin)<1.1,delayedFlag=flagged&&close&&assistant.experience+assistant.communication+rng()*35>130,confidence=clamp(55+Math.abs(perceivedMargin)*24+quality*30-(close?18:0)),assistantError=flagged!==actualOffside;return{actualOffside,flagged,delayedFlag,margin,perceivedMargin,confidence,assistantError,varEligible:close||assistantError};}
export function evaluateBoundaryDecision(state:MatchCoreState,lastTouch:LivePlayer|undefined,position:Vec2,assistant:AssistantRefereeProfile,rng=Math.random):BoundaryDecision{const sideOut=position.y<0||position.y>state.pitch.width,quality=(assistant.touchlineAccuracy*.45+assistant.positioning*.2+assistant.concentration*.2+assistant.experience*.15)/100,error=rng()>(.86+quality*.13);if(sideOut){let clubId=lastTouch?opponentOf(state,lastTouch.clubId).clubId:state.home.clubId;if(error&&lastTouch)clubId=lastTouch.clubId;return{restart:'throwIn',clubId,confidence:clamp(70+quality*25-(error?45:0)),assistantError:error};}const right=position.x>state.pitch.length,defending=right?(state.home.attackingRight?state.away:state.home):(state.home.attackingRight?state.home:state.away);let attacking=Boolean(lastTouch&&lastTouch.clubId!==defending.clubId);if(error)attacking=!attacking;return{restart:attacking?'corner':'goalKick',clubId:attacking?opponentOf(state,defending.clubId).clubId:defending.clubId,confidence:clamp(68+quality*27-(error?44:0)),assistantError:error};}
export function contextualVAR(ref:RefereeProfile,input:{type:VarReviewType;onField:'given'|'notGiven';evidence:number;clearError:number;offsideMargin?:number;identityConfidence?:number},rng=Math.random):VarReviewOutcome{const automatic=input.type==='goal'||input.type==='offside',eligible=automatic||input.type==='penalty'||input.type==='redCard'||input.type==='mistakenIdentity';if(!eligible)return{reviewed:false,type:input.type,onField:input.onField,final:input.onField,overturned:false,recommendation:'checkComplete',delaySeconds:0,confidence:0,clearObvious:0,reason:'Incident outside VAR protocol.'};const tech=input.type==='offside'?96:ref.varReliance*.42+ref.experience*.3+ref.consistency*.18+10,evidence=clamp(input.evidence*.62+tech*.38),margin=Math.abs(input.offsideMargin??99),objective=input.type==='offside'||input.type==='mistakenIdentity',clear=clamp(input.clearError+(objective?18:0)+(input.type==='offside'&&margin<.15?-8:0)),threshold=objective?58:72,overturned=clear+evidence*.16+rng()*8>threshold,recommendation:VarReviewOutcome['recommendation']=overturned?(objective?'overturn':'onFieldReview'):'checkComplete',final=overturned?(input.onField==='given'?'notGiven':'given'):input.onField,delaySeconds=Math.round((objective?22:48)+rng()*(objective?38:92)+(margin<.2?18:0));return{reviewed:true,type:input.type,onField:input.onField,final,overturned,recommendation,delaySeconds,confidence:evidence,clearObvious:clear,reason:overturned?(objective?'Objective evidence changed the on-field decision.':'Clear and obvious error: VAR recommends correction.'):'Check complete: insufficient evidence for intervention.'};}
export function addVARDelay(state:MatchCoreState,seconds:number){const any=state as any;any.__varDelaySeconds=(any.__varDelaySeconds??0)+Math.max(0,seconds)}
export function logOfficiating(state:MatchCoreState,event:any){const s=state as any;if(!s.__officiatingLog)s.__officiatingLog=[];s.__officiatingLog.push({second:state.seconds,...event});if(s.__officiatingLog.length>300)s.__officiatingLog.shift();}
export function officiatingLog(state:MatchCoreState){return[...((((state as any).__officiatingLog)??[]) as any[])]}
