import type { MatchCoreState, Vec2, LivePlayer } from './match-core-v2';
import { distance, livePlayer, teamOf, opponentOf } from './match-core-v2';
import { environmentEffects, inferEnvironment } from './match-environment-v2';

export type KickSpec={direction:Vec2;speed:number;lift?:number;spin?:number;ownerId?:string};
export type BallPrediction={position:Vec2;height:number;time:number};
export type InterceptionCandidate={player:LivePlayer;time:number;ballTime:number;margin:number;point:Vec2};
export type GoalFrameHit={kind:'leftPost'|'rightPost'|'crossbar';goalX:number;impactSpeed:number;position:Vec2;height:number};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const norm=(v:Vec2)=>{const m=Math.hypot(v.x,v.y)||1;return{x:v.x/m,y:v.y/m}};
function env(state:MatchCoreState){return((state as any).__environmentEffects??environmentEffects(inferEnvironment(state))) as ReturnType<typeof environmentEffects>}

export function kickBall(state:MatchCoreState,spec:KickSpec){const d=norm(spec.direction),e=env(state),speed=spec.speed*e.ballSpeed;state.ball.ownerId=undefined;state.ball.lastTouchId=spec.ownerId??state.ball.lastTouchId;state.ball.velocity={x:d.x*speed,y:d.y*speed};state.ball.verticalVelocity=(spec.lift??0)*(Math.sqrt(e.ballBounce));state.ball.spin=spec.spin??0;}
export function ballFriction(state:MatchCoreState){const surface=state.pitch.surface==='synthetic'?.992:state.pitch.surface==='hybrid'?.988:.984,wet=1+state.weather.rain*.0015,condition=.985+(state.pitch.condition/100)*.01,e=env(state),environmentDrag=clamp(.985+e.ballSpeed*.012,.972,.999);return clamp(surface*wet*condition*environmentDrag,.955,.998)}
function frameThreshold(state:MatchCoreState){return state.pitch.postRadius+state.pitch.ballRadius}
function crossedGoalPlane(prevX:number,nextX:number,goalX:number){return goalX===0?(prevX>0&&nextX<=0):(prevX<goalX&&nextX>=goalX)}
function goalFrameAt(state:MatchCoreState,prev:{x:number;y:number;height:number},next:{x:number;y:number;height:number},velocity:Vec2):GoalFrameHit|undefined{const goals=[0,state.pitch.length],half=state.pitch.goalWidth/2,centre=state.pitch.width/2,t=frameThreshold(state);for(const goalX of goals){if(!crossedGoalPlane(prev.x,next.x,goalX)&&Math.abs(next.x-goalX)>t)continue;const denom=next.x-prev.x,alpha=Math.abs(denom)>.0001?clamp((goalX-prev.x)/denom,0,1):1,y=prev.y+(next.y-prev.y)*alpha,h=prev.height+(next.height-prev.height)*alpha,speed=Math.hypot(velocity.x,velocity.y);if(Math.abs(y-(centre-half))<=t&&h<=state.pitch.goalHeight+t)return{kind:'leftPost',goalX,impactSpeed:speed,position:{x:goalX,y:centre-half},height:h};if(Math.abs(y-(centre+half))<=t&&h<=state.pitch.goalHeight+t)return{kind:'rightPost',goalX,impactSpeed:speed,position:{x:goalX,y:centre+half},height:h};if(y>=centre-half-t&&y<=centre+half+t&&Math.abs(h-state.pitch.goalHeight)<=t)return{kind:'crossbar',goalX,impactSpeed:speed,position:{x:goalX,y},height:state.pitch.goalHeight};}return undefined}
function logFrameHit(state:MatchCoreState,hit:GoalFrameHit){const any=state as any;if(!any.__goalFrameHits)any.__goalFrameHits=[];any.__goalFrameHits.push({...hit,second:state.seconds,lastTouchId:state.ball.lastTouchId});if(any.__goalFrameHits.length>160)any.__goalFrameHits.shift()}
function applyFrameBounce(state:MatchCoreState,hit:GoalFrameHit){const e=env(state),restitution=.68*e.ballBounce,side=hit.kind==='leftPost'?-1:hit.kind==='rightPost'?1:0;if(hit.kind==='crossbar'){state.ball.verticalVelocity=-Math.max(.9,Math.abs(state.ball.verticalVelocity)*restitution+hit.impactSpeed*.06);state.ball.velocity.x*=-.34;state.ball.velocity.y*=.84;state.ball.height=Math.min(state.pitch.goalHeight-state.pitch.ballRadius,state.ball.height)}else{state.ball.velocity.x*=-.48;state.ball.velocity.y=(state.ball.velocity.y+side*hit.impactSpeed*.34)*restitution;state.ball.verticalVelocity*=.72*e.ballBounce;state.ball.position.y=hit.position.y+side*frameThreshold(state)*1.05}state.ball.spin+=(side||1)*.35;state.ball.position.x=hit.goalX===0?frameThreshold(state):state.pitch.length-frameThreshold(state);logFrameHit(state,hit)}
export function evaluateGoalFrameTrajectory(state:MatchCoreState,target:Vec2,targetHeight:number,speed:number){const half=state.pitch.goalWidth/2,centre=state.pitch.width/2,t=frameThreshold(state),postDelta=Math.min(Math.abs(target.y-(centre-half)),Math.abs(target.y-(centre+half))),barDelta=Math.abs(targetHeight-state.pitch.goalHeight);if(postDelta<=t&&targetHeight<=state.pitch.goalHeight+t)return{hit:true,kind:(Math.abs(target.y-(centre-half))<Math.abs(target.y-(centre+half))?'leftPost':'rightPost') as GoalFrameHit['kind'],reboundSeverity:clamp(speed/32,.35,.95)};if(target.y>=centre-half-t&&target.y<=centre+half+t&&barDelta<=t)return{hit:true,kind:'crossbar' as const,reboundSeverity:clamp(speed/30,.4,.98)};return{hit:false as const};}
export function stepFreeBall(state:MatchCoreState,dt:number){if(state.ball.ownerId){const p=livePlayer(state,state.ball.ownerId);if(p){state.ball.position={...p.position};state.ball.velocity={...p.velocity};state.ball.height=0;state.ball.verticalVelocity=0;}return;}const e=env(state),f=Math.pow(ballFriction(state),dt*4),wind=state.weather.wind*.0025,wx=Math.cos(state.weather.windDirection)*wind,wy=Math.sin(state.weather.windDirection)*wind,prev={x:state.ball.position.x,y:state.ball.position.y,height:state.ball.height};(state as any).__lastBallPhysicsPosition={...prev};state.ball.position.x+=state.ball.velocity.x*dt;state.ball.position.y+=state.ball.velocity.y*dt;state.ball.height=Math.max(0,state.ball.height+state.ball.verticalVelocity*dt);const hit=goalFrameAt(state,prev,{x:state.ball.position.x,y:state.ball.position.y,height:state.ball.height},state.ball.velocity);if(hit)applyFrameBounce(state,hit);state.ball.velocity.x=(state.ball.velocity.x+wx*dt)*f;state.ball.velocity.y=(state.ball.velocity.y+wy*dt)*f;state.ball.verticalVelocity-=9.81*dt;if(state.ball.height<=0&&state.ball.verticalVelocity<0){state.ball.height=0;state.ball.verticalVelocity*=-.38*e.ballBounce;state.ball.velocity.x*=.93*e.ballSpeed;state.ball.velocity.y*=.93*e.ballSpeed;}if(Math.hypot(state.ball.velocity.x,state.ball.velocity.y)<.12){state.ball.velocity={x:0,y:0}}}
export function predictBall(state:MatchCoreState,horizon=4,dt=.1):BallPrediction[]{const result:BallPrediction[]=[],copy={position:{...state.ball.position},velocity:{...state.ball.velocity},height:state.ball.height,verticalVelocity:state.ball.verticalVelocity};let t=0;const e=env(state),f=Math.pow(ballFriction(state),dt*4);while(t<=horizon){result.push({position:{...copy.position},height:copy.height,time:t});copy.position.x+=copy.velocity.x*dt;copy.position.y+=copy.velocity.y*dt;copy.height=Math.max(0,copy.height+copy.verticalVelocity*dt);copy.velocity.x*=f;copy.velocity.y*=f;copy.verticalVelocity-=9.81*dt;if(copy.height<=0&&copy.verticalVelocity<0){copy.height=0;copy.verticalVelocity*=-.38*e.ballBounce;copy.velocity.x*=.93*e.ballSpeed;copy.velocity.y*=.93*e.ballSpeed}t+=dt}return result}
function playerReachTime(p:LivePlayer,point:Vec2,pace:number){const maxSpeed=4.7+pace*.035,turn=Math.abs(Math.atan2(point.y-p.position.y,point.x-p.position.x)-p.facing),turnPenalty=Math.min(Math.PI,Math.abs(Math.atan2(Math.sin(turn),Math.cos(turn))))*.12;return distance(p.position,point)/Math.max(2.6,maxSpeed*(1-p.fatigue*.004))+turnPenalty}
export function interceptionCandidates(state:MatchCoreState,clubId:string,paceOf:(id:string)=>number,horizon=4){const predicted=predictBall(state,horizon,.12),team=teamOf(state,clubId),out:InterceptionCandidate[]=[];for(const p of team.players.filter(x=>x.onPitch&&!x.sentOff)){let best:InterceptionCandidate|undefined;for(const b of predicted){if(b.height>2.2)continue;const pt=playerReachTime(p,b.position,paceOf(p.playerId)),margin=b.time-pt;if(margin<-.15)continue;const c={player:p,time:pt,ballTime:b.time,margin,point:{...b.position}};if(!best||c.ballTime<best.ballTime)best=c}if(best)out.push(best)}return out.sort((a,b)=>a.ballTime-b.ballTime||b.margin-a.margin)}
export function passingLaneRisk(state:MatchCoreState,from:Vec2,to:Vec2,attackingClubId:string){const defenders=opponentOf(state,attackingClubId).players.filter(x=>x.onPitch&&!x.sentOff),dx=to.x-from.x,dy=to.y-from.y,len2=dx*dx+dy*dy||1;let risk=0;for(const d of defenders){const t=clamp(((d.position.x-from.x)*dx+(d.position.y-from.y)*dy)/len2,0,1),px=from.x+dx*t,py=from.y+dy*t,dist=Math.hypot(d.position.x-px,d.position.y-py),central=1-Math.abs(t-.5)*1.2;risk+=Math.max(0,1-dist/5.5)*Math.max(.2,central)}return clamp(risk/Math.max(1,defenders.length*.18),0,1)}
export function tryClaimLooseBall(state:MatchCoreState,paceOf:(id:string)=>number){if(state.ball.ownerId||state.ball.height>1.8)return;const home=interceptionCandidates(state,state.home.clubId,paceOf,1.3)[0],away=interceptionCandidates(state,state.away.clubId,paceOf,1.3)[0],pick=!home?away:!away?home:home.ballTime<away.ballTime?home:away;if(!pick||pick.ballTime>.8)return;state.ball.ownerId=pick.player.playerId;state.ball.position={...pick.player.position};state.ball.velocity={...pick.player.velocity};state.possessionClubId=pick.player.clubId;}
export const passInterceptionRisk=passingLaneRisk;
export const predictBallPath=predictBall;
export function bestInterception(state:MatchCoreState,clubId:string,horizon=2){const best=interceptionCandidates(state,clubId,()=>65,horizon)[0];return best?{playerId:best.player.playerId,point:best.point,time:best.ballTime,margin:best.margin}:undefined;}
export function goalFrameHitLog(state:MatchCoreState):GoalFrameHit[]{return[...((((state as any).__goalFrameHits)??[]) as GoalFrameHit[])]}
