import type { Player } from './engine';
import type { LivePlayer, MatchCoreState } from './match-core-v2';

export type ContactMechanism='ankle'|'knee'|'lowerLeg'|'thigh'|'hip'|'shoulder'|'head'|'muscle';
export type MatchInjurySeverity='knock'|'minor'|'moderate'|'severe';
export type MatchInjury={playerId:string;clubId:string;second:number;mechanism:ContactMechanism;severity:MatchInjurySeverity;forcedOff:boolean;performancePenalty:number;estimatedDays:number;concussion:boolean;source:'foul'|'duel'|'sprint'|'landing'};
export type InjuryContact={victim:LivePlayer;victimData:Player;impact:number;relativeSpeed:number;fromBehind:boolean;studsUp:boolean;airborne:boolean;fatigue:number;source:MatchInjury['source']};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function mechanism(c:InjuryContact,r:number):ContactMechanism{if(c.airborne&&r<.38)return'head';if(c.studsUp)return r<.55?'lowerLeg':'ankle';if(c.fromBehind)return r<.45?'ankle':'knee';if(c.source==='sprint')return r<.6?'muscle':'thigh';return r<.2?'ankle':r<.38?'knee':r<.6?'lowerLeg':r<.78?'thigh':'shoulder'}
export function evaluateContactInjury(state:MatchCoreState,c:InjuryContact,rng=Math.random):MatchInjury|undefined{const condition=clamp(c.victim.condition),load=c.fatigue*.32+(100-condition)*.22+c.relativeSpeed*4.2+c.impact*.34+(c.fromBehind?9:0)+(c.studsUp?18:0)+(c.airborne?6:0);const probability=clamp((load-43)/150,.002,.32);if(rng()>probability)return;const mech=mechanism(c,rng()),trauma=load+rng()*28,severity:MatchInjurySeverity=trauma>105?'severe':trauma>84?'moderate':trauma>66?'minor':'knock',concussion=mech==='head'&&trauma>72,forcedOff=concussion||severity==='severe'||(severity==='moderate'&&rng()<.62),performancePenalty=severity==='knock'?8:severity==='minor'?18:severity==='moderate'?38:70,estimatedDays=severity==='knock'?0:severity==='minor'?1+Math.round(rng()*6):severity==='moderate'?7+Math.round(rng()*28):30+Math.round(rng()*120);const injury={playerId:c.victim.playerId,clubId:c.victim.clubId,second:state.seconds,mechanism:mech,severity,forcedOff,performancePenalty,estimatedDays,concussion,source:c.source};const any=state as any;if(!any.__matchInjuries)any.__matchInjuries=[];any.__matchInjuries.push(injury);c.victim.condition=clamp(c.victim.condition-performancePenalty,0,100);if(forcedOff)c.victim.currentIntent='holdShape';return injury}
export function matchInjuries(state:MatchCoreState):MatchInjury[]{return[...((((state as any).__matchInjuries??[]) as MatchInjury[]))]}
