import type { Club,Player } from './engine';
import type { MatchCoreState } from './match-core-v2';
import { livePlayer } from './match-core-v2';
import { applyEnvironmentTick,environmentEffects,inferEnvironment } from './match-environment-v2';
import { applyHandballDecision,evaluateHandball } from './match-handball-v2';
import { updateAdvantage } from './match-advantage-v2';
const map=(c:Club)=>new Map(c.players.map(p=>[p.id,p]));
export function prepareMatchContext(state:MatchCoreState){const env=inferEnvironment(state);(state as any).__environment=env;(state as any).__environmentEffects=environmentEffects(env);return env;}
export function stepMatchContext(state:MatchCoreState,home:Club,away:Club,rng=Math.random){const effects=applyEnvironmentTick(state,map(home),map(away),rng);state.memory.homePressure=effects.homePressure;state.memory.awayPressure=effects.awayPressure;updateAdvantage(state);return effects;}
export function maybeResolveHandball(state:MatchCoreState,home:Club,away:Club,rng=Math.random){if(state.restart||state.ball.ownerId||state.ball.height<.55||state.ball.height>1.95)return false;const speed=Math.hypot(state.ball.velocity.x,state.ball.velocity.y);if(speed<5)return false;const candidates=[...state.home.players,...state.away.players].filter(p=>p.onPitch&&!p.sentOff&&Math.hypot(p.position.x-state.ball.position.x,p.position.y-state.ball.position.y)<.72);if(!candidates.length)return false;const p=candidates.sort((a,b)=>Math.hypot(a.position.x-state.ball.position.x,a.position.y-state.ball.position.y)-Math.hypot(b.position.x-state.ball.position.x,b.position.y-state.ball.position.y))[0],club=p.clubId===home.id?home:away,data=club.players.find(x=>x.id===p.playerId) as Player|undefined;if(!data)return false;const armExtension=20+rng()*70,armMovementTowardBall=rng()*100,deflectionBeforeContact=rng()<.18,supportingArm=p.currentIntent==='tackle'&&rng()<.25,deliberate=armMovementTowardBall>82&&rng()<.35,d=evaluateHandball(state,{player:p,playerData:data,ballPosition:{...state.ball.position},ballSpeed:speed,armExtension,armMovementTowardBall,distanceFromKick:Math.min(20,speed*.55),deflectionBeforeContact,supportingArm,deliberate},rng);return applyHandballDecision(state,{player:p,playerData:data,ballPosition:{...state.ball.position},ballSpeed:speed,armExtension,armMovementTowardBall,distanceFromKick:Math.min(20,speed*.55),deflectionBeforeContact,supportingArm,deliberate},d);}
