import type { MatchStory, MatchStoryAction } from './matchday-story-v1';

const reduceMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches??false;
const timers=new WeakMap<HTMLElement,number[]>();

function clear(center:HTMLElement){for(const t of timers.get(center)??[])window.clearTimeout(t);timers.set(center,[]);center.querySelectorAll('.md-sequence-label,.md-sequence-path').forEach(n=>n.remove())}
function remember(center:HTMLElement,id:number){const list=timers.get(center)??[];list.push(id);timers.set(center,list)}
function playerEl(center:HTMLElement,id?:string){return id?center.querySelector<HTMLElement>(`[data-live-player="${CSS.escape(id)}"]`):null}
function movePlayer(el:HTMLElement|undefined|null,to:{x:number;y:number},duration:number){if(!el||reduceMotion)return;el.animate([{left:el.style.left,top:el.style.top},{left:`${to.x}%`,top:`${to.y}%`}],{duration,easing:'cubic-bezier(.2,.72,.2,1)',fill:'none'})}
function drawPath(pitch:HTMLElement,a:MatchStoryAction,duration:number){const dx=a.to.x-a.from.x,dy=a.to.y-a.from.y,dist=Math.hypot(dx,dy);if(dist<1)return;const line=document.createElement('i');line.className=`md-sequence-path ${a.type}`;line.style.left=`${a.from.x}%`;line.style.top=`${a.from.y}%`;line.style.width=`${dist}%`;line.style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;line.style.setProperty('--md-seq-duration',`${duration}ms`);pitch.appendChild(line);window.setTimeout(()=>line.remove(),duration+180)}
function label(pitch:HTMLElement,a:MatchStoryAction){const el=document.createElement('span');el.className=`md-sequence-label ${a.type}`;el.style.left=`${a.to.x}%`;el.style.top=`${a.to.y}%`;el.textContent=a.label;pitch.appendChild(el);window.setTimeout(()=>el.remove(),900)}
function runAction(center:HTMLElement,story:MatchStory,a:MatchStoryAction,duration:number,index:number){const pitch=center.querySelector<HTMLElement>('.md-live-pitch'),ball=pitch?.querySelector<HTMLElement>('.md-ball');if(!pitch||!ball)return;drawPath(pitch,a,duration);label(pitch,a);movePlayer(playerEl(center,a.playerId),a.from,Math.min(260,duration*.4));movePlayer(playerEl(center,a.targetPlayerId),a.to,duration);if(!reduceMotion){ball.animate([{left:`${a.from.x}%`,top:`${a.from.y}%`,transform:'translate(-50%,-50%) scale(1)'},{left:`${a.to.x}%`,top:`${a.to.y}%`,transform:`translate(-50%,-50%) scale(${a.type==='shot'||a.type==='goal'?1.22:1.08})`}],{duration,easing:a.type==='shot'||a.type==='goal'?'cubic-bezier(.15,.75,.15,1)':'cubic-bezier(.3,.7,.25,1)',fill:'none'})}pitch.dataset.sequenceAction=a.type;center.dataset.sequenceActor=a.playerId??'';document.dispatchEvent(new CustomEvent('touchline:match-action',{detail:{center,story,action:a,index,total:story.actions.length}}))}
function play(center:HTMLElement,story:MatchStory,speed:number){clear(center);if(!story.actions.length)return;const total=Math.max(700,Math.min(1900,1150/story.actions.length))*story.actions.length/Math.max(.5,speed);const step=Math.max(180,total/story.actions.length);story.actions.forEach((a,i)=>remember(center,window.setTimeout(()=>runAction(center,story,a,Math.max(170,step*.82),i),i*step)))}

document.addEventListener('touchline:match-story',e=>{const detail=(e as CustomEvent<{story:MatchStory;speed:number;center:HTMLElement|null}>).detail;if(!detail?.center||!detail.story)return;play(detail.center,detail.story,detail.speed||1)});
