import type { MatchCoreState, Vec2 } from './match-core-v2';
import { matchEventLedger } from './match-event-ledger-v2';
import { receptionLog } from './match-first-touch-v2';
import { officiatingLog } from './match-officiating-v2';
import { goalFrameHitLog } from './match-ball-physics-v2';
export type ActionMapType='shot'|'reception'|'foul'|'frameHit'|'goal';
export type ActionMapPoint={second:number;type:ActionMapType;playerId?:string;clubId?:string;position:Vec2;value?:number;success?:boolean;detail?:string};
function point(value:unknown):Vec2|undefined{const p=value as Partial<Vec2>|undefined;return p&&Number.isFinite(p.x)&&Number.isFinite(p.y)?{x:Number(p.x),y:Number(p.y)}:undefined}
export function matchActionMap(state:MatchCoreState):ActionMapPoint[]{const out:ActionMapPoint[]=[];const ledger=matchEventLedger(state),goals=new Set(ledger.filter(e=>e.type==='goal'||e.type==='physicalGoal').map(e=>`${e.second}:${e.playerId??''}`));for(const e of ledger.filter(e=>e.type==='shot')){const position=point(e.meta?.position);if(!position)continue;const goal=goals.has(`${e.second}:${e.playerId??''}`);out.push({second:e.second,type:goal?'goal':'shot',playerId:e.playerId,clubId:e.clubId,position,value:e.xg,success:goal,detail:e.detail})}for(const r of receptionLog(state)){const position=point(r.nextPosition);if(!position)continue;const p=[...state.home.players,...state.away.players].find(x=>x.playerId===r.playerId);out.push({second:Number(r.second??0),type:'reception',playerId:r.playerId,clubId:p?.clubId,position,value:r.control,success:r.success,detail:r.type})}for(const e of officiatingLog(state)){if(!e.foul||!e.victimId)continue;const position=point(e.position);if(!position)continue;const victim=[...state.home.players,...state.away.players].find(x=>x.playerId===e.victimId);out.push({second:Number(e.second??0),type:'foul',playerId:e.tacklerId,clubId:victim?.clubId===state.home.clubId?state.away.clubId:state.home.clubId,position,success:false,detail:e.reason??e.kind})}for(const h of goalFrameHitLog(state)){const position=point(h.position);if(position)out.push({second:Number((h as any).second??0),type:'frameHit',position,value:h.impactSpeed,success:false,detail:h.kind})}return out.sort((a,b)=>a.second-b.second)}
export function playerActionMap(state:MatchCoreState,playerId:string){return matchActionMap(state).filter(x=>x.playerId===playerId)}