import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, livePlayer, opponentOf, teamOf } from './match-core-v2';
import { applySubstitution, defaultCompetitionRules, legalMatchContinuation, suggestSubstitution } from './match-rules-v2';
import { decideOffBall, decideOnBall, type BallDecision } from './match-decision-ai-v2';
import { roleMovementTarget } from './match-role-behaviour-v2';
import { kickBall, stepFreeBall } from './match-ball-physics-v2';
import { evaluateReception, applyReception } from './match-first-touch-v2';
import { resolveAerialDuel, applyAerialResult } from './match-aerial-duel-v2';
import { resolveDefensiveContact } from './match-contact-resolver-v2';
import { executeRestartV2 } from './match-set-piece-runtime-v2';
import { resolveShotV2, applyShotResolution } from './match-goalkeeper-resolution-v2';
import { competitionPhaseUpdate, stepShootout, type KnockoutContext } from './match-time-competition-v2';
import { addVARDelay, contextualVAR, evaluateAssistantOffside, evaluateBoundaryDecision, logOfficiating, matchOfficials, officiatingLog } from './match-officiating-v2';
import { beginMatchLifecycle, syncMatchLifecycle } from './match-lifecycle-v2';
import { detectPhysicalGoal } from './match-goal-line-v2';
import { maybeResolveHandball, prepareMatchContext, stepMatchContext } from './match-context-bridge-v2';

const DT=.25;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function rng(s:MatchCoreState){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function norm(v:Vec2){const m=Math.hypot(v.x,v.y)||1;return{x:v.x/m,y:v.y/m}}
function player(c:Club,id:string){return c.players.find(p=>p.id===id)}
function hasBall(s:MatchCoreState,p:LivePlayer){return s.ball.ownerId===p.playerId}
function nearestOpponent(s:MatchCoreState,p:LivePlayer){return opponentOf(s,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff).sort((a,b)=>distance(p.position,a.position)-distance(p.position,b.position))[0]}
function separation(s:MatchCoreState,p:LivePlayer){let x=0,y=0;for(const q of [...s.home.players,...s.away.players]){if(q.playerId===p.playerId||!q.onPitch||q.sentOff)continue;const d=distance(p.position,q.position);if(d>0&&d<1.25){x+=(p.position.x-q.position.x)/d*(1.25-d);y+=(p.position.y-q.position.y)/d*(1.25-d)}}return{x:x*1.8,y:y*1.8}}
function steering(s:MatchCoreState,p:LivePlayer,target:Vec2,maxSpeed:number,intensity=1){const d=norm({x:target.x-p.position.x,y:target.y-p.position.y}),sep=separation(s,p),speed=maxSpeed*(1-p.fatigue*.004)*intensity,vx=d.x*speed+sep.x,vy=d.y*speed+sep.y;p.velocity={x:vx,y:vy};if(Math.hypot(vx,vy)>.05)p.facing=Math.atan2(vy,vx);p.position.x=clamp(p.position.x+vx*DT,.5,s.pitch.length-.5);p.position.y=clamp(p.position.y+vy*DT,.5,s.pitch.width-.5);p.fatigue=clamp(p.fatigue+Math.hypot(vx,vy)*.00065*(p.currentIntent==='press'?1.55:p.currentIntent==='run'?1.25:1),0,100)}
function movePlayers(s:MatchCoreState,home:Club,away:Club){for(const p of [...s.home.players,...s.away.players]){if(!p.onPitch||p.sentOff)continue;const c=p.clubId===home.id?home:away,src=player(c,p.playerId);if(!src)continue;if(hasBall(s,p)){const d=decideOnBall(s,c,p);p.currentIntent=d.kind==='shoot'?'shoot':d.kind==='carry'||d.kind==='dribble'?'carry':d.kind==='cross'?'cross':d.kind==='hold'?'receive':'pass';let target=d.target??roleMovementTarget(s,c,p);if(d.kind==='hold')target={...p.position};steering(s,p,target,4.6+src.attributes.pace*.034,d.kind==='carry'||d.kind==='dribble'?1.02:.82)}else{const d=decideOffBall(s,c,p);p.currentIntent=d.kind==='holdShape'?'holdShape':d.kind;const roleTarget=roleMovementTarget(s,c,p);const blend=(d.kind==='holdShape'||d.kind==='cover') ? .65 : d.kind==='support' ? .35 : .15;const target={x:roleTarget.x*blend+d.target.x*(1-blend),y:roleTarget.y*blend+d.target.y*(1-blend)};steering(s,p,target,4.55+src.attributes.pace*.034,d.kind==='press'||d.kind==='intercept'||d.kind==='run'?1.05:.9)}}}
function executePass(s:MatchCoreState,c:Club,from:LivePlayer,d:BallDecision,src:Player){const t=teamOf(s,c.id),to=d.targetPlayerId?t.players.find(x=>x.playerId===d.targetPlayerId):undefined;if(!to||!d.target)return;t.attemptedPasses++;const crew=matchOfficials(s),ar=from.position.y<s.pitch.width/2?crew.near:crew.far,off=evaluateAssistantOffside(s,from,to,s.ball.position,ar,()=>rng(s));if(off.flagged&&!off.delayedFlag){t.offsides++;s.ball.ownerId=undefined;s.possessionClubId=opponentOf(s,c.id).clubId;s.restart={type:'freeKick',clubId:s.possessionClubId,position:{...to.position},indirect:true};logOfficiating(s,{kind:'offside',assistantId:ar.id,receiverId:to.playerId,...off});return}if(off.delayedFlag||off.assistantError){const vr=contextualVAR(crew.referee,{type:'offside',onField:off.flagged?'given':'notGiven',evidence:off.confidence,clearError:off.assistantError?92:28,offsideMargin:off.margin},()=>rng(s));logOfficiating(s,{kind:'offsideCheck',assistantId:ar.id,receiverId:to.playerId,...off,var:vr});addVARDelay(s,vr.delaySeconds);if(vr.final==='given'){t.offsides++;s.ball.ownerId=undefined;s.possessionClubId=opponentOf(s,c.id).clubId;s.restart={type:'freeKick',clubId:s.possessionClubId,position:{...to.position},indirect:true};return}}const range=distance(from.position,d.target),base=.5+src.attributes.passing*.0038+src.attributes.decisions*.0022-d.risk*.46-range*.0035,quality=clamp(base,.08,.96),kindSpeed=d.kind==='shortPass'?13:d.kind==='progressivePass'?17:d.kind==='throughBall'?19:d.kind==='switchPlay'?22:d.kind==='longBall'?24:18,lift=d.kind==='longBall'||d.kind==='switchPlay'?4.2:d.kind==='throughBall'?1.3:.25;if(rng(s)<quality){t.completedPasses++;t.passSuccess=t.completedPasses/Math.max(1,t.attemptedPasses)*100}const error=(1-quality)*(rng(s)-.5)*8,target={x:d.target.x+(rng(s)-.5)*Math.abs(error),y:d.target.y+(rng(s)-.5)*Math.abs(error)},dir={x:target.x-from.position.x,y:target.y-from.position.y};kickBall(s,{direction:dir,speed:kindSpeed,lift,spin:(rng(s)-.5)*.8,ownerId:from.playerId});s.possessionClubId=undefined;s.memory.recentPossessions.push(c.id);if(s.memory.recentPossessions.length>30)s.memory.recentPossessions.shift()}
function executeCross(s:MatchCoreState,c:Club,p:LivePlayer,d:BallDecision,src:Player){const t=teamOf(s,c.id);t.attemptedPasses++;const boxTarget=d.target??{x:teamOf(s,c.id).attackingRight?s.pitch.length-8:8,y:s.pitch.width/2+(rng(s)-.5)*12},accuracy=clamp(.35+src.attributes.passing*.003+src.attributes.technique*.002-d.risk*.28,.15,.82),target={x:boxTarget.x+(rng(s)-.5)*(1-accuracy)*12,y:boxTarget.y+(rng(s)-.5)*(1-accuracy)*10};kickBall(s,{direction:{x:target.x-p.position.x,y:target.y-p.position.y},speed:20,lift:5.5,spin:(rng(s)-.5)*1.4,ownerId:p.playerId});s.possessionClubId=undefined}
function executeClear(s:MatchCoreState,c:Club,p:LivePlayer,d:BallDecision){const target=d.target??{x:p.position.x+(teamOf(s,c.id).attackingRight?45:-45),y:s.pitch.width/2};kickBall(s,{direction:{x:target.x-p.position.x,y:target.y-p.position.y},speed:26,lift:6.2,spin:(rng(s)-.5),ownerId:p.playerId});s.possessionClubId=undefined}
function shoot(s:MatchCoreState,c:Club,oppClub:Club,p:LivePlayer,src:Player){const resolution=resolveShotV2(s,c,oppClub,p,src,()=>rng(s));if(resolution.goal){const recent=officiatingLog(s).filter((e:any)=>s.seconds-e.second<12),suspicious=recent.find((e:any)=>e.kind==='offsideCheck'&&e.actualOffside&&e.var?.final==='notGiven'),vr=contextualVAR(matchOfficials(s).referee,{type:'goal',onField:'given',evidence:suspicious?82:96,clearError:suspicious?88:5,offsideMargin:undefined},()=>rng(s));addVARDelay(s,vr.delaySeconds);logOfficiating(s,{kind:'goalCheck',shooterId:p.playerId,var:vr,antecedent:suspicious?.kind});if(vr.final==='notGiven')resolution.goal=false}applyShotResolution(s,c,oppClub,p,resolution)}
function dribbleDuel(s:MatchCoreState,c:Club,p:LivePlayer,src:Player){const opp=nearestOpponent(s,p);if(!opp||distance(p.position,opp.position)>2.1){s.ball.position={...p.position};return}const attack=src.attributes.technique*.48+src.attributes.pace*.28+src.attributes.decisions*.14+src.morale*.1+rng(s)*22,defense=55*.48+55*.24+55*.14+rng(s)*24;if(attack>=defense){p.fatigue=clamp(p.fatigue+.12,0,100);s.ball.position={...p.position};return}s.ball.ownerId=opp.playerId;s.ball.position={...opp.position};s.possessionClubId=opp.clubId}
function executeBallActions(s:MatchCoreState,home:Club,away:Club){for(const p of [...s.home.players,...s.away.players]){if(!p.onPitch||p.sentOff||!hasBall(s,p))continue;const c=p.clubId===home.id?home:away,opp=p.clubId===home.id?away:home,src=player(c,p.playerId);if(!src)continue;const d=decideOnBall(s,c,p);if(d.kind==='shoot'){shoot(s,c,opp,p,src);continue}if(['shortPass','progressivePass','throughBall','switchPlay','longBall'].includes(d.kind)){executePass(s,c,p,d,src);continue}if(d.kind==='cross'){executeCross(s,c,p,d,src);continue}if(d.kind==='clear'){executeClear(s,c,p,d);continue}if(d.kind==='dribble'){dribbleDuel(s,c,p,src);continue}if(d.kind==='carry'){s.ball.position={...p.position};s.ball.velocity={...p.velocity};continue}if(d.kind==='hold'){s.ball.position={...p.position};s.ball.velocity={x:0,y:0}}}}
function resolveContact(s:MatchCoreState,home:Club,away:Club){if(!s.ball.ownerId)return;const attacker=livePlayer(s,s.ball.ownerId);if(!attacker)return;const defender=nearestOpponent(s,attacker);if(!defender||distance(attacker.position,defender.position)>1.45)return;const dc=defender.clubId===home.id?home:away,ac=attacker.clubId===home.id?home:away,defData=player(dc,defender.playerId),attData=player(ac,attacker.playerId);if(!defData||!attData)return;const result=resolveDefensiveContact(s,defender,attacker,defData,attData,()=>rng(s));if(result.wonBall){s.ball.ownerId=defender.playerId;s.ball.position={...defender.position};s.ball.velocity={...defender.velocity};s.possessionClubId=defender.clubId}}
function resolveFreeBall(s:MatchCoreState,home:Club,away:Club){if(s.ball.ownerId||s.restart)return;const all=[...s.home.players,...s.away.players].filter(p=>p.onPitch&&!p.sentOff);if(s.ball.height>=1.15){const near=all.filter(p=>distance(p.position,s.ball.position)<3.2);const duel=resolveAerialDuel(s,home,away,near,()=>rng(s));if(duel){applyAerialResult(s,duel);return}}if(s.ball.height>1.05)return;const near=all.filter(p=>distance(p.position,s.ball.position)<1.55).sort((a,b)=>distance(a.position,s.ball.position)-distance(b.position,s.ball.position));const p=near[0];if(!p)return;const club=p.clubId===home.id?home:away,ballSpeed=Math.hypot(s.ball.velocity.x,s.ball.velocity.y),out=evaluateReception(s,club,p,ballSpeed,s.ball.height,()=>rng(s));applyReception(s,out)}
function boundaryRestart(s:MatchCoreState){if(s.ball.ownerId||s.restart)return;const x=s.ball.position.x,y=s.ball.position.y;if(y>=0&&y<=s.pitch.width&&x>=0&&x<=s.pitch.length)return;const last=s.ball.lastTouchId?livePlayer(s,s.ball.lastTouchId):undefined,crew=matchOfficials(s),assistant=y<s.pitch.width/2?crew.near:crew.far,decision=evaluateBoundaryDecision(s,last,{x,y},assistant,()=>rng(s));logOfficiating(s,{kind:'boundary',assistantId:assistant.id,position:{x,y},lastTouchId:last?.playerId,...decision});if(decision.restart==='throwIn'){s.restart={type:'throwIn',clubId:decision.clubId,position:{x:clamp(x,0,s.pitch.length),y:clamp(y,0,s.pitch.width)}}}else if(decision.restart==='corner'){teamOf(s,decision.clubId).corners++;s.restart={type:'corner',clubId:decision.clubId,position:{x:x>s.pitch.length?s.pitch.length:0,y:y<s.pitch.width/2?0:s.pitch.width}}}else{s.restart={type:'goalKick',clubId:decision.clubId,position:{x:x>s.pitch.length?s.pitch.length-5.5:5.5,y:s.pitch.width/2}};s.ball.velocity={x:0,y:0}}}
export function stepMatch(s:MatchCoreState,home:Club,away:Club,knockout:KnockoutContext={requiresWinner:false}){if(s.phase==='finished'){syncMatchLifecycle(s);return s}if(s.phase==='preKickoff'){matchOfficials(s);prepareMatchContext(s);const starter=rng(s)<.5?s.home:s.away;beginMatchLifecycle(s,starter.clubId)}if(s.restart)executeRestartV2(s,home,away);competitionPhaseUpdate(s,knockout);syncMatchLifecycle(s);if(s.phase==='penalties'){stepShootout(s,home,away);s.seconds+=15;s.tick++;competitionPhaseUpdate(s,knockout);syncMatchLifecycle(s);return s}if(s.phase==='halftime'||s.phase==='extraTimeBreak'){s.seconds+=DT;s.tick++;competitionPhaseUpdate(s,knockout);syncMatchLifecycle(s);return s}if((s.phase as string)==='finished'){syncMatchLifecycle(s);return s}if(s.restart)executeRestartV2(s,home,away);stepMatchContext(s,home,away,()=>rng(s));movePlayers(s,home,away);executeBallActions(s,home,away);if(!s.restart){resolveContact(s,home,away);stepFreeBall(s,DT);const handball=maybeResolveHandball(s,home,away,()=>rng(s));if(!handball){const goal=detectPhysicalGoal(s,knockout.rules??defaultCompetitionRules);if(!goal){resolveFreeBall(s,home,away);boundaryRestart(s)}}}if(s.possessionClubId)teamOf(s,s.possessionClubId).possessionSeconds+=DT;for(const p of [...s.home.players,...s.away.players].filter(x=>x.onPitch&&!x.sentOff))p.minutesPlayed+=DT/60;s.seconds+=DT;s.tick++;competitionPhaseUpdate(s,knockout);syncMatchLifecycle(s);if(s.tick%240===0){for(const club of [home,away]){const sub=suggestSubstitution(s,club,defaultCompetitionRules);if(sub)applySubstitution(s,club,sub)}if(!legalMatchContinuation(s)){s.phase='finished';syncMatchLifecycle(s)}}return s}
export function simulateMatchCore(s:MatchCoreState,home:Club,away:Club,maxTicks=24000,knockout:KnockoutContext={requiresWinner:false}){for(let i=0;i<maxTicks&&s.phase!=='finished';i++)stepMatch(s,home,away,knockout);syncMatchLifecycle(s);return s}