import type {Club,Player} from './engine';
import type {LivePlayer,MatchCoreState,Vec2} from './match-core-v2';
import {distance,teamOf} from './match-core-v2';
export type SetPieceKind='corner'|'freeKickDirect'|'freeKickIndirect'|'throwIn'|'goalKick'|'penalty'|'kickoff';
export type SetPieceRoutine='directShot'|'nearPost'|'farPost'|'penaltySpot'|'edgeCutback'|'short'|'screen'|'dummy'|'secondPhase'|'quick'|'possession'|'longTarget'|'buildShort';
export type SetPieceRole='taker'|'primaryTarget'|'secondaryTarget'|'screen'|'edge'|'restDefense'|'marker'|'wall'|'keeper'|'rebound';
export type SetPieceAssignment={playerId:string;role:SetPieceRole;target:Vec2;priority:number};
export type SetPiecePlan={kind:SetPieceKind;routine:SetPieceRoutine;clubId:string;takerId:string;target?:Vec2;assignments:SetPieceAssignment[];quick:boolean;quality:number;reason:string};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const attr=(p:Player|undefined,k:string,f=50)=>Number((p?.attributes as any)?.[k]??f);
const pdata=(c:Club,id:string)=>c.players.find(p=>p.id===id);
const live=(s:MatchCoreState,cid:string)=>teamOf(s,cid).players.filter(p=>p.onPitch&&!p.sentOff);
const goal=(s:MatchCoreState,cid:string):Vec2=>({x:teamOf(s,cid).attackingRight?s.pitch.length:0,y:s.pitch.width/2});
function takerScore(p:Player,kind:SetPieceKind){const a=p.attributes as any;let x=attr(p,'technique')*.22+attr(p,'passing')*.2+attr(p,'decisions')*.12;if(kind==='penalty')x+=attr(p,'finishing')*.32+attr(p,'composure')*.14;if(kind==='corner'||kind==='freeKickIndirect')x+=attr(p,'crossing',a.passing)*.22;if(kind==='freeKickDirect')x+=attr(p,'finishing')*.22+attr(p,'longShots',a.finishing)*.18+attr(p,'freeKicks',a.technique)*.22;if(kind==='throwIn')x+=attr(p,'strength')*.16;return x}
export function chooseSetPieceTaker(c:Club,kind:SetPieceKind,available?:Set<string>){return c.players.filter(p=>!available||available.has(p.id)).sort((a,b)=>takerScore(b,kind)-takerScore(a,kind))[0]}
function aerialScore(p:Player){return attr(p,'jumpingReach')*.27+attr(p,'heading')*.29+attr(p,'strength')*.16+attr(p,'bravery')*.12+attr(p,'positioning')*.16}
function routine(s:MatchCoreState,c:Club,kind:SetPieceKind,pos:Vec2):SetPieceRoutine{const g=goal(s,c.id),d=distance(pos,g),players=[...c.players],air=players.sort((a,b)=>aerialScore(b)-aerialScore(a)).slice(0,3).reduce((n,p)=>n+aerialScore(p),0)/3,technical=c.players.reduce((n,p)=>n+attr(p,'technique'),0)/Math.max(1,c.players.length),ment=c.tactics.mentality;if(kind==='penalty')return'directShot';if(kind==='goalKick')return c.tactics.passingStyle==='short'?'buildShort':c.tactics.passingStyle==='direct'?'longTarget':technical>64?'buildShort':'longTarget';if(kind==='throwIn')return d<30&&air>67?'longTarget':technical>65?'possession':'quick';if(kind==='kickoff')return ment==='attacking'?'quick':'possession';if(kind==='freeKickDirect'&&d<29)return'directShot';if(kind==='freeKickIndirect')return d<34?(air>68?'farPost':'screen'):'possession';if(kind==='corner'){if(air>70)return Math.abs(pos.y-s.pitch.width/2)>28?'nearPost':'farPost';if(technical>69)return'edgeCutback';return Math.random()<.22?'short':'penaltySpot'}return technical>67?'short':'secondPhase'}
function boxTargets(s:MatchCoreState,cid:string,r:SetPieceRoutine,pos:Vec2):Vec2[]{const g=goal(s,cid),sg=teamOf(s,cid).attackingRight?1:-1,cy=s.pitch.width/2;if(r==='nearPost')return[{x:g.x-sg*5.5,y:cy+(pos.y<cy?-1:1)*3},{x:g.x-sg*9,y:cy}];if(r==='farPost')return[{x:g.x-sg*7,y:cy+(pos.y<cy?1:-1)*5},{x:g.x-sg*10,y:cy}];if(r==='edgeCutback')return[{x:g.x-sg*17,y:cy},{x:g.x-sg*11,y:cy+(pos.y<cy?-1:1)*5}];return[{x:g.x-sg*9,y:cy},{x:g.x-sg*12,y:cy+5},{x:g.x-sg*12,y:cy-5}]}
export function buildSetPiecePlan(s:MatchCoreState,c:Club,kind:SetPieceKind,pos:Vec2):SetPiecePlan{const lp=live(s,c.id),ids=new Set(lp.map(p=>p.playerId)),t=chooseSetPieceTaker(c,kind,ids)??c.players[0],r=routine(s,c,kind,pos),targets=boxTargets(s,c.id,r,pos),candidates=lp.filter(p=>p.playerId!==t.id).sort((a,b)=>aerialScore(pdata(c,b.playerId)!)-aerialScore(pdata(c,a.playerId)!)),assignments:SetPieceAssignment[]=[];if(kind==='penalty')return{kind,routine:'directShot',clubId:c.id,takerId:t.id,target:goal(s,c.id),assignments,quick:false,quality:takerScore(t,kind),reason:'pênalti: técnica, finalização e compostura'};candidates.slice(0,3).forEach((p,i)=>assignments.push({playerId:p.playerId,role:i===0?'primaryTarget':'secondaryTarget',target:targets[i%targets.length],priority:90-i*8}));const rest=candidates.slice(3);if(rest[0])assignments.push({playerId:rest[0].playerId,role:'edge',target:targets[0]?{x:(targets[0].x+pos.x)/2,y:s.pitch.width/2}:pos,priority:68});for(const p of rest.slice(1,3))assignments.push({playerId:p.playerId,role:'restDefense',target:{...p.homeSlot},priority:62});const quick=(r==='quick'||r==='short')&&attr(t,'decisions')>62;return{kind,routine:r,clubId:c.id,takerId:t.id,target:targets[0],assignments,quick,quality:clamp(takerScore(t,kind)),reason:`${kind}/${r}: selecionado por contexto, perfil técnico e alvos disponíveis`}}
export function defensiveSetPieceAssignments(s:MatchCoreState,def:Club,plan:SetPiecePlan):SetPieceAssignment[]{const lp=live(s,def.id),attackingGoal=goal(s,plan.clubId),defGoal={x:attackingGoal.x===0?s.pitch.length:0,y:s.pitch.width/2},out:SetPieceAssignment[]=[];const gk=lp.find(p=>p.role==='goalkeeper'||p.role==='sweeperKeeper');if(gk)out.push({playerId:gk.playerId,role:'keeper',target:{x:defGoal.x+(defGoal.x===0?1.2:-1.2),y:defGoal.y},priority:100});const field=lp.filter(p=>p!==gk),targets=plan.assignments.filter(a=>a.role==='primaryTarget'||a.role==='secondaryTarget');targets.forEach((a,i)=>{const d=field[i];if(d)out.push({playerId:d.playerId,role:'marker',target:{...a.target},priority:88-i*4})});if((plan.kind==='freeKickDirect'||plan.kind==='freeKickIndirect')&&distance((s.restart as any)?.position??s.ball.position,defGoal)<32){const ball=(s.restart as any)?.position??s.ball.position,dx=defGoal.x-ball.x,dy=defGoal.y-ball.y,m=Math.hypot(dx,dy)||1,n=Math.min(5,Math.max(2,Math.round(5-distance(ball,defGoal)/12)));field.slice(targets.length,targets.length+n).forEach((p,i)=>out.push({playerId:p.playerId,role:'wall',target:{x:ball.x+dx/m*9.15,y:ball.y+dy/m*9.15+(i-(n-1)/2)*.75},priority:92}))}for(const p of field)if(!out.some(a=>a.playerId===p.playerId))out.push({playerId:p.playerId,role:'rebound',target:{x:defGoal.x+(defGoal.x===0?1:-1)*18,y:s.pitch.width/2+(p.homeSlot.y-s.pitch.width/2)*.45},priority:55});return out}
export function setPieceExpectedThreat(s:MatchCoreState,c:Club,p:SetPiecePlan){const g=goal(s,c.id),d=distance((s.restart as any)?.position??s.ball.position,g),targets=p.assignments.filter(a=>a.role==='primaryTarget'||a.role==='secondaryTarget'),air=targets.map(a=>pdata(c,a.playerId)).filter(Boolean).reduce((n,x)=>n+aerialScore(x!),0)/Math.max(1,targets.length),routineBonus=p.routine==='directShot'?18:p.routine==='nearPost'||p.routine==='farPost'?14:p.routine==='edgeCutback'?12:p.routine==='short'?7:5;return clamp(18+(35-d)*1.15+p.quality*.25+air*.18+routineBonus)}
