import type { Club, World } from './engine';
import type { MatchCoreState } from './match-core-v2';
import { playerMatchPerformances } from './match-player-performance-v2';
import { matchEventLedger, playerLedgerStats } from './match-event-ledger-v2';
import { matchInjuries } from './match-contact-injury-v2';

export type PlayerSeasonStats={season:number;playerId:string;clubId:string;appearances:number;starts:number;minutes:number;goals:number;assists:number;keyPasses:number;shots:number;shotsOnTarget:number;xg:number;postShotXg:number;bigChances:number;bigChancesMissed:number;yellowCards:number;redCards:number;foulsCommitted:number;foulsWon:number;saves:number;goalsConceded:number;cleanSheets:number;keeperErrors:number;aerialDuels:number;aerialWins:number;injuries:number;forcedOff:number;ownGoals:number;hatTricks:number;frameHits:number;errorsLeadingToShot:number;errorsLeadingToGoal:number;ratingSum:number;ratingCount:number;averageRating:number;bestRating:number;motm:number};
export type PlayerCareerStats={playerId:string;appearances:number;minutes:number;goals:number;assists:number;keyPasses:number;yellowCards:number;redCards:number;cleanSheets:number;hatTricks:number;ownGoals:number;motm:number;ratingSum:number;ratingCount:number;averageRating:number;seasons:Record<number,PlayerSeasonStats>};
export type ClubSeasonStats={season:number;clubId:string;played:number;wins:number;draws:number;losses:number;goalsFor:number;goalsAgainst:number;xgFor:number;xgAgainst:number;shotsFor:number;shotsAgainst:number;cleanSheets:number;yellowCards:number;redCards:number;penaltiesFor:number;penaltiesAgainst:number;ownGoalsFor:number;ownGoalsAgainst:number;attendance?:number};
export type MatchArchiveRecord={id:string;season:number;date?:string;competitionId?:string;round?:number;homeClubId:string;awayClubId:string;homeGoals:number;awayGoals:number;homeXg:number;awayXg:number;seconds:number;motmPlayerId?:string;eventCount:number};
type HistoryState={players:Map<string,PlayerCareerStats>;clubs:Map<string,ClubSeasonStats>;matches:MatchArchiveRecord[];processed:Set<string>};
const states=new WeakMap<World,HistoryState>();
const round=(v:number,n=2)=>{const p=10**n;return Math.round(v*p)/p};
function state(world:World){let s=states.get(world);if(!s){s={players:new Map(),clubs:new Map(),matches:[],processed:new Set()};states.set(world,s)}return s}
function blankPlayerSeason(season:number,playerId:string,clubId:string):PlayerSeasonStats{return{season,playerId,clubId,appearances:0,starts:0,minutes:0,goals:0,assists:0,keyPasses:0,shots:0,shotsOnTarget:0,xg:0,postShotXg:0,bigChances:0,bigChancesMissed:0,yellowCards:0,redCards:0,foulsCommitted:0,foulsWon:0,saves:0,goalsConceded:0,cleanSheets:0,keeperErrors:0,aerialDuels:0,aerialWins:0,injuries:0,forcedOff:0,ownGoals:0,hatTricks:0,frameHits:0,errorsLeadingToShot:0,errorsLeadingToGoal:0,ratingSum:0,ratingCount:0,averageRating:0,bestRating:0,motm:0}}
function career(s:HistoryState,id:string){let c=s.players.get(id);if(!c){c={playerId:id,appearances:0,minutes:0,goals:0,assists:0,keyPasses:0,yellowCards:0,redCards:0,cleanSheets:0,hatTricks:0,ownGoals:0,motm:0,ratingSum:0,ratingCount:0,averageRating:0,seasons:{}};s.players.set(id,c)}return c}
function clubSeason(s:HistoryState,season:number,id:string){const key=`${season}:${id}`;let c=s.clubs.get(key);if(!c){c={season,clubId:id,played:0,wins:0,draws:0,losses:0,goalsFor:0,goalsAgainst:0,xgFor:0,xgAgainst:0,shotsFor:0,shotsAgainst:0,cleanSheets:0,yellowCards:0,redCards:0,penaltiesFor:0,penaltiesAgainst:0,ownGoalsFor:0,ownGoalsAgainst:0};s.clubs.set(key,c)}return c}
function matchKey(world:World,m:MatchCoreState,meta?:{fixtureId?:string;date?:string;competitionId?:string;round?:number}){return meta?.fixtureId??`${world.season}:${meta?.competitionId??'match'}:${meta?.round??0}:${m.home.clubId}:${m.away.clubId}:${Math.round(m.seconds)}:${m.seed}`}
export function persistCompletedMatchV2(world:World,m:MatchCoreState,home:Club,away:Club,meta?:{fixtureId?:string;date?:string;competitionId?:string;round?:number}){if(m.phase!=='finished')return false;const s=state(world),key=matchKey(world,m,meta);if(s.processed.has(key))return false;const perf=playerMatchPerformances(m,home,away),motm=perf[0],events=matchEventLedger(m),injuries=matchInjuries(m),homeCS=clubSeason(s,world.season,home.id),awayCS=clubSeason(s,world.season,away.id),homeWin=m.home.score>m.away.score,awayWin=m.away.score>m.home.score,draw=!homeWin&&!awayWin;
 for(const [cs,team,opp] of [[homeCS,m.home,m.away],[awayCS,m.away,m.home]] as const){cs.played++;if(draw)cs.draws++;else if(team.score>opp.score)cs.wins++;else cs.losses++;cs.goalsFor+=team.score;cs.goalsAgainst+=opp.score;cs.xgFor=round(cs.xgFor+team.xg);cs.xgAgainst=round(cs.xgAgainst+opp.xg);cs.shotsFor+=team.shots;cs.shotsAgainst+=opp.shots;if(opp.score===0)cs.cleanSheets++;cs.yellowCards+=team.yellowCards;cs.redCards+=team.redCards}
 for(const e of events){if(e.type==='ownGoal'&&e.clubId===home.id){homeCS.ownGoalsAgainst++;awayCS.ownGoalsFor++}if(e.type==='ownGoal'&&e.clubId===away.id){awayCS.ownGoalsAgainst++;homeCS.ownGoalsFor++}}
 const pen=((m as any).__refereeLog??[]) as any[];homeCS.penaltiesFor+=pen.filter(x=>x.penalty&&x.victimClubId===home.id).length;awayCS.penaltiesFor+=pen.filter(x=>x.penalty&&x.victimClubId===away.id).length;homeCS.penaltiesAgainst=awayCS.penaltiesFor;awayCS.penaltiesAgainst=homeCS.penaltiesFor;
 for(const p of perf){const c=career(s,p.playerId),season=c.seasons[world.season]??blankPlayerSeason(world.season,p.playerId,p.clubId),led=playerLedgerStats(m,p.playerId),wasStarter=(p.clubId===home.id?m.home:m.away).players.find(x=>x.playerId===p.playerId)?.minutesPlayed>0&&p.minutes>=45;season.appearances++;if(wasStarter)season.starts++;season.minutes=round(season.minutes+p.minutes,1);season.goals+=led.goals;season.assists+=led.assists;season.keyPasses+=led.keyPasses;season.shots+=p.shots;season.shotsOnTarget+=p.shotsOnTarget;season.xg=round(season.xg+p.xg);season.postShotXg=round(season.postShotXg+p.postShotXg);season.bigChances+=led.bigChances;season.bigChancesMissed+=led.bigChancesMissed;season.yellowCards+=p.yellowCards;season.redCards+=p.redCards;season.foulsCommitted+=p.foulsCommitted;season.foulsWon+=p.foulsWon;season.saves+=p.saves;season.goalsConceded+=p.goalsConceded;season.cleanSheets+=led.cleanSheets;season.keeperErrors+=p.keeperErrors;season.aerialDuels+=p.aerialDuels;season.aerialWins+=p.aerialWins;season.injuries+=p.injuries;season.forcedOff+=p.forcedOff?1:0;season.ownGoals+=led.ownGoals;season.hatTricks+=led.hatTricks;season.frameHits+=led.frameHits;season.errorsLeadingToShot+=led.errorsLeadingToShot;season.errorsLeadingToGoal+=led.errorsLeadingToGoal;season.ratingSum+=p.rating;season.ratingCount++;season.averageRating=round(season.ratingSum/season.ratingCount);season.bestRating=Math.max(season.bestRating,p.rating);if(motm?.playerId===p.playerId)season.motm++;c.seasons[world.season]=season;c.appearances++;c.minutes=round(c.minutes+p.minutes,1);c.goals+=led.goals;c.assists+=led.assists;c.keyPasses+=led.keyPasses;c.yellowCards+=p.yellowCards;c.redCards+=p.redCards;c.cleanSheets+=led.cleanSheets;c.hatTricks+=led.hatTricks;c.ownGoals+=led.ownGoals;if(motm?.playerId===p.playerId)c.motm++;c.ratingSum+=p.rating;c.ratingCount++;c.averageRating=round(c.ratingSum/c.ratingCount)}
 for(const i of injuries){const c=career(s,i.playerId),season=c.seasons[world.season];if(season&&!perf.some(p=>p.playerId===i.playerId))season.injuries++}
 s.matches.push({id:key,season:world.season,date:meta?.date,competitionId:meta?.competitionId,round:meta?.round,homeClubId:home.id,awayClubId:away.id,homeGoals:m.home.score,awayGoals:m.away.score,homeXg:round(m.home.xg),awayXg:round(m.away.xg),seconds:m.seconds,motmPlayerId:motm?.playerId,eventCount:events.length});if(s.matches.length>5000)s.matches.shift();s.processed.add(key);return true}
export function playerCareerStats(world:World,id:string){return state(world).players.get(id)}
export function playerSeasonStats(world:World,id:string,season=world.season){return state(world).players.get(id)?.seasons[season]}
export function clubSeasonStats(world:World,id:string,season=world.season){return state(world).clubs.get(`${season}:${id}`)}
export function matchArchive(world:World){return[...state(world).matches]}
export function snapshotMatchHistory(world:World){const s=state(world);return{players:[...s.players],clubs:[...s.clubs],matches:s.matches,processed:[...s.processed]}}
export function restoreMatchHistory(world:World,x:ReturnType<typeof snapshotMatchHistory>){states.set(world,{players:new Map(x.players),clubs:new Map(x.clubs),matches:[...x.matches],processed:new Set(x.processed)})}
