import type { Club, Player } from './engine';
import type { MatchCoreState, RestartState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf } from './match-core-v2';
import { kickBall } from './match-ball-physics-v2';
import { buildSetPiecePlan, defensiveSetPieceAssignments, setPieceExpectedThreat, type SetPieceKind, type SetPiecePlan } from './match-set-pieces-v2';

const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const attr=(p:Player|undefined,k:string,f=50)=>Number((p?.attributes as any)?.[k]??f);
function player(c:Club,id:string){return c.players.find(p=>p.id===id)}
function rng(s:MatchCoreState){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296}
function goal(s:MatchCoreState,id:string):Vec2{return{x:teamOf(s,id).attackingRight?s.pitch.length:0,y:s.pitch.width/2}}
function mapKind(r:RestartState):SetPieceKind{if(r.type==='corner')return'corner';if(r.type==='goalKick')return'goalKick';if(r.type==='throwIn')return'throwIn';if(r.type==='penalty')return'penalty';if(r.type==='kickoff')return'kickoff';return r.indirect?'freeKickIndirect':'freeKickDirect'}
function moveAssignments(s:MatchCoreState,plan:SetPiecePlan,def:Club){for(const a of plan.assignments){const p=teamOf(s,plan.clubId).players.find(x=>x.playerId===a.playerId);if(p)p.position={...a.target}}for(const a of defensiveSetPieceAssignments(s,def,plan)){const p=teamOf(s,def.id).players.find(x=>x.playerId===a.playerId);if(p)p.position={...a.target}}}
function log(s:MatchCoreState,plan:SetPiecePlan,result:string,xT:number){const any=s as any;if(!any.__setPieceLog)any.__setPieceLog=[];any.__setPieceLog.push({second:s.seconds,clubId:plan.clubId,kind:plan.kind,routine:plan.routine,takerId:plan.takerId,expectedThreat:xT,result});if(any.__setPieceLog.length>220)any.__setPieceLog.shift()}
function directShot(s:MatchCoreState,c:Club,def:Club,plan:SetPiecePlan,pos:Vec2){const taker=player(c,plan.takerId),g=goal(s,c.id),gkLive=teamOf(s,def.id).players.find(p=>p.onPitch&&!p.sentOff&&(p.role==='goalkeeper'||p.role==='sweeperKeeper')),gk=gkLive?player(def,gkLive.playerId):undefined,d=distance(pos,g),wall=plan.kind==='freeKickDirect'&&d<31,tech=attr(taker,'technique'),fin=attr(taker,'finishing'),fk=attr(taker,'freeKicks',tech),composure=attr(taker,'composure',attr(taker,'decisions')),accuracy=clamp(.28+fk*.004+tech*.002+composure*.0015-d*.006-(wall?.08:0),.08,.82),goalChance=clamp(.04+(31-d)*.018+fin*.0026+fk*.0022-(gk?.attributes.goalkeeping??65)*.0022,.015,.52),target={x:g.x,y:g.y+(rng(s)-.5)*s.pitch.goalWidth*.88};teamOf(s,c.id).shots++;teamOf(s,c.id).xg+=goalChance;if(rng(s)<accuracy){teamOf(s,c.id).shotsOnTarget++;if(rng(s)<goalChance){teamOf(s,c.id).score++;s.restart={type:'kickoff',clubId:def.id,position:{x:s.pitch.length/2,y:s.pitch.width/2}};s.ball.ownerId=undefined;s.possessionClubId=def.id;return'goal'}}kickBall(s,{direction:{x:target.x-pos.x,y:target.y-pos.y},speed:23+fin*.055,lift:2.4+rng(s)*2.8,spin:(rng(s)-.5)*1.9,ownerId:plan.takerId});s.possessionClubId=undefined;return rng(s)<.45?'save/rebound':'miss/rebound'}
function penalty(s:MatchCoreState,c:Club,def:Club,plan:SetPiecePlan,pos:Vec2){const taker=player(c,plan.takerId),gkLive=teamOf(s,def.id).players.find(p=>p.onPitch&&!p.sentOff&&(p.role==='goalkeeper'||p.role==='sweeperKeeper')),gk=gkLive?player(def,gkLive.playerId):undefined,fin=attr(taker,'finishing'),tech=attr(taker,'technique'),comp=attr(taker,'composure',attr(taker,'decisions')),keeper=(gk?.attributes.goalkeeping??65)*.55+attr(gk,'decisions',60)*.2,placement=fin*.35+tech*.25+comp*.3+rng(s)*18,save=keeper*.65+rng(s)*34,miss=rng(s)*100>clamp(82+comp*.11+tech*.06,82,97);teamOf(s,c.id).shots++;teamOf(s,c.id).xg+=.76;if(!miss&&placement>save){teamOf(s,c.id).shotsOnTarget++;teamOf(s,c.id).score++;s.restart={type:'kickoff',clubId:def.id,position:{x:s.pitch.length/2,y:s.pitch.width/2}};s.possessionClubId=def.id;s.ball.ownerId=undefined;return'goal'}if(!miss)teamOf(s,c.id).shotsOnTarget++;s.ball.ownerId=undefined;s.possessionClubId=undefined;const g=goal(s,c.id);s.ball.position={x:g.x+(teamOf(s,c.id).attackingRight?-6:6),y:g.y+(rng(s)-.5)*7};s.ball.velocity={x:0,y:0};return miss?'miss':'save/rebound'}
function delivery(s:MatchCoreState,c:Club,plan:SetPiecePlan,pos:Vec2){const taker=player(c,plan.takerId),target=plan.target??plan.assignments.find(a=>a.role==='primaryTarget')?.target??{x:pos.x+(teamOf(s,c.id).attackingRight?18:-18),y:s.pitch.width/2},quality=clamp(attr(taker,'passing')*.34+attr(taker,'technique')*.3+attr(taker,'decisions')*.15+plan.quality*.2),error=(100-quality)/100*(plan.kind==='corner'?8:plan.kind==='goalKick'?12:6),actual={x:target.x+(rng(s)-.5)*error,y:target.y+(rng(s)-.5)*error},long=plan.routine==='longTarget'||plan.kind==='corner'||['nearPost','farPost','penaltySpot','screen'].includes(plan.routine),speed=plan.kind==='throwIn'?12:plan.kind==='goalKick'?24:long?20:14,lift=plan.kind==='throwIn'?(plan.routine==='longTarget'?3.8:.4):plan.kind==='goalKick'?(long?6:1):long?5.2:.25;kickBall(s,{direction:{x:actual.x-pos.x,y:actual.y-pos.y},speed,lift,spin:(rng(s)-.5)*(plan.kind==='corner'?1.7:.8),ownerId:plan.takerId});s.possessionClubId=undefined;return'liveBall'}
export function executeRestartV2(s:MatchCoreState,home:Club,away:Club){const restart=s.restart;if(!restart)return false;const c=restart.clubId===home.id?home:away,def=restart.clubId===home.id?away:home,kind=mapKind(restart),plan=buildSetPiecePlan(s,c,kind,restart.position),taker=teamOf(s,c.id).players.find(p=>p.playerId===plan.takerId&&p.onPitch&&!p.sentOff);if(!taker)return false;moveAssignments(s,plan,def);taker.position={...restart.position};s.ball.position={...restart.position};s.ball.ownerId=plan.takerId;s.possessionClubId=c.id;const xT=setPieceExpectedThreat(s,c,plan);let result:string;if(kind==='penalty')result=penalty(s,c,def,plan,restart.position);else if(plan.routine==='directShot'&&kind==='freeKickDirect')result=directShot(s,c,def,plan,restart.position);else result=delivery(s,c,plan,restart.position);if(s.restart===restart)s.restart=undefined;log(s,plan,result,xT);return true}
export function setPieceLog(s:MatchCoreState){return[...((((s as any).__setPieceLog)??[]) as any[])]}
