import type { Club } from './engine';
import { createMatchCore } from './match-core-v2';
import { simulateMatchCore } from './match-stepper-v2';
import { validateMatchState } from './match-v2-diagnostics';
import { officiatingLog } from './match-officiating-v2';
import { shotResolutionLog } from './match-goalkeeper-resolution-v2';
import { aerialDuelLog } from './match-aerial-duel-v2';

export type CalibrationMetric='goals'|'shots'|'shotsOnTarget'|'xg'|'passPct'|'corners'|'fouls'|'yellows'|'reds'|'offsides'|'penalties'|'injuries'|'keeperSavePct'|'possessionHome';
export type CalibrationTarget={min:number;max:number;hardMin?:number;hardMax?:number};
export type CalibrationTargets=Record<CalibrationMetric,CalibrationTarget>;
export type CalibrationSummary={matches:number;invalidMatches:number;metrics:Record<CalibrationMetric,number>;issues:string[];score:number;withinTarget:Record<CalibrationMetric,boolean>};
export const broadFootballTargets:CalibrationTargets={goals:{min:2.0,max:3.5,hardMin:.7,hardMax:5.5},shots:{min:19,max:31,hardMin:10,hardMax:44},shotsOnTarget:{min:6,max:12,hardMin:3,hardMax:18},xg:{min:1.8,max:3.8,hardMin:.7,hardMax:5.5},passPct:{min:68,max:88,hardMin:52,hardMax:95},corners:{min:6,max:14,hardMin:2,hardMax:22},fouls:{min:18,max:34,hardMin:8,hardMax:48},yellows:{min:2,max:7,hardMin:.4,hardMax:12},reds:{min:.03,max:.45,hardMin:0,hardMax:1.2},offsides:{min:1,max:6,hardMin:.2,hardMax:10},penalties:{min:.08,max:.55,hardMin:0,hardMax:1.1},injuries:{min:.08,max:.8,hardMin:0,hardMax:1.8},keeperSavePct:{min:58,max:82,hardMin:35,hardMax:94},possessionHome:{min:44,max:56,hardMin:30,hardMax:70}};
const mean=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
function matchStats(home:Club,away:Club,seed:number){const s=createMatchCore(home,away,{seed});simulateMatchCore(s,home,away);const refs=officiatingLog(s),shots=shotResolutionLog(s),inj=(((s as any).__matchInjuries??[]) as any[]),totalPoss=Math.max(1,s.home.possessionSeconds+s.away.possessionSeconds),onTarget=s.home.shotsOnTarget+s.away.shotsOnTarget,saves=shots.filter(x=>x.onTarget&&!x.goal).length;return{invalid:validateMatchState(s).length>0,goals:s.home.score+s.away.score,shots:s.home.shots+s.away.shots,shotsOnTarget:onTarget,xg:s.home.xg+s.away.xg,passPct:((s.home.passSuccess+s.away.passSuccess)/2)||0,corners:s.home.corners+s.away.corners,fouls:s.home.fouls+s.away.fouls,yellows:s.home.yellowCards+s.away.yellowCards,reds:s.home.redCards+s.away.redCards,offsides:s.home.offsides+s.away.offsides,penalties:refs.filter((x:any)=>x.kind==='contactVAR'&&x.varType==='penalty'&&x.finalFoul).length,injuries:inj.filter((x:any)=>x.severity!=='knock').length,keeperSavePct:onTarget?Math.min(100,saves/onTarget*100):0,possessionHome:s.home.possessionSeconds/totalPoss*100,aerialDuels:aerialDuelLog(s).length,varReviews:refs.filter((x:any)=>x.var?.reviewed).length}}
export function calibrateMatchEngineV2(home:Club,away:Club,matches=250,seedBase=20260824,targets:CalibrationTargets=broadFootballTargets):CalibrationSummary{const rows:ReturnType<typeof matchStats>[]=[];for(let i=0;i<matches;i++)rows.push(matchStats(home,away,seedBase+i*7919));const metrics={} as Record<CalibrationMetric,number>,keys=Object.keys(targets) as CalibrationMetric[];for(const k of keys)metrics[k]=Number(mean(rows.map(r=>Number(r[k]))).toFixed(3));const withinTarget={} as Record<CalibrationMetric,boolean>,issues:string[]=[];let score=100;for(const k of keys){const t=targets[k],v=metrics[k],ok=v>=t.min&&v<=t.max;withinTarget[k]=ok;if(!ok){const below=v<t.min,delta=below?(t.min-v)/Math.max(.01,t.min):(v-t.max)/Math.max(.01,t.max),hard=(t.hardMin!==undefined&&v<t.hardMin)||(t.hardMax!==undefined&&v>t.hardMax);score-=Math.min(hard?18:10,delta*24+(hard?7:2));issues.push(`${k}: ${v} fora da faixa ${t.min}–${t.max}${hard?' (desvio crítico)':''}`)}}const invalidMatches=rows.filter(r=>r.invalid).length;if(invalidMatches){score-=Math.min(30,invalidMatches/matches*100);issues.push(`${invalidMatches}/${matches} partidas violaram invariantes.`)}return{matches,invalidMatches,metrics,issues,score:Number(Math.max(0,score).toFixed(1)),withinTarget}}
export function compareCalibrationVariants(home:Club,away:Club,variants:{name:string;seedBase:number;matches?:number}[]){return variants.map(v=>({name:v.name,result:calibrateMatchEngineV2(home,away,v.matches??150,v.seedBase)})).sort((a,b)=>b.result.score-a.result.score)}
