import type { Club } from './engine';
import { createMatchCore } from './match-core-v2';
import { kickBall, stepFreeBall } from './match-ball-physics-v2';
import { setMatchEnvironment, environmentEffects, inferEnvironment } from './match-environment-v2';
import { evaluateHandball } from './match-handball-v2';
import { startAdvantage, updateAdvantage } from './match-advantage-v2';

export type EnvironmentDiagnosticCheck={name:string;ok:boolean;detail:string};
export function environmentDiagnosticsV2(home:Club,away:Club,seed=20260824){const checks:EnvironmentDiagnosticCheck[]=[];const add=(name:string,ok:boolean,detail:string)=>checks.push({name,ok,detail});
 const dry=createMatchCore(home,away,{seed,weather:{temperature:20,rain:0,wind:2,windDirection:0}}),wet=createMatchCore(home,away,{seed,weather:{temperature:18,rain:85,wind:8,windDirection:0}});setMatchEnvironment(dry,{weather:'clear',moisture:'dry'});setMatchEnvironment(wet,{weather:'heavyRain',moisture:'waterlogged'});const de=environmentEffects(inferEnvironment(dry,(dry as any).__environment)),we=environmentEffects(inferEnvironment(wet,(wet as any).__environment));add('gramado altera tração',we.traction<de.traction,`${de.traction.toFixed(2)} -> ${we.traction.toFixed(2)}`);add('ambiente altera fadiga',we.fatigueMultiplier>de.fatigueMultiplier*.9,`${de.fatigueMultiplier.toFixed(2)} vs ${we.fatigueMultiplier.toFixed(2)}`);kickBall(dry,{direction:{x:1,y:0},speed:20,lift:0});kickBall(wet,{direction:{x:1,y:0},speed:20,lift:0});for(let i=0;i<16;i++){stepFreeBall(dry,.25);stepFreeBall(wet,.25)}add('física da bola responde ao ambiente',Math.abs(dry.ball.position.x-wet.ball.position.x)>.05,`${dry.ball.position.x.toFixed(2)} vs ${wet.ball.position.x.toFixed(2)}`);
 const defender=wet.home.players.find(p=>p.onPitch)!;const data=home.players.find(p=>p.id===defender.playerId)!;const hand=evaluateHandball(wet,{player:defender,playerData:data,ballPosition:{...defender.position},ballSpeed:18,armExtension:95,armMovementTowardBall:95,distanceFromKick:8,deflectionBeforeContact:false,supportingArm:false,deliberate:true},()=>.01);add('mão deliberada detectável',hand.contact&&hand.offence,hand.reason);
 const attacker=wet.away.players.find(p=>p.onPitch)!;wet.possessionClubId=attacker.clubId;startAdvantage(wet,{offendingPlayerId:defender.playerId,victimId:attacker.playerId,beneficiaryClubId:attacker.clubId,foulPosition:{...attacker.position},card:'yellow',severity:'reckless',promisingAttack:80});wet.seconds+=1;wet.possessionClubId=defender.clubId;updateAdvantage(wet);add('vantagem pode voltar à falta',wet.restart?.type==='freeKick',wet.restart?.type??'sem restart');
 const score=Math.round(checks.filter(x=>x.ok).length/checks.length*100);return{ok:checks.every(x=>x.ok),score,checks,metrics:{dryTraction:de.traction,wetTraction:we.traction,dryBallX:dry.ball.position.x,wetBallX:wet.ball.position.x,handball:hand.offence}};}
