import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf, territorialControlAt } from './match-core-v2';

export type AttackingPattern='overlap'|'underlap'|'thirdMan'|'oneTwo'|'decoyRun'|'falseNineDrop'|'insideForwardRun'|'invertedFullback'|'switchOverload'|'attackBrokenLine';
export type PatternTask={playerId:string;pattern:AttackingPattern;target:Vec2;partnerIds:string[];priority:number;reason:string};
export type AttackingPlan={clubId:string;tasks:PatternTask[];overloadSide?:'left'|'right';brokenLineX?:number;generatedAt:number};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
const sign=(s:MatchCoreState,id:string)=>teamOf(s,id).attackingRight?1:-1;
const src=(c:Club,id:string)=>c.players.find(p=>p.id===id);
const roleIn=(p:LivePlayer,roles:string[])=>roles.includes(p.role as string);
function openSpace(state:MatchCoreState,clubId:string,p:Vec2){const c=territorialControlAt(state,p);return clubId===state.home.clubId?c.home:c.away}
function opponentLine(state:MatchCoreState,clubId:string){const opp=opponentOf(state,clubId),xs=opp.players.filter(p=>p.onPitch&&!p.sentOff&&!roleIn(p,['goalkeeper','sweeperKeeper'])).map(p=>p.position.x).sort((a,b)=>a-b);if(xs.length<2)return state.pitch.length/2;return opp.attackingRight?xs[1]:xs[xs.length-2]}
function brokenDefender(state:MatchCoreState,clubId:string){const opp=opponentOf(state,clubId),line=opponentLine(state,clubId),dir=sign(state,clubId);return opp.players.filter(p=>p.onPitch&&!p.sentOff&&roleIn(p,['centralDefender','ballPlayingDefender','stopper','fullback','invertedFullback'])).map(p=>({p,delta:(p.position.x-line)*dir})).sort((a,b)=>b.delta-a.delta)[0]}
function ability(club:Club,p:LivePlayer){const x=src(club,p.playerId);return x?x.attributes.decisions*.35+x.attributes.positioning*.35+x.attributes.pace*.15+x.attributes.technique*.15:50}
export function buildAttackingPlan(state:MatchCoreState,club:Club):AttackingPlan{const team=teamOf(state,club.id),players=team.players.filter(p=>p.onPitch&&!p.sentOff),carrier=state.ball.ownerId?players.find(p=>p.playerId===state.ball.ownerId):undefined,dir=sign(state,club.id),tasks:PatternTask[]=[],left=players.filter(p=>p.position.y<state.pitch.width*.38).length,right=players.filter(p=>p.position.y>state.pitch.width*.62).length,overloadSide=left>right+1?'left':right>left+1?'right':undefined,line=opponentLine(state,club.id),broken=brokenDefender(state,club.id);
 if(carrier){const flank=carrier.position.y<15||carrier.position.y>state.pitch.width-15;if(flank){const same=players.filter(p=>p.playerId!==carrier.playerId&&Math.abs(p.position.y-carrier.position.y)<16).sort((a,b)=>distance(a.position,carrier.position)-distance(b.position,carrier.position));const wide=same.find(p=>roleIn(p,['fullback','wingback','invertedFullback']));if(wide){const outside=carrier.position.y<state.pitch.width/2?Math.max(2,carrier.position.y-6):Math.min(state.pitch.width-2,carrier.position.y+6);const inside=state.pitch.width/2+(carrier.position.y-state.pitch.width/2)*.45;const overlap=openSpace(state,club.id,{x:carrier.position.x+dir*12,y:outside}),under=openSpace(state,club.id,{x:carrier.position.x+dir*10,y:inside}),pattern:AttackingPattern=overlap>=under?'overlap':'underlap';tasks.push({playerId:wide.playerId,pattern,target:{x:clamp(carrier.position.x+dir*(pattern==='overlap'?13:10),2,state.pitch.length-2),y:pattern==='overlap'?outside:inside},partnerIds:[carrier.playerId],priority:68+ability(club,wide)*.18,reason:`${pattern}: criar superioridade e linha de passe ao redor do portador`})}}}
 const forwards=players.filter(p=>roleIn(p,['falseNine','advancedForward','insideForward','shadowStriker','poacher']));for(const f of forwards){if(f.role==='falseNine'){tasks.push({playerId:f.playerId,pattern:'falseNineDrop',target:{x:f.position.x-dir*10,y:state.pitch.width/2},partnerIds:[],priority:62+ability(club,f)*.2,reason:'recuar entrelinhas para arrastar marcador e abrir profundidade'})}else if(f.role==='insideForward'){tasks.push({playerId:f.playerId,pattern:'insideForwardRun',target:{x:clamp(Math.max(0,Math.min(state.pitch.length,f.position.x+dir*13)),2,state.pitch.length-2),y:state.pitch.width/2+(f.position.y-state.pitch.width/2)*.35},partnerIds:[],priority:60+ability(club,f)*.22,reason:'diagonal interior atacando intervalo entre lateral e zagueiro'})}}
 const fullbacks=players.filter(p=>p.role==='invertedFullback');for(const f of fullbacks)tasks.push({playerId:f.playerId,pattern:'invertedFullback',target:{x:f.position.x+dir*5,y:state.pitch.width/2+(f.position.y-state.pitch.width/2)*.35},partnerIds:[],priority:58+ability(club,f)*.18,reason:'entrar no meio para gerar superioridade na construção'});
 if(carrier){const support=players.filter(p=>p.playerId!==carrier.playerId&&distance(p.position,carrier.position)<18).sort((a,b)=>ability(club,b)-ability(club,a))[0];const runner=players.filter(p=>p.playerId!==carrier.playerId&&p.playerId!==support?.playerId).map(p=>({p,space:openSpace(state,club.id,{x:p.position.x+dir*9,y:p.position.y})})).sort((a,b)=>b.space-a.space)[0]?.p;if(support&&runner){tasks.push({playerId:support.playerId,pattern:'oneTwo',target:{x:(support.position.x+carrier.position.x)/2+dir*3,y:(support.position.y+carrier.position.y)/2},partnerIds:[carrier.playerId,runner.playerId],priority:57+ability(club,support)*.2,reason:'apoio curto para tabela e progressão rápida'});tasks.push({playerId:runner.playerId,pattern:'thirdMan',target:{x:clamp(runner.position.x+dir*11,2,state.pitch.length-2),y:runner.position.y},partnerIds:[carrier.playerId,support.playerId],priority:60+ability(club,runner)*.2,reason:'terceiro homem ataca espaço enquanto a bola circula entre dois jogadores'})}}
 if(broken&&broken.delta>2.5){const attackers=players.filter(p=>p.position.x*dir<line*dir+25).sort((a,b)=>distance(a.position,broken.p.position)-distance(b.position,broken.p.position));const runner=attackers[0];if(runner)tasks.push({playerId:runner.playerId,pattern:'attackBrokenLine',target:{x:clamp(broken.p.position.x+dir*8,2,state.pitch.length-2),y:clamp(broken.p.position.y+(runner.position.y-broken.p.position.y)*.5,2,state.pitch.width-2)},partnerIds:[],priority:86,reason:'identificou defensor quebrando a linha e ataca o espaço legalizado por ele'})}
 const byPlayer=new Map<string,PatternTask>();for(const t of tasks){const old=byPlayer.get(t.playerId);if(!old||t.priority>old.priority)byPlayer.set(t.playerId,t)}return{clubId:club.id,tasks:[...byPlayer.values()],overloadSide,brokenLineX:broken?.p.position.x,generatedAt:state.seconds}}
export function attackingPatternTask(state:MatchCoreState,club:Club,playerId:string){const key=club.id===state.home.clubId?'__homeAttackPlan':'__awayAttackPlan',a=state as any;let plan=a[key] as AttackingPlan|undefined;if(!plan||state.seconds-plan.generatedAt>.75){plan=buildAttackingPlan(state,club);a[key]=plan}return plan.tasks.find(t=>t.playerId===playerId)}
