import type { MatchCoreState, LivePlayer, Vec2 } from './match-core-v2';
import { livePlayer, opponentOf, teamOf } from './match-core-v2';
export type DefensiveTask='press'|'cover'|'screen'|'mark'|'protectDepth'|'offsideLine'|'recover'|'doubleTeam';
export type DefensiveAssignment={playerId:string;task:DefensiveTask;target:Vec2;opponentId?:string;urgency:number;reason:string};
export type DefensivePhase='highPress'|'midBlock'|'lowBlock'|'counterpress'|'recovery';
export type CollectiveDefencePlan={clubId:string;phase:DefensivePhase;lineX:number;compactness:number;pressTrigger:number;assignments:DefensiveAssignment[];trapSide?:'left'|'right';generatedAt:number};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v)),dist=(a:Vec2,b:Vec2)=>Math.hypot(a.x-b.x,a.y-b.y),mid=(a:Vec2,b:Vec2):Vec2=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
function ownGoalX(s:MatchCoreState,id:string){return teamOf(s,id).attackingRight?0:s.pitch.length}
function dir(s:MatchCoreState,id:string){return teamOf(s,id).attackingRight?1:-1}
function danger(s:MatchCoreState,id:string){return clamp(100-Math.abs(s.ball.position.x-ownGoalX(s,id))/s.pitch.length*100)}
function defensivePhase(s:MatchCoreState,id:string,press:number,line:number):DefensivePhase{const d=danger(s,id),loss=(s as any).__lastPossessionLoss;const recentLoss=loss?.clubId===id&&s.seconds-(loss?.second??-99)<6;if(recentLoss&&press>55)return'counterpress';if(d>72)return'lowBlock';if(press>72&&d<52)return'highPress';if(d>48||line<45)return'midBlock';return'recovery'}
function linePosition(s:MatchCoreState,id:string,line:number,p:DefensivePhase){const own=ownGoalX(s,id),sign=dir(s,id),base=(p==='highPress'?54:p==='counterpress'?49:p==='midBlock'?39:p==='lowBlock'?25:34)+(line-50)*.22;return own+sign*clamp(base,18,68)}
function nearest(players:LivePlayer[],pos:Vec2,used:Set<string>){return players.filter(p=>p.onPitch&&!p.sentOff&&!used.has(p.playerId)).sort((a,b)=>dist(a.position,pos)-dist(b.position,pos))[0]}
function screenPoint(carrier:LivePlayer,target:LivePlayer,goalX:number){const m=mid(carrier.position,target.position);return{x:m.x+(goalX-m.x)*.08,y:m.y}}
export function buildCollectiveDefencePlan(s:MatchCoreState,clubId:string,t:{pressing:number;defensiveLine:number;compactness?:number}):CollectiveDefencePlan{const own=teamOf(s,clubId),opp=opponentOf(s,clubId),defenders=own.players.filter(p=>p.onPitch&&!p.sentOff),opponents=opp.players.filter(p=>p.onPitch&&!p.sentOff),carrier=s.ball.ownerId?livePlayer(s,s.ball.ownerId):undefined,ph=defensivePhase(s,clubId,t.pressing,t.defensiveLine),lineX=linePosition(s,clubId,t.defensiveLine,ph),assignments:DefensiveAssignment[]=[],used=new Set<string>(),goalX=ownGoalX(s,clubId);let trapSide:'left'|'right'|undefined;
 if(carrier&&carrier.clubId!==clubId){trapSide=carrier.position.y<s.pitch.width/2?'left':'right';const presser=nearest(defenders,carrier.position,used);if(presser){used.add(presser.playerId);assignments.push({playerId:presser.playerId,task:'press',target:{...carrier.position},opponentId:carrier.playerId,urgency:ph==='counterpress'?96:82,reason:ph==='counterpress'?'pressão imediata após perda':'pressionador viável mais próximo'});const support=nearest(defenders,carrier.position,used);if(support&&dist(support.position,carrier.position)<14){used.add(support.playerId);const double=ph==='counterpress'||danger(s,clubId)>65;assignments.push({playerId:support.playerId,task:double?'doubleTeam':'cover',target:double?{x:carrier.position.x,y:carrier.position.y+(trapSide==='left'?2.8:-2.8)}:mid(presser.position,{x:goalX,y:s.pitch.width/2}),opponentId:carrier.playerId,urgency:double?84:72,reason:double?'dobrar portador':'cobrir pressionador'})}for(const o of opponents.filter(o=>o.playerId!==carrier.playerId).sort((a,b)=>dist(a.position,carrier.position)-dist(b.position,carrier.position)).slice(0,3)){const point=screenPoint(carrier,o,goalX),scr=nearest(defenders,point,used);if(!scr)continue;used.add(scr.playerId);assignments.push({playerId:scr.playerId,task:'screen',target:point,opponentId:o.playerId,urgency:68,reason:'sombra de pressão / fechar linha de passe'})}}}
 for(const o of opponents.filter(o=>Math.abs(o.position.x-goalX)<38).sort((a,b)=>Math.abs(a.position.x-goalX)-Math.abs(b.position.x-goalX)).slice(0,3)){const marker=nearest(defenders,o.position,used);if(!marker)continue;used.add(marker.playerId);assignments.push({playerId:marker.playerId,task:'mark',target:{x:o.position.x-dir(s,clubId)*2.2,y:o.position.y},opponentId:o.playerId,urgency:75,reason:'acompanhar ameaça em profundidade'})}
 for(const p of defenders.filter(p=>!used.has(p.playerId))){const central=Math.abs(p.homeSlot.y-s.pitch.width/2)<18&&!['goalkeeper','sweeperKeeper'].includes(p.role);assignments.push({playerId:p.playerId,task:central&&ph!=='lowBlock'?'offsideLine':'recover',target:{x:central&&ph!=='lowBlock'?lineX:p.homeSlot.x,y:p.homeSlot.y},urgency:central?58:52,reason:central?'manter linha sincronizada':'recompor estrutura'})}
 return{clubId,phase:ph,lineX,compactness:clamp((t.compactness??own.compactness)+(ph==='lowBlock'?14:ph==='counterpress'?-4:0)),pressTrigger:clamp(t.pressing+(ph==='counterpress'?18:0)),assignments,trapSide,generatedAt:s.seconds}}
export function defensiveAssignment(plan:CollectiveDefencePlan,playerId:string){return plan.assignments.find(a=>a.playerId===playerId)}
export function collectiveDefencePlan(s:MatchCoreState,clubId:string,t:{pressing:number;defensiveLine:number;compactness?:number}){const key=clubId===s.home.clubId?'__homeDefPlan':'__awayDefPlan',any=s as any;const cached=any[key] as CollectiveDefencePlan|undefined;if(cached&&s.seconds-cached.generatedAt<.8)return cached;return any[key]=buildCollectiveDefencePlan(s,clubId,t)}
