import type { MatchCoreState } from './match-core-v2';
export type TacticalObservation={second:number;opponentId:string;channel:'left'|'centre'|'right';action:'progression'|'throughBall'|'cross'|'dribble'|'longBall'|'turnover';success:boolean;danger:number};
export type TacticalMemory={clubId:string;observations:TacticalObservation[];leftThreat:number;centralThreat:number;rightThreat:number;throughBallThreat:number;crossThreat:number;dribbleThreat:number;recommended:{pressingDelta:number;compactnessDelta:number;lineDelta:number;trapSide?:'left'|'right';protectDepth:boolean};lastUpdated:number};
const clamp=(v:number,a=-20,b=20)=>Math.max(a,Math.min(b,v));
function store(state:MatchCoreState){const any=state as any;if(!any.__tacticalMemory)any.__tacticalMemory=new Map<string,TacticalMemory>();return any.__tacticalMemory as Map<string,TacticalMemory>}
export function tacticalMemory(state:MatchCoreState,clubId:string){const s=store(state);let m=s.get(clubId);if(!m){m={clubId,observations:[],leftThreat:0,centralThreat:0,rightThreat:0,throughBallThreat:0,crossThreat:0,dribbleThreat:0,recommended:{pressingDelta:0,compactnessDelta:0,lineDelta:0,protectDepth:false},lastUpdated:0};s.set(clubId,m)}return m}
export function observeOpponentPattern(state:MatchCoreState,defendingClubId:string,o:Omit<TacticalObservation,'second'>){const m=tacticalMemory(state,defendingClubId),obs={...o,second:state.seconds};m.observations.push(obs);if(m.observations.length>160)m.observations.shift();recalculate(m,state.seconds)}
function recalculate(m:TacticalMemory,second:number){const recent=m.observations.filter(o=>second-o.second<1200),score=(pred:(o:TacticalObservation)=>boolean)=>recent.filter(pred).reduce((s,o)=>s+(o.success?1:.35)*o.danger,0)/Math.max(1,recent.filter(pred).length);m.leftThreat=score(o=>o.channel==='left');m.centralThreat=score(o=>o.channel==='centre');m.rightThreat=score(o=>o.channel==='right');m.throughBallThreat=score(o=>o.action==='throughBall');m.crossThreat=score(o=>o.action==='cross');m.dribbleThreat=score(o=>o.action==='dribble');const maxWide=Math.max(m.leftThreat,m.rightThreat),centre=m.centralThreat,depth=m.throughBallThreat>58;m.recommended={pressingDelta:clamp(m.dribbleThreat>60?7:m.throughBallThreat>65?-5:2),compactnessDelta:clamp(centre>maxWide+10?10:maxWide>centre+12?-6:2),lineDelta:clamp(depth?-9:m.crossThreat>65?-3:1),trapSide:m.leftThreat>m.rightThreat+12?'right':m.rightThreat>m.leftThreat+12?'left':undefined,protectDepth:depth};m.lastUpdated=second}
export function adaptiveDefensiveTactics(state:MatchCoreState,clubId:string,base:{pressing:number;compactness:number;defensiveLine:number}){const r=tacticalMemory(state,clubId).recommended;return{pressing:Math.max(0,Math.min(100,base.pressing+r.pressingDelta)),compactness:Math.max(0,Math.min(100,base.compactness+r.compactnessDelta)),defensiveLine:Math.max(0,Math.min(100,base.defensiveLine+r.lineDelta)),trapSide:r.trapSide,protectDepth:r.protectDepth}}
export function snapshotTacticalMemory(state:MatchCoreState){return[...store(state).entries()].map(([k,v])=>[k,{...v,observations:v.observations.map(o=>({...o})),recommended:{...v.recommended}}] as const)}
