import type { Club, Player } from './engine';
import type { MatchCoreState, LivePlayer, Vec2 } from './match-core-v2';
import { distance, livePlayer, opponentOf, teamOf } from './match-core-v2';

export type RefereeProfile={id:string;name:string;strictness:number;advantage:number;cardThreshold:number;penaltyThreshold:number;varReliance:number;homeBias:number;communication:number;fitness:number;experience:number};
export type FoulContext={tackler:LivePlayer;victim:LivePlayer;position:Vec2;fromBehind:boolean;lastMan:boolean;studsUp:boolean;deniedGoalChance:boolean;contact:number;ballContact:number;speed:number;insidePenaltyArea:boolean};
export type RefereeDecision={foul:boolean;advantage:boolean;card?:'yellow'|'red';restart?:'directFreeKick'|'indirectFreeKick'|'penalty';varReview:boolean;reason:string};
export type CompetitionMatchRules={maxSubs:number;subWindows:number;concussionSubs:number;extraTime:boolean;extraTimeSubs:number;var:boolean;goalLineTechnology:boolean;awayGoals:boolean;fiveSubRule:boolean;benchSize:number;minimumPlayers:number};
export const defaultCompetitionRules:CompetitionMatchRules={maxSubs:5,subWindows:3,concussionSubs:1,extraTime:true,extraTimeSubs:1,var:true,goalLineTechnology:true,awayGoals:false,fiveSubRule:true,benchSize:12,minimumPlayers:7};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h>>>0)};
const seeded=(seed:number,offset:number)=>{const x=Math.sin(seed*12.9898+offset*78.233)*43758.5453;return x-Math.floor(x)};
const refNames=['Anderson Dantas','Bruno Meireles','Carlos Valença','Daniel Sampaio','Eduardo Paes','Felipe Monteiro','Gustavo Nery','Henrique Bastos','Rafael Lemos','Sérgio Mota'];
export function refereeForMatch(seed:number):RefereeProfile{const idx=Math.floor(seeded(seed,1)*refNames.length),name=refNames[idx],base=hash(`${name}-${seed}`);return{id:`ref-${base}`,name,strictness:Math.round(35+seeded(base,2)*45),advantage:Math.round(35+seeded(base,3)*55),cardThreshold:Math.round(38+seeded(base,4)*48),penaltyThreshold:Math.round(40+seeded(base,5)*45),varReliance:Math.round(45+seeded(base,6)*50),homeBias:Math.round((seeded(base,7)-.5)*8),communication:Math.round(40+seeded(base,8)*50),fitness:Math.round(55+seeded(base,9)*40),experience:Math.round(35+seeded(base,10)*60)};}
export function analyseFoul(state:MatchCoreState,ref:RefereeProfile,c:FoulContext,rng=Math.random):RefereeDecision{const recklessness=c.contact*.34+c.speed*.22+(c.fromBehind?18:0)+(c.studsUp?32:0)+(c.deniedGoalChance?15:0)-c.ballContact*.28;const foulThreshold=46-ref.strictness*.12;const foul=recklessness+rng()*18>foulThreshold;if(!foul)return{foul:false,advantage:false,varReview:false,reason:'Contato considerado legal.'};const cardScore=recklessness+ref.strictness*.18+(c.lastMan?18:0)+(c.deniedGoalChance?22:0),red=cardScore>88||(c.studsUp&&cardScore>76)||(c.deniedGoalChance&&c.lastMan&&cardScore>72),yellow=!red&&cardScore>ref.cardThreshold+22;const attacking=teamOf(state,c.victim.clubId),opponent=opponentOf(state,c.victim.clubId),futureControl=(attacking.momentum-opponent.momentum)+attacking.passSuccess*.15;const advantage=ref.advantage+rng()*25>62&&futureControl>-8&&!c.insidePenaltyArea&&!red;const varReview=Boolean((c.insidePenaltyArea||red||c.deniedGoalChance)&&ref.varReliance+rng()*30>68);return{foul:true,advantage,card:red?'red':yellow?'yellow':undefined,restart:c.insidePenaltyArea?'penalty':'directFreeKick',varReview,reason:red?'Falta grave/expulsão possível.':yellow?'Infração imprudente com advertência.':advantage?'Vantagem aplicada.':'Falta assinalada.'};}
export function applyRefereeDecision(state:MatchCoreState,decision:RefereeDecision,tacklerId:string,victimId:string){const tackler=livePlayer(state,tacklerId),victim=livePlayer(state,victimId);if(!tackler||!victim||!decision.foul)return;const team=teamOf(state,tackler.clubId);team.fouls++;state.memory.recentFouls.push({clubId:tackler.clubId,second:state.seconds});if(state.memory.recentFouls.length>20)state.memory.recentFouls.shift();if(decision.card==='yellow'){tackler.yellowCards++;team.yellowCards++;if(tackler.yellowCards>=2){tackler.sentOff=true;tackler.onPitch=false;team.redCards++}}else if(decision.card==='red'){tackler.sentOff=true;tackler.onPitch=false;team.redCards++}if(!decision.advantage&&decision.restart)state.restart={type:decision.restart==='penalty'?'penalty':'freeKick',clubId:victim.clubId,position:{...victim.position}};}
export function isOffsideAtPass(state:MatchCoreState,attacker:LivePlayer,receiver:LivePlayer,ballPosition:Vec2){if(attacker.clubId!==receiver.clubId)return false;const defending=opponentOf(state,attacker.clubId),defenders=defending.players.filter(p=>p.onPitch&&!p.sentOff).sort((a,b)=>a.position.x-b.position.x),attackingRight=teamOf(state,attacker.clubId).attackingRight;if(defenders.length<2)return false;const line=attackingRight?defenders[defenders.length-2].position.x:defenders[1].position.x;if(attackingRight){if(receiver.position.x<=state.pitch.length/2)return false;return receiver.position.x>line&&receiver.position.x>ballPosition.x+.15}if(receiver.position.x>=state.pitch.length/2)return false;return receiver.position.x<line&&receiver.position.x<ballPosition.x-.15;}
export type VarIncident={type:'goal'|'penalty'|'redCard'|'mistakenIdentity';original:'given'|'notGiven';confidence:number;clearError:number};
export function reviewVAR(ref:RefereeProfile,incident:VarIncident,rng=Math.random){const threshold=incident.type==='goal'?70:incident.type==='penalty'?74:78,reviewQuality=ref.experience*.35+ref.varReliance*.4+incident.confidence*.25,overturn=incident.clearError+reviewQuality*.18+rng()*14>threshold;return{overturn,final:overturn?(incident.original==='given'?'notGiven':'given'):incident.original,delaySeconds:45+Math.round(rng()*85)};}
export type SubstitutionDecision={outId:string;inId:string;reason:'fatigue'|'injury'|'yellowRisk'|'tactical'|'performance'|'timeWaste';window:boolean};
function benchCandidate(club:Club,benchIds:string[],out:Player,reason:SubstitutionDecision['reason']){const bench=club.players.filter(p=>benchIds.includes(p.id));const positional=(p:Player)=>p.position===out.position?25:['CM','DM','AM'].includes(p.position)&&['CM','DM','AM'].includes(out.position)?12:0;return bench.sort((a,b)=>score(b)-score(a))[0];function score(p:Player){let x=p.currentAbility+positional(p)+p.condition*.18+p.morale*.08;if(reason==='tactical')x+=p.attributes.decisions*.1+p.attributes.pace*.08;if(reason==='fatigue')x+=p.attributes.stamina*.08;return x}}
export function suggestSubstitution(state:MatchCoreState,club:Club,rules=defaultCompetitionRules):SubstitutionDecision|undefined{const team=teamOf(state,club.id);if(team.substitutionsUsed>=rules.maxSubs+(state.phase.startsWith('extraTime')?rules.extraTimeSubs:0)||team.substitutionWindowsUsed>=rules.subWindows)return;const minute=state.seconds/60,live=team.players.filter(p=>p.onPitch&&!p.sentOff);let target=live.sort((a,b)=>subRisk(b)-subRisk(a))[0];if(!target)return;let reason:SubstitutionDecision['reason']='performance';const fatigue=target.fatigue+(100-target.condition)*.65;if(fatigue>62&&minute>52)reason='fatigue';else if(target.yellowCards>0&&minute>58)reason='yellowRisk';else if(minute>64&&((team.score<opponentOf(state,club.id).score)||team.momentum<38))reason='tactical';else if(minute>82&&team.score>opponentOf(state,club.id).score)reason='timeWaste';else if(minute<58)return;const out=club.players.find(p=>p.id===target.playerId),incoming=out?benchCandidate(club,team.benchIds,out,reason):undefined;if(!out||!incoming)return;return{outId:out.id,inId:incoming.id,reason,window:true};function subRisk(p:LivePlayer){return p.fatigue*.55+(100-p.condition)*.32+p.yellowCards*22+(minute>65?8:0)}}
export function applySubstitution(state:MatchCoreState,club:Club,d:SubstitutionDecision){const team=teamOf(state,club.id),out=team.players.find(p=>p.playerId===d.outId),incoming=club.players.find(p=>p.id===d.inId);if(!out||!incoming||!out.onPitch||!team.benchIds.includes(incoming.id))return false;out.onPitch=false;const next:LivePlayer={...out,playerId:incoming.id,role:out.role,condition:incoming.condition,fatigue:0,yellowCards:0,sentOff:false,onPitch:true,minutesPlayed:0,currentIntent:'holdShape'};team.players.push(next);team.benchIds=team.benchIds.filter(id=>id!==incoming.id);team.substitutionsUsed++;if(d.window)team.substitutionWindowsUsed++;return true;}
export function legalMatchContinuation(state:MatchCoreState,rules=defaultCompetitionRules){const home=state.home.players.filter(p=>p.onPitch&&!p.sentOff).length,away=state.away.players.filter(p=>p.onPitch&&!p.sentOff).length;return home>=rules.minimumPlayers&&away>=rules.minimumPlayers;}
