import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf } from './match-core-v2';
import { collectiveDefencePlan, defensiveAssignment } from './match-collective-defence-v2';
export type MarkingMode='zonal'|'man'|'hybrid';
export type MarkingInstruction={playerId:string;mode:MarkingMode;target:Vec2;opponentId?:string;handoff?:boolean;communicationFailure?:boolean;urgency:number;reason:string};
export type MarkingSnapshot={clubId:string;mode:MarkingMode;instructions:MarkingInstruction[];generatedAt:number;handoffs:number;failures:number};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function playerData(club:Club,id:string){return club.players.find(p=>p.id===id)}
function modeFor(club:Club):MarkingMode{const t=club.tactics as any;if(t.marking==='man'||t.marking==='zonal'||t.marking==='hybrid')return t.marking;const press=club.tactics.pressing,line=club.tactics.defensiveLine;return press>=70&&line>=60?'hybrid':press<40?'zonal':'hybrid'}
function threatScore(state:MatchCoreState,clubId:string,o:LivePlayer){const own=teamOf(state,clubId),goalX=own.attackingRight?0:state.pitch.length,central=1-Math.min(1,Math.abs(o.position.y-state.pitch.width/2)/(state.pitch.width/2)),goalThreat=1-Math.min(1,Math.abs(o.position.x-goalX)/state.pitch.length);return goalThreat*.52+central*.22+(o.currentIntent==='run'||o.currentIntent==='receive'?0.16:0)+(o.role==='advancedForward'||o.role==='shadowStriker'||o.role==='insideForward'?0.1:0)}
function zoneTarget(state:MatchCoreState,p:LivePlayer){const ball=state.ball.position,home=p.homeSlot,shiftX=(ball.x-state.pitch.length/2)*.18,shiftY=(ball.y-state.pitch.width/2)*.24;return{x:clamp(home.x+shiftX,1,state.pitch.length-1),y:clamp(home.y+shiftY,1,state.pitch.width-1)}}
function coverSide(state:MatchCoreState,clubId:string,p:LivePlayer,o:LivePlayer):Vec2{const own=teamOf(state,clubId),goalX=own.attackingRight?0:state.pitch.length,goal={x:goalX,y:state.pitch.width/2},dx=goal.x-o.position.x,dy=goal.y-o.position.y,m=Math.hypot(dx,dy)||1,offset=1.8;return{x:o.position.x+dx/m*offset,y:o.position.y+dy/m*offset}}
function communicationScore(a:Player,b:Player|undefined,pa:LivePlayer,pb:LivePlayer|undefined){const base=a.attributes.decisions*.35+a.attributes.positioning*.35+(100-pa.fatigue)*.15+a.morale*.15;if(!b||!pb)return base;return(base+b.attributes.decisions*.25+b.attributes.positioning*.25+(100-pb.fatigue)*.1)/1.6}
function deterministicNoise(state:MatchCoreState,key:string){let h=2166136261;for(const c of key){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}const x=Math.sin((h^state.seed)*12.9898+Math.floor(state.seconds*2)*78.233)*43758.5453;return x-Math.floor(x)}
export function markingSnapshot(state:MatchCoreState,club:Club):MarkingSnapshot{const cacheKey=club.id===state.home.clubId?'__homeMarking':'__awayMarking',any=state as any,cached=any[cacheKey] as MarkingSnapshot|undefined;if(cached&&state.seconds-cached.generatedAt<.8)return cached;const own=teamOf(state,club.id),opp=opponentOf(state,club.id),mode=modeFor(club),plan=collectiveDefencePlan(state,club.id,{pressing:club.tactics.pressing,defensiveLine:club.tactics.defensiveLine,compactness:own.compactness}),defenders=own.players.filter(p=>p.onPitch&&!p.sentOff),attackers=opp.players.filter(p=>p.onPitch&&!p.sentOff),usedOpp=new Set<string>(),instructions:MarkingInstruction[]=[];let handoffs=0,failures=0;
 const threats=[...attackers].sort((a,b)=>threatScore(state,club.id,b)-threatScore(state,club.id,a));
 for(const p of defenders){const src=playerData(club,p.playerId);if(!src)continue;const collective=defensiveAssignment(plan,p.playerId);if(collective&&['press','doubleTeam','screen','offsideLine'].includes(collective.task)){instructions.push({playerId:p.playerId,mode,target:{...collective.target},opponentId:collective.opponentId,urgency:collective.urgency,reason:`responsabilidade coletiva: ${collective.reason}`});continue}
   if(mode==='zonal'){instructions.push({playerId:p.playerId,mode,target:zoneTarget(state,p),urgency:56,reason:'proteger zona e preservar referências coletivas'});continue}
   const candidates=threats.filter(o=>!usedOpp.has(o.playerId)).map(o=>({o,score:threatScore(state,club.id,o)*55-distance(p.position,o.position)*1.15+(Math.abs(p.homeSlot.y-o.position.y)<12?8:0)})).sort((a,b)=>b.score-a.score);const pick=candidates[0];if(!pick||pick.score<5){instructions.push({playerId:p.playerId,mode,target:zoneTarget(state,p),urgency:50,reason:'sem ameaça individual suficientemente perigosa'});continue}
   const o=pick.o,zoneDist=distance(zoneTarget(state,p),o.position),hybridStay=mode==='hybrid'&&zoneDist>18&&threatScore(state,club.id,o)<.62;if(hybridStay){instructions.push({playerId:p.playerId,mode,target:zoneTarget(state,p),urgency:54,reason:'híbrido: ameaça fora da zona primária'});continue}
   usedOpp.add(o.playerId);let target=coverSide(state,club.id,p,o),handoff=false,communicationFailure=false;const mate=defenders.filter(x=>x.playerId!==p.playerId).sort((a,b)=>distance(a.position,o.position)-distance(b.position,o.position))[0],mateData=mate?playerData(club,mate.playerId):undefined;if(mate&&distance(mate.position,o.position)+3<distance(p.position,o.position)&&distance(p.position,p.homeSlot)>10){handoff=true;handoffs++;const comm=communicationScore(src,mateData,p,mate),failureChance=clamp((65-comm)*.009+(p.fatigue+mate.fatigue)*.0015,0,.28);if(deterministicNoise(state,`${p.playerId}-${mate.playerId}-${o.playerId}`)<failureChance){communicationFailure=true;failures++;target={x:(p.position.x+mate.position.x)/2,y:(p.position.y+mate.position.y)/2}}else target=zoneTarget(state,p)}instructions.push({playerId:p.playerId,mode,target,opponentId:o.playerId,handoff,communicationFailure,urgency:Math.round(58+threatScore(state,club.id,o)*35),reason:communicationFailure?'falha de comunicação na troca de marcação':handoff?'troca de marcação executada':mode==='man'?'marcação individual':'encaixe híbrido sobre ameaça'})}
 const snap={clubId:club.id,mode,instructions,generatedAt:state.seconds,handoffs,failures};any[cacheKey]=snap;return snap}
export function markingInstruction(state:MatchCoreState,club:Club,playerId:string){return markingSnapshot(state,club).instructions.find(x=>x.playerId===playerId)}
