import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf, territorialControlAt } from './match-core-v2';
import { applyHandballDecision, evaluateHandball } from './match-handball-v2';
export type ReceptionType='cushion'|'openBody'|'backToGoal'|'firstTime'|'flick'|'leave';
export type ReceptionOutcome={playerId:string;type:ReceptionType;success:boolean;control:number;error:number;nextPosition:Vec2;bodyFacing:number;looseBall:boolean;reason:string;handball?:boolean};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const attr=(p:Player,key:string,fallback:number)=>Number((p.attributes as any)[key]??fallback);
function nearestPressure(state:MatchCoreState,p:LivePlayer){const opp=opponentOf(state,p.clubId).players.filter(x=>x.onPitch&&!x.sentOff);const d=opp.length?Math.min(...opp.map(x=>distance(x.position,p.position))):20;return clamp((6-d)/6*100,0,100)}
function attackingDir(state:MatchCoreState,id:string){return teamOf(state,id).attackingRight?1:-1}
function chooseType(state:MatchCoreState,p:LivePlayer,src:Player,ballSpeed:number,ballHeight:number,pressure:number,rng:()=>number):ReceptionType{const dir=attackingDir(state,p.clubId),goalSide=(p.position.x-state.ball.position.x)*dir>0,firstTouch=attr(src,'firstTouch',src.attributes.technique),flair=attr(src,'flair',src.attributes.technique);if(ballHeight>1.1&&flair>72&&pressure>55)return'flick';if(ballSpeed<10&&pressure<35&&firstTouch>58)return'openBody';if(goalSide&&pressure>48)return'backToGoal';if(firstTouch>82&&src.attributes.decisions>76&&ballSpeed<17&&pressure<55)return'firstTime';if(pressure<25&&src.attributes.decisions>70&&rng()<.04)return'leave';return'cushion'}
export function evaluateReception(state:MatchCoreState,club:Club,p:LivePlayer,ballSpeed:number,ballHeight:number,rng=Math.random):ReceptionOutcome{const src=club.players.find(x=>x.id===p.playerId);if(!src)return{playerId:p.playerId,type:'cushion',success:true,control:50,error:0,nextPosition:{...p.position},bodyFacing:p.facing,looseBall:false,reason:'fallback sem atributos'};if(ballHeight>=.6&&ballHeight<=1.75&&ballSpeed>6){const armExtension=16+rng()*76,armMovementTowardBall=rng()*100,deflectionBeforeContact=rng()<.16,supportingArm=p.currentIntent==='tackle'&&rng()<.24,deliberate=armMovementTowardBall>84&&rng()<.3,ctx={player:p,playerData:src,ballPosition:{...state.ball.position},ballSpeed,armExtension,armMovementTowardBall,distanceFromKick:Math.min(20,ballSpeed*.55),deflectionBeforeContact,supportingArm,deliberate},hand=evaluateHandball(state,ctx,rng);if(hand.contact&&hand.offence){applyHandballDecision(state,ctx,hand);return{playerId:p.playerId,type:'leave',success:false,control:0,error:0,nextPosition:{...p.position},bodyFacing:p.facing,looseBall:true,reason:`mão: ${hand.reason}`,handball:true}}}
 const pressure=nearestPressure(state,p),firstTouch=attr(src,'firstTouch',src.attributes.technique),balance=attr(src,'balance',65),strength=attr(src,'strength',60),agility=attr(src,'agility',src.attributes.pace),type=chooseType(state,p,src,ballSpeed,ballHeight,pressure,rng),territory=territorialControlAt(state,p.position),own=p.clubId===state.home.clubId?territory.home:territory.away;let control=firstTouch*.42+src.attributes.technique*.23+src.attributes.decisions*.14+balance*.07+agility*.06+(100-pressure)*.11+own*8-ballSpeed*.55-ballHeight*4.5-p.fatigue*.12;if(type==='openBody')control+=7;if(type==='backToGoal')control+=strength*.08-pressure*.04;if(type==='firstTime')control+=firstTouch>80?5:-10;if(type==='flick')control+=attr(src,'flair',60)*.09-pressure*.05;if(type==='leave')control=82;control=clamp(control,3,98);const roll=rng()*100,success=roll<control,error=success?(100-control)/100*(.3+rng()*1.2):(1.1+(100-control)/35+rng()*2.4),dir=attackingDir(state,p.clubId),bodyFacing=type==='openBody'?(dir>0?0:Math.PI):type==='backToGoal'?(dir>0?Math.PI:0):p.facing,nextPosition={x:clamp(p.position.x+(type==='openBody'?dir*1.8:0)+(rng()-.5)*error,0,state.pitch.length),y:clamp(p.position.y+(rng()-.5)*error,0,state.pitch.width)},looseBall=!success&&error>1.5;return{playerId:p.playerId,type,success,control,error,nextPosition,bodyFacing,looseBall,reason:`${type}: controle ${control.toFixed(0)}, pressão ${pressure.toFixed(0)}, velocidade ${ballSpeed.toFixed(1)}, altura ${ballHeight.toFixed(1)}`}}
export function applyReception(state:MatchCoreState,outcome:ReceptionOutcome){const p=[...state.home.players,...state.away.players].find(x=>x.playerId===outcome.playerId);if(!p)return;const any=state as any;if(!any.__receptions)any.__receptions=[];any.__receptions.push({...outcome,second:state.seconds});if(any.__receptions.length>300)any.__receptions.splice(0,any.__receptions.length-300);if(outcome.handball)return;p.facing=outcome.bodyFacing;if(outcome.type==='leave'){state.ball.ownerId=undefined;return}if(outcome.looseBall){state.ball.ownerId=undefined;state.ball.position={...outcome.nextPosition};state.ball.velocity={x:(outcome.nextPosition.x-p.position.x)*2,y:(outcome.nextPosition.y-p.position.y)*2};return}p.position={...outcome.nextPosition};state.ball.ownerId=p.playerId;state.ball.position={...p.position};state.ball.velocity={...p.velocity};state.possessionClubId=p.clubId}
export function receptionLog(state:MatchCoreState){return[...(((state as any).__receptions??[]) as any[])]}
