import type { Club, Player } from './engine';
import type { LivePlayer, MatchCoreState, Vec2 } from './match-core-v2';
import { distance, opponentOf, teamOf } from './match-core-v2';
import { predictBall } from './match-ball-physics-v2';
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function ownGoal(state:MatchCoreState,clubId:string):Vec2{return{x:teamOf(state,clubId).attackingRight?0:state.pitch.length,y:state.pitch.width/2}}
function goalLineX(state:MatchCoreState,clubId:string){return teamOf(state,clubId).attackingRight?1.2:state.pitch.length-1.2}
function player(club:Club,id:string){return club.players.find(p=>p.id===id)}
export type GoalkeeperDecision={kind:'holdLine'|'setPosition'|'sweep'|'claimCross'|'closeAngle'|'recover';target:Vec2;urgency:number;reason:string};
export function goalkeeperDecision(state:MatchCoreState,club:Club,gk:LivePlayer):GoalkeeperDecision{const src=player(club,gk.playerId),goal=ownGoal(state,club.id),ball=state.ball.position,distGoal=distance(ball,goal),opp=opponentOf(state,club.id),opponentOwner=state.ball.ownerId?opp.players.find(x=>x.playerId===state.ball.ownerId):undefined;const predicted=predictBall(state,2.8,.12),towardGoal=predicted.find(p=>Math.abs(p.position.x-goal.x)<2.2&&Math.abs(p.position.y-goal.y)<state.pitch.goalWidth/2+1.5),boxX=teamOf(state,club.id).attackingRight?ball.x<state.pitch.penaltyAreaDepth:ball.x>state.pitch.length-state.pitch.penaltyAreaDepth,inBox=boxX&&Math.abs(ball.y-state.pitch.width/2)<state.pitch.penaltyAreaWidth/2;if(!state.ball.ownerId&&inBox){const earliest=predicted.find(p=>p.height<2.4&&distance(gk.position,p.position)<8);if(earliest)return{kind:'claimCross',target:{...earliest.position},urgency:88,reason:'trajetória aérea/bola solta atacável dentro da área'}}if(opponentOwner&&distGoal<20){const line={x:goalLineX(state,club.id),y:clamp(ball.y,goal.y-state.pitch.goalWidth/2+0.4,goal.y+state.pitch.goalWidth/2-0.4)},ratio=clamp((20-distGoal)/20,0,1),target={x:line.x+(ball.x-line.x)*ratio*.34,y:line.y+(ball.y-line.y)*ratio*.24};return{kind:'closeAngle',target,urgency:82,reason:'reduzir ângulo de finalização'}}if(towardGoal)return{kind:'setPosition',target:{x:goalLineX(state,club.id),y:clamp(towardGoal.position.y,goal.y-state.pitch.goalWidth/2+.3,goal.y+state.pitch.goalWidth/2-.3)},urgency:94,reason:'bola projetada em direção ao gol'};const sweeper=src&&(gk.role==='sweeperKeeper'||src.attributes.positioning>72)&&!state.ball.ownerId&&distGoal<34;if(sweeper){const p=predicted.find(x=>x.height<1.8&&distance(gk.position,x.position)<10);if(p)return{kind:'sweep',target:{...p.position},urgency:70,reason:'goleiro-líbero antecipa bola nas costas da defesa'}}const angle=Math.atan2(ball.y-goal.y,Math.abs(ball.x-goal.x)||1),depth=distGoal>34?3.2:distGoal>24?4.4:5.8,target={x:goal.x+(teamOf(state,club.id).attackingRight?depth:-depth),y:clamp(goal.y+Math.tan(angle)*depth,goal.y-state.pitch.goalWidth/2+.5,goal.y+state.pitch.goalWidth/2-.5)};return{kind:'holdLine',target,urgency:45,reason:'posicionamento por bissetriz do ângulo bola-gol'}}
export function goalkeeperCanClaim(state:MatchCoreState,club:Club,gk:LivePlayer){const d=goalkeeperDecision(state,club,gk),src=player(club,gk.playerId);if(!src||!['claimCross','sweep'].includes(d.kind))return false;const reach=distance(gk.position,d.target)/(4.2+src.attributes.pace*.025),pred=predictBall(state,2,.1).find(x=>distance(x.position,d.target)<1.2);return !!pred&&reach<=pred.time+.25}
