import type { Fixture, MatchEvent, World } from './engine';
import type { MatchBroadcastTape, BroadcastAction } from './match-broadcast-v2';
import type { MatchStory, MatchStoryAction, MatchStoryActionType, MatchStoryPoint } from './matchday-story-v1';
import { matchStories } from './matchday-story-v1';
import { playerMatchLabel } from './player-shirt-number-v1';

const player=(world:World,id?:string)=>id?world.clubs.flatMap(c=>c.players).find(p=>p.id===id):undefined;
const label=(world:World,id?:string)=>{const p=player(world,id);return p?playerMatchLabel(p):''};
const pct=(p:{x:number;y:number}|undefined,tape:MatchBroadcastTape):MatchStoryPoint|undefined=>p?{x:Math.max(2,Math.min(98,p.x/tape.pitch.length*100)),y:Math.max(3,Math.min(97,p.y/tape.pitch.width*100))}:undefined;
const mappedType=(type:string):MatchStoryActionType=>({receive:'pass',pass:'pass',progressivePass:'through',throughBall:'through',switchPlay:'switch',longBall:'longBall',cross:'cross',carry:'carry',dribble:'dribble',press:'press',tackle:'tackle',intercept:'intercept',foul:'foul',shot:'shot',save:'save',goal:'goal',frameHit:'rebound',turnover:'loose',assist:'pass',restart:'restart',kickoff:'restart',fulltime:'restart'} as Record<string,MatchStoryActionType>)[type]??'pass';
function human(world:World,a:BroadcastAction){const who=label(world,a.playerId),target=label(world,a.targetPlayerId);switch(a.type){case'receive':return who?`${who} domina a bola e levanta a cabeça.`:'A bola é dominada e a jogada continua.';case'pass':return who&&target?`${who} toca para ${target}.`:who?`${who} faz o passe.`:'A equipe troca passes.';case'progressivePass':return who&&target?`${who} encontra ${target} entre as linhas.`:`${who||'O meio-campista'} acelera a jogada com passe vertical.`;case'throughBall':return who&&target?`${who} enfia para ${target} atacar o espaço.`:`${who||'O jogador'} encontra um passe em profundidade.`;case'switchPlay':return `${who||'O jogador'} vira o jogo e muda o corredor do ataque.`;case'longBall':return target?`${who||'O jogador'} lança longo procurando ${target}.`:`${who||'O jogador'} busca a bola longa.`;case'cross':return target?`${who||'O jogador'} cruza procurando ${target}.`:`${who||'O jogador'} levanta a bola na área.`;case'carry':return `${who||'O portador'} conduz a bola e ganha terreno.`;case'dribble':return `${who||'O jogador'} parte para cima e supera a pressão no drible.`;case'press':return `${who||'O marcador'} acelera a pressão sobre a bola.`;case'tackle':return `${who||'O defensor'} entra no tempo da bola para desarmar.`;case'intercept':return `${who||'O defensor'} lê o passe e intercepta.`;case'foul':return `${who||'O jogador'} chega na disputa e o árbitro marca a falta.`;case'turnover':return `${who||'O jogador'} perde a posse e abre a transição adversária.`;case'assist':return who&&target?`${who} deixa ${target} em condição de finalizar.`:`${who||'O jogador'} produz o passe decisivo.`;case'shot':return `${who||'O atacante'} prepara o corpo e finaliza${a.value?` — xG ${a.value.toFixed(2)}`:''}.`;case'frameHit':return 'A bola explode na trave e continua viva!';case'save':return target?`${who||'O goleiro'} reage ao chute de ${target} e faz a defesa.`:`${who||'O goleiro'} reage e faz a defesa.`;case'goal':return `${who||'O atacante'} finaliza e É GOL!`;default:return a.detail||'A jogada continua.'}}
function eventType(a:BroadcastAction):MatchEvent['type']{return(a.type==='goal'?'goal':a.type==='shot'?'shot':a.type==='save'?'save':'chance') as MatchEvent['type']}
export function broadcastStories(world:World,fixture:Fixture):MatchStory[]{const tape=(fixture as Fixture&{broadcastTape?:MatchBroadcastTape}).broadcastTape;if(!tape?.actions?.length)return matchStories(world,fixture,fixture.events??[]);const stories:MatchStory[]=[];let last:MatchStoryPoint={x:50,y:50};for(const a of tape.actions){const from=pct(a.from,tape)??last,to=pct(a.to??a.position,tape)??from;const text=human(world,a);const ev:MatchEvent={minute:Math.max(0,Math.floor(a.second/60)),type:eventType(a),clubId:a.clubId,playerId:a.playerId,secondaryPlayerId:a.targetPlayerId,text,...(a.value!==undefined?{xg:a.value}: {})};const extended=ev as MatchEvent&{second?:number;broadcastType?:string};extended.second=a.second;extended.broadcastType=a.type;const action:MatchStoryAction={type:mappedType(a.type),playerId:a.playerId,targetPlayerId:a.targetPlayerId,from,to,label:text};stories.push({event:ev,actions:[action],narration:text,origin:from,target:to,assistPlayerId:a.type==='assist'?a.playerId:undefined});last=to}return stories}
export function fixtureUsesV2Broadcast(fixture:Fixture){return Boolean((fixture as Fixture&{broadcastTape?:MatchBroadcastTape}).broadcastTape?.actions?.length)}
