import type { Club, Player } from './engine';
import type { MatchCoreState, LivePlayer, Vec2 } from './match-core-v2';
import { distance, livePlayer, opponentOf, teamOf } from './match-core-v2';

export type RefereeProfile={id:string;name:string;strictness:number;advantage:number;cardThreshold:number;penaltyThreshold:number;varReliance:number;homeBias:number;communication:number;fitness:number;experience:number;consistency:number;dogsoStrictness:number;physicalTolerance:number};
export type FoulContext={tackler:LivePlayer;victim:LivePlayer;position:Vec2;fromBehind:boolean;lastMan:boolean;studsUp:boolean;deniedGoalChance:boolean;contact:number;ballContact:number;speed:number;insidePenaltyArea:boolean;twoFooted?:boolean;airborne?:boolean;late?:boolean;directionToGoal?:number;distanceToGoal?:number;coveringDefenders?:number;controlLikelihood?:number};
export type RefereeDecision={foul:boolean;advantage:boolean;card?:'yellow'|'red';restart?:'directFreeKick'|'indirectFreeKick'|'penalty';varReview:boolean;reason:string;severity:'legal'|'careless'|'reckless'|'seriousFoulPlay'|'dogso';foulScore:number;cardScore:number};
export type CompetitionMatchRules={maxSubs:number;subWindows:number;concussionSubs:number;extraTime:boolean;extraTimeSubs:number;var:boolean;goalLineTechnology:boolean;awayGoals:boolean;fiveSubRule:boolean;benchSize:number;minimumPlayers:number};
export const defaultCompetitionRules:CompetitionMatchRules={maxSubs:5,subWindows:3,concussionSubs:1,extraTime:true,extraTimeSubs:1,var:true,goalLineTechnology:true,awayGoals:false,fiveSubRule:true,benchSize:12,minimumPlayers:7};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h>>>0)};
const seeded=(seed:number,offset:number)=>{const x=Math.sin(seed*12.9898+offset*78.233)*43758.5453;return x-Math.floor(x)};
const refNames=['Anderson Dantas','Bruno Meireles','Carlos Valença','Daniel Sampaio','Eduardo Paes','Felipe Monteiro','Gustavo Nery','Henrique Bastos','Rafael Lemos','Sérgio Mota'];
export function refereeForMatch(seed:number):RefereeProfile{const idx=Math.floor(seeded(seed,1)*refNames.length),name=refNames[idx],base=hash(`${name}-${seed}`);return{id:`ref-${base}`,name,strictness:Math.round(35+seeded(base,2)*45),advantage:Math.round(35+seeded(base,3)*55),cardThreshold:Math.round(38+seeded(base,4)*48),penaltyThreshold:Math.round(40+seeded(base,5)*45),varReliance:Math.round(45+seeded(base,6)*50),homeBias:Math.round((seeded(base,7)-.5)*8),communication:Math.round(40+seeded(base,8)*50),fitness:Math.round(55+seeded(base,9)*40),experience:Math.round(35+seeded(base,10)*60),consistency:Math.round(45+seeded(base,11)*50),dogsoStrictness:Math.round(45+seeded(base,12)*45),physicalTolerance:Math.round(25+seeded(base,13)*60)};}
function dogsoScore(c:FoulContext){return(c.deniedGoalChance?25:0)+(c.lastMan?18:0)+(c.directionToGoal??50)*.18+(100-clamp((c.distanceToGoal??45)*1.8))* .16+(c.controlLikelihood??50)*.18-Math.min(4,c.coveringDefenders??1)*8}
export function analyseFoul(state:MatchCoreState,ref:RefereeProfile,c:FoulContext,rng=Math.random):RefereeDecision{const force=c.contact*.29+c.speed*2.2+(c.fromBehind?11:0)+(c.studsUp?25:0)+(c.twoFooted?24:0)+(c.airborne?12:0)+(c.late?14:0)-c.ballContact*.25;const perceptionNoise=(rng()-.5)*(28-ref.consistency*.2)+(100-ref.fitness)*.04;const foulScore=force+ref.strictness*.13-ref.physicalTolerance*.1+perceptionNoise;const foul=foulScore>43;if(!foul)return{foul:false,advantage:false,varReview:false,reason:'Contato dentro do nível físico tolerado pelo árbitro.',severity:'legal',foulScore,cardScore:0};const dogso=dogsoScore(c)+ref.dogsoStrictness*.12;const serious=(c.studsUp||c.twoFooted)&&force>70||force>94;const reckless=!serious&&(force>58||c.fromBehind&&force>50||c.late&&force>52);const severity=dogso>66?'dogso':serious?'seriousFoulPlay':reckless?'reckless':'careless';const cardScore=force+dogso*.32+ref.strictness*.12;const red=severity==='seriousFoulPlay'||severity==='dogso'&&dogso>72;const yellow=!red&&severity==='reckless';const attacking=teamOf(state,c.victim.clubId),opponent=opponentOf(state,c.victim.clubId),futureControl=(attacking.momentum-opponent.momentum)+attacking.passSuccess*.15;const advantage=ref.advantage+rng()*25>62&&futureControl>-8&&!c.insidePenaltyArea&&!red;const varReview=Boolean((c.insidePenaltyArea||red||severity==='dogso')&&ref.varReliance+rng()*30>68);return{foul:true,advantage,card:red?'red':yellow?'yellow':undefined,restart:c.insidePenaltyArea?'penalty':'directFreeKick',varReview,severity,foulScore,cardScore,reason:red?(severity==='dogso'?'DOGSO: oportunidade clara de gol impedida.':'Jogo brusco grave com força/risco excessivo.'):yellow?'Entrada imprudente: advertência por risco e intensidade.':advantage?'Infração detectada, vantagem aplicada.':'Infração descuidada assinalada.'};}
export function applyRefereeDecision(state:MatchCoreState,decision:RefereeDecision,tacklerId:string,victimId:string){const tackler=livePlayer(state,tacklerId),victim=livePlayer(state,victimId);if(!tackler||!victim||!decision.foul)return;const team=teamOf(state,tackler.clubId);team.fouls++;state.memory.recentFouls.push({clubId:tackler.clubId,second:state.seconds});if(state.memory.recentFouls.length>20)state.memory.recentFouls.shift();if(decision.card==='yellow'){tackler.yellowCards++;team.yellowCards++;if(tackler.yellowCards>=2){tackler.sentOff=true;tackler.onPitch=false;team.redCards++}}else if(decision.card==='red'){tackler.sentOff=true;tackler.onPitch=false;team.redCards++}if(!decision.advantage&&decision.restart)state.restart={type:decision.restart==='penalty'?'penalty':'freeKick',clubId:victim.clubId,position:{...victim.position}};const any=state as any;if(!any.__refereeLog)any.__refereeLog=[];any.__refereeLog.push({second:state.seconds,tacklerId,victimId,...decision});if(any.__refereeLog.length>200)any.__refereeLog.shift();}
export function isOffsideAtPass(state:MatchCoreState,attacker:LivePlayer,receiver:LivePlayer,ballPosition:Vec2){if(attacker.clubId!==receiver.clubId)return false;const defending=opponentOf(state,attacker.clubId),defenders=defending.players.filter(p=>p.onPitch&&!p.sentOff).sort((a,b)=>a.position.x-b.position.x),attackingRight=teamOf(state,attacker.clubId).attackingRight;if(defenders.length<2)return false;const line=attackingRight?defenders[defenders.length-2].position.x:defenders[1].position.x;if(attackingRight){if(receiver.position.x<=state.pitch.length/2)return false;return receiver.position.x>line&&receiver.position.x>ballPosition.x+.15}if(receiver.position.x>=state.pitch.length/2)return false;return receiver.position.x<line&&receiver.position.x<ballPosition.x-.15;}
export type VarIncident={type:'goal'|'penalty'|'redCard'|'mistakenIdentity';original:'given'|'notGiven';confidence:number;clearError:number};
export function reviewVAR(ref:RefereeProfile,incident:VarIncident,rng=Math.random){const threshold=incident.type==='goal'?70:incident.type==='penalty'?74:78,reviewQuality=ref.experience*.35+ref.varReliance*.4+incident.confidence*.25,overturn=incident.clearError+reviewQuality*.18+rng()*14>threshold;return{overturn,final:overturn?(incident.original==='given'?'notGiven':'given'):incident.original,delaySeconds:45+Math.round(rng()*85)};}
export type SubstitutionDecision={outId:string;inId:string;reason:'fatigue'|'injury'|'yellowRisk'|'tactical'|'performance'|'timeWaste';window:boolean};
function benchCandidate(club:Club,benchIds:string[],out:Player,reason:SubstitutionDecision['reason']){const bench=club.players.filter(p=>benchIds.includes(p.id));const positional=(p:Player)=>p.position===out.position?25:['CM','DM','AM'].includes(p.position)&&['CM','DM','AM'].includes(out.position)?12:0;return bench.sort((a,b)=>score(b)-score(a))[0];function score(p:Player){let x=p.currentAbility+positional(p)+p.condition*.18+p.morale*.08;if(reason==='tactical')x+=p.attributes.decisions*.1+p.attributes.pace*.08;if(reason==='fatigue')x+=p.attributes.stamina*.08;return x}}
export function suggestSubstitution(state:MatchCoreState,club:Club,rules=defaultCompetitionRules):SubstitutionDecision|undefined{const team=teamOf(state,club.id);if(team.substitutionsUsed>=rules.maxSubs+(state.phase.startsWith('extraTime')?rules.extraTimeSubs:0)||team.substitutionWindowsUsed>=rules.subWindows)return;const minute=state.seconds/60,live=team.players.filter(p=>p.onPitch&&!p.sentOff);let target=live.sort((a,b)=>subRisk(b)-subRisk(a))[0];if(!target)return;let reason:SubstitutionDecision['reason']='performance';const injury=((((state as any).__matchInjuries??[]) as any[]).filter(i=>i.playerId===target.playerId&&i.forcedOff).at(-1));const fatigue=target.fatigue+(100-target.condition)*.65;if(injury)reason='injury';else if(fatigue>62&&minute>52)reason='fatigue';else if(target.yellowCards>0&&minute>58)reason='yellowRisk';else if(minute>64&&((team.score<opponentOf(state,club.id).score)||team.momentum<38))reason='tactical';else if(minute>82&&team.score>opponentOf(state,club.id).score)reason='timeWaste';else if(minute<58)return;const out=club.players.find(p=>p.id===target.playerId),incoming=out?benchCandidate(club,team.benchIds,out,reason):undefined;if(!out||!incoming)return;return{outId:out.id,inId:incoming.id,reason,window:true};function subRisk(p:LivePlayer){const inj=((((state as any).__matchInjuries??[]) as any[]).some(i=>i.playerId===p.playerId&&i.forcedOff));return(inj?1000:0)+p.fatigue*.55+(100-p.condition)*.32+p.yellowCards*22+(minute>65?8:0)}}
export function applySubstitution(state:MatchCoreState,club:Club,d:SubstitutionDecision){const team=teamOf(state,club.id),out=team.players.find(p=>p.playerId===d.outId),incoming=club.players.find(p=>p.id===d.inId);if(!out||!incoming||!out.onPitch||!team.benchIds.includes(incoming.id))return false;out.onPitch=false;const next:LivePlayer={...out,playerId:incoming.id,role:out.role,condition:incoming.condition,fatigue:0,yellowCards:0,sentOff:false,onPitch:true,minutesPlayed:0,currentIntent:'holdShape'};team.players.push(next);team.benchIds=team.benchIds.filter(id=>id!==incoming.id);team.substitutionsUsed++;if(d.window)team.substitutionWindowsUsed++;return true;}
export function legalMatchContinuation(state:MatchCoreState,rules=defaultCompetitionRules){const home=state.home.players.filter(p=>p.onPitch&&!p.sentOff).length,away=state.away.players.filter(p=>p.onPitch&&!p.sentOff).length;return home>=rules.minimumPlayers&&away>=rules.minimumPlayers;}
