import './media-hub-v7.css';
import type { World } from './engine';
import { userManager } from './manager-character';
import { managerInteractionState, pendingManagerInteractions, resolveManagerInteraction, type ManagerInteraction } from './manager-interactions';
import { recentHumanConversations } from './institutional-memory';
import { answerPressQuestion, createPressConferenceFromSportNews, pressConferences } from './football-press-room-v1';
import { latestSportNews } from './sport-news-weekly-v2';
import { renderSportNewsIssue, SPORT_NEWS_CSS } from './sport-news-view-v1';
import { worldCore, type WorldEvent } from './world-core-v2';
import { dailyCalendar } from './daily-simulation';

let activeTab:'daily'|'interviews'|'conference'|'newspaper'='daily';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function world(){return window.__touchlineWorld as World|undefined}
function clubId(w:World){return userManager(w)?.currentClubId??w.clubs[0]?.id}
function clubName(w:World,id?:string){return w.clubs.find(c=>c.id===id)?.name??'Clube'}
function mediaEvents(w:World,id:string){return [...worldCore(w).events].filter(e=>e.type==='MediaStoryPublished'&&(!e.entityIds.length||e.entityIds.includes(id))).slice(-50).reverse()}
function eventHeadline(e:WorldEvent){return String(e.payload.headline??e.payload.summary??e.payload.title??'Nova repercussão na imprensa')}
function eventDeck(e:WorldEvent){return String(e.payload.deck??e.payload.context??e.payload.description??'Repercussão produzida pelo universo da carreira.')}
function mediaInteractions(w:World,id:string){return managerInteractionState(w).interactions.filter(i=>i.clubId===id&&i.kind==='media').slice(-20).reverse()}
function tabButton(id:typeof activeTab,label:string,count?:number){return `<button data-media-tab="${id}" class="${activeTab===id?'active':''}">${label}${typeof count==='number'?` · ${count}`:''}</button>`}
function dailyPane(w:World,id:string){const events=mediaEvents(w,id),pending=pendingManagerInteractions(w,id).filter(i=>i.kind==='media');const profile=managerInteractionState(w).profiles.get(id);return `<div class="media-daily-grid"><section class="daily-feed"><header><b>IMPRENSA COTIDIANA</b><span>FLUXO DO WORLD CORE</span></header>${events.length?events.map(e=>`<article class="daily-story"><time>${esc(e.date)}</time><div><b>${esc(eventHeadline(e))}</b><p>${esc(eventDeck(e))}</p></div><em>${e.importance>=3?'DESTAQUE':'NOTA'}</em></article>`).join(''):'<div class="media-empty"><b>Nenhuma nota publicada ainda.</b>Avance o calendário para alimentar a imprensa cotidiana.</div>'}</section><aside class="media-side"><header><b>PRESSÃO & PERFIL</b><span>ESTADO DO TREINADOR</span></header><div class="metric-row"><span>Interações pendentes</span><b>${pending.length}</b></div><div class="metric-row"><span>Habilidade com mídia</span><b>${Math.round(profile?.mediaSkill??50)}</b></div><div class="metric-row"><span>Diplomacia</span><b>${Math.round(profile?.diplomacy??50)}</b></div><div class="metric-row"><span>Reputação</span><b>${Math.round(profile?.reputation??50)}</b></div><div class="metric-row"><span>Stress</span><b>${Math.round(profile?.stress??0)}</b></div></aside></div>`}
function interviewCard(w:World,i:ManagerInteraction){const player=i.playerId?w.clubs.flatMap(c=>c.players).find(p=>p.id===i.playerId):undefined,conversations=recentHumanConversations(w,100,i.clubId).filter(c=>c.interactionId===i.id),opening=conversations.find(c=>c.phase==='opening'),reaction=conversations.find(c=>c.phase==='reaction'),answered=i.chosenOptionId?i.options.find(o=>o.id===i.chosenOptionId):undefined;return `<section class="media-interview"><header><h2>${player?`Entrevista sobre ${esc(player.name)}`:'Entrevista rápida'}</h2><p>${esc(i.context)}</p><div class="interview-status"><span>${esc(i.date)} · exposição ${Math.round(i.publicity)}/100</span><b>${i.status==='pending'?'AGUARDANDO RESPOSTA':i.status.toUpperCase()}</b></div></header><div class="interview-dialogue"><article class="interview-question"><b>${esc(opening?.speakerId??'Repórter')}</b><p>${esc(opening?.text??i.context)}</p>${opening?.voiceSignature?`<small>${esc(opening.voiceSignature)}</small>`:''}</article>${answered?`<article class="manager"><b>Treinador</b><p>${esc(answered.label)}</p><small>${esc(answered.description)}</small></article>`:''}${reaction?`<article class="interview-question reaction"><b>${esc(reaction.speakerId)}</b><p>${esc(reaction.text)}</p><small>${esc(reaction.voiceSignature)}</small></article>`:''}</div>${i.status==='pending'?`<div class="interview-options">${i.options.map(o=>`<button data-media-option="${esc(i.id)}|${esc(o.id)}"><b>${esc(o.label)}</b><br><small>${esc(o.description)}</small></button>`).join('')}</div>`:''}</section>`}
function interviewsPane(w:World,id:string){const rows=mediaInteractions(w,id);return `<div class="media-interview-list">${rows.length?rows.map(i=>interviewCard(w,i)).join(''):'<div class="media-empty"><b>Nenhuma entrevista individual disponível.</b>Rumores, incidentes públicos e histórias com jogadores podem gerar entrevistas rápidas.</div>'}</div>`}
function conferencePane(w:World,id:string){const issue=latestSportNews(w),all=pressConferences(w,id),conference=[...all].reverse().find(x=>x.status==='pending')??all.at(-1);if(!conference)return `<section class="press-room-stage"><div class="press-room-meta"><span>SALA DE IMPRENSA</span><span>${esc(clubName(w,id))}</span></div><section class="system-note"><b>Nenhuma coletiva pendente.</b><p>${issue?'A edição atual do Sport News pode gerar uma coletiva com os assuntos de maior repercussão.':'A primeira coletiva será alimentada quando houver pauta suficiente.'}</p>${issue?'<button data-media-create-conference>PREPARAR COLETIVA</button>':''}</section></section>`;return `<section class="press-room-stage"><div class="press-room-meta"><span>SALA DE IMPRENSA</span><span>${esc(conference.date)}</span><span>REAÇÃO PÚBLICA ${Math.round(conference.publicReaction)}/100</span></div><section class="glass press-beta"><div class="section-title"><h2>Coletiva · ${conference.status==='pending'?'Em andamento':'Encerrada'}</h2><span>${conference.questions.length} perguntas</span></div>${conference.questions.map(q=>{const answer=conference.answers.find(a=>a.questionId===q.id);return `<article class="press-question ${q.followUpOf?'follow-up':''}"><span>${esc(q.topic.toUpperCase())} · pressão ${q.pressure}${q.followUpOf?' · REPREGUNTA':''}</span><h3>${esc(q.text)}</h3><p>${esc(q.context)}</p>${answer?`<b>Resposta: ${esc(answer.text??q.options.find(o=>o.id===answer.optionId)?.label??answer.optionId)}</b>${answer.decisionLabel?`<small>Intenção: ${esc(answer.decisionLabel)}</small>`:''}`:`<div class="press-options">${q.options.map(o=>`<button data-media-press-answer="${esc(conference.id)}|${esc(q.id)}|${esc(o.id)}">${esc(o.label)}</button>`).join('')}</div>`}</article>`}).join('')}</section></section>`}
function newspaperPane(w:World){return `<section class="newspaper-stage"><div class="engine-news-wrap">${renderSportNewsIssue(w,latestSportNews(w))}</div><style>${SPORT_NEWS_CSS}</style></section>`}
function render(){const w=world(),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!host)return;const id=clubId(w);if(!id)return;const interviews=mediaInteractions(w,id),confs=pressConferences(w,id);host.innerHTML=`<section class="media-hub-v7"><header class="media-hub-head"><div><span>MÍDIA · ${esc(clubName(w,id).toUpperCase())}</span><h1>Central de Imprensa</h1><p>Noticiário cotidiano, entrevistas, coletivas e o jornal Sport News em ambientes próprios.</p></div></header><nav class="media-hub-tabs">${tabButton('daily','Imprensa cotidiana',mediaEvents(w,id).length)}${tabButton('interviews','Entrevistas',interviews.filter(x=>x.status==='pending').length)}${tabButton('conference','Coletivas',confs.filter(x=>x.status==='pending').length)}${tabButton('newspaper','Sport News')}</nav><div class="media-pane">${activeTab==='daily'?dailyPane(w,id):activeTab==='interviews'?interviewsPane(w,id):activeTab==='conference'?conferencePane(w,id):newspaperPane(w)}</div></section>`;markNavActive();bind(w,id)}
function bind(w:World,id:string){document.querySelectorAll<HTMLButtonElement>('[data-media-tab]').forEach(b=>b.addEventListener('click',()=>{activeTab=(b.dataset.mediaTab as typeof activeTab)||'daily';render()}));document.querySelectorAll<HTMLButtonElement>('[data-media-option]').forEach(b=>b.addEventListener('click',()=>{const [interactionId,optionId]=(b.dataset.mediaOption??'').split('|');if(interactionId&&optionId)resolveManagerInteraction(w,interactionId,optionId,dailyCalendar(w).date);render()}));document.querySelector<HTMLButtonElement>('[data-media-create-conference]')?.addEventListener('click',()=>{const issue=latestSportNews(w);if(issue)createPressConferenceFromSportNews(w,{clubId:id,issueId:issue.id,date:dailyCalendar(w).date});render()});document.querySelectorAll<HTMLButtonElement>('[data-media-press-answer]').forEach(b=>b.addEventListener('click',()=>{const [conferenceId,questionId,optionId]=(b.dataset.mediaPressAnswer??'').split('|');if(conferenceId&&questionId&&optionId)answerPressQuestion(w,conferenceId,questionId,optionId);render()}))}
function pendingCount(){const w=world();if(!w)return 0;const id=clubId(w);if(!id)return 0;return pendingManagerInteractions(w,id).filter(i=>i.kind==='media').length+pressConferences(w,id).filter(c=>c.status==='pending').length}
function ensureNav(){const nav=document.querySelector<HTMLElement>('.game-sidebar nav');if(!nav)return;let button=nav.querySelector<HTMLButtonElement>('[data-media-hub-nav]');if(!button){button=document.createElement('button');button.dataset.mediaHubNav='1';button.innerHTML='<i>◉</i><span>Imprensa</span><em data-media-nav-count></em>';const inbox=nav.querySelector('[data-view="inbox"]');inbox?.after(button);button.addEventListener('click',()=>{activeTab='daily';render()})}const badge=button.querySelector<HTMLElement>('[data-media-nav-count]');const count=pendingCount();if(badge){badge.textContent=count?String(count):'';badge.hidden=!count}}
function markNavActive(){document.querySelectorAll('.game-sidebar nav button').forEach(b=>b.classList.remove('media-active'));document.querySelector('[data-media-hub-nav]')?.classList.add('media-active')}
function maybeTakeOver(target:Element){const button=target.closest<HTMLElement>('[data-engine-launch="press"],[data-system-direct="press"]');if(!button)return;setTimeout(()=>{activeTab='daily';render()},0)}
document.addEventListener('click',e=>{if(e.target instanceof Element)maybeTakeOver(e.target)});
const app=document.querySelector('#app');if(app)new MutationObserver(()=>queueMicrotask(()=>{ensureNav();const press=document.querySelector('.engine-news-wrap,.press-beta');if(press&&!document.querySelector('.media-hub-v7'))render()})).observe(app,{subtree:true,childList:true});
window.addEventListener('touchline:world-ready',ensureNav);window.addEventListener('touchline:view-rendered',ensureNav);ensureNav();
