import type { Player, Position, World } from './engine';
import { playerProfile, capTiePlayer } from './player-profile-v2';
import { effectiveReadiness } from './player-match-state-v2';
import { nationalTeamRanking } from './national-team-ranking-v1';
import { worldCore } from './world-core-v2';
import { realPlayersV2 } from './real-world-player-import-v2';
export type CallUpReason='ability'|'form'|'experience'|'youth'|'positionNeed'|'leadership';
export type NationalSquadMember={playerId:string;clubId:string;position:Position;score:number;reasons:CallUpReason[];status:'selected'|'reserve'};
export type NationalSquad={teamId:string;countryId:string;date:string;competitionId?:string;members:NationalSquadMember[];reserves:NationalSquadMember[];captainId?:string;averageAbility:number;averageAge:number};
const weights:Record<Position,number>={GK:3,RB:2,CB:4,LB:2,DM:3,CM:4,AM:3,RW:3,LW:3,ST:4};
function globalPlayerPopulation(w:World){const byId=new Map<string,Player>();for(const c of w.clubs)for(const p of c.players)byId.set(p.id,p);for(const r of realPlayersV2(w))if(!byId.has(r.player.id))byId.set(r.player.id,r.player);return[...byId.values()]}
function eligibleFor(w:World,p:Player,countryId:string){const pr=playerProfile(w,p.id);if(!pr||pr.retired)return false;const e=pr.eligibility.find(x=>x.countryId===countryId);return !!e?.eligible||pr.nationalities.includes(countryId)||pr.citizenships.includes(countryId)}
function selectionScore(w:World,p:Player,countryId:string){const pr=playerProfile(w,p.id),ready=effectiveReadiness(w,p),e=pr?.eligibility.find(x=>x.countryId===countryId),caps=e?.seniorCaps??0,hidden=pr?.hidden;const experience=Math.min(12,caps*.22),leadership=((hidden?.leadership??50)-50)*.06,big=((hidden?.bigMatches??50)-50)*.05,form=(ready.form-50)*.13,sharp=(ready.sharpness-50)*.08,condition=(ready.condition-70)*.05,ageCurve=p.age<21?2:p.age>33?-Math.min(8,(p.age-33)*1.2):0;return p.currentAbility*.72+p.potentialAbility*(p.age<=22?.08:.02)+experience+leadership+big+form+sharp+condition+ageCurve}
function reasonsFor(w:World,p:Player,countryId:string,score:number):CallUpReason[]{const out:CallUpReason[]=['ability'];const pr=playerProfile(w,p.id),ready=effectiveReadiness(w,p),caps=pr?.eligibility.find(x=>x.countryId===countryId)?.seniorCaps??0;if(ready.form>=65)out.push('form');if(caps>=20)out.push('experience');if(p.age<=21&&p.potentialAbility>=p.currentAbility+8)out.push('youth');if((pr?.hidden.leadership??0)>=75)out.push('leadership');if(score<55)out.push('positionNeed');return out}
export function selectNationalSquad(w:World,input:{teamId:string;countryId:string;size?:number;reserveSize?:number;competitionId?:string;date?:string}){const size=input.size??26,reserveSize=input.reserveSize??8,date=input.date??worldCore(w).date,population=globalPlayerPopulation(w),candidates=population.filter(p=>eligibleFor(w,p,input.countryId)).map(p=>({p,score:selectionScore(w,p,input.countryId)}));const selected:NationalSquadMember[]=[],used=new Set<string>();for(const [pos,min] of Object.entries(weights) as [Position,number][]){const pool=candidates.filter(x=>x.p.position===pos&&!used.has(x.p.id)).sort((a,b)=>b.score-a.score).slice(0,Math.min(min,size-selected.length));for(const x of pool){used.add(x.p.id);selected.push({playerId:x.p.id,clubId:x.p.clubId,position:x.p.position,score:Number(x.score.toFixed(2)),reasons:reasonsFor(w,x.p,input.countryId,x.score),status:'selected'})}}for(const x of candidates.filter(x=>!used.has(x.p.id)).sort((a,b)=>b.score-a.score)){if(selected.length>=size)break;used.add(x.p.id);selected.push({playerId:x.p.id,clubId:x.p.clubId,position:x.p.position,score:Number(x.score.toFixed(2)),reasons:reasonsFor(w,x.p,input.countryId,x.score),status:'selected'})}const reserves=candidates.filter(x=>!used.has(x.p.id)).sort((a,b)=>b.score-a.score).slice(0,reserveSize).map(x=>({playerId:x.p.id,clubId:x.p.clubId,position:x.p.position,score:Number(x.score.toFixed(2)),reasons:reasonsFor(w,x.p,input.countryId,x.score),status:'reserve' as const}));const allPlayers=new Map(population.map(p=>[p.id,p])),captain=[...selected].sort((a,b)=>{const pa=playerProfile(w,a.playerId),pb=playerProfile(w,b.playerId);const ca=(pa?.hidden.leadership??50)+(pa?.eligibility.find(x=>x.countryId===input.countryId)?.seniorCaps??0)*.25,cb=(pb?.hidden.leadership??50)+(pb?.eligibility.find(x=>x.countryId===input.countryId)?.seniorCaps??0)*.25;return cb-ca})[0]?.playerId,players=selected.map(x=>allPlayers.get(x.playerId)).filter(Boolean) as Player[],squad:NationalSquad={teamId:input.teamId,countryId:input.countryId,date,competitionId:input.competitionId,members:selected,reserves,captainId:captain,averageAbility:players.length?Number((players.reduce((s,p)=>s+p.currentAbility,0)/players.length).toFixed(1)):0,averageAge:players.length?Number((players.reduce((s,p)=>s+p.age,0)/players.length).toFixed(1)):0};return squad}
export function recordSeniorInternationalAppearance(w:World,playerId:string,countryId:string,date:string,competitive=true){const p=playerProfile(w,playerId);if(!p)return false;const e=p.eligibility.find(x=>x.countryId===countryId);if(!e)return false;if(competitive&&!e.capTied)return capTiePlayer(w,playerId,countryId,date);e.seniorCaps++;e.lastRepresentedDate=date;return true}
export function callUpPressure(w:World,teamId:string){const r=nationalTeamRanking(w,teamId);return r?Math.max(25,Math.min(95,45+(r.reputation-50)*.7)):50}
