import type { Club, World } from './engine';
import { negotiationHistory, clubEnvironment } from './negotiation';

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v);
const statusLabel:Record<string,string>={accepted:'Acordo',rejected:'Rejeitada',withdrawn:'Desistência',collapsed:'Sem acordo',open:'Em andamento'};
const leakLabel:Record<string,string>={private:'Sigilosa',rumour:'Rumor',reported:'Noticiada',public:'Pública'};

export function renderNegotiations(world:World,club:Club):string{
  const rows=negotiationHistory(world,club.id,30);const env=clubEnvironment(world,club.id);
  const accepted=rows.filter(r=>r.status==='accepted').length;const leaks=rows.filter(r=>r.leakState!=='private').length;const collapsed=rows.filter(r=>['collapsed','rejected','withdrawn'].includes(r.status)).length;
  return `<header><div><span class="eyebrow">MERCADO · ${club.name.toUpperCase()}</span><h1>Centro de Negociações</h1><p>As transferências passam por clube vendedor, atleta, agente, diretoria, torcida e imprensa. Propostas podem vazar, sofrer ultimatos, gerar contrapropostas ou simplesmente desmoronar.</p></div></header>
  <section class="cards"><article class="card metric"><span>Negociações recentes</span><strong>${rows.length}</strong></article><article class="card metric"><span>Acordos</span><strong>${accepted}</strong></article><article class="card metric"><span>Vazamentos</span><strong>${leaks}</strong></article><article class="card metric"><span>Sem acordo</span><strong>${collapsed}</strong></article></section>
  ${env?`<section class="card negotiation-context"><div class="section-title"><h2>Contexto do clube</h2><span>Ambiente que influencia decisões</span></div><div class="context-grid"><div><span>Região</span><b>${env.region}</b></div><div><span>Clima</span><b>${env.climate}</b></div><div><span>Prestígio da cidade</span><b>${env.cityPrestige}</b></div><div><span>Pressão</span><b>${env.pressure}</b></div><div><span>Paixão da torcida</span><b>${env.supporterPassion}</b></div><div><span>Intensidade da imprensa</span><b>${env.mediaIntensity}</b></div></div></section>`:''}
  <div class="negotiation-cases">${rows.length?rows.map(c=>{
    const p=c.currentPackage;const total=p.upfrontFee+p.installments*p.installmentValue;const clauses=p.clauses.map(x=>`<span>${x.description}</span>`).join('');
    return `<section class="card negotiation-case"><div class="section-title"><h2>${c.playerName}</h2><span class="neg-status ${c.status}">${statusLabel[c.status]}</span></div><div class="case-head"><div><span>Operação</span><b>${p.type}</b></div><div><span>Taxa total</span><b>${money(total)}</b></div><div><span>Salário</span><b>${money(p.weeklyWage)}/sem</b></div><div><span>Agente</span><b>${c.agent.name}</b></div><div><span>Exposição</span><b>${leakLabel[c.leakState]}</b></div><div><span>Rodadas</span><b>${c.rounds.length}</b></div></div><div class="sentiment-strip"><span>Torcida compradora <b>${Math.round(c.sentiment.supportersBuyer)}</b></span><span>Torcida vendedora <b>${Math.round(c.sentiment.supportersSeller)}</b></span><span>Imprensa compradora <b>${Math.round(c.sentiment.mediaBuyer)}</b></span><span>Imprensa vendedora <b>${Math.round(c.sentiment.mediaSeller)}</b></span></div>${clauses?`<div class="clause-list">${clauses}</div>`:''}<div class="neg-timeline">${c.rounds.map(r=>`<div class="neg-event ${r.action}"><span>R${r.round}</span><b>${r.actor}</b><em>${r.action}</em><p>${r.message}</p>${r.playerInterest?`<small>Interesse do atleta ${r.playerInterest}/100 · poder comprador ${r.leverageBuyer} · poder vendedor ${r.leverageSeller}</small>`:''}</div>`).join('')}</div><div class="case-result"><b>${c.finalReason??'Em andamento'}</b></div></section>`;
  }).join(''):'<div class="card empty-state">Nenhuma negociação registrada ainda.</div>'}</div>`;
}
