import type { RealPlayerSeedV2 } from './real-world-player-import-v2';

export const OPENFOOTBALL_PEOPLE_REPO='https://github.com/openfootball/players';
export const OPENFOOTBALL_PEOPLE_RAW='https://raw.githubusercontent.com/openfootball/players/master';
export const OPENFOOTBALL_PEOPLE_COUNTRIES=[['BR','south-america/brazil/br.players.txt'],['AR','south-america/argentina/ar.players.txt'],['UY','south-america/uruguay/uy.players.txt'],['PY','south-america/paraguay/py.players.txt'],['CL','south-america/chile/cl.players.txt'],['CO','south-america/colombia/co.players.txt'],['PE','south-america/peru/pe.players.txt'],['EC','south-america/ecuador/ec.players.txt'],['VE','south-america/venezuela/ve.players.txt'],['BO','south-america/bolivia/bo.players.txt']] as const;
const months:Record<string,string>={jan:'01',feb:'02',mar:'03',apr:'04',may:'05',jun:'06',jul:'07',aug:'08',sep:'09',oct:'10',nov:'11',dec:'12'};
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function position(raw:string):RealPlayerSeedV2['position']|undefined{const p=raw.trim().toUpperCase();return p==='G'?'GK':p==='D'?'CB':p==='M'?'CM':p==='F'?'ST':undefined}
function date(meta:string){const iso=meta.match(/\b(\d{4}-\d{2}-\d{2})\b/)?.[1];if(iso)return iso;const m=meta.match(/\bb\.\s*(\d{1,2})\s+([A-Za-z]{3})\s+(\d{4})\b/i);if(!m)return;const month=months[m[2].toLowerCase()];return month?`${m[3]}-${month}-${String(m[1]).padStart(2,'0')}`:undefined}
export function parseOpenFootballPeople(text:string,countryId:string,snapshotDate:string):RealPlayerSeedV2[]{const rows:RealPlayerSeedV2[]=[];let lineNo=0;for(const raw of text.split(/\r?\n/)){lineNo++;const line=raw.trim();if(!line||line.startsWith('#')||line.startsWith('=')||line.startsWith('-'))continue;const cols=line.split(',').map(x=>x.trim());if(cols.length<2)continue;const name=cols[0],pos=position(cols[1]);if(name.length<3||!pos)continue;const meta=cols.slice(2).join(', '),dob=date(meta),heightMatch=meta.match(/\b(\d(?:\.\d{1,2})?)\s*m\b/i),heightCm=heightMatch?Math.round(Number(heightMatch[1])*100):undefined,sourceId=`${countryId}:${lineNo}:${norm(name).replace(/ /g,'-')}`;rows.push({externalIds:{openfootball:sourceId},name,dateOfBirth:dob,heightCm,position:pos,nationalityCountryIds:[countryId],provenance:[{source:'openfootball-players',sourceId,snapshotDate,confidence:80,license:'CC0',url:OPENFOOTBALL_PEOPLE_REPO}]})}return rows}
async function text(url:string){const r=await fetch(url);if(!r.ok)throw new Error(`OpenFootball people ${r.status}: ${url}`);return r.text()}
export async function fetchOpenFootballPeople2026(snapshotDate=new Date().toISOString().slice(0,10)){const players:RealPlayerSeedV2[]=[],failures:Array<{countryId:string;path:string;error:string}>=[];for(const [countryId,path] of OPENFOOTBALL_PEOPLE_COUNTRIES){try{players.push(...parseOpenFootballPeople(await text(`${OPENFOOTBALL_PEOPLE_RAW}/${path}`),countryId,snapshotDate))}catch(e){failures.push({countryId,path,error:e instanceof Error?e.message:String(e)})}}if(!players.length)throw new Error('Nenhum jogador pôde ser carregado da fonte CC0 OpenFootball.');return{players,staff:[],manifest:{generatedAt:new Date().toISOString(),cutover:'2026',mode:'live-cc0-fallback',sources:{openfootball:{repo:OPENFOOTBALL_PEOPLE_REPO,license:'CC0-1.0'}},counts:{players:players.length,staff:0,failures:failures.length},failures,notes:['Fallback ao vivo usa somente OpenFootball CC0.','Atributos não públicos continuam sendo estimados e marcados pelo runtime.','Staff real não é inventado quando não há fonte licenciada disponível.']}}}
