import type { World } from './engine';
import { alias, footballCompetition, registerClubRecord, registerCompetitionRecord, registerStadiumRecord, resolveFootballEntity, footballClub, type ClubRecord, type CompetitionKind, type CompetitionRecord, type DataProvenance, type StadiumRecord } from './world-football-data-v1';

export type OpenFootballSource={id:string;repo:string;path:string;kind:'leagues'|'clubs'|'stadiums'|'matches'|'seasons';countryId?:string;confederationId?:string;sectionCountryMap?:Record<string,string>;license:'CC0-1.0';historical:boolean};
export type ImportResult={source:OpenFootballSource;created:number;updated:number;warnings:string[];entityIds:string[]};
const provenance=(s:OpenFootballSource,sourceEntityId?:string):DataProvenance=>({sourceId:s.id,sourceEntityId,sourcePath:`${s.repo}/${s.path}`,license:s.license,historical:s.historical,confidence:92});
const clean=(s:string)=>s.replace(/\s+#.*$/,'').replace(/\s+/g,' ').trim();
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const splitAliases=(line:string)=>line.replace(/^\s*\|\s*/,'').split('|').map(clean).filter(Boolean).filter(x=>!/^([a-z]{2,4}\.)+[a-z0-9.]+$/i.test(x));
const isSection=(line:string)=>/^=+\s*[^=]+\s*=+$/.test(line.trim());
const sectionName=(line:string)=>line.replace(/^=+|=+$/g,'').trim();
const competitionKind=(code:string,name:string):CompetitionKind=>{const x=`${code} ${name}`.toLowerCase();if(/qual/i.test(x))return'qualifier';if(/super|recopa/i.test(x))return'supercup';if(/cup|copa|pokal|fa cup|coppa/i.test(x))return'cup';if(/paulista|carioca|mineiro|gaucho|gaúcho|paranaense|estadual/i.test(x))return'stateLeague';return'league'};
const levelFrom=(code:string)=>/^\d+$/.test(code)?Number(code):undefined;
const defaultRules=()=>({pointsWin:3,pointsDraw:1,legs:2 as 1|2,tiebreakers:['points','wins','goalDifference','goalsFor'] as any[],promotion:[] as any[],relegation:[] as any[],qualification:[] as any[],calendarPattern:'calendar-year' as const,seasonStartMonth:1,seasonEndMonth:12,usesPlayoffs:false});

export function parseOpenFootballLeagues(world:World,text:string,source:OpenFootballSource):ImportResult{const warnings:string[]=[],entityIds:string[]=[];let section=source.countryId??'International',current:CompetitionRecord|undefined,created=0,updated=0;for(const raw of text.replace(/\r/g,'').split('\n')){const line=raw.trimEnd();if(!line.trim()||line.trim().startsWith('#'))continue;if(isSection(line)){section=sectionName(line);current=undefined;continue}if(/^\s*\|/.test(line)){if(current){current.aliases.push(...splitAliases(line).map(v=>alias(v)));registerCompetitionRecord(world,current);updated++}continue}const m=line.match(/^\s*(\S+)\s{2,}(.+?)\s*$/);if(!m)continue;const code=clean(m[1]),name=clean(m[2]);if(!name)continue;const sectionCountry=source.sectionCountryMap?.[section],countryId=source.countryId??sectionCountry,international=section.toLowerCase()==='international'||section.toLowerCase()==='national teams'||!countryId;const level=international?undefined:levelFrom(code),id=international?`comp-${source.confederationId?.toLowerCase()??'world'}-${slug(code||name)}`:`comp-${countryId.toLowerCase()}-${slug(code||name)}`;current={id,name,aliases:[],scope:international?(source.confederationId?'continental':'international'):'domestic',kind:competitionKind(code,name),countryId:international?undefined:countryId,confederationId:international?source.confederationId:undefined,level,active:true,rules:defaultRules(),provenance:[provenance(source,code)]};registerCompetitionRecord(world,current);entityIds.push(id);created++}return{source,created,updated,warnings,entityIds}}

export function parseOpenFootballClubs(world:World,text:string,source:OpenFootballSource):ImportResult{const warnings:string[]=[],entityIds:string[]=[];let current:ClubRecord|undefined,created=0,updated=0;for(const raw of text.replace(/\r/g,'').split('\n')){const line=raw.trimEnd();if(!line.trim())continue;if(/^==[^=].*==$/.test(line.trim())){current=undefined;continue}if(line.trim().startsWith('#'))continue;if(/^\s*\|/.test(line)){if(current){current.aliases.push(...splitAliases(line).map(v=>alias(v)));registerClubRecord(world,current);updated++}continue}if(/^=/.test(line.trim()))continue;const body=clean(line);const parts=body.split(',').map(clean).filter(Boolean);if(parts.length<2)continue;const name=parts[0];let foundedYear:number|undefined,cityName:string|undefined;if(/^\d{4}$/.test(parts[1])){foundedYear=Number(parts[1]);cityName=parts[2]}else cityName=parts[1];if(!cityName){warnings.push(`cidade ausente: ${name}`);continue}const id=`club-${(source.countryId??'xx').toLowerCase()}-${slug(name)}`;current={id,name,aliases:[],countryId:source.countryId??'UNK',cityName,foundedYear,active:!/(\d{4})-(\d{4})/.test(name),stadiumIds:[],historicalNames:[],provenance:[provenance(source,name)]};const historical=name.match(/\((\d{4})-(\d{4})\)/);if(historical){current.foundedYear=current.foundedYear??Number(historical[1]);current.ceasedYear=Number(historical[2]);current.active=false}registerClubRecord(world,current);entityIds.push(id);created++}return{source,created,updated,warnings,entityIds}}

export function parseOpenFootballStadiums(world:World,text:string,source:OpenFootballSource):ImportResult{const warnings:string[]=[],entityIds:string[]=[];let current:StadiumRecord|undefined,created=0,updated=0;for(const raw of text.replace(/\r/g,'').split('\n')){const line=raw.trimEnd();if(!line.trim())continue;if(/^==[^=].*==$/.test(line.trim())){current=undefined;continue}if(/^\s*#\s*[Cc]lub:\s*/.test(line)){const clubAlias=line.replace(/^\s*#\s*[Cc]lub:\s*/,'').trim();if(current&&clubAlias){const clubIds=resolveFootballEntity(world,clubAlias).filter(id=>id.startsWith('club-'));for(const clubId of clubIds){if(!current.ownerClubIds.includes(clubId))current.ownerClubIds.push(clubId);const club=footballClub(world,clubId);if(club&&!club.stadiumIds.includes(current.id)){club.stadiumIds.push(current.id);registerClubRecord(world,club)}}current.provenance.push({...provenance(source,clubAlias),confidence:75});registerStadiumRecord(world,current);updated++}continue}if(line.trim().startsWith('#'))continue;if(/^\s*\|/.test(line)){if(current){current.aliases.push(...splitAliases(line).map(v=>alias(v)));registerStadiumRecord(world,current);updated++}continue}if(/^=/.test(line.trim()))continue;const body=clean(line),parts=body.split(',').map(clean);if(parts.length<3)continue;const rawName=parts[0],capacityText=parts[1].replace(/_/g,''),cityName=parts[2];const capacity=Number(capacityText),commercial=(rawName.match(/\$([^$]+)\$/)||[])[1],name=rawName.replace(/\$/g,'');if(!Number.isFinite(capacity)){warnings.push(`capacidade inválida: ${rawName}`);continue}const id=`stadium-${(source.countryId??'xx').toLowerCase()}-${slug(name)}`;current={id,name,aliases:[],countryId:source.countryId??'UNK',cityName,capacity,ownerClubIds:[],commercialName:commercial,provenance:[provenance(source,name)]};registerStadiumRecord(world,current);entityIds.push(id);created++}return{source,created,updated,warnings,entityIds}}

export function linkDomesticPyramid(world:World,competitionIds:string[]){const comps=competitionIds.map(id=>footballCompetition(world,id)).filter(Boolean) as CompetitionRecord[];const leagues=comps.filter(c=>c.kind==='league'&&c.level).sort((a,b)=>(a.level??99)-(b.level??99));for(let i=0;i<leagues.length;i++){const c=leagues[i],up=leagues[i-1],down=leagues[i+1];if(up&&!c.rules.promotion.some(x=>x.toCompetitionId===up.id))c.rules.promotion.push({toCompetitionId:up.id,automaticSlots:Math.min(4,c.level===2?4:2)});if(down&&!c.rules.relegation.some(x=>x.toCompetitionId===down.id))c.rules.relegation.push({toCompetitionId:down.id,automaticSlots:Math.min(4,c.level===1?4:2)})}return leagues}

const southAmericaSections={Paraguay:'PAR',Peru:'PER',Bolivia:'BOL',Chile:'CHI',Colombia:'COL',Uruguay:'URU',Ecuador:'ECU',Venezuela:'VEN'};
export const OPENFOOTBALL_SOURCES={
 leaguesGlobal:{id:'openfootball-leagues-global',repo:'openfootball/leagues',path:'leagues.txt',kind:'leagues',license:'CC0-1.0',historical:true} as OpenFootballSource,
 leaguesSouthAmerica:{id:'openfootball-leagues-south-america',repo:'openfootball/leagues',path:'south-america/leagues.txt',kind:'leagues',confederationId:'CONMEBOL',sectionCountryMap:southAmericaSections,license:'CC0-1.0',historical:true} as OpenFootballSource,
 leaguesBrazil:{id:'openfootball-leagues-brazil',repo:'openfootball/leagues',path:'south-america/brazil/br.leagues.txt',kind:'leagues',countryId:'BRA',confederationId:'CONMEBOL',license:'CC0-1.0',historical:true} as OpenFootballSource,
 clubsBrazil:{id:'openfootball-clubs-brazil',repo:'openfootball/clubs',path:'south-america/brazil/br.clubs.txt',kind:'clubs',countryId:'BRA',confederationId:'CONMEBOL',license:'CC0-1.0',historical:true} as OpenFootballSource,
 stadiumsBrazil:{id:'openfootball-stadiums-brazil',repo:'openfootball/clubs',path:'south-america/brazil/br.stadiums.txt',kind:'stadiums',countryId:'BRA',confederationId:'CONMEBOL',license:'CC0-1.0',historical:true} as OpenFootballSource
};
