import type { World } from './engine';
import { registerHistoricalMatch, registerMembership, registerTitle, resolveFootballEntity, type DataProvenance, type HistoricalMatchRecord } from './world-football-data-v1';
import type { OpenFootballSource } from './openfootball-importer-v1';

export type TournamentImportResult={competitionId:string;season:string;matches:number;championTeamId?:string;runnerUpTeamId?:string;unresolvedTeams:string[];stages:string[]};
const months:Record<string,number>={Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8,Sep:9,Oct:10,Nov:11,Dec:12};
const pad=(n:number)=>String(n).padStart(2,'0');
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
const prov=(s:OpenFootballSource):DataProvenance=>({sourceId:s.id,sourcePath:`${s.repo}/${s.path}`,license:s.license,historical:true,confidence:96});
const cleanTeam=(s:string)=>s.replace(/\s+\([A-Z]{3}\)\s*$/,'').replace(/\s+/g,' ').trim();
function resolveTeam(world:World,name:string){const ids=resolveFootballEntity(world,cleanTeam(name)).filter(x=>x.startsWith('club-')||x.startsWith('nt-'));return ids.length===1?ids[0]:undefined}
function parseDate(line:string,seasonStart:number,lastDate?:string){const m=line.trim().match(/^(?:Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+([A-Z][a-z]{2})\s+(\d{1,2})(?:\s+(\d{4}))?/);if(!m)return;const month=months[m[1]],day=Number(m[2]);if(!month)return;let year=m[3]?Number(m[3]):seasonStart;if(!m[3]&&lastDate){const lastMonth=Number(lastDate.slice(5,7));if(month<lastMonth-6)year++}return`${year}-${pad(month)}-${pad(day)}`}
function winnerFromScore(home:string,away:string,hg:number,ag:number,extra:string){if(hg>ag)return home;if(ag>hg)return away;const p=extra.match(/(\d+)\s*-\s*(\d+)\s*pen/i);if(p)return Number(p[1])>Number(p[2])?home:away;return undefined}
export function importOpenFootballTournament(world:World,text:string,input:{source:OpenFootballSource;competitionId:string;season:string;teamKind?:'club'|'national'}):TournamentImportResult{const startYear=Number(input.season.slice(0,4)),unresolved=new Set<string>(),stages=new Set<string>(),records:HistoricalMatchRecord[]=[];let date:string|undefined,stage:string|undefined,finalWinner:string|undefined,runnerUp:string|undefined;for(const raw of text.replace(/\r/g,'').split('\n')){const line=raw.trimEnd();const sm=line.trim().match(/^▪\s*(.+?)(?:\s*\|.*)?$/);if(sm){stage=sm[1].trim();stages.add(stage);continue}const d=parseDate(line,startYear,date);if(d){date=d;continue}if(!date)continue;
  let homeName:string|undefined,awayName:string|undefined,hg:number|undefined,ag:number|undefined,tail='';
  const v=line.match(/^\s*(?:(\d{1,2}:\d{2})\s+)?(.+?)\s+v\s+(.+?)\s+(\d+)-(\d+)(.*)$/);
  if(v){homeName=v[2].trim();awayName=v[3].trim();hg=Number(v[4]);ag=Number(v[5]);tail=v[6]??''}
  if(!v){const w=line.match(/^\s*(?:\d{1,2}:\d{2}\s+)?(.+?)\s+(\d+)-(\d+)\s+(.*)$/);if(w){homeName=w[1].trim();hg=Number(w[2]);ag=Number(w[3]);const rest=w[4].replace(/\s+@.+$/,'').trim();const parts=rest.split(/\s{2,}/).filter(Boolean);awayName=parts.at(-1)?.replace(/^.*pen\.\s*/i,'').trim();tail=rest}}
  if(!homeName||!awayName||hg===undefined||ag===undefined)continue;homeName=cleanTeam(homeName);awayName=cleanTeam(awayName);const homeTeamId=resolveTeam(world,homeName),awayTeamId=resolveTeam(world,awayName);if(!homeTeamId||!awayTeamId){if(!homeTeamId)unresolved.add(homeName);if(!awayTeamId)unresolved.add(awayName);continue}const rec:HistoricalMatchRecord={id:`ht-${hash(`${input.competitionId}:${input.season}:${date}:${stage}:${homeTeamId}:${awayTeamId}`)}`,date,competitionId:input.competitionId,season:input.season,homeTeamId,awayTeamId,homeGoals:hg,awayGoals:ag,stage,round:stage,source:'historical',provenance:[prov(input.source)]};registerHistoricalMatch(world,rec);records.push(rec);for(const teamId of [homeTeamId,awayTeamId])registerMembership(world,{season:input.season,competitionId:input.competitionId,teamId,teamKind:input.teamKind??(teamId.startsWith('nt-')?'national':'club'),status:'participant',source:'historical',provenance:[prov(input.source)]});if(stage&&/^final$/i.test(stage)){const winner=winnerFromScore(homeTeamId,awayTeamId,hg,ag,tail);if(winner){finalWinner=winner;runnerUp=winner===homeTeamId?awayTeamId:homeTeamId}}}
  if(finalWinner){registerTitle(world,{id:`title-${input.competitionId}-${input.season}-${finalWinner}`,teamId:finalWinner,teamKind:input.teamKind??(finalWinner.startsWith('nt-')?'national':'club'),competitionId:input.competitionId,season:input.season,source:'historical',provenance:[prov(input.source)]});registerMembership(world,{season:input.season,competitionId:input.competitionId,teamId:finalWinner,teamKind:input.teamKind??(finalWinner.startsWith('nt-')?'national':'club'),status:'champion',source:'historical',provenance:[prov(input.source)]})}
  return{competitionId:input.competitionId,season:input.season,matches:records.length,championTeamId:finalWinner,runnerUpTeamId:runnerUp,unresolvedTeams:[...unresolved].sort(),stages:[...stages]}}
