import type { Player, PlayerAttributes, Position, World } from './engine';
import { deterministicRandom, queueWorldEvent, worldCore } from './world-core-v2';
import { registerGeneratedYouth, type YouthGenerationResult } from './player-generation-v2';
import { potentialTierFor, type PlayerPotentialLabel } from './player-potential-tier-v1';

export type CultureNamePool={cultureId:string;first:string[];last:string[]};
export type NewgenPersonality={professionalism:number;ambition:number;pressure:number;consistency:number;adaptability:number;loyalty:number;controversy:number;injurySusceptibility:number};
export type NewgenPlayerV3={result:YouthGenerationResult;birthRegionId?:string;preferredFoot:'left'|'right';weakFoot:number;secondaryPositions:Position[];heightCm:number;personality:NewgenPersonality;cultureId:string;potentialLabel:PlayerPotentialLabel};
export type StaffRole='manager'|'assistant'|'coach'|'goalkeepingCoach'|'fitnessCoach'|'analyst'|'scout'|'physio'|'doctor'|'psychologist'|'nutritionist'|'youthCoach'|'loanManager'|'recruitmentDirector'|'technicalDirector'|'footballCoordinator'|'performanceCoach';
export type GeneratedStaffV3={id:string;name:string;age:number;countryId:string;cultureId:string;role:StaffRole;reputation:number;coaching:number;judgingAbility:number;judgingPotential:number;manManagement:number;tactical:number;medical:number;analysis:number;adaptability:number;languages:string[];personality:NewgenPersonality;playingBackground?:{position:Position;peakAbility:number;years:number};educationLevel:number;licenseLevel:number};
const pools=new Map<string,CultureNamePool>();
export function registerCultureNamePool(pool:CultureNamePool){pools.set(pool.cultureId,{cultureId:pool.cultureId,first:[...pool.first],last:[...pool.last]})}
registerCultureNamePool({cultureId:'pt-BR',first:['Arthur','Bernardo','Caio','Davi','Eduardo','Felipe','Gabriel','Heitor','João','Lucas','Mateus','Miguel','Otávio','Pedro','Rafael','Samuel','Thiago','Vinícius','Wesley','Yuri'],last:['Almeida','Barbosa','Cardoso','Duarte','Ferreira','Gomes','Lima','Martins','Nogueira','Oliveira','Pereira','Rocha','Santos','Silva','Souza','Teixeira','Vieira']});
registerCultureNamePool({cultureId:'es',first:['Alejandro','Álvaro','Carlos','Daniel','Diego','Hugo','Javier','Jorge','Luis','Marcos','Mateo','Pablo','Sergio'],last:['Alonso','Castro','García','Gómez','López','Martínez','Moreno','Navarro','Pérez','Romero','Ruiz','Sánchez']});
registerCultureNamePool({cultureId:'en',first:['Adam','Ben','Callum','Daniel','Ethan','George','Harry','Jack','James','Joe','Lewis','Luke','Oliver','Ryan','Thomas'],last:['Brown','Clark','Davies','Evans','Green','Hall','Harris','Jackson','Johnson','Jones','Smith','Taylor','Walker','White','Wilson']});
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));const r=(w:World,k:string)=>deterministicRandom(w,'person-v3',k);const pick=<T>(w:World,k:string,x:T[])=>x[Math.floor(r(w,k)*x.length)];
function personality(w:World,key:string):NewgenPersonality{const v=(k:string,b=50,s=50)=>Math.round(clamp(b+(r(w,`${key}:${k}`)-.5)*s));return{professionalism:v('pro',55,70),ambition:v('amb',55,75),pressure:v('press',50,75),consistency:v('cons',52,65),adaptability:v('adapt',50,80),loyalty:v('loyal',52,80),controversy:v('contro',28,55),injurySusceptibility:v('injury',32,55)}}
function correlatedAttrs(base:number,pos:Position,w:World,key:string):PlayerAttributes{const family=(name:string,bias=0)=>base+bias+(r(w,`${key}:family:${name}`)-.5)*10,tech=family('technical'),mental=family('mental'),physical=family('physical'),def=family('defensive'),atk=family('attacking'),a=(v:number,k:string)=>Math.round(clamp(v+(r(w,`${key}:${k}`)-.5)*8,15,96));return{pace:a(physical+(['RB','LB','RW','LW'].includes(pos)?7:0),'pace'),passing:a(tech+(['DM','CM','AM'].includes(pos)?7:0),'passing'),technique:a(tech+(['AM','RW','LW','ST'].includes(pos)?5:0),'technique'),finishing:a(atk+(pos==='ST'?10:['AM','RW','LW'].includes(pos)?4:-8),'finishing'),tackling:a(def+(['CB','RB','LB','DM'].includes(pos)?9:-8),'tackling'),positioning:a(mental+(['GK','CB','DM'].includes(pos)?6:1),'positioning'),stamina:a(physical+(['RB','LB','DM','CM'].includes(pos)?5:0),'stamina'),decisions:a(mental,'decisions'),goalkeeping:a(pos==='GK'?base+15:15,'goalkeeping')}}
export function generateNewgenPlayerV3(w:World,input:{clubId:string;countryId:string;cultureId:string;season?:number;serial:number;academyQuality:number;recruitmentReach:number;positionNeed?:Position;countryStrength?:number}):NewgenPlayerV3{
 const season=input.season??w.season,key=`${input.countryId}:${input.clubId}:${season}:${input.serial}`,pool=pools.get(input.cultureId)??pools.get('en')!,positions:Position[]=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];
 const pos=input.positionNeed??pick(w,`${key}:pos`,positions),age=14+Math.floor(r(w,`${key}:age`)*6),discovery=clamp(input.academyQuality*.45+input.recruitmentReach*.35+(input.countryStrength??50)*.2),tail=Math.pow(r(w,`${key}:talent`),5),ca=Math.round(clamp(27+age*1.25+discovery*.16+tail*16+(r(w,`${key}:ca`)-.5)*9,25,72)),pa=Math.round(clamp(ca+8+Math.pow(r(w,`${key}:potential`),.42)*34+(discovery-50)*.05,45,99));
 const name=`${pick(w,`${key}:first`,pool.first)} ${pick(w,`${key}:last`,pool.last)}`,id=`ng3-${input.countryId}-${season}-${input.clubId}-${input.serial}-${Math.floor(r(w,`${key}:id`)*1e8).toString(36)}`;
 const player:Player={id,clubId:input.clubId,name,position:pos,age,currentAbility:ca,potentialAbility:Math.max(ca,pa),condition:96,morale:72+Math.round(r(w,`${key}:morale`)*20),attributes:correlatedAttrs(ca,pos,w,key)};
 const rarity:YouthGenerationResult['rarity']=pa>=94?'generational':pa>=88?'elite':pa>=76?'promising':'ordinary',result:YouthGenerationResult={player,profileSeed:key,rarity},preferredFoot:'left'|'right'=r(w,`${key}:foot`)<.22?'left':'right',secondaryPositions:Position[]=[];
 const adj:Partial<Record<Position,Position[]>>={RB:['LB','CB'],LB:['RB','CB'],CB:['DM'],DM:['CM','CB'],CM:['DM','AM'],AM:['CM','RW','LW'],RW:['LW','AM','ST'],LW:['RW','AM','ST'],ST:['RW','LW']};if(r(w,`${key}:secondary`)<.62)secondaryPositions.push(...(adj[pos]??[]).slice(0,r(w,`${key}:secondary2`)<.25?2:1));
 const heightBase:Record<Position,number>={GK:190,RB:177,CB:187,LB:177,DM:183,CM:180,AM:178,RW:176,LW:176,ST:184},certainty=age<=15?24:age<=17?34:45;
 return{result,birthRegionId:undefined,preferredFoot,weakFoot:Math.round(20+r(w,`${key}:weak`)*75),secondaryPositions,heightCm:Math.round(heightBase[pos]+(r(w,`${key}:height`)-.5)*14-(18-age)*.8),personality:personality(w,key),cultureId:input.cultureId,potentialLabel:potentialTierFor({potential:pa,position:pos,certainty,age})};
}
export function registerNewgenPlayerV3(w:World,p:NewgenPlayerV3,countryId:string){const profile=registerGeneratedYouth(w,p.result,countryId);queueWorldEvent(w,{date:worldCore(w).date,type:'NewgenPotentialClassified',scope:'person',entityIds:[p.result.player.id],importance:p.potentialLabel.tier==='possible-legend'?4:p.potentialLabel.tier==='possible-elite'?3:1,payload:{tier:p.potentialLabel.tier,label:p.potentialLabel.label,confidence:p.potentialLabel.confidence,ceilingBand:p.potentialLabel.ceilingBand}});return profile}
export function generateStaffV3(w:World,input:{countryId:string;cultureId:string;role:StaffRole;season?:number;serial:number;formerPlayer?:{position:Position;peakAbility:number;years:number}}):GeneratedStaffV3{const key=`staff:${input.countryId}:${input.role}:${input.season??w.season}:${input.serial}`,pool=pools.get(input.cultureId)??pools.get('en')!,age=input.formerPlayer?35+Math.floor(r(w,`${key}:age`)*30):24+Math.floor(r(w,`${key}:age`)*42),education=Math.round(25+r(w,`${key}:edu`)*70),license=Math.round(clamp(education*.45+(age-20)*.65+r(w,`${key}:lic`)*25)),experience=Math.max(0,age-25)+(input.formerPlayer?.years??0),base=clamp(25+experience*.65+education*.2+license*.25),roleBias=(...roles:StaffRole[])=>roles.includes(input.role)?12:0,p=personality(w,key);return{id:`staff3-${input.countryId}-${input.role}-${input.season??w.season}-${input.serial}-${Math.floor(r(w,`${key}:id`)*1e7).toString(36)}`,name:`${pick(w,`${key}:first`,pool.first)} ${pick(w,`${key}:last`,pool.last)}`,age,countryId:input.countryId,cultureId:input.cultureId,role:input.role,reputation:Math.round(clamp(base*.55+(input.formerPlayer?.peakAbility??30)*.25)),coaching:Math.round(clamp(base+roleBias('manager','assistant','coach','youthCoach','goalkeepingCoach','fitnessCoach'))),judgingAbility:Math.round(clamp(base+roleBias('scout','recruitmentDirector','technicalDirector'))),judgingPotential:Math.round(clamp(base+roleBias('scout','youthCoach','recruitmentDirector'))),manManagement:Math.round(clamp(base*.75+p.pressure*.25+roleBias('manager','assistant','footballCoordinator'))),tactical:Math.round(clamp(base+roleBias('manager','assistant','analyst'))),medical:Math.round(clamp(base*.45+roleBias('physio','doctor','psychologist','nutritionist')*3)),analysis:Math.round(clamp(base+roleBias('analyst','performanceCoach','recruitmentDirector'))),adaptability:p.adaptability,languages:[input.countryId],personality:p,playingBackground:input.formerPlayer,educationLevel:education,licenseLevel:license}}
export function emitStaffGenerated(w:World,s:GeneratedStaffV3){queueWorldEvent(w,{date:worldCore(w).date,type:'StaffGenerated',scope:'person',entityIds:[s.id],importance:s.reputation>75?3:1,payload:{role:s.role,countryId:s.countryId,reputation:s.reputation,formerPlayer:!!s.playingBackground}})}