import { createWorld, type World } from './engine';
import { ensurePlayerProfiles } from './player-profile-v2';
import { ensureTechnicalProfiles, positionFamiliarity } from './player-technical-profile-v2';
import { ensurePlayerBehavior, trainTrait } from './player-behavior-v2';
import { ensurePlayerMatchState, recordMatchExposure, injuryLayoffEffect } from './player-match-state-v2';
import { ensureScoutingKnowledge, observePlayer, type ScoutSkill } from './player-scouting-v2';
import { ensurePartnership, recordPartnershipMinutes } from './player-partnerships-v2';
import { populationBudgetAudit } from './player-attribute-budget-v2';
import { snapshotWorldFoundation, validateWorldFoundationSave } from './world-save-schema-v2';

export type PlayerModelFinalDiagnostics={ok:boolean;score:number;checks:Record<string,boolean>;issues:string[]};
const scout:ScoutSkill={judgingAbility:78,judgingPotential:76,tacticalEvaluation:72,medicalAwareness:68,regionalKnowledge:80};
export function diagnosePlayerModelV2(world:World=createWorld()):PlayerModelFinalDiagnostics{const issues:string[]=[],checks:Record<string,boolean>={};ensurePlayerProfiles(world);ensureTechnicalProfiles(world);const players=world.clubs.flatMap(c=>c.players),p=players[0],q=world.clubs[0].players[1];checks.population=players.length>30;if(!checks.population)issues.push('população inicial insuficiente');const behavior=ensurePlayerBehavior(world,p);checks.behavior=Object.values(behavior.behavior).every(v=>v>=0&&v<=100);if(!checks.behavior)issues.push('behavior profile fora da faixa');const trait=trainTrait(world,p,'playsOneTwos',240,80);checks.traits=Boolean(trait&&trait.learningProgress>0);if(!checks.traits)issues.push('trait training não evoluiu');const ms=ensurePlayerMatchState(world,p),sharp0=ms.sharpness;recordMatchExposure(world,p,90,7.2,'2026-08-01');checks.sharpness=ms.sharpness>sharp0;injuryLayoffEffect(world,p,90);checks.layoff=ms.sharpness<sharp0+25;if(!checks.sharpness||!checks.layoff)issues.push('sharpness não reage corretamente a jogo/lesão');const k=ensureScoutingKnowledge(world,'scout-test',p,scout),width0=k.potentialRange[1]-k.potentialRange[0];for(let i=0;i<6;i++)observePlayer(world,'scout-test',p,scout,{match:true,minutes:90,date:`2026-08-${String(i+2).padStart(2,'0')}`});const width1=k.potentialRange[1]-k.potentialRange[0];checks.scouting=width1<width0&&k.overallKnowledge>20;if(!checks.scouting)issues.push('scouting não reduziu incerteza');const pair=ensurePartnership(world,p,q),chem0=pair.chemistry;recordPartnershipMinutes(world,p,q,1800,{tacticalFit:80,relationship:75,sharedSuccess:70});checks.partnership=pair.chemistry>chem0;if(!checks.partnership)issues.push('partnership não evoluiu');checks.positions=positionFamiliarity(world,p.id,p.position)>=90;if(!checks.positions)issues.push('posição natural com familiaridade baixa');const budget=populationBudgetAudit(world);checks.budget=budget.ok;if(!checks.budget)issues.push(`attribute budget drift elevado (${budget.severe}/${budget.players})`);const save=snapshotWorldFoundation(world),validation=validateWorldFoundationSave(save);checks.save=validation.ok&&save.schemaVersion>=5;if(!checks.save)issues.push(`save V5 inválido: ${validation.issues.join(', ')}`);const values=Object.values(checks),score=Math.round(values.filter(Boolean).length/values.length*100);return{ok:issues.length===0,score,checks,issues}}
