import type { World, Position } from './engine';
import { createWorld } from './engine';
import { ensureTechnicalProfiles, effectiveAbilityAtPosition, positionFamiliarity, recordPositionMinutes, technicalProfile, trainPosition } from './player-technical-profile-v2';

export type PlayerTechnicalDiagnostic={ok:boolean;score:number;issues:string[];players:number;attributeCount:number;naturalAverage:number;secondaryAverage:number;outOfPositionAverage:number};
const positions:Position[]=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];
const avg=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
export function diagnosePlayerTechnicalModel(world:World):PlayerTechnicalDiagnostic{const issues:string[]=[],state=ensureTechnicalProfiles(world),players=world.clubs.flatMap(c=>c.players),naturals:number[]=[],secondary:number[]=[],oop:number[]=[];let attrCount=0;for(const p of players){const t=technicalProfile(world,p.id);if(!t){issues.push(`missing technical profile ${p.id}`);continue}const entries=Object.entries(t.attributes);attrCount=Math.max(attrCount,entries.length);for(const [k,v] of entries)if(!Number.isFinite(v)||v<1||v>99)issues.push(`invalid detailed attribute ${p.id}:${k}=${v}`);for(const pos of positions){const f=positionFamiliarity(world,p.id,pos);if(pos===p.position)naturals.push(f);else if(f>=45)secondary.push(f);else oop.push(f)}if(positionFamiliarity(world,p.id,p.position)<90)issues.push(`natural position below 90: ${p.id}`);const natural=effectiveAbilityAtPosition(world,p,p.position),worst=positions.map(pos=>effectiveAbilityAtPosition(world,p,pos)).sort((a,b)=>a-b)[0];if(natural<worst)issues.push(`natural effective ability below out-of-position: ${p.id}`)}if(attrCount<35)issues.push(`detailed attribute set too small: ${attrCount}`);const naturalAverage=avg(naturals),secondaryAverage=avg(secondary),outOfPositionAverage=avg(oop);if(naturalAverage<92)issues.push(`natural familiarity average too low: ${naturalAverage.toFixed(1)}`);if(outOfPositionAverage>=secondaryAverage)issues.push('out-of-position familiarity not meaningfully lower than secondary positions');return{ok:issues.length===0,score:Math.max(0,100-issues.length*8),issues,players:players.length,attributeCount:attrCount,naturalAverage:Number(naturalAverage.toFixed(1)),secondaryAverage:Number(secondaryAverage.toFixed(1)),outOfPositionAverage:Number(outOfPositionAverage.toFixed(1))}}
export function testPositionLearning(){const world=createWorld(),p=world.clubs[0].players.find(x=>x.position!=='GK')!,target:Position=p.position==='CM'?'AM':'CM',before=positionFamiliarity(world,p.id,target);trainPosition(world,p,target,180,82);recordPositionMinutes(world,p,target,1800);const after=positionFamiliarity(world,p.id,target);return{ok:after>before,playerId:p.id,target,before,after,gain:after-before}}
export function testTechnicalDeterminism(){const a=createWorld(),b=createWorld(),pa=a.clubs[0].players[0],pb=b.clubs[0].players[0],ta=technicalProfile(a,pa.id),tb=technicalProfile(b,pb.id);return{ok:JSON.stringify(ta?.attributes)===JSON.stringify(tb?.attributes)&&JSON.stringify(ta?.positions)===JSON.stringify(tb?.positions),playerId:pa.id}}
