import type { Player, World } from './engine';
import { createWorld, playCurrentRound } from './engine';
import { advanceToNextSeason, careerState, seasonFinished } from './lifecycle';
import { ensurePlayerProfiles, playerProfile } from './player-profile-v2';
import { retirementHistory } from './player-lifecycle-v2';

export type PopulationSeasonSnapshot={season:number;population:number;avgAge:number;u21Pct:number;o32Pct:number;avgAbility:number;avgPotential:number;elitePlayers:number;goalkeepers:number;retirements:number;youthGenerated:number};
export type PopulationRegressionResult={seasons:number;ok:boolean;score:number;snapshots:PopulationSeasonSnapshot[];issues:string[];summary:{startPopulation:number;endPopulation:number;minPopulation:number;maxPopulation:number;avgAgeStart:number;avgAgeEnd:number;eliteStart:number;eliteEnd:number;retirements:number;youthGenerated:number}};
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const pct=(n:number,d:number)=>d?100*n/d:0;
function allPlayers(w:World){return w.clubs.flatMap(c=>c.players)}
function snapshot(w:World):PopulationSeasonSnapshot{const ps=allPlayers(w),state=careerState(w),ret=retirementHistory(w);return{season:w.season,population:ps.length,avgAge:Number(avg(ps.map(p=>p.age)).toFixed(2)),u21Pct:Number(pct(ps.filter(p=>p.age<=21).length,ps.length).toFixed(2)),o32Pct:Number(pct(ps.filter(p=>p.age>=32).length,ps.length).toFixed(2)),avgAbility:Number(avg(ps.map(p=>p.currentAbility)).toFixed(2)),avgPotential:Number(avg(ps.map(p=>p.potentialAbility)).toFixed(2)),elitePlayers:ps.filter(p=>p.currentAbility>=82).length,goalkeepers:ps.filter(p=>p.position==='GK').length,retirements:ret.length,youthGenerated:state.youthIntakes.length}}
function validateSnapshot(s:PopulationSeasonSnapshot,clubs:number,issues:string[]){const min=clubs*18,max=clubs*34;if(s.population<min)issues.push(`${s.season}: população abaixo do mínimo sustentável (${s.population}<${min}).`);if(s.population>max)issues.push(`${s.season}: população acima do limite esperado (${s.population}>${max}).`);if(s.avgAge<20.5||s.avgAge>30.5)issues.push(`${s.season}: idade média anormal (${s.avgAge}).`);if(s.u21Pct<8||s.u21Pct>48)issues.push(`${s.season}: proporção sub-21 anormal (${s.u21Pct}%).`);if(s.o32Pct>35)issues.push(`${s.season}: excesso de atletas 32+ (${s.o32Pct}%).`);if(s.avgAbility<40||s.avgAbility>82)issues.push(`${s.season}: habilidade média fora de faixa (${s.avgAbility}).`);if(s.goalkeepers<clubs*2)issues.push(`${s.season}: clubes sem profundidade mínima de goleiros.`)}
export function runPlayerPopulationRegression(input:{seasons?:number;worldFactory?:()=>World;playRound?:(w:World)=>void}={}):PopulationRegressionResult{const seasons=Math.max(1,Math.min(80,input.seasons??50)),world=(input.worldFactory??createWorld)(),play=input.playRound??playCurrentRound,issues:string[]=[],snapshots:PopulationSeasonSnapshot[]=[];ensurePlayerProfiles(world);snapshots.push(snapshot(world));for(let i=0;i<seasons;i++){let guard=0;while(!seasonFinished(world)&&guard<500){play(world);guard++}if(!seasonFinished(world)){issues.push(`${world.season}: temporada não concluiu dentro do guard.`);break}advanceToNextSeason(world);ensurePlayerProfiles(world);const s=snapshot(world);snapshots.push(s);validateSnapshot(s,world.clubs.length,issues);const ids=allPlayers(world).map(p=>p.id);if(new Set(ids).size!==ids.length)issues.push(`${world.season}: IDs de jogadores duplicados.`);for(const p of allPlayers(world)){const prof=playerProfile(world,p.id);if(!prof)issues.push(`${world.season}: perfil ausente para ${p.id}.`);else if(prof.potential.floor>prof.potential.projection||prof.potential.projection>prof.potential.ceiling)issues.push(`${world.season}: envelope de potencial inválido em ${p.id}.`)}}
 const first=snapshots[0],last=snapshots[snapshots.length-1],pops=snapshots.map(s=>s.population),career=careerState(world),ret=retirementHistory(world);if(last&&first&&Math.abs(last.avgAbility-first.avgAbility)>18)issues.push(`Drift de habilidade média excessivo: ${first.avgAbility} -> ${last.avgAbility}.`);if(last&&first&&Math.abs(last.avgAge-first.avgAge)>6)issues.push(`Drift demográfico excessivo: ${first.avgAge} -> ${last.avgAge}.`);const score=Math.max(0,100-issues.length*5);return{seasons:snapshots.length-1,ok:issues.length===0,score,snapshots,issues,summary:{startPopulation:first.population,endPopulation:last.population,minPopulation:Math.min(...pops),maxPopulation:Math.max(...pops),avgAgeStart:first.avgAge,avgAgeEnd:last.avgAge,eliteStart:first.elitePlayers,eliteEnd:last.elitePlayers,retirements:ret.length,youthGenerated:career.youthIntakes.length}}}
