import type { Player, Position, World } from './engine';
import { playerProfile } from './player-profile-v2';

export type PartnershipType='GK-CB'|'CB-CB'|'FB-Winger'|'DM-CM'|'CM-AM'|'AM-ST'|'ST-ST'|'generic';
export type PlayerPartnership={a:string;b:string;type:PartnershipType;chemistry:number;minutesTogether:number;matchesTogether:number;tacticalCompatibility:number;personalAffinity:number;languageCompatibility:number;lastSeason:number};
export type PartnershipSnapshot={pairs:[string,PlayerPartnership][]};
type State={pairs:Map<string,PlayerPartnership>};const states=new WeakMap<World,State>();const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));const pairKey=(a:string,b:string)=>[a,b].sort().join('::');
function state(w:World){let s=states.get(w);if(!s){s={pairs:new Map()};states.set(w,s)}return s}
function typeFor(a:Position,b:Position):PartnershipType{const s=new Set([a,b]);if(s.has('GK')&&s.has('CB'))return'GK-CB';if(a==='CB'&&b==='CB')return'CB-CB';if((s.has('RB')||s.has('LB'))&&(s.has('RW')||s.has('LW')))return'FB-Winger';if(s.has('DM')&&s.has('CM'))return'DM-CM';if(s.has('CM')&&s.has('AM'))return'CM-AM';if(s.has('AM')&&s.has('ST'))return'AM-ST';if(a==='ST'&&b==='ST')return'ST-ST';return'generic'}
function initial(w:World,a:Player,b:Player):PlayerPartnership{const pa=playerProfile(w,a.id),pb=playerProfile(w,b.id),sameNation=Boolean(pa&&pb&&pa.nationalities.some(x=>pb.nationalities.includes(x))),adapt=((pa?.hidden.adaptability??50)+(pb?.hidden.adaptability??50))/2,teamwork=((pa?.hidden.professionalism??50)+(pb?.hidden.professionalism??50))/2;return{a:a.id,b:b.id,type:typeFor(a.position,b.position),chemistry:Math.round(clamp(28+adapt*.16+teamwork*.12+(sameNation?10:0))),minutesTogether:0,matchesTogether:0,tacticalCompatibility:Math.round(clamp(45+adapt*.25)),personalAffinity:Math.round(clamp(42+((pa?.hidden.loyalty??50)+(pb?.hidden.loyalty??50))/5)),languageCompatibility:sameNation?85:48,lastSeason:w.season}}
export function ensurePartnership(w:World,a:Player,b:Player){const s=state(w),k=pairKey(a.id,b.id);let p=s.pairs.get(k);if(!p){p=initial(w,a,b);s.pairs.set(k,p)}return p}
export function recordPartnershipMinutes(w:World,a:Player,b:Player,minutes:number,input:{tacticalFit?:number;relationship?:number;sharedSuccess?:number}={}){const p=ensurePartnership(w,a,b),fit=input.tacticalFit??p.tacticalCompatibility,rel=input.relationship??p.personalAffinity,success=input.sharedSuccess??50,gain=minutes/900*(2.2+fit/35+rel/45+success/55)*(1-p.chemistry/112);p.minutesTogether+=minutes;p.matchesTogether+=minutes>=30?1:0;p.tacticalCompatibility=Math.round(clamp(p.tacticalCompatibility*.92+fit*.08));p.personalAffinity=Math.round(clamp(p.personalAffinity*.94+rel*.06));p.chemistry=Number(clamp(p.chemistry+gain).toFixed(1));p.lastSeason=w.season;return p}
export function partnershipBonus(w:World,aId:string,bId:string){const p=state(w).pairs.get(pairKey(aId,bId));if(!p)return 0;const experience=Math.min(1,p.minutesTogether/5000),quality=(p.chemistry*.5+p.tacticalCompatibility*.25+p.personalAffinity*.15+p.languageCompatibility*.1)/100;return Number((quality*experience*8).toFixed(2))}
export function decayPartnerships(w:World){for(const p of state(w).pairs.values()){const idle=Math.max(0,w.season-p.lastSeason);if(idle>0)p.chemistry=Number(clamp(p.chemistry-idle*2.2,0,100).toFixed(1))}}
export function strongestPartnerships(w:World,limit=20){return[...state(w).pairs.values()].sort((a,b)=>b.chemistry-a.chemistry||b.minutesTogether-a.minutesTogether).slice(0,limit)}
export function snapshotPartnerships(w:World):PartnershipSnapshot{return{pairs:[...state(w).pairs.entries()].map(([k,v])=>[k,{...v}])}}
export function restorePartnerships(w:World,x:PartnershipSnapshot){states.set(w,{pairs:new Map(x.pairs.map(([k,v])=>[k,{...v}]))})}
