import type { Player, World } from './engine';
import { deterministicRandom } from './world-core-v2';
import { playerProfile } from './player-profile-v2';
import { technicalProfile } from './player-technical-profile-v2';

export type BehavioralProfile={riskAppetite:number;verticality:number;creativeFreedom:number;pressResistance:number;ballRetention:number;progressionBias:number;dribblePreference:number;shootingEagerness:number;crossingPreference:number;tempoPreference:number;defensiveAggression:number;pressingDiscipline:number;positioningDiscipline:number;offBallRoaming:number;supportInstinct:number;counterAttackInstinct:number};
export type PlayerTrait='triesKillerBalls'|'dictatesTempo'|'carriesBallThroughCentre'|'cutsInside'|'hugsLine'|'shootsFromDistance'|'avoidsWeakFoot'|'roundsKeeper'|'playsOneTwos'|'playsSimplePasses'|'comesDeep'|'movesIntoChannels'|'switchesPlay'|'marksTightly'|'divesIntoTackles'|'avoidsSlidingTackles'|'anticipatesRatherThanChallenges';
export type TraitState={trait:PlayerTrait;strength:number;learned:boolean;learningProgress:number;active:boolean};
export type PlayerBehaviorState={playerId:string;behavior:BehavioralProfile;traits:TraitState[];version:number};
export type BehaviorSnapshot={players:[string,PlayerBehaviorState][]};
type State={players:Map<string,PlayerBehaviorState>};const states=new WeakMap<World,State>();const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
function state(w:World){let s=states.get(w);if(!s){s={players:new Map()};states.set(w,s)}return s}
function r(w:World,p:Player,key:string){return deterministicRandom(w,'players',`${p.id}:behavior:${key}`)}
function behavior(w:World,p:Player):BehavioralProfile{const tech=technicalProfile(w,p.id)?.attributes,hidden=playerProfile(w,p.id)?.hidden;const n=(base:number,key:string,spread=10)=>Math.round(clamp(base+(r(w,p,key)-.5)*spread));const vision=tech?.vision??p.attributes.passing,comp=tech?.composure??p.attributes.decisions,drib=tech?.dribbling??p.attributes.technique,off=tech?.offBall??p.attributes.positioning,work=tech?.workRate??p.attributes.stamina;return{riskAppetite:n((hidden?.ambition??55)*.28+(hidden?.pressure??55)*.2+vision*.28+comp*.24,'risk'),verticality:n(vision*.34+p.attributes.passing*.26+p.attributes.pace*.18+(hidden?.ambition??55)*.22,'vertical'),creativeFreedom:n(vision*.38+(tech?.technique??p.attributes.technique)*.28+(hidden?.adaptability??55)*.16+(hidden?.controversy??30)*.18,'creative'),pressResistance:n(comp*.38+(tech?.firstTouch??p.attributes.technique)*.32+(tech?.balance??55)*.16+(hidden?.pressure??55)*.14,'pressResistance'),ballRetention:n(comp*.28+(tech?.firstTouch??55)*.27+(tech?.shortPassing??p.attributes.passing)*.25+(hidden?.temperament??55)*.2,'retention'),progressionBias:n(vision*.32+off*.22+p.attributes.pace*.18+(hidden?.ambition??55)*.18+(hidden?.bigMatches??55)*.1,'progression'),dribblePreference:n(drib*.42+p.attributes.pace*.23+(hidden?.ambition??55)*.18+(hidden?.controversy??30)*.17,'dribble'),shootingEagerness:n((tech?.finishing??p.attributes.finishing)*.34+(tech?.longShots??p.attributes.finishing)*.27+(hidden?.ambition??55)*.22+(hidden?.pressure??55)*.17,'shoot'),crossingPreference:n((tech?.crossing??p.attributes.passing)*.46+(p.position==='RW'||p.position==='LW'||p.position==='RB'||p.position==='LB'?25:0)+(tech?.teamwork??hidden?.professionalism??55)*.2,'cross'),tempoPreference:n((tech?.decisions??p.attributes.decisions)*.3+(tech?.vision??p.attributes.passing)*.26+(hidden?.pressure??55)*.18+(hidden?.adaptability??55)*.16+p.attributes.pace*.1,'tempo'),defensiveAggression:n((tech?.aggression??50)*.44+(tech?.bravery??50)*.2+p.attributes.tackling*.2+(hidden?.temperament??55)*.16,'defAgg'),pressingDiscipline:n((tech?.workRate??work)*.34+(tech?.teamwork??55)*.27+(tech?.decisions??p.attributes.decisions)*.22+(hidden?.professionalism??55)*.17,'pressDisc'),positioningDiscipline:n((tech?.concentration??55)*.34+(tech?.anticipation??55)*.25+p.attributes.positioning*.25+(hidden?.professionalism??55)*.16,'posDisc'),offBallRoaming:n(off*.32+(hidden?.adaptability??55)*.24+(hidden?.ambition??55)*.18+(tech?.vision??55)*.14+(hidden?.controversy??30)*.12,'roam'),supportInstinct:n((tech?.teamwork??55)*.39+(tech?.offBall??off)*.23+(tech?.decisions??55)*.2+(hidden?.loyalty??55)*.18,'support'),counterAttackInstinct:n(p.attributes.pace*.28+(tech?.anticipation??55)*.24+(tech?.offBall??55)*.2+(tech?.decisions??55)*.18+(hidden?.pressure??55)*.1,'counter')};}
function defaultTraits(b:BehavioralProfile):TraitState[]{const defs:[PlayerTrait,number][]=[['triesKillerBalls',(b.verticality+b.creativeFreedom)/2],['dictatesTempo',(b.tempoPreference+b.ballRetention)/2],['carriesBallThroughCentre',b.dribblePreference],['shootsFromDistance',b.shootingEagerness],['playsOneTwos',b.supportInstinct],['playsSimplePasses',100-b.riskAppetite],['comesDeep',b.ballRetention],['movesIntoChannels',(b.offBallRoaming+b.progressionBias)/2],['switchesPlay',(b.creativeFreedom+b.verticality)/2],['marksTightly',b.positioningDiscipline],['divesIntoTackles',b.defensiveAggression],['anticipatesRatherThanChallenges',(b.positioningDiscipline+100-b.defensiveAggression)/2]];return defs.filter(([,v])=>v>=68).map(([trait,v])=>({trait,strength:Math.round(v),learned:false,learningProgress:100,active:true}))}
export function ensurePlayerBehavior(w:World,p:Player){const s=state(w);let x=s.players.get(p.id);if(!x){const b=behavior(w,p);x={playerId:p.id,behavior:b,traits:defaultTraits(b),version:1};s.players.set(p.id,x)}return x}
export function playerBehavior(w:World,id:string){for(const c of w.clubs){const p=c.players.find(x=>x.id===id);if(p)return ensurePlayerBehavior(w,p)}return state(w).players.get(id)}
export function trainTrait(w:World,p:Player,trait:PlayerTrait,hours:number,coachQuality=60){const s=ensurePlayerBehavior(w,p);let t=s.traits.find(x=>x.trait===trait);if(!t){t={trait,strength:35,learned:true,learningProgress:0,active:false};s.traits.push(t)}const prof=playerProfile(w,p.id),adapt=(prof?.hidden.adaptability??50)/100,professional=(prof?.hidden.professionalism??50)/100,gain=hours/20*(.45+coachQuality/150)*(.55+adapt*.4+professional*.2);t.learningProgress=clamp(t.learningProgress+gain);if(t.learningProgress>=100){t.active=true;t.learned=true;t.strength=Math.round(clamp(55+adapt*25+professional*15))}return t}
export function unlearnTrait(w:World,p:Player,trait:PlayerTrait,hours:number){const t=ensurePlayerBehavior(w,p).traits.find(x=>x.trait===trait);if(!t)return;const prof=playerProfile(w,p.id),adapt=(prof?.hidden.adaptability??50)/100;t.strength=Math.round(clamp(t.strength-hours/25*(.7+adapt),0,100));if(t.strength<25)t.active=false;return t}
export function snapshotPlayerBehavior(w:World):BehaviorSnapshot{return{players:[...state(w).players.entries()].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}
export function restorePlayerBehavior(w:World,x:BehaviorSnapshot){states.set(w,{players:new Map(x.players.map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
