import type { Player, PlayerAttributes, Position, World } from './engine';
import { deterministicRandom, worldCore, queueWorldEvent } from './world-core-v2';
import { addEligibility, registerPlayerProfile } from './player-profile-v2';

export type YouthGenerationContext={clubId:string;countryId:string;season:number;academyQuality:number;recruitmentReach:number;positionNeed?:Position;serial:number};
export type YouthGenerationResult={player:Player;profileSeed:string;rarity:'ordinary'|'promising'|'elite'|'generational'};
const positions:Position[]=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];
const firstBR=['Arthur','Bernardo','Caio','Davi','Eduardo','Felipe','Gabriel','Heitor','João','Lucas','Mateus','Miguel','Otávio','Pedro','Rafael','Samuel','Thiago','Vinícius','Wesley','Yuri'];
const lastBR=['Almeida','Barbosa','Cardoso','Duarte','Ferreira','Gomes','Lima','Martins','Nogueira','Oliveira','Pereira','Rocha','Santos','Silva','Souza','Teixeira','Vieira'];
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const r=(w:World,key:string)=>deterministicRandom(w,'youth',key);
function pick<T>(w:World,key:string,list:T[]){return list[Math.floor(r(w,key)*list.length)]}
function attrBase(base:number,pos:Position,w:World,key:string):PlayerAttributes{const a=(bias:number,k:string)=>Math.round(clamp(base+bias+(r(w,`${key}:${k}`)-.5)*16,20,92));return{pace:a(['RB','LB','RW','LW'].includes(pos)?8:pos==='GK'?-10:0,'pace'),passing:a(['DM','CM','AM'].includes(pos)?8:pos==='GK'?-8:0,'passing'),technique:a(['AM','RW','LW','ST'].includes(pos)?6:0,'technique'),finishing:a(pos==='ST'?11:['AM','RW','LW'].includes(pos)?5:-6,'finishing'),tackling:a(['CB','RB','LB','DM'].includes(pos)?10:-6,'tackling'),positioning:a(['GK','CB','DM'].includes(pos)?8:2,'positioning'),stamina:a(['RB','LB','DM','CM'].includes(pos)?6:0,'stamina'),decisions:a(-2,'decisions'),goalkeeping:a(pos==='GK'?16:-35,'goalkeeping')};}
export function generateYouthPlayerV2(world:World,ctx:YouthGenerationContext):YouthGenerationResult{const key=`${ctx.clubId}:${ctx.season}:${ctx.serial}:${ctx.countryId}`,roll=r(world,`${key}:rarity`),rarity:YouthGenerationResult['rarity']=roll>.995?'generational':roll>.965?'elite':roll>.78?'promising':'ordinary',quality=clamp(ctx.academyQuality*.72+ctx.recruitmentReach*.28),age=16+Math.floor(r(world,`${key}:age`)*3),pos=ctx.positionNeed??pick(world,`${key}:pos`,positions),rarityBoost=rarity==='generational'?18:rarity==='elite'?11:rarity==='promising'?5:0,current=Math.round(clamp(34+quality*.31+rarityBoost*.18+(r(world,`${key}:ca`)-.5)*11,30,72)),ceilingBonus=rarity==='generational'?28:rarity==='elite'?23:rarity==='promising'?17:10,potential=Math.round(clamp(current+ceilingBonus+r(world,`${key}:pa`)*10,Math.max(current+6,48),rarity==='generational'?99:rarity==='elite'?95:91)),first=pick(world,`${key}:first`,firstBR),last=pick(world,`${key}:last`,lastBR),id=`yg-${ctx.countryId}-${ctx.season}-${ctx.clubId}-${ctx.serial}-${Math.floor(r(world,`${key}:id`)*1e8).toString(36)}`,p:Player={id,clubId:ctx.clubId,name:`${first} ${last}`,position:pos,age,currentAbility:current,potentialAbility:potential,condition:94+Math.round(r(world,`${key}:condition`)*6),morale:68+Math.round(r(world,`${key}:morale`)*25),attributes:attrBase(current,pos,world,key)};return{player:p,profileSeed:key,rarity}}
export function registerGeneratedYouth(world:World,result:YouthGenerationResult,countryId:string){const p=result.player,profile=registerPlayerProfile(world,p,{createdBy:'generated',birthCountryId:countryId,nationalities:[countryId],citizenships:[countryId],potential:{floor:Math.max(p.currentAbility,p.potentialAbility-18),ceiling:Math.min(99,p.potentialAbility+4),projection:p.potentialAbility,certainty:28,lateBloomer:Math.round(r(world,`${result.profileSeed}:late`)*100),developmentVolatility:45+Math.round(r(world,`${result.profileSeed}:vol`)*40)}});addEligibility(world,p.id,{countryId,basis:'birth',eligible:true,capTied:false,seniorCaps:0,youthCaps:0});queueWorldEvent(world,{date:worldCore(world).date,type:'YouthPlayerGenerated',scope:'person',entityIds:[p.id,p.clubId],importance:result.rarity==='generational'?5:result.rarity==='elite'?4:2,payload:{rarity:result.rarity,currentAbility:p.currentAbility,potentialProjection:profile.potential.projection,countryId}});return profile}
export function generateClubYouthIntakeV2(world:World,input:{clubId:string;countryId:string;season?:number;academyQuality:number;recruitmentReach:number;count:number;positionNeeds?:Position[]}){const out:YouthGenerationResult[]=[];for(let i=0;i<input.count;i++){const result=generateYouthPlayerV2(world,{clubId:input.clubId,countryId:input.countryId,season:input.season??world.season,academyQuality:input.academyQuality,recruitmentReach:input.recruitmentReach,positionNeed:input.positionNeeds?.[i],serial:i+1});out.push(result)}return out}
