import type { Player, World } from './engine';
import { deterministicRandom } from './world-core-v2';
import { playerProfile } from './player-profile-v2';
import { technicalProfile, type DetailedPlayerAttributes } from './player-technical-profile-v2';

export type ScoutSkill={judgingAbility:number;judgingPotential:number;tacticalEvaluation:number;medicalAwareness:number;regionalKnowledge:number};
export type AttributeEstimate={attribute:keyof DetailedPlayerAttributes;min:number;max:number;confidence:number;observations:number};
export type ScoutingKnowledge={playerId:string;observerId:string;overallKnowledge:number;abilityRange:[number,number];potentialRange:[number,number];personalityKnown:number;medicalKnown:number;attributes:Partial<Record<keyof DetailedPlayerAttributes,AttributeEstimate>>;lastObservedDate?:string;matchesObserved:number};
export type ScoutingSnapshot={entries:[string,ScoutingKnowledge][]};
type State={entries:Map<string,ScoutingKnowledge>};const states=new WeakMap<World,State>();const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));const key=(observerId:string,playerId:string)=>`${observerId}:${playerId}`;
function state(w:World){let s=states.get(w);if(!s){s={entries:new Map()};states.set(w,s)}return s}
function noise(w:World,observerId:string,playerId:string,tag:string){return deterministicRandom(w,'players',`scout:${observerId}:${playerId}:${tag}`)-.5}
export function ensureScoutingKnowledge(w:World,observerId:string,p:Player,skill:ScoutSkill):ScoutingKnowledge{const s=state(w),k=key(observerId,p.id);let x=s.entries.get(k);if(x)return x;const abilityErr=(100-skill.judgingAbility)*.12+7,potentialErr=(100-skill.judgingPotential)*.16+10,abilityMid=clamp(p.currentAbility+noise(w,observerId,p.id,'ability')*abilityErr),prof=playerProfile(w,p.id),potentialMid=clamp((prof?.potential.projection??p.potentialAbility)+noise(w,observerId,p.id,'potential')*potentialErr);x={playerId:p.id,observerId,overallKnowledge:8+skill.regionalKnowledge*.12,abilityRange:[Math.round(clamp(abilityMid-abilityErr)),Math.round(clamp(abilityMid+abilityErr))],potentialRange:[Math.round(clamp(potentialMid-potentialErr)),Math.round(clamp(potentialMid+potentialErr))],personalityKnown:Math.round(skill.tacticalEvaluation*.08),medicalKnown:Math.round(skill.medicalAwareness*.08),attributes:{},matchesObserved:0};s.entries.set(k,x);return x}
export function observePlayer(w:World,observerId:string,p:Player,skill:ScoutSkill,input:{minutes?:number;match?:boolean;training?:boolean;medicalAccess?:boolean;date?:string}={}){const x=ensureScoutingKnowledge(w,observerId,p,skill),tech=technicalProfile(w,p.id),minutes=input.minutes??90,weight=(input.match?1:input.training?.7:.45)*Math.min(1.3,minutes/90),gain=(4+skill.regionalKnowledge*.025+skill.judgingAbility*.035)*weight;x.overallKnowledge=clamp(x.overallKnowledge+gain);x.matchesObserved+=input.match?1:0;x.lastObservedDate=input.date;const shrink=Math.max(.18,1-x.overallKnowledge/118),abilityErr=Math.max(1.5,(100-skill.judgingAbility)*.055+10*shrink),potentialErr=Math.max(3,(100-skill.judgingPotential)*.085+16*shrink),abilityMid=p.currentAbility+noise(w,observerId,p.id,`ability-${x.matchesObserved}`)*abilityErr*.5,prof=playerProfile(w,p.id),potentialMid=(prof?.potential.projection??p.potentialAbility)+noise(w,observerId,p.id,`potential-${x.matchesObserved}`)*potentialErr*.55;x.abilityRange=[Math.round(clamp(abilityMid-abilityErr)),Math.round(clamp(abilityMid+abilityErr))];x.potentialRange=[Math.round(clamp(potentialMid-potentialErr)),Math.round(clamp(potentialMid+potentialErr))];x.personalityKnown=clamp(x.personalityKnown+weight*skill.tacticalEvaluation*.055);x.medicalKnown=clamp(x.medicalKnown+weight*skill.medicalAwareness*.04+(input.medicalAccess?25:0));if(tech){for(const [attr,value] of Object.entries(tech.attributes) as [keyof DetailedPlayerAttributes,number][]) {const existing=x.attributes[attr],obs=(existing?.observations??0)+1,baseErr=Math.max(1,(100-skill.judgingAbility)*.045+12*(1-x.overallKnowledge/110)),mid=value+noise(w,observerId,p.id,`${String(attr)}-${obs}`)*baseErr;x.attributes[attr]={attribute:attr,min:Math.round(clamp(mid-baseErr)),max:Math.round(clamp(mid+baseErr)),confidence:Math.round(clamp(100-baseErr*5)),observations:obs}}}return x}
export function scoutingKnowledge(w:World,observerId:string,playerId:string){return state(w).entries.get(key(observerId,playerId))}
export function scoutDisplayValue(x:ScoutingKnowledge,attr:keyof DetailedPlayerAttributes){const a=x.attributes[attr];return a?`${a.min}-${a.max}`:'desconhecido'}
export function snapshotScouting(w:World):ScoutingSnapshot{return{entries:[...state(w).entries.entries()].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}
export function restoreScouting(w:World,x:ScoutingSnapshot){states.set(w,{entries:new Map(x.entries.map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
