import type { Player, PlayerAttributes, Position, World } from './engine';
import { playerProfile } from './player-profile-v2';
import { playerSeasonStats } from './match-season-history-v2';
import { deterministicRandom } from './world-core-v2';

export type DevelopmentDomain='physical'|'technical'|'mental'|'goalkeeping';
export type DevelopmentContext={season:number;trainingQuality?:number;facilities?:number;coachQuality?:number;injuryBurden?:number;minutesTarget?:number};
export type DevelopmentOutcome={playerId:string;before:number;after:number;delta:number;domainDelta:Record<DevelopmentDomain,number>;potentialProjection:number;reasons:string[]};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const physical=new Set<keyof PlayerAttributes>(['pace','stamina']);
const mental=new Set<keyof PlayerAttributes>(['decisions','positioning']);
const technical=new Set<keyof PlayerAttributes>(['passing','technique','finishing','tackling']);
function peakAge(pos:Position){if(pos==='GK')return 31;if(pos==='CB'||pos==='DM')return 29;if(pos==='ST'||pos==='RW'||pos==='LW')return 27;return 28}
function ageCurve(age:number,pos:Position,domain:DevelopmentDomain){const peak=peakAge(pos);if(domain==='physical'){if(age<=19)return 1.12;if(age<=23)return .82;if(age<=peak)return .28;if(age<=peak+2)return -.15;if(age<=peak+5)return -.6;return -1.15}if(domain==='mental'){if(age<=20)return .32;if(age<=29)return .46;if(age<=34)return .22;return -.08}if(domain==='goalkeeping'){if(pos!=='GK')return 0;if(age<=22)return .65;if(age<=31)return .42;if(age<=35)return -.18;return -.72}if(age<=19)return .9;if(age<=23)return .72;if(age<=peak)return .34;if(age<=peak+3)return -.14;if(age<=peak+6)return -.45;return -.82}
function attrDomain(k:keyof PlayerAttributes):DevelopmentDomain{return k==='goalkeeping'?'goalkeeping':physical.has(k)?'physical':mental.has(k)?'mental':'technical'}
function usageFactor(world:World,p:Player,season:number,target=2200){const stats=playerSeasonStats(world,p.id,season),minutes=stats?.minutes??0;const ageNeed=p.age<=21?.72:p.age<=24?.58:.35;return clamp(minutes/target,0,1.25)*ageNeed+(1-ageNeed)*.55}
export function projectPlayerDevelopment(world:World,p:Player,ctx:DevelopmentContext):DevelopmentOutcome{const prof=playerProfile(world,p.id),hidden=prof?.hidden,season=ctx.season,usage=usageFactor(world,p,season,ctx.minutesTarget),professionalism=(hidden?.professionalism??60)/100,ambition=(hidden?.ambition??55)/100,volatility=(prof?.potential.developmentVolatility??45)/100,training=clamp((ctx.trainingQuality??60)*.35+(ctx.facilities??60)*.3+(ctx.coachQuality??60)*.35)/100,injury=Math.max(0,ctx.injuryBurden??0),gap=Math.max(0,(prof?.potential.projection??p.potentialAbility)-p.currentAbility),reasons:string[]=[],domainDelta={physical:0,technical:0,mental:0,goalkeeping:0};for(const domain of Object.keys(domainDelta) as DevelopmentDomain[]){const age=ageCurve(p.age,p.position,domain),opportunity=age>0?(0.5+usage*.5):(1+Math.max(0,1-usage)*.08),ceiling=age>0?Math.min(1.25,gap/12+.25):1,injuryPenalty=domain==='physical'?injury*.018:injury*.007,noise=(deterministicRandom(world,'players',`${p.id}:${season}:${domain}`)-.5)*volatility*.55,delta=age*opportunity*(.55+training*.55)*(.65+professionalism*.35)*(.75+ambition*.25)*ceiling-injuryPenalty+noise;domainDelta[domain]=Number(delta.toFixed(2))}if(usage>.75&&p.age<=23)reasons.push('minutagem competitiva favoreceu o desenvolvimento');if(training>.75)reasons.push('estrutura de treino acima da média');if(prof&&prof.hidden.professionalism>78)reasons.push('alto profissionalismo sustentou a evolução');if(injury>.5)reasons.push('lesões reduziram a progressão');if(p.age>peakAge(p.position)+3)reasons.push('declínio etário passou a pesar');const weighted=domainDelta.technical*.34+domainDelta.physical*.28+domainDelta.mental*.25+domainDelta.goalkeeping*(p.position==='GK'?.42:.03),rawAfter=clamp(p.currentAbility+weighted,25,prof?.potential.ceiling??99),after=Math.round(rawAfter),projection=Math.round(clamp((prof?.potential.projection??p.potentialAbility)+(deterministicRandom(world,'players',`${p.id}:${season}:projection`)-.5)*(prof?.potential.developmentVolatility??40)/18+(usage-.5)*2+(professionalism-.5)*1.5,p.currentAbility,prof?.potential.ceiling??99));return{playerId:p.id,before:p.currentAbility,after,delta:after-p.currentAbility,domainDelta,potentialProjection:projection,reasons}}
export function applyPlayerDevelopment(world:World,p:Player,ctx:DevelopmentContext){const out=projectPlayerDevelopment(world,p,ctx),prof=playerProfile(world,p.id);const keys=Object.keys(p.attributes) as (keyof PlayerAttributes)[];for(const k of keys){const d=out.domainDelta[attrDomain(k)],bias=k==='pace'&&p.age>30?-.35:k==='decisions'&&p.age>=25?.15:0;p.attributes[k]=Math.round(clamp(p.attributes[k]+d+bias,20,99))}p.currentAbility=out.after;if(prof)prof.potential.projection=out.potentialProjection;return out}
export function developmentReadiness(world:World,p:Player,season=world.season){const prof=playerProfile(world,p.id),stats=playerSeasonStats(world,p.id,season),minutes=stats?.minutes??0;return{playerId:p.id,age:p.age,minutes,potentialGap:Math.max(0,(prof?.potential.projection??p.potentialAbility)-p.currentAbility),professionalism:prof?.hidden.professionalism??50,lateBloomer:prof?.potential.lateBloomer??50}}
