import type { Player, World } from './engine';
import { deterministicRandom, queueWorldEvent, worldCore } from './world-core-v2';
import { playerCareerStats, playerSeasonStats } from './match-season-history-v2';
import { markPlayerRetired, playerProfile } from './player-profile-v2';

export type RetirementAssessment={playerId:string;eligible:boolean;probability:number;reasons:string[];staffInterest:number};
export type RetirementRecord={playerId:string;date:string;age:number;clubId:string;careerAppearances:number;careerGoals:number;careerAssists:number;peakAbility:number;staffTransitionInterest:number};
type State={retired:RetirementRecord[];processed:Set<string>};
const states=new WeakMap<World,State>();
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
function state(w:World){let s=states.get(w);if(!s){s={retired:[],processed:new Set()};states.set(w,s)}return s}
export function assessRetirement(world:World,p:Player,date=worldCore(world).date):RetirementAssessment{const prof=playerProfile(world,p.id),career=playerCareerStats(world,p.id),season=playerSeasonStats(world,p.id,world.season),keeper=p.position==='GK',baseAge=keeper?36:34,reasons:string[]=[];if(p.age<baseAge)return{playerId:p.id,eligible:false,probability:0,reasons:['idade abaixo da faixa normal de aposentadoria'],staffInterest:prof?.staffTransitionInterest??0};let score=.04+(p.age-baseAge)*(keeper?.085:.11),minutes=season?.minutes??0;if(minutes<600){score+=.11;reasons.push('pouca utilização recente')}if(p.currentAbility<55){score+=.12;reasons.push('nível competitivo atual baixo')}if(p.condition<65){score+=.08;reasons.push('condição física deteriorada')}if((prof?.hidden.ambition??50)>78){score-=.06;reasons.push('ambição prolonga a carreira')}if((prof?.hidden.professionalism??50)>80){score-=.04;reasons.push('alto profissionalismo ajuda a prolongar a carreira')}if((prof?.hidden.injuryProneness??50)>75){score+=.05;reasons.push('histórico físico desfavorável')}if((career?.appearances??0)>500&&p.currentAbility>=65){score-=.03;reasons.push('carreira consolidada e ainda competitiva')}if(p.age>=43)score=.97;else if(!keeper&&p.age>=41)score=Math.max(score,.88);else if(keeper&&p.age>=42)score=Math.max(score,.82);return{playerId:p.id,eligible:true,probability:clamp(score,0,.98),reasons,staffInterest:prof?.staffTransitionInterest??0}}
export function maybeRetirePlayer(world:World,p:Player,date=worldCore(world).date){const s=state(world),key=`${date}:${p.id}`;if(s.processed.has(key))return;s.processed.add(key);const a=assessRetirement(world,p,date);if(!a.eligible)return;const roll=deterministicRandom(world,'players',`${p.id}:${date}:retirement`);if(roll>=a.probability)return;const c=playerCareerStats(world,p.id),record:RetirementRecord={playerId:p.id,date,age:p.age,clubId:p.clubId,careerAppearances:c?.appearances??0,careerGoals:c?.goals??0,careerAssists:c?.assists??0,peakAbility:Math.max(p.currentAbility,p.potentialAbility),staffTransitionInterest:a.staffInterest};s.retired.push(record);markPlayerRetired(world,p.id,date);queueWorldEvent(world,{date,type:'PlayerRetired',scope:'person',entityIds:[p.id,p.clubId],importance:p.currentAbility>=75?4:2,payload:{age:p.age,clubId:p.clubId,careerAppearances:record.careerAppearances,careerGoals:record.careerGoals,careerAssists:record.careerAssists,staffTransitionInterest:a.staffInterest,reasons:a.reasons}});return record}
export function annualRetirementSweep(world:World,date=worldCore(world).date){const retired:RetirementRecord[]=[];for(const club of world.clubs){const survivors:Player[]=[];for(const p of club.players){const r=maybeRetirePlayer(world,p,date);if(r)retired.push(r);else survivors.push(p)}club.players=survivors}return retired}
export function staffTransitionCandidates(world:World,minInterest=60){return state(world).retired.filter(r=>r.staffTransitionInterest>=minInterest).sort((a,b)=>b.staffTransitionInterest-a.staffTransitionInterest)}
export function retirementHistory(world:World){return[...state(world).retired]}
export function snapshotPlayerLifecycle(world:World){const s=state(world);return{retired:s.retired.map(x=>({...x})),processed:[...s.processed]}}
export function restorePlayerLifecycle(world:World,x:ReturnType<typeof snapshotPlayerLifecycle>){states.set(world,{retired:x.retired.map(r=>({...r})),processed:new Set(x.processed)})}
