import type { Player, World } from './engine';
import { realPlayersV2 } from './real-world-player-import-v2';

const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
export type RosterDuplicate={key:string;playerIds:string[];clubIds:string[];reason:'same-id'|'same-real-identity'|'probable-bio-duplicate'};
export type RosterIntegrityReport={ok:boolean;duplicates:RosterDuplicate[];removed:number;players:number;clubMemberships:number};

function probableKey(p:Player){return`${norm(p.name)}:${p.age}:${p.position}`}
export function inspectPlayerRosterIntegrity(w:World):RosterIntegrityReport{const duplicates:RosterDuplicate[]=[],byId=new Map<string,string[]>(),byBio=new Map<string,Array<{id:string;clubId:string}>>();let memberships=0;for(const c of w.clubs)for(const p of c.players){memberships++;const ids=byId.get(p.id)??[];ids.push(c.id);byId.set(p.id,ids);const k=probableKey(p),rows=byBio.get(k)??[];rows.push({id:p.id,clubId:c.id});byBio.set(k,rows)}for(const [id,clubs] of byId)if(clubs.length>1)duplicates.push({key:id,playerIds:[id],clubIds:clubs,reason:'same-id'});const real=new Map(realPlayersV2(w).map(r=>[r.player.id,r.identityKey]));for(const [k,rows] of byBio){const ids=[...new Set(rows.map(x=>x.id))];if(ids.length<2)continue;const realKeys=[...new Set(ids.map(id=>real.get(id)).filter(Boolean))];duplicates.push({key:k,playerIds:ids,clubIds:[...new Set(rows.map(x=>x.clubId))],reason:realKeys.length===1&&realKeys.length>0?'same-real-identity':'probable-bio-duplicate'})}return{ok:duplicates.length===0,duplicates,removed:0,players:byId.size,clubMemberships:memberships}}
export function dedupePlayerRosters(w:World){let removed=0;const owner=new Map<string,string>();for(const c of w.clubs){const next:Player[]=[];const local=new Set<string>();for(const p of c.players){if(local.has(p.id)){removed++;continue}local.add(p.id);const preferred=p.clubId&&w.clubs.some(x=>x.id===p.clubId)?p.clubId:undefined,existing=owner.get(p.id);if(existing&&existing!==c.id){if(preferred===c.id){const old=w.clubs.find(x=>x.id===existing);if(old){const before=old.players.length;old.players=old.players.filter(x=>x.id!==p.id);removed+=before-old.players.length}owner.set(p.id,c.id);next.push(p)}else removed++;continue}owner.set(p.id,c.id);next.push(p)}c.players=next}const after=inspectPlayerRosterIntegrity(w);return{...after,removed}}
export function movePlayerCanonical(w:World,player:Player,toClubId:string){for(const c of w.clubs)c.players=c.players.filter(x=>x.id!==player.id);player.clubId=toClubId;const club=w.clubs.find(c=>c.id===toClubId);if(club&&!club.players.some(x=>x.id===player.id))club.players.push(player);return player}
