import type { Player, Position, World } from './engine';
import { deterministicRandom, worldCore } from './world-core-v2';
import { playerFootedness } from './injuries';

export type PreferredFoot='right'|'left'|'both';
export type BodyType='slight'|'lean'|'balanced'|'powerful'|'stocky';
export type EligibilityBasis='birth'|'parent'|'grandparent'|'residency'|'citizenship';
export type NationalEligibility={countryId:string;basis:EligibilityBasis;eligible:boolean;capTied:boolean;seniorCaps:number;youthCaps:number;lastRepresentedDate?:string};
export type HiddenTraits={professionalism:number;ambition:number;consistency:number;bigMatches:number;adaptability:number;pressure:number;loyalty:number;temperament:number;leadership:number;controversy:number;injuryProneness:number};
export type PotentialEnvelope={floor:number;ceiling:number;projection:number;certainty:number;lateBloomer:number;developmentVolatility:number};
export type PhysicalProfile={heightCm:number;weightKg:number;preferredFoot:PreferredFoot;weakFoot:number;bodyType:BodyType;growthComplete:boolean};
export type PlayerIdentityProfile={playerId:string;birthDate:string;birthCountryId:string;birthCityId?:string;nationalities:string[];citizenships:string[];eligibility:NationalEligibility[];physical:PhysicalProfile;hidden:HiddenTraits;potential:PotentialEnvelope;positionFamiliarity:Partial<Record<Position,number>>;createdBy:'seeded'|'generated'|'imported'|'real';retired:boolean;retiredDate?:string;staffTransitionInterest:number};
export type PlayerProfileSnapshot={profiles:[string,PlayerIdentityProfile][]};

type State={profiles:Map<string,PlayerIdentityProfile>};
const states=new WeakMap<World,State>();
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const isoAgeDate=(date:string,age:number,r:number)=>{const y=Number(date.slice(0,4))-age-(r<.35?1:0),m=1+Math.floor(r*12),d=1+Math.floor(((r*997)%1)*28);return`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`};
const rand=(w:World,id:string,key:string)=>deterministicRandom(w,'players',`${id}:${key}`);
function bodyFor(position:Position,height:number,weight:number):BodyType{const bmi=weight/((height/100)**2);if(position==='GK'||position==='CB'||position==='ST')return bmi>24.2?'powerful':'balanced';if(bmi<20.8)return'slight';if(bmi<22.5)return'lean';if(bmi>25.5)return'stocky';return'balanced'}
function defaultHeight(p:Player,r:number){const ranges:Record<Position,[number,number]>={GK:[184,199],RB:[168,188],CB:[178,198],LB:[168,188],DM:[174,193],CM:[168,190],AM:[165,188],RW:[164,187],LW:[164,187],ST:[174,198]};const [a,b]=ranges[p.position];return Math.round(a+(b-a)*r)}
function familiarity(p:Player):Partial<Record<Position,number>>{const out:Partial<Record<Position,number>>={[p.position]:100};const related:Partial<Record<Position,Position[]>>={RB:['LB','CB','DM'],LB:['RB','CB','DM'],CB:['RB','LB','DM'],DM:['CM','CB','AM'],CM:['DM','AM'],AM:['CM','RW','LW','ST'],RW:['LW','AM','ST'],LW:['RW','AM','ST'],ST:['AM','RW','LW'],GK:[]};for(const pos of related[p.position]??[])out[pos]=pos===p.position?100:60;return out}
function trait(world:World,p:Player,key:string,min=25,max=90){return Math.round(min+(max-min)*rand(world,p.id,key))}
function profile(world:World,p:Player):PlayerIdentityProfile{const date=worldCore(world).date,foot=playerFootedness(world,p.id),h=defaultHeight(p,rand(world,p.id,'height')),weight=Math.round((h-100)*(.86+rand(world,p.id,'weight')*.18)),floor=Math.max(p.currentAbility,Math.round(p.potentialAbility-10-rand(world,p.id,'floor')*8)),ceiling=Math.min(99,Math.max(p.potentialAbility,Math.round(p.potentialAbility+rand(world,p.id,'ceiling')*6))),projection=Math.round(clamp((floor+ceiling)/2,p.currentAbility,99)),certainty=Math.round(45+rand(world,p.id,'certainty')*45),birthCountryId='BRA',birthDate=isoAgeDate(date,p.age,rand(world,p.id,'birthDate')),weakFoot=Math.round(28+rand(world,p.id,'weakFoot')*67);const hidden:HiddenTraits={professionalism:trait(world,p,'professionalism'),ambition:trait(world,p,'ambition'),consistency:trait(world,p,'consistency'),bigMatches:trait(world,p,'bigMatches'),adaptability:trait(world,p,'adaptability'),pressure:trait(world,p,'pressure'),loyalty:trait(world,p,'loyalty'),temperament:trait(world,p,'temperament'),leadership:trait(world,p,'leadership'),controversy:trait(world,p,'controversy',5,65),injuryProneness:trait(world,p,'injuryProneness',15,80)};return{playerId:p.id,birthDate,birthCountryId,nationalities:[birthCountryId],citizenships:[birthCountryId],eligibility:[{countryId:birthCountryId,basis:'birth',eligible:true,capTied:false,seniorCaps:0,youthCaps:0}],physical:{heightCm:h,weightKg:weight,preferredFoot:foot,weakFoot,bodyType:bodyFor(p.position,h,weight),growthComplete:p.age>=20},hidden,potential:{floor,ceiling,projection,certainty,lateBloomer:Math.round(rand(world,p.id,'lateBloomer')*100),developmentVolatility:Math.round(20+rand(world,p.id,'volatility')*65)},positionFamiliarity:familiarity(p),createdBy:'seeded',retired:false,staffTransitionInterest:Math.round(rand(world,p.id,'staff')*100)}}
function state(world:World){let s=states.get(world);if(!s){s={profiles:new Map()};states.set(world,s)}return s}
export function ensurePlayerProfiles(world:World){const s=state(world);for(const c of world.clubs)for(const p of c.players)if(!s.profiles.has(p.id))s.profiles.set(p.id,profile(world,p));return s}
export function registerPlayerProfile(world:World,p:Player,patch:Partial<PlayerIdentityProfile>={}){const s=state(world),base=s.profiles.get(p.id)??profile(world,p),next={...base,...patch,physical:{...base.physical,...patch.physical},hidden:{...base.hidden,...patch.hidden},potential:{...base.potential,...patch.potential},positionFamiliarity:{...base.positionFamiliarity,...patch.positionFamiliarity}};s.profiles.set(p.id,next);return next}
export function playerProfile(world:World,id:string){const s=state(world),direct=s.profiles.get(id);return direct??ensurePlayerProfiles(world).profiles.get(id)}
export function setPlayerProfile(world:World,id:string,patch:Partial<PlayerIdentityProfile>){const s=state(world),cur=s.profiles.get(id)??ensurePlayerProfiles(world).profiles.get(id);if(!cur)return;const next={...cur,...patch,physical:{...cur.physical,...patch.physical},hidden:{...cur.hidden,...patch.hidden},potential:{...cur.potential,...patch.potential},positionFamiliarity:{...cur.positionFamiliarity,...patch.positionFamiliarity}};s.profiles.set(id,next);return next}
export function addEligibility(world:World,id:string,e:NationalEligibility){const p=playerProfile(world,id);if(!p)return;const existing=p.eligibility.find(x=>x.countryId===e.countryId);if(existing)Object.assign(existing,e);else p.eligibility.push({...e});if(e.eligible&&!p.nationalities.includes(e.countryId))p.nationalities.push(e.countryId);return p}
export function capTiePlayer(world:World,id:string,countryId:string,date:string){const p=playerProfile(world,id);if(!p)return false;for(const e of p.eligibility){if(e.countryId===countryId){e.capTied=true;e.seniorCaps++;e.lastRepresentedDate=date}else e.eligible=false}return true}
export function markPlayerRetired(world:World,id:string,date:string){const p=playerProfile(world,id);if(!p)return;p.retired=true;p.retiredDate=date;return p}
export function snapshotPlayerProfiles(world:World):PlayerProfileSnapshot{return{profiles:[...ensurePlayerProfiles(world).profiles.entries()].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}
export function restorePlayerProfiles(world:World,x:PlayerProfileSnapshot){states.set(world,{profiles:new Map(x.profiles.map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
