import type { Player, Position, World } from './engine';
import { technicalProfile, type DetailedPlayerAttributes } from './player-technical-profile-v2';

export type AttributeBudgetReport={playerId:string;position:Position;currentAbility:number;weightedAverage:number;expectedAverage:number;drift:number;severity:'ok'|'watch'|'correct';corrected:boolean};
const weightsByPosition:Record<Position,Partial<Record<keyof DetailedPlayerAttributes,number>>>={
GK:{goalkeeperReflexes:1.5,goalkeeperHandling:1.4,goalkeeperAerial:1.2,goalkeeperOneOnOne:1.2,goalkeeperKicking:.7,goalkeeperCommunication:.8,concentration:.7,decisions:.7},
RB:{acceleration:1,sprintSpeed:1,stamina:1,crossing:.9,standingTackle:.9,marking:.8,interceptions:.7,shortPassing:.7,workRate:.8},LB:{acceleration:1,sprintSpeed:1,stamina:1,crossing:.9,standingTackle:.9,marking:.8,interceptions:.7,shortPassing:.7,workRate:.8},
CB:{marking:1.2,interceptions:1.15,standingTackle:1.1,heading:1,strength:.9,jumping:.75,anticipation:.8,concentration:.8,decisions:.7},
DM:{interceptions:1.05,standingTackle:.95,marking:.8,shortPassing:.9,longPassing:.7,decisions:.85,anticipation:.8,workRate:.8,positioning:.01 as any},
CM:{shortPassing:1,longPassing:.8,vision:.9,firstTouch:.85,decisions:.9,workRate:.85,teamwork:.75,technique:.75,anticipation:.65},
AM:{vision:1,firstTouch:.95,technique:.95,shortPassing:.9,dribbling:.85,offBall:.8,finishing:.7,decisions:.85,composure:.75},
RW:{acceleration:1,sprintSpeed:1,dribbling:1,crossing:.85,firstTouch:.85,offBall:.8,finishing:.75,technique:.8,decisions:.65},LW:{acceleration:1,sprintSpeed:1,dribbling:1,crossing:.85,firstTouch:.85,offBall:.8,finishing:.75,technique:.8,decisions:.65},
ST:{finishing:1.2,offBall:1.05,firstTouch:.9,composure:.9,acceleration:.8,sprintSpeed:.75,heading:.7,anticipation:.8,decisions:.7}
};
const clamp=(v:number,a=1,b=99)=>Math.max(a,Math.min(b,v));
export function expectedDetailedAverage(ca:number){return 28+ca*.66}
export function evaluateAttributeBudget(world:World,p:Player):AttributeBudgetReport{const t=technicalProfile(world,p.id);if(!t)return{playerId:p.id,position:p.position,currentAbility:p.currentAbility,weightedAverage:p.currentAbility,expectedAverage:expectedDetailedAverage(p.currentAbility),drift:0,severity:'ok',corrected:false};const w=weightsByPosition[p.position],entries=Object.entries(w) as [keyof DetailedPlayerAttributes,number][],total=entries.reduce((s,[,x])=>s+x,0),avg=entries.reduce((s,[k,x])=>s+t.attributes[k]*x,0)/Math.max(.01,total),expected=expectedDetailedAverage(p.currentAbility),drift=avg-expected,severity=Math.abs(drift)>=8?'correct':Math.abs(drift)>=5?'watch':'ok';return{playerId:p.id,position:p.position,currentAbility:p.currentAbility,weightedAverage:Number(avg.toFixed(2)),expectedAverage:Number(expected.toFixed(2)),drift:Number(drift.toFixed(2)),severity,corrected:false}}
export function gentlyCorrectAttributeBudget(world:World,p:Player,maxStep=.9){const report=evaluateAttributeBudget(world,p),t=technicalProfile(world,p.id);if(!t||report.severity!=='correct')return report;const direction=report.drift>0?-1:1,step=Math.min(maxStep,Math.abs(report.drift)*.12),w=weightsByPosition[p.position];for(const [k,weight] of Object.entries(w) as [keyof DetailedPlayerAttributes,number][]){const change=direction*step*Math.min(1.2,.45+weight*.55);t.attributes[k]=Math.round(clamp(t.attributes[k]+change))}return{...evaluateAttributeBudget(world,p),corrected:true}}
export function populationBudgetAudit(world:World){const reports=[] as AttributeBudgetReport[];for(const c of world.clubs)for(const p of c.players)reports.push(evaluateAttributeBudget(world,p));const severe=reports.filter(x=>x.severity==='correct');return{ok:severe.length<=Math.max(2,reports.length*.04),players:reports.length,severe:severe.length,meanAbsDrift:Number((reports.reduce((s,x)=>s+Math.abs(x.drift),0)/Math.max(1,reports.length)).toFixed(2)),worst:[...reports].sort((a,b)=>Math.abs(b.drift)-Math.abs(a.drift)).slice(0,10)}}
