import type { Player, Position, World } from './engine';
import { deterministicRandom } from './world-core-v2';
import { playerProfile } from './player-profile-v2';

export type DetailedPlayerAttributes={
  acceleration:number;sprintSpeed:number;agility:number;balance:number;strength:number;jumping:number;
  firstTouch:number;dribbling:number;crossing:number;shortPassing:number;longPassing:number;technique:number;
  finishing:number;longShots:number;volleys:number;heading:number;penalties:number;freeKicks:number;
  vision:number;composure:number;anticipation:number;decisions:number;offBall:number;teamwork:number;workRate:number;
  marking:number;interceptions:number;standingTackle:number;slidingTackle:number;aggression:number;bravery:number;concentration:number;
  goalkeeperReflexes:number;goalkeeperHandling:number;goalkeeperAerial:number;goalkeeperOneOnOne:number;goalkeeperKicking:number;goalkeeperCommunication:number;
};
export type PositionFamiliarityState={position:Position;familiarity:number;trainingHours:number;matchMinutes:number;lastUsedSeason:number;natural:boolean};
export type PlayerTechnicalProfile={playerId:string;attributes:DetailedPlayerAttributes;positions:Record<Position,PositionFamiliarityState>;version:number};
export type TechnicalProfileSnapshot={profiles:[string,PlayerTechnicalProfile][]};

type State={profiles:Map<string,PlayerTechnicalProfile>};
const states=new WeakMap<World,State>();
const positions:Position[]=['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];
const clamp=(v:number,a=1,b=99)=>Math.max(a,Math.min(b,v));
const jitter=(world:World,p:Player,key:string,span=10)=>(deterministicRandom(world,'players',`${p.id}:detail:${key}`)-.5)*span;
const n=(world:World,p:Player,key:string,base:number,bias=0,span=10)=>Math.round(clamp(base+bias+jitter(world,p,key,span)));
function profileState(world:World){let s=states.get(world);if(!s){s={profiles:new Map()};states.set(world,s)}return s}
function buildDetailed(world:World,p:Player):DetailedPlayerAttributes{const a=p.attributes,prof=playerProfile(world,p.id),phys=prof?.physical,hidden=prof?.hidden,height=phys?.heightCm??180,weight=phys?.weightKg??75,bodyPower=clamp(50+(weight-72)*1.1+(height-180)*.25,20,90),mentalBase=(a.decisions+a.positioning)/2,tech=a.technique,pass=a.passing,def=(a.tackling+a.positioning)/2,gk=a.goalkeeping;return{
acceleration:n(world,p,'acceleration',a.pace,4),sprintSpeed:n(world,p,'sprintSpeed',a.pace,2),agility:n(world,p,'agility',a.pace*.58+tech*.42),balance:n(world,p,'balance',tech*.45+bodyPower*.3+a.pace*.25),strength:n(world,p,'strength',bodyPower*.62+a.stamina*.38),jumping:n(world,p,'jumping',bodyPower*.45+a.pace*.18+a.stamina*.18+(height-175)*1.1),
firstTouch:n(world,p,'firstTouch',tech*.66+a.decisions*.18+pass*.16),dribbling:n(world,p,'dribbling',tech*.62+a.pace*.23+a.decisions*.15),crossing:n(world,p,'crossing',pass*.58+tech*.27+a.decisions*.15,['RB','LB','RW','LW'].includes(p.position)?5:-2),shortPassing:n(world,p,'shortPassing',pass*.7+a.decisions*.18+tech*.12),longPassing:n(world,p,'longPassing',pass*.58+a.decisions*.22+tech*.2,['DM','CM','CB'].includes(p.position)?4:0),technique:n(world,p,'technique',tech),
finishing:n(world,p,'finishing',a.finishing),longShots:n(world,p,'longShots',a.finishing*.58+tech*.25+a.decisions*.17,['AM','CM','ST'].includes(p.position)?3:0),volleys:n(world,p,'volleys',a.finishing*.55+tech*.35+a.decisions*.1),heading:n(world,p,'heading',a.finishing*.24+def*.18+bodyPower*.28+(height-175)*1.05,['CB','ST'].includes(p.position)?8:0),penalties:n(world,p,'penalties',a.finishing*.5+tech*.25+(hidden?.pressure??55)*.25),freeKicks:n(world,p,'freeKicks',tech*.42+a.finishing*.25+pass*.2+(hidden?.pressure??55)*.13),
vision:n(world,p,'vision',pass*.46+a.decisions*.34+tech*.2,['CM','AM','DM'].includes(p.position)?5:0),composure:n(world,p,'composure',a.decisions*.52+(hidden?.pressure??55)*.3+(hidden?.temperament??55)*.18),anticipation:n(world,p,'anticipation',mentalBase*.65+(hidden?.consistency??55)*.2+(hidden?.bigMatches??55)*.15),decisions:n(world,p,'decisions',a.decisions),offBall:n(world,p,'offBall',a.positioning*.42+a.decisions*.31+a.pace*.15+a.finishing*.12,['ST','AM','RW','LW'].includes(p.position)?4:0),teamwork:n(world,p,'teamwork',a.decisions*.38+(hidden?.professionalism??55)*.28+(hidden?.loyalty??55)*.18+(hidden?.leadership??55)*.16),workRate:n(world,p,'workRate',a.stamina*.52+(hidden?.professionalism??55)*.34+(hidden?.ambition??55)*.14),
marking:n(world,p,'marking',def*.64+a.decisions*.2+a.stamina*.16,['CB','RB','LB','DM'].includes(p.position)?5:-3),interceptions:n(world,p,'interceptions',a.positioning*.44+a.tackling*.31+a.decisions*.25,['CB','DM'].includes(p.position)?5:0),standingTackle:n(world,p,'standingTackle',a.tackling*.72+a.positioning*.18+a.decisions*.1),slidingTackle:n(world,p,'slidingTackle',a.tackling*.62+a.pace*.18+(hidden?.temperament??55)*.16+(hidden?.pressure??55)*.04),aggression:n(world,p,'aggression',50+(hidden?.temperament??55)*.24+(hidden?.controversy??30)*.18+(hidden?.ambition??55)*.08),bravery:n(world,p,'bravery',50+(hidden?.pressure??55)*.28+(hidden?.leadership??55)*.18+(hidden?.professionalism??55)*.1),concentration:n(world,p,'concentration',a.decisions*.42+(hidden?.consistency??55)*.35+(hidden?.professionalism??55)*.23),
goalkeeperReflexes:n(world,p,'gkReflexes',gk*.72+a.pace*.12+a.decisions*.16,p.position==='GK'?6:-20),goalkeeperHandling:n(world,p,'gkHandling',gk*.72+a.technique*.12+a.decisions*.16,p.position==='GK'?5:-20),goalkeeperAerial:n(world,p,'gkAerial',gk*.58+bodyPower*.18+a.positioning*.24,p.position==='GK'?6:-20),goalkeeperOneOnOne:n(world,p,'gkOneOnOne',gk*.55+a.decisions*.25+a.pace*.12+(hidden?.pressure??55)*.08,p.position==='GK'?5:-20),goalkeeperKicking:n(world,p,'gkKicking',gk*.38+pass*.34+tech*.18+a.decisions*.1,p.position==='GK'?4:-20),goalkeeperCommunication:n(world,p,'gkCommunication',gk*.4+a.decisions*.25+(hidden?.leadership??55)*.25+(hidden?.pressure??55)*.1,p.position==='GK'?5:-20)
};}
function relatedPositions(primary:Position):Partial<Record<Position,number>>{const table:Record<Position,Partial<Record<Position,number>>>={GK:{GK:100},RB:{RB:100,LB:58,CB:54,DM:42},LB:{LB:100,RB:58,CB:54,DM:42},CB:{CB:100,RB:52,LB:52,DM:64},DM:{DM:100,CM:76,CB:62,AM:48},CM:{CM:100,DM:78,AM:74,RW:40,LW:40},AM:{AM:100,CM:76,RW:68,LW:68,ST:58},RW:{RW:100,LW:72,AM:66,ST:58},LW:{LW:100,RW:72,AM:66,ST:58},ST:{ST:100,AM:62,RW:52,LW:52}};return table[primary]}
function buildPositions(world:World,p:Player){const rel=relatedPositions(p.position),out={} as Record<Position,PositionFamiliarityState>;for(const pos of positions){const base=rel[pos]??(pos==='GK'||p.position==='GK'?2:18),noise=(deterministicRandom(world,'players',`${p.id}:familiarity:${pos}`)-.5)*8,fam=Math.round(clamp(base+noise,1,100));out[pos]={position:pos,familiarity:fam,trainingHours:0,matchMinutes:0,lastUsedSeason:world.season,natural:pos===p.position}}return out}
function createTechnical(world:World,p:Player):PlayerTechnicalProfile{return{playerId:p.id,attributes:buildDetailed(world,p),positions:buildPositions(world,p),version:1}}
export function ensureTechnicalProfiles(world:World){const s=profileState(world);for(const c of world.clubs)for(const p of c.players)if(!s.profiles.has(p.id))s.profiles.set(p.id,createTechnical(world,p));return s}
export function technicalProfile(world:World,id:string){return ensureTechnicalProfiles(world).profiles.get(id)}
export function registerTechnicalProfile(world:World,p:Player){const s=profileState(world),existing=s.profiles.get(p.id);if(existing)return existing;const t=createTechnical(world,p);s.profiles.set(p.id,t);return t}
export function refreshTechnicalFromLegacy(world:World,p:Player,blend=.45){const t=registerTechnicalProfile(world,p),fresh=buildDetailed(world,p);for(const key of Object.keys(t.attributes) as (keyof DetailedPlayerAttributes)[]){t.attributes[key]=Math.round(clamp(t.attributes[key]*(1-blend)+fresh[key]*blend,1,99))}t.version++;return t}
export function detailedAttribute(world:World,id:string,key:keyof DetailedPlayerAttributes,fallback=50){return technicalProfile(world,id)?.attributes[key]??fallback}
export function positionFamiliarity(world:World,id:string,pos:Position){return technicalProfile(world,id)?.positions[pos]?.familiarity??1}
export function effectiveAbilityAtPosition(world:World,p:Player,pos:Position){const fam=positionFamiliarity(world,p.id,pos),penalty=fam>=90?1:fam>=75?.97:fam>=60?.92:fam>=45?.84:fam>=30?.73:.58;return Number((p.currentAbility*penalty).toFixed(1))}
export function trainPosition(world:World,p:Player,pos:Position,hours:number,coachQuality=60){const t=registerTechnicalProfile(world,p),slot=t.positions[pos],natural=slot.natural,adaptability=playerProfile(world,p.id)?.hidden.adaptability??50,difficulty=natural?.15:pos==='GK'||p.position==='GK'?1.8:1,gain=Math.max(0,hours/24*(.45+coachQuality/160)*(.55+adaptability/140)/difficulty*(1-slot.familiarity/112));slot.trainingHours+=hours;slot.familiarity=Math.round(clamp(slot.familiarity+gain,1,100));return slot}
export function recordPositionMinutes(world:World,p:Player,pos:Position,minutes:number){const t=registerTechnicalProfile(world,p),slot=t.positions[pos],adaptability=playerProfile(world,p.id)?.hidden.adaptability??50,gain=Math.max(0,minutes/900*(1.1+adaptability/125)*(1-slot.familiarity/108));slot.matchMinutes+=minutes;slot.lastUsedSeason=world.season;slot.familiarity=Math.round(clamp(slot.familiarity+gain,1,100));return slot}
export function decayUnusedPositionFamiliarity(world:World,p:Player){const t=registerTechnicalProfile(world,p);for(const slot of Object.values(t.positions)){if(slot.natural)continue;const seasonsIdle=Math.max(0,world.season-slot.lastUsedSeason-1);if(seasonsIdle>0)slot.familiarity=Math.round(clamp(slot.familiarity-Math.min(8,seasonsIdle*1.6),1,100))}return t}
export function snapshotTechnicalProfiles(world:World):TechnicalProfileSnapshot{return{profiles:[...ensureTechnicalProfiles(world).profiles.entries()].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}
export function restoreTechnicalProfiles(world:World,x:TechnicalProfileSnapshot){states.set(world,{profiles:new Map(x.profiles.map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]))})}
