import type { Player, PlayerAttributes, Position, World } from './engine';
import { addEligibility, registerPlayerProfile } from './player-profile-v2';
import { potentialTierFor } from './player-potential-tier-v1';
import { queueWorldEvent, worldCore } from './world-core-v2';
import type { PersonProvenance } from './real-world-person-import-v1';
import { movePlayerCanonical } from './player-roster-integrity-v1';

export type RealPlayerPublicStats={minutes?:number;goals?:number;assists?:number;caps?:number;internationalGoals?:number;yellowCards?:number;redCards?:number;saves?:number;cleanSheets?:number};
export type RealPlayerAttributeHints=Partial<PlayerAttributes>&{preferredFoot?:'left'|'right';weakFoot?:number;paceEvidence?:number;technicalEvidence?:number;defensiveEvidence?:number;goalkeepingEvidence?:number};
export type RealPlayerSeedV2={externalIds?:Record<string,string>;name:string;dateOfBirth?:string;age?:number;heightCm?:number;position:Position;secondaryPositions?:Position[];nationalityCountryIds:string[];birthCountryId?:string;clubId?:string;nationalTeamId?:string;shirtNumber?:number;captain?:boolean;marketValue?:number;currentAbility?:number;potentialAbility?:number;stats?:RealPlayerPublicStats;attributeHints?:RealPlayerAttributeHints;provenance:PersonProvenance[]};
export type RealPlayerFieldEvidence={estimated:boolean;confidence:number;basis:'public-source'|'derived-from-public-data'|'engine-default'};
export type RealPlayerRecordV2={id:string;player:Player;realWorld:true;identityKey:string;bioIdentityKey:string;aliases:string[];externalIds:Record<string,string>;provenance:PersonProvenance[];dateOfBirth?:string;heightCm?:number;secondaryPositions:Position[];nationalTeamId?:string;shirtNumber?:number;captain:boolean;marketValue?:number;stats:RealPlayerPublicStats;preferredFoot:'left'|'right';weakFoot:number;potentialLabel:ReturnType<typeof potentialTierFor>;fieldEvidence:Record<string,RealPlayerFieldEvidence>;estimatedFields:string[]};
export type RealPlayerImportReport={inserted:number;merged:number;duplicatesPrevented:number;conflicts:Array<{identityKey:string;field:string;kept:any;discarded:any}>};
const states=new WeakMap<World,Map<string,RealPlayerRecordV2>>();const aliases=new WeakMap<World,Map<string,string>>();
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const slug=(s:string)=>norm(s).replace(/ /g,'-');
function store(w:World){let s=states.get(w);if(!s){s=new Map();states.set(w,s)}return s}function aliasStore(w:World){let s=aliases.get(w);if(!s){s=new Map();aliases.set(w,s)}return s}
function ageAt(dob?:string,fallback=24){if(!dob)return fallback;const d=new Date(`${dob}T12:00:00Z`),c=new Date('2026-08-25T12:00:00Z');let a=c.getUTCFullYear()-d.getUTCFullYear();if(c.getUTCMonth()<d.getUTCMonth()||(c.getUTCMonth()===d.getUTCMonth()&&c.getUTCDate()<d.getUTCDate()))a--;return Math.max(14,a)}
function bioIdentity(seed:RealPlayerSeedV2){return`bio:${norm(seed.name)}:${seed.dateOfBirth??seed.age??'u'}:${seed.nationalityCountryIds.slice().sort().join(',')}`}
function externalIdentity(seed:RealPlayerSeedV2){const ids=Object.entries(seed.externalIds??{}).filter(([,v])=>!!v).sort().map(([k,v])=>`${k}:${v}`).join('|');return ids?`ext:${ids}`:undefined}
function identity(seed:RealPlayerSeedV2){return externalIdentity(seed)??bioIdentity(seed)}
function externalAliases(seed:RealPlayerSeedV2){return Object.entries(seed.externalIds??{}).flatMap(([k,v])=>v?[`external:${k}:${v}`,`external-value:${v}`]:[])}
function sourceConfidence(seed:RealPlayerSeedV2){return Math.max(20,...seed.provenance.map(p=>p.confidence??50))}
function inferCA(seed:RealPlayerSeedV2){if(seed.currentAbility!==undefined)return clamp(seed.currentAbility,20,96);const age=seed.age??ageAt(seed.dateOfBirth),s=seed.stats??{},market=seed.marketValue??0;let ca=48;ca+=Math.min(14,Math.log10(Math.max(1,market/100000+1))*5);ca+=Math.min(10,(s.minutes??0)/450);ca+=Math.min(6,(s.caps??0)/15);if(seed.captain)ca+=3;if(age<=21)ca-=2;return Math.round(clamp(ca,30,92))}
function inferPA(seed:RealPlayerSeedV2,ca:number){if(seed.potentialAbility!==undefined)return Math.round(clamp(seed.potentialAbility,ca,99));const age=seed.age??ageAt(seed.dateOfBirth);const ageUpside=age<=17?24:age<=19?18:age<=21?12:age<=23?7:3;return Math.round(clamp(ca+ageUpside,ca,98))}
function attrs(seed:RealPlayerSeedV2,ca:number):PlayerAttributes{const h=seed.attributeHints??{},p=seed.position,s=seed.stats??{},a=(x:number)=>Math.round(clamp(x,15,97));const pace=a(h.pace??ca+(['RB','LB','RW','LW'].includes(p)?6:0)+(h.paceEvidence??0));const passing=a(h.passing??ca+(['DM','CM','AM'].includes(p)?6:-2)+(h.technicalEvidence??0)*.35);const technique=a(h.technique??ca+(['AM','RW','LW','ST'].includes(p)?5:0)+(h.technicalEvidence??0)*.55);const finishing=a(h.finishing??ca+(p==='ST'?9:['RW','LW','AM'].includes(p)?4:-8)+Math.min(5,(s.goals??0)/6));const tackling=a(h.tackling??ca+(['CB','RB','LB','DM'].includes(p)?8:-10)+(h.defensiveEvidence??0)*.6);const positioning=a(h.positioning??ca+(['GK','CB','DM'].includes(p)?6:1));const stamina=a(h.stamina??ca+(['RB','LB','DM','CM'].includes(p)?5:0)+Math.min(4,(s.minutes??0)/1000));const decisions=a(h.decisions??ca+(seed.captain?3:0));const goalkeeping=a(h.goalkeeping??(p==='GK'?ca+10+(h.goalkeepingEvidence??0)*.6+Math.min(5,(s.saves??0)/30):15));return{pace,passing,technique,finishing,tackling,positioning,stamina,decisions,goalkeeping}}
function mergeProvenance(a:PersonProvenance[],b:PersonProvenance[]){const m=new Map<string,PersonProvenance>();for(const p of [...a,...b]){const k=`${p.source}:${p.sourceId??''}:${p.snapshotDate}`;const cur=m.get(k);if(!cur||(p.confidence??0)>(cur.confidence??0))m.set(k,p)}return[...m.values()]}
function evidence(seed:RealPlayerSeedV2,confidence:number){const out:Record<string,RealPlayerFieldEvidence>={},estimated:string[]=[];const publicField=(name:string,present:boolean)=>{out[name]={estimated:!present,confidence:present?confidence:Math.min(55,Math.round(confidence*.62)),basis:present?'public-source':'derived-from-public-data'};if(!present)estimated.push(name)};publicField('currentAbility',seed.currentAbility!==undefined);publicField('potentialAbility',seed.potentialAbility!==undefined);for(const k of ['pace','passing','technique','finishing','tackling','positioning','stamina','decisions','goalkeeping'] as (keyof PlayerAttributes)[])publicField(`attributes.${k}`,seed.attributeHints?.[k]!==undefined);publicField('preferredFoot',seed.attributeHints?.preferredFoot!==undefined);publicField('weakFoot',seed.attributeHints?.weakFoot!==undefined);return{fieldEvidence:out,estimatedFields:estimated}}
function registerAliases(w:World,rec:RealPlayerRecordV2,seed?:RealPlayerSeedV2){const a=aliasStore(w);a.set(rec.identityKey,rec.id);a.set(rec.bioIdentityKey,rec.id);for(const [k,v] of Object.entries(rec.externalIds))if(v){a.set(`external:${k}:${v}`,rec.id);a.set(`external-value:${v}`,rec.id)}if(seed)for(const k of externalAliases(seed))a.set(k,rec.id)}
function findExisting(w:World,seed:RealPlayerSeedV2){const s=store(w),a=aliasStore(w),keys=[identity(seed),bioIdentity(seed),...externalAliases(seed)];for(const k of keys){const id=a.get(k);if(id&&s.has(id))return s.get(id)}const bio=bioIdentity(seed);return[...s.values()].find(x=>x.bioIdentityKey===bio||Object.entries(seed.externalIds??{}).some(([k,v])=>!!v&&(x.externalIds[k]===v||Object.values(x.externalIds).includes(v))))}
function ensureClubPlayer(w:World,p:Player){if(!p.clubId||p.clubId==='unattached')return;const club=w.clubs.find(c=>c.id===p.clubId);if(!club)return;if(!club.players.some(x=>x.id===p.id))club.players.push(p)}
export function importRealPlayerV2(w:World,seed:RealPlayerSeedV2,report?:RealPlayerImportReport){const key=identity(seed),s=store(w),existing=findExisting(w,seed),confidence=sourceConfidence(seed);if(existing){const previousConfidence=Math.max(20,...existing.provenance.map(p=>p.confidence??50));existing.provenance=mergeProvenance(existing.provenance,seed.provenance);existing.aliases=[...new Set([...existing.aliases,seed.name])];existing.externalIds={...existing.externalIds,...(seed.externalIds??{})};if(seed.marketValue!==undefined&&(existing.marketValue===undefined||confidence>=previousConfidence))existing.marketValue=seed.marketValue;existing.stats={...existing.stats,...seed.stats};if(seed.dateOfBirth&&!existing.dateOfBirth)existing.dateOfBirth=seed.dateOfBirth;if(seed.heightCm&&!existing.heightCm)existing.heightCm=seed.heightCm;if(seed.secondaryPositions?.length)existing.secondaryPositions=[...new Set([...existing.secondaryPositions,...seed.secondaryPositions])];if(seed.clubId&&seed.clubId!==existing.player.clubId&&confidence>=previousConfidence){report?.conflicts.push({identityKey:key,field:'clubId',kept:seed.clubId,discarded:existing.player.clubId});movePlayerCanonical(w,existing.player,seed.clubId)}const ev=evidence(seed,confidence);for(const [field,value] of Object.entries(ev.fieldEvidence)){const cur=existing.fieldEvidence?.[field];if(!cur||value.confidence>=cur.confidence)(existing.fieldEvidence??={})[field]=value}existing.estimatedFields=[...new Set(Object.entries(existing.fieldEvidence??{}).filter(([,v])=>v.estimated).map(([k])=>k))];registerAliases(w,existing,seed);report&&(report.merged++,report.duplicatesPrevented++);return existing}
 const ca=inferCA(seed),pa=inferPA(seed,ca),id=`real26-${slug(seed.name)}-${seed.dateOfBirth?.replaceAll('-','')??seed.age??'u'}-${Math.abs(hash(bioIdentity(seed))).toString(36)}`,age=seed.age??ageAt(seed.dateOfBirth),player:Player={id,clubId:seed.clubId??'unattached',name:seed.name,position:seed.position,age,currentAbility:ca,potentialAbility:pa,condition:100,morale:75,attributes:attrs(seed,ca)},best=seed.provenance.slice().sort((a,b)=>(b.confidence??0)-(a.confidence??0))[0],potentialCertainty=seed.potentialAbility!==undefined?(best?.confidence??65):Math.min(45,Math.round((best?.confidence??65)*.62));registerPlayerProfile(w,player,{createdBy:'real',birthCountryId:seed.birthCountryId??seed.nationalityCountryIds[0],nationalities:[...seed.nationalityCountryIds],citizenships:[...seed.nationalityCountryIds],potential:{floor:ca,ceiling:pa,projection:pa,certainty:potentialCertainty,lateBloomer:age<21?32:18,developmentVolatility:age<21?34:18}});for(const c of seed.nationalityCountryIds)addEligibility(w,id,{countryId:c,basis:c===seed.birthCountryId?'birth':'citizenship',eligible:true,capTied:false,seniorCaps:0,youthCaps:0});const ev=evidence(seed,sourceConfidence(seed)),rec:RealPlayerRecordV2={id,player,realWorld:true,identityKey:key,bioIdentityKey:bioIdentity(seed),aliases:[seed.name],externalIds:{...(seed.externalIds??{})},provenance:mergeProvenance([],seed.provenance),dateOfBirth:seed.dateOfBirth,heightCm:seed.heightCm,secondaryPositions:[...(seed.secondaryPositions??[])],nationalTeamId:seed.nationalTeamId,shirtNumber:seed.shirtNumber,captain:!!seed.captain,marketValue:seed.marketValue,stats:{...(seed.stats??{})},preferredFoot:seed.attributeHints?.preferredFoot??'right',weakFoot:seed.attributeHints?.weakFoot??50,potentialLabel:potentialTierFor({potential:pa,position:seed.position,certainty:potentialCertainty,age}),fieldEvidence:ev.fieldEvidence,estimatedFields:ev.estimatedFields};s.set(id,rec);registerAliases(w,rec,seed);ensureClubPlayer(w,player);queueWorldEvent(w,{date:worldCore(w).date,type:'RealPlayerImported',scope:'person',entityIds:[id,player.clubId],importance:1,payload:{identityKey:key,bioIdentityKey:rec.bioIdentityKey,potentialTier:rec.potentialLabel.tier,source:best?.source,estimatedFields:rec.estimatedFields}});report&&report.inserted++;return rec}
function hash(s:string){let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
export function importRealPlayerBatchV2(w:World,seeds:RealPlayerSeedV2[]){const report:RealPlayerImportReport={inserted:0,merged:0,duplicatesPrevented:0,conflicts:[]};const rows=seeds.map(s=>importRealPlayerV2(w,s,report));return{rows,report}}
export function realPlayersV2(w:World){return[...store(w).values()]}
export function realPlayerByIdV2(w:World,id:string){return store(w).get(id)}
export function snapshotRealPlayersV2(w:World){return{players:[...store(w)].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))] as [string,RealPlayerRecordV2]),aliases:[...aliasStore(w)]}}
export function restoreRealPlayersV2(w:World,x?:ReturnType<typeof snapshotRealPlayersV2>){states.set(w,new Map((x?.players??[]).map(([k,v])=>{const rec=JSON.parse(JSON.stringify(v)) as RealPlayerRecordV2;rec.bioIdentityKey??=`bio:${norm(rec.player.name)}:${rec.dateOfBirth??rec.player.age??'u'}:${''}`;rec.fieldEvidence??={};rec.estimatedFields??=[];return[k,rec]})));aliases.set(w,new Map(x?.aliases??[]));for(const rec of store(w).values()){registerAliases(w,rec);ensureClubPlayer(w,rec.player)}}
