import type { Player, Position, World } from './engine';
import { registerPlayerProfile, addEligibility } from './player-profile-v2';

export type PublicDataSource='openfootball-players'|'world-cup-player-tracker-2026'|'worldcup2026-fifa-snapshot'|'manual-public-fact';
export type PersonProvenance={source:PublicDataSource;sourceId?:string;snapshotDate:string;license:'CC0'|'public-fact-reference'|'unknown';confidence:number;url?:string};
export type RealPlayerSeed={id?:string;name:string;dateOfBirth?:string;age?:number;heightCm?:number;position:Position;secondaryPositions?:Position[];nationalityCountryIds:string[];birthCountryId?:string;clubId?:string;nationalTeamId?:string;shirtNumber?:number;captain?:boolean;currentAbility?:number;potentialAbility?:number;provenance:PersonProvenance[]};
export type ImportedRealPlayer={player:Player;provenance:PersonProvenance[];realWorld:true;dateOfBirth?:string;heightCm?:number;secondaryPositions:Position[];nationalTeamId?:string;shirtNumber?:number;captain:boolean};
const imports=new WeakMap<World,Map<string,ImportedRealPlayer>>();
const clamp=(n:number,a=0,b=100)=>Math.max(a,Math.min(b,n));
const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function store(w:World){let m=imports.get(w);if(!m){m=new Map();imports.set(w,m)}return m}
function ageAtCutoff(dob?:string,fallback=24){if(!dob)return fallback;const d=new Date(`${dob}T12:00:00Z`),cut=new Date('2026-08-25T12:00:00Z');let a=cut.getUTCFullYear()-d.getUTCFullYear();if(cut.getUTCMonth()<d.getUTCMonth()||(cut.getUTCMonth()===d.getUTCMonth()&&cut.getUTCDate()<d.getUTCDate()))a--;return Math.max(14,a)}
function defaultAttrs(pos:Position,ca:number){const a=(v:number)=>Math.round(clamp(v,15,95));return{pace:a(ca+(['RB','LB','RW','LW'].includes(pos)?6:0)),passing:a(ca+(['DM','CM','AM'].includes(pos)?6:-2)),technique:a(ca+(['AM','RW','LW','ST'].includes(pos)?5:0)),finishing:a(ca+(pos==='ST'?9:['RW','LW','AM'].includes(pos)?4:-8)),tackling:a(ca+(['CB','RB','LB','DM'].includes(pos)?8:-10)),positioning:a(ca+(['GK','CB','DM'].includes(pos)?6:1)),stamina:a(ca+(['RB','LB','DM','CM'].includes(pos)?5:0)),decisions:a(ca),goalkeeping:a(pos==='GK'?ca+10:15)} }
export function importRealPlayer(w:World,seed:RealPlayerSeed){const best=[...seed.provenance].sort((a,b)=>b.confidence-a.confidence)[0];const id=seed.id??`real-2026-${best?.sourceId?slug(best.sourceId):slug(seed.name)}-${seed.dateOfBirth?.slice(0,4)??seed.age??'u'}`;const existing=store(w).get(id);if(existing)return existing;const ca=Math.round(clamp(seed.currentAbility??55,20,94)),pa=Math.round(clamp(seed.potentialAbility??Math.max(ca,ca+(seed.age??ageAtCutoff(seed.dateOfBirth))<22?12:3),ca,98));const p:Player={id,clubId:seed.clubId??'unattached',name:seed.name,position:seed.position,age:seed.age??ageAtCutoff(seed.dateOfBirth),currentAbility:ca,potentialAbility:pa,condition:100,morale:75,attributes:defaultAttrs(seed.position,ca)};registerPlayerProfile(w,p,{createdBy:'real',birthCountryId:seed.birthCountryId??seed.nationalityCountryIds[0],nationalities:[...seed.nationalityCountryIds],citizenships:[...seed.nationalityCountryIds],potential:{floor:ca,ceiling:pa,projection:pa,certainty:best?.confidence??65,lateBloomer:20,developmentVolatility:25}});for(const countryId of seed.nationalityCountryIds)addEligibility(w,p.id,{countryId,basis:countryId===seed.birthCountryId?'birth':'citizenship',eligible:true,capTied:false,seniorCaps:0,youthCaps:0});const row:ImportedRealPlayer={player:p,provenance:[...seed.provenance],realWorld:true,dateOfBirth:seed.dateOfBirth,heightCm:seed.heightCm,secondaryPositions:[...(seed.secondaryPositions??[])],nationalTeamId:seed.nationalTeamId,shirtNumber:seed.shirtNumber,captain:!!seed.captain};store(w).set(id,row);return row}
export function importedRealPlayers(w:World){return[...store(w).values()]}
export function snapshotRealWorldPeople(w:World){return{players:[...store(w)].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])}}
export function restoreRealWorldPeople(w:World,x:{players:[string,ImportedRealPlayer][]}){imports.set(w,new Map((x?.players??[]).map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])))}
