import type { World } from './engine';
import { technicalStaffState, type TechnicalStaffMember, type TechnicalStaffRole } from './technical-staff';
import type { PersonProvenance } from './real-world-person-import-v1';
import { queueWorldEvent, worldCore } from './world-core-v2';
import type { SourceAssignmentResolution } from './real-world-player-import-v2';

export type RealStaffRole='headCoach'|'assistantManager'|'deputyManager'|'technicalAssistant'|'firstTeamCoach'|'goalkeepingCoach'|'fitnessCoach'|'performanceAnalyst'|'chiefScout'|'physiotherapist'|'clubDoctor'|'nutritionist'|'sportsPsychologist'|'youthCoach'|'footballCoordinator'|'technicalDirector'|'other';
export type RealStaffSourceAssignment={clubId?:string;nationalTeamId?:string;clubResolution?:SourceAssignmentResolution;nationalTeamResolution?:SourceAssignmentResolution};
export type RealStaffSeed={externalIds?:Record<string,string>;name:string;dateOfBirth?:string;age?:number;nationality?:string;role:RealStaffRole;clubId?:string;nationalTeamId?:string;sourceAssignment?:RealStaffSourceAssignment;reputation?:number;attributes?:Partial<{coaching:number;tactics:number;technical:number;physical:number;goalkeeping:number;analysis:number;medical:number;rehab:number;nutrition:number;psychology:number;youth:number;recruitment:number;manManagement:number;coordination:number;communication:number;data:number}>;provenance:PersonProvenance[]};
export type RealStaffRecord={id:string;identityKey:string;bioIdentityKey:string;seed:RealStaffSeed;technicalStaffId?:string;realWorld:true;estimatedFields:string[]};
const states=new WeakMap<World,Map<string,RealStaffRecord>>(),keys=new WeakMap<World,Map<string,string>>();
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function state(w:World){let s=states.get(w);if(!s){s=new Map();states.set(w,s)}return s}function keyState(w:World){let s=keys.get(w);if(!s){s=new Map();keys.set(w,s)}return s}
function bioIdentity(s:RealStaffSeed){return`bio:${norm(s.name)}:${s.dateOfBirth??s.age??'u'}:${norm(s.nationality??'')}`}
function externalIdentity(s:RealStaffSeed){const ext=Object.entries(s.externalIds??{}).filter(([,v])=>!!v).sort().map(([k,v])=>`${k}:${v}`).join('|');return ext?`ext:${ext}`:undefined}
function identity(s:RealStaffSeed){return externalIdentity(s)??bioIdentity(s)}
function externalKeys(s:RealStaffSeed){return Object.entries(s.externalIds??{}).flatMap(([k,v])=>v?[`external:${k}:${v}`,`external-value:${v}`]:[])}
function mergeProvenance(a:PersonProvenance[],b:PersonProvenance[]){const m=new Map<string,PersonProvenance>();for(const p of [...a,...b]){const k=`${p.source}:${p.sourceId??''}:${p.snapshotDate}`;const cur=m.get(k);if(!cur||(p.confidence??0)>(cur.confidence??0))m.set(k,p)}return[...m.values()]}
function registerKeys(w:World,rec:RealStaffRecord){const ks=keyState(w);ks.set(rec.identityKey,rec.id);ks.set(rec.bioIdentityKey,rec.id);for(const [k,v] of Object.entries(rec.seed.externalIds??{}))if(v){ks.set(`external:${k}:${v}`,rec.id);ks.set(`external-value:${v}`,rec.id)}}
function findExisting(w:World,seed:RealStaffSeed){const st=state(w),ks=keyState(w);for(const k of [identity(seed),bioIdentity(seed),...externalKeys(seed)]){const id=ks.get(k);if(id&&st.has(id))return st.get(id)}const bio=bioIdentity(seed);return[...st.values()].find(r=>r.bioIdentityKey===bio||Object.entries(seed.externalIds??{}).some(([k,v])=>!!v&&(r.seed.externalIds?.[k]===v||Object.values(r.seed.externalIds??{}).includes(v))))}
const roleMap:Partial<Record<RealStaffRole,TechnicalStaffRole>>={assistantManager:'assistantManager',deputyManager:'deputyManager',technicalAssistant:'technicalAssistant',firstTeamCoach:'firstTeamCoach',goalkeepingCoach:'goalkeepingCoach',fitnessCoach:'fitnessCoach',performanceAnalyst:'performanceAnalyst',chiefScout:'chiefScout',physiotherapist:'physiotherapist',clubDoctor:'clubDoctor',nutritionist:'nutritionist',sportsPsychologist:'sportsPsychologist',youthCoach:'youthCoach',footballCoordinator:'footballCoordinator'};
function ageOf(seed:RealStaffSeed){if(seed.age)return seed.age;if(seed.dateOfBirth)return Math.max(20,2026-Number(seed.dateOfBirth.slice(0,4)));return 45}
function estimatedFields(seed:RealStaffSeed){const out:string[]=[];if(seed.reputation===undefined)out.push('reputation');for(const k of ['coaching','tactics','technical','physical','goalkeeping','analysis','medical','rehab','nutrition','psychology','youth','recruitment','manManagement','coordination','communication','data'] as const)if(seed.attributes?.[k]===undefined)out.push(`attributes.${k}`);return out}
function createTechnical(w:World,id:string,seed:RealStaffSeed,role:TechnicalStaffRole):TechnicalStaffMember|undefined{if(!seed.clubId)return;const st=technicalStaffState(w),club=w.clubs.find(c=>c.id===seed.clubId);if(!club)return;const base=Math.max(35,Math.min(95,seed.reputation??Math.round(45+club.reputation*.35))),a=seed.attributes??{},skill=(k:keyof NonNullable<RealStaffSeed['attributes']>,bonus=0)=>Math.round(Math.max(20,Math.min(96,(a[k]??base)+bonus)));const m:TechnicalStaffMember={id:`realstaff-${id}`,clubId:seed.clubId,name:seed.name,age:ageOf(seed),nationality:seed.nationality??'Desconhecida',role,reputation:base,skills:{coaching:skill('coaching'),tactics:skill('tactics'),technical:skill('technical'),physical:skill('physical'),goalkeeping:skill('goalkeeping'),setPieces:skill('tactics',-5),analysis:skill('analysis'),medical:skill('medical'),rehab:skill('rehab'),nutrition:skill('nutrition'),psychology:skill('psychology'),youth:skill('youth'),recruitment:skill('recruitment'),manManagement:skill('manManagement'),coordination:skill('coordination'),communication:skill('communication'),data:skill('data')},personality:{discipline:58,empathy:58,ambition:60,loyalty:55,ego:38,adaptability:60,communication:skill('communication'),conflictTolerance:58},philosophy:{clubIdentity:55,youthPathway:skill('youth'),dataOrientation:skill('data'),playerCare:60,performanceFirst:65,tacticalRigidity:50,collectiveWork:65},salaryWeekly:Math.round(900+base*35),contractEnd:`${w.season+2}-06-30`,managerLoyalty:50,clubLoyalty:55,managerCompatibility:60,clubPhilosophyFit:60,squadAffinity:60,playerAffinities:{},staffHarmony:62,workload:40,fatigue:12,stress:15,jobSatisfaction:68,ambitionToLead:role==='assistantManager'||role==='deputyManager'?58:25,careerPotential:Math.min(95,base+8),experience:Math.min(95,Math.max(10,(ageOf(seed)-25)*2)),qualifications:Math.min(95,base+5),status:'active',history:[{date:worldCore(w).date,type:'realImport',summary:'Importado da base pública 2026.',impact:0}]};st.members.set(m.id,m);const ids=st.clubStaff.get(seed.clubId)??[],synthetic=ids.map(x=>st.members.get(x)).find(x=>x?.role===role&&x.id.startsWith('staff-'));if(synthetic){synthetic.status='freeAgent';st.clubStaff.set(seed.clubId,ids.filter(x=>x!==synthetic.id))}const current=st.clubStaff.get(seed.clubId)??[];if(!current.includes(m.id))st.clubStaff.set(seed.clubId,[...current,m.id]);return m}
function moveTechnical(w:World,rec:RealStaffRecord,toClubId:string){if(!rec.technicalStaffId)return;const st=technicalStaffState(w),member=st.members.get(rec.technicalStaffId);if(!member)return;for(const [clubId,ids] of st.clubStaff)if(ids.includes(member.id))st.clubStaff.set(clubId,ids.filter(x=>x!==member.id));member.clubId=toClubId;member.status='active';const next=st.clubStaff.get(toClubId)??[];if(!next.includes(member.id))st.clubStaff.set(toClubId,[...next,member.id])}
export function importRealStaff(w:World,seed:RealStaffSeed){const ik=identity(seed),existing=findExisting(w,seed);if(existing){const previousConfidence=Math.max(20,...existing.seed.provenance.map(p=>p.confidence??50)),incomingConfidence=Math.max(20,...seed.provenance.map(p=>p.confidence??50));existing.seed.provenance=mergeProvenance(existing.seed.provenance,seed.provenance);existing.seed.externalIds={...existing.seed.externalIds,...seed.externalIds};if(seed.sourceAssignment)existing.seed.sourceAssignment={...(existing.seed.sourceAssignment??{}),...seed.sourceAssignment};if(seed.dateOfBirth&&!existing.seed.dateOfBirth)existing.seed.dateOfBirth=seed.dateOfBirth;if(seed.age&&!existing.seed.age)existing.seed.age=seed.age;if(seed.nationality&&!existing.seed.nationality)existing.seed.nationality=seed.nationality;if(seed.attributes)existing.seed.attributes={...existing.seed.attributes,...seed.attributes};if(seed.reputation!==undefined&&incomingConfidence>=previousConfidence)existing.seed.reputation=seed.reputation;if(seed.clubId&&seed.clubId!==existing.seed.clubId&&incomingConfidence>=previousConfidence){existing.seed.clubId=seed.clubId;moveTechnical(w,existing,seed.clubId)}existing.estimatedFields=estimatedFields(existing.seed);registerKeys(w,existing);return{record:existing,merged:true}}const id=`rs-${Math.abs([...bioIdentity(seed)].reduce((h,c)=>Math.imul(h^c.charCodeAt(0),16777619),2166136261)>>>0).toString(36)}`,rec:RealStaffRecord={id,identityKey:ik,bioIdentityKey:bioIdentity(seed),seed:{...seed,sourceAssignment:seed.sourceAssignment?{...seed.sourceAssignment}:undefined,externalIds:{...(seed.externalIds??{})},provenance:mergeProvenance([],seed.provenance)},realWorld:true,estimatedFields:estimatedFields(seed)};const mapped=roleMap[seed.role];if(mapped&&seed.clubId)rec.technicalStaffId=createTechnical(w,id,seed,mapped)?.id;state(w).set(id,rec);registerKeys(w,rec);queueWorldEvent(w,{date:worldCore(w).date,type:'RealStaffImported',scope:'person',entityIds:[id,seed.clubId??seed.nationalTeamId??''],importance:1,payload:{name:seed.name,role:seed.role,estimatedFields:rec.estimatedFields,sourceAssignment:rec.seed.sourceAssignment}});return{record:rec,merged:false}}
export function importRealStaffBatch(w:World,seeds:RealStaffSeed[]){let inserted=0,merged=0;const rows=seeds.map(s=>{const r=importRealStaff(w,s);r.merged?merged++:inserted++;return r.record});return{rows,inserted,merged}}
export function realStaff(w:World){return[...state(w).values()]}
export function snapshotRealStaff(w:World){return{records:[...state(w)].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))] as [string,RealStaffRecord]),keys:[...keyState(w)]}}
export function restoreRealStaff(w:World,x?:ReturnType<typeof snapshotRealStaff>){states.set(w,new Map((x?.records??[]).map(([k,v])=>{const rec=JSON.parse(JSON.stringify(v)) as RealStaffRecord;rec.bioIdentityKey??=bioIdentity(rec.seed);rec.estimatedFields??=estimatedFields(rec.seed);return[k,rec]})));keys.set(w,new Map(x?.keys??[]));for(const rec of state(w).values())registerKeys(w,rec)}
