import type { World } from './engine';
import { importRealPlayerBatchV2, type RealPlayerSeedV2, type SourceAssignmentResolution } from './real-world-player-import-v2';
import { importRealStaffBatch, type RealStaffSeed } from './real-world-staff-import-v1';
import { dedupePlayerRosters } from './player-roster-integrity-v1';
import { medicalState } from './injuries';
import { queueWorldEvent, worldCore } from './world-core-v2';
import { footballDataSnapshot, resolveFootballEntity } from './world-football-data-v1';
import { fetchOpenFootballPeople2026 } from './openfootball-people-source-v1';

export type PublicPeople2026Payload={players:RealPlayerSeedV2[];staff:RealStaffSeed[];manifest?:any};
export type AssignmentResolutionReport={club:{exact:number;alias:number;unresolved:number;ambiguous:number;absent:number};nationalTeam:{exact:number;alias:number;unresolved:number;ambiguous:number;absent:number}};
export type PublicPeople2026LoadReport={players:{inserted:number;merged:number;duplicatesPrevented:number;conflicts:number};staff:{inserted:number;merged:number};assignments:AssignmentResolutionReport;rosterDuplicatesRemoved:number;medicalProfiles:number;manifest?:any};

type Resolution={id?:string;resolution:SourceAssignmentResolution};
const emptyCounts=()=>({exact:0,alias:0,unresolved:0,ambiguous:0,absent:0});
function resolveAgainst(w:World,raw:string|undefined,valid:Set<string>):Resolution{if(!raw)return{resolution:'absent'};if(valid.has(raw))return{id:raw,resolution:'exact'};const candidates=[...new Set(resolveFootballEntity(w,raw).filter(id=>valid.has(id)))];return candidates.length===1?{id:candidates[0],resolution:'alias'}:candidates.length>1?{resolution:'ambiguous'}:{resolution:'unresolved'}}
function normalizeAssignments(w:World,payload:PublicPeople2026Payload){const clubs=new Set(w.clubs.map(c=>c.id)),teams=new Set(footballDataSnapshot(w).nationalTeams.map(t=>t.id)),report:AssignmentResolutionReport={club:emptyCounts(),nationalTeam:emptyCounts()};const count=(kind:'club'|'nationalTeam',r:SourceAssignmentResolution)=>report[kind][r]++;
 const players=(payload.players??[]).map(seed=>{const club=resolveAgainst(w,seed.clubId,clubs),team=resolveAgainst(w,seed.nationalTeamId,teams);count('club',club.resolution);count('nationalTeam',team.resolution);return{...seed,clubId:club.id,nationalTeamId:team.id,sourceAssignment:{...(seed.sourceAssignment??{}),clubId:seed.sourceAssignment?.clubId??seed.clubId,nationalTeamId:seed.sourceAssignment?.nationalTeamId??seed.nationalTeamId,clubResolution:club.resolution,nationalTeamResolution:team.resolution}}});
 const staff=(payload.staff??[]).map(seed=>{const club=resolveAgainst(w,seed.clubId,clubs),team=resolveAgainst(w,seed.nationalTeamId,teams);count('club',club.resolution);count('nationalTeam',team.resolution);return{...seed,clubId:club.id,nationalTeamId:team.id,sourceAssignment:{...(seed.sourceAssignment??{}),clubId:seed.sourceAssignment?.clubId??seed.clubId,nationalTeamId:seed.sourceAssignment?.nationalTeamId??seed.nationalTeamId,clubResolution:club.resolution,nationalTeamResolution:team.resolution}}});return{players,staff,report}}

export function loadPublicPeople2026(w:World,payload:PublicPeople2026Payload):PublicPeople2026LoadReport{const normalized=normalizeAssignments(w,payload),p=importRealPlayerBatchV2(w,normalized.players),s=importRealStaffBatch(w,normalized.staff),integrity=dedupePlayerRosters(w),medical=medicalState(w);const report={players:{inserted:p.report.inserted,merged:p.report.merged,duplicatesPrevented:p.report.duplicatesPrevented,conflicts:p.report.conflicts.length},staff:{inserted:s.inserted,merged:s.merged},assignments:normalized.report,rosterDuplicatesRemoved:integrity.removed,medicalProfiles:medical.profiles.size,manifest:payload.manifest};queueWorldEvent(w,{date:worldCore(w).date,type:'PublicPeople2026Loaded',scope:'world',entityIds:[],importance:2,payload:report});return report}

async function json<T>(url:string):Promise<T>{const r=await fetch(url);if(!r.ok)throw new Error(`Falha ao carregar ${url}: ${r.status}`);return r.json() as Promise<T>}
export async function loadLiveLicensedPublicPeople2026(w:World){const live=await fetchOpenFootballPeople2026();return loadPublicPeople2026(w,live)}
export async function loadBundledPublicPeople2026(w:World,base='/data/people',options:{fallbackToLicensedLive?:boolean}={fallbackToLicensedLive:true}){try{const [players,staff,manifest]=await Promise.all([json<RealPlayerSeedV2[]>(`${base}/real-players-2026.json`),json<RealStaffSeed[]>(`${base}/real-staff-2026.json`),json<any>(`${base}/manifest-2026.json`).catch(()=>undefined)]);return loadPublicPeople2026(w,{players,staff,manifest})}catch(error){if(!options.fallbackToLicensedLive)throw error;queueWorldEvent(w,{date:worldCore(w).date,type:'PublicPeople2026BundledUnavailable',scope:'world',entityIds:[],importance:1,payload:{base,error:error instanceof Error?error.message:String(error),fallback:'openfootball-cc0'}});return loadLiveLicensedPublicPeople2026(w)}}
