import type { Club, World } from './engine';
import { governanceSnapshot, recruitmentHistory } from './recruitment-workflow';

const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);
const decisionLabel:Record<string,string>={approve:'Aprovado',reject:'Rejeitado',requestScouting:'Exigir scouting',requestMedical:'Exigir avaliação médica',renegotiate:'Renegociar',defer:'Adiar'};

export function renderRecruitmentGovernance(world:World,club:Club):string{
  const history=recruitmentHistory(world,club.id,40);
  const snapshot=governanceSnapshot(world,club.id);
  const gov=snapshot.governance!;const coach=snapshot.coach!;
  return `<header><div><span class="eyebrow">GOVERNANÇA DE CONTRATAÇÕES · ${club.name.toUpperCase()}</span><h1>Comitê de Futebol</h1><p>Contratações passam por interesses esportivos, scouting, medicina, finanças, diretoria e contexto externo. O treinador influencia, mas não possui poder absoluto.</p></div></header>
  <section class="cards"><article class="card metric"><span>Influência do treinador</span><strong>${gov.coachInfluence}</strong></article><article class="card metric"><span>Rigor de governança</span><strong>${gov.governanceStrictness}</strong></article><article class="card metric"><span>Ambição esportiva</span><strong>${gov.sportingAmbition}</strong></article><article class="card metric"><span>Tolerância a risco médico</span><strong>${gov.medicalRiskTolerance}</strong></article></section>
  <div class="recruitment-layout"><section class="card"><div class="section-title"><h2>Processos recentes</h2><span>${history.length} solicitações</span></div>${history.length?`<div class="recruitment-list">${history.map(p=>`<article class="recruitment-case ${p.status}"><div class="case-head"><div><b>${p.playerName}</b><small>${p.position} · ${p.initiatedBy} · ${p.urgency}</small></div><span>${p.status.toUpperCase()}</span></div><div class="case-numbers"><span>Taxa <b>${money(p.fee)}</b></span><span>Salário <b>${money(p.expectedWage)}/sem</b></span><span>Necessidade <b>${Math.round(p.needScore)}</b></span><span>Score final <b>${p.finalScore??'—'}</b></span></div><div class="workflow-track">${p.steps.map(s=>`<div class="workflow-step ${s.decision}"><b>${s.stage}</b><span>${decisionLabel[s.decision]??s.decision}</span><small>${s.score}/100${s.mandatory?' · obrigatório':''}</small></div>`).join('')}</div>${p.finalReasons?.length?`<p>${p.finalReasons.join(' ')}</p>`:''}</article>`).join('')}</div>`:'<div class="empty-state">Nenhum processo de contratação ainda.</div>'}</section>
  <aside class="card"><div class="section-title"><h2>Identidade decisória</h2><span>Clube + treinador</span></div><div class="governance-list"><div><b>Conservadorismo financeiro</b><span>${gov.financialConservatism}</span></div><div><b>Preferência por jovens</b><span>${gov.youthPreference}</span></div><div><b>Preferência por revenda</b><span>${gov.resalePreference}</span></div><div><b>Sensibilidade à torcida</b><span>${gov.supporterSensitivity}</span></div><div><b>Sensibilidade à imprensa</b><span>${gov.mediaSensitivity}</span></div><div><b>Influência diretor de futebol</b><span>${gov.footballDirectorInfluence}</span></div><div><b>Identidade tática</b><span>${coach.tacticalIdentity}</span></div><div><b>Exigência física</b><span>${coach.physicalDemand}</span></div><div><b>Exigência técnica</b><span>${coach.technicalDemand}</span></div><div><b>Paciência com desenvolvimento</b><span>${coach.patienceForDevelopment}</span></div></div></aside></div>`;
}
