import './save-beta-ui-v1.css';
import { createSaveSnapshot, type SaveGameV15 } from './save-game';
import { snapshotWorldFoundation, restoreWorldFoundation, WORLD_SAVE_SCHEMA_VERSION, type WorldFoundationSave } from './world-save-schema-v2';
import { restoreDailyCalendar } from './daily-simulation';
import { restoreEventBus } from './event-bus';
import { restoreInstitutionalState } from './institutional-memory';
import { restoreTemporalState } from './temporal-persistence';
import { restoreHumanLife } from './human-life';
import { restoreSocialWorld } from './social-world';
import { restoreDressingRoom } from './dressing-room';
import { restoreTrainingState } from './training-engine';
import { restoreManagerInteractions } from './manager-interactions';
import { restoreManagerCharacters } from './manager-character';
import { restoreManagerDevelopment } from './manager-education-development';
import { restoreManagerEvolution } from './manager-longterm-evolution';
import { restoreManagerEmployment } from './manager-employment';
import { restoreManagerCareerLife } from './manager-career-lifecycle';
import { restoreManagerJobMarket } from './manager-job-market-v2';
import { restoreManagerJobInterviews } from './manager-job-interview';
import { restoreTechnicalStaff } from './technical-staff';
import { economyState, type Contract, type ClubFinance, type TransferRecord, type LoanRecord } from './economy';
import { recruitmentWorkflowState, type ClubGovernance, type CoachRecruitmentProfile, type RecruitmentProposal } from './recruitment-workflow';
import { snapshotPressRoom, restorePressRoom, type PressRoomSnapshot } from './football-press-room-v1';
import type { Player, World } from './engine';

const key='touchline-beta-save-v2';
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
type EconomyBetaSnapshot={contracts:[string,Contract][];finances:[string,ClubFinance][];freeAgents:Player[];transfers:TransferRecord[];loans:LoanRecord[]};
type RecruitmentBetaSnapshot={governance:[string,ClubGovernance][];coaches:[string,CoachRecruitmentProfile][];proposals:RecruitmentProposal[]};
type TouchlineBetaSave={format:'touchline-beta';version:2;createdAt:string;base:SaveGameV15;foundation:WorldFoundationSave;economy:EconomyBetaSnapshot;recruitment:RecruitmentBetaSnapshot;pressRoom:PressRoomSnapshot};
function world(){return window.__touchlineWorld as World|undefined}
function snapshotEconomy(w:World):EconomyBetaSnapshot{const s=economyState(w);return{contracts:[...s.contracts].map(([k,v])=>[k,clone(v)]),finances:[...s.finances].map(([k,v])=>[k,clone(v)]),freeAgents:clone(s.freeAgents),transfers:clone(s.transfers),loans:clone(s.loans)}}
function restoreEconomy(w:World,x:EconomyBetaSnapshot){const s=economyState(w);s.contracts=new Map((x.contracts??[]).map(([k,v])=>[k,clone(v)]));s.finances=new Map((x.finances??[]).map(([k,v])=>[k,clone(v)]));s.freeAgents=clone(x.freeAgents??[]);s.transfers=clone(x.transfers??[]);s.loans=clone(x.loans??[])}
function snapshotRecruitment(w:World):RecruitmentBetaSnapshot{const s=recruitmentWorkflowState(w);return{governance:[...s.governance].map(([k,v])=>[k,clone(v)]),coaches:[...s.coaches].map(([k,v])=>[k,clone(v)]),proposals:clone(s.proposals)}}
function restoreRecruitment(w:World,x:RecruitmentBetaSnapshot){const s=recruitmentWorkflowState(w);s.governance=new Map((x.governance??[]).map(([k,v])=>[k,clone(v)]));s.coaches=new Map((x.coaches??[]).map(([k,v])=>[k,clone(v)]));s.proposals=clone(x.proposals??[])}
function createBetaSave(w:World):TouchlineBetaSave{return{format:'touchline-beta',version:2,createdAt:new Date().toISOString(),base:createSaveSnapshot(w),foundation:snapshotWorldFoundation(w,{gameVersion:'0.2.0-beta.1',notes:'Playable beta composite save'}),economy:snapshotEconomy(w),recruitment:snapshotRecruitment(w),pressRoom:snapshotPressRoom(w)}}
function restoreLegacyBase(target:World,save:SaveGameV15){const source=save.world;for(const k of Object.keys(target as any))delete (target as any)[k];Object.assign(target,clone(source));restoreDailyCalendar(target,save.calendar);restoreEventBus(target,save.events);restoreInstitutionalState(target,save.institutional);restoreTemporalState(target,save.temporal);restoreHumanLife(target,save.humanLife);restoreSocialWorld(target,save.socialWorld);restoreDressingRoom(target,save.dressingRoom);restoreTrainingState(target,save.training);restoreManagerInteractions(target,save.managerInteractions);restoreManagerCharacters(target,save.managerCharacters);restoreManagerDevelopment(target,save.managerDevelopment);restoreManagerEvolution(target,save.managerEvolution);restoreManagerEmployment(target,save.managerEmployment);restoreManagerCareerLife(target,save.managerCareerLife);restoreManagerJobMarket(target,save.managerJobMarket);restoreManagerJobInterviews(target,save.managerJobInterviews);restoreTechnicalStaff(target,save.technicalStaff)}
function restoreInto(target:World,save:TouchlineBetaSave){if(save.format!=='touchline-beta'||save.version!==2)throw new Error('Save não pertence à beta v2.');if(save.base.schemaVersion!==15)throw new Error(`Base incompatível: schema ${save.base.schemaVersion}.`);restoreLegacyBase(target,save.base);restoreWorldFoundation(target,save.foundation);restoreEconomy(target,save.economy);restoreRecruitment(target,save.recruitment);restorePressRoom(target,save.pressRoom);window.dispatchEvent(new CustomEvent('touchline:save-loaded',{detail:{createdAt:save.createdAt,season:target.season,foundation:save.foundation.schemaVersion}}))}
function parse(raw:string):TouchlineBetaSave{const s=JSON.parse(raw) as TouchlineBetaSave;if(s.format!=='touchline-beta'||s.version!==2)throw new Error('Formato de save não suportado por esta beta.');return s}
function renderSave(){const w=world(),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!host)return;const raw=localStorage.getItem(key);let meta='Nenhum save local';if(raw){try{const s=parse(raw);meta=`Beta v${s.version} · Foundation V${s.foundation.schemaVersion} · ${new Date(s.createdAt).toLocaleString('pt-BR')} · temporada ${s.base.world.season}`}catch{meta='Save local inválido'}}host.innerHTML=`<header class="view-hero"><div><span class="kicker">CARREIRA · PERSISTÊNCIA</span><h1>Salvar & Carregar</h1><p>Snapshot composto da beta: mundo jogável + estados profundos dos motores.</p></div><div class="hero-glow"></div></header><section class="save-beta-grid"><article class="glass save-card"><span>SAVE LOCAL</span><h3>${meta}</h3><button data-save-local>SALVAR AGORA</button><button data-load-local ${raw?'':'disabled'}>CARREGAR SAVE</button></article><article class="glass save-card"><span>ARQUIVO</span><h3>Backup JSON</h3><button data-export-save>EXPORTAR SAVE</button><label class="save-import">IMPORTAR SAVE<input data-import-save type="file" accept="application/json,.json"></label></article></section><section class="glass save-status" data-save-status><b>Beta save v2 · Base V15 + Foundation V${WORLD_SAVE_SCHEMA_VERSION}</b><p>Inclui o World com elencos/fixtures/classificação e, em paralelo, calendário, treinador, emprego, entrevistas, vida social, vestiário, treino, medicina, scouting, negociações, economia/contratos, recrutamento, Sport News, coletiva, Escolinha, finanças pessoais, staff real/técnico e demais estados do Foundation.</p></section>`;const status=(msg:string)=>{const box=document.querySelector<HTMLElement>('[data-save-status]');if(box)box.innerHTML=`<b>${msg}</b>`};document.querySelector<HTMLButtonElement>('[data-save-local]')?.addEventListener('click',()=>{const s=createBetaSave(w);localStorage.setItem(key,JSON.stringify(s));status('Carreira completa salva com sucesso.');setTimeout(renderSave,250)});document.querySelector<HTMLButtonElement>('[data-load-local]')?.addEventListener('click',()=>{try{restoreInto(w,parse(localStorage.getItem(key)!));status('Save carregado com todos os estados da beta.')}catch(e){status(`Falha ao carregar: ${String(e)}`)}});document.querySelector<HTMLButtonElement>('[data-export-save]')?.addEventListener('click',()=>{const s=createBetaSave(w),blob=new Blob([JSON.stringify(s)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`touchline-${w.season}-beta-full.json`;a.click();URL.revokeObjectURL(url);status('Backup completo exportado.');});document.querySelector<HTMLInputElement>('[data-import-save]')?.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;try{const raw=await f.text(),s=parse(raw);localStorage.setItem(key,raw);restoreInto(w,s);status('Arquivo importado e carregado com sucesso.')}catch(err){status(`Falha na importação: ${String(err)}`)}})}
function inject(){const nav=document.querySelector('.game-sidebar nav');if(!nav||nav.querySelector('[data-save-view]'))return;const manager=nav.querySelector('[data-view="manager"]');const b=document.createElement('button');b.dataset.saveView='1';b.innerHTML='<span class="engine-nav-icon">▣</span><span>Salvar</span>';b.onclick=renderSave;manager?.after(b)}
const app=document.querySelector('#app');if(app)new MutationObserver(()=>queueMicrotask(inject)).observe(app,{subtree:true,childList:true});window.addEventListener('touchline:world-ready',inject);inject();