import type { World } from './engine';
import { snapshotDailyCalendar, restoreDailyCalendar, type DailyCalendarSnapshot } from './daily-simulation';
import { snapshotEventBus, restoreEventBus, type EventBusSnapshot } from './event-bus';
import { snapshotInstitutionalState, restoreInstitutionalState, type InstitutionalSnapshot } from './institutional-memory';
import { snapshotTemporalState, restoreTemporalState, type TemporalSnapshot } from './temporal-persistence';
import { snapshotHumanLife, restoreHumanLife, type HumanLifeSnapshot } from './human-life';
import { snapshotSocialWorld, restoreSocialWorld, type SocialWorldSnapshot } from './social-world';
import { snapshotDressingRoom, restoreDressingRoom, type DressingRoomSnapshot } from './dressing-room';
import { snapshotTrainingState, restoreTrainingState, type TrainingSnapshot } from './training-engine';
import { snapshotManagerInteractions, restoreManagerInteractions, type ManagerInteractionSnapshot } from './manager-interactions';
import { snapshotManagerCharacters, restoreManagerCharacters, type ManagerCharacterSnapshot } from './manager-character';
import { snapshotManagerDevelopment, restoreManagerDevelopment, type ManagerDevelopmentSnapshot } from './manager-education-development';
import { snapshotManagerEvolution, restoreManagerEvolution, type ManagerEvolutionSnapshot } from './manager-longterm-evolution';
import { snapshotManagerEmployment, restoreManagerEmployment, type ManagerEmploymentSnapshot } from './manager-employment';
import { snapshotManagerCareerLife, restoreManagerCareerLife, type ManagerCareerLifeSnapshot } from './manager-career-lifecycle';

export type SaveGameV1={schemaVersion:1;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot};
export type SaveGameV2={schemaVersion:2;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot};
export type SaveGameV3={schemaVersion:3;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot};
export type SaveGameV4={schemaVersion:4;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot};
export type SaveGameV5={schemaVersion:5;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot};
export type SaveGameV6={schemaVersion:6;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot};
export type SaveGameV7={schemaVersion:7;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot;managerInteractions:ManagerInteractionSnapshot};
export type SaveGameV8={schemaVersion:8;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot;managerInteractions:ManagerInteractionSnapshot;managerCharacters:ManagerCharacterSnapshot};
export type SaveGameV9={schemaVersion:9;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot;managerInteractions:ManagerInteractionSnapshot;managerCharacters:ManagerCharacterSnapshot;managerDevelopment:ManagerDevelopmentSnapshot};
export type SaveGameV10={schemaVersion:10;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot;managerInteractions:ManagerInteractionSnapshot;managerCharacters:ManagerCharacterSnapshot;managerDevelopment:ManagerDevelopmentSnapshot;managerEvolution:ManagerEvolutionSnapshot};
export type SaveGameV11={schemaVersion:11;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot;managerInteractions:ManagerInteractionSnapshot;managerCharacters:ManagerCharacterSnapshot;managerDevelopment:ManagerDevelopmentSnapshot;managerEvolution:ManagerEvolutionSnapshot;managerEmployment:ManagerEmploymentSnapshot};
export type SaveGameV12={schemaVersion:12;createdAt:string;world:World;calendar:DailyCalendarSnapshot;events:EventBusSnapshot;institutional:InstitutionalSnapshot;temporal:TemporalSnapshot;humanLife:HumanLifeSnapshot;socialWorld:SocialWorldSnapshot;dressingRoom:DressingRoomSnapshot;training:TrainingSnapshot;managerInteractions:ManagerInteractionSnapshot;managerCharacters:ManagerCharacterSnapshot;managerDevelopment:ManagerDevelopmentSnapshot;managerEvolution:ManagerEvolutionSnapshot;managerEmployment:ManagerEmploymentSnapshot;managerCareerLife:ManagerCareerLifeSnapshot};
export type SaveGame=SaveGameV1|SaveGameV2|SaveGameV3|SaveGameV4|SaveGameV5|SaveGameV6|SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12;

export function createSaveSnapshot(world:World):SaveGameV12{return{schemaVersion:12,createdAt:new Date().toISOString(),world:JSON.parse(JSON.stringify(world)) as World,calendar:snapshotDailyCalendar(world),events:snapshotEventBus(world),institutional:snapshotInstitutionalState(world),temporal:snapshotTemporalState(world),humanLife:snapshotHumanLife(world),socialWorld:snapshotSocialWorld(world),dressingRoom:snapshotDressingRoom(world),training:snapshotTrainingState(world),managerInteractions:snapshotManagerInteractions(world),managerCharacters:snapshotManagerCharacters(world),managerDevelopment:snapshotManagerDevelopment(world),managerEvolution:snapshotManagerEvolution(world),managerEmployment:snapshotManagerEmployment(world),managerCareerLife:snapshotManagerCareerLife(world)};}
export function serializeSave(world:World):string{return JSON.stringify(createSaveSnapshot(world));}
export function restoreSave(serialized:string):World{const parsed=JSON.parse(serialized) as SaveGame;if(![1,2,3,4,5,6,7,8,9,10,11,12].includes(parsed.schemaVersion))throw new Error(`Save incompatível: versão ${String((parsed as {schemaVersion?:unknown}).schemaVersion)}`);const world=parsed.world;restoreDailyCalendar(world,parsed.calendar);restoreEventBus(world,parsed.events);restoreInstitutionalState(world,parsed.institutional);if(parsed.schemaVersion>=2)restoreTemporalState(world,(parsed as SaveGameV2|SaveGameV3|SaveGameV4|SaveGameV5|SaveGameV6|SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).temporal);if(parsed.schemaVersion>=3)restoreHumanLife(world,(parsed as SaveGameV3|SaveGameV4|SaveGameV5|SaveGameV6|SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).humanLife);if(parsed.schemaVersion>=4)restoreSocialWorld(world,(parsed as SaveGameV4|SaveGameV5|SaveGameV6|SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).socialWorld);if(parsed.schemaVersion>=5)restoreDressingRoom(world,(parsed as SaveGameV5|SaveGameV6|SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).dressingRoom);if(parsed.schemaVersion>=6)restoreTrainingState(world,(parsed as SaveGameV6|SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).training);if(parsed.schemaVersion>=7)restoreManagerInteractions(world,(parsed as SaveGameV7|SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).managerInteractions);if(parsed.schemaVersion>=8)restoreManagerCharacters(world,(parsed as SaveGameV8|SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).managerCharacters);if(parsed.schemaVersion>=9)restoreManagerDevelopment(world,(parsed as SaveGameV9|SaveGameV10|SaveGameV11|SaveGameV12).managerDevelopment);if(parsed.schemaVersion>=10)restoreManagerEvolution(world,(parsed as SaveGameV10|SaveGameV11|SaveGameV12).managerEvolution);if(parsed.schemaVersion>=11)restoreManagerEmployment(world,(parsed as SaveGameV11|SaveGameV12).managerEmployment);if(parsed.schemaVersion===12)restoreManagerCareerLife(world,parsed.managerCareerLife);return world;}
export function downloadSave(world:World,fileName=`football-project-${world.season}.json`):void{const blob=new Blob([serializeSave(world)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName;a.click();URL.revokeObjectURL(url);}
