import type { Club, Player, Position, World } from './engine';
import { economyState, playerMarketValue } from './economy';
import { executeBackgroundPermanentTransfer, type BackgroundTransferResult } from './background-club-transfer-v1';
import { negotiateTransfer, type NegotiationCase } from './negotiation';
import { realPlayerByIdV2 } from './real-world-player-import-v2';
import { evaluateRecruitmentProposal, recruitmentWorkflowState, type RecruitmentProposal } from './recruitment-workflow';
import { scoutingReport } from './scouting';
import { worldPlayerById, worldPlayerClub } from './world-player-pool-v1';
import { footballClub } from './world-football-data-v1';

export type ScoutingMarketStatus={playerId:string;transactionReady:boolean;kind:'transfer'|'free'|'background-club'|'external-unmapped'|'own-player'|'missing';sellerClubId?:string;sellerName?:string;label:string;reason:string};
export type BackgroundRecruitmentExecution={ok:boolean;status:ScoutingMarketStatus;proposal?:RecruitmentProposal;negotiation?:NegotiationCase;transfer?:BackgroundTransferResult['transfer'];reason?:string};
const minimum:Partial<Record<Position,number>>={GK:2,RB:2,CB:4,LB:2,DM:2,CM:3,AM:2,RW:2,LW:2,ST:3};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
function needScore(club:Club,player:Player){const same=club.players.filter(p=>p.position===player.position),target=minimum[player.position]??2,best=Math.max(0,...same.map(p=>p.currentAbility)),shortage=Math.max(0,target-same.length)*24,quality=Math.max(0,player.currentAbility-best+8)*2.2,potential=player.age<=23?Math.max(0,player.potentialAbility-player.currentAbility)*.8:0;return clamp(28+shortage+quality+potential,0,100)}
function estimatedWage(player:Player,buyer:Club){const base=Math.pow(Math.max(20,player.currentAbility),2.05)*1.85,rep=.75+buyer.reputation/140,age=player.age<=21?.72:player.age>=32?.82:1;return Math.max(500,Math.round(base*rep*age/100)*100)}

export function scoutingMarketStatus(world:World,buyerClubId:string,playerId:string):ScoutingMarketStatus{
  const player=worldPlayerById(world,playerId,economyState(world).freeAgents);if(!player)return{playerId,transactionReady:false,kind:'missing',label:'Indisponível',reason:'A identidade não existe na população ativa.'};
  if(player.clubId===buyerClubId)return{playerId,transactionReady:false,kind:'own-player',label:'Seu jogador',reason:'O atleta já pertence ao clube do treinador.'};
  const economy=economyState(world);if(economy.freeAgents.some(p=>p.id===playerId))return{playerId,transactionReady:true,kind:'free',label:'Agente livre',reason:'O jogador está explicitamente registrado como agente livre no estado econômico da carreira.'};
  const seller=worldPlayerClub(world,playerId);if(seller&&seller.id!==buyerClubId)return{playerId,transactionReady:true,kind:'transfer',sellerClubId:seller.id,sellerName:seller.name,label:'Negociação disponível',reason:`Vínculo ativo confirmado com ${seller.name}.`};
  const background=player.clubId&&player.clubId!=='unattached'?footballClub(world,player.clubId):undefined;if(background)return{playerId,transactionReady:true,kind:'background-club',sellerClubId:background.id,sellerName:background.name,label:'Negociação factual disponível',reason:`Vínculo factual confirmado com ${background.name}. O clube permanece fora do calendário jogável, mas pode negociar economicamente por meio do adaptador Tier B/C.`};
  const real=realPlayerByIdV2(world,playerId),sourceClub=real?.sourceAssignment?.clubId;return{playerId,transactionReady:false,kind:'external-unmapped',label:'Apenas scouting',reason:sourceClub?`A fonte indica vínculo externo (${sourceClub}), mas ele ainda não foi resolvido com segurança para um clube canônico.`:'A fonte não fornece vínculo atual confiável; o jogo não presume que o atleta esteja livre.'};
}
export function submitScoutedPlayerToRecruitment(world:World,buyerClubId:string,playerId:string):{ok:boolean;status:ScoutingMarketStatus;proposal?:RecruitmentProposal;reason?:string}{const status=scoutingMarketStatus(world,buyerClubId,playerId);if(!status.transactionReady)return{ok:false,status,reason:status.reason};const buyer=world.clubs.find(c=>c.id===buyerClubId),player=worldPlayerById(world,playerId,economyState(world).freeAgents);if(!buyer||!player)return{ok:false,status,reason:'Comprador ou jogador não encontrado no runtime.'};const state=recruitmentWorkflowState(world),existing=[...state.proposals].reverse().find(p=>p.buyerClubId===buyerClubId&&p.playerId===playerId&&p.season===world.season&&p.status!=='rejected');if(existing)return{ok:true,status,proposal:existing};const economy=economyState(world),finance=economy.finances.get(buyer.id);if(!finance)return{ok:false,status,reason:'Finanças do clube comprador indisponíveis.'};const contract=economy.contracts.get(player.id),fee=status.kind==='free'?0:Math.round(playerMarketValue(player)*1.08/10000)*10000,wage=contract?.weeklyWage??estimatedWage(player,buyer),report=scoutingReport(world,buyer.id,player.id),urgency=needScore(buyer,player)>=75?'high':'normal',proposal=evaluateRecruitmentProposal(world,buyer,player,{fee,expectedWage:wage,needScore:needScore(buyer,player),transferBudget:finance.transferBudget,wageBudget:finance.wageBudget,wageSpend:finance.wageSpend,sellerClubId:status.sellerClubId,initiatedBy:'scoutingDepartment',urgency});if((report?.confidence??0)<20&&proposal.status==='approved')proposal.status='deferred';return{ok:true,status,proposal}}
export function completeBackgroundScoutedTransfer(world:World,buyerClubId:string,playerId:string):BackgroundRecruitmentExecution{
  const submitted=submitScoutedPlayerToRecruitment(world,buyerClubId,playerId),status=submitted.status;if(!submitted.ok||status.kind!=='background-club'||!status.sellerClubId)return{ok:false,status,proposal:submitted.proposal,reason:submitted.reason??'O atleta não possui vendedor factual de background elegível.'};
  const proposal=submitted.proposal;if(!proposal||proposal.status!=='approved')return{ok:false,status,proposal,reason:`Comitê não aprovou a negociação (${proposal?.status??'sem proposta'}).`};
  const buyer=world.clubs.find(c=>c.id===buyerClubId),player=worldPlayerById(world,playerId,economyState(world).freeAgents),finance=economyState(world).finances.get(buyerClubId);if(!buyer||!player||!finance)return{ok:false,status,proposal,reason:'Comprador, jogador ou finanças indisponíveis na execução.'};
  const negotiation=negotiateTransfer(world,buyer,undefined,player,{fee:proposal.fee,weeklyWage:proposal.expectedWage,transferBudget:finance.transferBudget,initiatedBy:'scouting',urgency:proposal.urgency,dealType:'permanent',externalSellerClubId:status.sellerClubId});if(negotiation.status!=='accepted')return{ok:false,status,proposal,negotiation,reason:negotiation.finalReason??`Negociação ${negotiation.status}.`};
  const executed=executeBackgroundPermanentTransfer(world,buyer,player,status.sellerClubId,negotiation.currentPackage);return{ok:executed.ok,status,proposal,negotiation,transfer:executed.transfer,reason:executed.reason};
}
