import type { Club, Position, World } from './engine';
import { activeAssignments, assignScout, isShortlisted, scoutProfile, scoutingCandidates, scoutingReport, shortlistedReports, toggleShortlist } from './scouting';
import { globalScoutingCountries, globalScoutingSearch } from './global-scouting-search-v1';
import { scoutingMarketStatus, submitScoutedPlayerToRecruitment } from './scouting-recruitment-bridge-v1';
import { worldPlayerPoolCounts } from './world-player-pool-v1';

const positions: Position[] = ['GK','RB','CB','LB','DM','CM','AM','RW','LW','ST'];
const money = (value:number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(value);
const num = (value:number) => new Intl.NumberFormat('pt-BR').format(value);
const range = (r:{min:number;max:number}) => r.min===r.max ? `${r.min}` : `${r.min}–${r.max}`;
const recommendationLabel: Record<string,string> = { avoid:'Descartar', monitor:'Monitorar', consider:'Considerar', strong:'Forte alvo', elite:'Elite' };

export type ScoutingUiState = {position?: Position;countryId?:string;query?:string;selectedPlayerId?: string;showShortlist: boolean;notice?:string};
export function createScoutingUiState(): ScoutingUiState {return { showShortlist:false }}

export function renderScouting(world: World, observer: Club, state: ScoutingUiState): string {
  const profile = scoutProfile(world,observer.id)!;
  const assignments = activeAssignments(world,observer.id);
  const pool = worldPlayerPoolCounts(world);
  const countries = globalScoutingCountries(world);
  const searching = !state.showShortlist && Boolean(state.query?.trim()||state.countryId);
  const search = searching ? globalScoutingSearch(world,{observerClubId:observer.id,query:state.query,countryId:state.countryId,position:state.position,limit:80}) : undefined;
  const candidates = state.showShortlist ? shortlistedReports(world,observer.id) : search?.reports ?? scoutingCandidates(world,observer.id,state.position,40);
  const selected = state.selectedPlayerId ? scoutingReport(world,observer.id,state.selectedPlayerId) : candidates[0];
  if (selected && !state.selectedPlayerId) state.selectedPlayerId=selected.playerId;
  const attrs = selected ? Object.entries(selected.attributes) : [];
  const market = selected ? scoutingMarketStatus(world,observer.id,selected.playerId) : undefined;
  const resultText=state.showShortlist?`${candidates.length} na lista`:search?`${num(search.matched)} encontrados em ${num(search.scanned)} ativos`:`${candidates.length} melhores exibidos`;
  return `<header><div><span class="eyebrow">RECRUTAMENTO · ${observer.name.toUpperCase()}</span><h1>Centro de Scouting</h1><p>Busca conectada ao universo global do jogo. Jogadores de clubes ativos e atletas reais de background compartilham a mesma identidade persistente, sem expor CA/PA reais antes do conhecimento do scout.</p></div></header>
  <section class="cards"><article class="card metric"><span>Universo ativo</span><strong>${num(pool.active)}</strong><small>${num(pool.backgroundReal)} atletas reais de background</small></article><article class="card metric"><span>Julgar habilidade</span><strong>${profile.judgingAbility}</strong></article><article class="card metric"><span>Julgar potencial</span><strong>${profile.judgingPotential}</strong></article><article class="card metric"><span>Scouts ocupados</span><strong>${assignments.length}/${profile.capacity}</strong><small>Adaptabilidade ${profile.adaptability}</small></article></section>
  ${state.notice?`<section class="card scouting-notice"><b>${state.notice}</b></section>`:''}
  <div class="scouting-toolbar"><input id="scout-query" type="search" value="${state.query??''}" placeholder="Buscar jogador, clube ou país" aria-label="Buscar no universo global"><select id="scout-country"><option value="">Todas as nacionalidades</option>${countries.slice(0,180).map(c=>`<option value="${c.id}" ${state.countryId===c.id?'selected':''}>${c.name} (${num(c.count)})</option>`).join('')}</select><select id="scout-position"><option value="">Todas as posições</option>${positions.map(p=>`<option value="${p}" ${state.position===p?'selected':''}>${p}</option>`).join('')}</select><button id="run-scout-search" class="primary">Buscar</button><button id="clear-scout-search" class="secondary">Limpar</button><button id="toggle-shortlist" class="secondary">${state.showShortlist?'Ver candidatos':'Ver lista de interesse'}</button><span class="scouting-global-note">${resultText} · ${num(pool.retired)} aposentados preservados</span></div>
  <div class="scouting-layout"><section class="card scouting-list"><div class="section-title"><h2>${state.showShortlist?'Lista de interesse':searching?'Resultado da busca global':'Melhores candidatos do universo global'}</h2><span>${resultText}</span></div>${candidates.length?`<table><thead><tr><th>Jogador</th><th>Clube</th><th>Pos</th><th>Idade</th><th>CA estimado</th><th>PA estimado</th><th>Conf.</th><th></th></tr></thead><tbody>${candidates.map(r=>`<tr class="${selected?.playerId===r.playerId?'selected-scout':''}"><td><button class="scout-player" data-scout-player="${r.playerId}">${r.playerName}</button></td><td>${r.clubId==='unattached'?'Vínculo não mapeado':world.clubs.find(c=>c.id===r.clubId)?.name??r.clubId}</td><td>${r.position}</td><td>${r.age}</td><td>${range(r.currentAbility)}</td><td>${range(r.potentialAbility)}</td><td>${r.confidence}%</td><td><span class="scout-grade ${r.recommendation}">${recommendationLabel[r.recommendation]}</span></td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Nenhum jogador encontrado com estes filtros.</div>'}</section>
  <aside class="card scouting-report">${selected?`<div class="section-title"><h2>${selected.playerName}</h2><span>${selected.position} · ${selected.age} anos</span></div><div class="report-body"><div class="knowledge-meter"><span>Conhecimento</span><b>${selected.confidence}%</b><div><i style="width:${selected.confidence}%"></i></div></div><div class="report-verdict ${selected.recommendation}"><b>${recommendationLabel[selected.recommendation]}</b><p>${selected.summary}</p></div><div class="report-grid"><div><span>Habilidade</span><b>${range(selected.currentAbility)}</b></div><div><span>Potencial</span><b>${range(selected.potentialAbility)}</b></div><div><span>Valor estimado</span><b>${money(selected.marketValue.min)}${selected.marketValue.min===selected.marketValue.max?'':` – ${money(selected.marketValue.max)}`}</b></div><div><span>Confiança</span><b>${selected.confidence}%</b></div></div><div class="report-grid"><div><span>Mercado</span><b>${market?.label??'—'}</b></div><div><span>Origem</span><b>${selected.clubId==='unattached'?'Vínculo não mapeado':world.clubs.find(c=>c.id===selected.clubId)?.name??selected.clubId}</b></div></div><p class="scouting-market-reason">${market?.reason??''}</p><div class="scout-attrs"><h3>Atributos conhecidos</h3>${attrs.length?attrs.map(([name,value])=>`<div><span>${name}</span><b>${range(value!)}</b></div>`).join(''):'<p>Conhecimento insuficiente para estimar atributos.</p>'}</div><div class="report-actions"><button id="assign-scout" class="primary" data-player="${selected.playerId}">${assignments.some(a=>a.playerId===selected.playerId)?'Em observação':'Observar jogador'}</button><button id="shortlist-player" class="secondary" data-player="${selected.playerId}">${isShortlisted(world,observer.id,selected.playerId)?'Remover da lista':'Adicionar à lista'}</button><button id="submit-recruitment" class="primary" data-player="${selected.playerId}" ${market?.transactionReady?'':'disabled'}>${market?.transactionReady?'Levar ao comitê':'Negociação indisponível'}</button></div></div>`:'<div class="empty-state">Selecione um jogador.</div>'}</aside></div>`;
}

export function bindScouting(world: World, observer: Club, state: ScoutingUiState, rerender:()=>void): void {
  const apply=()=>{state.query=document.querySelector<HTMLInputElement>('#scout-query')?.value.trim()||undefined;state.countryId=document.querySelector<HTMLSelectElement>('#scout-country')?.value||undefined;state.position=(document.querySelector<HTMLSelectElement>('#scout-position')?.value||undefined) as Position|undefined;state.selectedPlayerId=undefined;state.showShortlist=false;state.notice=undefined;rerender()};
  document.querySelector<HTMLButtonElement>('#run-scout-search')?.addEventListener('click',apply);
  document.querySelector<HTMLInputElement>('#scout-query')?.addEventListener('keydown',event=>{if(event.key==='Enter')apply()});
  document.querySelector<HTMLButtonElement>('#clear-scout-search')?.addEventListener('click',()=>{state.query=undefined;state.countryId=undefined;state.position=undefined;state.selectedPlayerId=undefined;state.showShortlist=false;state.notice=undefined;rerender()});
  document.querySelector<HTMLSelectElement>('#scout-position')?.addEventListener('change',apply);
  document.querySelector<HTMLSelectElement>('#scout-country')?.addEventListener('change',apply);
  document.querySelector<HTMLButtonElement>('#toggle-shortlist')?.addEventListener('click',()=>{state.showShortlist=!state.showShortlist;state.selectedPlayerId=undefined;state.notice=undefined;rerender()});
  document.querySelectorAll<HTMLButtonElement>('[data-scout-player]').forEach(button=>button.addEventListener('click',()=>{state.selectedPlayerId=button.dataset.scoutPlayer;state.notice=undefined;rerender()}));
  document.querySelector<HTMLButtonElement>('#assign-scout')?.addEventListener('click',event=>{const playerId=(event.currentTarget as HTMLButtonElement).dataset.player;if(playerId)assignScout(world,observer.id,playerId);state.notice='Observação atualizada no departamento de scouting.';rerender()});
  document.querySelector<HTMLButtonElement>('#shortlist-player')?.addEventListener('click',event=>{const playerId=(event.currentTarget as HTMLButtonElement).dataset.player;if(playerId){const added=toggleShortlist(world,observer.id,playerId);state.notice=added?'Jogador adicionado à lista de interesse.':'Jogador removido da lista de interesse.'}rerender()});
  document.querySelector<HTMLButtonElement>('#submit-recruitment')?.addEventListener('click',event=>{const playerId=(event.currentTarget as HTMLButtonElement).dataset.player;if(!playerId)return;const result=submitScoutedPlayerToRecruitment(world,observer.id,playerId);state.notice=result.ok&&result.proposal?`Processo ${result.proposal.status}: ${result.proposal.playerName} enviado ao Comitê de Futebol.`:result.reason??result.status.reason;rerender()});
}
