import type { Club, World } from './engine';
import { emitWorldEvent } from './event-bus';
import { humanLifeState, type LifePerson, type LifeProfile } from './human-life';
import { worldRandom } from './world-core-v2';

export type SocialActorRole='manager'|'assistant'|'physio'|'director'|'journalist'|'supporterLeader';
export type SocialActor={id:string;role:SocialActorRole;clubId?:string;personId:string;influence:number;credibility:number;stress:number;relationshipWithClub:number};
export type SocialWorldState={actors:Map<string,SocialActor>;lastTick?:string};
export type SocialWorldSnapshot={actors:[string,SocialActor][];lastTick?:string};

const states=new WeakMap<World,SocialWorldState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:number,o:number)=>{const x=Math.sin(s*12.9898+o*78.233)*43758.5453;return x-Math.floor(x)};
const names=['Marcelo Nunes','Renato Prado','Fábio Torres','André Martins','Gustavo Lima','Ricardo Alves','Paulo Vieira','Bruno Costa','Carla Rocha','Mariana Lopes','Fernanda Dias','Juliana Moura'];

function makePerson(id:string,name:string,kind:LifePerson['kind'],clubId:string|undefined,seed:number):LifePerson{return{id,kind,name,clubId,fame:Math.round(25+pseudo(seed,1)*60),mediaInterest:Math.round(20+pseudo(seed,2)*70),privacy:Math.round(30+pseudo(seed,3)*65),temperament:Math.round(20+pseudo(seed,4)*75),professionalism:Math.round(40+pseudo(seed,5)*55),sociability:Math.round(25+pseudo(seed,6)*70)};}
function makeProfile(id:string,seed:number):LifeProfile{return{personId:id,familyOrientation:Math.round(30+pseudo(seed,7)*65),nightlifeAffinity:Math.round(5+pseudo(seed,8)*60),fameComfort:Math.round(25+pseudo(seed,9)*70),scandalRisk:Math.round(5+pseudo(seed,10)*55),relationshipNeed:Math.round(25+pseudo(seed,11)*70),stressResilience:Math.round(30+pseudo(seed,12)*65),currentLoad:{concentration:0,morale:0,fatigue:0,availability:true,performancePct:100,mediaPressure:0,socialSupport:0},publicProfile:'known'};}
function addActor(world:World,state:SocialWorldState,club:Club|undefined,role:SocialActorRole,index:number):void{const key=`${role}-${club?.id??'global'}-${index}`;if(state.actors.has(key))return;const seed=hash(key);const personId=`person-${key}`;const life=humanLifeState(world);const kind:LifePerson['kind']=role==='journalist'?'journalist':role==='supporterLeader'?'supporter':role==='manager'?'manager':'staff';if(!life.people.has(personId))life.people.set(personId,makePerson(personId,names[Math.floor(pseudo(seed,1)*names.length)],kind,club?.id,seed));if(!life.profiles.has(personId))life.profiles.set(personId,makeProfile(personId,seed));state.actors.set(key,{id:key,role,clubId:club?.id,personId,influence:Math.round(35+pseudo(seed,2)*60),credibility:Math.round(35+pseudo(seed,3)*60),stress:Math.round(15+pseudo(seed,4)*35),relationshipWithClub:Math.round(45+pseudo(seed,5)*45)});}

export function socialWorldState(world:World):SocialWorldState{let s=states.get(world);if(!s){s={actors:new Map()};states.set(world,s);}for(const club of world.clubs){addActor(world,s,club,'manager',0);addActor(world,s,club,'assistant',0);addActor(world,s,club,'physio',0);addActor(world,s,club,'director',0);addActor(world,s,club,'supporterLeader',0);}for(let i=0;i<6;i++)addActor(world,s,undefined,'journalist',i);return s;}

function managerEvent(world:World,a:SocialActor,date:string):void{if(worldRandom(world,'humanLife',`social:${date}:${a.id}:manager-event`)>.004)return;a.stress=clamp(a.stress+(worldRandom(world,'humanLife',`social:${date}:${a.id}:manager-stress`)-.35)*10);const high=a.stress>70;emitWorldEvent(world,{type:'PersonalLifeEvent',date,actorIds:[a.personId],clubIds:a.clubId?[a.clubId]:[],importance:high?3:1,summary:high?'Treinador demonstra desgaste fora do campo':'Treinador participa de compromisso pessoal',payload:{type:high?'managerStress':'managerRoutine',severity:Math.round(a.stress/12),publicity:high?45:12,description:high?'Carga profissional e pessoal aumentou o desgaste do treinador.':'Compromisso cotidiano sem impacto esportivo relevante.'}});}
function staffEvent(world:World,a:SocialActor,date:string):void{if(worldRandom(world,'humanLife',`social:${date}:${a.id}:staff-event`)>.0025)return;const family=worldRandom(world,'humanLife',`social:${date}:${a.id}:staff-family`)<.6;emitWorldEvent(world,{type:'PersonalLifeEvent',date,actorIds:[a.personId],clubIds:a.clubId?[a.clubId]:[],importance:family?2:1,summary:family?'Membro da comissão precisa ajustar rotina familiar':'Staff participa de atividade externa',payload:{type:family?'staffFamilyMatter':'staffPublicEvent',severity:family?4:2,publicity:family?5:20,description:family?'Questão familiar altera pontualmente a disponibilidade do profissional.':'Atividade externa amplia sua rede de contatos.'}});}
function journalistEvent(world:World,a:SocialActor,date:string):void{if(worldRandom(world,'media',`social:${date}:${a.id}:journalist-event`)>.006)return;const clubs=world.clubs.filter(c=>worldRandom(world,'media',`social:${date}:${a.id}:club:${c.id}`)<.22).slice(0,2);if(!clubs.length)return;const speculative=worldRandom(world,'media',`social:${date}:${a.id}:speculative`)>(a.credibility/120);emitWorldEvent(world,{type:'MediaStoryPublished',date,actorIds:[a.personId],clubIds:clubs.map(c=>c.id),importance:speculative?2:1,summary:speculative?'Coluna publica bastidor ainda não confirmado':'Setorista publica informação de bastidor',payload:{sourceActorId:a.personId,credibility:a.credibility,speculative}});}
function supporterEvent(world:World,a:SocialActor,date:string):void{if(worldRandom(world,'humanLife',`social:${date}:${a.id}:supporter-event`)>.003)return;const mood=worldRandom(world,'humanLife',`social:${date}:${a.id}:supporter-mood`)<.5?'support':'criticism';emitWorldEvent(world,{type:'SupporterMoodChanged',date,actorIds:[a.personId],clubIds:a.clubId?[a.clubId]:[],importance:2,summary:mood==='support'?'Liderança de torcida demonstra apoio ao clube':'Grupo de torcedores aumenta cobrança pública',payload:{direction:mood==='support'?-2:3,influence:a.influence}});}

export function tickSocialWorld(world:World,date:string):void{const s=socialWorldState(world);if(s.lastTick===date)return;s.lastTick=date;for(const actor of s.actors.values()){if(actor.role==='manager')managerEvent(world,actor,date);else if(actor.role==='journalist')journalistEvent(world,actor,date);else if(actor.role==='supporterLeader')supporterEvent(world,actor,date);else staffEvent(world,actor,date);}}
export function snapshotSocialWorld(world:World):SocialWorldSnapshot{const s=socialWorldState(world);return{actors:[...s.actors.entries()].map(([k,v])=>[k,{...v}]),lastTick:s.lastTick};}
export function restoreSocialWorld(world:World,snapshot?:SocialWorldSnapshot):void{if(!snapshot)return;states.set(world,{actors:new Map(snapshot.actors.map(([k,v])=>[k,{...v}])),lastTick:snapshot.lastTick});}
