import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { managerByClub } from './manager-character';
import { managerProfile } from './manager-interactions';
import { clubGovernance } from './club-governance';
import { supporterCulture } from './club-supporter-culture-v1';
import { sportNewsCallbacks, type SportNewsCallback } from './sport-news-memory-v1';
import type { SportNewsArticle, SportNewsCategory, SportNewsIssue } from './sport-news-weekly-v1';

const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const unique=(xs:string[])=>[...new Set(xs.filter(Boolean))];

type ConsequenceProfile={media:number;managerStress:number;managerReputation:number;boardConfidence:number;fanApproval:number;fanPatience:number;fanVolatility:number;fanExpectation:number;playerMorale:number};
const profiles:Record<SportNewsCallback['kind'],ConsequenceProfile>={
  'repeat-final':{media:4,managerStress:3,managerReputation:1,boardConfidence:0,fanApproval:0,fanPatience:-2,fanVolatility:4,fanExpectation:2,playerMorale:2},
  'revenge':{media:3,managerStress:2,managerReputation:0,boardConfidence:0,fanApproval:0,fanPatience:-1,fanVolatility:4,fanExpectation:1,playerMorale:2},
  'manager-return':{media:4,managerStress:5,managerReputation:1,boardConfidence:-1,fanApproval:0,fanPatience:-1,fanVolatility:3,fanExpectation:2,playerMorale:0},
  'transfer-saga':{media:3,managerStress:1,managerReputation:0,boardConfidence:0,fanApproval:-1,fanPatience:-1,fanVolatility:2,fanExpectation:1,playerMorale:-3},
  'record-echo':{media:2,managerStress:1,managerReputation:1,boardConfidence:1,fanApproval:2,fanPatience:1,fanVolatility:1,fanExpectation:1,playerMorale:4},
  'reunion':{media:2,managerStress:2,managerReputation:1,boardConfidence:0,fanApproval:0,fanPatience:0,fanVolatility:2,fanExpectation:1,playerMorale:1},
  'historical-echo':{media:1,managerStress:1,managerReputation:0,boardConfidence:0,fanApproval:0,fanPatience:0,fanVolatility:1,fanExpectation:0,playerMorale:0}
};
function categoryFor(kind:SportNewsCallback['kind']):SportNewsCategory{if(kind==='manager-return')return'manager';if(kind==='transfer-saga')return'transfer';if(kind==='record-echo')return'record';return'history'}
function headlineFor(cb:SportNewsCallback){if(cb.kind==='repeat-final')return'A decisão de hoje reabre uma página antiga';if(cb.kind==='revenge')return'Velhos adversários voltam a acertar contas';if(cb.kind==='manager-return')return'O passado volta a cercar o treinador';if(cb.kind==='transfer-saga')return'Uma velha novela reaparece no mercado';if(cb.kind==='record-echo')return'O arquivo coloca a marca atual em perspectiva';if(cb.kind==='reunion')return'Um reencontro que o arquivo não esqueceu';return'O passado volta a explicar o presente'}
function questionFor(cb:SportNewsCallback){if(cb.kind==='repeat-final')return'Quanto aquela decisão antiga pesa na preparação para este novo confronto?';if(cb.kind==='revenge')return'Existe sentimento de revanche depois do que aconteceu no passado?';if(cb.kind==='manager-return')return'O reencontro com esse capítulo da sua carreira muda emocionalmente esta semana?';if(cb.kind==='transfer-saga')return'A repercussão daquela negociação antiga influencia a postura das partes hoje?';if(cb.kind==='record-echo')return'Você sente que o peso da marca histórica pode afetar o jogador nos próximos jogos?';if(cb.kind==='reunion')return'Como administrar um reencontro que carrega uma história anterior?';return'O que mudou desde aquela edição do Sport News e o que ainda permanece igual?'}
function callbackArticle(issue:SportNewsIssue,cb:SportNewsCallback):SportNewsArticle{const p=profiles[cb.kind],importance=clamp(45+cb.source.score*.52,45,94);return{id:`sn-memory-${issue.id}-${cb.source.issueId}-${cb.kind}-${Math.abs(cb.source.headline.length)}`,page:3,category:categoryFor(cb.kind),headline:headlineFor(cb),deck:`O Sport News recupera a edição #${cb.source.edition}, publicada em ${cb.source.date}.`,body:`${cb.summary} A lembrança volta à pauta porque o contexto atual reacendeu a ligação entre os personagens envolvidos. Pergunta de coletiva: “${questionFor(cb)}”`,importance,sentiment:cb.kind==='record-echo'?'positive':'mixed',clubIds:[...cb.source.clubIds],playerIds:[...cb.source.playerIds],managerIds:[...cb.source.managerIds],competitionIds:[...cb.source.competitionIds],sourceEventIds:[],effects:cb.source.clubIds.map(clubId=>({target:'club' as const,entityId:clubId,pressure:p.media,reputation:p.boardConfidence,morale:p.fanApproval}))}}
function runtimeClubIds(w:World,ids:string[]){const set=new Set(w.clubs.map(c=>c.id));return unique(ids).filter(id=>set.has(id))}
function applyConsequences(w:World,cb:SportNewsCallback){const p=profiles[cb.kind],clubs=runtimeClubIds(w,cb.source.clubIds);for(const clubId of clubs){const g=clubGovernance(w,clubId),fans=supporterCulture(w,clubId),m=managerProfile(w,clubId);g.mediaPressure=clamp(g.mediaPressure+p.media);g.managerConfidence=clamp(g.managerConfidence+p.boardConfidence);g.fanApproval=clamp(g.fanApproval+p.fanApproval);fans.patience=clamp(fans.patience+p.fanPatience);fans.volatility=clamp(fans.volatility+p.fanVolatility);fans.expectation=clamp(fans.expectation+p.fanExpectation);if(m){m.stress=clamp(m.stress+p.managerStress);m.reputation=clamp(m.reputation+p.managerReputation)}}for(const playerId of unique(cb.source.playerIds)){const player=w.clubs.flatMap(c=>c.players).find(x=>x.id===playerId);if(player)player.morale=clamp(player.morale+p.playerMorale)}return clubs}
function emitCallback(w:World,issue:SportNewsIssue,cb:SportNewsCallback,clubs:string[]){const currentManagers=clubs.map(id=>managerByClub(w,id)?.id).filter((x):x is string=>!!x);emitWorldEvent(w,{type:'MediaStoryPublished',date:issue.date,clubIds:clubs,playerIds:unique(cb.source.playerIds),actorIds:unique([...cb.source.managerIds,...currentManagers]),importance:cb.source.score>=90?4:cb.source.score>=65?3:2,tags:['sport-news','historical-memory',cb.kind],summary:`Sport News recupera a edição #${cb.source.edition}: ${cb.source.headline}`,payload:{currentIssueId:issue.id,memoryKind:cb.kind,sourceIssueId:cb.source.issueId,sourceEdition:cb.source.edition,sourceDate:cb.source.date,sourceHeadline:cb.source.headline,score:cb.source.score,reasons:cb.source.reasons}})}
export function enrichSportNewsWithHistoricalMemory(w:World,issue:SportNewsIssue){if((issue as any).__memoryEnriched)return issue;const competitionIds=unique(issue.pages.flatMap(p=>p.articles.flatMap(a=>a.competitionIds))),callbacks=sportNewsCallbacks(w,{date:issue.date,season:issue.season,clubIds:issue.featuredClubIds,playerIds:issue.featuredPlayerIds,managerIds:issue.featuredManagerIds,competitionIds,query:issue.coverHeadline,limit:8,minAgeDays:28});const chosen:SportNewsCallback[]=[],seen=new Set<string>();for(const cb of callbacks){if(cb.source.score<42)continue;const key=`${cb.kind}:${cb.source.issueId}:${cb.source.headline}`;if(seen.has(key))continue;seen.add(key);chosen.push(cb);if(chosen.length>=3)break}const articles=chosen.map(cb=>callbackArticle(issue,cb));if(articles.length)issue.pages[2].articles=[...articles,...issue.pages[2].articles].sort((a,b)=>b.importance-a.importance).slice(0,10);for(const cb of chosen){const clubs=applyConsequences(w,cb);emitCallback(w,issue,cb,clubs)}issue.featuredClubIds=unique(issue.pages.flatMap(p=>p.articles.flatMap(a=>a.clubIds))).slice(0,16);issue.featuredPlayerIds=unique(issue.pages.flatMap(p=>p.articles.flatMap(a=>a.playerIds))).slice(0,16);issue.featuredManagerIds=unique(issue.pages.flatMap(p=>p.articles.flatMap(a=>a.managerIds))).slice(0,12);(issue as any).__memoryEnriched=true;return issue}
