import type { World } from './engine';
import { latestSportNews } from './sport-news-weekly-v2';
import { sportNewsArchive, sportNewsArchiveIssue, sportNewsSeasonSummary, type SportNewsArchiveFilter } from './sport-news-archive-v1';
import type { SportNewsIssue, SportNewsArticle } from './sport-news-weekly-v1';
import { footballDataSnapshot } from './world-football-data-v1';

const esc=(s:string)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const nameFor=(w:World,id:string)=>{const f=footballDataSnapshot(w);return f.clubs.find(x=>x.id===id)?.name??f.nationalTeams.find(x=>x.id===id)?.name??w.clubs.find(x=>x.id===id)?.name??id};
const label:Record<SportNewsArticle['category'],string>={headline:'Destaque',competition:'Competições',international:'Internacional',player:'Jogadores',manager:'Treinadores',injury:'Departamento médico',transfer:'Mercado',tactics:'Tática',history:'História',record:'Recordes',governance:'Bastidores',supporters:'Torcida'};

function articleCard(w:World,a:SportNewsArticle){const entities=[...a.clubIds,...a.playerIds,...a.managerIds].slice(0,5).map(id=>nameFor(w,id));return `<article class="sn-article sn-${a.sentiment}"><div class="sn-kicker">${esc(label[a.category])}</div><h3>${esc(a.headline)}</h3><p class="sn-deck">${esc(a.deck)}</p><p>${esc(a.body)}</p>${entities.length?`<div class="sn-entities">${entities.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}</article>`}

export function renderSportNewsIssue(w:World,issue?:SportNewsIssue){const x=issue??latestSportNews(w);if(!x)return '<section class="sport-news-empty"><h2>Sport News</h2><p>A primeira edição será publicada no domingo.</p></section>';return `<section class="sport-news-paper"><header class="sn-masthead"><div><span>SPORT NEWS</span><small>EDIÇÃO ${x.edition}</small></div><div><time>${esc(x.date)}</time><small>${esc(x.weekStart)} — ${esc(x.weekEnd)}</small></div></header><section class="sn-cover"><span>CAPA</span><h1>${esc(x.coverHeadline)}</h1></section>${x.pages.map(p=>`<section class="sn-page" data-page="${p.number}"><header><span>PÁGINA ${p.number}</span><h2>${esc(p.title)}</h2></header><div class="sn-grid">${p.articles.map(a=>articleCard(w,a)).join('')}</div></section>`).join('')}<footer class="sn-footer"><span>Sport News · arquivo histórico da temporada ${x.season}</span><span>${x.pages.reduce((n,p)=>n+p.articles.length,0)} matérias</span></footer></section>`}

export function renderSportNewsArchive(w:World,filter:SportNewsArchiveFilter={}){const entries=sportNewsArchive(w,filter).sort((a,b)=>b.date.localeCompare(a.date)),season=filter.season??entries[0]?.season,summary=season!==undefined?sportNewsSeasonSummary(w,season):undefined;return `<section class="sport-news-archive"><header class="sn-archive-head"><div><span>SPORT NEWS</span><h1>Arquivo</h1></div><small>${entries.length} edições encontradas</small></header>${summary?`<div class="sn-summary"><article><span>Edições</span><strong>${summary.editions}</strong></article><article><span>Matérias</span><strong>${summary.articles}</strong></article><article><span>Período</span><strong>${esc(summary.firstDate)} — ${esc(summary.lastDate)}</strong></article></div>`:''}<div class="sn-archive-list">${entries.map(e=>`<article data-issue-id="${esc(e.id)}"><time>${esc(e.date)}</time><span>EDIÇÃO ${e.edition}</span><h3>${esc(e.coverHeadline)}</h3><small>${e.articleCount} matérias · temporada ${e.season}</small></article>`).join('')||'<p>Nenhuma edição encontrada para os filtros selecionados.</p>'}</div></section>`}

export function renderSportNewsArchiveIssue(w:World,idOrEdition:string|number){const entry=sportNewsArchiveIssue(w,idOrEdition);if(!entry)return '<section class="sport-news-empty"><h2>Sport News</h2><p>Edição não encontrada no arquivo.</p></section>';const issue=latestSportNews(w)?.id===entry.id?latestSportNews(w):undefined;if(issue)return renderSportNewsIssue(w,issue);return `<section class="sport-news-paper sn-archived"><header class="sn-masthead"><div><span>SPORT NEWS</span><small>EDIÇÃO ${entry.edition}</small></div><div><time>${esc(entry.date)}</time><small>ARQUIVO HISTÓRICO</small></div></header><section class="sn-cover"><span>CAPA</span><h1>${esc(entry.coverHeadline)}</h1></section>${entry.pageHeadlines.map((heads,i)=>`<section class="sn-page" data-page="${i+1}"><header><span>PÁGINA ${i+1}</span><h2>${i===0?'Capa & Panorama':i===1?'Competições & Destaques':'Bastidores, Memória & Pressão'}</h2></header><div class="sn-archive-headlines">${heads.map(h=>`<article><h3>${esc(h)}</h3></article>`).join('')}</div></section>`).join('')}</section>`}

export const SPORT_NEWS_CSS=`
.sport-news-paper,.sport-news-archive{max-width:1180px;margin:0 auto;background:#f5f0e7;color:#171717;font-family:Georgia,'Times New Roman',serif;box-shadow:0 18px 50px rgba(0,0,0,.18)}
.sn-masthead,.sn-archive-head{display:flex;justify-content:space-between;align-items:flex-end;padding:24px 30px;border-bottom:5px solid #171717}.sn-masthead>div:first-child span,.sn-archive-head span{font:900 42px/1 Arial,sans-serif;letter-spacing:-2px}.sn-masthead small,.sn-archive-head small{display:block;font:700 11px Arial,sans-serif;letter-spacing:1.4px;margin-top:7px}.sn-cover{padding:34px 30px 28px;border-bottom:1px solid #999}.sn-cover>span,.sn-page header span,.sn-kicker{font:800 10px Arial,sans-serif;letter-spacing:1.6px}.sn-cover h1{font-size:48px;line-height:1.02;max-width:900px;margin:12px 0 0}.sn-page{padding:28px 30px;border-bottom:1px solid #aaa}.sn-page header{display:flex;gap:20px;align-items:baseline;border-bottom:2px solid #171717;margin-bottom:20px}.sn-page h2{font-size:24px;margin:0 0 9px}.sn-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 28px}.sn-article{padding:0 0 24px;margin:0 0 22px;border-bottom:1px solid #bbb}.sn-article h3{font-size:27px;line-height:1.08;margin:7px 0}.sn-deck{font-weight:700}.sn-article p{font-size:15px;line-height:1.52}.sn-entities{display:flex;gap:6px;flex-wrap:wrap}.sn-entities span{font:700 10px Arial,sans-serif;border:1px solid #999;padding:4px 7px}.sn-negative .sn-kicker{font-weight:900}.sn-footer{display:flex;justify-content:space-between;padding:16px 30px;font:700 10px Arial,sans-serif;letter-spacing:.8px}.sn-summary{display:grid;grid-template-columns:repeat(3,1fr);padding:20px 30px;border-bottom:1px solid #aaa}.sn-summary article{display:flex;flex-direction:column}.sn-summary span{font:700 10px Arial,sans-serif;text-transform:uppercase}.sn-summary strong{font-size:22px;margin-top:5px}.sn-archive-list{padding:10px 30px 30px}.sn-archive-list article{display:grid;grid-template-columns:110px 100px 1fr auto;gap:12px;align-items:center;padding:18px 0;border-bottom:1px solid #aaa}.sn-archive-list time,.sn-archive-list span,.sn-archive-list small{font:700 10px Arial,sans-serif}.sn-archive-list h3{margin:0;font-size:21px}.sn-archive-headlines{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.sn-archive-headlines article{border-bottom:1px solid #aaa}.sn-archive-headlines h3{font-size:21px}.sport-news-empty{padding:30px}.sport-news-empty h2{margin-top:0}@media(max-width:760px){.sn-grid,.sn-summary,.sn-archive-headlines{grid-template-columns:1fr}.sn-cover h1{font-size:34px}.sn-masthead>div:first-child span,.sn-archive-head span{font-size:30px}.sn-archive-list article{grid-template-columns:1fr}.sn-masthead{align-items:flex-start;gap:20px}.sn-masthead,.sn-archive-head{flex-direction:column}}
`;
