import type { World } from './engine';
import { emitWorldEvent } from './event-bus';
import { clubTechnicalStaff, technicalStaffMember, type TechnicalStaffMember, type TechnicalStaffRole } from './technical-staff';
export type StaffLicense='none'|'nationalC'|'nationalB'|'nationalA'|'continentalA'|'continentalPro'|'medicalSpecialist'|'sportsScience'|'performanceAnalysis'|'nutritionSpecialist'|'psychologySpecialist';
export type StaffResponsibility='training'|'individualDevelopment'|'setPieces'|'opposition'|'fitness'|'recovery'|'medical'|'nutrition'|'psychology'|'youthIntegration'|'loans'|'recruitment'|'squadLiaison'|'pressSupport';
export type StaffContract={staffId:string;clubId:string;startDate:string;endDate:string;weeklySalary:number;releaseClause?:number;role:TechnicalStaffRole;promisedRole?:TechnicalStaffRole;renewalStatus:'none'|'talks'|'agreed'|'rejected'|'expiring';security:number};
export type StaffCareerProfile={staffId:string;licenses:StaffLicense[];studying?:StaffLicense;studyProgress:number;leadershipReadiness:number;managerialInterest:number;preferredResponsibilities:StaffResponsibility[];delegatedResponsibilities:StaffResponsibility[];promotionPressure:number;lastPromotion?:string;conflicts:{withId:string;severity:number;cause:string;started:string;resolved?:string}[]};
type State={contracts:Map<string,StaffContract>;profiles:Map<string,StaffCareerProfile>;lastTick?:string};const states=new WeakMap<World,State>();const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const prefs:Partial<Record<TechnicalStaffRole,StaffResponsibility[]>>={assistantManager:['training','individualDevelopment','pressSupport'],deputyManager:['training','individualDevelopment','pressSupport'],technicalAssistant:['training','individualDevelopment'],setPieceCoach:['setPieces'],oppositionAnalyst:['opposition'],performanceAnalyst:['opposition'],fitnessCoach:['fitness'],strengthConditioningCoach:['fitness'],physiotherapist:['recovery'],rehabSpecialist:['recovery'],clubDoctor:['medical'],nutritionist:['nutrition'],sportsPsychologist:['psychology'],mentalCoach:['psychology'],youthDevelopmentCoach:['youthIntegration'],loanManager:['loans'],chiefScout:['recruitment'],recruitmentAnalyst:['recruitment'],squadCoordinator:['squadLiaison'],playerLiaison:['squadLiaison']};
function licenseFor(s:TechnicalStaffMember):StaffLicense{if(s.role==='clubDoctor'||s.role==='physiotherapist'||s.role==='rehabSpecialist')return'medicalSpecialist';if(s.role==='nutritionist')return'nutritionSpecialist';if(s.role==='sportsPsychologist'||s.role==='mentalCoach')return'psychologySpecialist';if(['performanceAnalyst','oppositionAnalyst','videoAnalyst'].includes(s.role))return'performanceAnalysis';if(s.role==='sportsScientist'||s.role==='fitnessCoach'||s.role==='strengthConditioningCoach')return'sportsScience';return s.qualifications>=82?'continentalPro':s.qualifications>=70?'continentalA':s.qualifications>=58?'nationalA':s.qualifications>=45?'nationalB':'nationalC'}
function ensure(world:World,s:TechnicalStaffMember,state:State){if(!state.contracts.has(s.id))state.contracts.set(s.id,{staffId:s.id,clubId:s.clubId,startDate:`${world.season}-07-01`,endDate:s.contractEnd,weeklySalary:s.salaryWeekly,role:s.role,renewalStatus:'none',security:65});if(!state.profiles.has(s.id))state.profiles.set(s.id,{staffId:s.id,licenses:[licenseFor(s)],studyProgress:0,leadershipReadiness:clamp(s.skills.manManagement*.35+s.skills.tactics*.3+s.personality.communication*.2+s.experience*.15),managerialInterest:s.ambitionToLead,preferredResponsibilities:prefs[s.role]??['training'],delegatedResponsibilities:[],promotionPressure:0,conflicts:[]})}
export function staffCareerState(world:World){let st=states.get(world);if(!st){st={contracts:new Map(),profiles:new Map()};states.set(world,st)}for(const c of world.clubs)for(const s of clubTechnicalStaff(world,c.id))ensure(world,s,st);return st}
export function staffCareerProfile(world:World,id:string){const s=technicalStaffMember(world,id);if(s)ensure(world,s,staffCareerState(world));return staffCareerState(world).profiles.get(id)}
export function staffContract(world:World,id:string){const s=technicalStaffMember(world,id);if(s)ensure(world,s,staffCareerState(world));return staffCareerState(world).contracts.get(id)}
export function delegateStaffResponsibility(world:World,id:string,r:StaffResponsibility,date:string){const p=staffCareerProfile(world,id),s=technicalStaffMember(world,id);if(!p||!s)return false;for(const x of staffCareerState(world).profiles.values())x.delegatedResponsibilities=x.delegatedResponsibilities.filter(v=>v!==r);p.delegatedResponsibilities.push(r);s.jobSatisfaction=clamp(s.jobSatisfaction+(p.preferredResponsibilities.includes(r)?3:-1));emitWorldEvent(world,{type:'StaffResponsibilityDelegated',date,actorIds:[id],clubIds:[s.clubId],importance:1,summary:`${s.name} recebeu responsabilidade por ${r}.`,payload:{staffId:id,responsibility:r}});return true}
export function renewStaffContract(world:World,id:string,date:string,years=2,raise=.08){const c=staffContract(world,id),s=technicalStaffMember(world,id);if(!c||!s)return false;const acceptance=clamp(s.jobSatisfaction*.4+s.clubLoyalty*.25+(100-s.personality.ambition)*.15+c.security*.2);if(acceptance<42){c.renewalStatus='rejected';return false}c.renewalStatus='agreed';c.startDate=date;c.endDate=`${Number(date.slice(0,4))+years}-06-30`;c.weeklySalary=Math.round(c.weeklySalary*(1+raise));s.contractEnd=c.endDate;s.salaryWeekly=c.weeklySalary;s.jobSatisfaction=clamp(s.jobSatisfaction+4);return true}
export function promoteStaff(world:World,id:string,newRole:TechnicalStaffRole,date:string){const s=technicalStaffMember(world,id),p=staffCareerProfile(world,id),c=staffContract(world,id);if(!s||!p||!c)return false;const old=s.role;s.role=newRole;c.role=newRole;c.weeklySalary=Math.round(c.weeklySalary*1.18);s.salaryWeekly=c.weeklySalary;s.reputation=clamp(s.reputation+2);s.jobSatisfaction=clamp(s.jobSatisfaction+12);p.promotionPressure=0;p.lastPromotion=date;emitWorldEvent(world,{type:'StaffPromoted',date,actorIds:[id],clubIds:[s.clubId],importance:2,summary:`${s.name} foi promovido de ${old} para ${newRole}.`,payload:{staffId:id,oldRole:old,newRole}});return true}
export function staffHeadCoachCandidates(world:World,clubId?:string){const st=staffCareerState(world);return[...st.profiles.values()].map(p=>({profile:p,staff:technicalStaffMember(world,p.staffId)})).filter(x=>x.staff&&(!clubId||x.staff.clubId===clubId)&&x.profile.managerialInterest>=55&&x.profile.leadershipReadiness>=55).sort((a,b)=>b.profile.leadershipReadiness-a.profile.leadershipReadiness)}
function evolve(world:World,s:TechnicalStaffMember,date:string){const p=staffCareerProfile(world,s.id)!,c=staffContract(world,s.id)!;p.leadershipReadiness=clamp(p.leadershipReadiness*.97+s.skills.manManagement*.012+s.skills.tactics*.008+s.experience*.01);p.promotionPressure=clamp(p.promotionPressure+(p.managerialInterest>65?0.08:0)+(s.reputation>72?0.05:0)-(p.lastPromotion?0.02:0));if(!p.studying&&s.qualifications<88&&Math.random()<.0015){p.studying=['assistantManager','deputyManager','technicalAssistant','firstTeamCoach'].includes(s.role)?'continentalPro':licenseFor(s);p.studyProgress=0}if(p.studying){p.studyProgress+=.35;if(p.studyProgress>=100){if(!p.licenses.includes(p.studying))p.licenses.push(p.studying);p.studying=undefined;p.studyProgress=0;s.qualifications=clamp(s.qualifications+5)}}const end=new Date(c.endDate+'T00:00:00'),now=new Date(date+'T00:00:00'),days=(end.getTime()-now.getTime())/86400000;if(days<180&&c.renewalStatus==='none')c.renewalStatus='expiring';if(days<90&&s.jobSatisfaction>55&&c.renewalStatus==='expiring')c.renewalStatus='talks';if(days<45&&c.renewalStatus==='talks')renewStaffContract(world,s.id,date,2,.06+(s.reputation/1000));}
function conflicts(world:World,clubId:string,date:string){const staff=clubTechnicalStaff(world,clubId),st=staffCareerState(world);for(let i=0;i<staff.length;i++)for(let j=i+1;j<staff.length;j++){const a=staff[i],b=staff[j],pa=st.profiles.get(a.id)!,pb=st.profiles.get(b.id)!;if(pa.conflicts.some(c=>c.withId===b.id&&!c.resolved))continue;const risk=(a.personality.ego+b.personality.ego+a.personality.ambition+b.personality.ambition-a.staffHarmony-b.staffHarmony)/400;if(risk>.22&&Math.random()<risk*.001){const cause=Math.abs(a.philosophy.tacticalRigidity-b.philosophy.tacticalRigidity)>35?'divergência de metodologia':Math.abs(a.philosophy.playerCare-b.philosophy.playerCare)>35?'gestão de jogadores':'disputa por influência',severity=Math.round(clamp(25+risk*80));pa.conflicts.push({withId:b.id,severity,cause,started:date});pb.conflicts.push({withId:a.id,severity,cause,started:date});a.jobSatisfaction=clamp(a.jobSatisfaction-severity*.05);b.jobSatisfaction=clamp(b.jobSatisfaction-severity*.05);emitWorldEvent(world,{type:'StaffConflict',date,actorIds:[a.id,b.id],clubIds:[clubId],importance:severity>60?3:2,summary:`Surgiu tensão entre ${a.name} e ${b.name}: ${cause}.`,payload:{severity,cause}})}}}
export function tickStaffCareer(world:World,date:string){const st=staffCareerState(world);if(st.lastTick===date)return;for(const c of world.clubs){for(const s of clubTechnicalStaff(world,c.id))evolve(world,s,date);conflicts(world,c.id,date)}st.lastTick=date}
export function snapshotStaffCareer(world:World){const s=staffCareerState(world);return{contracts:[...s.contracts],profiles:[...s.profiles],lastTick:s.lastTick}}
export function restoreStaffCareer(world:World,x:ReturnType<typeof snapshotStaffCareer>){states.set(world,{contracts:new Map(x.contracts),profiles:new Map(x.profiles),lastTick:x.lastTick})}
