import { applyTacticPreset, tacticPresets, teamStrength, updateClubTactics, type Club, type Mentality, type PassingStyle, type TransitionStyle } from './engine';

export function renderTactics(club: Club, clubOptions: string): string {
  const t = club.tactics;
  const s = teamStrength(club);
  const mentalityLabel: Record<Mentality,string> = { defensive:'Defensiva', balanced:'Equilibrada', positive:'Positiva', attacking:'Ofensiva' };
  const range = (id:string,label:string,value:number,low:string,high:string) => `<label class="range-row"><div><b>${label}</b><span>${low}</span></div><input id="${id}" type="range" min="0" max="100" value="${value}"><strong>${value}</strong><small>${high}</small></label>`;
  return `<header><div><span class="eyebrow">TÁTICAS · ${club.name.toUpperCase()}</span><h1>Modelo de jogo</h1><p>As instruções alteram posse, criação, risco, cartões e desgaste no motor.</p></div><select id="club-select">${clubOptions}</select></header>
  <section class="cards"><article class="card metric"><span>Ataque projetado</span><strong>${s.attack.toFixed(1)}</strong></article><article class="card metric"><span>Controle de meio</span><strong>${s.midfield.toFixed(1)}</strong></article><article class="card metric"><span>Solidez defensiva</span><strong>${s.defense.toFixed(1)}</strong></article><article class="card metric"><span>Mentalidade</span><strong>${mentalityLabel[t.mentality]}</strong></article></section>
  <div class="tactics-layout"><section class="card pitch-card"><div class="section-title"><h2>Estrutura base</h2><span>4-2-3-1</span></div><div class="mini-pitch"><span class="p gk">GK</span><span class="p rb">RB</span><span class="p cb1">CB</span><span class="p cb2">CB</span><span class="p lb">LB</span><span class="p dm">DM</span><span class="p cm">CM</span><span class="p am">AM</span><span class="p rw">RW</span><span class="p lw">LW</span><span class="p st">ST</span></div><div class="tactic-summary"><span>Ritmo <b>${t.tempo}</b></span><span>Pressão <b>${t.pressing}</b></span><span>Linha <b>${t.defensiveLine}</b></span><span>Largura <b>${t.width}</b></span></div></section>
  <section class="card tactic-controls"><div class="section-title"><h2>Instruções coletivas</h2><span>Impacto em tempo real</span></div><div class="preset-row">${Object.keys(tacticPresets).map(key=>`<button class="preset" data-preset="${key}">${key==='contraAtaque'?'Contra-ataque':key==='blocoBaixo'?'Bloco baixo':key[0].toUpperCase()+key.slice(1)}</button>`).join('')}</div><div class="control-grid"><label><span>Mentalidade</span><select id="mentality"><option value="defensive" ${t.mentality==='defensive'?'selected':''}>Defensiva</option><option value="balanced" ${t.mentality==='balanced'?'selected':''}>Equilibrada</option><option value="positive" ${t.mentality==='positive'?'selected':''}>Positiva</option><option value="attacking" ${t.mentality==='attacking'?'selected':''}>Ofensiva</option></select></label><label><span>Estilo de passe</span><select id="passing"><option value="short" ${t.passingStyle==='short'?'selected':''}>Curto</option><option value="mixed" ${t.passingStyle==='mixed'?'selected':''}>Misto</option><option value="direct" ${t.passingStyle==='direct'?'selected':''}>Direto</option></select></label><label><span>Transição</span><select id="transition"><option value="hold" ${t.transition==='hold'?'selected':''}>Manter posse</option><option value="balanced" ${t.transition==='balanced'?'selected':''}>Equilibrada</option><option value="counter" ${t.transition==='counter'?'selected':''}>Contra-atacar</option></select></label></div><div class="ranges">${range('tempo','Ritmo',t.tempo,'Paciente','Muito rápido')}${range('pressing','Pressão',t.pressing,'Recuada','Sufocante')}${range('line','Linha defensiva',t.defensiveLine,'Muito baixa','Muito alta')}${range('width','Largura',t.width,'Muito estreita','Muito aberta')}</div></section></div>`;
}

export function bindTactics(club: Club, rerender: () => void): void {
  document.querySelectorAll<HTMLButtonElement>('.preset').forEach(btn=>btn.addEventListener('click',()=>{applyTacticPreset(club,btn.dataset.preset as keyof typeof tacticPresets);rerender();}));
  document.querySelector<HTMLSelectElement>('#mentality')?.addEventListener('change',e=>{updateClubTactics(club,{mentality:(e.target as HTMLSelectElement).value as Mentality});rerender();});
  document.querySelector<HTMLSelectElement>('#passing')?.addEventListener('change',e=>{updateClubTactics(club,{passingStyle:(e.target as HTMLSelectElement).value as PassingStyle});rerender();});
  document.querySelector<HTMLSelectElement>('#transition')?.addEventListener('change',e=>{updateClubTactics(club,{transition:(e.target as HTMLSelectElement).value as TransitionStyle});rerender();});
  const map = {tempo:'tempo',pressing:'pressing',line:'defensiveLine',width:'width'} as const;
  Object.entries(map).forEach(([id,key])=>document.querySelector<HTMLInputElement>(`#${id}`)?.addEventListener('change',e=>{updateClubTactics(club,{[key]:Number((e.target as HTMLInputElement).value)});rerender();}));
}
