import type { Club, World } from './engine';
import { availableTechnicalStaff, clubTechnicalStaff, dismissTechnicalStaff, hireTechnicalStaff, staffDepartmentEffects, technicalStaffState, type TechnicalStaffMember, type TechnicalStaffRole } from './technical-staff';
import { dailyCalendar } from './daily-simulation';
import { managerByClub } from './manager-character';

const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const roleLabel:Record<TechnicalStaffRole,string>={assistantManager:'Auxiliar técnico',firstTeamCoach:'Treinador de campo',fitnessCoach:'Preparador físico',goalkeepingCoach:'Treinador de goleiros',setPieceCoach:'Especialista em bola parada',performanceAnalyst:'Analista de desempenho',sportsScientist:'Cientista do esporte',physiotherapist:'Fisioterapeuta',clubDoctor:'Médico',sportsPsychologist:'Psicólogo esportivo',youthCoach:'Treinador de base',recruitmentAnalyst:'Analista de recrutamento'};
const skill=(s:TechnicalStaffMember)=>Math.max(...Object.values(s.skills));
const row=(s:TechnicalStaffMember)=>`<tr><td><b>${esc(s.name)}</b><small>${esc(s.nationality)} · ${s.age} anos</small></td><td>${esc(roleLabel[s.role])}</td><td>${s.reputation}</td><td>${skill(s)}</td><td>${s.managerCompatibility.toFixed(0)}</td><td>${s.staffHarmony.toFixed(0)}</td><td>${s.jobSatisfaction.toFixed(0)}</td><td>R$ ${s.salaryWeekly.toLocaleString('pt-BR')}</td><td><button class="staff-dismiss" data-staff="${s.id}">Dispensar</button></td></tr>`;
export function renderTechnicalStaff(world:World,club:Club){const staff=clubTechnicalStaff(world,club.id),effects=staffDepartmentEffects(world,club.id),free=availableTechnicalStaff(world).sort((a,b)=>b.reputation-a.reputation).slice(0,8),manager=managerByClub(world,club.id);return `<header><div><span class="eyebrow">COMISSÃO TÉCNICA · ${esc(club.name.toUpperCase())}</span><h1>Staff técnico e científico</h1><p>A comissão possui competências, personalidade, lealdade, carga, relação com o treinador e harmonia interna. Uma equipe forte não é apenas soma de atributos.</p></div></header><section class="cards"><article class="card metric"><span>Treino</span><strong>${effects.trainingQuality.toFixed(0)}</strong></article><article class="card metric"><span>Preparação física</span><strong>${effects.physicalPreparation.toFixed(0)}</strong></article><article class="card metric"><span>Departamento médico</span><strong>${effects.medicalQuality.toFixed(0)}</strong></article><article class="card metric"><span>Harmonia da comissão</span><strong>${effects.staffHarmony.toFixed(0)}</strong></article></section><section class="card"><div class="section-title"><h2>Comissão atual</h2><span>${staff.length} profissionais · treinador ${esc(manager?.name??'não definido')}</span></div><table><thead><tr><th>Profissional</th><th>Função</th><th>Rep.</th><th>Melhor competência</th><th>Compat. treinador</th><th>Harmonia</th><th>Satisfação</th><th>Salário/sem.</th><th></th></tr></thead><tbody>${staff.map(row).join('')}</tbody></table></section><section class="card"><div class="section-title"><h2>Mercado de staff</h2><span>profissionais disponíveis</span></div>${free.length?`<table><thead><tr><th>Profissional</th><th>Função</th><th>Rep.</th><th>Competência</th><th>Lealdade prévia</th><th></th></tr></thead><tbody>${free.map(s=>`<tr><td><b>${esc(s.name)}</b><small>${esc(s.nationality)}</small></td><td>${esc(roleLabel[s.role])}</td><td>${s.reputation}</td><td>${skill(s)}</td><td>${s.managerLoyalty}</td><td><button class="staff-hire" data-staff="${s.id}">Contratar</button></td></tr>`).join('')}</tbody></table>`:'<p>Não há profissionais livres relevantes neste momento.</p>'}</section>`;}
export function bindTechnicalStaff(world:World,club:Club,rerender:()=>void){const date=dailyCalendar(world).date,manager=managerByClub(world,club.id);document.querySelectorAll<HTMLButtonElement>('.staff-dismiss').forEach(b=>b.addEventListener('click',()=>{dismissTechnicalStaff(world,b.dataset.staff!,date,'reestruturação da comissão');rerender();}));document.querySelectorAll<HTMLButtonElement>('.staff-hire').forEach(b=>b.addEventListener('click',()=>{hireTechnicalStaff(world,b.dataset.staff!,club.id,date,manager?.id);rerender();}));technicalStaffState(world);}
