import type { World } from './engine';
import { emitWorldEvent, onWorldEvent } from './event-bus';
import { managerByClub, managerCharacterState } from './manager-character';
import { managerContract } from './manager-employment';

export type TechnicalStaffRole='assistantManager'|'firstTeamCoach'|'fitnessCoach'|'goalkeepingCoach'|'setPieceCoach'|'performanceAnalyst'|'sportsScientist'|'physiotherapist'|'clubDoctor'|'sportsPsychologist'|'youthCoach'|'recruitmentAnalyst';
export type StaffPersonality={discipline:number;empathy:number;ambition:number;loyalty:number;ego:number;adaptability:number;communication:number;conflictTolerance:number};
export type StaffSkills={coaching:number;tactics:number;technical:number;physical:number;goalkeeping:number;setPieces:number;analysis:number;medical:number;rehab:number;psychology:number;youth:number;recruitment:number;manManagement:number};
export type TechnicalStaffMember={id:string;clubId:string;name:string;age:number;nationality:string;role:TechnicalStaffRole;reputation:number;skills:StaffSkills;personality:StaffPersonality;salaryWeekly:number;contractEnd:string;managerId?:string;managerLoyalty:number;clubLoyalty:number;managerCompatibility:number;staffHarmony:number;workload:number;fatigue:number;stress:number;jobSatisfaction:number;ambitionToLead:number;status:'active'|'notice'|'freeAgent'|'retired';history:{date:string;type:string;summary:string;impact:number}[]};
export type StaffRelationship={a:string;b:string;trust:number;respect:number;friction:number;professionalSynergy:number;lastChanged?:string};
export type TechnicalStaffState={members:Map<string,TechnicalStaffMember>;relationships:Map<string,StaffRelationship>;clubStaff:Map<string,string[]>;lastTick?:string;wired:boolean};
export type TechnicalStaffSnapshot={members:[string,TechnicalStaffMember][];relationships:[string,StaffRelationship][];clubStaff:[string,string[]][];lastTick?:string};
const states=new WeakMap<World,TechnicalStaffState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return Math.abs(h>>>0)};
const pseudo=(s:string,o=0)=>{const x=Math.sin((hash(s)+o)*12.9898)*43758.5453;return x-Math.floor(x)};
const roles:TechnicalStaffRole[]=['assistantManager','firstTeamCoach','fitnessCoach','goalkeepingCoach','performanceAnalyst','sportsScientist','physiotherapist','clubDoctor','youthCoach'];
const first=['André','Bruno','Caio','Daniel','Eduardo','Felipe','Gustavo','Henrique','Igor','João','Lucas','Marcelo','Nicolas','Paulo','Rafael','Sérgio','Thiago','Vinícius'];
const last=['Almeida','Barbosa','Cardoso','Duarte','Ferreira','Gomes','Lima','Martins','Melo','Nogueira','Oliveira','Pereira','Ramos','Rocha','Silva','Souza','Teixeira'];
const countries=['Brasil','Argentina','Uruguai','Portugal','Espanha','Itália','Chile'];
const relKey=(a:string,b:string)=>[a,b].sort().join('|');
function baseSkills(seed:string,role:TechnicalStaffRole,rep:number):StaffSkills{const val=(bias=0,o=0)=>Math.round(clamp(38+rep*.38+bias+(pseudo(seed,o)-.5)*22,25,94));return{coaching:val(role.includes('Coach')||role==='assistantManager'?10:0,1),tactics:val(['assistantManager','firstTeamCoach','performanceAnalyst'].includes(role)?11:0,2),technical:val(['firstTeamCoach','youthCoach'].includes(role)?12:0,3),physical:val(['fitnessCoach','sportsScientist'].includes(role)?16:0,4),goalkeeping:val(role==='goalkeepingCoach'?28:-12,5),setPieces:val(role==='setPieceCoach'?24:0,6),analysis:val(['performanceAnalyst','recruitmentAnalyst'].includes(role)?22:0,7),medical:val(['clubDoctor','physiotherapist','sportsScientist'].includes(role)?20:-5,8),rehab:val(['physiotherapist','sportsScientist'].includes(role)?22:0,9),psychology:val(role==='sportsPsychologist'?26:0,10),youth:val(role==='youthCoach'?22:0,11),recruitment:val(role==='recruitmentAnalyst'?24:0,12),manManagement:val(role==='assistantManager'?16:0,13)};}
function createMember(world:World,clubId:string,role:TechnicalStaffRole,index:number):TechnicalStaffMember{const club=world.clubs.find(c=>c.id===clubId),rep=club?.reputation??60,seed=`${clubId}-${role}-${index}`;const manager=managerByClub(world,clubId);const managerLoyalty=manager?Math.round(25+pseudo(seed,31)*55):20;return{id:`staff-${clubId}-${role}-${index}`,clubId,name:`${first[Math.floor(pseudo(seed,1)*first.length)]} ${last[Math.floor(pseudo(seed,2)*last.length)]}`,age:29+Math.floor(pseudo(seed,3)*34),nationality:countries[Math.floor(pseudo(seed,4)*countries.length)],role,reputation:Math.round(clamp(30+rep*.45+(pseudo(seed,5)-.5)*18)),skills:baseSkills(seed,role,rep),personality:{discipline:Math.round(35+pseudo(seed,14)*55),empathy:Math.round(30+pseudo(seed,15)*60),ambition:Math.round(35+pseudo(seed,16)*60),loyalty:Math.round(30+pseudo(seed,17)*65),ego:Math.round(15+pseudo(seed,18)*70),adaptability:Math.round(35+pseudo(seed,19)*58),communication:Math.round(35+pseudo(seed,20)*58),conflictTolerance:Math.round(25+pseudo(seed,21)*65)},salaryWeekly:Math.round(700+rep*30+(role==='assistantManager'?1500:role==='clubDoctor'?1200:0)),contractEnd:`${world.season+2+(index%2)}-06-30`,managerId:manager?.id,managerLoyalty,clubLoyalty:Math.round(30+pseudo(seed,32)*60),managerCompatibility:Math.round(40+pseudo(seed,33)*50),staffHarmony:60,workload:45,fatigue:18,stress:20,jobSatisfaction:65,ambitionToLead:role==='assistantManager'?Math.round(35+pseudo(seed,34)*60):Math.round(5+pseudo(seed,34)*35),status:'active',history:[]};}
function desiredRoles(rep:number):TechnicalStaffRole[]{const out=[...roles];if(rep>=68)out.push('setPieceCoach','sportsPsychologist');if(rep>=75)out.push('recruitmentAnalyst');if(rep>=82)out.push('firstTeamCoach');return out;}
function ensureClub(world:World,clubId:string,s:TechnicalStaffState){if(s.clubStaff.has(clubId))return;const rep=world.clubs.find(c=>c.id===clubId)?.reputation??60,ids:string[]=[];const counts=new Map<TechnicalStaffRole,number>();for(const role of desiredRoles(rep)){const i=(counts.get(role)??0)+1;counts.set(role,i);const m=createMember(world,clubId,role,i);s.members.set(m.id,m);ids.push(m.id);}s.clubStaff.set(clubId,ids);rebuildRelationships(world,clubId,s);}
function rebuildRelationships(world:World,clubId:string,s:TechnicalStaffState){const ids=s.clubStaff.get(clubId)??[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const k=relKey(ids[i],ids[j]);if(s.relationships.has(k))continue;const a=s.members.get(ids[i])!,b=s.members.get(ids[j])!;const compatibility=100-(Math.abs(a.personality.discipline-b.personality.discipline)+Math.abs(a.personality.ambition-b.personality.ambition)+Math.abs(a.personality.empathy-b.personality.empathy))/3;s.relationships.set(k,{a:a.id,b:b.id,trust:Math.round(clamp(42+compatibility*.25+(pseudo(k,1)-.5)*16)),respect:Math.round(clamp(45+(a.reputation+b.reputation)*.16+(pseudo(k,2)-.5)*14)),friction:Math.round(clamp(28-compatibility*.18+(a.personality.ego+b.personality.ego)*.08+(pseudo(k,3)-.5)*12)),professionalSynergy:Math.round(clamp(35+compatibility*.42+(pseudo(k,4)-.5)*14))});}}
export function technicalStaffState(world:World):TechnicalStaffState{let s=states.get(world);if(!s){s={members:new Map(),relationships:new Map(),clubStaff:new Map(),wired:false};states.set(world,s);}for(const club of world.clubs)ensureClub(world,club.id,s);if(!s.wired){s.wired=true;wireStaffEvents(world);}return s;}
export function clubTechnicalStaff(world:World,clubId:string){const s=technicalStaffState(world);return(s.clubStaff.get(clubId)??[]).map(id=>s.members.get(id)).filter((x):x is TechnicalStaffMember=>!!x&&x.status==='active');}
export function technicalStaffMember(world:World,id:string){return technicalStaffState(world).members.get(id);}
export function staffRelationship(world:World,a:string,b:string){return technicalStaffState(world).relationships.get(relKey(a,b));}
function managerFit(world:World,member:TechnicalStaffMember){const m=managerByClub(world,member.clubId);if(!m)return 50;const philosophy=100-(Math.abs(m.personality.discipline-member.personality.discipline)+Math.abs(m.personality.empathy-member.personality.empathy)+Math.abs(m.personality.adaptability-member.personality.adaptability))/3;return clamp(philosophy*.55+member.managerLoyalty*.25+member.personality.communication*.2);}
export function staffDepartmentEffects(world:World,clubId:string){const staff=clubTechnicalStaff(world,clubId),avg=(pick:(s:TechnicalStaffMember)=>number)=>staff.length?staff.reduce((a,s)=>a+pick(s),0)/staff.length:45;const harmony=avg(s=>s.staffHarmony);return{trainingQuality:clamp(avg(s=>Math.max(s.skills.coaching,s.skills.technical,s.skills.tactics))*.72+harmony*.28),physicalPreparation:clamp(avg(s=>Math.max(s.skills.physical,s.skills.rehab))*.75+harmony*.25),medicalQuality:clamp(avg(s=>Math.max(s.skills.medical,s.skills.rehab))*.78+harmony*.22),analysisQuality:clamp(avg(s=>Math.max(s.skills.analysis,s.skills.tactics))*.78+harmony*.22),youthQuality:clamp(avg(s=>Math.max(s.skills.youth,s.skills.coaching))*.75+harmony*.25),psychologicalSupport:clamp(avg(s=>Math.max(s.skills.psychology,s.skills.manManagement))*.7+harmony*.3),staffHarmony:harmony};}
export function dismissTechnicalStaff(world:World,staffId:string,date:string,reason='decisão técnica'){const s=technicalStaffState(world),m=s.members.get(staffId);if(!m||m.status!=='active')return false;m.status='freeAgent';const oldClub=m.clubId;m.clubId='';s.clubStaff.set(oldClub,(s.clubStaff.get(oldClub)??[]).filter(id=>id!==staffId));m.history.push({date,type:'dismissed',summary:`Deixou ${oldClub}: ${reason}.`,impact:-3});emitWorldEvent(world,{type:'StaffDismissed',date,actorIds:[staffId],clubIds:[oldClub],importance:2,summary:`${m.name} deixou a comissão técnica de ${oldClub}.`,payload:{staffId,role:m.role,reason}});return true;}
export function hireTechnicalStaff(world:World,staffId:string,clubId:string,date:string,managerId?:string){const s=technicalStaffState(world),m=s.members.get(staffId);if(!m||m.status==='retired')return false;const old=m.clubId;if(old)s.clubStaff.set(old,(s.clubStaff.get(old)??[]).filter(id=>id!==staffId));m.clubId=clubId;m.status='active';m.managerId=managerId??managerByClub(world,clubId)?.id;m.managerLoyalty=m.managerId===managerId?clamp(m.managerLoyalty+12):m.managerLoyalty;m.contractEnd=`${Number(date.slice(0,4))+2}-06-30`;m.salaryWeekly=Math.round(m.salaryWeekly*(old?1.08:1.15));if(!s.clubStaff.has(clubId))s.clubStaff.set(clubId,[]);s.clubStaff.get(clubId)!.push(m.id);rebuildRelationships(world,clubId,s);m.history.push({date,type:'hired',summary:`Contratado por ${clubId}.`,impact:3});emitWorldEvent(world,{type:'StaffHired',date,actorIds:[m.id,...(m.managerId?[m.managerId]:[])],clubIds:[clubId],importance:2,summary:`${m.name} entrou na comissão técnica de ${clubId}.`,payload:{staffId:m.id,role:m.role}});return true;}
export function availableTechnicalStaff(world:World,role?:TechnicalStaffRole){return[...technicalStaffState(world).members.values()].filter(s=>s.status==='freeAgent'&&(!role||s.role===role));}
function maybeEntourage(world:World,managerId:string,clubId:string,date:string){const s=technicalStaffState(world),m=managerCharacterState(world).characters.get(managerId),contract=managerContract(world,managerId);if(!m||!contract)return;const control=contract.autonomy;const candidates=[...s.members.values()].filter(x=>x.status==='freeAgent'&&x.managerId===managerId&&x.managerLoyalty>=62).sort((a,b)=>b.managerLoyalty-a.managerLoyalty);const max=control>=78?3:control>=62?2:control>=48?1:0;for(const staff of candidates.slice(0,max))hireTechnicalStaff(world,staff.id,clubId,date,managerId);if(candidates.length&&max===0)emitWorldEvent(world,{type:'StaffRequestDenied',date,actorIds:[managerId],clubIds:[clubId],importance:2,summary:`A diretoria limitou mudanças imediatas na comissão de ${m.name}.`,payload:{managerId,requested:candidates.length,autonomy:control}});}
function onManagerLeaves(world:World,managerId:string,clubId:string,date:string){for(const s of clubTechnicalStaff(world,clubId)){if(s.managerId!==managerId)continue;const followChance=clamp((s.managerLoyalty-45)*.012+(s.personality.loyalty-50)*.004-(s.clubLoyalty-50)*.006,0,.72);if(pseudo(`${managerId}-${s.id}-${date}-follow`)<followChance){s.status='freeAgent';s.clubId='';technicalStaffState(world).clubStaff.set(clubId,(technicalStaffState(world).clubStaff.get(clubId)??[]).filter(id=>id!==s.id));s.history.push({date,type:'managerExit',summary:`Deixou o clube após a saída de ${managerId}.`,impact:-1});emitWorldEvent(world,{type:'StaffFollowedManager',date,actorIds:[s.id,managerId],clubIds:[clubId],importance:2,summary:`${s.name} deixou ${clubId} após a saída do treinador.`,payload:{staffId:s.id,managerId}});}}}
function wireStaffEvents(world:World){onWorldEvent(world,'ManagerHired',(e)=>{const managerId=e.actorIds[0],clubId=String(e.payload.to??e.clubIds[0]??'');if(managerId&&clubId)maybeEntourage(world,managerId,clubId,e.date);});onWorldEvent(world,'ManagerSacked',(e)=>{const managerId=e.actorIds[0],clubId=String(e.payload.clubId??e.clubIds[0]??'');if(managerId&&clubId)onManagerLeaves(world,managerId,clubId,e.date);});onWorldEvent(world,'ManagerResigned',(e)=>{const managerId=e.actorIds[0],clubId=e.clubIds[0];if(managerId&&clubId)onManagerLeaves(world,managerId,clubId,e.date);});}
function tickMember(world:World,s:TechnicalStaffMember,date:string){if(s.status!=='active')return;s.managerCompatibility=managerFit(world,s);const colleagues=clubTechnicalStaff(world,s.clubId).filter(x=>x.id!==s.id);const rels=colleagues.map(x=>staffRelationship(world,s.id,x.id)).filter(Boolean) as StaffRelationship[];const harmony=rels.length?rels.reduce((a,r)=>a+r.professionalSynergy-r.friction*.45,0)/rels.length:60;s.staffHarmony=clamp(harmony*.65+s.managerCompatibility*.35);s.workload=clamp(s.workload*.94+(45+(s.role==='assistantManager'?8:0)+(clubTechnicalStaff(world,s.clubId).length<8?12:0))*.06);s.fatigue=clamp(s.fatigue+(s.workload-55)*.012-.18);s.stress=clamp(s.stress+(100-s.managerCompatibility)*.006+(100-s.staffHarmony)*.006-.22);s.jobSatisfaction=clamp(s.jobSatisfaction+(s.staffHarmony-55)*.004+(s.managerCompatibility-55)*.004-(s.stress-45)*.003);if(s.jobSatisfaction<24&&pseudo(`${s.id}-${date}-quit`)<.0025){dismissTechnicalStaff(world,s.id,date,'insatisfação profissional');emitWorldEvent(world,{type:'StaffResigned',date,actorIds:[s.id],importance:2,summary:`${s.name} pediu desligamento por insatisfação.`,payload:{staffId:s.id,role:s.role}});}if(s.age>=68&&pseudo(`${s.id}-${date}-retire`)<.0008){const club=s.clubId;dismissTechnicalStaff(world,s.id,date,'aposentadoria');s.status='retired';emitWorldEvent(world,{type:'StaffRetired',date,actorIds:[s.id],clubIds:club?[club]:[],importance:2,summary:`${s.name} encerrou a carreira no futebol.`,payload:{staffId:s.id,role:s.role}});}}
function fillVacancies(world:World,clubId:string,date:string){const s=technicalStaffState(world),rep=world.clubs.find(c=>c.id===clubId)?.reputation??60,current=clubTechnicalStaff(world,clubId);for(const role of desiredRoles(rep)){if(current.some(x=>x.role===role))continue;let candidate=availableTechnicalStaff(world,role).sort((a,b)=>b.reputation-a.reputation)[0];if(!candidate){candidate=createMember(world,'',role,hash(`${clubId}-${role}-${date}`)%10000);candidate.status='freeAgent';candidate.clubId='';s.members.set(candidate.id,candidate);}hireTechnicalStaff(world,candidate.id,clubId,date,managerByClub(world,clubId)?.id);}}
export function tickTechnicalStaff(world:World,date:string){const s=technicalStaffState(world);if(s.lastTick===date)return;s.lastTick=date;for(const member of [...s.members.values()])tickMember(world,member,date);if(date.endsWith('-01')||date.endsWith('-15'))for(const club of world.clubs)fillVacancies(world,club.id,date);}
export function snapshotTechnicalStaff(world:World):TechnicalStaffSnapshot{const s=technicalStaffState(world);return{members:[...s.members.entries()].map(([k,v])=>[k,JSON.parse(JSON.stringify(v))]),relationships:[...s.relationships.entries()].map(([k,v])=>[k,{...v}]),clubStaff:[...s.clubStaff.entries()].map(([k,v])=>[k,[...v]]),lastTick:s.lastTick};}
export function restoreTechnicalStaff(world:World,snapshot?:TechnicalStaffSnapshot){if(!snapshot)return;states.set(world,{members:new Map(snapshot.members.map(([k,v])=>[k,JSON.parse(JSON.stringify(v))])),relationships:new Map(snapshot.relationships.map(([k,v])=>[k,{...v}])),clubStaff:new Map(snapshot.clubStaff.map(([k,v])=>[k,[...v]])),lastTick:snapshot.lastTick,wired:false});}
