import type { Club, World } from './engine';
import { availableTechnicalStaff, clubTechnicalStaff, dismissTechnicalStaff, hireTechnicalStaff, staffDepartmentEffects, staffRoleLabel, technicalStaffState, type TechnicalStaffMember } from './technical-staff';
import { dailyCalendar } from './daily-simulation';
import { managerByClub } from './manager-character';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const skill=(s:TechnicalStaffMember)=>Math.max(...Object.values(s.skills));
const row=(s:TechnicalStaffMember)=>`<tr><td><b>${esc(s.name)}</b><small>${esc(s.nationality)} · ${s.age} anos</small></td><td>${esc(staffRoleLabel(s.role))}</td><td>${s.reputation.toFixed(0)}</td><td>${skill(s).toFixed(0)}</td><td>${s.managerCompatibility.toFixed(0)}</td><td>${s.squadAffinity.toFixed(0)}</td><td>${s.clubPhilosophyFit.toFixed(0)}</td><td>${s.staffHarmony.toFixed(0)}</td><td>${s.jobSatisfaction.toFixed(0)}</td><td>R$ ${s.salaryWeekly.toLocaleString('pt-BR')}</td><td><button class="staff-dismiss" data-staff="${s.id}">Dispensar</button></td></tr>`;
export function renderTechnicalStaff(world:World,club:Club){const staff=clubTechnicalStaff(world,club.id),e=staffDepartmentEffects(world,club.id),free=availableTechnicalStaff(world).sort((a,b)=>b.reputation-a.reputation).slice(0,12),manager=managerByClub(world,club.id);return `<header><div><span class="eyebrow">COMISSÃO TÉCNICA · ${esc(club.name.toUpperCase())}</span><h1>Ecossistema técnico, científico e humano</h1><p>Cada profissional tem carreira, reputação, atributos, personalidade, filosofia, afinidade com treinador e jogadores, lealdade e relações internas próprias.</p></div></header><section class="cards"><article class="card metric"><span>Treino</span><strong>${e.trainingQuality.toFixed(0)}</strong></article><article class="card metric"><span>Medicina</span><strong>${e.medicalQuality.toFixed(0)}</strong></article><article class="card metric"><span>Nutrição</span><strong>${e.nutritionQuality.toFixed(0)}</strong></article><article class="card metric"><span>Psicológico</span><strong>${e.psychologicalSupport.toFixed(0)}</strong></article><article class="card metric"><span>Coordenação</span><strong>${e.coordinationQuality.toFixed(0)}</strong></article><article class="card metric"><span>Afinidade elenco</span><strong>${e.squadAffinity.toFixed(0)}</strong></article><article class="card metric"><span>Filosofia clube</span><strong>${e.clubPhilosophyFit.toFixed(0)}</strong></article><article class="card metric"><span>Harmonia</span><strong>${e.staffHarmony.toFixed(0)}</strong></article></section><section class="card"><div class="section-title"><h2>Estrutura atual</h2><span>${staff.length} profissionais · treinador ${esc(manager?.name??'não definido')}</span></div><table><thead><tr><th>Profissional</th><th>Função</th><th>Rep.</th><th>Melhor atrib.</th><th>Treinador</th><th>Elenco</th><th>Clube</th><th>Harmonia</th><th>Satisf.</th><th>Salário/sem.</th><th></th></tr></thead><tbody>${staff.map(row).join('')}</tbody></table></section><section class="card"><div class="section-title"><h2>Mercado de staff</h2><span>profissionais disponíveis</span></div>${free.length?`<table><thead><tr><th>Profissional</th><th>Função</th><th>Rep.</th><th>Potencial</th><th>Qualificação</th><th>Lealdade ao treinador</th><th></th></tr></thead><tbody>${free.map(s=>`<tr><td><b>${esc(s.name)}</b><small>${esc(s.nationality)} · ${s.age} anos</small></td><td>${esc(staffRoleLabel(s.role))}</td><td>${s.reputation.toFixed(0)}</td><td>${s.careerPotential.toFixed(0)}</td><td>${s.qualifications.toFixed(0)}</td><td>${s.managerLoyalty.toFixed(0)}</td><td><button class="staff-hire" data-staff="${s.id}">Contratar</button></td></tr>`).join('')}</tbody></table>`:'<p>Não há profissionais livres relevantes neste momento.</p>'}</section>`}
export function bindTechnicalStaff(world:World,club:Club,rerender:()=>void){const date=dailyCalendar(world).date,manager=managerByClub(world,club.id);document.querySelectorAll<HTMLButtonElement>('.staff-dismiss').forEach(b=>b.addEventListener('click',()=>{dismissTechnicalStaff(world,b.dataset.staff!,date,'reestruturação da comissão');rerender()}));document.querySelectorAll<HTMLButtonElement>('.staff-hire').forEach(b=>b.addEventListener('click',()=>{hireTechnicalStaff(world,b.dataset.staff!,club.id,date,manager?.id);rerender()}));technicalStaffState(world)}
