import type { World } from './engine';
import { emitWorldEvent, onWorldEvent } from './event-bus';
import { managerByClub, managerCharacterState } from './manager-character';
import { managerContract } from './manager-employment';

export type TechnicalStaffRole='assistantManager'|'deputyManager'|'technicalAssistant'|'firstTeamCoach'|'attackingCoach'|'defensiveCoach'|'possessionCoach'|'transitionCoach'|'fitnessCoach'|'strengthConditioningCoach'|'goalkeepingCoach'|'setPieceCoach'|'performanceAnalyst'|'oppositionAnalyst'|'videoAnalyst'|'sportsScientist'|'physiotherapist'|'rehabSpecialist'|'clubDoctor'|'nutritionist'|'sportsPsychologist'|'mentalCoach'|'youthCoach'|'youthDevelopmentCoach'|'loanManager'|'recruitmentAnalyst'|'chiefScout'|'footballCoordinator'|'squadCoordinator'|'teamManager'|'playerLiaison'|'welfareOfficer';
export type StaffPersonality={discipline:number;empathy:number;ambition:number;loyalty:number;ego:number;adaptability:number;communication:number;conflictTolerance:number};
export type StaffPhilosophy={clubIdentity:number;youthPathway:number;dataOrientation:number;playerCare:number;performanceFirst:number;tacticalRigidity:number;collectiveWork:number};
export type StaffSkills={coaching:number;tactics:number;technical:number;physical:number;goalkeeping:number;setPieces:number;analysis:number;medical:number;rehab:number;nutrition:number;psychology:number;youth:number;recruitment:number;manManagement:number;coordination:number;communication:number;data:number};
export type TechnicalStaffMember={id:string;clubId:string;name:string;age:number;nationality:string;role:TechnicalStaffRole;reputation:number;skills:StaffSkills;personality:StaffPersonality;philosophy:StaffPhilosophy;salaryWeekly:number;contractEnd:string;managerId?:string;managerLoyalty:number;clubLoyalty:number;managerCompatibility:number;clubPhilosophyFit:number;squadAffinity:number;playerAffinities:Record<string,number>;staffHarmony:number;workload:number;fatigue:number;stress:number;jobSatisfaction:number;ambitionToLead:number;careerPotential:number;experience:number;qualifications:number;status:'active'|'notice'|'freeAgent'|'retired';history:{date:string;type:string;summary:string;impact:number}[]};
export type StaffRelationship={a:string;b:string;trust:number;respect:number;friction:number;professionalSynergy:number;lastChanged?:string};
export type TechnicalStaffState={members:Map<string,TechnicalStaffMember>;relationships:Map<string,StaffRelationship>;clubStaff:Map<string,string[]>;lastTick?:string;wired:boolean};
export type TechnicalStaffSnapshot={members:[string,TechnicalStaffMember][];relationships:[string,StaffRelationship][];clubStaff:[string,string[]][];lastTick?:string};
const states=new WeakMap<World,TechnicalStaffState>(),clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return Math.abs(h>>>0)},pseudo=(s:string,o=0)=>{const x=Math.sin((hash(s)+o)*12.9898)*43758.5453;return x-Math.floor(x)};
const first=['André','Bruno','Caio','Daniel','Eduardo','Felipe','Gustavo','Henrique','Igor','João','Lucas','Marcelo','Nicolas','Paulo','Rafael','Sérgio','Thiago','Vinícius'],last=['Almeida','Barbosa','Cardoso','Duarte','Ferreira','Gomes','Lima','Martins','Melo','Nogueira','Oliveira','Pereira','Ramos','Rocha','Silva','Souza','Teixeira'],countries=['Brasil','Argentina','Uruguai','Portugal','Espanha','Itália','Chile','Colômbia','Paraguai'];
const labels:Record<TechnicalStaffRole,string>={assistantManager:'Auxiliar principal',deputyManager:'Treinador adjunto',technicalAssistant:'Auxiliar técnico',firstTeamCoach:'Treinador do time principal',attackingCoach:'Treinador ofensivo',defensiveCoach:'Treinador defensivo',possessionCoach:'Treinador de posse',transitionCoach:'Treinador de transições',fitnessCoach:'Preparador físico',strengthConditioningCoach:'Preparador de força e condicionamento',goalkeepingCoach:'Treinador de goleiros',setPieceCoach:'Treinador de bolas paradas',performanceAnalyst:'Analista de desempenho',oppositionAnalyst:'Analista de adversários',videoAnalyst:'Analista de vídeo',sportsScientist:'Cientista do esporte',physiotherapist:'Fisioterapeuta',rehabSpecialist:'Especialista em reabilitação',clubDoctor:'Médico do clube',nutritionist:'Nutricionista esportivo',sportsPsychologist:'Psicólogo esportivo',mentalCoach:'Treinador mental',youthCoach:'Treinador da base',youthDevelopmentCoach:'Desenvolvedor de jovens',loanManager:'Coordenador de empréstimos',recruitmentAnalyst:'Analista de recrutamento',chiefScout:'Chefe de scouting',footballCoordinator:'Coordenador de futebol',squadCoordinator:'Coordenador de elenco',teamManager:'Supervisor de equipe',playerLiaison:'Relações com atletas',welfareOfficer:'Bem-estar de atletas'};
const allRoles=Object.keys(labels) as TechnicalStaffRole[],relKey=(a:string,b:string)=>[a,b].sort().join('|');
const specialties:Partial<Record<keyof StaffSkills,TechnicalStaffRole[]>>={coaching:['assistantManager','deputyManager','technicalAssistant','firstTeamCoach','attackingCoach','defensiveCoach','possessionCoach','transitionCoach','youthCoach'],tactics:['assistantManager','deputyManager','firstTeamCoach','performanceAnalyst','oppositionAnalyst'],physical:['fitnessCoach','strengthConditioningCoach','sportsScientist'],goalkeeping:['goalkeepingCoach'],setPieces:['setPieceCoach'],analysis:['performanceAnalyst','oppositionAnalyst','videoAnalyst','recruitmentAnalyst'],medical:['clubDoctor','physiotherapist','rehabSpecialist'],rehab:['physiotherapist','rehabSpecialist','sportsScientist'],nutrition:['nutritionist','sportsScientist'],psychology:['sportsPsychologist','mentalCoach','playerLiaison','welfareOfficer'],youth:['youthCoach','youthDevelopmentCoach','loanManager'],recruitment:['recruitmentAnalyst','chiefScout','footballCoordinator'],manManagement:['assistantManager','deputyManager','footballCoordinator','squadCoordinator','teamManager'],coordination:['footballCoordinator','squadCoordinator','teamManager','loanManager'],communication:['assistantManager','squadCoordinator','playerLiaison','welfareOfficer'],data:['performanceAnalyst','oppositionAnalyst','videoAnalyst','sportsScientist','recruitmentAnalyst']};
function skills(seed:string,role:TechnicalStaffRole,rep:number){const out={} as StaffSkills,keys=(['coaching','tactics','technical','physical','goalkeeping','setPieces','analysis','medical','rehab','nutrition','psychology','youth','recruitment','manManagement','coordination','communication','data'] as (keyof StaffSkills)[]);keys.forEach((k,i)=>out[k]=Math.round(clamp(32+rep*.4+(specialties[k]?.includes(role)?23:0)+(pseudo(seed,i)-.5)*22,18,96)));return out}
function createMember(world:World,clubId:string,role:TechnicalStaffRole,index:number):TechnicalStaffMember{const rep=world.clubs.find(c=>c.id===clubId)?.reputation??60,seed=`${clubId}-${role}-${index}`,manager=managerByClub(world,clubId),personality={discipline:Math.round(30+pseudo(seed,20)*65),empathy:Math.round(25+pseudo(seed,21)*70),ambition:Math.round(30+pseudo(seed,22)*68),loyalty:Math.round(25+pseudo(seed,23)*72),ego:Math.round(10+pseudo(seed,24)*82),adaptability:Math.round(28+pseudo(seed,25)*68),communication:Math.round(28+pseudo(seed,26)*68),conflictTolerance:Math.round(22+pseudo(seed,27)*72)},philosophy={clubIdentity:Math.round(25+pseudo(seed,40)*70),youthPathway:Math.round(20+pseudo(seed,41)*76),dataOrientation:Math.round(20+pseudo(seed,42)*76),playerCare:Math.round(25+pseudo(seed,43)*70),performanceFirst:Math.round(25+pseudo(seed,44)*72),tacticalRigidity:Math.round(15+pseudo(seed,45)*80),collectiveWork:Math.round(25+pseudo(seed,46)*70)};return{id:`staff-${clubId}-${role}-${index}`,clubId,name:`${first[Math.floor(pseudo(seed,1)*first.length)]} ${last[Math.floor(pseudo(seed,2)*last.length)]}`,age:27+Math.floor(pseudo(seed,3)*38),nationality:countries[Math.floor(pseudo(seed,4)*countries.length)],role,reputation:Math.round(clamp(28+rep*.47+(pseudo(seed,5)-.5)*20)),skills:skills(seed,role,rep),personality,philosophy,salaryWeekly:Math.round(650+rep*31+(['assistantManager','deputyManager','footballCoordinator'].includes(role)?1600:role==='clubDoctor'?1300:0)),contractEnd:`${world.season+2+(index%2)}-06-30`,managerId:manager?.id,managerLoyalty:manager?Math.round(22+pseudo(seed,31)*65):20,clubLoyalty:Math.round(25+pseudo(seed,32)*68),managerCompatibility:Math.round(38+pseudo(seed,33)*55),clubPhilosophyFit:60,squadAffinity:60,playerAffinities:{},staffHarmony:60,workload:42,fatigue:16,stress:18,jobSatisfaction:66,ambitionToLead:['assistantManager','deputyManager','technicalAssistant','footballCoordinator'].includes(role)?Math.round(35+pseudo(seed,36)*62):Math.round(5+pseudo(seed,36)*38),careerPotential:Math.round(clamp(45+rep*.25+(pseudo(seed,37)-.5)*35)),experience:Math.round(clamp((27+Math.floor(pseudo(seed,3)*38)-24)*2.1,5,95)),qualifications:Math.round(clamp(35+rep*.35+(pseudo(seed,38)-.5)*28)),status:'active',history:[]}}
function desiredRoles(rep:number){const r:TechnicalStaffRole[]=['assistantManager','technicalAssistant','firstTeamCoach','fitnessCoach','goalkeepingCoach','performanceAnalyst','sportsScientist','physiotherapist','clubDoctor','nutritionist','sportsPsychologist','youthCoach','recruitmentAnalyst','footballCoordinator','squadCoordinator'];if(rep>=62)r.push('attackingCoach','defensiveCoach','rehabSpecialist','oppositionAnalyst','playerLiaison');if(rep>=68)r.push('setPieceCoach','strengthConditioningCoach','youthDevelopmentCoach','teamManager');if(rep>=73)r.push('deputyManager','videoAnalyst','mentalCoach','loanManager','chiefScout');if(rep>=78)r.push('possessionCoach','transitionCoach','welfareOfficer');if(rep>=84)r.push('firstTeamCoach','performanceAnalyst','physiotherapist','sportsScientist');return r}
function rebuild(clubId:string,s:TechnicalStaffState){const ids=s.clubStaff.get(clubId)??[];for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++){const k=relKey(ids[i],ids[j]);if(s.relationships.has(k))continue;const a=s.members.get(ids[i])!,b=s.members.get(ids[j])!,fit=100-(Math.abs(a.personality.discipline-b.personality.discipline)+Math.abs(a.personality.ambition-b.personality.ambition)+Math.abs(a.philosophy.collectiveWork-b.philosophy.collectiveWork))/3;s.relationships.set(k,{a:a.id,b:b.id,trust:Math.round(clamp(40+fit*.28)),respect:Math.round(clamp(42+(a.reputation+b.reputation)*.18)),friction:Math.round(clamp(30-fit*.2+(a.personality.ego+b.personality.ego)*.09)),professionalSynergy:Math.round(clamp(32+fit*.45))})}}
function ensureClub(world:World,clubId:string,s:TechnicalStaffState){if(s.clubStaff.has(clubId))return;const ids:string[]=[],counts=new Map<TechnicalStaffRole,number>();for(const role of desiredRoles(world.clubs.find(c=>c.id===clubId)?.reputation??60)){const i=(counts.get(role)??0)+1;counts.set(role,i);const m=createMember(world,clubId,role,i);s.members.set(m.id,m);ids.push(m.id)}s.clubStaff.set(clubId,ids);rebuild(clubId,s)}
export function technicalStaffState(world:World){let s=states.get(world);if(!s){s={members:new Map(),relationships:new Map(),clubStaff:new Map(),wired:false};states.set(world,s)}for(const c of world.clubs)ensureClub(world,c.id,s);if(!s.wired){s.wired=true;wire(world)}return s}
export function clubTechnicalStaff(world:World,clubId:string){const s=technicalStaffState(world);return(s.clubStaff.get(clubId)??[]).map(id=>s.members.get(id)).filter((x):x is TechnicalStaffMember=>!!x&&x.status==='active')}
export function technicalStaffMember(world:World,id:string){return technicalStaffState(world).members.get(id)}
export function staffRelationship(world:World,a:string,b:string){return technicalStaffState(world).relationships.get(relKey(a,b))}
function updateFits(world:World,s:TechnicalStaffMember){const m=managerByClub(world,s.clubId),club=world.clubs.find(c=>c.id===s.clubId);s.managerCompatibility=m?clamp((100-(Math.abs(m.personality.discipline-s.personality.discipline)+Math.abs(m.personality.empathy-s.personality.empathy)+Math.abs(m.personality.adaptability-s.personality.adaptability))/3)*.55+s.managerLoyalty*.25+s.personality.communication*.2):50;s.clubPhilosophyFit=club?clamp(100-Math.abs(s.philosophy.clubIdentity-(42+club.reputation*.45))*.55-Math.abs(s.philosophy.performanceFirst-club.reputation)*.3):50;let total=0,n=0;if(club)for(const p of club.players){let v=s.playerAffinities[p.id]??Math.round(clamp(38+s.personality.empathy*.22+s.personality.communication*.18+(pseudo(`${s.id}-${p.id}`)-.5)*34));v=clamp(v+(s.philosophy.playerCare-50)*.002-(s.personality.ego-55)*.001);s.playerAffinities[p.id]=Number(v.toFixed(2));total+=v;n++}s.squadAffinity=n?total/n:50}
export function staffDepartmentEffects(world:World,clubId:string){const st=clubTechnicalStaff(world,clubId),avg=(f:(s:TechnicalStaffMember)=>number)=>st.length?st.reduce((a,s)=>a+f(s),0)/st.length:45,h=avg(s=>s.staffHarmony),sq=avg(s=>s.squadAffinity),fit=avg(s=>s.clubPhilosophyFit);return{trainingQuality:clamp(avg(s=>Math.max(s.skills.coaching,s.skills.technical,s.skills.tactics))*.6+h*.22+fit*.18),physicalPreparation:clamp(avg(s=>Math.max(s.skills.physical,s.skills.rehab,s.skills.nutrition))*.68+h*.16+sq*.16),medicalQuality:clamp(avg(s=>Math.max(s.skills.medical,s.skills.rehab,s.skills.nutrition))*.7+h*.15+sq*.15),analysisQuality:clamp(avg(s=>Math.max(s.skills.analysis,s.skills.data,s.skills.tactics))*.72+h*.16+fit*.12),youthQuality:clamp(avg(s=>Math.max(s.skills.youth,s.skills.coaching))*.65+h*.15+fit*.2),psychologicalSupport:clamp(avg(s=>Math.max(s.skills.psychology,s.skills.manManagement,s.skills.communication))*.62+h*.15+sq*.23),coordinationQuality:clamp(avg(s=>Math.max(s.skills.coordination,s.skills.manManagement,s.skills.communication))*.65+h*.2+fit*.15),nutritionQuality:clamp(avg(s=>Math.max(s.skills.nutrition,s.skills.physical))*.72+sq*.15+h*.13),staffHarmony:h,squadAffinity:sq,clubPhilosophyFit:fit}}
export function dismissTechnicalStaff(world:World,id:string,date:string,reason='decisão técnica'){const st=technicalStaffState(world),m=st.members.get(id);if(!m||m.status!=='active')return false;const old=m.clubId;m.status='freeAgent';m.clubId='';st.clubStaff.set(old,(st.clubStaff.get(old)??[]).filter(x=>x!==id));m.history.push({date,type:'dismissed',summary:`Deixou ${old}: ${reason}.`,impact:-3});emitWorldEvent(world,{type:'StaffDismissed',date,actorIds:[id],clubIds:[old],importance:2,summary:`${m.name} deixou ${old}.`,payload:{staffId:id,role:m.role,reason}});return true}
export function hireTechnicalStaff(world:World,id:string,clubId:string,date:string,managerId?:string){const st=technicalStaffState(world),m=st.members.get(id);if(!m||m.status==='retired')return false;const old=m.clubId;if(old)st.clubStaff.set(old,(st.clubStaff.get(old)??[]).filter(x=>x!==id));m.clubId=clubId;m.status='active';m.managerId=managerId??managerByClub(world,clubId)?.id;m.contractEnd=`${Number(date.slice(0,4))+2}-06-30`;m.salaryWeekly=Math.round(m.salaryWeekly*(old?1.08:1.15));m.jobSatisfaction=68;if(!st.clubStaff.has(clubId))st.clubStaff.set(clubId,[]);st.clubStaff.get(clubId)!.push(id);rebuild(clubId,st);emitWorldEvent(world,{type:'StaffHired',date,actorIds:[id],clubIds:[clubId],importance:2,summary:`${m.name} entrou na estrutura técnica de ${clubId}.`,payload:{staffId:id,role:m.role}});return true}
export function availableTechnicalStaff(world:World,role?:TechnicalStaffRole){return[...technicalStaffState(world).members.values()].filter(s=>s.status==='freeAgent'&&(!role||s.role===role))}
function entourage(world:World,managerId:string,clubId:string,date:string){const st=technicalStaffState(world),contract=managerContract(world,managerId);if(!managerCharacterState(world).characters.get(managerId)||!contract)return;const c=[...st.members.values()].filter(x=>x.status==='freeAgent'&&x.managerId===managerId&&x.managerLoyalty>=62).sort((a,b)=>b.managerLoyalty-a.managerLoyalty),max=contract.autonomy>=78?4:contract.autonomy>=62?3:contract.autonomy>=48?2:1;for(const x of c.slice(0,max))hireTechnicalStaff(world,x.id,clubId,date,managerId)}
function managerLeaves(world:World,managerId:string,clubId:string,date:string){for(const s of clubTechnicalStaff(world,clubId))if(s.managerId===managerId&&pseudo(`${managerId}-${s.id}-${date}`)<clamp((s.managerLoyalty-45)*.012+(s.personality.loyalty-50)*.004-(s.clubLoyalty-50)*.006,0,.75)){s.status='freeAgent';s.clubId='';technicalStaffState(world).clubStaff.set(clubId,(technicalStaffState(world).clubStaff.get(clubId)??[]).filter(id=>id!==s.id));emitWorldEvent(world,{type:'StaffFollowedManager',date,actorIds:[s.id,managerId],clubIds:[clubId],importance:2,summary:`${s.name} deixou ${clubId} após a saída do treinador.`,payload:{staffId:s.id,managerId}})}}
function wire(world:World){onWorldEvent(world,'ManagerHired',e=>{const m=e.actorIds[0],c=String(e.payload.to??e.clubIds[0]??'');if(m&&c)entourage(world,m,c,e.date)});onWorldEvent(world,'ManagerSacked',e=>{const m=e.actorIds[0],c=String(e.payload.clubId??e.clubIds[0]??'');if(m&&c)managerLeaves(world,m,c,e.date)});onWorldEvent(world,'ManagerResigned',e=>{const m=e.actorIds[0],c=e.clubIds[0];if(m&&c)managerLeaves(world,m,c,e.date)})}
function tick(world:World,s:TechnicalStaffMember,date:string){if(s.status!=='active')return;updateFits(world,s);const rels=clubTechnicalStaff(world,s.clubId).filter(x=>x.id!==s.id).map(x=>staffRelationship(world,s.id,x.id)).filter(Boolean) as StaffRelationship[],h=rels.length?rels.reduce((a,r)=>a+r.professionalSynergy-r.friction*.45,0)/rels.length:60;s.staffHarmony=clamp(h*.52+s.managerCompatibility*.22+s.clubPhilosophyFit*.13+s.squadAffinity*.13);s.fatigue=clamp(s.fatigue*.94+s.workload*.018-1.1);s.stress=clamp(s.stress*.95+(100-s.staffHarmony)*.018+(100-s.managerCompatibility)*.012+s.fatigue*.01);s.jobSatisfaction=clamp(s.jobSatisfaction*.97+s.staffHarmony*.012+s.managerCompatibility*.008+s.clubPhilosophyFit*.006+s.squadAffinity*.006-s.stress*.008);if(date.endsWith('-07-01')){s.age++;s.experience=clamp(s.experience+2);if(s.age<55&&s.reputation<s.careerPotential&&pseudo(`${s.id}-${date}-dev`)<.55){const ks=Object.keys(s.skills) as (keyof StaffSkills)[],k=ks.sort((a,b)=>(specialties[b]?.includes(s.role)?1:0)-(specialties[a]?.includes(s.role)?1:0))[0];s.skills[k]=clamp(s.skills[k]+1);s.reputation=clamp(s.reputation+.5);s.qualifications=clamp(s.qualifications+1)}if(s.age>=66&&pseudo(`${s.id}-${date}-retire`)<clamp((s.age-64)*.09,0,.7))s.status='retired'}if(date.endsWith('-01')&&s.reputation>=70&&pseudo(`${s.id}-${date}-poach`)<.012){const target=world.clubs.filter(c=>c.id!==s.clubId&&c.reputation>=s.reputation-8).sort((a,b)=>b.reputation-a.reputation)[0];if(target&&pseudo(`${s.id}-${date}-accept`)<clamp((s.personality.ambition+s.reputation-s.clubLoyalty)/130,.15,.8))hireTechnicalStaff(world,s.id,target.id,date)}if(s.jobSatisfaction<28&&pseudo(`${s.id}-${date}-quit`)<.006)s.status='notice'}
export function tickTechnicalStaff(world:World,date:string){const st=technicalStaffState(world);if(st.lastTick===date)return;for(const m of [...st.members.values()])tick(world,m,date);for(const c of world.clubs){const active=clubTechnicalStaff(world,c.id),critical:TechnicalStaffRole[]=['assistantManager','fitnessCoach','goalkeepingCoach','physiotherapist','clubDoctor','nutritionist','sportsPsychologist','footballCoordinator'];for(const role of critical)if(!active.some(x=>x.role===role)){const m=createMember(world,c.id,role,[...st.members.values()].filter(x=>x.role===role).length+1);st.members.set(m.id,m);st.clubStaff.get(c.id)!.push(m.id);rebuild(c.id,st)}}st.lastTick=date}
export function snapshotTechnicalStaff(world:World):TechnicalStaffSnapshot{const s=technicalStaffState(world);return{members:[...s.members.entries()].map(([k,v])=>[k,{...v,skills:{...v.skills},personality:{...v.personality},philosophy:{...v.philosophy},playerAffinities:{...v.playerAffinities},history:v.history.map(h=>({...h}))}]),relationships:[...s.relationships.entries()].map(([k,v])=>[k,{...v}]),clubStaff:[...s.clubStaff.entries()].map(([k,v])=>[k,[...v]]),lastTick:s.lastTick}}
export function restoreTechnicalStaff(world:World,x:TechnicalStaffSnapshot){states.set(world,{members:new Map(x.members.map(([k,v])=>[k,{...v,philosophy:{...(v.philosophy??{clubIdentity:50,youthPathway:50,dataOrientation:50,playerCare:50,performanceFirst:50,tacticalRigidity:50,collectiveWork:50})},playerAffinities:{...(v.playerAffinities??{})}}])),relationships:new Map(x.relationships),clubStaff:new Map(x.clubStaff),lastTick:x.lastTick,wired:false});technicalStaffState(world)}
export function staffRoleLabel(role:TechnicalStaffRole){return labels[role]}
export function technicalStaffRoles(){return[...allRoles]}
