import './training-beta-ui-v1.css';
import { dailyCalendar, setClubTrainingPlan, type TrainingFocus, type TrainingIntensity } from './daily-simulation';
import { userManager } from './manager-character';
import type { World } from './engine';

const focuses:TrainingFocus[]=['recovery','physical','technical','tactical','attacking','defending'];
const intensities:TrainingIntensity[]=['low','medium','high'];
const label:Record<string,string>={recovery:'Recuperação',physical:'Físico',technical:'Técnico',tactical:'Tático',attacking:'Ataque',defending:'Defesa',low:'Baixa',medium:'Média',high:'Alta'};
function world(){return window.__touchlineWorld as World|undefined}
function renderTraining(){const w=world(),host=document.querySelector<HTMLElement>('.game-stage main.view');if(!w||!host)return;const m=userManager(w),c=w.clubs.find(x=>x.id===m?.currentClubId);if(!c)return;const plan=dailyCalendar(w).clubPlans.get(c.id)!;host.innerHTML=`<header class="view-hero"><div><span class="kicker">FUTEBOL · TREINO</span><h1>Centro de Treinamento</h1><p>O plano abaixo alimenta diretamente o motor diário. Em dias sem partida, o calendário executa treino ou descanso usando esta configuração.</p></div><div class="hero-glow"></div></header><section class="training-beta-grid"><article class="glass training-card"><span>FOCO</span><h3>${label[plan.focus]}</h3><div class="training-options">${focuses.map(x=>`<button data-focus="${x}" class="${plan.focus===x?'active':''}">${label[x]}</button>`).join('')}</div></article><article class="glass training-card"><span>INTENSIDADE</span><h3>${label[plan.intensity]}</h3><div class="training-options">${intensities.map(x=>`<button data-intensity="${x}" class="${plan.intensity===x?'active':''}">${label[x]}</button>`).join('')}</div></article><article class="glass training-card"><span>DIA DE DESCANSO</span><h3>${plan.restDay?'Programado':'Treino ativo'}</h3><button data-rest class="training-rest ${plan.restDay?'active':''}">${plan.restDay?'REMOVER DESCANSO':'PROGRAMAR DESCANSO'}</button></article></section><section class="glass training-note"><b>Motor conectado</b><p>Ao clicar em <strong>Continuar</strong>, o ciclo diário usa <code>executeTrainingDay</code> ou <code>executeRestDay</code> e conecta carga, recuperação e departamento médico.</p></section>`;host.querySelectorAll<HTMLButtonElement>('[data-focus]').forEach(b=>b.onclick=()=>{setClubTrainingPlan(w,c.id,{focus:b.dataset.focus as TrainingFocus,restDay:false});renderTraining()});host.querySelectorAll<HTMLButtonElement>('[data-intensity]').forEach(b=>b.onclick=()=>{setClubTrainingPlan(w,c.id,{intensity:b.dataset.intensity as TrainingIntensity});renderTraining()});host.querySelector<HTMLButtonElement>('[data-rest]')?.addEventListener('click',()=>{setClubTrainingPlan(w,c.id,{restDay:!plan.restDay});renderTraining()})}
document.addEventListener('touchline:view-rendered',event=>{if((event as CustomEvent).detail?.view==='training')queueMicrotask(renderTraining)});
