import type { Club, Player, PlayerAttributes, Position, World } from './engine';
import { emitWorldEvent } from './event-bus';
import { medicalProfile, isUnavailable } from './injuries';
import { clubDressingRoom } from './dressing-room';
import { personalPerformanceFactor } from './human-life';
import { weeklySessionsForDate } from './training-weekly-schedule-v1';

export type SessionType='rest'|'recovery'|'rehabilitation'|'endurance'|'speed'|'technical'|'passing'|'finishing'|'defending'|'positioning'|'pressing'|'transition'|'teamShape'|'attackingUnit'|'defensiveUnit'|'setPieces'|'videoAnalysis'|'opponentSpecific'|'roleWork'|'weakFoot'|'newPosition';
export type SessionIntensity='veryLow'|'low'|'medium'|'high'|'veryHigh';
export type TrainingUnit='all'|'goalkeepers'|'defenders'|'midfielders'|'attackers'|'rehab';
export type MicrocyclePreset='recoveryWeek'|'balanced'|'development'|'tactical'|'physicalBuild'|'congested'|'preMatch';
export type TacticalAxis='buildUp'|'pressing'|'defensiveShape'|'transition'|'setPieces'|'roleFamiliarity';
export type TrainingSession={id:string;type:SessionType;intensity:SessionIntensity;unit:TrainingUnit;durationMinutes:number;focusAttributes:(keyof PlayerAttributes)[];tacticalAxes:TacticalAxis[];load:number;injuryExposure:number;cohesionEffect:number};
export type IndividualTrainingPlan={playerId:string;focus:SessionType;targetPosition?:Position;targetAttribute?:keyof PlayerAttributes;intensity:SessionIntensity;startedDate:string;progress:number;satisfaction:number};
export type PlayerLoadState={playerId:string;acuteLoad:number;chronicLoad:number;readiness:number;fatigue:number;monotony:number;strain:number;last7:number[];last28:number[];lastTrainingDate?:string;overloadDays:number};
export type PlayerTrainingState={playerId:string;tacticalFamiliarity:Record<TacticalAxis,number>;weakFootProgress:number;positionProgress:Partial<Record<Position,number>>;roleProgress:number;individual?:IndividualTrainingPlan;load:PlayerLoadState;lastGainDate?:string};
export type ClubTrainingState={clubId:string;preset:MicrocyclePreset;facilityQuality:number;sportsScience:number;medicalCoordination:number;academyIntegration:number;players:Map<string,PlayerTrainingState>;lastSessionDate?:string;trainingHistory:TrainingDayRecord[]};
export type TrainingDayRecord={date:string;clubId:string;sessions:{type:SessionType;intensity:SessionIntensity;participants:number;avgLoad:number}[];avgReadiness:number;overloaded:number;notes:string[]};
export type TrainingState={clubs:Map<string,ClubTrainingState>};
export type ClubTrainingSnapshot=Omit<ClubTrainingState,'players'> & {players:[string,PlayerTrainingState][]};
export type TrainingSnapshot={clubs:[string,ClubTrainingSnapshot][]};

const states=new WeakMap<World,TrainingState>();
const clamp=(v:number,min=0,max=100)=>Math.max(min,Math.min(max,v));
const intensityFactor:Record<SessionIntensity,number>={veryLow:.35,low:.6,medium:1,high:1.35,veryHigh:1.7};
const attrBySession:Partial<Record<SessionType,(keyof PlayerAttributes)[]>>={endurance:['stamina'],speed:['pace','stamina'],technical:['technique','passing'],passing:['passing','technique','decisions'],finishing:['finishing','technique','decisions'],defending:['tackling','positioning','stamina'],positioning:['positioning','decisions'],pressing:['stamina','tackling','positioning'],transition:['pace','passing','decisions'],teamShape:['positioning','decisions','passing'],attackingUnit:['finishing','passing','technique'],defensiveUnit:['tackling','positioning','stamina'],setPieces:['technique','passing','finishing'],roleWork:['positioning','decisions','technique'],weakFoot:['technique','passing','finishing'],newPosition:['positioning','decisions']};
const tacticalBySession:Partial<Record<SessionType,TacticalAxis[]>>={positioning:['defensiveShape'],pressing:['pressing'],transition:['transition'],teamShape:['buildUp','defensiveShape'],attackingUnit:['buildUp','transition'],defensiveUnit:['defensiveShape','pressing'],setPieces:['setPieces'],videoAnalysis:['buildUp','defensiveShape'],opponentSpecific:['defensiveShape','transition'],roleWork:['roleFamiliarity'],newPosition:['roleFamiliarity']};

function initialPlayer(id:string):PlayerTrainingState{return{playerId:id,tacticalFamiliarity:{buildUp:50,pressing:50,defensiveShape:50,transition:50,setPieces:50,roleFamiliarity:45},weakFootProgress:0,positionProgress:{},roleProgress:0,load:{playerId:id,acuteLoad:0,chronicLoad:0,readiness:82,fatigue:10,monotony:0,strain:0,last7:[],last28:[],overloadDays:0}};}
function initialClub(club:Club):ClubTrainingState{return{clubId:club.id,preset:'balanced',facilityQuality:clamp(45+club.reputation*.45),sportsScience:clamp(40+club.reputation*.4),medicalCoordination:clamp(45+club.reputation*.38),academyIntegration:clamp(35+club.reputation*.42),players:new Map(),trainingHistory:[]};}
export function trainingState(world:World):TrainingState{let s=states.get(world);if(!s){s={clubs:new Map()};states.set(world,s);}for(const club of world.clubs){if(!s.clubs.has(club.id))s.clubs.set(club.id,initialClub(club));const c=s.clubs.get(club.id)!;for(const p of club.players)if(!c.players.has(p.id))c.players.set(p.id,initialPlayer(p.id));}return s;}
export function clubTraining(world:World,clubId:string){return trainingState(world).clubs.get(clubId);}
export function setMicrocyclePreset(world:World,clubId:string,preset:MicrocyclePreset){const c=clubTraining(world,clubId);if(c)c.preset=preset;}
export function setIndividualTraining(world:World,clubId:string,playerId:string,input:Omit<IndividualTrainingPlan,'playerId'|'startedDate'|'progress'|'satisfaction'>,date:string){const p=clubTraining(world,clubId)?.players.get(playerId);if(p)p.individual={...input,playerId,startedDate:date,progress:0,satisfaction:65};}

function mk(type:SessionType,intensity:SessionIntensity,unit:TrainingUnit='all',durationMinutes=75):TrainingSession{const base=type==='rest'?0:type==='recovery'||type==='videoAnalysis'?12:type==='rehabilitation'?16:['endurance','speed','pressing'].includes(type)?42:28;const exposure=['speed','endurance','pressing'].includes(type)?1.45:['defending','transition','attackingUnit','defensiveUnit'].includes(type)?1.1:(type==='rehabilitation'||type==='recovery')?.35:.7;return{id:`${type}-${intensity}-${unit}-${durationMinutes}`,type,intensity,unit,durationMinutes,focusAttributes:attrBySession[type]??[],tacticalAxes:tacticalBySession[type]??[],load:base*intensityFactor[intensity]*(durationMinutes/75),injuryExposure:exposure*intensityFactor[intensity],cohesionEffect:['teamShape','attackingUnit','defensiveUnit','setPieces'].includes(type)?2:type==='rest'?0:1};}
function dayPlan(c:ClubTrainingState,next?:number,last?:number,congested=false):TrainingSession[]{if(last!==undefined&&last<=1)return[mk('recovery','low'),mk('videoAnalysis','veryLow')];if(next!==undefined&&next<=1)return[mk('teamShape','low'),mk('setPieces','low')];if(congested||c.preset==='congested')return[mk('recovery','low'),mk('opponentSpecific','low')];if(c.preset==='recoveryWeek')return[mk('recovery','low'),mk('technical','low')];if(c.preset==='development')return[mk('technical','medium'),mk('passing','medium'),mk('roleWork','low')];if(c.preset==='tactical')return[mk('teamShape','medium'),mk('pressing','medium'),mk('transition','medium')];if(c.preset==='physicalBuild')return[mk('endurance','high'),mk('speed','medium'),mk('recovery','low')];if(c.preset==='preMatch')return[mk('opponentSpecific','medium'),mk('teamShape','low'),mk('setPieces','low')];return[mk('technical','medium'),mk('teamShape','medium'),mk('attackingUnit','low'),mk('defensiveUnit','low')];}
function unitFor(pos:Position):TrainingUnit{return pos==='GK'?'goalkeepers':['RB','CB','LB'].includes(pos)?'defenders':['DM','CM','AM'].includes(pos)?'midfielders':'attackers';}
function allowed(world:World,p:Player,s:TrainingSession){const active=medicalProfile(world,p.id)?.activeInjuries??[];if(active.length){const phases=new Set(active.map(i=>i.phase));if(phases.has('acute')||phases.has('immobilization'))return s.type==='rest';if(phases.has('rehab'))return['rehabilitation','recovery','videoAnalysis'].includes(s.type);if(phases.has('returnToTraining'))return['rehabilitation','recovery','videoAnalysis','positioning','roleWork'].includes(s.type);}return s.unit==='all'||s.unit==='rehab'&&active.length>0||unitFor(p.position)===s.unit;}
function ageFactor(age:number){return age<=18?1.45:age<=21?1.28:age<=24?1.12:age<=29?1:age<=32?.78:age<=35?.55:.38;}
function ratio(l:PlayerLoadState){return l.chronicLoad<=4?1:l.acuteLoad/l.chronicLoad;}
function updateLoad(l:PlayerLoadState,daily:number,condition:number,science:number){l.last7.push(daily);if(l.last7.length>7)l.last7.shift();l.last28.push(daily);if(l.last28.length>28)l.last28.shift();l.acuteLoad=l.last7.reduce((a,b)=>a+b,0)/Math.max(1,l.last7.length);l.chronicLoad=l.last28.reduce((a,b)=>a+b,0)/Math.max(1,l.last28.length);const avg=l.acuteLoad,variance=l.last7.reduce((s,x)=>s+(x-avg)**2,0)/Math.max(1,l.last7.length),sd=Math.sqrt(variance);l.monotony=sd<1?3:clamp(avg/sd,0,3);l.strain=l.last7.reduce((a,b)=>a+b,0)*l.monotony;const r=ratio(l),over=Math.max(0,r-1.25)*32+Math.max(0,l.strain-1100)/55;l.fatigue=clamp(l.fatigue*.82+daily*.34+over*.18-(science-50)*.025);l.readiness=clamp(condition-l.fatigue*.42-(r>1.5?8:0)+(science-50)*.06,10,100);l.overloadDays=r>1.5||l.strain>1500?l.overloadDays+1:Math.max(0,l.overloadDays-1);}
function gainChance(world:World,club:Club,p:Player,ps:PlayerTrainingState,s:TrainingSession){const chem=(clubDressingRoom(world,club.id)?.chemistry??55)/100,readiness=ps.load.readiness/100,gap=Math.max(0,p.potentialAbility-p.currentAbility),ceiling=gap<=0?.2:clamp(.5+gap/35,.55,1.35),facility=(clubTraining(world,club.id)?.facilityQuality??50)/100;return .0085*intensityFactor[s.intensity]*ageFactor(p.age)*ceiling*(.72+facility*.42)*(.84+chem*.22)*(.68+readiness*.4)*personalPerformanceFactor(world,p.id);}
function applyLearning(world:World,club:Club,p:Player,ps:PlayerTrainingState,s:TrainingSession){if(s.focusAttributes.length&&Math.random()<gainChance(world,club,p,ps,s)){const k=s.focusAttributes[Math.floor(Math.random()*s.focusAttributes.length)];const cap=Math.min(99,Math.max(p.attributes[k],p.potentialAbility+6));if(p.attributes[k]<cap){p.attributes[k]++;ps.lastGainDate=ps.load.lastTrainingDate;}}const learn=(.18+s.durationMinutes/320)*intensityFactor[s.intensity]*(.7+p.attributes.decisions/180);for(const a of s.tacticalAxes)ps.tacticalFamiliarity[a]=clamp(ps.tacticalFamiliarity[a]+learn);if(s.type==='roleWork')ps.roleProgress=clamp(ps.roleProgress+learn*.9);if(s.type==='weakFoot')ps.weakFootProgress=clamp(ps.weakFootProgress+learn*.7);if(s.type==='newPosition'&&ps.individual?.targetPosition){const pos=ps.individual.targetPosition;ps.positionProgress[pos]=clamp((ps.positionProgress[pos]??0)+learn*.65);}}
function individual(world:World,club:Club,p:Player,ps:PlayerTrainingState){const plan=ps.individual;if(!plan)return 0;if(isUnavailable(world,p.id)){plan.satisfaction=clamp(plan.satisfaction-.1);return 0;}const f=intensityFactor[plan.intensity],load=9*f;plan.progress=clamp(plan.progress+.16*f*ageFactor(p.age)*(clubTraining(world,club.id)!.facilityQuality/70));if(plan.targetAttribute&&Math.random()<.0025*f&&p.attributes[plan.targetAttribute]<99)p.attributes[plan.targetAttribute]++;if(plan.focus==='weakFoot')ps.weakFootProgress=clamp(ps.weakFootProgress+.2*f);if(plan.focus==='newPosition'&&plan.targetPosition)ps.positionProgress[plan.targetPosition]=clamp((ps.positionProgress[plan.targetPosition]??0)+.14*f);if(plan.focus==='roleWork')ps.roleProgress=clamp(ps.roleProgress+.18*f);plan.satisfaction=clamp(plan.satisfaction+(ps.load.readiness>65?.08:-.16));return load;}

export function executeTrainingDay(world:World,date:string,ctx:{daysToNextMatch?:number;daysSinceLastMatch?:number;matchesNext7?:number}={}){const state=trainingState(world);for(const club of world.clubs){const cs=state.clubs.get(club.id)!,scheduled=weeklySessionsForDate(world,club.id,date),usingWeekly=scheduled!==undefined,sessions=(scheduled??dayPlan(cs,ctx.daysToNextMatch,ctx.daysSinceLastMatch,(ctx.matchesNext7??0)>=2)).map(s=>mk(s.type,s.intensity,s.unit,s.durationMinutes));let sum=0,count=0,overloaded=0;for(const p of club.players){const ps=cs.players.get(p.id)!;let load=0;const attended:TrainingSession[]=[];for(const s of sessions){if(!allowed(world,p,s))continue;load+=s.load*(.82+(100-p.condition)/220);attended.push(s);applyLearning(world,club,p,ps,s);}if(!usingWeekly||sessions.length)load+=individual(world,club,p,ps);updateLoad(ps.load,load,p.condition,cs.sportsScience);ps.load.lastTrainingDate=date;p.condition=Math.round(clamp(p.condition-load*.07+(sessions.length===0?5:attended.some(s=>s.type==='recovery')?5:1),30,100));sum+=ps.load.readiness;count++;const pressure=clamp((ratio(ps.load)-1.15)*18+ps.load.overloadDays*2+Math.max(0,ps.load.strain-1200)/80+attended.reduce((a,s)=>a+s.injuryExposure,0),0,50);if(pressure>18)overloaded++;if(pressure>34&&Math.random()<.015)emitWorldEvent(world,{type:'TrainingOverloadWarning',date,clubIds:[club.id],playerIds:[p.id],importance:3,summary:`Carga de treino elevada para ${p.name}.`,payload:{ratio:Number(ratio(ps.load).toFixed(2)),strain:Math.round(ps.load.strain),readiness:Math.round(ps.load.readiness),riskPressure:Math.round(pressure)}});}const rows=sessions.map(s=>({type:s.type,intensity:s.intensity,participants:club.players.filter(p=>allowed(world,p,s)).length,avgLoad:Number(s.load.toFixed(1))}));const rec:TrainingDayRecord={date,clubId:club.id,sessions:rows,avgReadiness:Math.round(sum/Math.max(1,count)),overloaded,notes:[usingWeekly?(sessions.length?'Grade semanal personalizada executada.':'Grade semanal: descanso integral.'):(ctx.matchesNext7??0)>=2?'Microciclo adaptado por calendário congestionado.':'Carga normal de microciclo.',!usingWeekly&&ctx.daysToNextMatch!==undefined&&ctx.daysToNextMatch<=1?'Sessões reduzidas por proximidade da partida.':''].filter(Boolean)};cs.trainingHistory.push(rec);if(cs.trainingHistory.length>180)cs.trainingHistory.splice(0,cs.trainingHistory.length-180);cs.lastSessionDate=date;emitWorldEvent(world,{type:'TrainingCompleted',date,clubIds:[club.id],importance:overloaded>=4?2:1,tags:['training',cs.preset,...(usingWeekly?['weekly-schedule']:[])],summary:`${club.name} concluiu ${sessions.length} sessões de treino.`,payload:{preset:cs.preset,weeklySchedule:usingWeekly,sessions:rows,avgReadiness:rec.avgReadiness,overloaded}});}}
export function playerReadiness(world:World,playerId:string){for(const c of trainingState(world).clubs.values()){const p=c.players.get(playerId);if(p)return p.load.readiness;}return 75;}
export function tacticalFamiliarity(world:World,clubId:string){const c=clubTraining(world,clubId);if(!c||!c.players.size)return 50;let sum=0,n=0;for(const p of c.players.values())for(const v of Object.values(p.tacticalFamiliarity)){sum+=v;n++;}return sum/Math.max(1,n);}
export function trainingPerformanceFactor(world:World,playerId:string){return clamp(.94+(playerReadiness(world,playerId)-50)/500,.9,1.06);}
export function snapshotTrainingState(world:World):TrainingSnapshot{const s=trainingState(world);return{clubs:[...s.clubs.entries()].map(([id,c])=>[id,{...c,players:[...c.players.entries()].map(([pid,p])=>[pid,{...p,tacticalFamiliarity:{...p.tacticalFamiliarity},positionProgress:{...p.positionProgress},individual:p.individual?{...p.individual}:undefined,load:{...p.load,last7:[...p.load.last7],last28:[...p.load.last28]}}]),trainingHistory:c.trainingHistory.map(r=>({...r,sessions:r.sessions.map(x=>({...x})),notes:[...r.notes]}))}])};}
export function restoreTrainingState(world:World,snapshot?:TrainingSnapshot){if(!snapshot)return;states.set(world,{clubs:new Map(snapshot.clubs.map(([id,c])=>[id,{...c,players:new Map(c.players.map(([pid,p])=>[pid,{...p,tacticalFamiliarity:{...p.tacticalFamiliarity},positionProgress:{...p.positionProgress},individual:p.individual?{...p.individual}:undefined,load:{...p.load,last7:[...p.load.last7],last28:[...p.load.last28]}}])),trainingHistory:c.trainingHistory.map(r=>({...r,sessions:r.sessions.map(x=>({...x})),notes:[...r.notes]}))}]))});}
