import './transfer-beta-ui-v1.css';

type Player={wikidataId:string;name:string;dateOfBirth?:string;nationality?:string;heightCm?:number;position?:string;roleGroup?:string;clubName:string};
type Snapshot={season:number;rosters:Array<{name:string;players:Player[]}>};
let snapshot:Snapshot|undefined;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const hash=(text:string)=>{let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0)};
const age=(dob?:string)=>dob?Math.max(16,2026-Number(dob.slice(0,4))):24;
const role=(p:Player)=>{if(p.position==='GK')return'GK';if(['RB','CB','LB'].includes(p.position||''))return'DEF';if(['DM','CM','AM'].includes(p.position||''))return'MEI';if(['RW','LW','ST'].includes(p.position||''))return'ATA';return p.roleGroup==='goalkeeper'?'GK':p.roleGroup==='defender'?'DEF':p.roleGroup==='midfielder'?'MEI':p.roleGroup==='forward'?'ATA':'—'};
function engineValue(p:Player){const seed=hash(p.wikidataId||p.name),a=age(p.dateOfBirth),base=2+(seed%230)/10;return Math.max(.4,Math.round(base*(a<=23?1.35:a>=31?.66:1)*10)/10)}
function shortlist(){try{return new Set<string>(JSON.parse(localStorage.getItem('touchline-shortlist-v1')||'[]'))}catch{return new Set<string>()}}
function save(s:Set<string>){localStorage.setItem('touchline-shortlist-v1',JSON.stringify([...s]))}
async function load(){if(snapshot)return snapshot;const r=await fetch('/data/rosters/brazil-serie-a-2026.json',{cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);snapshot=await r.json() as Snapshot;return snapshot}
async function renderMarket(){const view=document.querySelector<HTMLElement>('.game-stage main.view');if(!view)return;view.innerHTML=`<header class="view-hero"><div><span class="kicker">RECRUTAMENTO · BETA</span><h1>Mercado & Observação</h1><p>Jogadores com identidade e vínculo rastreáveis no snapshot 2026. Valores são estimativas do engine; negociações financeiras ainda não estão ativadas.</p></div><div class="hero-glow"></div></header><section class="glass transfer-loading">Carregando base factual...</section>`;try{const s=await load(),players=s.rosters.flatMap(r=>(r.players||[]).map(p=>({...p,clubName:p.clubName||r.name}))),watch=shortlist();view.innerHTML=`<header class="view-hero"><div><span class="kicker">RECRUTAMENTO · BETA</span><h1>Mercado & Observação</h1><p>${players.length} atletas factuais rastreáveis · shortlist persistente neste navegador.</p></div><div class="hero-glow"></div></header><section class="transfer-metrics"><article class="glass"><span>BASE OBSERVÁVEL</span><b>${players.length}</b><small>snapshot ${s.season}</small></article><article class="glass"><span>NA SHORTLIST</span><b data-shortlist-count>${watch.size}</b><small>acompanhamento local</small></article><article class="glass"><span>NEGOCIAÇÕES</span><b>BETA</b><small>somente observação nesta versão</small></article></section><section class="glass transfer-panel"><div class="transfer-toolbar"><input data-market-search placeholder="Buscar jogador, clube ou nacionalidade"><select data-market-role><option value="">Todas as funções</option><option>GK</option><option>DEF</option><option>MEI</option><option>ATA</option></select><button data-only-shortlist>SHORTLIST</button></div><div class="transfer-table-wrap"><table class="transfer-table"><thead><tr><th>Jogador</th><th>Clube</th><th>Função</th><th>Idade</th><th>Nacionalidade</th><th>Valor engine</th><th></th></tr></thead><tbody>${players.sort((a,b)=>engineValue(b)-engineValue(a)).map(p=>{const r=role(p),v=engineValue(p),on=watch.has(p.wikidataId);return `<tr data-market-row data-key="${esc(p.wikidataId)}" data-search="${esc(`${p.name} ${p.clubName} ${p.nationality||''}`.toLowerCase())}" data-role="${r}"><td><b>${esc(p.name)}</b><small>${esc(p.position||p.roleGroup||'função ampla')}</small></td><td>${esc(p.clubName)}</td><td><mark>${r}</mark></td><td>${age(p.dateOfBirth)}</td><td>${esc(p.nationality||'—')}</td><td><b>R$ ${v.toLocaleString('pt-BR')} mi</b><small>estimativa</small></td><td><button class="watch ${on?'on':''}" data-watch="${esc(p.wikidataId)}">${on?'★ ACOMPANHANDO':'☆ OBSERVAR'}</button></td></tr>`}).join('')}</tbody></table></div></section>`;bindMarket()}catch(e){view.innerHTML+=`<section class="glass transfer-error">Não foi possível carregar o snapshot: ${esc(e)}</section>`}}
function bindMarket(){const rows=()=>[...document.querySelectorAll<HTMLElement>('[data-market-row]')],search=document.querySelector<HTMLInputElement>('[data-market-search]'),filter=document.querySelector<HTMLSelectElement>('[data-market-role]'),only=document.querySelector<HTMLButtonElement>('[data-only-shortlist]');let shortlistOnly=false;const apply=()=>{const q=(search?.value||'').trim().toLowerCase(),r=filter?.value||'',watch=shortlist();rows().forEach(row=>row.hidden=Boolean((q&&!row.dataset.search?.includes(q))||(r&&row.dataset.role!==r)||(shortlistOnly&&!watch.has(row.dataset.key||''))))};search?.addEventListener('input',apply);filter?.addEventListener('change',apply);only?.addEventListener('click',()=>{shortlistOnly=!shortlistOnly;only.classList.toggle('active',shortlistOnly);apply()});document.querySelectorAll<HTMLButtonElement>('[data-watch]').forEach(btn=>btn.addEventListener('click',()=>{const s=shortlist(),key=btn.dataset.watch!;s.has(key)?s.delete(key):s.add(key);save(s);btn.classList.toggle('on',s.has(key));btn.textContent=s.has(key)?'★ ACOMPANHANDO':'☆ OBSERVAR';const count=document.querySelector('[data-shortlist-count]');if(count)count.textContent=String(s.size);apply()}))}
document.addEventListener('click',e=>{const btn=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-view="transfers"]');if(btn)queueMicrotask(()=>void renderMarket())});
