import type { Position, World } from './engine';
import { loadPublicPeople2026 } from './real-world-2026-loader-v1';
import type { RealPlayerSeedV2 } from './real-world-player-import-v2';
import { footballDataSnapshot } from './world-football-data-v1';
import { globalFootballMetadata } from './world-football-global-metadata-v1';
import { worldPeopleStatus } from './world-people-runtime-v1';

export type TierARosterPlayer={wikidataId?:string;name:string;dateOfBirth?:string;nationality?:string;heightCm?:number;roleGroup?:'goalkeeper'|'defender'|'midfielder'|'forward';position?:Position;clubName:string;clubWikidataId?:string;membershipStart?:string;membershipRank?:string;provenance?:Record<string,unknown>};
export type TierARosterSnapshot={version:number;generatedAt:string;season:number;tier:'A';sources:Array<{name:string;license:string;membershipProperty?:string;commit?:string}>;players:TierARosterPlayer[];clubs:Array<{wikidataId:string;name:string;countryId:string;players:TierARosterPlayer[]}>;counts:{countries:number;countriesResolved:number;clubs:number;players:number}};
export type TierARosterRuntimeStatus={state:'idle'|'loading'|'ready'|'unavailable';players:number;clubs:number;merged:number;inserted:number;resolvedClubAssignments:number;unresolvedClubAssignments:number;generatedAt?:string;error?:string};

const rolePosition:Record<string,Position>={goalkeeper:'GK',defender:'CB',midfielder:'CM',forward:'ST'};
const running=new WeakSet<World>(),hydrated=new WeakSet<World>(),statuses=new WeakMap<World,TierARosterRuntimeStatus>();
const emptyStatus=():TierARosterRuntimeStatus=>({state:'idle',players:0,clubs:0,merged:0,inserted:0,resolvedClubAssignments:0,unresolvedClubAssignments:0});
export function tierARosterStatus(world:World){return statuses.get(world)??emptyStatus()}
const status=(world:World,patch:Partial<TierARosterRuntimeStatus>)=>{const next={...tierARosterStatus(world),...patch};statuses.set(world,next);return next};
async function json<T>(url:string){const r=await fetch(new URL(url.replace(/^\/+/,''),document.baseURI).toString(),{cache:'no-cache'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json() as Promise<T>}
function seedFrom(player:TierARosterPlayer,snapshot:TierARosterSnapshot):RealPlayerSeedV2&{positionEstimated?:boolean;positionBasis?:string}{const factualPosition=player.position,position=factualPosition??rolePosition[player.roleGroup??'']??'CM';return{externalIds:player.wikidataId?{wikidata:player.wikidataId}:undefined,name:player.name,dateOfBirth:player.dateOfBirth,heightCm:player.heightCm,position,secondaryPositions:[],nationalityCountryIds:player.nationality?[player.nationality]:[],clubId:player.clubName,sourceAssignment:{clubId:player.clubName},positionEstimated:!factualPosition,positionBasis:factualPosition?'Wikidata specific role':player.roleGroup?`Wikidata/OpenFootball broad ${player.roleGroup}`:'engine fallback',provenance:[{source:'wikidata-membership',sourceId:player.wikidataId,snapshotDate:snapshot.generatedAt.slice(0,10),confidence:player.membershipRank==='PreferredRank'?99:94,license:'CC0'}]}}
async function hydrate(){const world=window.__touchlineWorld;if(!world||running.has(world)||hydrated.has(world))return;if(worldPeopleStatus(world).state!=='ready'||!globalFootballMetadata(world))return;running.add(world);status(world,{state:'loading'});try{const snapshot=await json<TierARosterSnapshot>('data/rosters/world-tier-a-2026.json');if(snapshot.version<1||snapshot.tier!=='A'||!Array.isArray(snapshot.players))throw new Error('invalid Tier A roster snapshot');const canonicalClubs=footballDataSnapshot(world).clubs.length,seeds=snapshot.players.map(p=>seedFrom(p,snapshot)),report=loadPublicPeople2026(world,{players:seeds,staff:[],manifest:{kind:'world-tier-a-rosters',generatedAt:snapshot.generatedAt,sources:snapshot.sources,counts:snapshot.counts}}),resolved=report.assignments.club.exact+report.assignments.club.alias;hydrated.add(world);const current=status(world,{state:'ready',players:snapshot.players.length,clubs:snapshot.clubs.length,merged:report.players.merged,inserted:report.players.inserted,resolvedClubAssignments:resolved,unresolvedClubAssignments:report.assignments.club.unresolved+report.assignments.club.ambiguous,generatedAt:snapshot.generatedAt,error:undefined});window.dispatchEvent(new CustomEvent('touchline:world-rosters-ready',{detail:{...current,canonicalClubs}}))}catch(e){const current=status(world,{state:'unavailable',error:e instanceof Error?e.message:String(e)});window.dispatchEvent(new CustomEvent('touchline:world-rosters-unavailable',{detail:current}))}finally{running.delete(world)}}
function schedule(){queueMicrotask(()=>void hydrate())}
window.addEventListener('touchline:world-people-ready',schedule);window.addEventListener('touchline:world-football-global-metadata-ready',schedule);window.addEventListener('touchline:save-loaded',()=>{const world=window.__touchlineWorld;if(world)hydrated.delete(world);schedule()});window.addEventListener('touchline:world-ready',schedule);schedule();
