import type { Position, World } from './engine';
import { loadPublicPeople2026 } from './real-world-2026-loader-v1';
import type { RealPlayerSeedV2 } from './real-world-player-import-v2';
import { footballDataSnapshot } from './world-football-data-v1';

export type TierARosterPlayer={wikidataId?:string;name:string;dateOfBirth?:string;nationality?:string;heightCm?:number;roleGroup?:'goalkeeper'|'defender'|'midfielder'|'forward';position?:Position;clubName:string;clubWikidataId?:string;membershipStart?:string;membershipRank?:string;provenance?:Record<string,unknown>};
export type TierARosterSnapshot={version:number;generatedAt:string;season:number;tier:'A';sources:Array<{name:string;license:string;membershipProperty?:string;commit?:string}>;players:TierARosterPlayer[];clubs:Array<{wikidataId:string;name:string;countryId:string;players:TierARosterPlayer[]}>;counts:{countries:number;countriesResolved:number;clubs:number;players:number}};
export type TierARosterRuntimeStatus={state:'idle'|'loading'|'ready'|'unavailable';players:number;clubs:number;merged:number;inserted:number;resolvedClubAssignments:number;unresolvedClubAssignments:number;generatedAt?:string;error?:string};
declare global {interface Window {__touchlineTierARosters?:TierARosterRuntimeStatus}}

const rolePosition:Record<string,Position>={goalkeeper:'GK',defender:'CB',midfielder:'CM',forward:'ST'};
let running=false,hydratedWorld:World|undefined;
const status=(patch:Partial<TierARosterRuntimeStatus>)=>{const current=window.__touchlineTierARosters??{state:'idle',players:0,clubs:0,merged:0,inserted:0,resolvedClubAssignments:0,unresolvedClubAssignments:0};window.__touchlineTierARosters={...current,...patch};return window.__touchlineTierARosters};
async function json<T>(url:string){const r=await fetch(new URL(url.replace(/^\/+/,''),document.baseURI).toString(),{cache:'no-cache'});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json() as Promise<T>}
function seedFrom(player:TierARosterPlayer,snapshot:TierARosterSnapshot):RealPlayerSeedV2&{positionEstimated?:boolean;positionBasis?:string}{const factualPosition=player.position,position=factualPosition??rolePosition[player.roleGroup??'']??'CM',source=snapshot.sources.find(x=>x.name==='Wikidata');return{externalIds:player.wikidataId?{wikidata:player.wikidataId}:undefined,name:player.name,dateOfBirth:player.dateOfBirth,heightCm:player.heightCm,position,secondaryPositions:[],nationalityCountryIds:player.nationality?[player.nationality]:[],clubId:player.clubName,sourceAssignment:{clubId:player.clubName},positionEstimated:!factualPosition,positionBasis:factualPosition?'Wikidata specific role':player.roleGroup?`Wikidata/OpenFootball broad ${player.roleGroup}`:'engine fallback',provenance:[{source:'Wikidata',sourceId:player.wikidataId,snapshotDate:snapshot.generatedAt.slice(0,10),confidence:player.membershipRank==='PreferredRank'?99:94,license:source?.license??'CC0'}]}}
async function hydrate(){const world=window.__touchlineWorld;if(!world||running||hydratedWorld===world)return;if(window.__touchlinePeopleStatus?.state!=='ready'||!window.__touchlineGlobalMetadata)return;running=true;status({state:'loading'});try{const snapshot=await json<TierARosterSnapshot>('data/rosters/world-tier-a-2026.json');if(snapshot.version<1||snapshot.tier!=='A'||!Array.isArray(snapshot.players))throw new Error('invalid Tier A roster snapshot');const canonicalClubs=footballDataSnapshot(world).clubs.length,seeds=snapshot.players.map(p=>seedFrom(p,snapshot)),report=loadPublicPeople2026(world,{players:seeds,staff:[],manifest:{kind:'world-tier-a-rosters',generatedAt:snapshot.generatedAt,sources:snapshot.sources,counts:snapshot.counts}}),resolved=report.assignments.club.exact+report.assignments.club.alias;hydratedWorld=world;status({state:'ready',players:snapshot.players.length,clubs:snapshot.clubs.length,merged:report.players.merged,inserted:report.players.inserted,resolvedClubAssignments:resolved,unresolvedClubAssignments:report.assignments.club.unresolved+report.assignments.club.ambiguous,generatedAt:snapshot.generatedAt,error:undefined});window.dispatchEvent(new CustomEvent('touchline:world-rosters-ready',{detail:{...window.__touchlineTierARosters,canonicalClubs}}))}catch(e){status({state:'unavailable',error:e instanceof Error?e.message:String(e)});window.dispatchEvent(new CustomEvent('touchline:world-rosters-unavailable',{detail:window.__touchlineTierARosters}))}finally{running=false}}
function schedule(){queueMicrotask(()=>void hydrate())}
window.addEventListener('touchline:world-people-ready',schedule);window.addEventListener('touchline:world-football-global-metadata-ready',schedule);window.addEventListener('touchline:save-loaded',()=>{hydratedWorld=undefined;schedule()});window.addEventListener('touchline:world-ready',schedule);schedule();
