import type { World } from './engine';
import { ensureActiveWorldFootballFoundation } from './world-football-foundation-runtime-v1';
import { canonicalCountryId } from './country-code-v1';
import { alias, footballDataSnapshot, registerClubRecord, registerCompetitionRecord, registerStadiumRecord, resolveFootballEntity, type ClubRecord, type CompetitionKind, type CompetitionRecord, type CompetitionScope, type ConfederationId, type DataProvenance, type StadiumRecord } from './world-football-data-v1';

export type GlobalFootballMetadataReport={files:{clubs:number;leagues:number};parsed:{clubs:number;stadiums:number;competitions:number};registered:{clubs:number;stadiums:number;competitions:number};merged:{clubs:number;competitions:number};skipped:{unknownCountry:number;malformed:number};sourceCommit?:string;license:string};
type Manifest={license:string;repos:Array<{repo:string;commit:string;files:number}>;files:Array<{repo:string;path:string;sha:string;license:string}>};
type ParsedClub={name:string;aliases:string[];countryName:string;cityName?:string;foundedYear?:number;stadiumName?:string;sourcePath:string;sourceSha:string};
type ParsedCompetition={code:string;name:string;aliases:string[];countryName?:string;confederationId?:ConfederationId;scope:CompetitionScope;kind:CompetitionKind;sourcePath:string;sourceSha:string};

declare global { interface Window { __touchlineGlobalMetadata?:GlobalFootballMetadataReport;__touchlineWorld?:World } }
const ROOT='/data/openfootball-global';
const norm=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const slug=(s:string)=>norm(s).replace(/ /g,'-').slice(0,100);
const clean=(s:string)=>s.replace(/\s*##.*$/,'').replace(/\s+#.*$/,'').trim();
const provenance=(repo:string,path:string,sha:string):DataProvenance=>({sourceId:repo,sourceEntityId:sha,sourcePath:path,license:'CC0-1.0',historical:true,confidence:88});
const rules=(calendarPattern:'calendar-year'|'cross-year'):CompetitionRecord['rules']=>({pointsWin:3,pointsDraw:1,tiebreakers:['goalDifference','goalsFor','headToHead'],promotion:[],relegation:[],qualification:[],calendarPattern});
function publicUrl(path:string){return new URL(path.replace(/^\//,''),document.baseURI).toString()}
async function text(path:string){const r=await fetch(publicUrl(path),{cache:'force-cache'});if(!r.ok)throw new Error(`${r.status} ${path}`);return r.text()}
async function json<T>(path:string){return JSON.parse(await text(path)) as T}
function countryResolver(w:World){const teams=footballDataSnapshot(w).nationalTeams,valid=new Set(teams.map(t=>t.countryId)),byName=new Map<string,string>();for(const t of teams)for(const v of [t.countryId,t.name,...t.aliases.map(a=>a.value)])if(!byName.has(norm(v)))byName.set(norm(v),t.countryId);return(raw?:string)=>{if(!raw)return;const direct=canonicalCountryId(raw);if(direct&&valid.has(direct))return direct;return byName.get(norm(raw))??direct}}
function parseClubFile(raw:string,sourcePath:string,sourceSha:string){let countryName='',current:ParsedClub|undefined;const out:ParsedClub[]=[];for(const original of raw.split(/\r?\n/)){const trimmed=original.trim();if(!trimmed||trimmed.startsWith('#')||/^[-=]{5,}$/.test(trimmed))continue;const heading=trimmed.match(/^=+\s*([^=]+?)\s*=*$/);if(heading){countryName=heading[1].trim();current=undefined;continue}if(/^\s*\|/.test(original)&&current){for(const a of trimmed.replace(/^\|/,'').split('|').map(clean).filter(Boolean))if(!current.aliases.includes(a))current.aliases.push(a);continue}if(/^\s/.test(original)||trimmed.startsWith('|'))continue;const line=clean(trimmed),parts=line.split(',').map(x=>x.trim()).filter(Boolean),name=clean(parts[0]??'');if(!name||name.length<2||!countryName)continue;const year=line.match(/(?:^|,|\s)((?:18|19|20)\d{2})(?:\s|,|$)/)?.[1],at=line.match(/@\s*([^,]+)/),stadiumName=at?clean(at[1]):undefined;let cityName:string|undefined;if(at){const after=line.slice((at.index??0)+at[0].length).replace(/^\s*,\s*/,'');cityName=clean(after.split(',')[0]??'')||undefined}else if(parts.length>1){const candidate=parts.find((p,i)=>i>0&&!/^\d{4}$/.test(p)&&!p.startsWith('@'));if(candidate)cityName=clean(candidate)}current={name,aliases:[],countryName,cityName,foundedYear:year?Number(year):undefined,stadiumName,sourcePath,sourceSha};out.push(current)}return out}
function inferConfederation(path:string,code:string,name:string):ConfederationId|undefined{const s=`${path} ${code} ${name}`.toLowerCase();if(s.includes('uefa')||s.includes('/europe/'))return'UEFA';if(s.includes('conmebol')||s.includes('/south-america/'))return'CONMEBOL';if(s.includes('concacaf')||s.includes('/north-america/')||s.includes('/central-america/')||s.includes('/caribbean/'))return'CONCACAF';if(s.includes('/africa/')||/^caf\./.test(code))return'CAF';if(s.includes('/asia/')||s.includes('/middle-east/')||/^afc\./.test(code))return'AFC';if(s.includes('/pacific/')||/^ofc\./.test(code))return'OFC';return undefined}
function competitionKind(code:string,name:string):CompetitionKind{const s=`${code} ${name}`.toLowerCase();if(/quali|qualification|qualifying/.test(s))return'qualifier';if(/super\s*cup|supercopa|super cup|super$/.test(s))return'supercup';if(/cup|copa|coppa|pokal|ta[cç]a|trophy/.test(s))return'cup';if(/league|liga|bundesliga|premier|division|serie|ligue|eredivisie/.test(s))return'league';return'tournament'}
function parseLeagueFile(raw:string,sourcePath:string,sourceSha:string,resolveCountry:(x?:string)=>string|undefined){let section='',current:ParsedCompetition|undefined;const out:ParsedCompetition[]=[];for(const original of raw.split(/\r?\n/)){const trimmed=original.trim();if(!trimmed||trimmed.startsWith('#')||/^[-=]{5,}$/.test(trimmed))continue;const heading=trimmed.match(/^=+\s*([^=]+?)\s*=*$/);if(heading){section=heading[1].trim();current=undefined;continue}if(/^\s*\|/.test(original)&&current){for(const a of trimmed.replace(/^\|/,'').split('|').map(clean).filter(Boolean))if(!current.aliases.includes(a))current.aliases.push(a);continue}if(/^\s/.test(original)||trimmed.startsWith('|'))continue;const line=clean(trimmed),m=line.match(/^(\S+)\s+(?:(?:\d{4}(?:\/\d{2})?(?:-[^\s]+)?)\s+)?(.+?)\s*$/);if(!m)continue;const code=m[1],name=m[2].replace(/^\d{4}(?:\/\d{2})?(?:-[^\s]+)?\s+/,'').trim();if(!name||name.length<3)continue;const countryId=resolveCountry(section),confederationId=inferConfederation(sourcePath,code,name),national=/^world(?:\.|$)|^euro(?:\.|$)|^southamerica$|^northamerica$|^asia$|^africa$|^paf?icic$|nations league/i.test(`${code} ${name}`),scope:CompetitionScope=countryId?'domestic':national?'international':'continental';current={code,name,aliases:[],countryName:countryId?section:undefined,confederationId,scope,kind:competitionKind(code,name),sourcePath,sourceSha};out.push(current)}return out}
function mergeAliases(existing:string[],extra:string[]){return[...new Map([...existing,...extra].map(x=>[norm(x),x])).values()]}
export async function loadGlobalFootballMetadata(world:World):Promise<GlobalFootballMetadataReport>{ensureActiveWorldFootballFoundation(world);const manifest=await json<Manifest>(`${ROOT}/manifest.json`);if(manifest.license!=='CC0-1.0')throw new Error(`Licença global não autorizada: ${manifest.license}`);const clubFiles=manifest.files.filter(f=>f.repo==='openfootball/clubs'&&/\.clubs\.txt$/i.test(f.path)),leagueFiles=manifest.files.filter(f=>f.repo==='openfootball/leagues'&&/leagues\.txt$/i.test(f.path)),resolveCountry=countryResolver(world),report:GlobalFootballMetadataReport={files:{clubs:clubFiles.length,leagues:leagueFiles.length},parsed:{clubs:0,stadiums:0,competitions:0},registered:{clubs:0,stadiums:0,competitions:0},merged:{clubs:0,competitions:0},skipped:{unknownCountry:0,malformed:0},sourceCommit:manifest.repos.find(r=>r.repo==='openfootball/clubs')?.commit,license:manifest.license};
 const parsedClubs=(await Promise.all(clubFiles.map(async f=>parseClubFile(await text(`${ROOT}/openfootball__clubs/${f.path}`),f.path,f.sha)))).flat();report.parsed.clubs=parsedClubs.length;for(const row of parsedClubs){const countryId=resolveCountry(row.countryName);if(!countryId){report.skipped.unknownCountry++;continue}const sourceProv=provenance('openfootball/clubs',row.sourcePath,row.sourceSha),existingId=resolveFootballEntity(world,row.name).find(id=>footballDataSnapshot(world).clubs.some(c=>c.id===id&&c.countryId===countryId)),existing=existingId?footballDataSnapshot(world).clubs.find(c=>c.id===existingId):undefined;let stadiumId:string|undefined;if(row.stadiumName){const sid=resolveFootballEntity(world,row.stadiumName).find(id=>footballDataSnapshot(world).stadiums.some(s=>s.id===id&&s.countryId===countryId))??`of-stadium-${countryId.toLowerCase()}-${slug(row.stadiumName)}`;const old=footballDataSnapshot(world).stadiums.find(s=>s.id===sid),stadium:StadiumRecord=old?{...old,aliases:old.aliases,ownerClubIds:old.ownerClubIds,provenance:[...old.provenance,sourceProv]}:{id:sid,name:row.stadiumName,aliases:[],countryId,cityName:row.cityName,ownerClubIds:[],provenance:[sourceProv]};registerStadiumRecord(world,stadium);stadiumId=sid;if(!old)report.registered.stadiums++}
  if(existing){registerClubRecord(world,{...existing,aliases:mergeAliases(existing.aliases.map(a=>a.value),row.aliases).map(x=>alias(x)),cityName:existing.cityName??row.cityName,foundedYear:existing.foundedYear??row.foundedYear,stadiumIds:[...new Set([...existing.stadiumIds,...(stadiumId?[stadiumId]:[])])],provenance:[...existing.provenance,sourceProv]});report.merged.clubs++}else{const id=`of-club-${countryId.toLowerCase()}-${slug(row.name)}`,record:ClubRecord={id,name:row.name,aliases:row.aliases.map(x=>alias(x)),countryId,cityName:row.cityName,foundedYear:row.foundedYear,active:true,stadiumIds:stadiumId?[stadiumId]:[],historicalNames:[],provenance:[sourceProv]};registerClubRecord(world,record);report.registered.clubs++}}
 report.parsed.stadiums=report.registered.stadiums;
 const parsedCompetitions=(await Promise.all(leagueFiles.map(async f=>parseLeagueFile(await text(`${ROOT}/openfootball__leagues/${f.path}`),f.path,f.sha,resolveCountry)))).flat();report.parsed.competitions=parsedCompetitions.length;for(const row of parsedCompetitions){const countryId=row.countryName?resolveCountry(row.countryName):undefined;if(row.scope==='domestic'&&!countryId){report.skipped.unknownCountry++;continue}const sourceProv=provenance('openfootball/leagues',row.sourcePath,row.sourceSha),snapshot=footballDataSnapshot(world),existingId=resolveFootballEntity(world,row.name).find(id=>snapshot.competitions.some(c=>c.id===id)),existing=existingId?snapshot.competitions.find(c=>c.id===existingId):undefined;if(existing){registerCompetitionRecord(world,{...existing,aliases:mergeAliases(existing.aliases.map(a=>a.value),row.aliases).map(x=>alias(x)),provenance:[...existing.provenance,sourceProv]});report.merged.competitions++;continue}const calendarPattern=countryId&&['BRA','ARG','URU','PAR','CHI','COL','ECU','PER','BOL','VEN'].includes(countryId)?'calendar-year':'cross-year';registerCompetitionRecord(world,{id:`of-comp-${slug(row.code)}`,name:row.name,aliases:row.aliases.map(x=>alias(x)),scope:row.scope,kind:row.kind,countryId,confederationId:row.confederationId,active:true,rules:rules(calendarPattern),provenance:[sourceProv]});report.registered.competitions++}
 window.__touchlineGlobalMetadata=report;window.dispatchEvent(new CustomEvent('touchline:global-football-metadata-ready',{detail:report}));return report}
const loaded=new WeakSet<World>();async function activate(){const world=window.__touchlineWorld;if(!world||loaded.has(world))return;loaded.add(world);try{await loadGlobalFootballMetadata(world)}catch(error){loaded.delete(world);window.dispatchEvent(new CustomEvent('touchline:global-football-metadata-error',{detail:{message:error instanceof Error?error.message:String(error)}}))}}
if(typeof window!=='undefined'){window.addEventListener('touchline:world-hydrated',()=>void activate());window.addEventListener('touchline:world-ready',()=>void activate());queueMicrotask(()=>void activate())}
