import type { World } from './engine';
import { deterministicRandom, registerCity, registerCountry, worldCore, type WorldGeo } from './world-core-v2';

export type Hemisphere='north'|'south'|'equatorial';
export type ClimateNormals={monthlyTemperature:number[];monthlyRain:number[];monthlyHumidity:number[];monthlyWind:number[]};
export type CountryProfile={id:string;name:string;continent:string;associationId?:string;hemisphere:Hemisphere;defaultClimate:WorldGeo['climate'];};
export type CityProfile=WorldGeo & {elevation:number;population:number;countryCode:string;normals:ClimateNormals};
export type DailyWeather={date:string;cityId:string;temperature:number;rain:number;humidity:number;wind:number;windDirection:number;condition:'clear'|'cloudy'|'lightRain'|'heavyRain'|'storm'|'snow'|'heat';pitchMoisture:'dry'|'damp'|'wet'|'waterlogged'};

const cityProfiles=new WeakMap<World,Map<string,CityProfile>>();
const countryProfiles=new WeakMap<World,Map<string,CountryProfile>>();
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function profiles(world:World){let c=cityProfiles.get(world);if(!c){c=new Map();cityProfiles.set(world,c)}let k=countryProfiles.get(world);if(!k){k=new Map();countryProfiles.set(world,k)}return{cities:c,countries:k}}
function month(date:string){return Math.max(0,Math.min(11,Number(date.slice(5,7))-1))}
function hemi(lat:number):Hemisphere{return Math.abs(lat)<8?'equatorial':lat>0?'north':'south'}
function seasonalSeries(base:number,amplitude:number,hemisphere:Hemisphere){return Array.from({length:12},(_,m)=>{const phase=(m/12)*Math.PI*2+(hemisphere==='south'?Math.PI:hemisphere==='equatorial'?Math.PI/2:0);return Number((base+Math.cos(phase)*amplitude).toFixed(1))})}
export function defaultClimateNormals(climate:WorldGeo['climate'],hemisphere:Hemisphere):ClimateNormals{const table={tropical:{temp:27,amp:3,rain:58,hum:78,wind:11},subtropical:{temp:21,amp:8,rain:42,hum:70,wind:13},temperate:{temp:14,amp:11,rain:36,hum:68,wind:14},continental:{temp:10,amp:18,rain:27,hum:61,wind:13},arid:{temp:25,amp:10,rain:8,hum:35,wind:15},polar:{temp:-5,amp:16,rain:18,hum:64,wind:20},highland:{temp:13,amp:7,rain:35,hum:62,wind:16}}[climate];const temperatures=seasonalSeries(table.temp,table.amp,hemisphere),rain=Array.from({length:12},(_,m)=>clamp(table.rain+(climate==='tropical'?Math.sin((m/12)*Math.PI*2+(hemisphere==='south'?0:Math.PI))*24:Math.sin((m/12)*Math.PI*2)*8),0,100));return{monthlyTemperature:temperatures,monthlyRain:rain.map(x=>Number(x.toFixed(1))),monthlyHumidity:Array.from({length:12},()=>table.hum),monthlyWind:Array.from({length:12},()=>table.wind)}}
export function registerCountryProfile(world:World,input:Omit<CountryProfile,'hemisphere'> & {hemisphere?:Hemisphere}){const p:CountryProfile={...input,hemisphere:input.hemisphere??'south'};profiles(world).countries.set(p.id,p);registerCountry(world,{id:p.id,name:p.name,continent:p.continent,associationId:p.associationId});return p}
export function registerCityProfile(world:World,input:Omit<CityProfile,'normals'|'countryCode'> & {countryCode?:string;normals?:ClimateNormals}){const hemisphere=hemi(input.latitude),p:CityProfile={...input,countryCode:input.countryCode??input.countryId,elevation:input.elevation??0,population:input.population??0,normals:input.normals??defaultClimateNormals(input.climate,hemisphere)};profiles(world).cities.set(p.cityId,p);registerCity(world,p);return p}
export function cityProfile(world:World,cityId:string){return profiles(world).cities.get(cityId)}
export function countryProfile(world:World,countryId:string){return profiles(world).countries.get(countryId)}
export function dailyWeatherFor(world:World,cityId:string,date:string):DailyWeather{const city=cityProfile(world,cityId);if(!city)throw new Error(`Unknown city ${cityId}`);const m=month(date),key=`${cityId}:${date}`,tempNoise=(deterministicRandom(world,'weather',`${key}:temp`)-.5)*7,rainRoll=deterministicRandom(world,'weather',`${key}:rain`),windNoise=(deterministicRandom(world,'weather',`${key}:wind`)-.5)*8,stormRoll=deterministicRandom(world,'weather',`${key}:storm`),temperature=Number((city.normals.monthlyTemperature[m]+tempNoise-city.elevation*.006).toFixed(1)),rainBase=city.normals.monthlyRain[m],rain=rainRoll<rainBase/100?clamp(rainBase*.65+deterministicRandom(world,'weather',`${key}:rainIntensity`)*50,5,100):0,humidity=clamp(city.normals.monthlyHumidity[m]+(rain>0?12:0)+(deterministicRandom(world,'weather',`${key}:humidity`)-.5)*14,15,100),wind=clamp(city.normals.monthlyWind[m]+windNoise+(stormRoll>.96?18:0),0,55),windDirection=deterministicRandom(world,'weather',`${key}:direction`)*Math.PI*2;let condition:DailyWeather['condition']='clear';if(temperature>=34)condition='heat';if(temperature<=1&&rain>0)condition='snow';else if(rain>=70||stormRoll>.97)condition='storm';else if(rain>=45)condition='heavyRain';else if(rain>0)condition='lightRain';else if(humidity>82)condition='cloudy';const pitchMoisture:DailyWeather['pitchMoisture']=rain>=80?'waterlogged':rain>=45?'wet':rain>0?'damp':'dry';return{date,cityId,temperature,rain:Number(rain.toFixed(1)),humidity:Number(humidity.toFixed(1)),wind:Number(wind.toFixed(1)),windDirection,condition,pitchMoisture}}
export function geographySnapshot(world:World){const p=profiles(world);return{countries:[...p.countries.values()].map(x=>({...x})),cities:[...p.cities.values()].map(x=>({...x,normals:{monthlyTemperature:[...x.normals.monthlyTemperature],monthlyRain:[...x.normals.monthlyRain],monthlyHumidity:[...x.normals.monthlyHumidity],monthlyWind:[...x.normals.monthlyWind]}}))}}
export function restoreGeography(world:World,s:{countries:CountryProfile[];cities:CityProfile[]}){countryProfiles.set(world,new Map());cityProfiles.set(world,new Map());for(const c of s.countries)registerCountryProfile(world,c);for(const c of s.cities)registerCityProfile(world,c)}
export function seedBrazilFoundation(world:World){if(countryProfile(world,'BRA'))return;registerCountryProfile(world,{id:'BRA',name:'Brasil',continent:'South America',associationId:'CBF',hemisphere:'south',defaultClimate:'tropical'});registerCityProfile(world,{countryId:'BRA',countryName:'Brasil',continent:'South America',cityId:'SAO',cityName:'São Paulo',latitude:-23.5505,longitude:-46.6333,timezone:'America/Sao_Paulo',climate:'subtropical',elevation:760,population:11450000});registerCityProfile(world,{countryId:'BRA',countryName:'Brasil',continent:'South America',cityId:'RIO',cityName:'Rio de Janeiro',latitude:-22.9068,longitude:-43.1729,timezone:'America/Sao_Paulo',climate:'tropical',elevation:11,population:6211000});registerCityProfile(world,{countryId:'BRA',countryName:'Brasil',continent:'South America',cityId:'CUI',cityName:'Cuiabá',latitude:-15.6014,longitude:-56.0979,timezone:'America/Cuiaba',climate:'tropical',elevation:165,population:650000});}
