import type { World } from './engine';
import { snapshotWorldCore, restoreWorldCore, type WorldCoreSnapshot } from './world-core-v2';
import { geographySnapshot, restoreGeography, type CountryProfile, type CityProfile } from './world-geography-climate-v2';
import { schedulerSnapshot, restoreScheduler, type ScheduledWorldEvent } from './world-event-scheduler-v2';
import { snapshotPlayerProfiles, restorePlayerProfiles, type PlayerProfileSnapshot } from './player-profile-v2';
import { snapshotPlayerLifecycle, restorePlayerLifecycle } from './player-lifecycle-v2';
import { snapshotTechnicalProfiles, restoreTechnicalProfiles, type TechnicalProfileSnapshot } from './player-technical-profile-v2';
import { snapshotPlayerBehavior, restorePlayerBehavior, type BehaviorSnapshot } from './player-behavior-v2';
import { snapshotPlayerMatchStates, restorePlayerMatchStates, type MatchStateSnapshot } from './player-match-state-v2';
import { snapshotScouting, restoreScouting, type ScoutingSnapshot } from './player-scouting-v2';
import { snapshotPartnerships, restorePartnerships, type PartnershipSnapshot } from './player-partnerships-v2';

export const WORLD_SAVE_SCHEMA_VERSION=5;
export type WorldFoundationSave={schemaVersion:number;createdAt:string;worldCore:WorldCoreSnapshot;geography:{countries:CountryProfile[];cities:CityProfile[]};scheduler:ScheduledWorldEvent[];players:PlayerProfileSnapshot;playerLifecycle:ReturnType<typeof snapshotPlayerLifecycle>;technicalProfiles:TechnicalProfileSnapshot;playerBehavior:BehaviorSnapshot;playerMatchStates:MatchStateSnapshot;scouting:ScoutingSnapshot;partnerships:PartnershipSnapshot;metadata:{gameVersion:string;notes?:string}};
export function snapshotWorldFoundation(world:World,metadata:Partial<WorldFoundationSave['metadata']>={}):WorldFoundationSave{return{schemaVersion:WORLD_SAVE_SCHEMA_VERSION,createdAt:new Date().toISOString(),worldCore:snapshotWorldCore(world),geography:geographySnapshot(world),scheduler:schedulerSnapshot(world),players:snapshotPlayerProfiles(world),playerLifecycle:snapshotPlayerLifecycle(world),technicalProfiles:snapshotTechnicalProfiles(world),playerBehavior:snapshotPlayerBehavior(world),playerMatchStates:snapshotPlayerMatchStates(world),scouting:snapshotScouting(world),partnerships:snapshotPartnerships(world),metadata:{gameVersion:metadata.gameVersion??'0.1.0',notes:metadata.notes}}}
function migrateV1toV2(input:any){return{schemaVersion:2,createdAt:input.createdAt??new Date(0).toISOString(),worldCore:{...input.worldCore,schemaVersion:Math.max(1,input.worldCore?.schemaVersion??1)},geography:input.geography??{countries:[],cities:[]},scheduler:input.scheduler??[],metadata:{gameVersion:input.metadata?.gameVersion??'0.1.0',notes:input.metadata?.notes}}}
function migrateV2toV3(input:any){return{...input,schemaVersion:3,players:input.players??{profiles:[]},playerLifecycle:input.playerLifecycle??{retired:[],processed:[]}}}
function migrateV3toV4(input:any){return{...input,schemaVersion:4,technicalProfiles:input.technicalProfiles??{profiles:[]}}}
function migrateV4toV5(input:any):WorldFoundationSave{return{...input,schemaVersion:5,playerBehavior:input.playerBehavior??{players:[]},playerMatchStates:input.playerMatchStates??{players:[]},scouting:input.scouting??{entries:[]},partnerships:input.partnerships??{pairs:[]}} as WorldFoundationSave}
export function migrateWorldFoundationSave(input:any):WorldFoundationSave{let x=input;if(!x||typeof x!=='object')throw new Error('Invalid world save payload');let v=Number(x.schemaVersion??1);if(v>WORLD_SAVE_SCHEMA_VERSION)throw new Error(`Save schema ${v} is newer than supported ${WORLD_SAVE_SCHEMA_VERSION}`);if(v===1){x=migrateV1toV2(x);v=2}if(v===2){x=migrateV2toV3(x);v=3}if(v===3){x=migrateV3toV4(x);v=4}if(v===4){x=migrateV4toV5(x);v=5}if(v!==WORLD_SAVE_SCHEMA_VERSION)throw new Error(`Unsupported migrated schema ${v}`);return x as WorldFoundationSave}
export function restoreWorldFoundation(world:World,input:any){const save=migrateWorldFoundationSave(input);restoreWorldCore(world,save.worldCore);restoreGeography(world,save.geography);restoreScheduler(world,save.scheduler);restorePlayerProfiles(world,save.players);restorePlayerLifecycle(world,save.playerLifecycle);restoreTechnicalProfiles(world,save.technicalProfiles);restorePlayerBehavior(world,save.playerBehavior);restorePlayerMatchStates(world,save.playerMatchStates);restoreScouting(world,save.scouting);restorePartnerships(world,save.partnerships);return save}
export function validateWorldFoundationSave(input:any){const issues:string[]=[];let save:WorldFoundationSave;try{save=migrateWorldFoundationSave(input)}catch(e:any){return{ok:false,issues:[e?.message??String(e)]}}if(!save.worldCore?.worldId)issues.push('worldId ausente');if(!/^\d{4}-\d{2}-\d{2}$/.test(save.worldCore.date))issues.push('data mundial inválida');if(!Array.isArray(save.geography?.countries)||!Array.isArray(save.geography?.cities))issues.push('geografia inválida');if(!Array.isArray(save.scheduler))issues.push('fila agendada inválida');if(!Array.isArray(save.players?.profiles))issues.push('perfis de jogadores inválidos');if(!Array.isArray(save.playerLifecycle?.retired)||!Array.isArray(save.playerLifecycle?.processed))issues.push('lifecycle de jogadores inválido');if(!Array.isArray(save.technicalProfiles?.profiles))issues.push('perfis técnicos detalhados inválidos');if(!Array.isArray(save.playerBehavior?.players))issues.push('behavior profiles inválidos');if(!Array.isArray(save.playerMatchStates?.players))issues.push('match states inválidos');if(!Array.isArray(save.scouting?.entries))issues.push('scouting inválido');if(!Array.isArray(save.partnerships?.pairs))issues.push('partnerships inválidos');const duplicateScheduled=new Set<string>();for(const e of save.scheduler){if(duplicateScheduled.has(e.id))issues.push(`evento agendado duplicado: ${e.id}`);duplicateScheduled.add(e.id)}const playerIds=new Set<string>();for(const [id,p] of save.players.profiles){if(playerIds.has(id))issues.push(`perfil de jogador duplicado: ${id}`);playerIds.add(id);if(p.potential.floor>p.potential.ceiling)issues.push(`faixa de potencial inválida: ${id}`)}const technicalIds=new Set<string>();for(const [id,t] of save.technicalProfiles.profiles){if(technicalIds.has(id))issues.push(`perfil técnico duplicado: ${id}`);technicalIds.add(id);for(const [k,v] of Object.entries(t.attributes))if(typeof v!=='number'||v<1||v>99)issues.push(`atributo técnico inválido: ${id}:${k}`)}return{ok:issues.length===0,issues,schemaVersion:save.schemaVersion,worldId:save.worldCore.worldId,date:save.worldCore.date,playerProfiles:save.players.profiles.length,technicalProfiles:save.technicalProfiles.profiles.length,behaviorProfiles:save.playerBehavior.players.length,matchStates:save.playerMatchStates.players.length,scoutingEntries:save.scouting.entries.length,partnerships:save.partnerships.pairs.length,retiredPlayers:save.playerLifecycle.retired.length}}
