import { createWorld, type World } from './engine';
import { seedFootballGovernanceFoundation } from './world-football-foundation-v1';
import { OPENFOOTBALL_SOURCES, linkDomesticPyramid, parseOpenFootballClubs, parseOpenFootballLeagues, parseOpenFootballStadiums } from './openfootball-importer-v1';
import { domesticPyramid, footballDataSnapshot, resolveFootballEntity, validateFootballData } from './world-football-data-v1';
import { snapshotWorldFoundation, validateWorldFoundationSave } from './world-save-schema-v2';

const leagues=`= Brazil =\n\n1       Brasileiro Série A\n | Campeonato Brasileiro Série A\n | br.a\n2       Brasileiro Série B\n | Campeonato Brasileiro Série B\n | br.b\n3       Brasileiro Série C\n4       Brasileiro Série D\ncup      Copa do Brasil\n | Brazil Cup\nsp       Campeonato Paulista\n | Paulistão\n`;
const clubs=`= Brazil\n== São Paulo ==\nPalmeiras SP, São Paulo\n | Palmeiras | SE Palmeiras | Sociedade Esportiva Palmeiras\nCorinthians SP, São Paulo\n | Corinthians | Sport Club Corinthians Paulista\nRB Bragantino, 2019, Bragança Paulista\n | Red Bull Bragantino\n`;
const stadiums=`= Brazil\n== São Paulo ==\n$Allianz$ Parque, 43_713, São Paulo\n | Arena Palestra Itália | Arena Palmeiras\n# club: Palmeiras\n$Neo Química$ Arena, 68_000, São Paulo\n | Arena Corinthians\n# club: Corinthians\n`;
export type FootballDataDiagnostic={ok:boolean;score:number;checks:Record<string,boolean>;issues:string[];counts:ReturnType<typeof validateFootballData>['counts']};
export function diagnoseWorldFootballDataV1(world:World=createWorld()):FootballDataDiagnostic{const checks:Record<string,boolean>={},issues:string[]=[];seedFootballGovernanceFoundation(world);const l=parseOpenFootballLeagues(world,leagues,OPENFOOTBALL_SOURCES.leaguesBrazil),c=parseOpenFootballClubs(world,clubs,OPENFOOTBALL_SOURCES.clubsBrazil),s=parseOpenFootballStadiums(world,stadiums,OPENFOOTBALL_SOURCES.stadiumsBrazil);linkDomesticPyramid(world,l.entityIds);const pyramid=domesticPyramid(world,'BRA');checks.fourDivisions=pyramid.length>=4&&pyramid.slice(0,4).every((x,i)=>x.level===i+1);checks.clubAliases=resolveFootballEntity(world,'Sociedade Esportiva Palmeiras').some(id=>id.includes('palmeiras'));checks.stadiumCapacity=footballDataSnapshot(world).stadiums.some(x=>x.capacity===43713);checks.governance=footballDataSnapshot(world).associations.some(x=>x.id==='CBF')&&footballDataSnapshot(world).confederations.some(x=>x.id==='CONMEBOL');checks.importVolume=l.created>=6&&c.created===3&&s.created===2;const valid=validateFootballData(world);checks.invariants=valid.ok;const save=snapshotWorldFoundation(world),saveValid=validateWorldFoundationSave(save);checks.saveV6=save.schemaVersion>=6&&saveValid.ok&&save.footballData.clubs.length===3;for(const [k,v] of Object.entries(checks))if(!v)issues.push(k);const score=Math.round(Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100);return{ok:issues.length===0,score,checks,issues,counts:valid.counts}}
