import type { World } from './engine';

export type WorldCadence='daily'|'weekly'|'monthly'|'yearly';
export type WorldGeo={countryId:string;countryName:string;continent:string;cityId:string;cityName:string;latitude:number;longitude:number;timezone:string;climate:'tropical'|'subtropical'|'temperate'|'continental'|'arid'|'polar'|'highland'};
export type WorldEvent={id:string;date:string;type:string;scope:'world'|'country'|'city'|'club'|'person'|'competition';entityIds:string[];importance:number;payload:Record<string,unknown>};
export type RNGStreamName='world'|'players'|'transfers'|'matches'|'media'|'humanLife'|'finance'|'weather'|'youth'|'competitions'|'person-v3'|'football-school';
export type WorldCoreState={schemaVersion:number;worldId:string;seed:number;date:string;season:number;dayIndex:number;countries:Map<string,{id:string;name:string;continent:string;associationId?:string}>;cities:Map<string,WorldGeo>;events:WorldEvent[];streamCounters:Record<RNGStreamName,number>;lastCadence:{weekly?:string;monthly?:string;yearly?:string}};
export type WorldCoreSnapshot=Omit<WorldCoreState,'countries'|'cities'> & {countries:[string,{id:string;name:string;continent:string;associationId?:string}][];cities:[string,WorldGeo][]};
const states=new WeakMap<World,WorldCoreState>();
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function defaultDate(world:World){return `${world.season}-07-25`}
export function worldCore(world:World,seed?:number){let s=states.get(world);if(!s){const d=defaultDate(world),base=seed??hash(`football-project:${world.season}:${world.clubs.map(c=>c.id).join('|')}`);s={schemaVersion:1,worldId:`world-${base.toString(36)}`,seed:base,date:d,season:world.season,dayIndex:0,countries:new Map(),cities:new Map(),events:[],streamCounters:{world:0,players:0,transfers:0,matches:0,media:0,humanLife:0,finance:0,weather:0,youth:0,competitions:0,'person-v3':0,'football-school':0},lastCadence:{}};states.set(world,s)}return s}
function mulberry32(a:number){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
export function worldRandom(world:World,stream:RNGStreamName,tag=''){const s=worldCore(world),counter=s.streamCounters[stream]++,seed=(s.seed^hash(`${stream}:${tag}:${counter}`))>>>0;return mulberry32(seed)()}
export function deterministicRandom(world:World,stream:RNGStreamName,stableKey:string){const s=worldCore(world);return mulberry32((s.seed^hash(`${stream}:${stableKey}`))>>>0)()}
export function registerCountry(world:World,c:{id:string;name:string;continent:string;associationId?:string}){worldCore(world).countries.set(c.id,{...c})}
export function registerCity(world:World,g:WorldGeo){worldCore(world).cities.set(g.cityId,{...g})}
export function queueWorldEvent(world:World,e:Omit<WorldEvent,'id'>){const s=worldCore(world),id=`we-${hash(`${e.date}:${e.type}:${e.scope}:${e.entityIds.join(',')}:${s.events.length}`).toString(36)}`;s.events.push({id,...e});s.events.sort((a,b)=>a.date.localeCompare(b.date)||b.importance-a.importance||a.id.localeCompare(b.id));if(s.events.length>50000)s.events.splice(0,s.events.length-50000);return id}
export function worldEvents(world:World,filter:{from?:string;to?:string;type?:string;scope?:WorldEvent['scope'];entityId?:string}={}){return worldCore(world).events.filter(e=>(!filter.from||e.date>=filter.from)&&(!filter.to||e.date<=filter.to)&&(!filter.type||e.type===filter.type)&&(!filter.scope||e.scope===filter.scope)&&(!filter.entityId||e.entityIds.includes(filter.entityId)))}
export function syncWorldDate(world:World,date:string){const s=worldCore(world),previous=s.date;s.date=date;s.season=world.season;s.dayIndex+=date===previous?0:1;const weekly=new Date(`${date}T12:00:00Z`).getUTCDay()===1,monthly=date.slice(8,10)==='01',yearly=date.slice(5)==='01-01',cadences:WorldCadence[]=['daily'];if(weekly&&s.lastCadence.weekly!==date){cadences.push('weekly');s.lastCadence.weekly=date}if(monthly&&s.lastCadence.monthly!==date){cadences.push('monthly');s.lastCadence.monthly=date}if(yearly&&s.lastCadence.yearly!==date){cadences.push('yearly');s.lastCadence.yearly=date}return{previous,date,cadences}}
export function snapshotWorldCore(world:World):WorldCoreSnapshot{const s=worldCore(world);return{...s,countries:[...s.countries.entries()].map(([k,v])=>[k,{...v}]),cities:[...s.cities.entries()].map(([k,v])=>[k,{...v}]),events:s.events.map(e=>({...e,entityIds:[...e.entityIds],payload:{...e.payload}})),streamCounters:{...s.streamCounters},lastCadence:{...s.lastCadence}}}
export function restoreWorldCore(world:World,x:WorldCoreSnapshot){const counters={...x.streamCounters,'person-v3':x.streamCounters?.['person-v3']??0,'football-school':x.streamCounters?.['football-school']??0} as Record<RNGStreamName,number>;states.set(world,{...x,countries:new Map(x.countries.map(([k,v])=>[k,{...v}])),cities:new Map(x.cities.map(([k,v])=>[k,{...v}])),events:x.events.map(e=>({...e,entityIds:[...e.entityIds],payload:{...e.payload}})),streamCounters:counters,lastCadence:{...x.lastCadence}})}
export function validateWorldCore(world:World){const s=worldCore(world),issues:string[]=[];if(s.schemaVersion<1)issues.push('Schema version inválida.');if(!/^\d{4}-\d{2}-\d{2}$/.test(s.date))issues.push('Data mundial inválida.');if(!Number.isFinite(s.seed))issues.push('Seed mundial inválida.');if(s.events.some((e,i,a)=>i>0&&a[i-1].date>e.date))issues.push('Fila de eventos fora de ordem.');if(s.season!==world.season)issues.push('Temporada do World Core diverge do World.');return{ok:issues.length===0,issues,date:s.date,season:s.season,worldId:s.worldId,events:s.events.length}}
