import type { World } from './engine';
import { importOpenFootballTournament, type TournamentImportResult } from './openfootball-tournament-importer-v1';
import type { OpenFootballSource } from './openfootball-importer-v1';

export type HistoricalTournamentSource={repo:string;path:string;competitionId:string;season:string;teamKind:'club'|'national'};
export type FootballHistoryBootstrapReport={loaded:string[];missing:string[];imports:TournamentImportResult[];warnings:string[]};
const urlFor=(s:HistoricalTournamentSource)=>`/data/openfootball/${s.repo.replace('/','__')}/${s.path}`;
async function loadText(s:HistoricalTournamentSource){const r=await fetch(urlFor(s));if(!r.ok)return;return await r.text()}
const source=(x:HistoricalTournamentSource):OpenFootballSource=>({id:`history-${x.repo.replace('/','-')}-${x.path.replace(/[^a-z0-9]+/gi,'-')}`,repo:x.repo,path:x.path,kind:'matches',license:'CC0-1.0',historical:true});
export function internationalHistorySources():HistoricalTournamentSource[]{const out:HistoricalTournamentSource[]=[];
for(let y=2011;y<=2024;y++){const season=`${y}-${String((y+1)%100).padStart(2,'0')}`;out.push({repo:'openfootball/champions-league',path:`${season}/cl.txt`,competitionId:'comp-uefa-cl',season,teamKind:'club'},{repo:'openfootball/champions-league',path:`${season}/el.txt`,competitionId:'comp-uefa-el',season,teamKind:'club'});if(y>=2021)out.push({repo:'openfootball/champions-league',path:`${season}/conf.txt`,competitionId:'comp-uefa-conf',season,teamKind:'club'})}
for(let y=2012;y<=2024;y++){out.push({repo:'openfootball/south-america',path:`copa-libertadores/${y}_copal.txt`,competitionId:'comp-conmebol-libertadores',season:String(y),teamKind:'club'});out.push({repo:'openfootball/south-america',path:`copa-libertadores/${y}_copas.txt`,competitionId:'comp-conmebol-sudamericana',season:String(y),teamKind:'club'})}
const wcs=[['1930--uruguay','1930'],['1934--italy','1934'],['1938--france','1938'],['1950--brazil','1950'],['1954--switzerland','1954'],['1958--sweden','1958'],['1962--chile','1962'],['1966--england','1966'],['1970--mexico','1970'],['1974--west_germany','1974'],['1978--argentina','1978'],['1982--spain','1982'],['1986--mexico','1986'],['1990--italy','1990'],['1994--usa','1994'],['1998--france','1998'],['2002--south-korea-n-japan','2002'],['2006--germany','2006'],['2010--south-africa','2010'],['2014--brazil','2014'],['2018--russia','2018'],['2022--qatar','2022']] as const;for(const [folder,season] of wcs)out.push({repo:'openfootball/worldcup',path:`${folder}/cup_finals.txt`,competitionId:'comp-fifa-world-cup',season,teamKind:'national'});
const euros=[['1960--france','1960'],['1964--spain','1964'],['1968--italy','1968'],['1972--belgium','1972'],['1976--yugoslavia','1976'],['1980--italy','1980'],['1984--france','1984'],['1988--west-germany','1988'],['1992--sweden','1992'],['1996--england','1996'],['2000--belgium-netherlands','2000'],['2004--portugal','2004'],['2008--austria-switzerland','2008'],['2012--poland-ukraine','2012'],['2016--france','2016'],['2021--europe','2021'],['2024--germany','2024']] as const;for(const [folder,season] of euros)out.push({repo:'openfootball/euro',path:`${folder}/euro.txt`,competitionId:'comp-uefa-euro',season,teamKind:'national'});
for(const [folder,season] of [['2011--argentina','2011'],['2021--brazil','2021'],['2024--usa','2024']] as const)out.push({repo:'openfootball/copa-america',path:`${folder}/copa.txt`,competitionId:'comp-conmebol-copa-america',season,teamKind:'national'});return out}
export async function bootstrapInternationalFootballHistory(world:World,filter?:{fromYear?:number;toYear?:number;competitions?:string[]}):Promise<FootballHistoryBootstrapReport>{const loaded:string[]=[],missing:string[]=[],imports:TournamentImportResult[]=[],warnings:string[]=[];for(const s of internationalHistorySources()){const year=Number(s.season.slice(0,4));if(filter?.fromYear&&year<filter.fromYear)continue;if(filter?.toYear&&year>filter.toYear)continue;if(filter?.competitions&&!filter.competitions.includes(s.competitionId))continue;const text=await loadText(s);if(text===undefined){missing.push(`${s.repo}/${s.path}`);continue}loaded.push(`${s.repo}/${s.path}`);const result=importOpenFootballTournament(world,text,{source:source(s),competitionId:s.competitionId,season:s.season,teamKind:s.teamKind});imports.push(result);if(result.unresolvedTeams.length)warnings.push(`${s.competitionId} ${s.season}: ${result.unresolvedTeams.length} equipes não resolvidas (${result.unresolvedTeams.slice(0,6).join(', ')})`)}return{loaded,missing,imports,warnings}}
