import type { World } from './engine';
import { snapshotWorldCore, restoreWorldCore, type WorldCoreSnapshot } from './world-core-v2';
import { geographySnapshot, restoreGeography, type CountryProfile, type CityProfile } from './world-geography-climate-v2';
import { schedulerSnapshot, restoreScheduler, type ScheduledWorldEvent } from './world-event-scheduler-v2';
import { snapshotPlayerProfiles, restorePlayerProfiles, type PlayerProfileSnapshot } from './player-profile-v2';
import { snapshotPlayerLifecycle, restorePlayerLifecycle } from './player-lifecycle-v2';

export const WORLD_SAVE_SCHEMA_VERSION=3;
export type WorldFoundationSave={schemaVersion:number;createdAt:string;worldCore:WorldCoreSnapshot;geography:{countries:CountryProfile[];cities:CityProfile[]};scheduler:ScheduledWorldEvent[];players:PlayerProfileSnapshot;playerLifecycle:ReturnType<typeof snapshotPlayerLifecycle>;metadata:{gameVersion:string;notes?:string}};
export function snapshotWorldFoundation(world:World,metadata:Partial<WorldFoundationSave['metadata']>={}):WorldFoundationSave{return{schemaVersion:WORLD_SAVE_SCHEMA_VERSION,createdAt:new Date().toISOString(),worldCore:snapshotWorldCore(world),geography:geographySnapshot(world),scheduler:schedulerSnapshot(world),players:snapshotPlayerProfiles(world),playerLifecycle:snapshotPlayerLifecycle(world),metadata:{gameVersion:metadata.gameVersion??'0.1.0',notes:metadata.notes}}}
function migrateV1toV2(input:any){return{schemaVersion:2,createdAt:input.createdAt??new Date(0).toISOString(),worldCore:{...input.worldCore,schemaVersion:Math.max(1,input.worldCore?.schemaVersion??1)},geography:input.geography??{countries:[],cities:[]},scheduler:input.scheduler??[],metadata:{gameVersion:input.metadata?.gameVersion??'0.1.0',notes:input.metadata?.notes}}}
function migrateV2toV3(input:any):WorldFoundationSave{return{...input,schemaVersion:3,players:input.players??{profiles:[]},playerLifecycle:input.playerLifecycle??{retired:[],processed:[]}} as WorldFoundationSave}
export function migrateWorldFoundationSave(input:any):WorldFoundationSave{let x=input;if(!x||typeof x!=='object')throw new Error('Invalid world save payload');let v=Number(x.schemaVersion??1);if(v>WORLD_SAVE_SCHEMA_VERSION)throw new Error(`Save schema ${v} is newer than supported ${WORLD_SAVE_SCHEMA_VERSION}`);if(v===1){x=migrateV1toV2(x);v=2}if(v===2){x=migrateV2toV3(x);v=3}if(v!==WORLD_SAVE_SCHEMA_VERSION)throw new Error(`Unsupported migrated schema ${v}`);return x as WorldFoundationSave}
export function restoreWorldFoundation(world:World,input:any){const save=migrateWorldFoundationSave(input);restoreWorldCore(world,save.worldCore);restoreGeography(world,save.geography);restoreScheduler(world,save.scheduler);restorePlayerProfiles(world,save.players);restorePlayerLifecycle(world,save.playerLifecycle);return save}
export function validateWorldFoundationSave(input:any){const issues:string[]=[];let save:WorldFoundationSave;try{save=migrateWorldFoundationSave(input)}catch(e:any){return{ok:false,issues:[e?.message??String(e)]}}if(!save.worldCore?.worldId)issues.push('worldId ausente');if(!/^\d{4}-\d{2}-\d{2}$/.test(save.worldCore.date))issues.push('data mundial inválida');if(!Array.isArray(save.geography?.countries)||!Array.isArray(save.geography?.cities))issues.push('geografia inválida');if(!Array.isArray(save.scheduler))issues.push('fila agendada inválida');if(!Array.isArray(save.players?.profiles))issues.push('perfis de jogadores inválidos');if(!Array.isArray(save.playerLifecycle?.retired)||!Array.isArray(save.playerLifecycle?.processed))issues.push('lifecycle de jogadores inválido');const duplicateScheduled=new Set<string>();for(const e of save.scheduler){if(duplicateScheduled.has(e.id))issues.push(`evento agendado duplicado: ${e.id}`);duplicateScheduled.add(e.id)}const playerIds=new Set<string>();for(const [id,p] of save.players.profiles){if(playerIds.has(id))issues.push(`perfil de jogador duplicado: ${id}`);playerIds.add(id);if(p.potential.floor>p.potential.ceiling)issues.push(`faixa de potencial inválida: ${id}`)}return{ok:issues.length===0,issues,schemaVersion:save.schemaVersion,worldId:save.worldCore.worldId,date:save.worldCore.date,playerProfiles:save.players.profiles.length,retiredPlayers:save.playerLifecycle.retired.length}}
